### ISSUE TITLE
Use-def chain of a binary

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#10]
I want to extract use-def chain of memory addresses from a binary. angr uses VEX IR which is in SSA form, so extracting use-def chain shouldn't be hard. How can I do this? Any pointer is appreciated.

I would be happy to contribute back.

**Comment by ltfish** [comment]
Extracting use-def chains is definitely not difficult. In fact, I was doing something like that in `DDG` class - although the code was very messy (that was when I first learn how to program in Python).

In general, all you need to do is the following:
- Generate a CFG with `keep_input_states = True`. We'll need those states later on.
- Iterate through the graph, and for each basic block, process actions in each state (they are stored in `state.log.actions`). Those actions are ordered.
- Each statement also stores their corresponding actions. Youi may also iterate through statements first, grab their actions, and process them.
`ddg.py` is a good example of how to build a use-def chain (not a good example of writing clean code though).

However, there is another problem. CFG is neither complete nor sound, and the states you get in building a CFG can be very far away from the runtime states (or _ideal states_) sometimes. This problem can be eliminated by generating a def-use chain on a single symbolic `Path` (the path you generated from a symbolic execution in `angr`). You should pick `CFG` or symbolic execution based on your needs.

In near future, the `VFG` should also support actions, and the def-use chain generated from a `VFG` will make more sense.

**Comment by kereoz** [comment]
@riyadparvez : to complement @ltfish 's answer, we currently provide two implementations of DDG (Data Dependence Graphs) in Angr: one of them relies on the states computed by the CFG (the analysis is mostly static, meaning that most expressions are not evaluated), and the other one does it on top of the value flow graph (VFG), which is an augmented form of CFG based on VSA[1].

Both these implementations compute def-use chains, and the code is located in analysis/ddg.py and analysis/vsa_ddg.py respectively.

[1] https://research.cs.wisc.edu/wpis/papers/balakrishnan_thesis.pdf

**Comment by riyadparvez** [comment]
Thanks for taking the time to reply :).

On Thu, Aug 20, 2015 at 4:39 PM, ltfish <notifications@github.com> wrote:

> Extracting use-def chains is definitely not difficult. In fact, I was
> doing something like that in DDG class - although the code was very messy
> (that was when I first learn how to program in Python).
>
> In general, all you need to do is the following:
>
>    - Generate a CFG with keep_input_states = True. We'll need those
>    states later on.
>    - Iterate through the graph, and for each basic block, process actions
>    in each state (they are stored in state.log.actions). Those actions
>    are ordered.
>    - Each statement also stores their corresponding actions. Youi may
>    also iterate through statements first, grab their actions, and process
>    them. ddg.py is a good example of how to build a use-def chain (not a
>    good example of writing clean code though).
>
> However, there is another problem. CFG is neither complete nor sound,
>

CFG is incomplete since statically extracting CFG is undecidable, is there
any reason why the CFG is not sound? Is it because you synthesize the
context during execution of basic blocks?

and the states you get in building a CFG can be very far away from the
> runtime states (or *ideal states*) sometimes.
>

I presume in here, by 'the states' you mean 'synthesized states' by the
analysis.


> This problem can be eliminated by generating a def-use chain on a single
> symbolic Path (the path you generated from a symbolic execution in angr).
> You should pick CFG or symbolic execution based on your needs.
>

I believe, the def-use chain on a single path would be highly
under-approximated.


> In near future, the VFG should also support actions, and the def-use
> chain generated from a VFG will make more sense.
>

Can you elaborate on VFG? From the doc comments in the source, I see: `This
class represents a control-flow graph with static analysis result.` How
it's different than the CFG analysis? I presume, in the CFG analysis you
execute the basic blocks creating contexts and in VFG analysis, you don't.

Also what's Value Flow Graph? It's not a very popular term in literature,

**Comment by ltfish** [comment]
The unsoundness of our recovered CFG is resulted from the following:
- Our implementation is not fully flow sensitive. Consider the following code snippet (where `func` is a function pointer):
```
func = 0xbadf00d;
if (always_return_1())
{
    func = printf;
}
func("Hello, world!\n");
```
In this case, `func` should always point to `printf` in reality. But since our implementation is not fully flow sensitive, depending on the order of analysis, `func` may point to either `0xbadf00d` or `printf`. Obviously one of them is incorrect.
- Some of our assumptions are unsound. For example, we are assuming a call will always return to the next instruction after the call instruction if it ever returns, which is not necessarily true.

The flight is landing... will continue later.

**Comment by ltfish** [comment]
Finally got Internet access before boarding my next flight.

The `VFG` is indeed a self-made term. It stands for _Value Flow Graph_, which encodes the analysis result from Value-Set Analysis (a type of static analysis that `angr` does, usually referred to as `VSA`) into a graph and link those states together according to the corresponding CFG. VSA yields a better analysis result than CFG for many reasons, and you may want to check it out from other papers if you have never heard of it before.

Note that in theory VSA is a sound approximation (or in another term, a sound analysis), but it is not sound in our implementation for various reasons, mostly for performance concerns. Feel free to make it sound if that is important to you, but soundness is not in our plan for now.

**Comment by ltfish** [comment]
And about the def-use chain, I'm currently working on something similar, but I cannot tell you for sure when it will be ready for release. Just don't yell at me if def-use chain support suddenly appears in the repo one day :-)

**Comment by riyadparvez** [comment]
I understand what you meant by unsound, I had different definition of unsoundness in mind.

I've tried to use VFG analysis. But I'm only seeing one node and no edges, whereas in CFG analysis, I see ~2500 nodes and 4200 edges. Any idea why this is happening?
I've tried the CFG analysis, the result I've got is pretty good. It would be great if you can update the documentation of VFG analysis.

About the def-use chain, seems like you've got yourself into a competition. 

Have a safe flight. Thanks for a nice set of tools.

**Comment by rhelmot** [comment]
Don't worry, it's an in-joke in our lab that @ltfish is the only one who has any idea how to use the VFG whatsoever :smile:

So yes, we do need documentation for the VFG analysis.

**Comment by kereoz** [comment]
@riyadparvez : what options did you give to VFG ?
You might want to adjust the size of the call stack. By default, interfunction_level is 0, which means that only the current function is being analyzed. This is probably not what you want.

**Comment by riyadparvez** [comment]
@kereoz I've tried with simple `vfg = b.analyses.VFG(cfg)`.

I've tried `vfg = b.analyses.VFG(cfg, interfunction_level=3)`; but this is the error message I'm seeing repeatedly: `valueset.reverse is not properly implemented `.

**Comment by ltfish** [comment]
- VFG should work. In fact I'm intensively using it myself right now. More documentation about VFG is definitely in my plan. But for now, I'm happy make it work for you first.
- `valueset.reverse is not properly implemented` was not an error message - it was a TODO entry for myself. My bad. It will go away in the next release.

**Comment by ronnychevalier** [comment]
On Thu, Aug 20, 2015 at 11:46 PM, ltfish <notifications@github.com> wrote:

> The unsoundness of our recovered CFG is resulted from the following:
>
>    - Our implementation is not fully flow sensitive. Consider the
>    following code snippet (where func is a function pointer):
>
> func = 0xbadf00d;
> if (always_return_1())
> {
>     func = printf;
> }
> func("Hello, world!\n");
>
> In this case, func should always point to printf in reality. But since
> our implementation is not fully flow sensitive, depending on the order of
> analysis, func may point to either 0xbadf00d or printf. Obviously one of
> them is incorrect.
>

 I will probably need to work on this later on. After adding the x86
segmentation and real mode, I noticed this issue which make my analysis
fail for a BIOS I was analyzing.

**Comment by ltfish** [comment]
@ronnychevalier Point-to analysis might be required to make it work well. What do you think?

**Comment by ronnychevalier** [comment]
On Fri, Aug 21, 2015 at 9:33 AM, ltfish <notifications@github.com> wrote:

> @ronnychevalier <https://github.com/ronnychevalier> Point-to analysis
> might be required to make it work well. What do you think?
>

Yeah it seems to be a good idea, I'm looking into this paper
https://www.cs.utexas.edu/users/lin/papers/cgo11.pdf right now.

**Comment by ltfish** [comment]
@ronnychevalier That paper is in my TODO list! I'll be very happy if you can implement that paper for angr :-)

**Comment by ronnychevalier** [comment]
On Fri, Aug 21, 2015 at 10:00 AM, ltfish <notifications@github.com> wrote:

> @ronnychevalier <https://github.com/ronnychevalier> That paper is in my
> TODO list! I'll be very happy if you can implement that paper for angr :-)
>

If it happens, it will not be any time soon I'm afraid. But it will help me
to know a little bit more about the innards of angr :)

**Comment by riyadparvez** [comment]
On Thu, Aug 20, 2015 at 10:33 PM, Christophe <notifications@github.com>
wrote:

> @riyadparvez <https://github.com/riyadparvez> : what options did you give
> to VFG ?
>

I've tried with 'vfg = b.analyses.VFG(cfg)'.


> You might want to adjust the size of the call stack. By default,
> interfunction_level is 0, which means that only the current function is
> being analyzed. This is probably not what you want.
>

I've tried with 'vfg = b.analyses.VFG(cfg, interfunction_level=1000)'. Now
I see ~25 nodes and ~30 edges.

Does 'interfunction_level' means the analysis will go into depth 1000 of
the call graph from the entry function?

**Comment by ltfish** [comment]
> Does 'interfunction_level' means the analysis will go into depth 1000 of
> the call graph from the entry function?

Correct. If `interfunction_level` is less than the maximum call depth (suppose it's **alpha**) of the target function on which you are creating the VFG, we will assume all calls at call depth **alpha** return to their call-site with a return value of TOP.

**Comment by riyadparvez** [comment]
On Fri, Aug 21, 2015 at 11:18 AM, ltfish <notifications@github.com> wrote:

> Does 'interfunction_level' means the analysis will go into depth 1000 of
> the call graph from the entry function?
>
> Correct. If interfunction_level is less than the maximum call depth
> (suppose it's *alpha*) of the target function on which you are creating
> the VFG, we will assume all calls at call depth *alpha* return to their
> call-site with a return value of TOP.
>
>
Is there any way to invoke with the depth of the call graph? I'm seeing ~25
nodes and ~30 edges with interfunction_level = 1000. Is there anything I
can do to find more blocks and edges?

**Comment by ltfish** [comment]
If there are blocks missing, I believe there is some sort of bug. Do you mind show me your test binary and your Python script to generate the VFG?

**Comment by riyadparvez** [comment]
I've tried with `mkdir` binary in Ubuntu 14.04. Here's the script:

```
import angr

b = angr.Project('/bin/mkdir')
cfg = b.analyses.CFG()
vfg = b.analyses.VFG(cfg, interfunction_level=1000)
print len(vfg.results['graph'].nodes())
print len(vfg.results['graph'].edges())
```

**Comment by riyadparvez** [comment]
On Thu, Aug 20, 2015 at 4:39 PM, ltfish <notifications@github.com> wrote:

> Extracting use-def chains is definitely not difficult. In fact, I was
> doing something like that in DDG class - although the code was very messy
> (that was when I first learn how to program in Python).
>
> In general, all you need to do is the following:
>
>    - Generate a CFG with keep_input_states = True. We'll need those
>    states later on.
>    - Iterate through the graph, and for each basic block, process actions
>    in each state (they are stored in state.log.actions). Those actions
>    are ordered.
>    - Each statement also stores their corresponding actions. Youi may
>    also iterate through statements first, grab their actions, and process
>    them. ddg.py is a good example of how to build a use-def chain (not a
>    good example of writing clean code though).
>
>
How can I access the statements of a basic block? I've looked into
`CFGNode` and state object in the `CFGNode`, none of them saves the
statements of the BB.

**Comment by ltfish** [comment]
All you need is to get a `SimIRSB` instance, and then access the `irsb` property of it.

Two ways:
- If you already have a `CFGNode`, and you have input states for it (`keep_input_states=True` was specified when building the `CFG`), then `irsb = cfg._get_irsb(cfg_node).irsb` gives you a reference to the basic block (`IRSB` is how VEX names it).
- Getting the `IRSB` (not the `SimIRSB`, which is essentially `IRSB` plus an initial state) does not necessarily mean you must have the initial state. So the following lines are easier:
```
block = proj.factory.block(<address>)
irsb = block.vex
irsb.pp() # For pretty printing
```
where `proj` is a reference to your angr project.

Moreover, the `Block` object has more power than just yielding an `IRSB`. Simply try `block.capstone.pp()`. @rhelmot designed the `Block` interface, which I really like :-)

**Comment by riyadparvez** [comment]
I've tried setting log level to debug, but the output I'm seeing still the
'valueset.reverse is not properly implemented'

The binary is uploaded at:
https://drive.google.com/file/d/0B5jqCZluyyOPY0tUWEwwYV9EdGM/view?usp=sharing

**Comment by ltfish** [comment]
`valueset.reverse is not properly implemented` is not an error message. It will go away in the next release, absolutely. You can just ignore it for now.

**Comment by ltfish** [comment]
- `valueset.reverse is not properly implemented` is gone.
- You can extract def-use chains from the new `VSA_DDG` class now. It's might be a bit difficult to use. I'll add interfaces to directly generate def-use chains as well as some test cases in the next few days.

Comments welcome!

**Comment by riyadparvez** [comment]
Thanks for publishing the analysis.

I'm seeing the following error (including the whole script), any idea why?

```
In [1]: import angr

In [2]: b = angr.Project('/home/riyad/tmp/coreutils-8.24/src/mkdir', load_options={'auto_load_libs': False})

In [4]: cfg = b.analyses.CFG()

In [5]: vfg = b.analyses.VFG(cfg, interfunction_level=3)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-25c1ab7b043c> in <module>()
----> 1 vfg = b.analyses.VFG(cfg, interfunction_level=3)

/home/riyad/tmp/angr/angr/angr/analysis.pyc in _analysis(self, analysis, *args, **kwargs)
     67 
     68         # Call __init__ of chosen analysis
---> 69         a = analysis(self._p, fail_fast, *args, **kwargs)
     70 
     71         return a

/home/riyad/tmp/angr/angr/angr/analysis.pyc in __core_init__(self, project, fail_fast, *args, **kwargs)
    123 
    124         if kwargs.pop('do_analysis', True):
--> 125             self.__analysis_init__(*args, **kwargs)  # pylint:disable=no-member
    126 
    127     def post_load(self):

/home/riyad/tmp/angr/angr/angr/analyses/vfg.pyc in __init__(self, cfg, context_sensitivity_level, function_start, interfunction_level, initial_state, avoid_runs)
    106 
    107         # Begin VFG construction!
--> 108         self._construct(initial_state=initial_state)
    109 
    110         self.result = {

/home/riyad/tmp/angr/angr/angr/analyses/vfg.pyc in _construct(self, initial_state)
    231 
    232             try:
--> 233                 self._ai_analyze(initial_state)
    234             except AngrVFGRestartAnalysisNotice:
    235                 l.info("Restarting analysis.")

/home/riyad/tmp/angr/angr/angr/analyses/vfg.pyc in _ai_analyze(self, initial_state, function_key)
    296             self._handle_entry(entry_wrapper, worklist,
    297                               exit_targets, fake_func_return_paths,
--> 298                               tracing_times, retn_target_sources
    299                               )
    300 

/home/riyad/tmp/angr/angr/angr/analyses/vfg.pyc in _handle_entry(self, entry_wrapper, remaining_entries, exit_targets, pending_returns, tracing_times, retn_target_sources)
    526 
    527         # Execute this basic block with input state, and get a new SimRun object
--> 528         simrun, error_occured, restart_analysis = self._get_simrun(input_state, current_path, addr)
    529 
    530         if restart_analysis:

/home/riyad/tmp/angr/angr/angr/analyses/vfg.pyc in _get_simrun(self, state, current_path, addr)
    394 
    395         try:
--> 396             sim_run = self._project.factory.sim_run(current_path.state, jumpkind=jumpkind)
    397         except simuvex.SimUninitializedAccessError as ex:
    398             l.error("Found an uninitialized access (used as %s) at expression %s.", ex.expr_type, ex.expr)

/home/riyad/tmp/angr/angr/angr/factory.pyc in sim_run(self, state, addr, jumpkind, **block_opts)
    114         else:
    115             l.debug("Creating SimIRSB at 0x%x", addr)
--> 116             r = self.sim_block(state, addr=addr, **block_opts)
    117 
    118         return r

/home/riyad/tmp/angr/angr/angr/factory.pyc in sim_block(self, state, stmt_whitelist, last_stmt, addr, opt_level, **block_opts)
     62                        addr=addr,
     63                        whitelist=stmt_whitelist,
---> 64                        last_stmt=last_stmt)
     65 
     66     def sim_run(self, state, addr=None, jumpkind=None, **block_opts):

/home/riyad/tmp/angr/simuvex/simuvex/vex/irsb.pyc in __init__(self, state, irsb, irsb_id, whitelist, last_stmt, **kwargs)
     60             self.state.release_plugin('solver_engine')
     61 
---> 62         self._handle_irsb()
     63 
     64         # It's for debugging

/home/riyad/tmp/angr/simuvex/simuvex/vex/irsb.pyc in _handle_irsb(self)
     90         # handle the statements
     91         try:
---> 92             self._handle_statements()
     93         except (SimSolverError, SimMemoryAddressError):
     94             l.warning("%s hit an when analyzing statements", self, exc_info=True)

/home/riyad/tmp/angr/simuvex/simuvex/vex/irsb.pyc in _handle_statements(self)
    205             # process it!
    206             self.state._inspect('statement', BP_BEFORE, statement=stmt_idx)
--> 207             s_stmt = translate_stmt(self.irsb, stmt_idx, self.last_imark, self.state)
    208             if s_stmt is not None:
    209                 self.state.log.extend_actions(s_stmt.actions)

/home/riyad/tmp/angr/simuvex/simuvex/vex/statements/__init__.pyc in translate_stmt(irsb, stmt_idx, imark, state)
     29         stmt_class = globals()[stmt_name]
     30         s = stmt_class(irsb, stmt_idx, imark, state)
---> 31         s.process()
     32         return s
     33     else:

/home/riyad/tmp/angr/simuvex/simuvex/vex/statements/base.pyc in process(self)
     24 
     25         # this is where we would choose between different analysis modes
---> 26         self._execute()
     27 
     28         del self.stmt

/home/riyad/tmp/angr/simuvex/simuvex/vex/statements/wrtmp.pyc in _execute(self)
      4     def _execute(self):
      5         # get data and track data reads
----> 6         data = self._translate_expr(self.stmt.data)
      7         self._write_tmp(self.stmt.tmp, data.expr, data.size_bits(), data.reg_deps(), data.tmp_deps())
      8 

/home/riyad/tmp/angr/simuvex/simuvex/vex/statements/base.pyc in _translate_expr(self, expr)
     34     def _translate_expr(self, expr):
     35         '''Translates an IRExpr into a SimIRExpr.'''
---> 36         e = translate_expr(expr, self.imark, self.stmt_idx, self.state)
     37         self._record_expr(e)
     38         return e

/home/riyad/tmp/angr/simuvex/simuvex/vex/expressions/__init__.pyc in translate_expr(expr, imark, stmt_idx, state)
     12     l.debug("Processing expression %s", expr_name)
     13     e = expr_class(expr, imark, stmt_idx, state)
---> 14     e.process()
     15     return e
     16 

/home/riyad/tmp/angr/simuvex/simuvex/vex/expressions/base.pyc in process(self)
     36 
     37         # this should change when additional analyses are implemented
---> 38         self._execute()
     39 
     40         self._post_process()

/home/riyad/tmp/angr/simuvex/simuvex/vex/expressions/ccall.pyc in _execute(self)
     21             try:
     22                 func = getattr(ccall, self._expr.callee.name)
---> 23                 self.expr, retval_constraints = func(self.state, *s_args)
     24                 self._constraints.extend(retval_constraints)
     25             except SimCCallError:

/home/riyad/tmp/angr/simuvex/simuvex/vex/ccall.pyc in amd64g_calculate_condition(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep)
    841 def amd64g_calculate_condition(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep):
    842     if USE_SIMPLIFIED_CCALLS in state.options:
--> 843         return pc_calculate_condition_simple(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep, platform='AMD64')
    844     else:
    845         return pc_calculate_condition(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep, platform='AMD64')

/home/riyad/tmp/angr/simuvex/simuvex/vex/ccall.pyc in pc_calculate_condition_simple(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep, platform)
    818 
    819     # TODO: Fallback to the complex-mode if the target method is not found.
--> 820     raise Exception('%s not found.' % funcname)
    821 
    822 def pc_calculate_rdata_c(state, cc_op, cc_dep1, cc_dep2, cc_ndep, platform=None):

Exception: pc_actions_LOGIC_CondLE not found.
```

**Comment by zardus** [comment]
Different binaries trigger different sorts of checks for conditional flags. The one you're analyzing seems to be using this LOGIC_CondLE, which we haven't seen before in our analyses.

Could you enable a debug log with `angr.project.l.setLevel("DEBUG")`? Check if the basic block addresses that it's printing out are actually in the binary, and make sense. If so, you'll need to implement `pc_actions_LOGIC_CondLE` in https://github.com/angr/simuvex/blob/master/simuvex/vex/ccall.py.

This function should return a single-bit 1 is `arg_l <= arg_r`, and a single-bit 0 otherwise. It should be analogous to `pc_actions_LOGIC_CondZ` and the rest of the `pc_actions_LOGIC_CondXX` functions from that file. We would really appreciate a pull request with that; getting a complete set of these actions is a pain :-)

**Comment by zardus** [comment]
Also, two TODOs for @fish:

- this gem: https://github.com/angr/simuvex/blob/master/simuvex/vex/ccall.py#L730
- this: https://github.com/angr/simuvex/blob/master/simuvex/vex/ccall.py#L820

Sorry @fish :-)

**Comment by riyadparvez** [comment]
@zardus I'm getting errors for this: https://github.com/angr/simuvex/blob/master/simuvex/vex/ccall.py#L730. Can you give me some pointers how to implement it? I'll submit a PR then.

**Comment by zardus** [comment]
I see; yeah, `pc_actions_SUB_CondNLE` should be implemented. It's "not less than or equal", so it should be the opposite of `pc_actions_SUB_CondLE`. If you could send us a PR, we'd be very thankful :-)

**Comment by riyadparvez** [comment]
The name of the parameters differ: `def pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep)` and `def pc_actions_SUB_CondNLE(state, cc_dep1, cc_dep2, cc_ndep)`. Should I rename the parameters too?

**Comment by zardus** [comment]
Yeah, that's another bug :-)

**Comment by ltfish** [comment]
BTW: If you `git blame` that method, it was committed by me. I must be very fucked up at that time...

**Comment by riyadparvez** [comment]
In implementation of `pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep)`, I see `r = se.If(se.ULE(arg_l, arg_r), se.BitVecVal(1, 1), se.BitVecVal(0, 1))` note the `se.ULE(arg_l, arg_r)`. but almost in all other methods this is like `r = se.If(result, se.BitVecVal(1, 1), se.BitVecVal(0, 1))`. Is it another bug?

**Comment by zardus** [comment]
Yeah. It's nothing bad, but it should still be changed.

To be honest, all of these optimizations in the conditional handlers are mostly obsolete now, as claripy does this internally, but we should be consistent until we take them all out.
