### ISSUE TITLE
Generating CFGAccurate fails on some x86 binaries as stat always returns a 64-bit value

### ISSUE THREAD

**Issue by fredwzz** [angr/angr#1004]
If I use pip or clone source code to install angr, there will be a warning
![image](https://user-images.githubusercontent.com/24257412/40403921-d11663cc-5e09-11e8-9be1-05abee224c84.png)
If I use docker to install angr the warning will disappear

Capstone version in pip and source code is 3.0.5, while in docker is 4.0.0.

However, I still have some problems with mips no matter which way I use
if I try commands below
```
print capstone.mips.MIPS_GPR_CALL
print capstone.mips.MIPS_GPR_JUMP
print capstone.mips.MIPS_GPR_RET
```
there is still something wrong with mips
![image](https://user-images.githubusercontent.com/24257412/40403077-453506c4-5e04-11e8-9ba9-703849841b0e.png)

 I want to analyze a mips binary, what should I do to make angr support mips?

**Comment by ltfish** [comment]
angr supports MIPS despite you seeing that warning message. The only difference is that you won't be able to load MIPS binaries in angr Management. You can safely ignore that if you cannot get the right version of capstone installed.

**Comment by fredwzz** [comment]
But nomatter which version cannot operate that three MIPS function. This is still not a problem?

**Comment by ltfish** [comment]
Those are not functions. It's not a problem.

**Comment by zardus** [comment]
Please look at the docker configuration (in github.com/angry/angr-dev) for
how to install this properly. We don't have the bandwidth to help debug
installation issues, unfortunately.

**Comment by fredwzz** [comment]
Sorry for asking installation questions. It's my first time to get in touch with symbolic execution. I'm really have no idea what to do since I tried all the installation method and followed each steps in tutorial but end up with failure. 
I want to extract CFG of a mips binary, but always end up with 
TypeError: <BV64 0x0> doesn't fit in an argument of size 4
Can you please give me some suggestions on what should I do to fix this. I try to google it but get nothing.

**Comment by fredwzz** [comment]
[sample1.zip](https://github.com/angr/angr/files/2029744/sample1.zip)
```
import angr
a = angr.Project('sample1')
a = angr.Project('sample11996', load_options={'auto_load_libs': False})
cfg = a.analyses.CFGAccurate(keep_state=True)
```

And please notice that the binary is a mips malware.

**Comment by ltfish** [comment]
The problem is that [stat.py](https://github.com/angr/angr/blob/master/angr/procedures/linux_kernel/stat.py) assumes the binary is 64-bit and always return a 64-bit value. @rhelmot Do you plan to keep working on this? It's your todo I believe.

**Comment by ltfish** [comment]
@fredwzz Why are you trying to generate a CFGAccurate on this binary? CFGFast (the default CFG) works well enough on it.

**Comment by fredwzz** [comment]
Thak you for your suggestion. I successfully extract CFG using CFGFast. But there is still something wrong when I try to plot the graph. 
`plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)
`
This command will return a warning:
Deprecation warning: Use main_object instead of main_bin

So I tried to modify the command. 
`
plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)`
But it will return error:

```
['dot', '-Tpng', '/tmp/tmp8g6FC8'] return code: -11

stdout, stderr:
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/angrutils/visualize.py", line 31, in plot_cfg
    vis.process(cfg.graph) 
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/base.py", line 310, in process
    return self.output.generate(graph)
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/output.py", line 214, in generate
    dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: -11
```
And I find that return of bellow two commands are both none.
```
main = proj.loader.main_object.get_symbol("main")
main = proj.loader.main_bin.get_symbol("main")
```
Could you plese give me some suggestions on how to fix this. I'm not familiar with analysis of MIPS architecture.

**Comment by rhelmot** [comment]
1) that’s a warning, not an error. It should have worked fine even if it
printed that.
2) this is now an issue in the angr utils package, which is not maintained
by the angr team.

**Comment by cq674350529** [comment]
Hi @fredwzz, I use IDA to load the binary you provided above, there is no function called `main` in the binary, so the result of `get_symbol()` you mentioned above is None.  

By the way, the binary you provided is static-linked and its size is big, so the cfg_graph generated by the `angrutils` may be too big. I have plot the cfg_graph successfully. If you have any problems, you can email to me: cq674350529@163.com. 

Thanks the angr team for the great job in `angr`.

**Comment by Cool-Y** [comment]
> Thak you for your suggestion. I successfully extract CFG using CFGFast. But there is still something wrong when I try to plot the graph.
> `plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True) `
> This command will return a warning:
> Deprecation warning: Use main_object instead of main_bin
> 
> So I tried to modify the command.
> ` plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)`
> But it will return error:
> 
> ```
> ['dot', '-Tpng', '/tmp/tmp8g6FC8'] return code: -11
> 
> stdout, stderr:
>  
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/angrutils/visualize.py", line 31, in plot_cfg
>     vis.process(cfg.graph) 
>   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/base.py", line 310, in process
>     return self.output.generate(graph)
>   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/output.py", line 214, in generate
>     dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
>   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1756, in write
>     s = self.create(prog, format, encoding=encoding)
>   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1884, in create
>     assert p.returncode == 0, p.returncode
> AssertionError: -11
> ```
> And I find that return of bellow two commands are both none.
> 
> ```
> main = proj.loader.main_object.get_symbol("main")
> main = proj.loader.main_bin.get_symbol("main")
> ```
> Could you plese give me some suggestions on how to fix this. I'm not familiar with analysis of MIPS architecture.

Hi, I met the same problem, have you solved the return error?

**Comment by fredwzz** [comment]
> > Thak you for your suggestion. I successfully extract CFG using CFGFast. But there is still something wrong when I try to plot the graph.
> > `plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True) `
> > This command will return a warning:
> > Deprecation warning: Use main_object instead of main_bin
> > So I tried to modify the command.
> > ` plot_cfg(cfg, "sample_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)`
> > But it will return error:
> > ```
> > ['dot', '-Tpng', '/tmp/tmp8g6FC8'] return code: -11
> > 
> > stdout, stderr:
> >  
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/angrutils/visualize.py", line 31, in plot_cfg
> >     vis.process(cfg.graph) 
> >   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/base.py", line 310, in process
> >     return self.output.generate(graph)
> >   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/bingraphvis/output.py", line 214, in generate
> >     dotfile.write("{}.{}".format(self.fname, self.format), format=self.format)
> >   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1756, in write
> >     s = self.create(prog, format, encoding=encoding)
> >   File "/home/angr/.virtualenvs/angr/local/lib/python2.7/site-packages/pydot.py", line 1884, in create
> >     assert p.returncode == 0, p.returncode
> > AssertionError: -11
> > ```
> > And I find that return of bellow two commands are both none.
> > ```
> > main = proj.loader.main_object.get_symbol("main")
> > main = proj.loader.main_bin.get_symbol("main")
> > ```
> > Could you plese give me some suggestions on how to fix this. I'm not familiar with analysis of MIPS architecture.
> 
> Hi, I met the same problem, have you solved the return error?

Unfortunately, no.....

**Comment by rhelmot** [comment]
Fixed. The stat function still only supports amd64 but at least it won't crash. This really illustrates the excesses of our team's mindset that you gotta do things perfectly or you might as well not do them at all...
