### ISSUE TITLE
EIP/RIP wrong during step()

### ISSUE THREAD

**Issue by s0i37** [angr/angr#1009]
Hello.
I have something strange behavior during step():

```
def on_exec(state):
	print "[exec] 0x%x" % state.addr

project = angr.Project(binary)
state = project.factory.entry_state()
state.inspect.b('instruction', when=angr.BP_AFTER, action=on_exec)
sm = project.factory.simgr(state)
sm.step()
```

And I get this:

```
0x400a2f:	push	rbp
0x400a30:	mov	rbp, rsp
0x400a33:	sub	rsp, 0x10
0x400a37:	mov	dword ptr [rbp - 4], edi
0x400a3a:	mov	qword ptr [rbp - 0x10], rsi
0x400a3e:	call	0x400740
[exec] 0x400a2f
[exec] 0x400a2f
[exec] 0x400a2f
[exec] 0x400a37
[exec] 0x400a3a
[exec] 0x400a3e
```

Each second instruction has wrong RIP value.
What I do wrong? How can I obtain code pointer register ?
Thanks.

**Comment by rhelmot** [comment]
Not a bug. The instruction pointer is not updated by libvex at each block. You can verify this by looking at the IR and looking for writes to rip.

Instead, you want to use `state.scratch.ins_addr`.

**Comment by s0i37** [comment]
Cool! Thank you a lot. Problem solved.
