### ISSUE TITLE
Simulation takes only true branch when unconstrained

### ISSUE THREAD

**Issue by Finnem** [angr/angr#1010]
Hey,
I'm currently playing around with the simulation manager and I discovered a weird behaviour.
When starting to simulate with a blank state in the middle of the program (I'm currently using dd from coreutils as my example, so in this case in the middle means at address 0x40997e see picture) it will only take the positive branch of the je instruction. That is, for the following assembly (it only shows the not branch which i cant produce with the simulation manager):
![slice for dd-0x4099be with depth 3](https://user-images.githubusercontent.com/15279480/40578308-0bc71f60-6112-11e8-8535-7c3e448d8590.png)
```
st = proj.factory.blank_state(addr=0x40997e)
sim = proj.factory.simgr(st, save_unconstrained = True)
sim.step()
<SimulationManager with 1 active>
sim.active
```

results in `[<SimState @ 0x4099c0>] `

I would however expect 2 active states. One where the jump is taken and one where it's not (the one in the image).

Is there some setting that I am missing?

**Comment by rhelmot** [comment]
That looks like a BSS address you’re loading from - angr initializes the BSS to 0. You’ll need to write symbolic values to the whole data and BSS if you want this to work.

**Comment by Finnem** [comment]
Ah yes,
that makes sense. Is there an easy way to write symbolic values instead of 0 to the BSS? Currently it seems to me this is happening in cle and not in angr itself (if it does happen angr I can't find it). 
Is there an elegant way to bypass/override the memory read to such sections?

**Comment by ltfish** [comment]
Create an initial state, overwrite the entire BSS section with some symbolic values you create, and then use that state for future symbolic execution runs.

**Comment by Finnem** [comment]
Perfect, it works now as intended.
Thank you very much!
