### ISSUE TITLE
understanding the binary operations from symbolic execution

### ISSUE THREAD

**Issue by steseb** [angr/angr#1013]
Hi, I'm trying to use the symbolic execution to explore a binary and thus understand which are the operations performed over the symbolic variables. The final goal is a source recovery with a behaviour similar to the original code.

I have been able to obtain the constraints associated to the deadended state  (`deadended.se.constraints`) even if the output format is not totally clear to me. In particular the presence of the sharp symbol and the two dots (e.g., `<Bool ((0#56 .. (0xffffffd0 + 0x0#24 .. arg1_0_8)[7:0]) & 0xff) <= 0x9>`). Moreover, is it possible to retrieve the AST for the operations over the symbolic variables? Even step by step during the symbolic execution is fine. Thank you

**Comment by rhelmot** [comment]
`0#56` is shorthand for "a bitvector with value 56 and length 0". `..` is the bitvector concatenation operation.

You can explore ASTs by looking at their properties `.op` and `.args`.

**Comment by steseb** [comment]
Thanks for your prompt reply @rhelmot. But there are still some points that are not clear to me.

1. What is the meaning of a Bitvector with a value but having length 0?
2. in the small chunk of constraint printed in my original post there was also: `0x0#24 `. It is the same of `0#24`? I mean, why sometimes the length of the bitvector is expressed as decimal and other times as hex? Or it has a different meaning? Are the constraints from `deadended.se.constraints` written according to any specific format?

From a very simple code such as:
```
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char** argv)
{
  int a = atoi(argv[1]);
  printf("%d\n", a);
  a = a+1;
  printf("%d\n", a);
  return a;
}
```
Calling Angr with:
```
    proj= angr.Project(sys.argv[1], load_options={'auto_load_libs': False})
    justAnArgument = claripy.BVS('arg1', 32)
    argv = [sys.argv[1], justAnArgument]
    state = proj.factory.entry_state(args=argv)
```
I was expecting to see something like:
`<BV32 arg1_0_32 + 0x1>`
by calling the symbolic variable: `justAnArgument`. Like in the Claripy example at [http://angr.io/api-doc/claripy.html](url) by printing the symbolic variable `c`.
Instead both the properties that you have suggested (`.op` and `.args`) don't have such an information with them but just: `BVS` and `('arg1_0_32', None, None, None, False, False, None)`. I also tried to perform a `step()` execution but the content is always the same. 

Moreover if new symbolic variables are created by Claripy (e.g., if in the C code there is something like `c = a + 2`) I expect to retrieve a list of the new variables just by doing `deadended.se.variables`.

Perhaps, I'm oversimplifying the internals of this really powerful tool but it would be great if it is possible to have something like this working. Even a pointer to the Angr source code and a few hints if something like this is feasible but not yet implemented would be fine.

Thank you again

**Comment by rhelmot** [comment]
Hey - the primary issue seems to be your thinking that variables are mutable, and changed by execution. Variables are immutable. When you create justAnArgument, it will always be justAnArgument, for the rest of time. If you want to inspect the results of computing with it, you need to extract the results from the state somehow.

Furthermore, the notion of a variable to `state.se.variables` doesn't correspond to the notion of a variable in a C program, like you want it to - it corresponds to the list of BVSs that are currently in play. So if you have `c = a + 2`, the only variable will be `a`.

You perhaps want `state.se.constraints`.

(btw, `state.solver` is a better way of spelling `state.se` - it's the exact same thing but less obscurely named)

**Comment by rhelmot** [comment]
(also note that there are issues with how angr handles printf. you should consider using `write(1, &var, sizeof(var))` for debugging)

**Comment by steseb** [comment]
Hi, I tried to implement your suggestions @rhelmot but I can't see any constraint in `state.solver.constraints` for this example. With other (more complex) binaries I have been able to get constraints, but I'm still unable to understand the adopted syntax and in particular the meaning of the `0x0#24` if it differs from `0#24`, and what a bit vector with a value (e.g., 24) but length zero could mean.

For the very simple code:
```
#include <unistd.h>
int main(int argc, char** argv) {
  char a = argv[1][0];
  a = a+3;
  write(1, &a, sizeof(a));
  return a;
}
```

I tried to use a few options in `Angr` such as:
```
   proj= angr.Project(sys.argv[1], load_options={'auto_load_libs': True})
   anargument = claripy.BVS('arg1', 64)
   argv = [sys.argv[1], anargument]
   state = proj.factory.entry_state(args=argv ,add_options={angr.options.TRACK_CONSTRAINTS, angr.options.TRACK_CONSTRAINT_ACTIONS, angr.options.TRACK_OP_ACTIONS})
   sm = proj.factory.simgr(state)
   simsuccessor = sm.step() 

   while(True) :
       if (hasattr(sm, 'deadended') and len(sm.deadended) > 0):
           break
       else:
           simsuccessor = sm.step()
           if len(simsuccessor.active) > 0:
               currentactive = simsuccessor.active[0]
               print "symbolic op is ", anargument.op
               print "symbolic args is ", anargument.args
               print "currentactive allvar ", currentactive.solver.all_variables
               print "currentactive constraints ", currentactive.solver.constraints
               print "currentactive temporalTrackedVar ", currentactive.solver.temporal_tracked_variables
   if (hasattr(sm, 'deadended') and len(sm.deadended) > 0):
       for deadended in sm.deadended:
           print "deadeneded output is %s. " % (deadended.posix.dumps(1))     
           print "deadeneded input is %s. " % (deadended.posix.dumps(0))
           print "constraints on deadended %s." % deadended.solver.constraints
```

and at each `sm.step()` the output is:
```
symbolic op is  BVS
symbolic args is  ('arg1_0_64', None, None, None, False, False, None)
currentactive allvar  []
currentactive constraints  []
currentactive temporalTrackedVar  {('reg', 168, None): 1, ('reg', 120, None): 1, ('reg', 120, 1): <BV64 reg_78_3_64{UNINITIALIZED}>, ('reg', 168, 1): <BV64 reg_a8_6_64{UNINITIALIZED}>, ('reg', 128, None): 1, ('reg', 128, 1): <BV64 reg_80_2_64{UNINITIALIZED}>, ('reg', 136, 1): <BV64 reg_88_1_64{UNINITIALIZED}>, ('reg', 136, None): 1, ('reg', 40, None): 1, ('reg', 40, 1): <BV64 reg_28_5_64{UNINITIALIZED}>, ('reg', 112, None): 1, ('reg', 112, 1): <BV64 reg_70_4_64{UNINITIALIZED}>}
```
and even on the `deadended` state: `deadended.solver.constraints` and `deadended.solver.temporal_tracked_variables` are the same. I don't know if there is any additional option that needs to be added to see any constraint or to recover the AST involving the symbolic variable for this example. Thanks

**Comment by rhelmot** [comment]
- I told you the interpretation backwards. Sorry about that. `0#24` is a bitvector of value 0 and length 24.
- The 0x prefix just signifies if the value is printed in hex or not. The choice of whether to print in hex or not is [based on the length of the bitvector](https://github.com/angr/claripy/blob/master/claripy/ast/base.py#L463).

Constraints are only added on conditional branches. This is a pretty basic element of symbolic execution.

The reason you don't see your variable in the tracking is because the tracking only works with variables that were registered with it. angr does this automatically with any variables it creates, but for variables you create you need to register it manually. You can do this by either creating the variable through the `state.solver.BVS()` constructor and providing a `key=` argument as a tuple of hierarchical descriptors for the variable, or using `state.solver.register_variable(ast, key)`.

However it looks like that's not what you want.

In this case if you want to track the correspondence between the input and the output you should just look directly at the output. Since it's going to stdout you want to look directly at stdout - `state.posix.stdout` to be precise. This is a SimFile - a complicated interface for managing file streams. IIRC the default stdout is actually a `SimPackets` to be able to better handle symbolic-length writes, so you want to look at `state.posix.stdout.content`, which is a list of tuples of `(content, content-length)`. Note that this only applies if you're running angr installed from github - SimFiles were refactored last month and changed a lot, and the pypi version hasn't caught up.

**Comment by steseb** [comment]
Ok now the syntax used in the constraints is clear. Thanks @rhelmot 

I totally agree with you that during a symbolic execution new constraints are added at conditional branches (considering an high level language: if, while, for, etc). Actually in my first post I was looking for an AST with the operations in which the symbolic variables are involved (I mean what is described in your doc on [Angr-Claripy](https://github.com/angr/angr-doc/blob/master/docs/claripy.md)). I think that at some point during the symbolic execution of my code, Angr needs to store the operation: symbolic_variable + 3. Obviously, since Angr doesn't have access to the C code but works on the VEX IR, I could see something more complex (e.g., a reference to a memory registry containing such a constant or whatever). But in my mind there should be somewhere an AST involving: (1) symbolic variable (`anargument` in my example), (2) operator (`+`) and the (3) constant (`3`).

I just misunderstood the suggestion in your old post where you were pointing me to the `state.se.constraints`. I think we are on the same page.

I also tried to register my variable using:
`state.solver.register_variable(anargument,key=('test', 1))`
just after the `state = proj.factory.entry_state...`. But the variable `anargument` is not registered in any case (it is not in `state.solver.temporal_tracked_variables`). Even trying to register it at each step of the symbolic execution doesn't change anything. Is this the right way of registering the variable? (the `key` parameter is not very clear to me)

Is still this variable registration what I need?

Thanks again.

**Comment by rhelmot** [comment]
You're not supposed to extract data via `temporal_tracked_variables`, you're supposed to use `get_variables`, which takes a tuple and returns all variables whose keys have that tuple as a prefix.

You're right, there is an AST somewhere that holds what you want. It's in stdout, as I described in the previous post. It's probably also in memory or registers somewhere, but none of those are explicit interfaces you designed as a programmer of the C code.

**Comment by rhelmot** [comment]
I'm sorry, it doesn't take a tuple, it takes the elements of the tuple as varargs.
