### ISSUE TITLE
KeyError when passing a Path to a function using multiprocessing

### ISSUE THREAD

**Issue by juk80x** [angr/angr#102]
The following code reproduces the KeyError for any test binary

``` python
import angr
from multiprocessing import Pool

def my_test(path):
    return path

pool = Pool(processes=4)
project = angr.Project("./testargprog")
state = project.factory.entry_state()
path_group = project.factory.path_group(state)
pool.apply_async(my_test, (path_group.active[0],))
path_group.step()
pool.apply_async(my_test, (path_group.active[0],))
path_group.step()
```

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
  File "/Library/Python/2.7/site-packages/ana/d.py", line 22, in D
    state = get_dl().load_state(uuid)
  File "/Library/Python/2.7/site-packages/ana/datalayer.py", line 69, in load_state
    p = self._state_store[uuid]
KeyError: (('0366d89d-7001-4db4-a375-0a9d80f163a5',), <function D at 0x106e07848>, ('0366d89d-7001-4db4-a375-0a9d80f163a5', <class 'simuvex.s_state.SimState'>, None))
```

**Comment by zardus** [comment]
Oh dear...

So claripy uses ANA (https://github.com/zardus/ana) to store ASTs. ANA is a bit of a homespun serialization mess that does some tricks to avoid serializing the same AST multiple times. As these analyses tend to contain the same AST across many states, pickling ASTs multiple times takes up a disastrous amount of space. Instead, when an ANA object is pickled, the actual pickled data is stored in an ANA backend, and only the identifier is returned to Python.

By default, this backend is a dict in memory (`self._state_store`), which doesn't persist between different processes, as you're seeing. ANA also supports a filesystem backend and a mongodb backend (https://github.com/zardus/ana#storage-backends). You probably want the filesystem backend, which will store object states in pickles in a directory. You'll need to give it a directory to use, but that can be in `/dev/shm` if you want to use shared memory. ANA will store its data there, and the different processes will retrieve it.

Note that this has no garbage collection with this at the moment. That's something that we still need to think about...
