### ISSUE TITLE
How to do a full-path symbolic execution with the function that obfuscated by Control-Flow-Flattening?

### ISSUE THREAD

**Issue by sparktend** [angr/angr#1023]
I want to use angr to deobfuscate the code obfuscated by Obfuscator-LLVM with "-mllvm -fla" according to  this article "Deobfuscation: recovering an OLLVM-protected program".
 I need do a full-path symbolic execution to analysis the basic block sequence. 

The origial function code is:
```
unsigned int target_function(unsigned int n)
{
  unsigned int mod = n % 4;
  unsigned int result = 0;

  if (mod == 0) result = (n | 0xBAAAD0BF) * (2 ^ n);
  else if (mod == 1) result = (n & 0xBAAAD0BF) * (3 + n);
  else if (mod == 2) result = (n ^ 0xBAAAD0BF) * (4 | n);
  else result = (n + 0xBAAAD0BF) * (5 & n);

  return result;
}
```

If I use the below script[No.1]:
```
x = state.solver.BVV(0x1, 32)
state.regs.r0 = x
simgr = proj.factory.simgr(state)
simgr.run()
print simgr
```
<SimulationManager with 1 deadended>

If I use the below script[No.2]:
```
simgr = proj.factory.simgr(state)
simgr.run()
print simgr
```
<SimulationManager with 4 deadended>

Both results are correct.
Now I use Obfuscator-LLVM with "-mllvm -fla" to obfuscate the function.
If I use the No.1 script the result is the same.
If I use the No.2 script the result is different. The```simgr.run()``` cann't finish.
Debug info:
```
WARNING | 2018-06-01 17:25:00,606 | angr.manager | No completion state defined for SimulationManager; stepping until all states deadend
DEBUG   | 2018-06-01 17:25:00,606 | angr.manager | Round 1: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,653 | angr.manager | Round 2: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,657 | angr.manager | Round 3: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,662 | angr.manager | Round 4: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,667 | angr.manager | Round 5: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,678 | angr.manager | Round 6: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,692 | angr.manager | Round 7: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,706 | angr.manager | Round 8: stepping <SimulationManager with 1 active>
DEBUG   | 2018-06-01 17:25:00,741 | angr.manager | Round 9: stepping <SimulationManager with 2 active>
DEBUG   | 2018-06-01 17:25:00,783 | angr.manager | Round 10: stepping <SimulationManager with 4 active>
DEBUG   | 2018-06-01 17:25:00,839 | angr.manager | Round 11: stepping <SimulationManager with 4 active>
DEBUG   | 2018-06-01 17:25:00,905 | angr.manager | Round 12: stepping <SimulationManager with 6 active>
DEBUG   | 2018-06-01 17:25:00,950 | angr.manager | Round 13: stepping <SimulationManager with 6 active>
DEBUG   | 2018-06-01 17:25:01,034 | angr.manager | Round 14: stepping <SimulationManager with 6 active>
DEBUG   | 2018-06-01 17:25:01,138 | angr.manager | Round 15: stepping <SimulationManager with 8 active>
DEBUG   | 2018-06-01 17:25:01,222 | angr.manager | Round 16: stepping <SimulationManager with 8 active>
DEBUG   | 2018-06-01 17:25:01,325 | angr.manager | Round 17: stepping <SimulationManager with 8 active>
DEBUG   | 2018-06-01 17:25:01,473 | angr.manager | Round 18: stepping <SimulationManager with 12 active>
DEBUG   | 2018-06-01 17:25:01,651 | angr.manager | Round 19: stepping <SimulationManager with 14 active>
DEBUG   | 2018-06-01 17:25:01,937 | angr.manager | Round 20: stepping <SimulationManager with 18 active>
DEBUG   | 2018-06-01 17:25:02,304 | angr.manager | Round 21: stepping <SimulationManager with 31 active>
DEBUG   | 2018-06-01 17:25:02,852 | angr.manager | Round 22: stepping <SimulationManager with 47 active>
...
```

The No.1 script result is correct, but not what I want. Of course, 
I can also set different parameters to cover the complete execution path.
But I want a more general way, rather than let me set different parameters, such like No.2 script.

The function have a main dispatcher(like switch-case) after obfuscation. 
It has a state variable to control the main dispatcher.
The main dispatcher block will executed many times when symbolic execution. 
```unconstrained stashes``` will increase per executing main dispatcher block. 
so the ```active stashes``` will inflate.

I think that ```unconstrained stashes``` increase is repeated. So that it becomes an infinite loop.
But I don't know how to control it so that I can get 4 deadended stashes like the function before obfuscation.

**Comment by ltfish** [comment]
It's hard to speculate without seeing the binary. Can you post the obfuscated binary?

**Comment by sparktend** [comment]
[libtarget_arm_flatten.zip](https://github.com/angr/angr/files/2062688/libtarget_arm_flatten.zip)
The obfuscated function offset is 0xDA4.

**Comment by ltfish** [comment]
The obfuscated function is at `0xd8d` (`0xd8c` + 1 because of THUMB mode). I'm not sure how you got `0xda4`.

My script:

```
import logging

logging.getLogger('angr.sim_manager').setLevel(logging.DEBUG)

import angr

p = angr.Project("libtarget_arm_flatten.so", auto_load_libs=False)
state = p.factory.blank_state(addr=0x400d8d)
simgr = p.factory.simgr(state, save_unconstrained=True)
simgr.run()

print simgr
```

Output:

```
<SimulationManager with 4 unconstrained>
```

I believe it's working as expected.

**Comment by sparktend** [comment]
Thank you. 
I used your script and got the correct result.

But if I change the function to ：
```
int test_main_second(int x, int y) {
    int result = 0;
    int mod = x % 3;
    int m = 0;
    if (mod == 0) {
        result = (x & 0xFFAABBCC) * (1 + y);
        if (7 * y * y - 1 == x * x) {
            result += (x & 0xFFEEDDCC);
        }
    } else if (mod == 1) {
        m = x * y;
        result = func_one_c(x, m);
    } else if (mod == 2) {
        result = func_two(x, y);
        mod = func_three(result, mod);
    }

    result = result + mod;
    return result;
}
```
[libtarget_arm_flatten2.zip](https://github.com/angr/angr/files/2066640/libtarget_arm_flatten2.zip)
I also used Obfuscator-LLVM with "-mllvm -fla" to obfuscate the function.
The obfuscated function is at 0x1075.
I got the error like I said at the beginning.

**Comment by ltfish** [comment]
The state explosion happens inside `sub_11c0`, which is the implementation of function `aeabi_idivmod()`.

The easy way to figure out what's going on is to use
```
while simgr.active:
    simgr.step()
    print(simgr.active)
```
instead of `simgr.run()`.

The solution is to manually provide a SimProcedure for `aeabi_idivmod()`.

**Comment by sparktend** [comment]
I understand what you mean.
But I still got the error when I used the script you gave.
Maybe What you said SimProcedure for ```aeabi_idivmod()``` doesn't work in my environment.
My angr version is 7.8.2.21.

I found another way to figure out. 
I used ```proj.hook``` to hook the address```0x401087```and```0x40109d``` with the implementation of funtion aeabi_idivmod() and divsi3() by myself. 
The result is what I want.
Thank you very much.

**Comment by ltfish** [comment]
> But I still got the error when I used the script you gave.

I gave you a script to help you figure out why the execution gets stuck. I *did not* give you a script to solve your state explosion problem.

> I used proj.hook to hook the address0x401087and0x40109d with the implementation of funtion aeabi_idivmod() and divsi3() by myself.

Good to know.
