### ISSUE TITLE
SimUnsatError while executing syscall on unsatisfiable path

### ISSUE THREAD

**Issue by Airtnp** [angr/angr#1030]
I was trying to continue processing state successors on unsat_successors. Here is my minimal example:
```python
"""
// gcc -g -O2
#include <stdlib.h>
#include <stdio.h>
#include <sys/stat.h>

int main() {
    FILE* err = fopen("/etc/hostname", "r"); # Always success since ALL_FILE_EXISTS and fopen hooked
    struct stat st;
    if (!err) { # 0x400579
	 lstat("/etc/hostname", &st);
         printf("Failed to open");
    } else {
         lstat("/etc/hostname", &st);
         printf("Able to open");
    }
}
"""

import angr
from angr.procedures import SIM_PROCEDURES

so = angr.sim_options

p = angr.Project("./unsat")

p.hook_symbol('fopen', SIM_PROCEDURES['libc']['fopen']()) # Also why this shows it was already hooked?
p.hook_symbol('printf', SIM_PROCEDURES['libc']['printf']())

start = p.factory.entry_state(
    add_options=set([
        so.TRACK_JMP_ACTIONS,
    ]),
    remove_options=set([
        so.LAZY_SOLVES,
        so.TRACK_CONSTRAINT_ACTIONS,
    ])
)

succ_func = p.factory.successors

simgr = p.factory.simgr(start)

simgr.run(until=lambda sm: sm.active[0].addr == 0x400579)

judge = simgr.active[0]

sat = succ_func(judge).successors[0]

for _ in range(8):
    print(sat)
    sat = sat.step().successors[0] # executing lstat in satisfiable path is OK.

unsat = succ_func(judge).unsat_successors[0]

# execute until lstat (not supported syscall, provided by syscall_stub
for _ in range(5):
    print(unsat)
    unsat = unsat.step().unsat_successors[0]

unsat.step() # This will incur SimUnsatError for Simprocedure syscall (lstat)
```

Does angr support finding state successors on unsat path?

**Comment by ltfish** [comment]
> Does angr support finding state successors on unsat path?

Not really. But you can work around this by manually dropping all constraints and clearing all caches of an unsat state. You will be responsible of whatever happens though.

**Comment by ltfish** [comment]
Oh, if you don't really rely on performing symbolic execution, you can set your state to `fastpath` mode, which essentially enables forced concrete execution. You will lose the ability to solve constraints in most cases, but you will be able to advance arbitrary states, regardless of whether they are satisfiable or not. This is how `CFGAccurate` is implemented.

**Comment by Airtnp** [comment]
Thank you for your quick and detailed response! 

In some cases (which I cannot figure out now), SImProcedure (eg. malloc) under fastpath mode invokes SimSolverModeError("Light solver can't handle this max()"). Does that mean fastpath mode is not suitable for this case? 

Maybe I guess I could try directly create a blank state when on unsat path.

**Comment by ltfish** [comment]
> Does that mean fastpath mode is not suitable for this case?

SimProcedures got executed. You probably don't want to execute SimProcedures in fastpath mode?
