### ISSUE TITLE
Sortedcontainers broke their API

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1035]
http://www.grantjenks.com/docs/sortedcontainers/history.html

I think everything was still working up until the 2.0.4 stuff, which honestly makes me mad as hell, but whatever. We need to replace all iterX methods with just the normal X methods. This is still efficient since it returns views instead of lists, but we'll need to make sure we're not depending on iterX returning a generator specifically.

**Comment by ltfish** [comment]
:(
