### ISSUE TITLE
Blocks inside functions not in the cfg accurate

### ISSUE THREAD

**Issue by valour01** [angr/angr#1039]
I use the cfg_accurate to generate the graph.

I use `cfg.kb.functions` to get every function and use the `functions[addr].blocks` to get the blocks inside every function. However. I found that the blocks inside a function is not in the graph itself.
For example,
```
In [15]: for b in cfg_accurate.kb.functions[0xb028].blocks:
    print b
   ....:     
<Block for 0xb158, 36 bytes>
<Block for 0xb130, 20 bytes>
<Block for 0xb064, 16 bytes>
<Block for 0xb1f8, 20 bytes>
<Block for 0xb028, 32 bytes>
<Block for 0xb0cc, 12 bytes>
<Block for 0xb17c, 36 bytes>
<Block for 0xb20c, 4 bytes>
<Block for 0xb090, 40 bytes>
<Block for 0xb048, 16 bytes>
<Block for 0xb1a0, 88 bytes>
<Block for 0xb074, 4 bytes>
<Block for 0xb144, 20 bytes>
<Block for 0xb058, 12 bytes>
<Block for 0xb078, 24 bytes>
<Block for 0xb0b8, 20 bytes>
<Block for 0xb11c, 20 bytes>
```

Then I use `cfg_accurate.get_any_node` to get the node. But it returns nothing.
```
 cfg_accurate.get_any_node(0xb058)
```

Do anyone know the reason. Attached testing binary
[cp-strip.zip](https://github.com/angr/angr/files/2089629/cp-strip.zip)

**Comment by valour01** [comment]
It seems the reason is that I also run `p.analysis.CFGFast()` and it will overwrite the knowledge base

**Comment by ltfish** [comment]
Every analysis will use the global knowledge base by default. You can prevent this from happening by creating your own `KnowledgeBase` instance first, and then pass it in to each analysis by doing `CFG(..., kb=my_kb)` (I'm using CFG as an example).
