### ISSUE TITLE
"loader.provide_symbol" has been removed

### ISSUE THREAD

**Issue by firmianay** [angr/angr#1051]
Hi, angr is amazing. I start to learn from its code and then find an abandoned function still used in `hook_symbol`:
```py
        if type(obj) in (int, long):
            # this is pretty intensely sketchy
            l.info("Instructing the loader to re-point symbol %s at address %#x", symbol_name, obj)
            self.loader.provide_symbol(self.loader.extern_object, symbol_name, AT.from_mva(obj, self.loader.extern_object).to_rva())
            return obj
```
`loader.provide_symbol` has been removed since this commit 186096775932d8fa844d9532a1f180bc2553f7d7

**Comment by ltfish** [comment]
Thanks for reporting!

**Comment by rhelmot** [comment]
I've just removed this functionality. As far as I can tell nobody was using it, and if someone comes to me with a good use-case I will figure out how to resurrect it then.
