### ISSUE TITLE
Strlen SimProcedure type error

### ISSUE THREAD

**Issue by irwincong** [angr/angr#1056]
VFG creation of a function containing a `strcpy()` call throws a `TypeError` exception inside the `strlen()` sim procedure.  The `strcpy()` sim procedure internally uses the `strlen()` sim procedure.  The issue, I think, stems from re-assigning a list variable the result of `max()`, which returns a single element.

Re-create the exception with what is documented in https://github.com/angr/angr/issues/27#issuecomment-397737270

Proposed patch/diff attached.
[strlen-patch.txt](https://github.com/angr/angr/files/2111562/strlen-patch.txt)

Note, two instance checks is probably overkill

**Comment by rhelmot** [comment]
The linked commit is a better fix. With that fix, the script now no longer crashes but instead runs my laptop out of RAM, which I think is a good sign :)
