### ISSUE TITLE
context sensitive reaching definitions

### ISSUE THREAD

**Issue by Finnem** [angr/angr#1060]
Hey,
is it possible to have a context sensitive reaching definitions analysis?
Lets say i have:
```
main:
mov [0x55] 5
...
call b

b:
mov rax [0x55]
call rax
```

Is it possible to deduct that rax  at the call instruction is dependant on the first mov statement with the reaching definitions analysis? Thanks!

**Comment by raycewest** [comment]
You perhaps looking for DDG?
https://github.com/angr/angr/issues/979
