### ISSUE TITLE
unique exploration technique exception return

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1068]
Hello,

I'm trying to use the unique explore technique very simply like so:
```
    technique = angr.exploration_techniques.UniqueSearch()
    simgr.use_technique(technique)
    simgr.run()
```

Whenever I try to run with the technique I receive the following exception:
```
    simgr.run()
  File "C:\Python27\lib\site-packages\angr\misc\immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "C:\Python27\lib\site-packages\angr\sim_manager.py", line 265, in run
    self.step(stash=stash, **kwargs)
  File "C:\Python27\lib\site-packages\angr\misc\hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "C:\Python27\lib\site-packages\angr\exploration_techniques\unique.py", line 69, in step
    unique_state = min(self.uniqueness.items(), key=lambda e: e[1])[0]
ValueError: min() arg is an empty sequence
```
On the following line:
```
unique_state = min(self.uniqueness.items(), key=lambda e: e[1])[0]
```
Printing self.uniqueness.items() shows that at the end of the run the states passed are empty list ([])
so it seems we should check if there are any states:
```
if len(self.uniqueness.items()) != 0: ...
```

**Comment by ltfish** [comment]
That is a bug with the unique exploration technique...

**Comment by ConnorNelson** [comment]
Yes, I can put up a patch later tonight. I guess I hadn't imagined running this technique exhaustively to completion. Of course in this case it should do nothing rather than crash.

**Comment by rhelmot** [comment]
Ah, in that case I know how the fix should look. Thanks for the guidance.
