### ISSUE TITLE
AnnotatedCFG

### ISSUE THREAD

**Issue by hanchaoqiang** [angr/angr#107]
after genetated a AnnotatedCFG  from backwardslice, how can i pass it to Exploer?
besides  p=b.surveyors.EXplorer(find=0x423D80)   can you give some examples for me how to get  this target address(0x423D80)?  
thanks

**Comment by ltfish** [comment]
You want to feed the AnnotatedCFG to `angr.surveyors.Slicecutor`. Sorry that we don't have any example available right now. We are happy to take your code if you want to contribute one to angr-doc!
