### ISSUE TITLE
Any idea on how to optimize time and memory usage for angr?

### ISSUE THREAD

**Issue by Airtnp** [angr/angr#1070]
Currently, my use of angr is like `step = p.factory.successors(state, num_inst=1)` and find one successor based on specific requirement (drop other ones). Are there some tricks I can use to reduce memory cost and speed up finding successors?. I tried gc.collect() and DOWNSIZE_Z3 but it had little use. I must run in symbolic mode since I need symbolic execution and hooked SimProcedure.

I tried guppy.hpy and find there are many pyvex objects in the memory? Where are they stored? Maybe state.history? Can I get rid of them? If necessary I can try to modify angr, claripy or some other modules.

Please mark this issue as question.

**Comment by ltfish** [comment]
How much memory is angr taking for you?

**Comment by Airtnp** [comment]
About 7g. Then my laptop memory exhausted.

**Comment by ltfish** [comment]
Are you using PyPy or CPython? How many states are you keeping around?

Heapy is a good tool to diagnose how much heap memory is used in Python code. You might want to see what unwanted objects are lying around.

**Comment by rhelmot** [comment]
Symbolic execution should not be able to exhaust 7g of RAM in anything less
than 12 hours. If it’s taking memory faster than that you are probably
keeping around too many states, either accidentally or intentionally.

**Comment by Airtnp** [comment]
Thanks for your advice! I use Python and I do find myself store over 5000 consequent states. I may think of just keep a sample of them. Is 6M for a state a good estimate?

**Comment by ltfish** [comment]
> Is 6M for a state a good estimate?

It is really hard to estimate - state contains `SimMemory` objects, which are copy-on-write. Writing 10 MB of bytes into a state will certainly take up more memory than writing only one byte into another state.
