### ISSUE TITLE
Avoiding Infinite Loops with loopseer technique

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1072]
Hello,

I'm trying to run some code which I know is just a loop running infinitely but I do want to exit this loop (hard coded limit) after it iterated 10 times.
I thought loopseer suppose to do just that but it doesn't seems to stop after 10 iterations but keep going non stop.

My example code:
```
void loop_forever(int a) {
        int i;
        for(i=0;;i++) {
                printf("Test infinite loop");
        }
}
```

Example usage:
```
p = angr.Project(loop_forever, load_options={"auto_load_libs": False})
cfg = p.analyses.CFGFast(normalize = True)
state = p.factory.call_state(addr=0x10438) # 0x10438 = loop_forever function
simgr = p.factory.simulation_manager(state)
simgr.use_technique(angr.exploration_techniques.LoopSeer(cfg=cfg, bound=10))
while len(simgr.active) != 0:
    simgr.step()
    print simgr.active
```

The binary (elf, 32bit arm) can be download here: https://ufile.io/9nym2

**Comment by tyb0807** [comment]
Ok, so I debugged this, and the problem is the argument `stash` is always `None`. Before #888 the exploration technique's `step` method is called after this line in https://github.com/angr/angr/blob/master/angr/sim_manager.py#L319 so everything was fine. @danse-macabre can you take a look at this please? Or just tell me what should be done to fix this.

Thanks

**Comment by danse-macabre** [comment]
@tyb0807 If I remember correctly, this exact problem was discussed in #934. I've posted a possible workaround there, but there must be a better solution to this problem.

**Comment by tyb0807** [comment]
So I guess we should set the default `stash` to `active` instead of `None` now?

**Comment by mor619dx** [comment]
I had tried to add:
```
# hookset.py
    @staticmethod
    def provide_defaults(**defaults):
        def _func_wrapper(func):
            def _defaults_provider(*args, **kwargs):
                for k, v in defaults.iteritems():
                    if k not in kwargs or kwargs[k] is None:
                        kwargs[k] = v
                return func(*args, **kwargs)
            return _defaults_provider
        return _func_wrapper

# sim_manager.py
    @ImmutabilityMixin.immutable
    @HookSet.provide_defaults(stash='active')
    def step(self, n=None, selector_func=None, step_func=None, stash=None,
             successor_func=None, until=None, filter_func=None, **run_args):
                 # ...
```
to the code as written in the post but it didn't seem to solve the problem.
Is there anything else to change in the code?

**Comment by danse-macabre** [comment]
@mor619dx That code was just a sketch of a possible solution. It is by no means a working prototype.
Instead, you could try to set the default `stash` to `active`. This should help.

**Comment by mor619dx** [comment]
I have tried to set the stash to active like so (on the running code):
```
simgr.step(stash='active') 
```
Also tried to change the default of stash in sim_manager.py to:
```
    def step(self, n=None, selector_func=None, step_func=None, stash='active',
             successor_func=None, until=None, filter_func=None, **run_args):
```
Doesn't seem to also solve it

**Comment by tyb0807** [comment]
@mor619dx I've pushed a new code that fixes this issue. But will have to wait for it to be merged.

Thank you for reporting the bug and sorry for the inconvenience

**Comment by mor619dx** [comment]
@tyb0807 I've just tested it, seems to work great!
Thanks for your help @tyb0807 @danse-macabre
