### ISSUE TITLE
DSE symbolic var: size of simfile implicitly restricted in size 

### ISSUE THREAD

**Issue by Usibre** [angr/angr#1076]
Hi, 
When I'm running angr with a symbolic file and the size of the simfile is symbolic, I found out that symbolic execution doesn't work unless I use the value 8*8=64 bits. However, this is implicit and very unclear. printing simgr.errored showed me: ` State errored with "args' length must all be equal" `. 
Maybe an (implicit) convert or a general warning would be good to make sure people don't end up debugging for hours until they start randomly changing numbers or find out about simgr.errored :)

For completion, here is the code I'm talking about: 
```

    # angr project
    self.project = angr.Project(self.binary )
    initstate = self.project.factory.entry_state(args=[self.binary, '/tmp/simfile'])

    # simfilesize
    simfilesize = claripy.BVS('simfilesize', 16*8) # 16*8 doesn't work 8*8 does
    initstate.solver.add(simfilesize > 0)
    initstate.solver.add(simfilesize < 64*8)  

    # simfile
    simfile = angr.SimFile('simfile', size=simfilesize)
    simfile.set_state(initstate)
    initstate.fs.insert('/tmp/simfile', simfile)
    simgr = self.project.factory.simgr(initstate)
    simgr.explore(find=self.find)
```

**Comment by rhelmot** [comment]
Fixed.

I agree that an early warning is better, but 1) simgr.errored is a _crucial_ debugging technique, and people should be drawn to it by the fact that the repr of such a simulation manager will include `(1 errored)`, and 2) we treat bitvector sizes as part of their types. Whenever you create a bitvector, you should be super conscious of what size it is - unless it's a char vector or something, getting it wrong will always give you a type error somewhere down the line.
