### ISSUE TITLE
The caller object eats much memory

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#108]
Hi
I'd like to explore all paths of a give fuction, so I choose the caller object. The tested code is a simple bubble sort, shown as follows.
```
#define BUFF_LEN 6
void bubble_sort(char *buff)
{
  for(int i = 0; i < BUFF_LEN - 1; i++)
    for(int j = i + 1; j < BUFF_LEN; j++)
    {
       if(buff[i] > buff[j])
       { 
         int tmp = buff[i];
         buff[i] = buff[j];
         buff[j] = tmp;
       }
    }
}

```
Then length of `buff `is 6, so I suppose there would be thousands of paths at most.
Below is my testing script.
```
import angr
b = angr.Project("path_explosion")
cfg = b.analyses.CFGAccurate()
target_func = cfg.kb.functions.function(name='bubble_sort')
print target_func
p = b.factory.path()
x = p.state.memory.load(0x1000, 6)
c = b.surveyors.Caller(0x400566, (0x1000, ), start=p)#0x400566 is the entry of bubble_sort 
print tuple(c.iter_returns())
print c
```

I installed Angr in a virtual machine. Before running the testing script, 4.1GB physical memory are cost (8GB in total). The memory consumption increases to 8GB in a few seconds, after I launch the script.  After a few minutes, Angr cashes due to memory exhaustion (may be).

Then I change the length of `buff `into a little bit smaller value, that is 5. Angr gives me result in about 3 minutes as follows (I omitted detailed information of all founded paths for brief).
`<Explorer with paths: 0 active, 0 spilled, 798 deadended, 0 errored, 0 unconstrained, 226 found, 0 avoided, 0 deviating, 0 looping, 0 lost>`

I suppose that the caller object may eat much memory if there are many paths (thousands?) should be explored.

**Comment by rhelmot** [comment]
There is no way around this. This is known as the "state explosion problem" in the literature, and is the reason naive symbolic execution is indefeasible for large applications.

**Comment by brokendragon** [comment]
@rhelmot I agree that path explosion cannot be solved now. But I think thousands of paths are not so explosive that symbolic execution cannot handle. I mean, Angr could be more scalable.

**Comment by rhelmot** [comment]
The state explosion here is not polynomial here - it is exponential. Each time a path goes through the inner loop, it splits in two. After the first loop, there are two paths, after the second, four, after the third, 8, etc.

For BUFF_LEN = 5, there are 4 + 3 + 2 + 1 = 10 loops, so there are 2^10 = 1024 paths in the end.

For BUFF_LEN = 6, there are 5 + 4 + 3 + 2 + 1 = 15 loops, so there are 2^15 = 32768 paths.

**Comment by brokendragon** [comment]
@rhelmot Thanks for your patient explanation.
So can I make the following conclusion: symbolic execution is not a good option for analyzing practical programs due to path explosion. I see that Angr feels difficult to analyze bubble sort thoroughtly even if the input is not long, that is 6 bytes.

**Comment by rhelmot** [comment]
No problem. In general, symbolic execution is a bit of a dumb tool that you need to add a lot of your own human intelligence to in order to solve problems effectively.

I talked for a bit at 32c3 last December about this problem precisely, if you like you can watch that [here](https://youtu.be/XGhg19_GXnM?t=1956).

**Comment by ltfish** [comment]
My two cents: symbolic execution is applicable for analyzing practical programs, as long as you have enough resource (both computational and storage).

In theory, angr uses more memory than some other symbolic execution solutions for the following reasons:

- We don't have a concrete execution engine. All machine code are executed (simulated) in Python code.
- angr is written in Python, over 99%. It's usually not a memory-efficient solution.
- angr is poorly optimized in terms of resource usage. We hardly have any time for optimizing the memory usage, unless it eats up all memory on our giant server (that has more than 128 GB of memory).
- Z3 solver is in the same memory space with angr itself. For complex constraints, Z3 may take an insane amount of memory, and this is not something angr has control of.

Regarding the reasons above, we have an internal branch in development that supports JIT and concrete execution, as well as some effort to make angr more performant (like some static analyses, separated Z3 solver engine, and the super awesome C++-based angr core). However, we cannot make any promise on if or when those components/functionalities will be available. angr's initial goal was making the problem of binary analysis easier and more approachable. It's not, and will never be a silver bullet to all problems in binary analysis. There are many active researches going on in this field. Expecting angr to be the solution to fundamental problems ("analyzing practical programs", without any limit on program size) is a pure illusion.

Saying that, only having 8GB of memory is too little if you want to analyze any practical code symbolically. I would suggest you get least 32 GB of memory no matter what symbolic execution engine you want to use.

Reading some papers in the field can give you some ideas on how to make symbolic execution smarter. You can start from [Mayhem](https://users.ece.cmu.edu/~arebert/papers/mayhem-oakland-12.pdf).

**Comment by zardus** [comment]
I think it's also important to note that there's a middle ground between "symbolic execution is the panacea of program analysis" and "symbolic execution is useless". One of the approaches that @rhelmot  talks about in the 32C3 talk is Veritesting (see: https://users.ece.cmu.edu/~aavgerin/papers/veritesting-icse-2014.pdf). angr includes an implementation of this, and it might actually help in this case.

In general, though, 8 gigs is very little memory. IMO, 32 gigs is too little for reasonable programs. My workstation for angr, for example, has 128 gigs.

**Comment by brokendragon** [comment]
@zardus You gave me a good suggestion, that is buying a powerful workstation before testing large software on Angr. It seems that it's the right time to throw away my poor laptop.

**Comment by zardus** [comment]
lol. For testing purposes, you can also spin up some pretty beefy instances on AWS. But I'd also check out veritesting. It can be used by passing `enable_veritesting=True` to the PathGroup creation.

**Comment by Manouchehri** [comment]
The c4 (compute) instances on EC2 are okay for angr. Just remember that a lot of this stuff is single threaded, so getting a larger instance won't help.

**Comment by ltfish** [comment]
@Manouchehri angr PathGroup supports multithreading! Although CPython has the notorious GIL that prevents you from having a real multithreaded Python program, you can also benefit from that by allowing other threads to execute Python code while one thread waits for Z3 to return results.
