### ISSUE TITLE
The speed of copying memory

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1095]
Hello,

I've had some problems with the speed of code copying memory (using memcpy sim procedure), it mostly happen when symbolic translates his minimal value to a high value and it causes for a very long step (hours).
I've made a simple code (with binaries):
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main() {
        int* ptr = malloc(0x1000000);
        int* ptr2 = malloc(0x1000000);

        if (ptr != NULL && ptr2 != NULL) {
                memcpy(ptr, ptr2, 0x1000000);
                printf("Copy finished!");
        }
}
```
I've also attached an compiled binaries of this code: both arm and x64 elf files: 
[memcpy_large_size.zip](https://github.com/angr/angr/files/2145252/memcpy_large_size.zip)

Running the x64 executable works very fast running in linux ubuntu (./memcpy_large_size) (just to see real life regular run time).
I am trying to run the arm version using angr and when it reach the memcpy sim procedure it takes hours to copy the memory.

Is this a python problem copying memory? Is there anything I can do to make it work faster since this is just copying memory?

Edit: I saw removing the flag:
`angr.options.SIMPLIFY_MEMORY_WRITES` solve this speed problem, what does it do? how does it impact of the exploration / hooking etc..

**Comment by rhelmot** [comment]
SIMPLIFY_MEMORY_WRITES takes every AST we write to memory and shoves it through z3's simplifier to try to make sure we're not storing undue complexity in our memory model. It's interesting that it's the difference between hours and (I'm guessing) seconds...

**Comment by ltfish** [comment]
This is a very interesting finding...

**Comment by salls** [comment]
when I was optimizing stuff for CGC I removed every simplification thing. I think trying to simplify frequently is never worthwhile

**Comment by mor619dx** [comment]
ok, does it mean I should hook malloc and remove the SIMPLIFY_MEMORY_WRITES flag on the run (and maybe bring it back after I allocated the memory). Will it hurt the performance later if some code access that memory?
