### ISSUE TITLE
posix not populating correctly

### ISSUE THREAD

**Issue by Owlz** [angr/angr#110]
Angr folk,

So I'm playing the TUCTF today and I was attempting to run angr against the "WoO2" challenge. Angr appeared to run correctly for the most part. It found some paths, and the output from `posix.dumps(1)` seemed correct. However, the corresponding input from `posix.dumps(0)` wasn't correct at all. This leads me to believe there's some issue with how that SimFile is being populated.

For reference, I didn't do anything fancy for the binary. Simply loaded it up and told it to explore all possibilities.

**Comment by ltfish** [comment]
How is the binary reading user input from stdin? What API is it using?

Also note that discussing challenges in publkic *might be* against rules of this CTF. Feel free to query us on the angr IRC, and we can discuss the issue in private.

**Comment by ltfish** [comment]
Comfirm: this is a bug in SimuVEX and will be fixed in the next release. Thanks for reporting!

I'll close this issue when the corresponding commit is released on SimuVEX.

**Comment by ltfish** [comment]
It's fixed. Please pull the latest version of angr, SimuVEX and claripy!
