### ISSUE TITLE
angr/exploration_techniques/threading.py occured an error

### ISSUE THREAD

**Issue by DreamingD** [angr/angr#1104]
Line 32 "tsimgr = simgr.copy(stashes=dict(simgr.stashes))"report an error.The error description is "TypeError: copy() got an unexpected keyword argument 'stashes'.There was no such error a few months ago.Would you help me solve this problem?

**Comment by rhelmot** [comment]
Duplicate of #1032. Threading is broken right now.

cc, @danse-macabre
