### ISSUE TITLE
Search the binary for instructions with certain mnemonics

### ISSUE THREAD

**Issue by awakened1712** [angr/angr#1108]
I would like to know how to search the entire arm64 binary for certain instructions, let say [CSEL ](https://developer.arm.com/docs/100069/0607/a64-general-instructions/csel). The return should be something like the array of addresses of those instructions.

Any help on this is very much appreciated.

**Comment by ltfish** [comment]
1. Generate a CFG of the binary.
1. Iterate through all nodes in the CFG.
1. For each node in the CFG, you can call `node.block.capstone` to get a capstone basic block representation. You can then access individual instructions from there. Please consult the documentation of capstone-engine to see what attributes you can access.
