### ISSUE TITLE
AngrTranslationError and PyVEXError when Lifter.lift(..., max_size = 0, ...)

### ISSUE THREAD

**Issue by ymjing** [angr/angr#111]
The issue is at Line 46 of lifter.py
`max_size = VEX_IRSB_MAX_SIZE if max_size is None else max_size`

If max_size is 0 at the beginning, it would remain 0 all the way through Line 100:
`irsb = pyvex.IRSB(buff, addr, arch,
                                  num_bytes=max_size,
                                  bytes_offset=byte_offset,
                                  traceflags=traceflags)`
PyVex/libvex does not allow a zero max_size and raises an PyVEXError at Line 50 of pyvex/pyvex/block.py

I guess you guys mean "not max_size" rather than "max_size is None". "not max_size" also returns True when max_size is 0. I changed Line 46 and it seems to work
`max_size = VEX_IRSB_MAX_SIZE if not max_size else max_size`

This is just my guess. I'd like to confirm with you guys about it. Let me know if you need the binary to reproduce the error.

**Comment by rhelmot** [comment]
What behavior would you like to see when you pass max_size = 0? An empty IRSB? An error? This is sort of a weird edge case that doesn't really matter a whole lot in the grand scheme of things.

IMO the correct thing to do is to patch pyvex to return an empty IRSB if max_size = 0.

**Comment by rhelmot** [comment]
Additional consideration - maybe the correct thing is to change nothing at all, or to throw a more specific error from pyvex, since passing max_size=0 will usually indicate a bug in the code calling the lifter.

**Comment by kevinis** [comment]
The caller is angr/knowledge/function.py:96
`block = self._project.factory.block(addr, max_size=self._block_sizes[addr])`

Here is the full trace. 
`File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.py", line 87, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 135, in __init__
    self._analyze()
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 121, in _analyze
    self._handle_entry(entry)
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 144, in _handle_entry
    self._pre_entry_handling(entry, _locals)
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 968, in _pre_entry_handling
    self._update_function_transition_graph(src_simrun_key, simrun_key, jumpkind=jumpkind)
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_accurate.py", line 1572, in _update_function_transition_graph
    )._get_block(ret_addr).codenode if ret_addr else None
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/knowledge/function.py", line 96, in _get_block
    block = self._project.factory.block(addr, max_size=self._block_sizes[addr])
  File "/home/yiming.j/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/lifter.py", line 103, in lift
    traceflags=traceflags)
  File "/home/yiming.j/Workspace/angr-dev/pyvex/pyvex/block.py", line 50, in __init__
    raise PyVEXError("C-backed bytes must have the length specified by num_bytes")
angr.errors.AngrTranslationError: ('Translation error', <class 'pyvex.errors.PyVEXError'>, PyVEXError('C-backed bytes must have the length specified by num_bytes',))`

**Comment by rhelmot** [comment]
Oh jeez!! I thought you were talking about programming using this interface and running into this as a problem of code design, not an actual exception you ran into. Sorry about that, I've been doing a lot of masturbatory interface design lately :(

Yes, that's a bug in the function manager. Can I have the binary to look into this more carefully? My initial guess is it's trying to lift a block for a SimProcedure, which won't work obviously.

**Comment by kevinis** [comment]
Here it is!
[sample.aarch64.elf.zip](https://github.com/angr/angr/files/267162/sample.aarch64.elf.zip)
