### ISSUE TITLE
ARM/Thumb confusion in CFG

### ISSUE THREAD

**Issue by subwire** [angr/angr#1114]
The ARM/Thumb problem is a hard one, but here are a few ideas for improving the situation:
- Allow the user to help CFG out a bit by forcing Thumb or ARM.  This option already exists, but is ignored when Ijk_NoDecode appears.  Most obviously appears when we give CFG a Cortex-M binary (there is only Thumb), currently it will make a ton of functions out of random data with even addresses.
- Use ARM Mapping Symbols, if available https://sourceware.org/binutils/docs/as/ARM-Mapping-Symbols.html
If we have those, this problem is literally solved.  Obviously, this doesn't work for blobs or anything like that, but hey, it's good to have.

**Comment by tyb0807** [comment]
Actually can fix this if we have another arch for Cortex, since Cortex only has Thumb mode?

**Comment by tyb0807** [comment]
@subwire friendly ping!
