### ISSUE TITLE
Can I use angr to list all functions' names and addresses of ndk built binary?

### ISSUE THREAD

**Issue by awskkzl** [angr/angr#1115]
Can I use angr to list all functions' names and addresses of ndk built binary? How?

**Comment by ltfish** [comment]
What’s ndk?

**Comment by awskkzl** [comment]
Android NDK

**Comment by Alexeyan** [comment]
Call the 
`cfg = project.analysese.CFGFast()` 
analysis and then take a look at 
`project.kb.functions.items()`

**Comment by awskkzl** [comment]
Thanks Alexeyan. Here's another question. Every time i used CFGFast() to get the cfg, i always got the error:

> angr.errors.SimProcedureError: static_exits() is not implemented for 'SimProcedure __libc_init'

I can only use CFGAccurate, but it takes million years...
The binary i have is a striped one, when analyse in IDA Pro, functions' name are all start with 'sub_XXXXX', just like part of angr's cfgaccurate function's result:
![image](https://user-images.githubusercontent.com/13219003/42490375-792c3a88-8442-11e8-8336-31e937b39975.png)
I don't know whether i can get all sub functions in a binary or not, and can CFGFast() do this, how to solve the error... Thanks again

**Comment by ltfish** [comment]
That's a bug. Whoever write `__libc_init.py` did not implement `static_exits()` method. You can fix it by implementing that method.

**Comment by rhelmot** [comment]
Side note: is there anything that can be done to simplify that method? It
seems like every implementation of it contains the same boilerplate which
definitely doesn’t belong there imo.

**Comment by ltfish** [comment]
@rhelmot Maybe? But it's not getting annoying enough for me to redesign it though, especially since only a few SimProcedures are adding new exits.

**Comment by yasong** [comment]
Is there another way to get start addresses of all functions? I don't need the CFG, and I only want to get the addresses. By using the CFGFast, it is  too slow when I reverse a binary file more than 50M. Thank you.

**Comment by ltfish** [comment]
> Is there another way to get start addresses of all functions?

If your binary has exported symbols, then yes, you can take a look at these symbols. Otherwise you will need to build a CFG first.

> By using the CFGFast, it is too slow when I reverse a binary file more than 50M.

The upcoming CFG improvement PR (#1092) should give you a huge performance boost on large binaries. You may also switch to PyPy.

**Comment by yasong** [comment]
Yeah, I have tried. It is ok for 23MB binary in PPC, but for 50MB binary, I still have no results. The memory of my PC is 16GB. And The binary file is Cisco IOS bin, which is in PPC or MIPS instruction set. The size of latest version is more than 220MB when be decompressed. So I think you can use them to test this tool. 
When I reverse the MIPS binary, the program throws an error.
```bash
Traceback (most recent call last):
  File "CiscoAngr.py", line 71, in <module>
    main()
  File "CiscoAngr.py", line 46, in main
    analysis(target)
  File "CiscoAngr.py", line 21, in analysis
    cfg = proj.analyses.CFGFast()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 909, in __init__
    self._analyze()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/forward_analysis.py", line 559, in _analyze
    self._post_analysis()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 1460, in _post_analysis
    self._remove_redundant_overlapping_blocks()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 2739, in _remove_redundant_overlapping_blocks
    self.graph.remove_node(b)
  File "/usr/local/lib/python2.7/dist-packages/networkx-2.1-py2.7.egg/networkx/classes/digraph.py", line 523, in remove_node
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node <CFGNode 0x806ea140[20]> is not in the digraph.
```

**Comment by ltfish** [comment]
That bug will be fixed soon (as soon as I have some uninterrupted time in front of my laptop). You can send me the binary so that I can use it as a test case. Thanks in advance.

**Comment by yasong** [comment]
The files are too large to upload to github, so I have sent it through email  to angr@lists.cs.ucsb.edu.
