### ISSUE TITLE
Disassemble code

### ISSUE THREAD

**Issue by valour01** [angr/angr#1116]
Angr is a tool for binary analysis. One way to get the disassembly code that I know is to use cfgfast() and then to iterate every generated basicblock to print out the machine code.

Any other ways to get the disassembly code without generate the control flow graph. You know, when the binary is very large, it will take a lot of time to generate the cfg. Many Thanks

**Comment by rhelmot** [comment]
Performing control flow analysis is the only way of telling what's code and what's not, which is a requirement for safe disassembly. If you'd like to forego that safety you can just start grabbing basic blocks wherever you want to view code.

**Comment by ltfish** [comment]
We are on our way of making CFGFast at least 5 times faster than the current inplementation! You can take a look at PR 1092.
