### ISSUE TITLE
Unlinking/deleting simfile gives error

### ISSUE THREAD

**Issue by Usibre** [angr/angr#1117]
Hi :) 

A binary I tested generated a temp file that it deleted straight after. However, when the file becomes symbolic, deleting the file gave the following error: 
`AttributeError: 'SimFile' object has no attribute 'delete'`
coming from the built in unlink() function. 

I assume this is easily resolved by creating the delete function and removing the simfile from the state (which shouldn't even be necessary) but I'm afraid I am overlooking something. 

`tl;dr`: binary deleting a symbolic file makes angr crash. 

Thanks!

**Comment by ltfish** [comment]
It’s a bug. @rhelmot?

**Comment by rhelmot** [comment]
I'm having a very hard time figuring out what could be causing this - is it possible you have an old version of angr? the bug fixed in https://github.com/angr/angr/issues/1094 could have caused this.

**Comment by Usibre** [comment]
My bad, you are completely right. #1094 fixed it. I was having this bug longer (since before the bugfix) and forgot the pull before creating the issue. Apologies for the mistake, and thank you!
