### ISSUE TITLE
Binary rewriting

### ISSUE THREAD

**Issue by awakened1712** [angr/angr#1118]
What is the API to rewrite the binary as mentioned in [this presentation](https://youtu.be/eqaddt9ssbQ?t=13m25s)?

Does it mean that angr can be used in a similar way as [McSema ](https://github.com/trailofbits/mcsema), i.e. lift the binary into IR, apply optimization/simplification on the IR and then recompile?

**Comment by ltfish** [comment]
Several keywords for Googling: Patcherex, angr’s Reassembler analysis, and angr’s BinaryOptimization analysis.

Lifting the entire binary into IR is definitely doable, but you need to generate a complete CFG first and correctly differentiate code from data, which is not always doable on binaries.
