### ISSUE TITLE
Missing constraints when using STRNE

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1119]
Hello,
I've encounter a case where the solver contain in the state (state.solver) doesn't contain certain constraints when encounter the instruction STRNE (store not equal).
This is my simple function:
![strne_func](https://user-images.githubusercontent.com/7024240/42449268-a79f63aa-8388-11e8-9f93-54b62c086b1c.PNG)

Now when I set a breakpoint (state.inspect.b) on mem_write when BP_AFTER. I have stopped on address `0xEE8`

In the hook I print the constraints using:
```
print state.se.constraints
```
the memory `memory = state.inspect.mem_write_address` is:
`<BV32 reg_r0_3_32 + 0x14>`
 and the constraints are:
```
[<Bool !(reg_r1_5_32 == 0x0)>, <Bool (reg_r0_3_32 + 0x14) <= 0xffffffff>]
```
There is no constrain that r0 must not be 0 (as seen on address `0xEE0`)
therefore this code return true instead of false:
```
reg = memory.args[0]
print reg # <BV32 reg_r0_3_32{UNINITIALIZED}>
print state.solver.satisfiable([reg == 0]) # Return True instead of False
```

On the constraints there should be another constraint something along:
`<Bool !(reg_r0_3_32 == 0x0)>`

This is the vex produced from the above code:
```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I1 t11:Ity_I32 t12:Ity_I32 t13:Ity_I1 t14:Ity_I1

   00 | ------ IMark(0x400ed8, 4, 0) ------
   01 | t0 = GET:I32(r1)
   02 | PUT(cc_op) = 0x00000002
   03 | PUT(cc_dep1) = t0
   04 | PUT(cc_dep2) = 0x00000000
   05 | PUT(cc_ndep) = 0x00000000
   06 | PUT(ip) = 0x00400edc
   07 | ------ IMark(0x400edc, 4, 0) ------
   08 | t13 = CmpEQ32(t0,0x00000000)
   09 | t12 = 1Uto32(t13)
   10 | t14 = 32to1(t12)
   11 | if (t14) { PUT(ip) = 0x400ef4; Ijk_Boring }
   NEXT: PUT(pc) = 0x00400ee0; Ijk_Boring
}
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I32 t15:Ity_I32 t16:Ity_I32 t17:Ity_I32 t18:Ity_I32 t19:Ity_I32 t20:Ity_I32 t21:Ity_I32 t22:Ity_I32 t23:Ity_I32 t24:Ity_I1 t25:Ity_I32 t26:Ity_I32 t27:Ity_I32 t28:Ity_I32 t29:Ity_I32 t30:Ity_I32 t31:Ity_I32 t32:Ity_I32 t33:Ity_I1 t34:Ity_I32 t35:Ity_I32 t36:Ity_I32 t37:Ity_I32 t38:Ity_I32 t39:Ity_I32 t40:Ity_I32 t41:Ity_I32 t42:Ity_I1 t43:Ity_I32 t44:Ity_I32 t45:Ity_I32 t46:Ity_I32 t47:Ity_I32 t48:Ity_I32 t49:Ity_I1 t50:Ity_I1 t51:Ity_I32 t52:Ity_I32 t53:Ity_I1 t54:Ity_I32 t55:Ity_I32 t56:Ity_I1 t57:Ity_I32 t58:Ity_I1 t59:Ity_I32 t60:Ity_I32 t61:Ity_I1 t62:Ity_I1 t63:Ity_I1

   00 | ------ IMark(0x400ee0, 4, 0) ------
   01 | t0 = GET:I32(a1)
   02 | PUT(cc_op) = 0x00000002
   03 | PUT(cc_dep1) = t0
   04 | PUT(cc_dep2) = 0x00000000
   05 | PUT(cc_ndep) = 0x00000000
   06 | ------ IMark(0x400ee4, 4, 0) ------
   07 | t53 = CmpNE32(t0,0x00000000)
   08 | t52 = 1Uto32(t53)
   09 | t23 = GET:I32(a4)
   10 | t54 = ITE(t53,0x00000000,t23)
   11 | PUT(a4) = t54
   12 | PUT(ip) = 0x00400ee8
   13 | ------ IMark(0x400ee8, 4, 0) ------
   14 | t56 = t53
   15 | t31 = Add32(t0,0x00000014)
   16 | if (t56) STle(t31) = t54
   17 | ------ IMark(0x400eec, 4, 0) ------
   18 | t59 = ITE(t53,t54,t0)
   19 | PUT(a1) = t59
   20 | PUT(ip) = 0x00400ef0
   21 | ------ IMark(0x400ef0, 4, 0) ------
   22 | t62 = 32to1(t52)
   23 | t63 = Not1(t62)
   24 | if (t63) { PUT(ip) = 0x400ef4; Ijk_Boring }
   25 | t15 = GET:I32(lr)
   NEXT: PUT(pc) = t15; Ijk_Ret
}
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I32 t15:Ity_I32 t16:Ity_I32 t17:Ity_I32 t18:Ity_I1 t19:Ity_I32 t20:Ity_I32 t21:Ity_I32 t22:Ity_I32 t23:Ity_I32 t24:Ity_I32 t25:Ity_I32 t26:Ity_I32 t27:Ity_I1 t28:Ity_I32 t29:Ity_I32 t30:Ity_I32 t31:Ity_I32 t32:Ity_I32 t33:Ity_I32 t34:Ity_I1 t35:Ity_I1 t36:Ity_I32

   00 | ------ IMark(0x400ee8, 4, 0) ------
   01 | t11 = GET:I32(cc_op)
   02 | t10 = Or32(t11,0x00000010)
   03 | t12 = GET:I32(cc_dep1)
   04 | t13 = GET:I32(cc_dep2)
   05 | t14 = GET:I32(cc_ndep)
   06 | t15 = armg_calculate_condition(t10,t12,t13,t14):Ity_I32
   07 | t17 = GET:I32(a1)
   08 | t16 = Add32(t17,0x00000014)
   09 | t3 = GET:I32(a4)
   10 | t18 = CmpNE32(t15,0x00000000)
   11 | if (t18) STle(t16) = t3
   12 | ------ IMark(0x400eec, 4, 0) ------
   13 | t25 = ITE(t18,t3,t17)
   14 | PUT(a1) = t25
   15 | PUT(ip) = 0x00400ef0
   16 | ------ IMark(0x400ef0, 4, 0) ------
   17 | t35 = 32to1(t15)
   18 | t34 = Not1(t35)
   19 | if (t34) { PUT(ip) = 0x400ef4; Ijk_Boring }
   20 | t9 = GET:I32(lr)
   NEXT: PUT(pc) = t9; Ijk_Ret
}
```

**Comment by rhelmot** [comment]
So, this is expected. This instruction is a conditional store, not a conditional branch, so its effect is not modeled by a state split + constraint. Instead, if you load the data from memory at that location, you will find a value of the form if-then-else(r0 != 14, 0, original_memory).

**Comment by mor619dx** [comment]
@rhelmot I'm not sure I understand it, Isn't CMP then STRNE is logically similar to cmp and str on separate branch?

I'm not sure then where to get the right constraints or am I not suppose to to use state.solver at all, I found the following:
`state.inspect.mem_write_expr`:
`<BV32 if (reg_r0_3_32 == 0x0) then reg_r3_6_32 else 0x0>`
Not sure why this is the expression here.

and `state.inspect.mem_write_condition`:
`<Bool reg_r0_3_32 != 0x0>`
which is in fact what I need, do I create new solver add all the state.solver.constraints and the above constraint and then check if:
```
reg = memory.args[0]
print reg # <BV32 reg_r0_3_32{UNINITIALIZED}>
print state.solver.satisfiable([reg == 0]) # Return True instead of False
```
?

**Comment by ltfish** [comment]
> Isn't CMP then STRNE is logically similar to cmp and str on separate branch?

You are right, but that is not the only way to implement `CMP + STRNE`. VEX chooses to implement it as a _conditional store_, not a _conditional branch_ where only one branch does the store, as you can see from the lifting result:

```
   13 | ------ IMark(0x400ee8, 4, 0) ------
   14 | t56 = t53
   15 | t31 = Add32(t0,0x00000014)
   16 | if (t56) STle(t31) = t54
```

The (conditional) store will only happen when `t56` is not zero.

> There is no constrain that r0 must not be 0 (as seen on address 0xEE0)

The constraint is the guard of the ITE expression `<BV32 if (reg_r0_3_32 == 0x0) then reg_r3_6_32 else 0x0>` that is stored in memory when executing statement 16 `16 | if (t56) STle(t31) = t54`. Unfortunately you cannot extract that condition from `solver.constraints`, as VEX did not model it as a path predicate that leads to conditional branches.
