### ISSUE TITLE
Difference between Dominator and Dominating Set

### ISSUE THREAD

**Issue by shelvenzhou** [angr/angr#1120]
Code in https://github.com/angr/angr/blob/master/angr/analyses/veritesting.py#L578 may confuse the concepts of dominator and dominating set. To my best knowledge, the function which is needed here is `networkx.immediate_dominators()`

**Comment by ltfish** [comment]
Confirmed that this is a bug. Thanks! Do you want to give us a PR, or should I do it?

**Comment by shelvenzhou** [comment]
just a one line fix, you please
