### ISSUE TITLE
Multiple different Problems leading to Symexec .step() running infinite

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#1126]
Hello, 

another day - another headache problem from me. Analyzing a few thousand arm32 files, we stumbled upon an interesting bug which causes the symbolic execution to run infinite with a single `step()`. Sadly, there are multiple problems that lead to this problem.

First the code and the targets:

Starting-Point: `0x7754B9`
Find-Point: `0x007754D4` [JNI-Method]

Setup: 
```python
import logging
logging.basicConfig()
l = logging.getLogger()
l.setLevel(logging.INFO)

import angr

backend = "elf"
binarypath = "933b179091b73a5eb6cbe57639280f4880d3e37eb63f2c295e42f97c22ab70a6"
proj_options = {'auto_load_libs': False, 'main_opts': {'backend': backend}}
project = angr.Project(binarypath, load_options=proj_options, translation_cache = False)

angr_explorer_tech = angr.exploration_techniques.Explorer( \
            find=0x007754d5, \
            find_stash='found', \
            avoid_stash='avoid', \
            num_find=1)

state = project.factory.blank_state(addr=0x7754B9)
simgr = project.factory.simgr([state])
simgr.use_technique(angr_explorer_tech)
simgr.step()
``` 

![ida](https://user-images.githubusercontent.com/12801920/42690540-dc766186-86a4-11e8-95ae-842a7c4b8c7f.png)

```
.text:007754B8 ; djinni::Optional<std::experimental::optional, djinni::Bool>::fromCpp(_JNIEnv *, std::experimental::optional<bool> const&)
.text:007754B8                 WEAK _ZN6djinni8OptionalINSt12experimental8optionalENS_4BoolEE7fromCppEP7_JNIEnvRKNS2_IbEE
.text:007754B8 _ZN6djinni8OptionalINSt12experimental8optionalENS_4BoolEE7fromCppEP7_JNIEnvRKNS2_IbEE
.text:007754B8                                         ; CODE XREF: djinni_generated::NativeDbxExtendedFixedPhotoMetadata::fromCpp(_JNIEnv *,dropbox::product::dbapp::camera_upload::cu_engine::DbxExtendedFixedPhotoMetadata const&)+44↓p
.text:007754B8                                         ; djinni_generated::NativeDbxExtendedFixedPhotoMetadata::fromCpp(_JNIEnv *,dropbox::product::dbapp::camera_upload::cu_engine::DbxExtendedFixedPhotoMetadata const&)+54↓p ...
.text:007754B8                 PUSH            {R4-R6,LR}
.text:007754BA                 MOV             R4, R0
.text:007754BC                 LDRB            R3, [R2]
.text:007754BE                 MOV             R5, R1
.text:007754C0                 MOV             R6, R2
.text:007754C2                 CBZ             R3, loc_7754E4

.text:007754C4                 LDR             R3, =(loc_88D50C - 0x3754CC)
.text:007754C6                 MOV             R0, R1
.text:007754C8                 ADD             R3, PC  ; _ZN6djinni8JniClassINS_4BoolEE11s_singletonE_ptr
.text:007754CA                 LDR             R3, [R3] ; djinni::JniClass<djinni::Bool>::s_singleton
.text:007754CC                 LDR             R3, [R3] ; djinni::JniClass<djinni::Bool>::s_singleton
.text:007754CE                 LDMIA.W         R3, {R1,R2}
.text:007754D2                 LDRB            R3, [R6,#1]
.text:007754D4                 BL              _ZN7_JNIEnv22CallStaticObjectMethodEP7_jclassP10_jmethodIDz ; 
   ...
   ...
.text:007754E4 loc_7754E4                              ; CODE XREF: djinni::Optional<std::experimental::optional,djinni::Bool>::fromCpp(_JNIEnv *,std::experimental::optional<bool> const&)+A↑j
.text:007754E4                 STR             R3, [R0]
.text:007754E6
.text:007754E6 loc_7754E6                              ; CODE XREF: djinni::Optional<std::experimental::optional,djinni::Bool>::fromCpp(_JNIEnv *,std::experimental::optional<bool> const&)+2A↑j
.text:007754E6                 MOV             R0, R4
.text:007754E8                 POP             {R4-R6,PC}

..
...
0x76C772 ; _JNIEnv::CallStaticObjectMethod(_jclass *, _jmethodID *, ...)
```

Problem 1: Exception in explorer, no successors:
```
Replacing explorer.py :: 127
state = self.project.factory.successors(state, num_inst=1).successors[0]

With:
succs = self.project.factory.successors(state, num_inst=1)
                    try:
                        if succs.successors:
                            state = succs.successors[0]
                    except SimIRSBNoDecodeError as ex:
                        if state.arch.name.startswith('MIPS'): 
                        ...
```

The solution may not be handy or sound, even faulty - but it brings the real problem to the top.

```python
Before Step: Active -> [0x7754B9]
After-Step: 
expected: active -> [0x7754E5, 0x7754C5] (At branching location, fallthrough branching)
faulty: active -> [0x7754E5, 0x76C773]
```
The step function at this point executes the entire basic block (which has incorrect boundaries, e.g. does not stop block at `CBZ`. While executing until the `BL` not stoping at `CBZ` it also ignores the `find addr`. Even more problematic, it also ignores setting the `LR` at `BL`. Hitting the return in the successive blocks it starts again at the beginning, thus leading to an un-interruptable infinite loop with a single `step()`.   

The same behaviour can be seen at `CBNZ` as well. 

Binary:
[933b179091b73a5eb6cbe57639280f4880d3e37eb63f2c295e42f97c22ab70a6.zip](https://github.com/angr/angr/files/2192463/933b179091b73a5eb6cbe57639280f4880d3e37eb63f2c295e42f97c22ab70a6.zip)

Any-Ideas?

Best reagrds,
Andreas

**Comment by tyb0807** [comment]
The `cb{n}z` problem is well-known .... (see #514) and was fixed by a bunch of commits in `vex`, `pyvex` and `angr`. But we do not have the API for this feature in `angr` symbolic execution and CFG yet. I'm about to implement it (if @rhelmot doesn't mind).
However, the `bl` being skipped issue is not normal at all...

**Comment by AndyXan** [comment]
Thanks for clarification @tyb0807 

I Wouldn't mind about the incorrect semantics of CB{N}Z if the "find" point would be triggered, or at least after the step filter(..) would be called or anything that would allow me to intervene. The infinite loop is the most significant problem for me. 

At least, from my understanding - i any case, even if wrong - the step should terminate after the `0x7754D5  BL`, or even better - terminate at the `find 0x7754D5`.

**Comment by rhelmot** [comment]
(this feature completely already exists in angr, just set `project.engines.vex.default_strict_block_end = True`)

I'm looking into the explorer issue. I believe it should work regardless of whether basic block ends are strict. It is my staunch belief that everything in angr and using angr should work correctly even if basic blocks don't terminate at certain branches.

**Comment by tyb0807** [comment]
.... Yes you are right, it is indeed already there. I should have read more thoroughly your example. Sorry guys...

**Comment by rhelmot** [comment]
I believe c10452a solves this issue.

**Comment by rhelmot** [comment]
In the future, I believe an even better solution to this problem would be to refactor explorer to do its "windup" not during `filter`, but instead by adding a `num_inst` parameter to the parameters dict during `step` if it believes that otherwise the step will go beyond the target.

Ah how I mourn for the days when we just told people to deal with the fact that you could only provide basic block addresses as find/avoid targets...
