### ISSUE TITLE
It doesn't work when changing the custom_base_addr to customize.

### ISSUE THREAD

**Issue by yasong** [angr/angr#1127]
what's wrong with the following code?
```python
base = 0x60008000
proj = angr.Project(target, auto_load_libs = False, load_options = {'main_opts':{'custom_base_addr': base}})
```
error message.
```bash
  File "/usr/local/lib/python2.7/dist-packages/networkx-2.1-py2.7.egg/networkx/classes/digraph.py", line 523, in remove_node
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node <CFGNode 0x806ea140[20]> is not in the digraph.
```
I think it is caused by a bug in the base address.

**Comment by ltfish** [comment]
Can you please post the binary as well as the full stack backtrace?

**Comment by yasong** [comment]
```python
def analysis(target, base)
    file_out = open('func.txt', 'w+')
    proj = angr.Project(target, auto_load_libs = False, load_options = {'main_opts':{'custom_base_addr': base}})
    cfg = proj.analyses.CFGFast()
    for i in proj.kb.functions.items():
		print >> file_out, hex(i[0])[2:]
    file_out.close()
def main():
	target = 'C3745-IP-test6.BIN'
	base_addr = 0x60008000
	analysis(target, base_addr)
if __name__ == '__main__':
	main()
```
```python
Traceback (most recent call last):
  File "CiscoAngr.py", line 76, in <module>
    main()
  File "CiscoAngr.py", line 49, in main
    analysis(target, base_addr)
  File "CiscoAngr.py", line 22, in analysis
    cfg = proj.analyses.CFGFast()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/analysis.py", line 108, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 909, in __init__
    self._analyze()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/forward_analysis.py", line 559, in _analyze
    self._post_analysis()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 1460, in _post_analysis
    self._remove_redundant_overlapping_blocks()
  File "/usr/local/lib/python2.7/dist-packages/angr-7.8.7.1-py2.7.egg/angr/analyses/cfg/cfg_fast.py", line 2739, in _remove_redundant_overlapping_blocks
    self.graph.remove_node(b)
  File "/usr/local/lib/python2.7/dist-packages/networkx-2.1-py2.7.egg/networkx/classes/digraph.py", line 523, in remove_node
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node <CFGNode 0x806ea140[20]> is not in the digraph.
```
[C3745-IP-test6.zip](https://github.com/angr/angr/files/2195740/C3745-IP-test6.zip)

**Comment by ltfish** [comment]
Umm can you try the latest version of angr on GitHub? I think that bug has been fixed in PR #1113.

**Comment by yasong** [comment]
Yeah, it works well. Thank you.

**Comment by yasong** [comment]
I found that the costom_base_addr didn't work. The output of function address is not the custom_base_addr. Is something wrong with the code posted above?

**Comment by rhelmot** [comment]
It's hard to tell without your binary but my guess is that your binary is not position-independent, and thus can't be rebased at a custom address.

**Comment by yasong** [comment]
I have posted the binary named C3745-IP-test6.zip in the above.

**Comment by ltfish** [comment]
Your binary is not a PIE. It cannot be rebased.

**Comment by yasong** [comment]
When the router load this binary file, it's base address is changed. I think angr should change the base address no matter whether the binary of embedded device is a PIE or not.

**Comment by ltfish** [comment]
> I think angr should change the base address no matter whether the binary of embedded device is a PIE or not.

How so? I don't think it is possible to relocate a non-PIE ELF, otherwise all the static pointers inside that binary will be broken after a relocation.

**Comment by yasong** [comment]
@ltfish This file is Cisco router IOS, when it is loaded into the router, the base address is not as the number in the readelf show 0x80008000, but it is changed into 0x60008000. If the base address is not  changed some references is broken. Maybe it is the Cisco to prevent us from reversing the IOS. When using IDA open this file, you must change the base address into 0x60008000 not 0x80008000, otherwise, the references of data are wrong.

**Comment by rhelmot** [comment]
I've implemented a feature to resolve this: you may now specify `force_rebase=True` in the binary options, and it will override the initial refusal to rebase the object.

However, since angr is heavily in flux right now, I've only been able to make this change on the `py3k` development branch. This is expected to merge within the next week.
