### ISSUE TITLE
Question: Caller-Simprocedure

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#1135]
Hello, not a bug this time around - just a short question.

I want to skip indirect-calls in ARM32, e.g. `BLX R3` with R3 being an address only known at runtime. 

A working solution is 

```python
project.hook(addr=0x400e5b, hook=indirect_blx_hook, length=2)

def indirect_blx_hook(state):
    if state.addr % 2 == 0:
        state.regs.r14 = state.regs.pc + 4 # set LR
    else:
        state.regs.r14 = state.regs.pc + 2 # set LR
```

This method requires an additional length parameter in `hook` which, ofc has to be `thumb/arm` sensitive.

My question is, if it is possible to address this more generically with the Stubs proecudure 'Caller' which gets the return unconstrained hook as target. Or any other more appropriate solution. Couldn't get it to work

Greetings,
Andy

**Comment by AndyXan** [comment]
I'm closing this as I found a tradeoff / good solution for my case:

```python
project.hook(addr=0x400e5b, hook=indirect_blx_hook)

    l.info("Custom ARM32 Hook executed")

    if state.thumb:
        state.regs.pc = state.regs.pc + 2
        state.regs.r14 = state.regs.pc
    else:
        state.regs.pc = state.regs.pc + 4
        state.regs.r14 = state.regs.pc
```

This circumvents the length specification and is more generic, or in other words - the pc incrementation is left in the responsibility of the specific hook, which I like way more.

The only remaining question is if this would've been possible with already existing Sim-Procedures (e.g. Caller) which I did not get to work properly.

**Comment by rhelmot** [comment]
I don't think caller is designed for this situation. Most established simprocedures are meant to actually return from the function they are hooked in once they finish.

**Comment by AndyXan** [comment]
So then I suppose, my solution here is already close to it's optimum. Hopefully there are no indirect jumps into no ret functions as the last instruction of a function..

Thanks @rhelmot  /closed
