### ISSUE TITLE
Failed jumptable resolution leads to CFG exception

### ISSUE THREAD

**Issue by mgsb** [angr/angr#1140]
I'm trying to run CFGFast on a relatively small Thumbv2 binary. During the resolution of a particular jump table, claripy is unable to solve for a particular minimum:

```
angr/local/lib/python2.7/site-packages/claripy/frontends/light_frontend.pyc in min(self, e, extra_constraints, exact)
     58             return self._solver_backend.min(e)
     59         except BackendError:
---> 60             raise ClaripyFrontendError("Light solver can't handle this min().")
     61 
     62     def solution(self, e, v, extra_constraints=(), exact=None):

SimSolverModeError: ('Translated claripy error:', <class 'claripy.errors.ClaripyFrontendError'>, ClaripyFrontendError("Light solver can't handle this min().",))
```
This stems from CFG's jumptable resolver:
```
angr/local/lib/python2.7/site-packages/angr/analyses/cfg/indirect_jump_resolvers/jumptable.pyc in resolve(self, cfg, addr, func_addr, block, jumpkind)
    192                 jump_table = [ ]
    193 
--> 194                 min_jump_target = state.se.min(jump_addr)
    195                 max_jump_target = state.se.max(jump_addr)
    196 
```
I understand that sometimes these constraints cannot be solved, but this seems like the kind of error that could be handled and discarded in CFGFast in order to yield a best-attempt CFG.

The binary is attached (note that the majority of the 4.4M is dwarf data).
[mpex.zip](https://github.com/angr/angr/files/2215466/mpex.zip)

**Comment by subwire** [comment]
Oh snap, this seems to be fixed as of #1234 because this is... actually a Cortex-M4 binary!
