### ISSUE TITLE
How to regenerate a function in a binary file.

### ISSUE THREAD

**Issue by awskkzl** [angr/angr#1141]
For example, I have a function's address. It has many basic blocks. I regenerated a different kind of control flow based on these blocks. How can I regenerate the binary?
To clear express what I want to do. A function has five blocks. 1 to 2 to 5, 1 to 3 to 4 to 5.(Block 1 has two branches). If the new CFG is 1 to 2 to 5, 1 to 4 to 5(delete block 3). I know i can rewrite by change the bytecode of opcode **bl**. But if a function has lots of blocks, how can i regenerate the binary. If I can't do this with angr, can I use angr to build a dot file or other kind of file based on the new control flow, which can be used to compare CFG similarity?

**Comment by ltfish** [comment]
While we don't support refinement of the CFG, you can always modify the graph by yourself! Take a look at `cfg.graph`, which is a `networkx.DiGraph` instance. You can make whatever modifications you want on the graph directly. Your modifications may include adding or removing blocks, adding or removing edges (note that edges have properties on them), etc.

**Comment by AndyXan** [comment]
We're doing something quite similar. Our CFG entirely comes from IDA, converted to angr datastructures. For the plotting / dot part:

```python

        dot_path = os.path.join(tempfile.gettempdir(), '{}.dot'.format(self.name))
        png_path = os.path.join(tempfile.gettempdir(), '{}.png'.format(self.name))

        pygraphviz_graph = networkx.drawing.nx_agraph.to_agraph(self.graph) # e.g. networkx.digraph
        pygraphviz_graph.node_attr['shape'] = 'box'
        #pygraphviz_graph.node_attr['labeljust'] = 'l'

        pygraphviz_graph.layout(prog='dot')
        pygraphviz_graph.draw(dot_path)
```

**Comment by awskkzl** [comment]
@AndyXan Thanks, Andy. I use 

> networkx.drawing.nx_agraph.write_dot(G_recover, path)

G_recover is the a networkx.DiGraph() object, I saved it as a **.dot** file
It works same.
