### ISSUE TITLE
angr-utils is out-of-date

### ISSUE THREAD

**Issue by BJY-SHU** [angr/angr#1143]
![image](https://user-images.githubusercontent.com/38481747/43068017-bb6a9c88-8e9b-11e8-9ee7-af3aa9e74b1c.png)
Hello, I have a question, when I output CFG pictures, why the basic block does not contain assembly information, here only debug information.The edge colors in CFG are not red and green. Thank you.With some of my code and screenshots.

cfg=p.analyses.CFGAccurate(fail_fast=True,starts=[0x400647],initial_state=start_state,
context_sensitivity_level=2,keep_state=True,call_depth=100,normalize=True)
    plot_cfg(cfg,"qq",asminst=True, format ="png",vexinst=True, debug_info=True, remove_imports=False, remove_path_terminator=False)

**Comment by zardus** [comment]
It looks like you might be using angr-utils, which, while a really cool project, we don't maintain. You'd have to ask @axt. You can also try angr-management.

**Comment by BJY-SHU** [comment]
Thank you very much for your reply. I hope you can give me more help.

**Comment by zardus** [comment]
That's all I got. You should try angr-management, probably by running it in docker using the `run-docker.sh` script in the angr-management repository.

**Comment by cq674350529** [comment]
@BJY-SHU Since the module `bingraphvis` used in `angr_uitls` is not kept update with `angr`, maybe you can update some code snippet by yourself.

**Comment by BJY-SHU** [comment]
@cq674350529 @zardus Thank you all very much for your help.

**Comment by zardus** [comment]
Please use `run-docker.sh` (
https://github.com/angr/angr-management/blob/master/run-docker.sh) from
*outside* of the angr-management dockerfile. It'll properly launch the
docker container, and as long as you're running X and Linux, you should be
okay. For MacOS, there's a MacOS version as well.

**Comment by BJY-SHU** [comment]
@zardus Hello, I use docker to run angr-management still can not save the cfg to the specified address. Click on the button to select the save location and save, but still can not find the file in the save location.

**Comment by rhelmot** [comment]
I can't reproduce your issue. I can save an image and it appears in the
filesystem.

Make sure if you're running inside the docker container, you're saving
somewhere accessable to your host filesystem, or you're reading it from
inside the docker.

**Comment by BJY-SHU** [comment]
@zardus @rhelmot I found the cause of the problem. Save the file as: picture.png or picture.bmp. not picture.png. The suffix should be added. Thank you very much for your help.
