### ISSUE TITLE
Questions about CFG in angr Management

### ISSUE THREAD

**Issue by BJY-SHU** [angr/angr#1146]
![image](https://user-images.githubusercontent.com/38481747/43128026-83d69024-8f63-11e8-914b-67d6c28b9297.png)
Hello, why can't save the image button, choose the save address, but there is no saved CFG image at the address. In addition, the accuracy of cfgaccurate in the example which is more obvious?How does the combination of cfgfast and cfgaccurate work? How to use the cfg node generated by cfgfast as the starting point of cfgaccurate and display cfg images with angr-mananger? how to use it in the angr-mananger tool? Can only one cfg image be displayed at the moment?

**Comment by ltfish** [comment]
> why can't save the image button, choose the save address, but there is no saved CFG image at the address.

Are you asking why the "Save image to..." button does not save an image of the current disassembly for you? Please check if there is any error output in the console where you ran angr management.

> In addition, the accuracy of cfgaccurate in the example which is more obvious?

I'm not sure what you mean.

> How does the combination of cfgfast and cfgaccurate work?

You cannot combine `CFGFast` and `CFGAccurate`.

> How to use the cfg node generated by cfgfast as the starting point of cfgaccurate and display cfg images with angr-mananger? how to use it in the angr-mananger tool? Can only one cfg image be displayed at the moment?

Good question. Currently this is not supported (i.e., you cannot display a `CFGAccurate` graph in angr management), but you are welcome to implement it by yourself, using the exact same infrastructure.


PS: Please make the title of your issue more descriptive. Claiming the urgency of your issue *does not* make other people respond faster, if not slower.

**Comment by BJY-SHU** [comment]
@ltfish The picture shows some information that appears when the binary file is read. There is no error message when clicking on the save picture button. It is possible to choose the location of the saved file, but the saved file is not found at the location.
![image](https://user-images.githubusercontent.com/38481747/43237652-5601391e-90bd-11e8-8381-ff8de90f1537.png)
