### ISSUE TITLE
ImportError: No module named simuvex

### ISSUE THREAD

**Issue by summerban** [angr/angr#1156]
I have use 
```
    mkvirtualenv angr && pip install angr 
```
to install angr 
but when I tried to import simuvex,i faced a question
```
ImportError: No module named simuvex
```
i tried to use  
```
    pip Install simuvex 
```

but when I finshed that i faced another question
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simuvex/__init__.py", line 1, in <module>
    from angr.sim_state import SimState
ImportError: cannot import name SimState
```

How can I resolve it
thanks

**Comment by rhelmot** [comment]
Simuvex is not used anymore. If you found a tutorial that told you to use simuvex, that tutorial is badly outdated.

**Comment by summerban** [comment]
but if I had to use this function,what should I do ,thanks

**Comment by rhelmot** [comment]
You can't use simuvex. Everything in it was migrated to angr. [https://docs.angr.io/MIGRATION.html](This document describes the migration).

**Comment by summerban** [comment]
thanks for you reply, maybe i should install lower version angr to satisfied

**Comment by ltfish** [comment]
You should really *not* use simuvex. *Everything* in simuvex are migrated to angr since a year ago. If your tutorial (or whatever document you are following) references simuvex, don't use that tutorial. You can manually port your code to the new angr, which should be fairly straightforward.

**Comment by summerban** [comment]
thanks for your advice,Could you please introduce a great tutorial for me to study angr,Thanks

**Comment by ltfish** [comment]
- https://github.com/angr/angr-doc
- https://github.com/jakespringer/angr_ctf
