### ISSUE TITLE
Convenient Way to permanently attach data to states 

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#1159]
Hello Guys,

having another question here. I'm looking for a convenient way to attach arbitrary (primitive) data like lists or identifiers to states. The use case here is a custom explorer which strictly follows a predefined path. If initializing `simgr`with a single `state` this is no problem at all, as I can pass the path to the custom explorer. However, when having more states with different paths this leads to the necessity to establish an association between an arbitrary state during the sym-execution and the path it shall follow.  

The closest thing I found to this is to write a SimPlugin, which seems to be a bit overkill for the desire to attach a simple list or even an identifier would do (initial uuid for instance). Do you know of a convenient way to do this?

regards, 
Andy

**Comment by ltfish** [comment]
What's the problem with using `SimStateGlobals` in this case?

**Comment by rhelmot** [comment]
To elaborate: `state.globals` is a dict* which is shallow-copied from state to successor state, so you can store an object in state.globals and the same reference to that object will be present on all successors to that state.

* not actually a dict but acts like one
