### ISSUE TITLE
angr cannot find the answer for fauxware written in c++

### ISSUE THREAD

**Issue by kevinkoo001** [angr/angr#1169]
Hi, I wrote a simplified version of fauxware both in C and in C++, which only checks a password. However angr was not able to find the password, SOSNEAKY, for the one written in c++. Is this because angr does not fully support `stdlibc++` yet or I might be doing something wrong?

```
// fauxware2.c - A simplified fauxware written in C
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

char *sneaky = "SOSNEAKY";

int authenticate(char *password) {
	// evil back d00r
	if (strcmp(password, sneaky) == 0) 
		return 1;
	else
		return 0;
}

int accepted() {
	printf("Welcome to the admin console, trusted user!\n");
}

int rejected() {
	printf("Go away!");
	exit(1);
}

int main(int argc, char **argv) {
	char username[9];
	char password[9];
	int authed;

	username[8] = 0;
	password[8] = 0;

	printf("Username: \n");
	read(0, username, 8);
	printf("Password: \n");
	read(0, password, 8);

	authed = authenticate(password);
	if (authed) 
            accepted();
	else 
            rejected();
    return 0;
}
```

Here is the same version of fauxware written in c++.
```
// fauxware.cc - A simplified fauxware written in C++
#include <iostream>
#include <cstring>
#include <cstdlib>

std::string sneaky = "SOSNEAKY";

int authenticate(std::string username, std::string password) {
	// evil back d00r
	if (std::strcmp(password.c_str(), sneaky.c_str()) == 0) 
           return 1;
	else
	   return 0;
}

int accepted() {
	std::cout << "Welcome to the admin console, trusted user!\n";
}

int rejected() {
	std::cout << "Go away!";
	exit(1);
}

int main(int argc, char **argv) {
	std::string username;
	std::string password;
	int authed;

	std::cout<<"Username: \n";
        getline(std::cin, username);
	std::cout<<"Password: \n";
        getline(std::cin, password);

	authed = authenticate(username, password);
	if (authed) 
            accepted();
	else 
            rejected();

    return 0;
}
```

And I set `auto_load_libs` as `True` when loading a binary and used `full_init_state` instead of `entry_state` when initializing a state.

```
import angr

def fauxware(binpath):
    p = angr.Project(binpath, load_options={"auto_load_libs": True})

    simFile = angr.SimFile('/dev/stdin')
    state = p.factory.full_init_state(stdin=simFile)

    while True:
        succ = state.step()
        if len(succ.successors) == 2:
            break
        state = succ.successors[0]

    state1, state2 = succ.successors
    input_data = state1.posix.stdin.load(0, state.posix.stdin.size)
    print state1.solver.eval(input_data, cast_to=str)
    print state2.solver.eval(input_data, cast_to=str)

if __name__ == '__main__':
    fauxware('fauxware2')
    fauxware('fauxware_cc')
```

Note that both were compiled with `gcc` and `ld.bfd` in ELF executable for `x86-64`, and dynamically linked. Thanks!

**Comment by ltfish** [comment]
angr does not have enough function summaries (SimProcedures) implemented for C++. We also did not spend enough time implementing and testing the support of C++ programs of angr.

**Comment by kevinkoo001** [comment]
Okay, I thought angr implements some of important functions (as SimProcedures) like cin because the `wyvern` [example](https://github.com/angr/angr-doc/blob/master/examples/csaw_wyvern/solve.py) was a 64-bit c++ binary. Thanks for the answer. 👍

**Comment by ltfish** [comment]
Definitely not cin, but maybe we should have...

It all boils down to the manpower issue.

**Comment by kevinkoo001** [comment]
A general question. Putting aside a `libstdc++` case, is every library required to have function summaries (SimProcedures) to be handled properly? If so, `load_options={"auto_load_libs": True}` only loads the  procedures of pre-defined libraries? As it is very common for a binary to employee multiple shared libraries, do we have to compile a statically-linked executable to find an input to reach a particular state (either in the executable or in the library) with symbolic execution in angr?  Thanks again!

**Comment by ltfish** [comment]
If you have all underlying syscalls implemented, *and* correctly simulate the initialization of libstdc++, then no, you don't need to implement all function summaries.

In order to support cin, I believe the latter is the culprit: You should be able to execute related code in libstdc++ directly as long as the initialization of libstdc++ is done correctly in angr.

**Comment by ltfish** [comment]
One of the issues we fixed before that was related to C++ program support: https://github.com/angr/angr/issues/536

Everything boils down to syscalls support and environment emulation in the end.

**Comment by rhelmot** [comment]
angr implements a full implementation of the Linux dynamic loader (CLE) so
it is not necessary to have simprocedures for everything. However, diving
deep into libraries for simple IO routines is a great way to get lost
really fast. The solution here will depend on how exactly your test case
fails. If it claims to have exhausted the state space without finding the
correct case, then that’s a bug in either a) our syscall support, b) our
implementation of relocations in CLE or c) our thread-local storage
implementation. If it blows up with a state explosion, then you just need
more simprocedures.

**Comment by rhelmot** [comment]
Actually, I looked at your code more carefully and I don’t think that’ll
work. In the C version, the first symbolic branch will definitely be as a
result of the string comparison, but here, the first symbolic branch will
probably be well before that, in the STL’s code for parsing input. You need
to use a proper find/avoid condition or attempt to exhaust the state space.

**Comment by kevinkoo001** [comment]
It's more clear now. So the libraries that implement underlying system calls need to be pre-defined in `SimProcedures`. Yes, I have tried it with a `find`/`avoid` condition but it could not reach the state of my interest. It ended up with the following error trace after a long run. 

```
File "/home/kevinkoo001/fuzzbox/symbolicExec.py", line 275, in fauxware
    sm.explore(find=(0x400f03,), avoid=(0x400f0a,))  # fauxware_cc
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_manager.py", line 238, in explore
    self.run(stash=stash, n=n, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_manager.py", line 260, in run
    self.step(stash=stash, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/misc/hookset.py", line 57, in __call__
    result = next_hook(self.func.im_self, *args, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/exploration_techniques/explorer.py", line 101, in step
    return simgr.step(stash=stash, extra_stop_points=base_extra_stop_points | self._extra_stop_points, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/misc/hookset.py", line 60, in __call__
    result = self.func(*args, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/misc/immutability.py", line 24, in _wrapper
    if method(self, *args, **kwargs) is not self:
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_manager.py", line 341, in step
    successors = self.step_state(state, successor_func, **run_args)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_manager.py", line 362, in step_state
    successors = self.successors(state, successor_func, **run_args)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_manager.py", line 401, in successors
    return self._project.factory.successors(state, **run_args)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/factory.py", line 61, in successors
    return self.project.engines.successors(*args, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/hub.py", line 128, in successors
    r = engine.process(state, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/hook.py", line 51, in process
    return self.project.factory.procedure_engine.process(state, procedure, force_addr=force_addr, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/procedure.py", line 31, in process
    force_addr=force_addr)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/engine.py", line 55, in process
    self._process(new_state, successors, *args, **kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/engines/procedure.py", line 65, in _process
    inst = procedure.execute(state, successors, ret_to=ret_to)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/sim_procedure.py", line 169, in execute
    r = getattr(inst, inst.run_func)(*sim_args, **inst.kwargs)
  File "/home/kevinkoo001/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/procedures/libc/ungetc.py", line 17, in run
    self.state.posix.fd[fileno]._pos -= 1
AttributeError: 'SimFileDescriptorDuplex' object has no attribute '_pos'
```

Speaking of C++, some constructor functions initialize global objects even before `main()` (i.e., function pointers in a `.init_array` or `.ctors` section). If I am not mistaken, I guess it would not be problematic as CLE has been fully implemented in angr, right? @Itfish and @rhelmot, thanks for your answers!

**Comment by rhelmot** [comment]
I just pushed a fix for that bug, which had already been reported as #1167.

Yes, we will run initializers if you're using a full_init_state.
