### ISSUE TITLE
Statically following dereferenced variable in a program

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1170]
Given the very simple case of a larger problem:

```
#pragma optimize("", off)
void main()
{
	int *x;
	*x = 24;
	malloc(*x);
}
```
Which compiles to:
![idard](https://user-images.githubusercontent.com/23474424/43841013-cf4f5d92-9b2a-11e8-9086-6ce4b654a574.PNG)

I want to find the size of the allocation at 0x1045C (which storted at R0 up to that point).  
Using Reaching Definitions I can follow `R0` to be defined by `R3` in 0x10458, and then to follow R3 to be defined at 0x10454 by `[R3]`.
However, from there, things become difficult - using Reaching Definitions I can't find any way to make the next step to 0x1044c, where `[R3]` is assigned. 
I believe that the root cause of the problem is that there is no specific memory address that angr can assign to the variable. 

Do you have any idea of how can I connect line 0x10454 with 0x1044c, using Reaching Definitions or any other method?
Or generally any other idea how can I find with angr the source of the allocation at 0x1045C?

**Comment by ltfish** [comment]
> However, from there, things become difficult - using Reaching Definitions I can't find any way to make the next step to 0x1044c

The problem is that `ReachingDefinitionAnalysis` does not make any attempt to resolve unknown pointers. To implement it correctly, pointer aliasing analysis is required, which I'm reluctant to do unless there is a pressing need (the typical "this is left as an exercise to the reader" thing ;) ).

**Comment by ltfish** [comment]
As a quick hack, you might want to just assign a random value (which should be a memory pointer that is not overlapping with any existing memory region) to `R3` when you are writing to it, which should allow you to obtain a connection from `R2` to `R3` at instruction `0x1044c`.
