### ISSUE TITLE
Unsupported Operation + Resilience = No Find?

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#1174]
Hello guys, 

having another basic question here. We're encountering an unsupported operation in vex `Iop_SqrtF64`. When adding `state.add_options(angr.sim_options.resilience)` to the state options the application does not crash, which is good - however the execution is not skipped or bypassed as I would have expected it - it just stops and does not move the program counter any further, instead being stuck at the address of the state where the error occurred.

This again leads to an infinite state in `run` as it never hits the target addr. So, the first question is - how can i circumvent this behaviour without having to implement the unsupported operation. The resilience options seemed to be there for just exact that reason.

The second question is, any tips for implementing such operations (ofc. with pull request if successful)? Code I seen so far goes very deep into core implementations of the vex engine.

**Comment by ltfish** [comment]
Regarding your first question, can you please share your binary? I don't think I can know what's going on without debugging it...

**Comment by zardus** [comment]
The Oppologist exploration technique can also handle running the single
instruction in Unicorn engine, if you don't need the results to be symbolic
(which is likely impossible for sqrt anyways).

**Comment by AndyXan** [comment]
Ok, sorry guys. I retried my code from yesterday - and it worked as I assumed it to work and I don't know why it didn't yesterday. Might be lack of sleep.

Added the resilience options today in the state constructor instead of `initial_state.options.add(..) and it worked like a charm as I originally assumed it would. 

```python
find_addrs = 0x100062B8C
project.factory.block(0x100062b18).vex.pp()
initial_state = project.factory.blank_state(addr = 0x100062b18, add_options = angr.sim_options.resilience)
angr_explorer_tech = angr.exploration_techniques.Explorer(find=find_addrs, find_stash='found', avoid_stash='avoid', num_find=1)
simgr = project.factory.simgr(initial_state)
simgr.use_technique(angr_explorer_tech)

In [2]: simgr.run()
INFO:angr.sim_manager:Stepping active of <SimulationManager with 1 active>
INFO:angr.engines.vex.irop:Using our imagination for op Iop_SqrtF64
INFO:angr.engines.vex.irop:...failed to make op
ERROR:angr.engines.vex.irop:Unsupported operation: Iop_SqrtF64
INFO:angr.engines.engine:Ticked state: <IRSB from 0x100062b18: 1 sat>
Out[2]: <SimulationManager with 1 found>
```

Sorry again for not testing thoroughly and thanks for the help /closed
