### ISSUE TITLE
Reaching definition in thumb mode

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1176]
Currently reaching definition in ARM thumb node is not very reliable, because of the implementation of vex in thumb mode. 

For example, given the following instruction:
`00414CC6 49 46       MOV             R1, R9`

The vex with the optimization level 0 (as reaching definition has it):
`block = p.factory.block(0x00414CC6, opt_level=0, thumb=True)`
`block.vex.pp()`
Output:
```
   00 | ------ IMark(0x414cc6, 2, 1) ------
   01 | t0 = 0x00000000
   02 | PUT(itstate) = t0
   03 | t1 = 0x00000001
   04 | t2 = GET:I32(v6)
   05 | t7 = GET:I32(r1)
   06 | t8 = CmpNE32(t1,0x00000000)
   07 | t6 = ITE(t8,t2,t7)
   08 | PUT(r1) = t6
   09 | PUT(ip) = 0x00414cc9
```
We can see that R1, that should be dependent only on R9 (v6) [line 04 in vex], also dependent on it's previous definition [line 05 in vex], when it clearly seen that it will never use it as a definition.

**Comment by ltfish** [comment]
We are not going to change how VEX lifts code. Our current solution in the decompiler is using `opt_level=1` and `cross_insn_opt=False`. Seems to work well.
