### ISSUE TITLE
Empty "accessed_data_references" in CFGNode?

### ISSUE THREAD

**Issue by GitZChen** [angr/angr#1177]
Hi!

I am trying to analyze the "encrypt" function of a binary to figure out all possible memory offsets of char array "key", assuming that I already know the exact location of the base address of "encrypt".

Example:
```c
void encrypt(FILE *in, FILE *out, char *key){ 
    /* initialize two buffers (in & out),
        passes key into OpenSSL struct,
        and encrypts file block by block */ 
}
```
(Clarification: "key" may not be passed in as an argument as shown. It could also be generated randomly within the function. My analysis should work against any scenario, and it is best if I am able to trace to where the OpenSSL struct is also.)

Here's my script: 

```python
cfg = project.analyses.CFGAccurate(keep_state=True)
cfg_fast = project.analyses.CFGFast()

func_manager = cfg.functions
funcs = func_manager.values()

# Currently I'm running on a binary w/ debugger info included, so I can do:
encrypt_func = [func for func in funcs if func.name == 'encrypt'][0]

/* skipping steps to get relevant blocks and cfg_nodes of interest */ 
blocks = ...
cfg_nodes = ...
cfg_fast_nodes = ...
```
However:
- It seems that the `cfg_fast_node.accessed_data_references` are all empty;
<img width="594" alt="screen shot 2018-08-15 at 16 30 14" src="https://user-images.githubusercontent.com/18753200/44178872-224a1e00-a0a9-11e8-9b10-b3f1955a07c9.png">

- `project.analyses.VariableRecovery` doesn't contain data on heap, per #1173 ; and

- `cfg_node.[input_state + final_states].solver.get_variables('mem')` seem to only yield uninitialized memory.
<img width="452" alt="screen shot 2018-08-15 at 16 29 09" src="https://user-images.githubusercontent.com/18753200/44178875-25450e80-a0a9-11e8-879b-e6bd203f8057.png">

Am I doing something wrong, and is there any way to achieve what I want to do with angr?

Thanks!

**Comment by rhelmot** [comment]
You need to set `collect_data_references=True` in the CFGFast constructor.

**Comment by ltfish** [comment]
@rhelmot beats me to it.

**Comment by GitZChen** [comment]
Thank you so much! 

It can collect data references now, but somehow there's still nothing relevant to the "encrypt" function?

As shown, `cfg_fast_result.insn_addr_to_memory_data` gives a bunch of output, but nothing in the addr space of the encrypt function.

<img width="762" alt="screen shot 2018-08-15 at 17 08 55" src="https://user-images.githubusercontent.com/18753200/44179823-f5e4d080-a0ad-11e8-8765-f658b4cb7b75.png">

Also, can I get a data flow graph of some sort to trace to the openssl graph that used the "key" variable? I can't seem to find much documentation on how to use the output of the DDG analysis?

**Comment by ltfish** [comment]
What's the `encrypt` function look like?

Please note that the data references that CFGFast collects by default only contain static references -- in other words, they do not contain references to stack variables or heap variables. Take a look at OllyDbg or IDA's cross reference, CFGFast's data references are closer to that.

Based on your description, what you need is some sort of data-flow tracking support. You may use DDG, which works on an simulated concrete execution output (CFGAccurate). DDG is not very documented, but it does come with a lot of comments in its code. Help yourself and read the comments in ddg.py at least. You may also use the new `ReachingDefinitionAnalysis` which does pure static data-flow analysis on individual functions.

**Comment by GitZChen** [comment]
Thanks for the quick reply!

To answer your question about the `encrypt` function - the point of me writing this analysis is to be able to find all possible locations of "key" (superset - wrong key is fine, but omitting key ideally should not happen) without knowing the specifics of the encrypt function, so that I can save all possible keys and try them later. (I am searching all char/int arrays, block memory locations, etc.)

You are 100% correct in stating that I need some sort of data-flow tracking - I am specifically looking to get the Data Flow Graph (by static analysis), so that I can manipulate it and find the relative offsets of the variables-of-interest later.

From your (very helpful) description of the DDG analysis, I now think that it might not be what I need, since DDG comes from dynamic analysis of (symbolically executing) the given binary, thus cannot (theoretically and for larger binaries) guarantee a fully complete graph of all possible scenarios.

I haven't had the time yet to deeply search your ReachingDefinitionAnalysis API, but are you doing inter- or intra- procedural analysis? And since ReachingDefinitionAnalysis is essentially the precursor to generating a full data flow graph, do angr already have (or planning to have in the near future) any support for statically generating data flow graphs? (If you have something like an early alpha, I'd be more than happy to contribute to finish building it!)

Thanks again for your time!
