### ISSUE TITLE
Detect symbolic variables in SimState

### ISSUE THREAD

**Issue by norrathep** [angr/angr#1178]
Hi,

I was wondering if there is a way to determine whether `SimState` object contains any symbolic variable? Ideally, I want to use `SimulationManager` to concretely execute some code and I would like to abort this execution when encountering any symbolic variable.

Thanks!

**Comment by rhelmot** [comment]
There is no good way to do this in principle - whenever angr encounters the limits of its environment model, it must introduce symbolic data to continue. Here are some suggestions:

- run your simulation manager with `until=lambda lsm: len(lsm.active) != 1`, which will halt whenever the state branches on a symbolic variable
- set a breakpoint on the creation of symbolic variables, as described [in the docs](https://docs.angr.io/docs/simulation.html)

**Comment by rhelmot** [comment]
There is definitely not any good way to solve this problem in the way you're asking about - SimStates are exceedingly complicated and deep, each plugin can store whatever data it wants wherever it wants, so you can definitely not enumerate the contents of the state to check for symbols.

**Comment by ltfish** [comment]
@rhelmot I think to achieve what he needs, setting up a breakpoint on the creation of symbolic variables (especially uninitialized reads) is sufficient.

**Comment by norrathep** [comment]
@rhelmot and @ltfish, thanks guys. I wasn't aware of this breakpoint. This should solve my problem.
