### ISSUE TITLE
step_state breakpoint no longer exists

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1196]
`step_state` isn't documented but it is part of the list of valid breakpoints in SimInspect, and the brave adventurer who looks into this list (@pwnslinger) will be very disappointed when he tries to use it.

As far as I can tell, this breakpoint used to be `step_path` and was triggered from path.py, but was never actually migrated out of path.py before its deletion during the end times. So, two issues:

1) Do we want to reimplement this? IMO the kosher way to instrument things between steps is with an exploration technique or a simulation manager.
2) We need to fix anything that uses this breakpoint. Currently this is just the crash monitor, but I suspect that fixing this will suddenly cause parts of rex to work again.

**Comment by zardus** [comment]
I agree that an otie is the correct way to do things. The implicit separation is this:

- ExplorationTechniques are there for handling everything above the level of "step!".
- SimInspect breakpoints are there for handling everything below the level of "step!"

So memory breakpoints, instruction breakpoints, etc make sense for SimInspect, and stepping and managing paths makes sense for oties.

I could see an argument being made for `step_state` being right at the intersection of the two, and to be supportable by both. It'd definitely necessitate fewer changes in rex, which may or may not be seen as a positive.

Honestly, I'm torn. My hunch is to keep it for now as the specific "handoff point" between oties and SimInspect, but I'm not strongly attached to that opinion.
