### ISSUE TITLE
Call graph of a binary

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#12]
Is there any analysis that extracts call graph of binary? Since angr has a CFG analysis, extracting call graph should be easy. Any pointer how to extract call graph easily?

I am happy to contribute back.

**Comment by rhelmot** [comment]
This appears to be implemented as `cfg.function_manager.interfunction_graph` @ltfish is this graph actually a call graph? From my inspection it looks like it.

**Comment by ltfish** [comment]
Sorry for the late reply. I believe it is call graph. Can you please try it out and let me know whether that suits your needs or not?

**Comment by riyadparvez** [comment]
Thanks for the reply.

It does look like a call graph. I've decided to use LLVM to extract call
graph during compilation which should be at least as accurate as extracting
call graph from binary.

BTW, is there any reason why it's named `interfunction_graph`, not the
standard `call_graph`? Using standard terminology will work as
documentation and help newbies to understand code-base.

**Comment by ltfish** [comment]
Good question. I honestly don't remember why.

If I can't recall the reason before next week, it will be renamed to `call_graph`.

**Comment by rhelmot** [comment]
(it was actually renamed to `callgraph`)
