### ISSUE TITLE
Variable simulation troubles

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#121]
Hi!
I've been working to use angr to solve a simple (C) version of a previously uploaded backdoor binary.
I tried to pair down the problem to the essentials in case the overall complexity of the large binary was angering angr. Previously, my angr analyses were getting stuck at a badge_id length checking step just before the actual backdoor because the badge_id had no value (it's gotten at runtime from a file).

![image](https://cloud.githubusercontent.com/assets/10760263/15578134/4b0761c8-232d-11e6-9c05-748a50171e92.png)

I am very easily able to find the backdoor using when there is a 'scanf' included in the source code. To make this test program more like the big binary, I removed the 'scanf' and was trying to simulate the 10 character badge_id variable in memory but am not having much luck.

Here, the badge id seems to be stored at rbp-0x40 which when I try to substitute for the a2 register, there is an error.

![image](https://cloud.githubusercontent.com/assets/10760263/15577613/420b4f78-232b-11e6-9f2b-304cdc0eebde.png)

I also tried this method with no better results:
![image](https://cloud.githubusercontent.com/assets/10760263/15577688/8a4380e4-232b-11e6-85dd-64e4c7ef4280.png)

Are these methods for simulating variables not correct?

[rfidc.zip](https://github.com/angr/angr/files/284605/rfidc.zip)

Thanks for taking a look at it!

**Comment by schieb** [comment]
I did not test your angr script but I would recommend that you try strncmp, or NULL terminate your char buffers. Post back if you still have issues.

**Comment by Dinatrix** [comment]
Hi!
Unfortunately those changes have not produced the backdoor that I was able to find when 'scanf' was present. I also tried a very similar program in c++ that models the real program (also c++) with no luck.
