### ISSUE TITLE
fgetc unexpected behavior

### ISSUE THREAD

**Issue by TheVillageIdiot2** [angr/angr#1213]
fgetc in the following test case is giving

```C
#include "stdio.h"

void read_int(int* targ){
    int i;
    char* cursor = (char*)targ;
    for(i=0; i<4; i++) {
        cursor[i] = fgetc(stdin);
    }
}

void write_int(int* output){
    int i;
    char* cursor = (char*)(output);
    for(i=0; i<4; i++) {
        fputc(cursor[i], stdout);
   }
}


int main(int argc, char** argv)
{
    int max;
    read_int(&max);
    write_int(&max);
    return 0;
}
```

Python code used:

```python
import angr
import claripy

proj = angr.Project('main', use_sim_procedures=True, auto_load_libs=True)
bytes_ast = "\n\n\n\n"
entry = proj.factory.entry_state(stdin=angr.SimFile('/dev/stdin', content=bytes_ast))
simgr = proj.factory.simgr(entry, save_unsat=True, save_unconstrained=True, save_errored=True)
while len(simgr.stashes['active']):
    simgr.step()

final = simg.stashes['deadended'][0]
import IPython
IPython.embed()
```

Evaluating final.posix.dumps(0) gives the expected '\n\n\n\n', but final.posix.dumps(1) gives '\xff\xff\xff\xff'. 
Not sure why, but fgetc() appears to be giving -1 as a signal for EOF, in spite of there being characters to read.

**Comment by rhelmot** [comment]
The fileno simprocedure was extracting the file descritptor number incorrectly - it was pulling 32 bytes instead of 32 bits of data, and thus getting an outrageous number. I have genuinely no idea how this has never been an issue before, but it has been fixed.
