### ISSUE TITLE
Document and add invariants for SimSymbolicMemory internals

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1230]
A perpetual source of bugs in angr is issues with SimSymbolicMemory (angr/state_plugins/symbolic_memory.py) whenever we need to refactor anything. This code, along with the paged memory implementation (angr/storage/paged_memory.py) are tightly coupled and very obscure, which is a bad combination. For example, we run in to bugs like https://github.com/angr/angr/issues/1227 which are hard to root-cause because it's unclear what properties of various functions we're supposed to be able to rely on.

A good project for someone looking to get involved with angr would be to dive in to the memory implementation and document it, adding comments and assertions about invariants among the plethora of load/store functions.

Of course, I would be totally willing to mentor anyone who needed help with this!

**Comment by zsisco** [comment]
Hi, I've been an angr user for the past year+ and would love to get involved. If this is still open, I'd be interested in working on it! Thanks

**Comment by rhelmot** [comment]
Hi! :D this is totally still open. I'm not sure where to point you other than just looking through the two mentioned files (along with, perhaps, the base class angr/storage/memory.py) and trying to understand everything. Definitely ask any questions you want, either here or in the angr slack!

**Comment by zsisco** [comment]
Hi, after looking through the couple source files and the details in issue #1227, I had a couple questions. 
So the problem referenced in #1227 is in the implementation of TreePage? Specifically its storage update methods like `store_overwrite` and `store_underwrite`? So from what I gather, the assertion of the invariant should be included in those functions; something like each item's `addr >= start` 

Extrapolating from this, is the overall goal of this task to apply this idea to other parts of the paged memory and symbolic memory code? (That is, documenting and enforcing invariants around load/store functions.) 

Please let me know if I've misunderstood anything. Thanks!

**Comment by rhelmot** [comment]
That sounds about right. The invariants should sort of be a byproduct of the broader goal, which is to document and comment the paged memory system.

**Comment by zwimer** [comment]
No longer relevant.
