### ISSUE TITLE
Strlen (or any function using state.memory.find) false memory information

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#1232]
I've encounter a bug where code calling to strlen with any input where there is inspect breakpoint on `mem_read` will report: `state.inspect.mem_read_length` to be the maximum length (which is libc.buf_symbolic_bytes value) instead of the actual length that have been read from strlen.

for example:
![strlen_asm](https://user-images.githubusercontent.com/7024240/46579747-2c8cf680-ca20-11e8-803a-e5e762d9edb5.PNG)
![strlen_code](https://user-images.githubusercontent.com/7024240/46579748-2e56ba00-ca20-11e8-8d9d-b115e2af3065.PNG)

state.inspect.mem_read_length always contain 256 instead of the length of "testing every strlen" or any other string.

**Comment by rhelmot** [comment]
I’ve known about this for a while but never really considered it important
enough to justify the hacks necessary to fix it. IIRC the bulk load is for
performance reasons - doing it a byte at a time results in noticeable
performance hits.

**Comment by mor619dx** [comment]
What is the correct way to enable it to read 1 byte at a time? (is this possible using the find function).
Maybe just adding some state option for it?

**Comment by rhelmot** [comment]
It’s not implemented currently.

**Comment by mor619dx** [comment]
I will add some option to make it read 1 byte at a time, thank you.
