### ISSUE TITLE
fix color of log messages

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1235]
**Is your feature request related to a problem? Please describe.**
Now `angr` has been ported to python3, and built in function `hash()` behaves differently from that in python2. Now, hash value stays the same in a certain session, but varies from session to session.
Note that `angr` use this code to generate colors of log message:
~~~
color = hash(record.name) % 7 + 31
record.name = ("\x1b[%dm" % color) + record.name + "\x1b[0m"
~~~
Which means log message will vary from session to session. This is not user friendly.

**Describe the solution you'd like**
Solution:
use other hash functions, like md5, sha1 etc. (I tried some, sha512 looks good, at least the most common messages are not white.)

**Comment by ltfish** [comment]
Can you please submit a patch for this?

**Comment by Alexeyan** [comment]
I hacked something together for this.
https://github.com/angr/angr/pull/1252
