### ISSUE TITLE
Angr can't find path to address unless extra constraints are added to the initial state

### ISSUE THREAD

**Issue by gsingh93** [angr/angr#124]
When running the following script on the [unbreakable](https://github.com/angr/angr-doc/blob/master/examples/google2016_unbreakable_0/unbreakable-enterprise-product-activation) challenge from GoogleCTF 2016, no path to the specified address is found, even though one definitely exists. Angr does not say anything about unconstrained paths, so I don't know any reason why no path would be found.

```
#!/usr/bin/env python2

from angr import *

input_size = 0x43
flag = claripy.BVS('flag', 8 * input_size)

p = Project('./unbreakable-enterprise-product-activation', load_options={'auto_load_libs': False})
state = p.factory.entry_state(args=[p.filename, flag])
pg = p.factory.path_group(state, veritesting=True)

state.libc.buf_symbolic_bytes = input_size + 1

for a, b in zip('CTF{', flag.chop(8)):
    state.se.add(ord(a) == b)

state.se.simplify()
logging.getLogger('angr.path_group').setLevel(logging.DEBUG)

pg.explore(find=(0x400830,), avoid=(0x400850,))
f = pg.found[0]

print f.state.se.any_str(flag)
```

If I add in some more constraints on the input buffer, then a path is found to that address:

```
#!/usr/bin/env python2

from angr import *

input_size = 0x43
flag = claripy.BVS('flag', 8 * input_size)

p = Project('./unbreakable-enterprise-product-activation', load_options={'auto_load_libs': False})
state = p.factory.entry_state(args=[p.filename, flag])
pg = p.factory.path_group(state, veritesting=True)

state.libc.buf_symbolic_bytes = input_size + 1

for a, b in zip('CTF{', flag.chop(8)):
    state.se.add(ord(a) == b)

# This for loop was added
for c in flag.chop(8):
    state.se.add(c > ord(' '))
    state.se.add(c < ord('~'))

state.se.simplify()
logging.getLogger('angr.path_group').setLevel(logging.DEBUG)

pg.explore(find=(0x400830,), avoid=(0x400850,))
f = pg.found[0]

print f.state.se.any_str(flag)
```

**Comment by salls** [comment]
It seems to be an issue with our memcpy simprocedure which is used internally by strncpy. When the length is symbolic it will try to take the libc.maximum_buffer_size, if you set that value higher it works. I'm adding a warning and updating the memcpy simprocedure

**Comment by gsingh93** [comment]
@salls any luck?

**Comment by salls** [comment]
It should be fixed on the current version on github.
I updated memcpy to have a larger maximum and added a warning when the memcpy size is limited.
https://github.com/angr/simuvex/blob/master/simuvex/procedures/libc___so___6/memcpy.py#L25-L27

**Comment by gsingh93** [comment]
Nice. We should probably have a warning like that for strcpy and another similar functions, right?

**Comment by salls** [comment]
memcpy was easy to add a warning to. For strcpy we'd need to look at strlen. 
But in strlen it isn't as easy. I'm not sure what a good condition would be for warning users. We could warn every time strlen is called on symbolic data, but maybe that's too annoying
