### ISSUE TITLE
testcase generation like DART

### ISSUE THREAD

**Issue by lidgik** [angr/angr#1253]
Hey, I am an angr beginner.
How to generate one testcase and negate? just like the algorithm in DART?

**Comment by ltfish** [comment]
Follow an existing path with concrete input first, and then unconstrain the input bytes. Then figure out which branch you want to negate and simply take the previously untaken state to solve for input bytes.

**Comment by lidgik** [comment]
Thx. But, would you show me the example code please? so I could understand the detail for basic learn.

**Comment by ltfish** [comment]
Sorry, I personally do not have the capacity to put together a demo for you. Someone else might want to step in.

You can learn a lot of basic stuff from the examples provided in angr-doc. Then I think it should be straightforward for you to reimplement DART.

**Comment by zardus** [comment]
Also, this is almost exactly what driller does at its core. Check out the
shellphish/driller repo.

- Yan

**Comment by lidgik** [comment]
Tks. I'll have a look.
