### ISSUE TITLE
csaw_wyvern example broken. 

### ISSUE THREAD

**Issue by Alexeyan** [angr/angr#1254]
The csaw_wyvern example does no longer work with the current angr-dev version of angr.

Trying to run it yields the following trace:
```
ERROR   | 2018-10-15 22:03:20,051 | angr.simos.simos | Resolver at 0x2039110 failed to resolve!                                                             
ERROR   | 2018-10-15 22:03:20,069 | angr.simos.simos | Resolver at 0x2033940 failed to resolve!                                                             
ERROR   | 2018-10-15 22:03:20,084 | angr.simos.simos | Resolver at 0x2028640 failed to resolve!  
[... Repeats a bunch]
ERROR   | 2018-10-15 22:03:20,987 | angr.simos.simos | Resolver at 0x40a4660 failed to resolve!
ERROR   | 2018-10-15 22:03:20,998 | angr.simos.simos | Resolver at 0x4089770 failed to resolve!
WARNING | 2018-10-15 22:03:23,906 | angr.state_plugins.unicorn_engine | fetching empty page [0x22000, 0x22fff]
None
Time elapsed: 6.01666784286499
```
I tried to debug this further, but setting the loglevel to debug produced no new prints.

**Comment by rhelmot** [comment]
It works for me...

This script is heavily dependent on the libraries that get loaded from your operating system. I've pushed to our binaries repo the libraries that for-sure work for me on my machine. Could you try copying them (https://github.com/angr/binaries/tree/master/tests/x86_64) into the wyvern directory and trying again?

**Comment by Alexeyan** [comment]
```
md5sum ./*
d348289e762bde30a5cf330700cff80e  ./libgcc_s.so.1
4c659326fdbac8a684298ccba999cc5c  ./libm.so.6
fadd7cd22c69ca02cdadee85f5c59a1a  ./libstdc++.so.6
f1d3c613b74c8e76576ee487d6dbe5bf  ./solve.py
c85f1be480808a9da350faaa6104a19b  ./wyvern
```
Same as before. Do i have to preload something or does angr use the libs in the current folder automatically?

Also: I use Arch, does that matter? Should i supply my version of the required libs for the challenge?

**Comment by rhelmot** [comment]
angr should use the libs in the current folder automatically. Notably you're missing the libc and ld-linux in that repo - those were already present, I just added the other ones in that commit. Those are probably going to be the culprit.

**Comment by rhelmot** [comment]
I would appreciate your copy of all the libs - tracking down issues in the loader is always a priority of mine.
