### ISSUE TITLE
Unable to analyse syscall 'arch_prctl'

### ISSUE THREAD

**Issue by SilverBut** [angr/angr#127]
While analyzing this sample:
[2.zip](https://github.com/angr/angr/files/288900/2.zip)

The following error occoured:
```
In [41]: ex = proj.surveyors.Explorer(avoid=0x401A0B).run()
ERROR   | 2016-05-30 13:57:46,801 | simuvex.procedures.syscalls | no syscall 158 for arch AMD64
```

Maybe angr lacks support of some syscalls?

**Comment by rhelmot** [comment]
angr lacks support for many syscalls, including this one. If I recall corrrectly, all this sycall usually does is to change the base address for the fs and gs segment selectors, so it should be easy to implement!

Syscalls are implemented in simuvex/simuvex/procedures/syscalls, and the mapping from syscall numbers to syscall procedure classes is found in simuvex/simuvex/procedures/syscalls/handler.py.

We'll get to this eventually, but if you want it done faster, drop us a PR. :)

**Comment by SilverBut** [comment]
Okay, I'll try to read the code and write something, but may be I'll be
slower than you. Just tag this issue with Enhancement or something like
that. :)
