### ISSUE TITLE
Error while importing angr

### ISSUE THREAD

**Issue by lalitdagre** [angr/angr#1271]
I am using CentOs7 and installed angr. But when importing angr I am getting following error

`AttributeError: module 'idalink' has no attribute 'idalink'`

![angr_error](https://user-images.githubusercontent.com/10557037/47430260-79115980-d7b6-11e8-94d1-a283047196bb.png)

**Comment by rhelmot** [comment]
This is already fixed on master. There will be a new release today.

**Comment by lalitdagre** [comment]
@rhelmot 
Will the latest version available through pip?

**Comment by rhelmot** [comment]
Yes. It is not there yet, I am working on it at this exact moment...

**Comment by lalitdagre** [comment]
@rhelmot great, thanks.
