### ISSUE TITLE
Producing succinct symbolic representation of IRSBs with SimEngine?

### ISSUE THREAD

**Issue by nimrodpar** [angr/angr#1276]
Hi,

I have this feeling that i can use the simulation engine in order to produce optimized symbolic expressions from a VEX block, but haven't been able to quite find out how.

For instance, for this piece of code:
```
t10 = GET:I32(eax)
t11 = Sub32(t10,0x00000004)
PUT(ebx) = t11
```
I would love to get `ebx = eax - 4`

I tried using something like this:
```
state = angr.SimState(arch=arch)
for succ in angr.SimEngineVEX().process(state.copy(), irsb):
  print (succ.simplify())
```
But this produces very limited results.

I guess i can dig in more into simulation and states and try to find a way, but i just wanted to know if this is realistic even.

Cheers.

**Comment by rhelmot** [comment]
The problem you want to solve is fantastically complicated and is effectively equivalent to starting to write a decompiler!

Solving your problem involves the following:

- identifying all the data sources involved
- identifying all the data sinks (storage locations that are mutated) involved
- constructing the ASTs between the sources and the sinks (set the sources to symbolic values, run the step, load from all the sinks)
- pretty-printing

This is enough to handle your simple case, but as soon as you get to anything even vaguely more complicated (memory accesses? control flow? god forbid, indirect memory access?) everything is going to go to shit.

I recommend looking into our fledgling decompiler (test_structurer) and seeing what it can give you.

**Comment by ltfish** [comment]
Ref: https://github.com/angr/angr/blob/master/tests/test_structurer.py

**Comment by nimrodpar** [comment]
Not surprising :) Thanks for the prompt reply!

**Comment by ltfish** [comment]
PS: Many of the algorithms you will need are already implemented (or at least partially implemented) in angr. `Structurer` is an entry point to our half-assed decompiler which uses many of those algorithms. You will need to excavate them...
