### ISSUE TITLE
Infinite loop while trying to concrete symbolic memory

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1285]
**Describe the bug**
When trying to concrete a string from the memory, angr might go to an infinite (or just very long) loop if the content of the memory location is symbolic. 

**Environment Information**
python 3.7
angr 8.18.10.5

**To Reproduce**
The issues could be reproduced with every arm binary. 

```
p.factory.call_state(<any_func_addr>)
memory = state.mem[0x111] ### Or any other undefined memory
form.string.concrete #### Infinite loop 
```

**Additional context**
Prints the following warnings:

> angr.state_plugins.symbolic_memory | Memory address 0x111 has an unspecified value; Generating an unconstrained value of 1 bytes.
> angr.state_plugins.symbolic_memory | Memory address 0x112 has an unspecified value; Generating an unconstrained value of 1 bytes.
..... 
and so on

I'm pretty sure that it wasn't the behaviour in some of the previous version of angr, but have no way to check it now..

**Comment by rhelmot** [comment]
This was "fixed" in https://github.com/angr/angr/commit/40214d42ddcd57d03e20d85458fa5efce9746a4e, which should be present in angr 8.18.10.25. The long and the short of it is that there's no good way to do this, so we have to just kick you out if you try to pull out the length of a symbolic string.
