### ISSUE TITLE
Hooks with tracer exploration technique

### ISSUE THREAD

**Issue by capgelka** [angr/angr#1295]
Hi, I want to do symbolic execution over trace.

For a simple binary with a call of `system` function, which arguments are tainted somehow by argv.

```
def symbolic_run(binary, argv)
    record = tracer.QEMURunner(
        binary=binary.path,
        input=b'',
        argv=argv
    )

    p = angr.Project(binary)

    entry = p.factory.full_init_state(
        addr=binary.main_addr,
        args=argv
    )

    t = angr.exploration_techniques.Tracer(
        record.trace
    )

    sm = p.factory.simgr(entry)
    sm.use_technique(t)

    @p.hook(binary.main_addr)
    def on_main(state):
      # here I want to symbolize argv[0]

    @p.hook(binary.func_map['system'])
    def on_system_call(state):
        # here I want to run solver
```

The problem is that I am getting an exception after my `on_main` hook.
```
 raise AngrTracerError("Trace failed to synchronize during fast forward? You might want to unhook %s." % (self.project.hooked_by(state.history.addr).display_name))
angr.errors.AngrTracerError: Trace failed to synchronize during fast forward? You might want to unhook UserHook.
```

I don't want to replace the function I am hooking with my own implementation, I just want to do some manipulation with memory at the moment angr reaches some routine, and then continue execution without changes.

Is this possible to achieve that with hooks? Or I should try another approach?

**Comment by rhelmot** [comment]
The current tracer was definitely not designed with zero-length hooks in mind. You would need to add a special case in the tracer to deal with this. Or, just wait until I have some free time and I'll do it.

In the meantime, you can provide a symbolic argv[0] by passing a BVS into the state constructor args, and you can stop at system by using the Explorer technique and making sure that you set the simgr `completion_mode` to `any`.
