### ISSUE TITLE
angr disassembly strategy

### ISSUE THREAD

**Issue by valour01** [angr/angr#1319]
Hi. I refer to the cfgfast() 

I understand the strategy of cfgfast to get the function start address.  I think angr will start to do the disassembly after get all the function start addresses.

A short question is that the disassembly is recursive or linear?

I noticed this `Finally, by default, the binary's entire code section will be scanned for executable contents, regardless of prologues or symbols` in the documentation. How do angr decide the code section. In other words, how do angr handle the inline data. Many Thanks

**Comment by ltfish** [comment]
> It will not handle inline data.

To clarify, CFGFast does handle inline data. The way that it handles inline data is by detecting where data is used by disassembly code (when `collect_data_references` is True) and marking the memory region that data occupies as `data` (instead of `code`).

**Comment by valour01** [comment]
I see. Sorry for the late reply. Many Thanks
