### ISSUE TITLE
SimFile.read() should return symbolic length variable

### ISSUE THREAD

**Issue by juk80x** [angr/angr#132]
In cases where the contents of the file is symbolic, shouldn't SimFile.read() return a symbolic variable for the length of the read call? Currently, it returns a BV for the same length it was called to read. Obviously, the amount returned by read is not always the amount read, and a lot of code exits in this case. By returning a symbolic variable, the exit path with be added to the path_group when stepping.

**Comment by zardus** [comment]
Short reads are rather tricky to handle in a performant way, and right now, the only real way to do it in angr is by setting the size of the SimFile. Obviously, this isn't very general (i.e., you might not know the size of the file ahead of time, or want to do this for a general size of the time).

My preference would be to keep SimFile simple and, instead, put the logic to handle short reads into the read syscall (https://github.com/angr/simuvex/blob/master/simuvex/procedures/syscalls/read.py). As to *how* to do this in a performant way, I'm not quite sure yet. We can create a new symbolic variable, constrain it to be less than or equal to the provided size, then pass *that* into SimFile.read and return it. This would have the unfortunate effect of causing a path explosion for every `read_exactly_n` type loop, though.

**Comment by juk80x** [comment]
What about just returning a symbolic variable, and let the calling function set the constraint if it's tested?

I would rather have to deal with path explosion as opposed to the current situation where paths are not being created at all.

**Comment by zardus** [comment]
I think the problem with returning a completely unconstrained value is that
you might end up in a situation where read() returns a *bigger* size than
what was passed into it. At the very least, the maximum should be
constrained there. Further constraints should come from the program itself;
I agree about that.

The way to balance between the path explosion and the missing paths is to
make the behavior configurable with a SHORT_READ_SUPPORT state option, I
think.

We're pretty swamped at the lab currently. Do you feel up to giving this a
go?

**Comment by juk80x** [comment]
I'll take a shot. So the expected behavior will be that when SHORT_READ_SUPPORT is True the read syscall returns a BVS and the BVS is constrained to be less than or equal to length.

**Comment by zardus** [comment]
Sounds correct. Rather than checking if it's true, you'd do something like `if options.SHORT_READ_SUPPORT in self.state.options:`. The state options are, unfortunately, a set at the moment.

Also keep in mind that, currently, the `read` syscall isn't used by, for example, the `read` libc simprocedure. It'll probably be best to have the latter call the former inline (there's an example of how to do this in the `strncpy` simprocedure, for example.

**Comment by zardus** [comment]
And thanks for taking a stab at this!
