### ISSUE TITLE
Arch Linux AUR Package

### ISSUE THREAD

**Issue by rnbwdsh** [angr/angr#1323]
Hi. I'd like to ask for an [Arch User Repository](https://aur.archlinux.org/) package for the python3-version of angr. So far only the python2-angr is available there, and [it uses the version 7.8.2.21](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-angr).

Installing it over pip3 under arch linux leads dependency issues, so an AUR package would be great.

**Comment by subwire** [comment]
*cough cough* @lockshaw

**Comment by lockshaw** [comment]
@subwire Yeah, I'll try to do this tonight

**Comment by lockshaw** [comment]
@rnbdsh Just created one tracking angr's master branch: https://aur.archlinux.org/packages/python-angr-git/. I'll work on getting one tracking the current angr release next

**Comment by quangIO** [comment]
@lockshaw Thank you for maintaining those packages on AUR. Could you change 
python-z3-solver-angr (in python-claripy) to python-z3?
