### ISSUE TITLE
CFGFast() - networkx DiGraph nodes are missing predecessors

### ISSUE THREAD

**Issue by nSinus-R** [angr/angr#134]
Hey guys,

I stumbled today upon some weirdness in the CFGFast()-analyses and @zardus  recommended me to open this issue.
In short, when using analyses.CFGFast() for generating a CFG, the networkx-digraph nodes appear to have at maximum one predecessor. At the same time, nodes can still have more than one successor, i.e. two successors, which is expected behavior but doesn't add up considering the observed amount of predecessors.

Here are some lines demonstrating the problem:
 
> import angr
> 
> b = angr.Project("/bin/true",load_options={'auto_load_libs': False})
> 
> cfg = b.analyses.CFGAccurate() #this yields expected results, i.e. nodes with more than one predeccors
> #cfg = b.analyses.CFGFast()
> 
> for n in cfg.graph.nodes_iter():
>     pre = n.predecessors #n.predecessors and cfg.graph.predecessors(n) are yielding the same result
>     print "#Predecessors for %s: %d" % (n.name, len(pre)) 
>     
> for n in cfg.graph.nodes_iter():
>     suc = n.successors #n.successors and cfg.graph.successors(n) are yielding the same result
>     print "#Successors   for %s: %d" % (n.name, len(suc))

**Comment by rhelmot** [comment]
This looks similar to a bug that was fixed recently - what version of angr are you working on?

**Comment by nSinus-R** [comment]
I was on 4.6.5.27, just updated to angr-4.6.6.4, which fixed it indeed.
Sorry for bothering.
