### ISSUE TITLE
Fix the unconstrained memory warning

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1351]
We need to do something about this warning. It always spawns false positives when executing from functions with callee-save functions, and it totally drowns out any sort of real errors during static analysis.

**Comment by ltfish** [comment]
I find it really annoying, too. I don't think what you see when executing callee-save functions are false positives though -- those warnings are expected. They are just not useful, as in, they do not indicate any bugs or errors that might arise.

We can probably degrade it to a level between `INFO` and `WARNING`? There should be a level that is intended for users to debug, which is probably between `INFO` and `WARNING`...

**Comment by rhelmot** [comment]
I think if we want that to be a normal message we should have some sort of affirmative flag we can apply to a state saying "yes, I want my {registers,memory} to be symbolic-filled and to have angr provide the symbols - don't tell me about it"

**Comment by ltfish** [comment]
> I think if we want that to be a normal message we should have some sort of affirmative flag we can apply to a state saying "yes, I want my {registers,memory} to be symbolic-filled and to have angr provide the symbols - don't tell me about it"

How do you want to implement this for a command-line interface though? It seems to me that a GUI is the way to go :/

**Comment by subwire** [comment]
Why not just have an `angr.sim_options.TOLERATE_UNCONSTRAINED_MEMORY` or somesuch?

**Comment by ltfish** [comment]
Here is what I propose:

- Add that flag.
- When that flag is on, we still warn about the first uninitialized memory/register usage. The warning message should tell the user that if he is debugging weird issues during symbolic execution, he might want to switch that option off. Future such warnings are muted.
- Leave that option on by default.
- (Most importantly) Add a troubleshoot manual to angr-doc and put that option in the manual.

What do you think?

**Comment by rhelmot** [comment]
I don't think that's necessary - I think that we can just leave the flag off by default. The messages are good to see when you're actually doing symbolic execution. The really annoying bit is that the messages show up during static analysis, and analyses can just add that option.

**Comment by ltfish** [comment]
Fine by me.
