### ISSUE TITLE
Got an unsat result

### ISSUE THREAD

**Issue by 344389541** [angr/angr#1360]
What is wrong with my code? How should I write it correctly。
Varieties of base64,  answer is MhAyOFQSR2JDUEZv 

code
`
def test_mac_5():

    proj = angr.Project("./a.out",
                        auto_load_libs=False)

    start = 0x000000000400807
    find = 0x000000000040080C

    state = proj.factory.blank_state(addr=start, )

    in_addr = state.regs.esp - 0x1000
    out_addr = state.regs.esp - 0x2000

    state.regs.rdi = out_addr
    state.regs.rsi = in_addr
    state.regs.rdx = 16

    sm = proj.factory.simulation_manager(state)
    sm.explore(find=find, )
    found = sm.found[0]

    # shouldbe is 2018TSCRCTF-
    found.add_constraints(found.memory.load(out_addr, 12) == int(binascii.hexlify(b"2018TSCRCTF-"), 16))

    in_mem = found.memory.load(in_addr, 16)
    for i in range(16):
        # We want those flags to be printable characters
        state.add_constraints(in_mem.get_byte(i) >= 0x20)
        state.add_constraints(in_mem.get_byte(i) <= 0x7e)

    text = found.solver.eval(found.memory.load(in_addr, 16), cast_to=bytes)
    print(text)

`

error

`angr.errors.SimUnsatError: Got an unsat result`

[a.out.zip](https://github.com/angr/angr/files/2713933/a.out.zip)

**Comment by ltfish** [comment]
Take a look at function `decode_sub_69ED10B7()`. There can be more than one exit path coming out of that function. Not all paths are corresponding to the one that yields you a correct decryption result. So you want to exhaust all path going out of `decode_sub_69ED10B7()`, add these constraints to every exit state, and test the satness of each state.

**Comment by 344389541** [comment]
decode_sub_69ED10B7  is a Varieties of base64。

**Comment by rhelmot** [comment]
the problem is that you’re adding constraints to a state after executing on it, not before. so, angr is telling you the correct answer: the state you’ve found (of which there could be many states that meet that criteria) is not satisfiable once you add those constraints.
