### ISSUE TITLE
Splitting of basic blocks (question/idea)

### ISSUE THREAD

**Issue by axt** [angr/angr#139]
I've tried to reduce the problem/question, to a really small example:
```
int main() {
        int a,b = 0;
        if (a > 10) b = 1;
        else b = 2;
}
```
As you can see, block `0x8048409` contains the entire block of `0x8048410`:

![cfg](https://cloud.githubusercontent.com/assets/759365/15991780/59abc352-30bd-11e6-961d-27643f6d01d4.png)

@ltfish : What do you think about introducing a `next` edge and split the basic-block `0x8048409` in these case, so we don't have duplicated code in the BBs? 

![cfg](https://cloud.githubusercontent.com/assets/759365/15991956/58a8ad9a-30c1-11e6-926f-affab49b7759.png)

I think the splitting could made reading of more complex graphs easier. To illustrate this, I've created the current graph, and the next-edge graph of a more complex artifical example. See the graphs at the end of these message.

I can make this transformation, when trying to visualize the graph (although not quite sure about how to handle higher context-sensitivity levels). Just wanted to know, if you see any benefit to having this in `angr`, not just when visualizing the results from `angr`.

More complex example:

Current | With the next edge (dotted blue line)
--- | ---
![cfg](https://cloud.githubusercontent.com/assets/759365/15991823/848bcc56-30be-11e6-97dc-b9210c38ae9f.png) | ![cfg2](https://cloud.githubusercontent.com/assets/759365/15991890/e51ebfaa-30bf-11e6-8962-2bab94fed31d.png)

**Comment by rhelmot** [comment]
If I'm reading this correctly, you're talking about basic block normalization!

This is supported by CFGAccurate, but not CFGFast. More useful, though, is that regardless of the CFG backend, individual functions in the function manager can normalize their intrafunction graphs by calling `normalize()` on them.

**Comment by axt** [comment]
@rhelmot : Thanks, I didn't know about that feature.

I've checked it. It seems working, although it only changes nodes in the graph, but not cfg._nodes, but this is mentioned in `fixme` comments. Also thanks for the hint on function manager.

**Comment by ltfish** [comment]
Trailer for the next angr release: both `CFGAccurate` and `CFGFast` will support `normalize()`, `cfg._nodes` as well as function transition graphs will be updated as well.

Source: me (I'm working on it).

**Comment by axt** [comment]
Sounds really cool  :+1:, can't wait to have it!

I'm sure you are full of work, and I really don't want to be insatiable, but can I propose another nice to have feature for the long-term? Jump table support. 

Unfortunatelly neither `symbolic_back_traversal` nor `backward_slicing` deal with jump tables, which is probably because its hard to solve them symbolically. Although I've checked some code from Borland C, and gcc, and they seem to have a very similar layout (check the range, dereference, jump). 

Instead of just asking for it, I'm ready to contribute to this, but would like know, what is your opinon of it.

**Comment by ltfish** [comment]
`CFGFast` supports jump table resolution. The long term plan is to move it to `CFGBase` so both `CFGFast` and `CFGAccurate` can use it. It'll be awesome if you can do it :-)

**Comment by axt** [comment]
Didn't worked for me with `CFGFast` (with `resolve_indirect_jumps` set to `true`). 
I think it found the jump target `BB`s, but the edges were missing. 
Will have another look on it.

**Comment by ltfish** [comment]
Which edges are missing? Please give me an example (with your fancy graph) when you have time.

**Comment by axt** [comment]
I've did this:
```
if __name__ == "__main__":
    proj = angr.Project(sample, load_options={'auto_load_libs':False})
    main_sym = proj.loader.main_bin.get_symbol("main")
    cfg = proj.analyses.CFGFast(fail_fast=False,
        start=main_sym.addr,
        end=main_sym.addr+main_sym.size,
        symbols=False,
        function_prologues=False,
        resolve_indirect_jumps=True)
```

This is the output graph:
![cfgfst](https://cloud.githubusercontent.com/assets/759365/16026057/d17d2754-31cb-11e6-8b4f-6c11a1452d77.png)

**Comment by ltfish** [comment]
Interesting. It should be a bug then. Can you please open a new issue for me?

**Comment by axt** [comment]
Sure! Thanks a lot!

**Comment by ltfish** [comment]
> Sure! Thanks a lot!

Thank you :-)
