### ISSUE TITLE
AttributeError in VSA DDG analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#14]
I'm experimenting with VSA DDG analysis. I'm seeing the following error message:

```
In [9]: vsa_ddg = b.analyses.VSA_DDG(b.entry)                                                                          
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-4533d51ccf3d> in <module>()
----> 1 vsa_ddg = b.analyses.VSA_DDG(b.entry)

/home/riyad/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.pyc in _analysis(self, analysis, *args, **kwargs)
     67 
     68         # Call __init__ of chosen analysis
---> 69         a = analysis(self._p, fail_fast, *args, **kwargs)
     70 
     71         return a

/home/riyad/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.pyc in __core_init__(self, project, fail_fast, *args, **kwargs)
    123 
    124         if kwargs.pop('do_analysis', True):
--> 125             self.__analysis_init__(*args, **kwargs)  # pylint:disable=no-member
    126 
    127     def post_load(self):

/home/riyad/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/vsa_ddg.pyc in __init__(self, start_addr, interfunction_level, context_sensitivity_level, keep_addrs)
     46 
     47         # We explore one path at a time
---> 48         self._branch({}, self._startnode)
     49 
     50     def _make_block(self, irsb, live_defs):

/home/riyad/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/datagraph_meta.pyc in _branch(self, live_defs, node, path)
     66         """
     67 
---> 68         irsb = self._irsb(node.state)
     69         path = path + " -> " + hex(irsb.addr)
     70 

/home/riyad/.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/datagraph_meta.pyc in _irsb(self, in_state)
     17             We expect a VSA state here.
     18             """
---> 19             return self._p.sim_run(in_state)
     20 
     21     def _vfg_node(self, addr):

AttributeError: 'Project' object has no attribute 'sim_run'
```

**Comment by ltfish** [comment]
That is a known bug and has been fixed on our internal branch. Just replace `self._p.sim_run(in_state)` with `self._p.factory.sim_run(in_state)`.

However, there are a couple of severe problems with the current implementation of VSA DDG. For instance, it does not properly utilize a worklist algorithm. We are implementing a new one on our internal branch, and it will be released soon (do expect this weekend). I would suggest you wait until then to try VSA DDG.

Sorry for any inconvinience that it may cause for you.

**Comment by ltfish** [comment]
Oh, and thank you for reporting the issue :-)

**Comment by riyadparvez** [comment]
On Wed, Aug 26, 2015 at 3:44 PM, ltfish <notifications@github.com> wrote:

> That is a known bug and has been fixed on our internal branch. Just
> replace self._p.sim_run(in_state) with self._p.factory.sim_run(in_state).
>
> However, there are a couple of severe problems with the current
> implementation of VSA DDG. For instance, it does not properly utilize a
> worklist algorithm. We are implementing a new one on our internal branch,
> and it will be released soon (do expect this weekend). I would suggest you
> wait until then to try VSA DDG.
>

Any idea when DDG will be released? Thanks for your support.

Sorry for any inconvinience that it may cause for you.
>
>
No problem at all.

**Comment by ltfish** [comment]
Yep, it will be merged to master and pushed soon. We just had an internal discussion on my code last weekend. So give me a few more days for this. I'm currently documenting my shit...

**Comment by ltfish** [comment]
Eventually my branch got merged in! Grab the latest code and try the `VSA_DDG` :-)

Also @zardus is working on an automatic publishing script for pypi. I suppose soon `pip install --upgrade angr` will just do all the magic.

**Comment by ltfish** [comment]
Oops I accidentally closed the issue. Feel free to reopen if you have more stuff to say!

**Comment by zardus** [comment]
The pip version is now updated. We now have scripts and a new, easier-to-tick version format, so with any luck, releases to pip will be more frequent.
