### ISSUE TITLE
CFGFast indirect jump edges are missing

### ISSUE THREAD

**Issue by axt** [angr/angr#140]
When using `CFGFast` with `resolve_indirect_jumps`, the target `BB`s are found, but the jump edges are missing.

```
    proj = angr.Project(sample, load_options={'auto_load_libs':False})
    main_sym = proj.loader.main_bin.get_symbol("main")
    cfg = proj.analyses.CFGFast(fail_fast=False,
        start=main_sym.addr,
        end=main_sym.addr+main_sym.size,
        symbols=False,
        function_prologues=False,
        resolve_indirect_jumps=True)

```
![cfgfst](https://cloud.githubusercontent.com/assets/759365/16026210/26060a06-31cd-11e6-8a26-015317ab6762.png)

Testcase: 
[testcase.zip](https://github.com/angr/angr/files/312867/testcase.zip)

**Comment by ltfish** [comment]
Thanks for reporting. This is a bug and I just fixed it. It will be included in the next angr release!

Here is what it looks like now.

![issue_140_resolved](https://cloud.githubusercontent.com/assets/5071575/16027663/ad3bdc30-318c-11e6-8a34-22c68caf9478.png)

**Comment by axt** [comment]
It seems to me, taht one edge is wrong: 804845e -> 8048463, which should be 804845e -> 8048472.

**Comment by axt** [comment]
Sorry! Just realized, that the edge is right! Just the blocks are not updated.

**Comment by axt** [comment]
My bad! Its an error in the visualization! Thanks for the fix, i'm closing the issue!
