### ISSUE TITLE
jumpkind of jr instruction in mips arthitecture

### ISSUE THREAD

**Issue by cq674350529** [angr/angr#1403]
Take the following code snippet as an example, the `jr` instruction is used to call a function.

    LOAD:0041FEF4 lw      $gp, 0x20+var_10($sp)
    LOAD:0041FEF8 lw      $ra, 0x20+var_4($sp)
    LOAD:0041FEFC la      $t9, httpd_ipc_init
    LOAD:0041FF00 nop
    LOAD:0041FF04 jr      $t9 ; httpd_ipc_init
    LOAD:0041FF08 addiu   $sp, 0x20

In my opinion, the jumpkind should be `Ijk_Call`. But acctually it outputs `Ijk_Boring`.  

    target = angr.Project('./httpd', load_options={'auto_load_libs':False})
    block1 = target.factory.block(0x41fef4)
    block1.vex.jumpkind    # output 'Ijk_Boring'

Does it work as expected? Do I misunderstand about `Ijk_Call`/`Ijk_Boring`? 

The binary is just a general program.  Any advice would be appreciated! Thanks in advance.

**Comment by rhelmot** [comment]
Generally you can’t expect the lifter to be able to get the
call/return/boring jumpkinds right 100% of the time. In this case, this
looks like a tail call. It is in fact a call, but it’s be being performed
with instructions which on the face of it just look like another jump. We
could perhaps add a specific edge case in libvex that jr $t9 would be a
call? Would that be safe?

**Comment by cq674350529** [comment]
@rhelmot  Thanks for your reply. 
 Yes. It occurs only if the block is the last block of a function. In other cases, a `jalr` instruction is used instead. 
In most cases, `jr $t9` means a function call. But I'm NOT very sure that's always the case.

**Comment by subwire** [comment]
If it's not universal, or inherent in the instruction itself, where to add this is a bit of a gray area.
Fish and I were going back and forth on a virtually identical issue on the ARM side of things, and after trying the VEX route, and running into exactly those cases where it's not a Call a lot faster than we thought, we ended up with a little bit in VEX, but most of it in angr itself, particularly within CFG.

In fact, the case here appears to be... nearly identical to that.  I wonder if we can adapt what we already did... :)

**Comment by rhelmot** [comment]
I’m fairly sure that we do not want tail calls to be marked Ijk_Call, I
feel like that messes up some assumptions that get made by different parts
of angr. Fish?

**Comment by cq674350529** [comment]
@subwire Yes, I rely on the jumpkind to do  further analysis. So treat `jr $t9` as a call would be more precise in my case.

**Comment by subwire** [comment]
@cq674350529 Would it work in your analysis to use the CFG to determine jumpkinds instead? With one built, you will have the locations of both calls and jumpouts in a function, which together gets you the set of calls that would be the best we'd ever do anyway. You also get this right now :)

Of course, as rhelmot said, it's very possible Fish has a better idea

**Comment by cq674350529** [comment]
@subwire In my analysis, I can't use the CFG to determine jumpkinds, for the CFG hasn't been built completely when I come accross this problem. In my case, I modified the process of building CFG slightly. 

At the moment, I use an UGLY trick to check if the jumpkind is really `Ijk_Boring` or not based on the address jumped to. Treat it as `Ijk_Call` if it's a function address. In most cases, it works well.

So just let it go if not have a better idea.

Thanks for your efforts.

**Comment by rhelmot** [comment]
I don't think we can make `jr $t9` an Ijk_Call. That would mess up a lot of other things in angr. We expect that an instruction of jumpkind call will return to the next instruction afterwards (not necessarily in CFG, but for state options like CALLLESS and a handful of other static analysis).

In general, piggybacking an analysis on the cfg construction process is a very bad idea. Build a CFG first, then work with that. If your project is about improving CFG construction, you will need some better metrics for determining what's a function or not, since function finding is an integral part of the CFG recovery process.

**Comment by ltfish** [comment]
@rhelmot I'm removing the `wontfix` label because this is not a bug in angr. angr is behaving correctly in this case.
