### ISSUE TITLE
questions about reconstrain function in preconstrainer

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1407]
It is probably not an issue. I just want to make it clear.
Here are my questions:

Question1: Purpose of `reconstrain`
Here is the the description of `reconstrain` function:
~~~
Re-apply preconstraints to improve solver time, hopefully these constraints still allow us to do meaningful things to state.
~~~
So, the name and the description of `reconstrain` implies that after I temporarily remove preconstraints, I can now be able to add those preconstraints back with this function.

But the implementation does not comply the intuitive understanding of the function. Here comes the implementation
~~~
    def reconstrain(self):
        """
        Split the solver. If any of the subsolvers time out after a short timeout (10 seconds), re-add the
        preconstraints associated with each of its variables. Hopefully these constraints still allow us to do
        meaningful things to the state.
        """

        # test all solver splits
        subsolvers = self.state.solver._solver.split()

        for solver in subsolvers:
            solver.timeout = 1000 * 10  # 10 seconds
            if not solver.satisfiable():
                for var in solver.variables:
                    if var in self.variable_map:
                        self.state.solver.add(self.variable_map[var])
                    else:
                        l.warning("var %s not found in self.variable_map", var)
~~~
The logic is more like: if it is tooooo slow, add the preconstraints back. And it is added directly to `state.solver`? My understanding is that preconstraints should only exist in `solver.state._state._replacements` or it will affect really constraints.

So there are two interpretation here, one is literally re-apply preconstraints, the other is re-apply to optimize speed(if I understand correctly). I wonder whether it is a naming issue. And shall we create two functions to serve different purposes?

Question 2: about usage of this function.
~~~
        # remove the preconstraints
        l.debug("removing preconstraints")
        state.preconstrainer.remove_preconstraints()

        l.debug("reconstraining... ")
        state.preconstrainer.reconstrain()
~~~
This is a snippet of `angr.exploration_techniques.tracer` trying to replay the crashing step.
I don't quite understand what it means. When tracer arrives at crash point, all preconstraints should be removed, right? why it still tries to reconstrain?

I'm sorry if these two questions are too dumb.

**Comment by rhelmot** [comment]
The correct description of the reconstrain function is given in its docstring. idk where you found the first one; I rewrote it into the docstring to clarify it several months ago.

At least part of the purpose of either removing preconstraints or reconstraining them (I forget which) is to convert the solver from a replacement solver to a composite solver. we can't have both.

The purpose of the remove-reconstrain idiom is, then, to remove all preconstraints except for the ones over variables which are slow to solve, as an optimization.

**Comment by Kyle-Kyle** [comment]
I found the first one at http://angr.io/api-doc/angr.html?highlight=cfg#angr.state_plugins.preconstrainer.SimStatePreconstrainer.reconstrain.

So now I need temporarily disable the preconstraints so I can see how many possible successors a state has  in normal execution flow. But after that, I cannot add preconstraints back. I can give it a hack and make it work. But do you think we need to add this functionality to preconstrainer?

**Comment by rhelmot** [comment]
We haven't done a release since the hackathon I made that change in apparently. Those are sourced from the docstrings, so the canon version is in the code snippet you posted :P

Make a copy of the state and remove preconstraints in that one to do your test.

**Comment by Kyle-Kyle** [comment]
OK. thanks.
