### ISSUE TITLE
Explorer.run() vs Explorer.run(1) vs PathGroup.explore()

### ISSUE THREAD

**Issue by ercoppa** [angr/angr#141]
First of all, let me say that angr is an amazing tool! Thank you for releasing it. I have already started to play with it (e.g., see my pull request in angr-doc https://github.com/angr/angr-doc/pull/75). I have some doubts about Explorer and PathGroup.

The documentation states that:

> Pathgroups are supposed to replace surveyors.Explorer, being more clever and efficient. 

I am observing that this may be not true in some cases. Also, I think that the behavior of Explorer is inconsistent wrt PathGroup, but also wrt to itself. Let me explain why.

1) Explorer can be used like this (A):

```
ex = proj.surveyors.Explorer(..., found=XXX, avoid = YYY, ...)
ex.run() //
```

Or (B): 

```
ex = proj.surveyors.Explorer(..., found=XXX, avoid = YYY, ...)
while True:
   ex.run(1)
   if len(ex.found) >= 1:
        break
```

I was expecting that the result will be same with (A) or (B) but it's not. Explorer is selecting active paths (among active+spilled paths) based on how many times the next instruction of a path have been  executed (see Explorer.path_comparator()). The instruction counter used by path_comparator() is updated: (i) for all states (active + spilled) when Explorer.run() is called, and (ii) for an active state that is explored. This means that if you call many times run() like in (B), you may get a very different instruction counter that in (A) where you call run() only once. Spilled states make the difference.  In my case, on one binary, (B) was able to hit a found path after ~4mins, while (A) did not hit a found path after ~20mins (I stopped it... I don't know if it is able to hit it sooner or later). I don't know when (A) is better of (B), or vice-versa. This was just my experience. I find this behavior a bit confusing or, even a bit inconsistent. I see this as a bug, but this may be a feature.  Where is the truth?

2) Explorer splits active states into: active and spilled. In particular, if you have N active states, max_active states will be "real" active, while N - max_active will be spilled. I am not 100%  sure but I don't see the concept of spilled states in PathGroup and thus all N active states will be explored. In my experiment, the memory usage of PathGroup when used like this:

```
pg = proj.factory.path_group(state) # the same if immutable=False
ex = pg.explore(find = XXX, avoid = YYY)
```

was much higher than Explorer. I had to kill angr when it was using ~4GB, while Explorer used at most ~1.2GB. Explorer is prioritizing (by default!) few active paths based on the instruction counter, while PathGroup is exploring all active states. On my workstation with 8GB of memory, Explorer is more "clever and efficient" than PathGroup. I know that this is may not be true in a general setting, 

My feeling is that PathGroup is much more flexible and powerful than Explorer, but it needs a bit of manual tuning. E.g., avoid PathGroup.explore() but use PathGroup.step() with some user defined "selector_func".

As it is, PathGroup.explore() is not an "equivalent" replacement for Explorer. Again, I am not sure if this  is a design choice or something that may be improved over time.  

Am I missing something about the usage of PathGroup? In particular, how can we "effectively" use it without adding some additional bits?

**Comment by zardus** [comment]
The whole `PathGroup` vs `Surveyor`/`Explorer` thing is definitely a pain. Thanks for looking into it! It sounds like we should at least do the following:

1. `PathGroup.explore` should provide a built-in way of limiting the number of active paths (and maybe prioritizing which paths should get explored). This is *doable* with PathGroups, but not built-in to `PathGroup.explore`.
2. With `LAZY_SOLVES` being on by default in angr, `PathGroup` uses a `PathHierarchy` to track path reachability. This eats up some memory as well. In the near future, we will turn off `LAZY_SOLVES` by default!

We're about to push a new fature, called `otiegnqwvk`, that adds support setting up "techniques" (such as prioritization, threading, veritesting, etc) to be applied to a `PathGroup` in a pluggable way. I'll play around with using that to implement some prioritization for `PathGroup.explore`, and we'll see if we can use all that to finally get rid of surveyors!

**Comment by zardus** [comment]
Whoops, I apologize. I typoed the interface name, `otiegnqwvk` should be `exploration techniques`.

**Comment by ercoppa** [comment]
(I forgot to say that in most of my experiments LAZY_SOLVES was disabled since I had too many paths around)

Ok, then I'll wait for ```otiegnqwvk```. It seems very interesting.

I already had in mind to work on your first suggestion. If I came up with something useful within the next dayy, I'll let you know. I need to find some time to work on it.

**Comment by zardus** [comment]
We pushed `otiegnqwvk` today! They are described in: http://angr.io/api-doc/angr.html#angr.exploration_techniques.ExplorationTechnique

Exploration techniques are stackable, so they should be able to be used to implement loop limiting and path prioritization for exploration without making invasive changes anywhere. I haven't actually had a chance to do the latter, but the LoopLimiter exploration technique should be able to take care of the former!
