### ISSUE TITLE
Path Group modification

### ISSUE THREAD

**Issue by P1kachu** [angr/angr#142]
[This modification](https://github.com/angr/angr/commit/6012119229707175ac4d8ac7abef9aad3ec16454#diff-5b6d270d612438f38d8eade5c781fdb9L160) erased code I had written lately, in order to make the paths step until any `find` address, even if this address was not at the top of any block (which is important in some usecases, and actually very important in mine). This feature had been requested by @ltfish 

Has it been moved somewhere else ?

**Comment by P1kachu** [comment]
Or is it supposed to be reiplemented as an `otiegnqwvk` ?

**Comment by rhelmot** [comment]
The functionality still exists. There are tests which rely on it. Look at `exploration_techniques/explorer.py` to find the exploration otiegnqwvk.

**Comment by P1kachu** [comment]
Great I'll check that
