### ISSUE TITLE
weird solver behavior

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#1431]
**Describe the bug**
I encountered this issue during a CTF.
It looks like a cache bug.
The behavior is like this.
~~~
[ins] In [1]: simgr.found[1].satisfiable()                                                                                                                                                                  
Out[1]: True

[ins] In [2]: simgr.found[1].simplify()                                                                                                                                                                     
Out[2]: [<Bool False>]

[nav] In [3]: simgr.found[1].satisfiable()                                                                                                                                                                  
Out[3]: False
~~~

**To Reproduce**

everything is in [here](https://gist.github.com/Kyle-Kyle/9682df5fc3ca49cc1b25ecbe6a4eb15a)

**Comment by Kyle-Kyle** [comment]
This challenge contains a lot of opaque predicates like
"""
mov eax, 1;
test eax, eax;
jne XXX
"""
So I guess the state that evaluated to be `False` after simplification is the the branch that should never be taken.

**Comment by rhelmot** [comment]
...maybe? it's still definitely an angr bug though

**Comment by Kyle-Kyle** [comment]
I'm just saying.
`False` is expected. It is `True` that concerns me.
So the problem is not `And` simplifier, I guess?
