### ISSUE TITLE
Symbian: Follow-fork and thread select

### ISSUE THREAD

**Issue by bannsec** [angr/angr#1434]
**Is your feature request related to a problem? Please describe.**
Not a "problem" per say.. However, when using Symbian, it would be helpful to be able to handle forking and thread switching.

**Describe the solution you'd like**
GDB specifically offers the concepts of `follow_fork_mode`. However, given that Symbian uses an abstraction for it's interactions (Avatar2), it should be possible to standardize implementation of handling that same functionality. For instance, IDA could simply catch all fork calls, then switch to the new process before continuing. It would be nice to be an option to auto-follow or not.

Similar with threads. Either follow-thread type option, or simply thread_switch call. Concept being, concrete execute to a part of the code, thread switch to the one you want to actually execute, then continue symbolically.

**Please include a sample of what *should* work if this feature is implemented.**
I'll have to get back to you on a binary multi-thread example.

**Describe alternatives you've considered**
It's not clear to me if this change would be done on angr's side, or if it would make sense to attempt to push the change into Avatar2.

One partial solution would be to be able to give Symbian a context of a program that's already running. For instance, run the program in gdb, break at a certain place, manually select different thread, then give that context over to angr to continue. I would actually like to see both options be possible as I could see them being used in different situations.

**Comment by ltfish** [comment]
WOW
