### ISSUE TITLE
What is the format of a VSA_DDG node?

### ISSUE THREAD

**Issue by Lightninghkm** [angr/angr#1436]
How to successfully generate a VSA_DDG of a given executable?
I used the script below to try to generate one:
<img width="1089" alt="2019-02-10 3 54 42" src="https://user-images.githubusercontent.com/43520471/52539447-35823180-2d4c-11e9-8b0b-5837694a7de2.png">
But it doesn't show any node, just a NodeView(())
Did I make any mistake when I generate this vsa_ddg?
Does the format of a node in vsa_ddg is the same as in original ddg?
Thank you very much!

**Comment by mephi42** [comment]
I also ran into a problem with `VSA_DDG` being empty, and resolved it by using the following `initial_state` for the `VFG`:

```
initial_state = proj.factory.blank_state(
    mode='static',
    add_options=angr.options.refs,
)
```

`VSA_DDG` uses `state.history.recent_actions`, and `angr.options.refs` makes sure it gets populated.

**Comment by Lightninghkm** [comment]
Thanks much, I will try that, thanks again for the help :)
