### ISSUE TITLE
Concolic execution example?

### ISSUE THREAD

**Issue by ThePatrickStar** [angr/angr#146]
Hi, first I would like to thank you guys for making such a powerful tool!
I met a problem when using the concolic execution feature of angr.
I was trying to run the binary program with a concrete seed provided.
First is the main function for the binary executable file (in c):

`int main(int argc, char** argv) {
    int x;
    FILE *fp = fopen(argv[1],"r");
    fread(tmp, 1, 20, fp);

    magic_n1[0] = tmp[0];
    magic_n1[1] = tmp[1];

    long i, j;

    strncpy(magic_s, tmp+5, 5);
    strncpy(magic_n2, tmp+14, 5);

    i = strtol(magic_n1, &dump, 10);
    j = strtol(magic_n2, &dump, 10);

    printf("magic_n1 is : %ld\n", i);
    printf("magic_n2 is : %ld\n", j);
    printf("maigc_s is : %s\n", magic_s);

    if(i<23 && i>20){
        if((j>-1001 && j<-998) || i==22){
           x=0;
        }
        else{
           //nothing here
        }
    } else {
         //nothing here
    }
  return 0;
}`

Then is the python script I used to run the binary concretely:

`state = bi.factory.entry_state(concrete_fs=True, args=['./'+self.binary, input_file])
 pa = bi.factory.path(state=state)
 #then i just run pa.step() and recursively step through the program`

I can access the content of the input file with the following script during the recursive stepping:
`if len(st.posix.files.keys()) > 3:
                m_id = max(st.posix.files.keys())
                m_f = st.posix.get_file(fd=m_id)
                a_b = m_f.all_bytes()`
It seems that the SimFile object was created correctly and the program is running with the concrete input. However, I found that some paths have 2 successors during the concrete run. Theoretically, if I give a program a  concrete input to run with, there should be only 1 successor for the paths right?
Do you guys have any idea about this? Or I wasn't using it correctly?

**Comment by rhelmot** [comment]
Hi! Currently, by default an option called LAZY_SOLVES is enabled, which means that state-satsfiability is checked as infrequently as possible, so some of the successors you've obtained probably aren't satisfiable. If you add the argument `remove_options={simuvex.o.LAZY_SOLVES}`, this issue should go away.

**Comment by ThePatrickStar** [comment]
Wow, thank you for the fast response and it works like a charm!
