### ISSUE TITLE
Thumb block from node

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1471]
I encountered this issue in reaching definitions in `reaching_definitions.py` in `_run_on_node`, however, I believe it's relevant to other places too. 

GIven the following disassembly (binary attached):
```
.text:000104C4   FF F7 38 FF BL      j_realloc
.text:000104C8   03 00       MOVS    R3, R0
.text:000104CA   7B 60       STR     R3, [R7,#8+var_4]
.text:000104CC   C0 46       NOP
.text:000104CE   BD 46       MOV     SP, R7
.text:000104D0   02 B0       ADD     SP, SP, #8
.text:000104D2   80 BD       POP     {R7,PC}
.text:000104D2             ; End of function
```
And given the `node` object that starts on `000104C8` (more correctly on `000104C9` in thumb manners)

```
block = self.project.factory.block(node.addr, node.size, opt_level=0)
print([hex(x) for x in block .instruction_addrs])
```

will result:
`['0x104c9', '0x104cb', '0x104cd', '0x104cf', '0x104d1']
`
ommiting the last instruction - `000104D2` (`000104D3` in thumb manners)

However, increasing the node size by one:
```
block = self.project.factory.block(node.addr, node.size + 1, opt_level=0)
print([hex(x) for x in block .instruction_addrs])
```
Will yield good results
`['0x104c9', '0x104cb', '0x104cd', '0x104cf', '0x104d1', '0x104d3']`

Attached test.zip that contains test.so, which is arm-thumb executable.
The issue is in the main function.
[test.zip](https://github.com/angr/angr/files/2953345/test.zip)

Note: I have the issue in `8.18.10.25` and still didn't test in on the newest version.

**Comment by rhelmot** [comment]
```python
import angr
p = angr.Project('test.so')
cfg = p.analyses.CFGFast()
node = cfg.get_any_node(0x104c9)
print(hex(node.addr))
print(node.size)

block = p.factory.block(node.addr, node.size, opt_level=0)
print([hex(x) for x in block.instruction_addrs])
```

```
0x104c9
12
['0x104c9', '0x104cb', '0x104cd', '0x104cf', '0x104d1', '0x104d3']
```

The issue is in whatever node you're specifically using. The node size isn't being calculated correctly by whatever analysis you're running.

**Comment by HexRoman** [comment]
You right, from checking the issue it looks like BlockNode is the one causing the issue and not the CFGNode

**Comment by rhelmot** [comment]
You should open a new issue with a testcase to reproduce the problem that the block attributes are incorrect for this specific analysis.
