### ISSUE TITLE
Is there any tutorial about how to analyze server file like "httpd"?

### ISSUE THREAD

**Issue by shivakasu** [angr/angr#1473]
I'm a bit confused about things like socket or url. I don't know how to set parameters. Is there a tutorial  or an example?

**Comment by yangshouguo** [comment]
state.register_plugin('posix', SimSystemPosix(...))
may helps

**Comment by rhelmot** [comment]
There is no such tutorial. Furthermore, HTTP parameters are too high-level for a binary analysis engine like angr. Instead, you need to specify the TCP input to the server process.

I'm not sure why you opened this issue. This was answered perfectly well in https://github.com/angr/angr/issues/1205, which you also opened.
