### ISSUE TITLE
Separate SimProcedure signature defs from run() function

### ISSUE THREAD

**Issue by aheinric** [angr/angr#1478]
*Disclaimer: The angr suite is maintained by a small team of volunteers. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with angr, from us and the community, join our [Slack.](http://angr.io/invite/)*

---

**Is your feature request related to a problem? Please describe.**
Argument and return types for SimProcedures (if defined) are not defined until procedure execution.  This means the procedure's type data isn't available to inspect breakpoints before the procedure is executed.

**Describe the solution you'd like**
Ideally, separate lifecycle callbacks, something like this:
```
get_arg_types(self, state):
    return { 0: SimTypeLength(state.arch) }
get_ret_type(self, state):
    return SimTypeTop()
```
This way, someone examining the procedure can get the types without actually running the procedure.

**Please include a sample of what *should* work if this feature is implemented.**
```
def breakpoint(state):
    arg_types = state.inspect.procedure.get_arg_types(state)
    arg_vals = proc.cc.arg_locs(is_fp=[False]) 
    if isinstance(arg_types[0], SimTypePointer):
        thing_i_care_about = state.memory.load(arg_vals[0], some_size, endness="Iend_BE")
        # Analyze the thing I care about.

def main():
    ...
    state.inspect.make_breakpoint("simprocedure", while=BP_BEFORE, action=breakpoint)
    ...
    # Execute the state.
```

**Describe alternatives you've considered**
I've looked at examining procedures after execution, at which point the types (if defined) are defined, but SimProcedure execution can change argument values or the memory pointed to by arguments.

**Additional context**

**Comment by rhelmot** [comment]
I have some great news! Function prototypes are part of the SimLibrary (see for example glibc.py), which are integrated into simprocedures through the calling convention. For a supported function, you can say `procedure.cc.func_ty`.

The method where we set the types in the run method is super old and nobody ever used it. It should be deprecated.

**Comment by aheinric** [comment]
Perfect!  This is exactly what I needed.  Many thanks!
