### ISSUE TITLE
Question: Are there any ways to give CFG knowledge to Angr?

### ISSUE THREAD

**Issue by soomin-kim** [angr/angr#1484]
Sometimes, we can have more accurate knowledge about CFG than that of angr's result, for example we can extract CFG infromation while we compile a program.

So in that case, I want to make angr to use such information. Is it possible?

**Comment by schieb** [comment]
@ltfish is working on https://github.com/angr/angr/issues/1444, which should give a user the ability to import CFG-related information taken from another source. Last I heard, it will be finished around the beginning of April.

**Comment by soomin-kim** [comment]
Thanks a lot! I'll be waiting for it :)
