### ISSUE TITLE
Version Tags/Branches

### ISSUE THREAD

**Issue by sraboy** [angr/angr#1487]
**Is your feature request related to a problem? Please describe.**
PyPi is really the only versioning in use but development moves much faster than that and there is no unified way to ensure, for example, a version of angr matches a version of CLE where some feature/bugfix was implemented. #1448 will partially resolve this but I can't checkout a `__version__` from a repo. 

**Describe the solution you'd like**
1. Add git tags to the repos for packages' major/minor releases.
2. When changes are merged to multiple repos for features/bugfixes (e.g., the ARM CFG party branches), require at least a minor version increment across them all and document it somewhere. 
3. Bonus: I'm partial to an "angr suite" version number that documents/pins each repo's major/minor/revision so we know, for example, "Feature X came in 'angr suite' v9.1.234, which uses angr v9.1.3, CLE v9.2.1, claripy, archinfo, etc etc".

**Please include a sample of what *should* work if this feature is implemented.**
Like with #1448, scripts can check `package.__version__` and documentation can specify major/minor versions that can be checked out via git tags.

Bonus: Scripts could also check something like `angr.__platform__` (or whatever) where the "angr suite" version lives. My documentation can specify "we target 'angr suite' v9.1.234; based on `angr/angr/suite_ver.md` checkout the tagged versions for each package."

**Describe alternatives you've considered**
For some internal projects, the only practical solution for me is manually documenting commit hashes across all the repos.

**Additional context**
It helps with documentation for projects, papers, write-ups, etc. For example, on CHESS, I'd like to document that my plugins and patches require specific major/minor versions so I can target them and not worry about breaking changes merged to master in the future.

**Comment by subwire** [comment]
I agree, the CFG party is totally version-bumpin' :D

**Comment by rhelmot** [comment]
So my take on this is that angr isn't really mature enough to do minor/revision versions, but what I think a good compromise would be is that we have an archive of the `pip freeze` for any successful CI run, which will give you a requirements.txt the exact hashes you could depend on. The beta CI has this implemented but there's no real working beta CI instance right now. We could probably rig up travis to do this, or we could just have a real quick button we press once a day to upload a new freeze version if CI is passing. The freeze version could even be a meta-package on pypi, `angr-dev`.

**Comment by sraboy** [comment]
That would help for the reference portion in documentation but I'm also hoping to avoid a scenario where another dev (or me later) has to `git checkout <hash>` in each repo and manually update them any time additional non-breaking changes are merged upstream. Can that meta-package actually clone and checkout the repos at that point or would it just be a 'release style' pip package? If it's the former, I think that would solve it.

Before you go and set up some awkward CI solution though, I just discovered `git rev-list` which might provide the same solution. I'll need to tinker with it some but I could probably add that to `git_all.sh` in `angr-dev` to automagically checkout a certain date.

**Comment by rhelmot** [comment]
Yes, we can specify dependencies on specific hashes in a pypi package.

**Comment by rhelmot** [comment]
Here's an example package I just built which pins the repos which I currently happen to have checked out: [angr-dev-8.1.0.tar.gz](https://github.com/angr/angr/files/3015958/angr-dev-8.1.0.tar.gz)

This is a full python package distribution that can be installed with pip (pip install thing.tar.gz) or uploaded to pypi.

**Comment by zardus** [comment]
Just for completion, there is also the `checkout_at.py` script, which, given a commit hash for one repository, will check out every repository to the time of the provided commit.

**Comment by sraboy** [comment]
Oh man, thanks guys. `checkout_at.py` is easier than remembering `rev-list` and and the new pinning script will make it easier to pass along to others for testing.

**Comment by subwire** [comment]
maybe we should integrate this with angr.misc.bug_report somehow?
Like somehow serialize the output into a form that becomes reproducible?

**Comment by rhelmot** [comment]
It's called `pip freeze`
