### ISSUE TITLE
Intel Distribution for Python?

### ISSUE THREAD

**Issue by Manouchehri** [angr/angr#149]
I was wondering, does angr use any of the Python libraries that Intel has modified for their processors (NumPy, SciPy, scikit-learn, numba, Cython, and pyDAAL)? They recently released a beta.

https://software.intel.com/en-us/python-distribution

Mostly leaving this here as a "to-do" task for myself to benchmark.

**Comment by rhelmot** [comment]
Angr uses none of these.

**Comment by Manouchehri** [comment]
None of it's dependencies either? (e.g. Z3)

**Comment by rhelmot** [comment]
z3 has no dependencies, libvex has no dependencies, capstone has no
dependencies, all the rest of the angr dependencies are pure Python and
only depend on pure Python modules.

**Comment by Manouchehri** [comment]
Thanks!
