### ISSUE TITLE
General way to pretty print the call of a SimProcedure with its arguments 

### ISSUE THREAD

**Issue by fmagin** [angr/angr#1496]
**Describe the solution you'd like**
I would like a way to quickly get the arguments of a SimProcedure in a form similar to the output of various GDB plugins like gef.

```
puts@plt (
   $rdi = 0x00007fffffffe5e1 → 0x4f43003176677261 ("Some string"?)
)
```
At least for an official SimProcedures the arguments need to be clear anyway so all the information should be available. 

**Describe alternatives you've considered**
This could be generalized to all functions if they have a prototype and a CC defined. 

I am currently trying to implement this myself, but https://github.com/angr/angr/issues/1495 is preventing me.

**Design suggestion**
The SimProcedure Base class gets a method to do this that implements this based on the defined prototype and CC, has either a specific state or `self.state` as the argument and returns the pretty string. Maybe some intermediate function to have the arguments first for other kind of analysis.

In case a user has a hacked together SimProcedure that only works for one context (i.e. lacks either a prototype or the calling convention) this could be overridden in that specific SimProcedure class

**Comment by fmagin** [comment]
In addition to the types and pretty printed arguments the names of the arguments (if available) would be nice. I know no place where this information is stored currently, I would expect it either in the associated calling convention object or directly in the function object in the knowledge base.

**Comment by rhelmot** [comment]
You'll need to use the same tricks that SimProcedure itself does, using python's inspect module to get the metadata of the `run` function. You can get exact argument numbers and names like that.

**Comment by fmagin** [comment]
https://github.com/angr/angr/pull/1503 Sufficiently addresses this for my use case, the actual printing is probably better left to something outside of the angr core
