### ISSUE TITLE
Claripy Annotations being dropped

### ISSUE THREAD

**Issue by cdisselkoen** [angr/angr#1497]
*Disclaimer: The angr suite is maintained by a small team of volunteers. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with angr, from us and the community, join our [Slack.](http://angr.io/invite/)*

---

**Describe the bug**
I'm filing this bug on angr, although it may actually be a bug in claripy, I'm not sure.  My reproduction case is in angr, so I'll start here.

1. Create an annotated BVS.
2. Do some simple math on the BVS (by executing a single irsb).
3. What comes back is an AST describing the operation(s).
Expected behavior: the final AST includes the annotated BVS, or at least includes the annotation somewhere
Observed behavior: none of the leaves of the AST, nor the AST itself, are annotated. It is as though the original BVS was copied for use in the final AST, and the annotation was dropped.

**Environment Information**
Many common issues are caused by problems with the local Python environment.
Before submitting, double-check that your versions of all modules in the angr suite (angr, cle, pyvex, ...) are up to date.
Please include the output of `python -m angr.misc.bug_report` here.

I reproduced this bug (exactly the same output of the script) in two different environments: one environment is a Mac with my own checkouts of `master` (or nearly so) for `angr`, `claripy`, `pyvex`, `archinfo`, and `cle`, while using Pip for the other dependencies; and the other environment is a Linux machine with `angr 8.19.2.4` and all its dependencies from Pip.  So I don't think the issue is a detail of my environment.  I've included more complete environment descriptions at the bottom just in case.

**To Reproduce**
Please include *both a script to reproduce the crash, and attach the binary used, if possible*

Script to reproduce the problem:
```
import angr
import claripy

def printAst(ast):
    aststr = str(ast)
    annotstr = "(annotated)" if ast.annotations else "(unannotated)"
    print(aststr + " " + annotstr)

def printAstWithLeaves(ast):
    printAst(ast)
    for l in ast.leaf_asts():
        print("    ", end="")
        printAst(l)

proj = angr.Project('simple')
arg = claripy.BVS('arg', 64, annotations=(claripy.Annotation(),))
funcaddr = proj.loader.find_symbol('foo').rebased_addr
state = proj.factory.call_state(funcaddr, arg)
simgr = proj.factory.simgr(state)

print("function argument:")
printAstWithLeaves(arg)
simgr.step()
print("function return value:")
printAstWithLeaves(simgr.active[0].regs.rax)
```

Observed output:
```
function argument:
<BV64 arg_0_64> (annotated)
    <BV64 arg_0_64> (annotated)
function return value:
<BV64 0x0 .. (arg_0_64[28:0] .. 0 + (0xffffffff * arg_0_64[31:0]))> (unannotated)
    <BV64 arg_0_64> (unannotated)
    <BV32 0xffffffff> (unannotated)
    <BV3 0> (unannotated)
    <BV32 0x0> (unannotated)
```

Binary is attached at [simple.gz](https://github.com/angr/angr/files/3036476/simple.gz) (GitHub seems not to allow attaching binaries, so I gzipped the binary)

Binary was acquired by compiling the following source file with `clang -O1` on a Linux machine:
```
int foo(int x) {
    int y = x * 7;
    return y;
}

int main() {
    int x = foo(3);
    return 0;
}
```

**Additional context**
This behavior is _not_ due to the `eliminatable` or `relocatable` properties of the particular `Annotation` object.  I get exactly the same results when adding this annotation instead of a base `claripy.Annotation`:
```
class MyAnnotation(claripy.Annotation):
    def eliminatable(self):
        return False

    def relocatable(self):
        return False

[...]
arg = claripy.BVS(..., annotations=(MyAnnotation(),))
[...]
```

**Extra details on environments**
Machine 1:
```
angr environment report
=============================
Date: 2019-04-02 18:18:55.521678
Running in virtual environment at [my venv dir]
Platform: macosx-10.14-x86_64
Python version: 3.6.1 (dab365a465140aa79a5f3ba4db784c4af4d5c195, Feb 18 2019, 10:53:27)
[PyPy 7.0.0-alpha0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
######## angr #########
Python found it in /Users/craig/angr/angr
Pip version not found!
Git info:
        Current commit 97fd492f8f94be7b12513d04c46cac16baccc9fb from branch master
        Checked out from remote origin: git@github.com:cdisselkoen/angr
######## ailment #########
Python found it in [my venv dir]/site-packages/ailment
Pip version ailment 8.19.2.4
######## cle #########
Python found it in /Users/craig/cle/cle
Pip version not found!
Git info:
        Current commit f5d43bdd279309c9833ce4c2fbadbb68843fd383 from branch master
        Checked out from remote origin: git@github.com:angr/cle
######## pyvex #########
Python found it in /Users/craig/pyvex/pyvex
Pip version pyvex 8.19.2.4
Git info:
        Current commit 6b9828885fd0ef8e309460d29d01b60220f96199 from branch master
        Checked out from remote origin: git@github.com:angr/pyvex
######## claripy #########
Python found it in /Users/craig/claripy/claripy
Pip version not found!
Git info:
        Current commit da3c05c7ad2dea231ce06a94748d79d4a9c04afe from branch master
        Checked out from remote origin: git@github.com:angr/claripy
######## archinfo #########
Python found it in /Users/craig/archinfo/archinfo
Pip version not found!
Git info:
        Current commit 4fcc183bd00617af6bd101b8aa60741be957160c from branch import-without-pyvex
        Checked out from remote origin: git@github.com:cdisselkoen/archinfo
######## z3 #########
Python found it in [my venv dir]/site-packages/z3
Pip version not found!
Git info:
        Current commit c1852c5165dc9e75b2dba62160fe4e1be1720df2 from branch master
######## unicorn #########
Python found it in [my venv dir]/site-packages/unicorn
Pip version unicorn 1.0.1
######### Native Module Info ##########
angr: None
unicorn: <CDLL '[my venv dir]/site-packages/unicorn/lib/libunicorn.dylib', handle 7fd489dac3f0 at 0x10f50e330>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000000010f155210>
z3: <CDLL '[my venv dir]/site-packages/z3/lib/libz3.dylib', handle 7fd48f2bc020 at 0x114c47328>
```

Machine 2:
```
angr environment report
=============================
Date: 2019-04-02 18:38:24.288341
Running in virtual environment at [my venv dir]
Platform: linux-x86_64
Python version: 3.6.1 (fb40f7a5524c77b80e6c468e087d621610137261, Feb 09 2019, 15:00:51)
[PyPy 7.0.0-alpha0 with GCC 8.2.0]
######## angr #########
Python found it in [my venv dir]/site-packages/angr
Pip version angr 8.19.2.4
######## ailment #########
Python found it in [my venv dir]/site-packages/ailment
Pip version ailment 8.19.2.4
######## cle #########
Python found it in [my venv dir]/site-packages/cle
Pip version cle 8.19.2.4
######## pyvex #########
Python found it in [my venv dir]/site-packages/pyvex
Pip version pyvex 8.19.2.4
######## claripy #########
Python found it in [my venv dir]/site-packages/claripy
Pip version claripy 8.19.2.4
######## archinfo #########
Python found it in [my venv dir]/site-packages/archinfo
Pip version archinfo 8.19.2.4
######## ana #########
Python found it in [my venv dir]/site-packages/ana
Pip version ana 0.5
######## z3 #########
Python found it in [my venv dir]/site-packages/z3
Pip version not found!
######## unicorn #########
Python found it in [my venv dir]/site-packages/unicorn
Pip version unicorn 1.0.1
######### Native Module Info ##########
angr: <CDLL '[my venv dir]/site-packages/angr/lib/angr_native.so', handle 2793590 at 0x7f19619b1980>
unicorn: <CDLL '[my venv dir]/site-packages/unicorn/lib/libunicorn.so', handle 1ce2ab0 at 0x1c25788>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00007f1964fc8988>
z3: <CDLL '[my venv dir]/site-packages/z3/lib/libz3.so', handle 3c9e5e0 at 0x7f195facda28>
```

**Comment by cdisselkoen** [comment]
It appears that at least with this particular reproduction case, the annotation is dropped on the line `arg = arg.reversed` during the call to `_standardize_value` in `setup_callsite` in `calling_conventions.py`.  If that's the only place where annotations are dropped, then this might be claripy's problem (namely, `arg.reversed` isn't preserving annotations).

**Comment by cdisselkoen** [comment]
I was too hasty with the above comment.  Although `arg.reversed` isn't annotated, `arg.reversed.leaf_asts()[0]` still is.  The annotation gets dropped from the AST somewhere else.

**Comment by cdisselkoen** [comment]
Ok, the place the annotation is dropped is in fact the line
```
store_item['value'] = self.state.solver.simplify(store_item['value'])
```
in `_store` in `symbolic_memory.py`.

That is, we are storing
```
<BV64 Reverse(arg_0_64)> (unannotated)
```
which has the leaf_ast
```
<BV64 arg_0_64> (annotated)
```
Before storing, we 'simplify' the value.  The simplified result is
```
<BV64 arg_0_64[7:0] .. arg_0_64[15:8] .. arg_0_64[23:16] .. arg_0_64[31:24] .. arg_0_64[39:32] .. arg_0_64[47:40] .. arg_0_64[55:48] .. arg_0_64[63:56]>
```
which crucially has the leaf_ast
```
<BV64 arg_0_64> (unannotated)
```
That is, the simplification has lost the annotation from the leaf_ast.

**Comment by rhelmot** [comment]
almost certainly an artifact of the conversion/abstraction process of getting the BVS into and out of z3. I'll get to this at some point but if you want to take a stab, annotations should be added to the data stored in/extracted from `extra_bvs_data` in claripy/backends/backend_z3.py.

**Comment by rhelmot** [comment]
hot take incoming: we should get rid of annotations and replace them with the ability to easily create custom AST leaves and ops.

**Comment by cdisselkoen** [comment]
Cool, I'll look into the fix in claripy/backends/backend_z3.py.  Probably won't get to it till tomorrow, but I'll take a stab.

**Comment by ltfish** [comment]
> hot take incoming: we should get rid of annotations and replace them with the ability to easily create custom AST leaves and ops.

We should also think about how to translate such code into C++... Maybe they can be done at the same time.
