### ISSUE TITLE
Problem with atoi simprocedure

### ISSUE THREAD

**Issue by Brucedh** [angr/angr#1498]
I wrote two very basic C programs which do the same thing, one using the libc atoi() function while the other one uses a custom myAtoi().

Here it is the second one:

    #include <stdio.h>

    int myAtoi(char *str);

    int main(void) {
      char str[5];
      scanf("%s", &str);
      int key = myAtoi(str);
  
      if (key == 1337)
        printf("succeded!\n");
      else
        printf("failed\n");
  
      return 0;
    }

    int myAtoi(char *str) { 
    int res = 0; 
    
    for (int i = 0; str[i] != '\0'; ++i) 
        res = res*10 + str[i] - '0'; 
   
    return res; 
    }

Then I wrote a script which starts symbolic execution from the binary's entry point, runs the execution until an instruction located after scanf but before myAtoi, and puts a symbolic variable as output of scanf (and input of myAtoi). 

Here it is the script:

    import angr

    p = angr.Project('myatoi') 

    initial_state = p.factory.entry_state()

    sm1 = p.factory.simulation_manager(initial_state)

    sm1.explore(find=0x00401156)
    # 0040114d    CALL     __isoc99_scanf
    # 00401152    LEA      RAX=>local_11,[RBP + -0x9]
    # 00401156    MOV      RDI,RAX
    # 00401159    CALL     myAtoi           

    after_scanf = sm1.found[0]

    word_size = 4
    input = initial_state.solver.BVS('input', 8*word_size)

    after_scanf.memory.store(after_scanf.regs.rax, input, endness="Iend_LE")

    for i in range(word_size):
        after_scanf.add_constraints(input.get_byte(i) >= 0x30)
        after_scanf.add_constraints(input.get_byte(i) <= 0x39)

    sm2 = p.factory.simulation_manager(after_scanf)
    sm2.explore(find=lambda s: b"succeded!" in s.posix.dumps(1))

    print(sm2.found[0].solver.eval_upto(input,10,cast_to=bytes))

This script works for the program with custom myAtoi (actually it returns the solution upside-down, that is b'7331', I don't know why), but when I test the version with built-in atoi with the same script (obviously changing the after_scanf address) it returns:
`[b'3100', b'0000', b'3310', b'1000', b'7331', b'9858', b'4924']`
As you can see, the solution is the fifth string, so why the others?

I guess there could be some issues with atoi (strtol) simprocedure.

Thank you in advance

**Comment by salls** [comment]
```
  char str[5];
  scanf("%s", &str);
```

I'd be weary about using scanf here. The buffer is only 5 bytes long, maybe things are getting overflowed and angr's finding some of those solutions?

**Comment by sraboy** [comment]
Might be a problem with the `scanf` simprocedure actually. Change your `scanf` call to `scanf("%4s", str);` and it's fixed. Both versions return the same: `[b'7331']`. 

[atoitest.zip](https://github.com/angr/angr/files/3038299/atoitest.zip) has both versions for testing: `atoitest_noamp_4` uses `atoi` `atoitest_noamp_4_my` uses `myAtoi`.

**Comment by Brucedh** [comment]
Right, thank you!
