### ISSUE TITLE
Accessing information about memory reads/writes

### ISSUE THREAD

**Issue by Kobzol** [angr/angr#150]
I tried to set a breakpoint using `state.inspect.b('mem_write', action=cb)`.
When the callback is invoked, I can access the program state through the state parameter, but I don't know how to see the address that is currently being written/read by the mem_write/mem_read event.
Is there a way to access this information about the memory write/read?
I know that it's not an issue, but I didn't know where else can I ask this.
Thanks in advance for your answer.

**Comment by rhelmot** [comment]
I actually had to figure this out myself a few days ago! It's not very well
documented, sorry...

For each of the parameters related to an event (mem_read_address,
mem_read_expr, etc), you can access state.inspect.{parameter} to retrieve
or set the current value. Where relevant, setting a value there will cause
it to be modified for further uses of it!

**Comment by Kobzol** [comment]
Thank you, that's exactly what I was looking for :-)
