### ISSUE TITLE
Dump content(string) argument

### ISSUE THREAD

**Issue by pelopato** [angr/angr#1514]
Hi, 

I need to dump the contents of an argument passed as a parameter, but it always looks like this:
Pointer memory address string: <BV64 argv1_0_200[199:136]>
or argument: < BV200 argv1_0_200>

I've tried things like that from a hook:
```python
# get content string
# rbx pointer string
pointer = state.solver.eval(state.regs.rbx)
pointer = state.mem[pointer].long.resolved.reversed
print("pointer:", pointer)
result: <BV64 argv1_0_200[199:136]>
```
or:
```python
# get content string 10 chars array
pointer = state.solver.eval(state.regs.rbx)
content = state.mem[pointer].char.array(10).resolved
print("content:", content[0])
result: <BV8 argv1_0_200[199:136]>
```
or dump args
```python
print("argv1:", argv1)
result: < BV200 argv1_0_200>
```

Thanks you.

**Comment by schieb** [comment]
Bit vectors must be passed to eval to get the either the "real" underlying bytes, or a valid solution if the bit vector is symbolic and has a solution.

```python
pointer = state.solver.eval(state.regs.rbx)
s_bv = state.memory.load(pointer, size_of_string)  # content is a bit vector
s_bytes = state.solver.eval(s_bv, cast_to=bytes)  # need to pass bit vectors to eval to get the data
```

See [another example](https://github.com/angr/angr/blob/ece7400d98e251edc02bfe1692693b6d68ab7485/tests/test_sprintf.py).

**Comment by pelopato** [comment]
> Bit vectors must be passed to eval to get the either the "real" underlying bytes, or a valid solution if the bit vector is symbolic and has a solution.
> 
> ```python
> pointer = state.solver.eval(state.regs.rbx)
> s_bv = state.memory.load(pointer, size_of_string)  # content is a bit vector
> s_bytes = state.solver.eval(s_bv, cast_to=bytes)  # need to pass bit vectors to eval to get the data
> ```
> 
> See [another example](https://github.com/angr/angr/blob/ece7400d98e251edc02bfe1692693b6d68ab7485/tests/test_sprintf.py).

**Comment by pelopato** [comment]
I have tried the following:

def hook_blah(state):
		pointer = state.solver.eval(state.regs.rbx)
		print("pointer:", hex(pointer))
		s_bv = state.memory.load(pointer, FLAG_SIZE)  # content is a bit vector
		print("s_bv:", s_bv)
		try:
			s_bytes = state.solver.eval(s_bv, cast_to=bytes)  # need to pass bit vectors to eval to get the data
			print("s_bytes:", s_bytes)
		except Exception as e:
			print("Exception:", e)`
`

result:
pointer: 0x7fffffffffeffc3
s_bv: <BV200 argv1_0_200>
Exception: Got an unsat result

**Comment by schieb** [comment]
As you probably know, the unsat result/exception means that there is not a valid, consistent solution for the object that you passed to `eval`. Either there is a bug somewhere (possibly angr itself), or there is in fact no solution.

There might be a partial solution to `s_bv` within the current context. Testing each byte one at a time might help debug the issue.

**Comment by pelopato** [comment]
> There might be a partial solution to `s_bv` within the current context. Testing each byte one at a time might help debug the issue.

How do i do it?

> As you probably know, the unsat result/exception means that there is not a valid, consistent solution for the object that you passed to `eval`

Although there is no valid solution, I would like to see the content of the argument.

thanks

**Comment by ltfish** [comment]
Can you post your binary and your full testing script?

**Comment by schieb** [comment]
> How do i do it?
Just get each individual byte and test it through `eval`. There are many ways to get a particular byte out of a bit vector. Try `chop`: [example](https://github.com/angr/angr-doc/blob/139150e496ee00dea741639e841f0f6123070716/examples/google2016_unbreakable_0/solve.py#L24).

> Although there is no valid solution, I would like to see the content of the argument.
I assume that by "see the content of the argument" you mean that you want to see all of the constraints associated with that symbolic bit vector for the given state. Nothing else makes sense because there is literally no solution, so asking for a solution can only raise an exception.

The constraints are an AST and are not meant to be very human-readable but with some work they might be helpful for you to debug the problem. I honestly don't remember how to access them from the top of my head.

**Comment by pelopato** [comment]
Basically I want to see all the combinations that you are testing until you find (or not) the solution.

**Comment by schieb** [comment]
A linear sweep over each byte in the bit vector is sufficient to do what you are asking. See my previous comment about using `chop`. Pass each byte to eval - it is either satisfiable, or not. You either get *a* solution, or an exception.

**Comment by pelopato** [comment]
```python
for s in s_bv.chop(8):
	try:
		print("s_bv chop:", state.solver.eval(s_bv.chop(8), cast_to=bytes))
	except Exception as e:
		print("Exception:", e)
```
...
Exception: Got an unsat result
Exception: Got an unsat result
Exception: Got an unsat result
Exception: Got an unsat result
Exception: Got an unsat result
Exception: Got an unsat result
Exception: Got an unsat result

I just want to see the memory content...

**Comment by rhelmot** [comment]
The thing you're not understanding is _there is no memory content_, by
the definition you're using. print(s_bv) will give you the "thing"
that is stored in memory. You cannot convert this to byte data. It is
not possible. There is no answer which could possibly represent
anything real. s_bv is a tree of operations describing everything that
was done to compute the value in memory from the program's inputs. By
the fact that you are at this point in the program with these
computations, the program must have gone down some path - this path is
represented by a set of constraints, in state.solver.constraints. z3
is checking those constraints and determining that it is impossible to
actually go down the path that you're currently exploring. There is no
such thing as a bytes value that can exist in memory at this time. You
live in a no-man's land.

**Comment by ltfish** [comment]
> I just want to see the memory content...

If your state is not satisfiable, you *cannot* "see" the content of a symbolic variable. The only content you can get at the moment is your `s_bv`: `print(s_bv)` will print out that symbolic variable, but that's clearly not what you want.

The solution is to figure out _why your state becomes unsatisfiable when you call `state.solver.eval()`_. It's easier for me to help you if you can post your binary and your script.

**Comment by pelopato** [comment]
Thank you all, I'll think about it a little. The binary is very similar to this solution.
https://github.com/angr/angr-doc/blob/139150e496ee00dea741639e841f0f6123070716/examples/google2016_unbreakable_0/solve.py
Receive a parameter with this format: "CTF {xxx}"
Depending on the values "x" take a correct path or not.

**Comment by pelopato** [comment]
It seems that I have a solution but with errors:

```python
sm.explore(find=0x401027, avoid=0x4011af)
found = sm.found[0]
print(found)
solution = found.solver.eval(argv1, cast_to=bytes) # exception
```
result: <SimState @ 0x401027>
exception:
...
claripy.errors.UnsatError: CompositeSolver is already unsat
...
angr.errors.SimUnsatError: Got an unsat result

any ideas?

**Comment by ltfish** [comment]
Can you test if `found` is satisfiable? `print(found.satisfiable())`.

Any chance you enabled `LAZY_SOLVES` for your state? You can see what state options are enabled by doing `print(state.options.tally())`.

**Comment by pelopato** [comment]
print(found.satisfiable() = False
print("found.options.tally()) = 
ALL_FILES_EXIST: True
COMPOSITE_SOLVER: True
COPY_STATES: True
DO_CCALLS: True
DO_GETS: True
DO_LOADS: True
DO_OPS: True
DO_PUTS: True
DO_STORES: True
EXTENDED_IROP_SUPPORT: True
FILES_HAVE_EOF: True
LAZY_SOLVES: True
OPTIMIZE_IR: True
SIMPLIFY_MEMORY_WRITES: True
SIMPLIFY_REGISTER_WRITES: True
SUPPORT_FLOATING_POINT: True
SYMBOLIC: True
SYMBOLIC_INITIAL_VALUES: True
TRACK_CONSTRAINTS: True
TRACK_CONSTRAINT_ACTIONS: True
TRACK_MEMORY_MAPPING: True
jumptable_symbolic_ip_max_targets: 16384
symbolic_ip_max_targets: 256
initial_state: ALL_FILES_EXIST: True
COMPOSITE_SOLVER: True
COPY_STATES: True
DO_CCALLS: True
DO_GETS: True
DO_LOADS: True
DO_OPS: True
DO_PUTS: True
DO_STORES: True
EXTENDED_IROP_SUPPORT: True
FILES_HAVE_EOF: True
LAZY_SOLVES: True
OPTIMIZE_IR: True
SIMPLIFY_MEMORY_WRITES: True
SIMPLIFY_REGISTER_WRITES: True
SUPPORT_FLOATING_POINT: True
SYMBOLIC: True
SYMBOLIC_INITIAL_VALUES: True
TRACK_CONSTRAINTS: True
TRACK_CONSTRAINT_ACTIONS: True
TRACK_MEMORY_MAPPING: True
jumptable_symbolic_ip_max_targets: 16384
symbolic_ip_max_targets: 256

**Comment by rhelmot** [comment]
Lazy solves is on. This is not a default setting; you enabled this
yourself. It means you will be exploring parts of the state space that
aren't grounded in any sort of reality, and it's your responsibility to
handle the possibility that your states aren't actually reachable.

**Comment by pelopato** [comment]
> Can you post your binary and your full testing script?

Can I send it privately?
