### ISSUE TITLE
"Got STOP_NOSTART but a positive number of steps. This indicates a serious unicorn bug."

### ISSUE THREAD

**Issue by Phasip** [angr/angr#1516]
Hello great work with angr!

Running with angr installed from angr-dev checked out today on a ubuntu x86_64 machine against the current ubuntu busybox binary ( sha256 c3ef4ee36aa52398cc3c5d7e0f5965eec4230a20f894aab23ba8708b8617210c )
Code:
```
import angr
import logging
logging.getLogger('angr').setLevel('DEBUG') 
proj = angr.Project("./busybox")
state = proj.factory.full_init_state(args=["./busybox","abc"], add_options=angr.options.unicorn | {angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY})
simgr = proj.factory.simulation_manager(state)
simgr.run()
print(simgr)
for e in simgr.errored:
    print(e)
```
stdout:
```
<SimulationManager with 6 deadended (4 errored)>
<State errored with "Got STOP_NOSTART but a positive number of steps. This indicates a serious unicorn bug.">
<State errored with "Got STOP_NOSTART but a positive number of steps. This indicates a serious unicorn bug.">
<State errored with "Got STOP_NOSTART but a positive number of steps. This indicates a serious unicorn bug.">
<State errored with "Got STOP_NOSTART but a positive number of steps. This indicates a serious unicorn bug.">
```

Attached is binary, script, stdout and stderr output.
[bugreport.tar.gz](https://github.com/angr/angr/files/3075131/bugreport.tar.gz)

**Comment by rhelmot** [comment]
This appears to be what happens when unicorn sees a `hlt` instruction. I'll look into making it work better.

**Comment by rhelmot** [comment]
Thanks for reporting. I've fixed this in sort of a hacky way and filed a bug upstream to try to make a better solution possible. The script now shows the correct errored states:

```
<SimulationManager with 6 deadended (4 errored)>
<State errored with "Cannot execute following jumpkind Ijk_SigTRAP">
<State errored with "Cannot execute following jumpkind Ijk_SigTRAP">
<State errored with "Cannot execute following jumpkind Ijk_SigTRAP">
<State errored with "Cannot execute following jumpkind Ijk_SigTRAP">
```

All of the errored states have the following in their stderr:

```
../sysdeps/unix/sysv/linux/dl-origin.c:47: _dl_get_origin: Assertion `linkval[0] == '/'' failed.
```

probably because the `readlink` syscall is unimplemented. The constraints on the state indicate that the stubbed return value must be a failure, so I guess this makes sense.
