### ISSUE TITLE
PowerPC32 vex translation creating unused temp variables

### ISSUE THREAD

**Issue by HexRoman** [angr/angr#1528]
In PowerPC32 binaries, I see that many times in vex, in `opt_level=0` there are uses of temp variables that don't actually do anything. 

For example in the attached binary file:
`100005AC addi      r9, r31, 0x14`

`block = project.factory.block(0x100005ac, opt_level=0, size=4)`
`block.vex.pp()`
is translated to:
```
   00 | ------ IMark(0x100005ac, 4, 0) ------
   01 | t0 = GET:I32(gpr31)
   02 | t1 = GET:I32(gpr0) <------------ This use 
   03 | t2 = Add32(t0,0x00000014)
   04 | PUT(gpr9) = t2
   05 | PUT(cia) = 0x100005b0
```
In this example it's `gpr0`, but in other cases it could be any other register like `gpr10` or `gpr16`. 

This behavior makes the work with reaching definitions very challenging because it's hard to distinguish between the real uses and those fake ones. 

Any idea what are these fake uses?
[test_ppc32.zip](https://github.com/angr/angr/files/3101333/test_ppc32.zip)

**Comment by rhelmot** [comment]
It's just libvex being lazy and generic in its lifter design. To "fix" this
you either need to postprocess the blocks yourself or enable optimization.
Or, you could change libvex.

**Comment by ltfish** [comment]
Enabling optimization (setting `opt_level=1`) is the easiest way to solve this problem.
