### ISSUE TITLE
Got a IR decoding error on Ubuntu 16.4.3 32bit.

### ISSUE THREAD

**Issue by JohnSmith139** [angr/angr#1534]
*Disclaimer: The angr suite is maintained by a small team of volunteers. While we cannot guarantee any timeliness for fixes and enhancements, we will do our best. For more real-time help with angr, from us and the community, join our [Slack.](http://angr.io/invite/)*

---

**Describe the bug**
Please include a clear and concise description of what the bug is.

I got a IR decoding error on my program at ubuntu 16.4.3 using angr
but I don't have the error on the program at win7 32bit using angr

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>> import claripy
>>> project = angr.Project("./t4")
>>> argv1 = claripy.BVS("argv1",27*8) 
>>> initial_state = project.factory.entry_state(args=["./t4",argv1])
>>> sm = project.factory.simulation_manager(initial_state)
>>> sm.explore(find=0x8048105)
<SimulationManager with all stashes empty (1 errored)>
>>> sm.errored
[<State errored with "IR decoding error at 0x80480d0. You can hook this instruction with a python replacement using project.hook(0x80480d0, your_function, length=length_of_instruction).">]
>>> project.loader
<Loaded t4, maps [0x8048000:0xb008000]>
>>> angr.__version__
(8, 19, 4, 5)
>>> 
```

**Environment Information**
Many common issues are caused by problems with the local Python environment.
Before submitting, double-check that your versions of all modules in the angr suite (angr, cle, pyvex, ...) are up to date.
Please include the output of `python -m angr.misc.bug_report` here.

```
$ cat /proc/version
Linux version 4.15.0-30-generic (buildd@lcy01-amd64-030) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)) #32~16.04.1-Ubuntu SMP Thu Jul 26 20:24:45 UTC 2018

$ python3 -m angr.misc.bug_report
angr environment report
=============================
Date: 2019-04-25 16:51:04.788286
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-i686
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
######## angr #########
Python found it in /home/john/.local/lib/python3.5/site-packages/angr
Pip version angr 8.19.4.5
Couldn't find git info
######## ailment #########
Python found it in /home/john/.local/lib/python3.5/site-packages/ailment
Pip version ailment 8.19.4.5
Couldn't find git info
######## cle #########
Python found it in /home/john/.local/lib/python3.5/site-packages/cle
Pip version cle 8.19.4.5
Couldn't find git info
######## pyvex #########
Python found it in /home/john/.local/lib/python3.5/site-packages/pyvex
Pip version pyvex 8.19.4.5
Couldn't find git info
######## claripy #########
Python found it in /home/john/.local/lib/python3.5/site-packages/claripy
Pip version claripy 8.19.4.5
Couldn't find git info
######## archinfo #########
Python found it in /home/john/.local/lib/python3.5/site-packages/archinfo
Pip version archinfo 8.19.4.5
Couldn't find git info
######## z3 #########
Python found it in /home/john/.local/lib/python3.5/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/john/.local/lib/python3.5/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
unicorn: <CDLL '/home/john/.local/lib/python3.5/site-packages/unicorn/lib/libunicorn.so', handle 8dd3278 at 0xb6647ccc>
angr: <CDLL '/home/john/.local/lib/python3.5/site-packages/angr/lib/angr_native.so', handle 91b1ae8 at 0xb4ce71cc>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0xb702834c>
z3: <CDLL '/home/john/.local/lib/python3.5/site-packages/z3/lib/libz3.so', handle 9744630 at 0xb229acac>
```

I installed angr on 2019.04.24 using the command "pip3 install angr“.

**To Reproduce**
Please include *both a script to reproduce the crash, and attach the binary used, if possible*

[t4.zip](https://github.com/angr/angr/files/3116004/t4.zip)

my pycode:

```
import angr
import claripy
project = angr.Project("./t4")
argv1 = claripy.BVS("argv1",27*8) 
initial_state = project.factory.entry_state(args=["./t4",argv1])
sm = project.factory.simulation_manager(initial_state)
sm.explore(find=0x8048105)
```

**Additional context**

**Comment by ltfish** [comment]
I cannot reproduce this issue under Linux. Can you take a look at the bytes at 0x80480d0 in angr's memory (`print(state.solver.eval(state.memory.load(0x80480d0, 20), cast_to=bytes))`)?

**Comment by JohnSmith139** [comment]
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>> import claripy
>>> project = angr.Project("./t4")
>>> argv1 = claripy.BVS("argv1",27*8) 
>>> initial_state = project.factory.entry_state(args=["./t4",argv1])
>>> sm = project.factory.simulation_manager(initial_state)
>>> state = initial_state
>>> print(state.solver.eval(state.memory.load(0x80480d0, 20), cast_to=bytes))
b'\x8b\x0c$\x83\xf9\x00t9\x8bD$\x08\x89\xc3\xb9\x00\x00\x00\x00\xbe'
>>> sm.explore(find=0x8048105)
<SimulationManager with all stashes empty (1 errored)>
>>> sm.errored
[<State errored with "IR decoding error at 0x80480d0. You can hook this instruction with a python replacement using project.hook(0x80480d0, your_function, length=length_of_instruction).">]
>>> 







电子名片新出VIP模板啦，快来体验>>




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Fish  <notifications@github.com>
 

 
 发送时间: 2019-04-25 17:17:16
 

 
 收件人:angr/angr <angr@noreply.github.com> 

 
 抄送:bxbyface <bxbyface@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [angr/angr] Got a IR decoding on Ubuntu 16.4.3 32bit. (#1534)
 



I cannot reproduce this issue under Linux. Can you take a look at the bytes at 0x80480d0 in angr's memory (print(state.solver.eval(state.memory.load(0x80480d0, 20), cast_to=bytes)))?

**Comment by rhelmot** [comment]
The bytes you posted decode fine, and I also can't reproduce your issue. Can you use `sm.errored.state` as the state and post the bytes like fish asked?

**Comment by rhelmot** [comment]
additionally, can you try running this?

```python
import pyvex, archinfo

pyvex.lift(b'\x8b\x0c$\x83\xf9\x00t9\x8bD$\x08\x89\xc3\xb9\x00\x00\x00\x00\xbe', 0x1000, archinfo.ArchX86()).pp()
```

**Comment by JohnSmith139** [comment]
>>> sm.errored
[<State errored with "IR decoding error at 0x80480d0. You can hook this instruction with a python replacement using project.hook(0x80480d0, your_function, length=length_of_instruction).">]
>>> state1 = sm.errored.state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'state'
>>> sm.errored.state
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'state'
>>> type(sm.errored)
<class 'list'>
>>> 







电子名片新出VIP模板啦，快来体验>>




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Audrey Dutcher  <notifications@github.com>
 

 
 发送时间: 2019-04-26 09:52:06
 

 
 收件人:angr/angr <angr@noreply.github.com> 

 
 抄送:bxbyface <bxbyface@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [angr/angr] Got a IR decoding on Ubuntu 16.4.3 32bit. (#1534)
 



The bytes you posted decode fine, and I also can't reproduce your issue. Can you use sm.errored.state as the state and post the bytes like fish asked?

**Comment by JohnSmith139** [comment]
>>> pyvex.lift(b'\x8b\x0c$\x83\xf9\x00t9\x8bD$\x08\x89\xc3\xb9\x00\x00\x00\x00\xbe', 0x1000, archinfo.ArchX86()).pp()
IRSB {
   

   NEXT: PUT(eip) = 0x00001000 Ijk_NoDecode
}
>>> 



电子名片新出VIP模板啦，快来体验>>




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Audrey Dutcher  <notifications@github.com>
 

 
 发送时间: 2019-04-26 09:53:24
 

 
 收件人:angr/angr <angr@noreply.github.com> 

 
 抄送:bxbyface <bxbyface@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [angr/angr] Got a IR decoding on Ubuntu 16.4.3 32bit. (#1534)
 



additionally, can you try running this?

 
import pyvex, archinfo

pyvex.lift(b'\x8b\x0c$\x83\xf9\x00t9\x8bD$\x08\x89\xc3\xb9\x00\x00\x00\x00\xbe', 0x1000, archinfo.ArchX86()).pp()

**Comment by JohnSmith139** [comment]
>>> state1 = sm.errored[0].state
>>> print(state1.solver.eval(state1.memory.load(0x80480d0, 20), cast_to=bytes))
b'\x8b\x0c$\x83\xf9\x00t9\x8bD$\x08\x89\xc3\xb9\x00\x00\x00\x00\xbe'







电子名片新出VIP模板啦，快来体验>>




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Audrey Dutcher  <notifications@github.com>
 

 
 发送时间: 2019-04-26 09:52:06
 

 
 收件人:angr/angr <angr@noreply.github.com> 

 
 抄送:bxbyface <bxbyface@139.com>,Author <author@noreply.github.com> 

 
 主题: Re: [angr/angr] Got a IR decoding on Ubuntu 16.4.3 32bit. (#1534)
 



The bytes you posted decode fine, and I also can't reproduce your issue. Can you use sm.errored.state as the state and post the bytes like fish asked?

**Comment by rhelmot** [comment]
okay. the test with pyvex just indicates that you've somehow installed pyvex incorectly. That test should produce something other than NoDecode.

I don't really know how to help you debug your installation...

**Comment by ltfish** [comment]
I just reproduced it on Ubuntu 16.04 **32-bit**! Looking into the problem.

**Comment by ltfish** [comment]
@JohnSmith139 You should consider switching to Ubuntu 64-bit if possible. No core developer uses 32-bit OS anymore, and it's really hard for us to offer help for angr running on 32-bit OS.

**Comment by JohnSmith139** [comment]
OK, Thanks. 







电子名片新出VIP模板啦，快来体验>>




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: Fish  <notifications@github.com>
 

 
 发送时间: 2019-04-26 11:45:41
 

 
 收件人:angr/angr <angr@noreply.github.com> 

 
 抄送:bxbyface <bxbyface@139.com>,Mention <mention@noreply.github.com> 

 
 主题: Re: [angr/angr] Got a IR decoding on Ubuntu 16.4.3 32bit. (#1534)
 



@JohnSmith139 You should consider switching to Ubuntu 64-bit if possible. No core developer uses 32-bit OS anymore, and it's really hard for us to offer help for angr running on 32-bit OS.

**Comment by ltfish** [comment]
Culprit: https://github.com/angr/vex/commit/84346f96dcef5223710133b22a00cbe6938ad345

@JohnSmith139 as a workaround, you can fix this problem right now by manually reverting that commit, compiling vex and pyvex, and then installing pyvex locally.

I will leave this to @rhelmot to fix it.

**Comment by JohnSmith139** [comment]
Thanks. I will get a try. Should I close the issue or let it open?

**Comment by JohnSmith139** [comment]
I downloaded the vex  code from angr/vex, and did the following changes on the file pub/libvex_guest_x86.h 
      HWord  guest_LDT; /* host addr, a VexGuestX86SegDescr* */
      HWord  guest_GDT; /* host addr, a VexGuestX86SegDescr* */
      //ULong  guest_LDT; /* host addr, a VexGuestX86SegDescr* */
      //ULong  guest_GDT; /* host addr, a VexGuestX86SegDescr* */
make it, get the libvex.a libvex.so

then I downloaded the pyvex code from angr/vex,
enter the directory pyvex_c, make it, got the libpyvex.a libpyvex.so

copy the four files  libvex.a libvex.so  libpyvex.a libpyvex.so to the directory:
~/.local/lib/python3.5/site-packages/pyvex/lib/ replacing the two files  libvex.a libvex.so  libpyvex.a .

tried the python code again, and got the same error.

what else should I do?

**Comment by rhelmot** [comment]
I will have a fix eventually... you're free to keep futzing around with trying to compile or debug stuff, but I can't really help you.

**Comment by JohnSmith139** [comment]
OK. Thanks.

**Comment by ltfish** [comment]
@JohnSmith139 This is what you want to do to recompile libvex and pyvex with your patch:

- Clone VEX and PyVEX. Put those repos under the same directory.
- In VEX, apply the patch as described above.
- Compile VEX by doing `make -f Makefile-gcc` under `vex` directory.
- If your angr is installed in a virtualenv, activate it by running `workon <name of your virtualenv>`.
- Uninstall the currently installed pyvex by doing `pip uninstall pyvex`.
- Go to the `pyvex` directory, and compile and install PyVEX by doing `pip install .`.

**Comment by JohnSmith139** [comment]
1.    Clone VEX and PyVEX. Put those repos under the same directory.
  Ensure the name of the directory of VEX is vex
 2.   In VEX, apply the patch as described above.
  do the following changes on the file pub/libvex_guest_x86.h
HWord guest_LDT; /* host addr, a VexGuestX86SegDescr* /
HWord guest_GDT; / host addr, a VexGuestX86SegDescr* /
//ULong guest_LDT; / host addr, a VexGuestX86SegDescr* /
//ULong guest_GDT; / host addr, a VexGuestX86SegDescr* */
 3.   Compile VEX by doing make -f Makefile-gcc under vex directory.
 It should not be necessary.
 4.   If your angr is installed in a virtualenv, activate it by running workon <name of your virtualenv>.
 I skipped it for not be in a virtualenv.
 5.   Uninstall the currently installed pyvex by doing pip uninstall pyvex.
  pip3 uninstall pyvex
 6.   Go to the pyvex directory, and compile and install PyVEX by doing pip install ..
  (1). go to the pyvex directory.
  (2). python3 setup.py bdist_wheel
  (3). go to the bdist subdirctory
  (4). pip3 install pyvex-8.19.4.5-py3-none-manylinux1_i686.whl ( replace with your wheel file's name)
 
Then It works.  no error return, but sm.explore(find=0x8048105) is running for a long time without return . It's same as in windows. :<

$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>> import claripy
>>> project = angr.Project("./t4")
>>> argv1 = claripy.BVS("argv1",27*8) 
>>> initial_state = project.factory.entry_state(args=["./t4",argv1])
>>> sm = project.factory.simulation_manager(initial_state)
>>> sm.explore(find=0x8048105)

**Comment by rhelmot** [comment]
Indeed. That is because your script is not a very efficient solver for the crackme.

**Comment by JohnSmith139** [comment]
Any suggestion for the usage of angr?
