### ISSUE TITLE
I cannot find all possible paths with path_group.explore(find=function)

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#154]
hi,
I use Angr's path_group.explore(find=function) to find all possible paths which can goto this function,but I only get one path found and actually there are more than one path.
 Below is my tested program.

```
#include <stdio.h>
int main(int argc, char** argv)
{
  
  int a=argv[1][0];
  int b=argv[2][0];
  int x=1;
  if(a<0xcc)
  { 
	  Func1(x);	  
  }
  if(b<0xaa){
	  Func1(x);
  }
  return 0; 
}
```

 Below is the commands.
```python
#!/usr/bin/env python
#coding=utf-8
import angr
import sys
import claripy

b=angr.Project('test_found_path',load_options={'auto_load_libs': True})

arg0=claripy.BVV(0x4321,32)
Sarg1=claripy.BVS('arg1',32)
Sarg2=claripy.BVS('arg2',32) 

p=b.factory.path(args=[arg0,arg1,arg2])
pg=b.factory.path_group(p)
found_func=[ad for ad,func in cfg.kb.functions.iteritems() if funcName==func.name]

print funcName,':',found_func

if(len(found_func)>0):
    ad=found_func[0]	
pg=pg.explore(find=ad)

print pg
print "found : ",pg.stashes['found'].__len__()
for _found_path in pg.stashes['found']: 
    print "found_path's addr is",_found_path.addr
    print "found_path's constraints are",_found_path.state.se.constraints

print "unsat : ",pg.stashes['unsat'].__len__()
for _unsat in pg.stashes['unsat']:
    print "_unsat_path's addr is",_unsat.addr
    print "_unsat_path's constraints are",_unsat.state.se.constraints
```

The result is showing as follows.
```
Func1 : [4195574L]
<PathGroup with 2 active, 1 found>

found :  1
found_path's addr is 4195574
found_path's constraints are [<Bool arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:24] <=s 0xcb>]

unsat :  0
```

In the tested program, I think there are two paths which can goto Func1,but I only found one .As we can see from the result ,state only stored one contraint(which got from the first 'if' ). I am not sure it is because my tested program has problems or I did not use right commands or something else.

Thanks a lot!

**Comment by rhelmot** [comment]
Hi! by default, pathgroup.explore() will stop when it finds one path that satisfies the given conditions. To find more, you should pass `num_find=n`, where `n` is the number of paths you'd like to find.

**Comment by brokendragon** [comment]
@rhelmot thanks for your help. 
I have tried to add num_find=2 to my commands and I did not change my tested program, but I got one found and one unsat. So , If I find the function in 'if' part, other calling sites about this function which is below the 'if' will be classified as ‘unsat’ ?
Below is the result.

`Func1 : [4195574L]
<PathGroup with 1 deadended, 1 unsat, 1 found>
===============
found :  1
found_path's addr is 4195574
found_path's constraints are [<Bool arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:24] <=s 0xcb>]
===============
unsat :  1
_unsat_path's addr is 4195574
_unsat_path's constraints are [<Bool arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:31] .. arg1_19_32[31:24] >s 0xcb>, <Bool arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:31] .. arg2_20_32[31:24] <=s 0xa9>]`

**Comment by rhelmot** [comment]
can you post `path.trace.hardcopy` for each of the paths in the path group?

**Comment by brokendragon** [comment]
ok.
Below is the  path.trace.hardcopy for each of the paths in this path group,including one found, one usat and one deadended.

`Func1 : 0x4004f6L
<PathGroup with 1 deadended, 1 unsat, 1 found>
===============
found :  1
found_path's addr is 0x4004f6L
['<SimIRSB 0x400400>', '<SimIRSB 0x4003e0>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x4005a0>', '<SimIRSB 0x4003a8>', '<SimIRSB 0x4003bd>', '<SimIRSB 0x4005d3>', '<SimIRSB 0x4005d8>', '<SimIRSB 0x4004d0>', '<SimIRSB 0x4004db>', '<SimIRSB 0x400470>', '<SimIRSB 0x4004a8>', '<SimIRSB 0x4005ed>', '<SimIRSB 0x4005f6>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x400527>', '<SimIRSB 0x40056e>']

unsat :  1
_unsat_path's addr is 0x4004f6L
['<SimIRSB 0x400400>', '<SimIRSB 0x4003e0>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x4005a0>', '<SimIRSB 0x4003a8>', '<SimIRSB 0x4003bd>', '<SimIRSB 0x4005d3>', '<SimIRSB 0x4005d8>', '<SimIRSB 0x4004d0>', '<SimIRSB 0x4004db>', '<SimIRSB 0x400470>', '<SimIRSB 0x4004a8>', '<SimIRSB 0x4005ed>', '<SimIRSB 0x4005f6>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x400527>', '<SimIRSB 0x400578>', '<SimIRSB 0x400581>']

deadended :  1
_unsat_path's addr is 0x4000020
['<SimIRSB 0x400400>', '<SimIRSB 0x4003e0>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x4005a0>', '<SimIRSB 0x4003a8>', '<SimIRSB 0x4003bd>', '<SimIRSB 0x4005d3>', '<SimIRSB 0x4005d8>', '<SimIRSB 0x4004d0>', '<SimIRSB 0x4004db>', '<SimIRSB 0x400470>', '<SimIRSB 0x4004a8>', '<SimIRSB 0x4005ed>', '<SimIRSB 0x4005f6>', '<SimProcedure __libc_start_main>', '<SimIRSB 0x400527>', '<SimIRSB 0x400578>', '<SimIRSB 0x40058b>']
`

**Comment by rhelmot** [comment]
okay. here's my best guess to what's happening:

Technically, that deadended path you found is unsatisfiable. It's actually completely impossible for your program to not take the first if branch - this is because you've implicitly casted a char to an int, both of which are signed variables, so the range of possible values for both `a` and `b` is [-0x80, 0x7f]. Try changing 0xcc and 0xaa to 0x40 and 0x60 or something!

**Comment by rhelmot** [comment]
also, if you want to post multiline blocks of monospace text, you need your markdown to start and end with three backticks, and the backticks must be on their own line. I've been fixing up your comments for readability, but you may want to keep this in mind in the future :)

**Comment by brokendragon** [comment]
ok,thank you very much,I will try change the values . Thanks for your proposal and i will pay attention to my format. I'm sorry for the trouble.
