### ISSUE TITLE
Disassembly Fails on Object Files

### ISSUE THREAD

**Issue by xavierholt** [angr/angr#1551]
Angr fails to fully disassemble the following program when it is compiled to an object file rather than an executable:

```C
#include <stdio.h>

int main() {
  puts("Hello world.\n");
  return 7;
}
```

Disassembling the `main()` function only gives the first basic block:

```asm
main:
push    rbp
mov     rbp, rsp
lea     rdi, [0x400017]
call    0x400010
```

If the program is compiled to an executable, the full disassembly is produced:

```asm
main:
push    rbp
mov     rbp, rsp
lea     rdi, [0x4006e4]
call    puts
mov     eax, 0x7
pop     rbp
ret     
```

The problem seems to be that when loading from an object file, the first CFG node for the main function has no successors:

```
>>> n
<CFGNode main 0x400000[16]>
>>> n.block.pp()
0x400000:	push	rbp
0x400001:	mov	rbp, rsp
0x400004:	lea	rdi, [rip + 0xc]
0x40000b:	call	0x400010
>>> n.successors
[]
```

**Environment Information**

I'm running Angr from inside the `angr/angr` Docker container.

```
(angr) angr@042bb26d910e:/tmp$ python -m angr.misc.bug_report
angr environment report
=============================
Date: 2019-04-30 23:37:54.865824
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.19.2.4
Git info:
	Current commit d2d68212f5c4d76dbb130fa746b527bc515c5297 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 8.19.2.4
Git info:
	Current commit bea5c50e987406af0264922cf8f10a765fdda210 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.19.2.4
Git info:
	Current commit afd546cfa47a182149b7b9c17590a7defc0cbc83 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.2.4
Git info:
	Current commit 050ffe4f45deb5e1aaad37312d83972c907682c3 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.19.2.4
Git info:
	Current commit 973e9e59ed17a89f9637dafa3deaae250db82d81 from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.2.4
Git info:
	Current commit 113620edbf2d4bd15b7de0cc2a93dc2ebe9570b8 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## ana #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/ana
Pip version ana 0.5
Couldn't find git info
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 2fa44c0 at 0x7f760a37c1d0>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2b13000 at 0x7f760e1e9278>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f760ee40fd0>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 35d3870 at 0x7f7608720780>
```

**Comment by rhelmot** [comment]
This is just because angr (specifically, CLE) doesn't support the relocations found in object files, so the calls will look like they're jumping to nonsense locations and the CFG will assume the function cannot proceed past the call.

If you want to take a crack at this, you should look at the warnings that appear when loading the binary of the form `[18:33:50] [cle.backends.elf.relocation] |  WARNING: Unknown reloc 4 on AMD64` and implement them. All the relocations are implemented [here](https://github.com/angr/cle/tree/master/cle/backends/elf/relocation). Relocations extend the base `Relocation` class or one of its children to implement the methods needed to identify the actual value to write to memory and where to write it.

**Comment by rhelmot** [comment]
Once the relocation is implemented, CLE will notice that the relocation is asking for a symbol which can't be found and create an address in the externs segment. Then, angr will notice there's a function address in the externs segment, so it will see if it knows how to hook over it with a specific simprocedure, and if not, will fall back to ReturnUnconstrained. Then, CFG will be able to proceed.

**Comment by subwire** [comment]
@rhelmot @xavierholt aha, indeed it is:

```
WARNING | 2019-04-30 18:39:18,962 | cle.backends.elf.relocation | Unknown reloc 4 on AMD64

```

**Comment by sraboy** [comment]
In case anyone gets around to it, see page 72 [here](https://www.uclibc.org/docs/psABI-x86_64.pdf).

**Comment by xavierholt** [comment]
Thanks!  I'll try to take a shot at it when I get time, mayybe over the weekend.

**Comment by xavierholt** [comment]
Now that I got a chance to look at this, it seems like it'll be kinda tricky.  This particular relocation (R_X86_64_PLT32) uses "the place (section offset or address) of the Procedure Linkage Table entry for a symbol" in its address calculation.  But the object files produced by GCC don't contain a PLT.

**Comment by sraboy** [comment]
I think you could still implement it, as if the PLT were there. I haven't looked at this code in a while so I'm curious what the ELF Backend will do here. If the `P` value is `None`, you'd see a `TypeError` exception when attempting to do math with it. If it's an integer value, it should still work, at least as far as having a relocation present. If it's not present, the relocation could still return some `extern` address to make the CFG happy... maybe pointing to some simulated thunk (or maybe we need a Backend for object files)?
