### ISSUE TITLE
CFG Protos in Separate Package

### ISSUE THREAD

**Issue by sraboy** [angr/angr#1561]
---

**Is your feature request related to a problem? Please describe.**

When someone who doesn't use angr wants to ingest the CFG proto, the definitions are unavailable unless they install angr.

**Describe the solution you would like.**

Create a separate `angr_protos` repo.

**Please include a sample of what *should* work if this feature is implemented.**

`from angr_protos import cfg_pb2` and `git submodule add git@github.com:angr/angr_protos`

**Describe alternatives you have considered.**

Keeping separate copies of the protobufs and hoping the user's angr installation hasn't changed them.

**Additional context.**

CHESS

**Comment by rhelmot** [comment]
(realistically this is the old bar4 idea, where we have a common repo of data definitions that we can use to store research results and artifacts for easy comparisons)

**Comment by zwimer** [comment]
We do not plan to implement this idea currently.
