### ISSUE TITLE
Identify the number of function argument in the binary function

### ISSUE THREAD

**Issue by yasong** [angr/angr#1564]
**Can angr identify the number of function argument used in the function call?
Thank you.**

**Comment by twizmwazin** [comment]
Hey, thanks for this issue. This feels like a new feature you're requesting. We have a feature request template, and would appreciate it if you would reformat your issue with that template. You can see the template here: https://github.com/angr/angr/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Thanks!

**Comment by ltfish** [comment]
Calling convention analysis in angr is what you want.

**Comment by yasong** [comment]
@ltfish Thank you. Could you tell me the detail API to get the number of function argument?

**Comment by ltfish** [comment]
Take a look at [calling_convention.py](https://github.com/angr/angr/blob/master/angr/analyses/calling_convention.py).

**Comment by yasong** [comment]
Thank you.
