### ISSUE TITLE
I wonder how to give program input stdin (scanf,ReadConsoleA,read function) by angr

### ISSUE THREAD

**Issue by pcy190** [angr/angr#1566]
---

When I use `k = state.posix.files[0].read_from(1)` or `state.posix.files[0].content.store(0, k )` , It report errors that `AttributeError: SimSystemPosix' object has no attribute 'files' `
It seems `posix` doesn't have attribute `file` in the latest angr version. 

So I wonder how to give problem INPUT correctly in the latest angr. Can I use `posix`'s other attribute? (I couldn't find anything from angr docs to solve this problem) .

I would appreciate it if could you offer me an example code to demonstrate the program Input.

**Comment by ltfish** [comment]
`posix.files` have long gone. Now you need to go through file descriptors (`posix.fds`). If you want to specify input through `stdin` for a program, you can either pass that in through `stdin=` when creating the state, or directly write to `posix.stdin` after creating the state: `state.posix.stdin.write(None, your_content_as_a_claripy_ast)`.

This should be definitely documented.

**Comment by ltfish** [comment]
Also, I don't think we support the Windows API `ReadConsoleA` - you will have to implement it by yourself.

**Comment by pcy190** [comment]
Get it. Thanks
