### ISSUE TITLE
Nested structs don't contain members of inner structs

### ISSUE THREAD

**Issue by Da5hes** [angr/angr#1573]
while defining structures in angr, i have encountered a problem with nested structs:
when you define a struct that contains other structs - this struct does not contain the sub-struct's members

example below

**Environment Information.**
angr environment report
=============================
Date: 2019-05-18 23:11:41.330655
Running in virtual environment at /home/da5h/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
######## angr #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/angr
Pip version angr 8.19.4.5
Couldn't find git info
######## ailment #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/ailment
Pip version ailment 8.19.4.5
Couldn't find git info
######## cle #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/cle
Pip version cle 8.19.4.5
Couldn't find git info
######## pyvex #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/pyvex
Pip version pyvex 8.19.4.5
Couldn't find git info
######## claripy #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/claripy
Pip version claripy 8.19.4.5
Couldn't find git info
######## archinfo #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/archinfo
Pip version archinfo 8.19.4.5
Couldn't find git info
######## z3 #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in /home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/angr/lib/angr_native.so', handle 3475b70 at 0x7f7760945780>
unicorn: <CDLL '/home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2ef0610 at 0x7f775fc50208>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f7760895278>
z3: <CDLL '/home/da5h/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 3ce5f80 at 0x7f77501c2f28>

**To Reproduce.**

reproducible with any method of adding structs into anger, for example
angr.types.define_struct('struct ahdr { int a ;}')
angr.types.define_struct('struct bhdr { int b ;}')
angr.types.define_struct('struct chdr { int c ;}')
angr.types.register_types(angr.types.parse_types('typedef struct ahdr ahdr;'))
angr.types.register_types(angr.types.parse_types('typedef struct bhdr bhdr;'))
angr.types.register_types(angr.types.parse_types('typedef struct chdr chdr;'))
angr.types.define_struct('struct dhdr { struct ahdr a; struct bhdr b; struct chdr c;}')

expected results:
angr.types.ALL_TYPES['dhdr'].fields['ahdr'].fields should return int a; 

current results:
angr.types.ALL_TYPES['dhdr'].fields['ahdr'].fields returns an empty dict

UPDATE:

it seems that by issuing : 
angr.types.define_struct('struct dhdr { struct ahdr a; struct bhdr b; struct chdr c;}')

 angr parses and redefines all 4 structs , even the other 3 that were already well defined, and it overwrites the structs that were already defined with empty structs

**Comment by rhelmot** [comment]
that update was super useful in figuring this out. I've pushed a commit to resolve this. However, this has made me realize that there are several inconsistencies in our docs and our usage of the type parsing code, which has evolved over time and gained new capabilities. I've opened https://github.com/angr/angr/issues/1574 for that, if you like you could take a look at it! it's pretty simple, I just barely have time to breathe, let alone rewrite docs.
