### ISSUE TITLE
Usage of type code with structs is outdated

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1574]
Once upon a time in angr, I didn't understand that there was a difference between the declaration of a struct (`struct asdf`) and a global typename for a structure (`typedef struct asdf asdf;`), because we all grow and learn things with time, and sometimes while designing a gigantically complicated system you mistake the trees for the forest.

Regardless, there's some weird inconsistent behavior in angr.sim_type related to structure (and union, but nobody uses those) declarations. `angr.sim_type.define_struct` was up until yesterday a function which added to the global type namespace the typename of the struct (`asdf`) but not the `struct asdf` name. this is bad obviously!!! i just made it so it added both, but really it should just add `struct asdf`. I have no idea the extent to which people rely on this behavior, so deprecating it would be weird, except...

Really, `define_struct` should not exist at all. I think the only reason it existed was because I thought "oh well the point of simtypes is to make it so you can type `state.mem[addr].type`, and you can't type types there that have spaces in their names, so what's the point! anyway I later realized I could just add `struct` as a special keyword to the mem accessors, so now you can go `state.mem[addr].struct.asdf`, so there's absolutely no need to have a big important function to import struct names as global typenames.

So, a to-do list:
- mark define_struct as deprecated
- fix the docs which tell you to use define_struct and add the `state.mem[addr].struct.name` syntax

**Comment by saullocarvalho** [comment]
Hello @rhelmot! How can I help?

What should be used instead of `define_struct()`? `register_types(parse_types())`? This alternative does not work exactly the same way.

Example:
`define_struct('struct aa { int x; }')` works, while `register_types(parse_types('struct aa { int x; }'))` does not.
`define_struct('struct aa { int x; } *;* ' )` and `register_types(parse_types('struct aa { int x; } *;* '))` work.

The semicolon at the end makes the difference.
As `register_types` expects an iterable and `parse_type` returns a SimStruct, `register_types(parse_type('struct aa { int x; }'))` does not work too.

I am not sure how relevant is this issue. What do you think?
Defining `register_type` would allow to use `register_type(parse_type())` instead of `define_struct()`.

**Comment by rhelmot** [comment]
I'm about evenly split between `register_types(parse_type(type_expr))`, `parse_type(type_expr register=True)`, and `register_types(type_expr)`. I'm sure you can see the pros and cons of each of them.

This also reminded me of a very related issue, which I think deserves attention alongside:

There's actually a very big difference in C between a type expression (`parse_type`, `define_struct`) and a series of declarations (`parse_types`, `parse_defns`, `parse_file`). One is an expression and one is a statement. One of the problems here is that our type expression parsing is partially broken! This is a consequence of the (un)intuitive way you write types in C - the old "declaration follows usage" thing. I couldn't find a good way in pycparser last I checked to actually parse a type expression. You have to feed full declarations in. As a result we have to reformat the types passed into `parse_type` into declarations, by prepending `"typedef "` and appending `"QQQQ;"`. Yes, this is literally how it works, check the code. The problem is that this doesn't work! For function and array types, the name does not go at the end, since declaration follows usage.

We should fix this. It may involve some hacking of pycparser, which I'm sure would be a welcome pull request upstream.

**Comment by saullocarvalho** [comment]
Regarding this issue: Should I mark `define_struct(struct_exp)` as deprecated, even with no direct substitute? The docs fixes should substitute `define_struct(struct_exp)` for `register_types(parse_types(struct_defn))` and `state.mem[addr].name` for `state.mem[addr].struct.name`?

I am looking at the `sim_type.py` code and playing with `pycparser` (I have never used it). As soon as I think about some hacking, I ping you!

**Comment by saullocarvalho** [comment]
While I was playing with `parse_types`, I have noticed an interesting behavior.

`parse_types` returns an empty `dict` when it is executed with a single function definition as parameter. When the function definition is within an union type definition, its corresponding `SimTypeFunction` is returned as a member of the corresponding `SimUnion`. The same occurs with array definitions.

**To reproduce:**

```python
>>> angr.types.parse_types('char a[20];')
{}
>>> angr.types.parse_types('int a[20];')
{}
>>> angr.types.parse_types('char *f (int x, float f);')
{}
>>> angr.types.parse_types('union aa { char a[20]; char *f (int x, float f); };')
{'union aa': union {
        a char[20];
        f (int, float) -> char*;
 }}
```

Is this behavior expected? As it is expected that `parse_type` parses function and array types, I think it is not.

**Comment by rhelmot** [comment]
I don't understand your first post. define_struct has a good substitute. We should probably implement one of the solutions I described for registering an individual type before we mark it deprecated though.

Your second post is expected, because `f` is a definition of a value, not a type. Look at `parse_file` and `parse_defns`.

**Comment by saullocarvalho** [comment]
First post: you answered. Your idea is to implement one of the solutions before mark `define_struct` deprecated!

Should `parse_types('char a[20];')` not return `char[20]` (`SimTypeFixedSizeArray`)?

**Comment by rhelmot** [comment]
it should not. `parse_defns('char a[20];')` should return `{a: char[20]}`.

**Comment by rhelmot** [comment]
using a format string is not a good solution. Ideally we would be able to provide anything that, for example, IDA can accept when it asks you for a type, i.e. with the name either missing or provided. I really think we should use a different interface to pycparser.

**Comment by saullocarvalho** [comment]
My idea is to substitute `defn = 'typedef ' + defn.strip('; \n\t\r') + ' QQQQ;'` for `defn = ('typedef ' + defn.strip('; \n\t\r')).format('QQQQ') + ';'`. `parse_type` would be executed as the following examples:

```python
>>> parse_type('int * ?')
>>> parse_type('char ?[20]')
>>> parse_type('int ?(int a, float b)')

**Comment by rhelmot** [comment]
I dont like that!

**Comment by saullocarvalho** [comment]
Ok! I will keep thinking about an alternative to this.

**Comment by saullocarvalho** [comment]
Do you have some interface in mind?

**Comment by rhelmot** [comment]
>  Ideally we would be able to provide anything that, for example, IDA can accept when it asks you for a type, i.e. with the name either missing or provided. I really think we should use a different interface to pycparser.

**Comment by saullocarvalho** [comment]
I have coded a simple decl and type parser using sly. The syntax isolate datatype from variable name.  The type expression parsing examples follows:

```python
parser > char
[('typedef', 'char')]
parser > *char[24]
[('typedef', ('array', ('pointer', 'char'), 24))]
parser > **int[30]; struct { int ; float; *int }
[('typedef', ('array', ('pointer', ('pointer', 'int')), 30)), ('struct', [('typedef', 'int'), ('typedef', 'float'), ('typedef', ('pointer', 'int'))])]
parser > *abcd[2]
[('typedef', ('array', ('pointer', 'abcd'), 2))]
parser > *(*abcd[3])
[('typedef', ('pointer', ('typedef', ('array', ('pointer', 'abcd'), 3))))]
```
The type names are not checked yet. Is this the type of hacking you were talking about?
I may continue coding the parser so it returns SimType objects, if you think it is interesting pursue this way.

The parser is at https://github.com/saullocarvalho/declparser

**Comment by rhelmot** [comment]
Kind of? I specifically mentioned messing with pycparser, which already has almost the grammar we need. I'm not a fan of another dependency or bundling a parser with angr but it would do the thing I wanted.

**Comment by saullocarvalho** [comment]
Sorry. Kind of!

**Comment by saullocarvalho** [comment]
I have found one way to use pycparser to parse type expressions. I have changed the start symbol of the cparser to 'parameter declaration', which accepts type expressions (including function and array type expressions) as input.

As this hack does not allow prepending typedef statements, used to define no basic types, I have had to modify the parse method of CParser to accept a scope_stack as argument, what solves the problem.

I have added `parse_type` test functions to be sure I do not break its core functionalities. I have created the PR #1595 with all the changes I've made.

**Comment by saullocarvalho** [comment]
`parse_type` function now parses type expressions and returns `SimType`. As registering a type into the global type namespace requires a typename (register_types receives a typename -> `SimType` mapping), `parse_type` does not do all the job.

Using the returned `SimType` representation works for struct, but it is not a general solution.

```python
>>> angr.types.parse_type('struct abcd')
struct abcd
>>> angr.types.parse_type('union abcd')
union abcd {

}
>>> angr.types.parse_type('int *')
int*
>>> angr.types.parse_type('char [12]')
char[12]
>>> angr.types.parse_type('int * (int, double)')
(int, double) -> int*
```

In my opinion, the possible general solutions would be `register_types({'typename': parse_type(type_expr)})` and `parse_type(type_expr, register=True, name='typename')`. `register_types(type_expr)` would need some extra work as it does not expect type expressions, but typename -> `SimType` mapping.

Should it be coded only a struct solution? If so, maybe `define_struct` should not be deprecated!
Should it be coded a general solution? If so, is any of the presented solutions acceptable?

**Comment by rhelmot** [comment]
Just pushed an acceptable solution.

**Comment by saullocarvalho** [comment]
This is great! I've just submitted a PR which updates struct usage.

**Comment by rhelmot** [comment]
Good work. I'll mark define_struct deprecated and update any examples using it.

**Comment by saullocarvalho** [comment]
I can do this, so you can focus on more important issues.
