### ISSUE TITLE
CFGAccurate Memory Requirements

### ISSUE THREAD

**Issue by marcusp46** [angr/angr#158]
Good Afternoon,

Is there a rule of thumb for the memory requirements for CFGAccurate reconstruction according to binary size?  On a system with 16GB of RAM, the procedure ran out of memory on /usr/bin/ssh.  I prefer to use CFGAccurate because the nature of our project demands the best CFG possible.  Any help would be appreciated, Thanks.

**Comment by rhelmot** [comment]
We have an FAQ entry in our docs (docs.angr.io) about excessive resource
consumption in CFGAccurate - try loading and the project without loading
shared libraries (load_options={auto_load_libs': False}) and seeing if you
have enough RAM then - there should be less of an explosion then.

**Comment by marcusp46** [comment]
Thanks!  What if I need the shared libraries as well?  I was hoping to get an interprocedural CFG  (super CFG)

**Comment by rhelmot** [comment]
There is generally not much you gain from this process. We have
SimProcedures implemented for most functions that modify control flow,
which is good enough to ensure good coverage on the binary. Library
functions themselves don't change between programs, so if you want an
analysis of those you should do this explicitly.

That being said, if you really want CFGAccurate to become tractable across
shared libraries, try turning the context sensitivity level down to zero. I
forget what the default value is but it's probably > 0.

**Comment by marcusp46** [comment]
Thanks again for the responsiveness.  The super CFG is a requirement for a current project.  So, I'm guessing the best bet is to do an analysis of the executable and each shared library and connect the callsites from the executable to the called functions via import/export symbols?  You have been a really great help!

**Comment by rhelmot** [comment]
Yep! That sounds like a good way to proceed. Glad I could help!
