### ISSUE TITLE
Backer is empty

### ISSUE THREAD

**Issue by OmarAflak** [angr/angr#1583]
I'm trying to run Angr on a `ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, stripped` file.

I'm getting the error `Backer is empty!` at the first line :

```python
angr.Project('./crackme')
```

Do you know where the problem might be coming from ?

Thanks !

**Comment by Alexeyan** [comment]
Please provide the binary so we can debug this issue.

**Comment by OmarAflak** [comment]
Here it is : https://mega.nz/#!PvBDXACY!l1F08TaOp_MbtkWBnJmHMu6VpA9FdtFFOUjBxlNJ6uE

**Comment by rhelmot** [comment]
This was resolved in https://github.com/angr/cle/commit/39ac6ea56dd21ea8504d3bc48257bb5d6c817f8a. Install the angr suite from github or wait for the next release.
