### ISSUE TITLE
Strange behavior with constraints on symbolic command-line argument

### ISSUE THREAD

**Issue by vivin** [angr/angr#1590]
I have this very simple C program with an obvious buffer-overflow on the stack:

```c
#include <stdio.h>
#include <string.h>

int main(int argc, char* argv[]) {
    char buf[32];
    strcpy(buf,argv[1]);
    printf("Input:%s\n",buf);
    return 0;
}
```

I've compiled this with `-fno-stack-protector` and `-z execstack`.

I can smash the stack on this and gain control of `rip` with the input string `python -c 'from struct import pack;print("A"*40 + str(pack("<Q", 0x424242424242), "utf-8"))'`. I can also verify in gdb that `rip` gets set to `0x424242424242`. 

However, I cannot solve for this `rip` value in angr. But I am able to solve for `rbp`.

This is my code:

```python
    proj = angr.Project("./csbo", exclude_sim_procedures_list=["strcpy"])

    # Make command-line arg symbolic
    num_input_chars = 64
    sym_commandline_arg = claripy.BVS("argv1", 8 * num_input_chars)

    state = proj.factory.entry_state(
        args=["csbo", sym_commandline_arg],
        add_options={
            angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY,
            angr.options.CONSTRAINT_TRACKING_IN_SOLVER
        }
    )

    # Looking for unconstrained paths
    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    # Step execution until we find an unconstrained path
    while sm.active and not sm.unconstrained:
        sm.step()

    # Make a copy of the state
    if not sm.unconstrained:
        raise Exception("Did not find any unconstrained paths!")

    s = sm.unconstrained[0].copy()

    pattern = 0x4142434445464748
    s.add_constraints(s.regs.rbp == pattern)
    assert s.satisfiable()
```

This works and I am also able to solve for a value of the command-line arg that will satisfy the constraints. However, when I add `s.add_constraints(s.regs.rip == 0x0000424242424242)`, the constraints are no longer satisfiable. Why is that? There is clearly an input that can achieve that, so why is the solver not able to find it?

I notice that when I print out `rip`, I get `<BV64 0x0 .. argv1_39_512[167:160] .. argv1_39_512[175:168] .. argv1_39_512[183:176] .. argv1_39_512[191:184]>`, which shows that there are clearly bits that are influenced by the input.

I'm still learning how to use angr, so my apologies if I have missed something obvious.

**EDIT:** I noticed that when I use the value `0x0000000042424242` in the `rip` constraint, it works. Is there some implicit range for the `rip` that angr uses?

**Comment by Lukas-Dresel** [comment]
In your print out of `rip` you can see that you are overwriting 4 bytes of `rip`. 

However your first constraint was trying to set 5 As instead of 4. This is clearly not possible in this case because the 4 unoverwritten bytes have the value 0. That is why you see the 4 As working, but not the 5 As.

What happens if you set the `num_input_chars` to 68 instead?

**Comment by vivin** [comment]
@Lukas-Dresel 

Ah, yes I see that now. I did try increasing `num_input_chars`, but has no effect -- it's always 4 bytes of `rip` that get overwritten. With `num_input_chars` set to 64, I get `rip` as:

`<BV64 0x0 .. argv1_39_512[167:160] .. argv1_39_512[175:168] .. argv1_39_512[183:176] .. argv1_39_512[191:184]>`

With 68, I get:

`<BV64 0x0 .. argv1_39_544[199:192] .. argv1_39_544[207:200] .. argv1_39_544[215:208] .. argv1_39_544[223:216]>`

But while playing around and trying to constrain the value of `sym_commandline_arg`, I am now able to set `rip` as I like, although I now have some new questions. Here is the new code:

```python
    proj = angr.Project("./csbo", exclude_sim_procedures_list=["strcpy"])

    # Make command-line arg symbolic
    num_input_chars = 64
    sym_commandline_arg = claripy.BVS("argv1", 8 * num_input_chars)

    state = proj.factory.entry_state(
        args=["csbo", sym_commandline_arg],
        add_options={
            angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY,
            angr.options.CONSTRAINT_TRACKING_IN_SOLVER
        }
    )

    # Buffer is 32 bytes. Next 8 bytes after that is for RBP, and 8 bytes after that is RIP.
    # We will constrain the values for the first 46 bytes (we want the upper two bytes of
    # RIP to be 0x0000
    for i in range(0, 46):
        byte = sym_commandline_arg.get_byte(i)
        state.add_constraints(
            claripy.Or(
                claripy.And(byte >= 0x61, byte <= 0x7A),
                claripy.And(byte >= 0x41, byte <= 0x5A),
                claripy.And(byte >= 0x30, byte <= 0x39)
            )
        )

    # Looking for unconstrained paths
    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    # Step execution until we find an unconstrained path
    while sm.active and not sm.unconstrained:
        sm.step()

    # Make a copy of the state
    if not sm.unconstrained:
        raise Exception("Did not find any unconstrained paths!")
    s = sm.unconstrained[0].copy()

    print("rip", s.regs.rip)
    print("rbp", s.regs.rbp)

    rbp_pattern = 0x4142434445464748
    rip_pattern = 0x00007fffffffd9e4
    s.add_constraints(s.regs.rbp == rbp_pattern)
    s.add_constraints(s.regs.rip == rip_pattern)

    assert s.satisfiable()

    # Solve for command-line argument that will let us set RBP and RIP
    solution = s.solver.eval(sym_commandline_arg)
    arg_hex_value = '{0:0{1}x}'.format(solution, num_input_chars * 2)
    arg_hex_bytes = bytes.fromhex(arg_hex_value)
    print("Command-line arg to hijack rip:", arg_hex_bytes)
    print("Hijacked-value to be placed at offset:", arg_hex_bytes.index(rip_pattern.to_bytes(8, 'little')))
```

I get the following output:

```
rip <BV64 Reverse(argv1_39_544[223:160])>
rbp <BV64 Reverse(argv1_39_544[287:224])>
<BV544 argv1_39_544>
Command-line arg to hijack rip: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00HGFEDCBA\xe4\xd9\xff\xff\xff\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Hijacked-value to be placed at offset: 40
```

So here `rip` is clearly overwritten by the command-line argument. But I have some additional questions:

 1. Why did adding constraints on the 6 bytes after the 8 bytes that overwrite `rbp` in the input string, allow angr to see that `rip` can be overwritten? In fact, if I change the range in the loop where I set to constraints from `range(0, 46)` to `range(0, 44)`, only the lower 5 bytes of `rip` can be overwritten (the value I get for `rip` is ` <BV64 0x0 .. argv1_39_544[191:184] .. argv1_39_544[199:192] .. argv1_39_544[207:200] .. argv1_39_544[215:208] .. argv1_39_544[223:216]>`). It's not clear to me how or why setting constraints is affecting this.
 2. How is it able to find a solution at all, based on the constraints I have defined? The bytes from offset 40 to 45 are constrained to alphanumeric values; values like `0xe4`, `0xd9`, `0xff`, and `0x7f` are clearly outside this range. Additionally, in the identified solution, the first 32 bytes are null bytes even though I have set constraints on those bytes to be alphanumeric.

**Comment by vivin** [comment]
Another update. I was able to get this working, but in a rather unexpected way. After going through the API documentation, I discovered that you can supply extra constraints to the `satisfiable` method. So what I did is set the initial constraints, but also add them to a list, and then supply them to the `satisfiable` method. This way the code appears to be working:

```python
    proj = angr.Project("./csbo", exclude_sim_procedures_list=["strcpy"])

    # Make command-line arg symbolic
    num_input_chars = 64
    sym_commandline_arg = claripy.BVS("argv1", 8 * num_input_chars)

    options = {
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS,
        angr.options.CONSTRAINT_TRACKING_IN_SOLVER
    }
    options.update(angr.options.unicorn)
    state = proj.factory.full_init_state(
        args=["csbo", argv1],
        add_options=options,
        remove_options={
            angr.options.LAZY_SOLVES
        }
    )

    # Keeping track of the constraints in this list
    constraints = []

    # Alphanumeric characters for first 32 bytes and 8 bytes for rbp
    for i in range(0, 32 + 8):
        byte = argv1.get_byte(i)
        constraint = claripy.Or(
            claripy.And(byte >= 0x61, byte <= 0x7A),
            claripy.And(byte >= 0x41, byte <= 0x5A),
            claripy.And(byte >= 0x30, byte <= 0x39)
        )
        state.add_constraints(constraint)
        constraints.append(constraint)

    # Nonzero bytes for first 6 bytes of rip
    for i in range(32 + 8, 32 + 8 + 6):
        byte = argv1.get_byte(i)
        state.add_constraints(byte != 0x00)
        constraints.append((byte != 0x00))

    # Looking for unconstrained paths
    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    # Step execution until we find an unconstrained path
    while sm.active and not sm.unconstrained:
        sm.step()

    # Make a copy of the state
    if not sm.unconstrained:
        raise Exception("Did not find any unconstrained paths!")
    s = sm.unconstrained[0].copy()

    print("rip", s.regs.rip)
    print("rbp", s.regs.rbp)

    rbp_pattern = 0x4142434445464748
    rip_pattern = 0x00007fffffffd9e4
    s.add_constraints(s.regs.rbp == rbp_pattern)
    s.add_constraints(s.regs.rip == rip_pattern)

    assert s.satisfiable(extra_constraints=constraints)

    # Solve for command-line argument that will let us set RBP and RIP
    solution = s.solver.eval(argv1, cast_to=bytes)
    print("Command-line arg to hijack rip:", solution)
    print("Hijacked-value to be placed at offset:", solution.index(rip_pattern.to_bytes(8, 'little')))
```

Now I get:

```
rip <BV64 Reverse(argv1_39_512[191:128])>
rbp <BV64 Reverse(argv1_39_512[255:192])>
Command-line arg to hijack rip: b'4EKLCzBzKzZKZzz33333333333z3333333333333\xe4\xd9\xff\xff\xff\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Hijacked-value to be placed at offset: 40
```

Which satisfies the constraints. 

So while it is working as I'd like it to, I would still like to know *why* it is working. So my questions still remain:

 1. Why do I need to set constraints in the input for angr to see that all bytes of `rip` can be overwritten by the input, and not just the lower 4 bytes?
 2. Why are the constraints that I initially set not being taken into account when checking for satisfiability? Why are they only taken into account when I explicitly pass them in as extra constraints?

**Comment by rhelmot** [comment]
Here is the root of the behavior you're seeing: you haven't specified that your input must be free of null bytes, so angr is discovering paths with shorter string lengths. Because of the way the optimized strlen and the stack layout intersect, the first unconstrained path it finds is one that only touches 4 bytes of the saved rip.

You can get a good analysis by adding the following lines:

```python
for byte in sym_commandline_arg.chop(8):
    state.solver.add(byte != 0)
state.libc.buf_symbolic_bytes = 65
```

The last one is because angr has built in limits on the amount of symbolic data it will process in order to maintain tractability, and they need to be raised in order to make it through the printf.

I'm not particularly sure what the deal is with the rabbit hole you went down with setting other constraints.

**Comment by ltfish** [comment]
The state option `SYMBOLIC_MEMORY_NO_SINGLEVALUE_OPTIMIZATIONS` might be what you want to disable.

**Comment by vivin** [comment]
Thank you! @ltfish I am assuming I would put that option under `remove_options`?

**Comment by vivin** [comment]
@rhelmot So with the changes you suggested, it is definitely working and it is able to see that `rip` is being touched. Your explanation as to why it wasn't seeing that earlier also makes sense. However, I still have the problem with the constraints on the input not being honored *unless* I explicitly pass them in via `extra_constraints` when testing for satisfiability.

For example, using the lines you provided in your post, I am able to add the constraint that the input must be free of null bytes. However, the solution that the solver returns includes null bytes for the input. The only way the constraints are honored are if I test for satisfiability by doing `s.satisfiable(extra_constraints=constraints)`, where `constraints` is a list of constraints I've built up (and they're exactly the same as the ones that have been added using `state.solver.add`), and then solve.

Not sure if this is a bug or something.

**Comment by rhelmot** [comment]
can you post another script that shows the weird behavior with my lines added? I'm not sure which pieces of which of your scripts I should cobble together.

**Comment by vivin** [comment]
@rhelmot Sure. 

Here is the script:

```python
#!/usr/bin/env python

def main():
    import angr
    import claripy

    # !!! This is on a binary that has no stack protection and stack is executable !!!
    # Tell angr to go through strcpy
    proj = angr.Project("./csbo", exclude_sim_procedures_list=["strcpy"])

    input_buf_size = 32

    # Make command-line arg symbolic
    input_length = input_buf_size * 2
    argv1 = claripy.BVS("argv1", 8 * input_length)

    options = {
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS,
        angr.options.CONSTRAINT_TRACKING_IN_SOLVER
    }
    options.update(angr.options.unicorn)
    state = proj.factory.full_init_state(
        args=["csbo", argv1],
        add_options=options,
        remove_options={
            angr.options.LAZY_SOLVES,
            angr.options.SYMBOLIC_MEMORY_NO_SINGLEVALUE_OPTIMIZATIONS
        }
    )

    constraints = []

    # I didn't use argv1.chop(8) because I only want the non-null constraints on rbp
    # and lower 6 bytes of rip.
    for i in range(0, input_buf_size + 8 + 6):
        byte = argv1.get_byte(i)
        state.solver.add(byte != 0)
        constraints.append(byte != 0)
    state.libc.buf_symbolic_bytes = input_length + 1

    # Looking for unconstrained paths
    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    # Step execution until we find unconstrained paths
    while sm.active and not sm.unconstrained:
        sm.step()

    print(sm)

    # Make a copy of the state
    if not sm.unconstrained:
        raise Exception("Uh oh! Did not find any unconstrained paths!")
    s = sm.unconstrained[0].copy()

    rbp_pattern = 0x4142434445464748
    rip_pattern = 0x00007fffffffd831
    s.add_constraints(s.regs.rbp == rbp_pattern)
    s.add_constraints(s.regs.rip == rip_pattern)

    # Uncomment this line and comment out "assert s.satisfiable()" to
    # get solution that satisfies constraints
    #assert s.satisfiable(extra_constraints=constraints)
    assert s.satisfiable()

    print("solution rip", hex(s.solver.eval(s.regs.rip)))
    print("solution rbp", hex(s.solver.eval(s.regs.rbp)))
    solution = s.solver.eval(argv1, cast_to=bytes)
    print("Command-line arg to hijack rip:", solution)
    print("Hijacked-value to be placed at offset:", solution.index(rip_pattern.to_bytes(8, 'little')))

if __name__ == '__main__':
    main()
```

When using `s.satisfiable()` by itself, this is the output (as you can see, there are null bytes where there shouldn't be any):

```
<SimulationManager with 40 active, 75 pruned, 1 unconstrained>
solution rip 0x7fffffffd831
solution rbp 0x4142434445464748
Command-line arg to hijack rip: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00HGFEDCBA1\xd8\xff\xff\xff\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Hijacked-value to be placed at offset: 40
```

When using `s.satisfiable(extra_constraints=constraints)`, this is the output:

```
<SimulationManager with 40 active, 75 pruned, 1 unconstrained>
solution rip 0x7fffffffd831
solution rbp 0x4142434445464748
Command-line arg to hijack rip: b'\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01HGFEDCBA1\xd8\xff\xff\xff\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Hijacked-value to be placed at offset: 40
```

I compared constraints (`s.solver.constraints`) before and after `s.satisfiable(extra_constraints=constraints)` and there appears to be no difference. So it's not clear why the constraints on the command-line argument are not taken into account unless I explicitly provide them.

**Comment by rhelmot** [comment]
For me, the assertion fails with either of the lines. Let me try it with the version from pypi...

**Comment by rhelmot** [comment]
I found that the difference between pypi and master for this testcase is caused by https://github.com/angr/claripy/commit/4ed61924880af1ea8fb778047d896ec0156412a6. This fixes a bug which caused inconsistent results to come out of the solver. There should be a new pypi release fairly soon.

**Comment by rhelmot** [comment]
By changing your script to loop until it finds an unconstrained state for which the assignments are satisfiable, it works correctly on master with both extra_constraints and without.

**Comment by vivin** [comment]
@rhelmot thank you!

Regarding the change you described, are you saying that for each unconstrained state that is found, I check to see if the constraints are satisfiable, and if not, continue looping? As opposed to what I am doing right now, which is looping until I find an unconstrained state and then checking to see if constraints are satisfiable on that state.

**Comment by rhelmot** [comment]
Yep, that's what I did. Here's my script:

```python
#!/usr/bin/env python

def main():
    import angr
    import claripy

    # !!! This is on a binary that has no stack protection and stack is executable !!!
    # Tell angr to go through strcpy
    proj = angr.Project("./csbo", exclude_sim_procedures_list=["strcpy"])

    input_buf_size = 32

    # Make command-line arg symbolic
    input_length = input_buf_size * 2
    argv1 = claripy.BVS("argv1", 8 * input_length)

    options = {
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.SYMBOL_FILL_UNCONSTRAINED_REGISTERS,
        angr.options.CONSTRAINT_TRACKING_IN_SOLVER
    }
    options.update(angr.options.unicorn)
    state = proj.factory.full_init_state(
        args=["csbo", argv1],
        add_options=options,
        remove_options={
            angr.options.LAZY_SOLVES,
            angr.options.SYMBOLIC_MEMORY_NO_SINGLEVALUE_OPTIMIZATIONS
        }
    )

    constraints = []

    # I didn't use argv1.chop(8) because I only want the non-null constraints on rbp
    # and lower 6 bytes of rip.
    for i in range(0, input_buf_size + 8 + 6):
        byte = argv1.get_byte(i)
        state.solver.add(byte != 0)
        constraints.append(byte != 0)
    state.libc.buf_symbolic_bytes = input_length + 1

    # Looking for unconstrained paths
    sm = proj.factory.simulation_manager(state, save_unconstrained=True)

    while True:
        # Step execution until we find unconstrained paths
        while sm.active and not sm.unconstrained:
            sm.step()

        print(sm)

        # Make a copy of the state
        if not sm.unconstrained:
            raise Exception("Uh oh! Did not find any unconstrained paths!")
        s = sm.unconstrained.pop().copy()

        rbp_pattern = 0x4142434445464748
        rip_pattern = 0x00007fffffffd831
        s.add_constraints(s.regs.rbp == rbp_pattern)
        s.add_constraints(s.regs.rip == rip_pattern)

        #good = s.satisfiable(extra_constraints=constraints)
        good = s.satisfiable()
        if good:
            break

    print("solution rip", hex(s.solver.eval(s.regs.rip)))
    print("solution rbp", hex(s.solver.eval(s.regs.rbp)))
    solution = s.solver.eval(argv1, cast_to=bytes)
    print("Command-line arg to hijack rip:", solution)
    print("Hijacked-value to be placed at offset:", solution.index(rip_pattern.to_bytes(8, 'little')))

if __name__ == '__main__':
    main()
```
