### ISSUE TITLE
Can angr generated CFG objects be serialized (including callgraph and _function_map and so on )?

### ISSUE THREAD

**Issue by N3vv** [angr/angr#1593]
When I analyze a large binary with angr, it takes me almost a few hours to identify and build CFG in 
the function.I wonder if angr can provide an interface to serialize the CFG and related information after
 analysis.So far, only the serialization of the cfg_model has been implemented, but additional 
information in CFG is needed when actually using angr for some static vulnerability detection.
      
Therefore, I feel that angr should provide an interface to CFG serialization to speed up analysis 
without having to re-identify functions and build CFG each time

**Comment by ltfish** [comment]
> it takes me almost a few hours to identify and build CFG in the function.

That's unexpected. Post the binary and we will improve the speed of CFG on it.

> I feel that angr should provide an interface to CFG serialization to speed up analysis without having to re-identify functions and build CFG each time

It is on our plan! Stay tuned.

**Comment by N3vv** [comment]
Thanks for your reply. And I plan to try to implement it first.

**Comment by zwimer** [comment]
Already implemented.

**Comment by DarkBoulder** [comment]
I've met the same question: I want to dump CFGFast instance to disk and reload it to memory when needed. I found that CFGModelSerializer has the dump and load function, but it does not directly related to CFGFast. Can someone help me to solve this? Thanks!

**Comment by N3vv** [comment]
> I've met the same question: I want to dump CFGFast instance to disk and reload it to memory when needed. I found that CFGModelSerializer has the dump and load function, but it does not directly related to CFGFast. Can someone help me to solve this? Thanks!

Maybe you used it in a wrong way? CFG is essentially a graph structure (if I remember correctly because I haven't seen angr code for a long time :), the icfg recorded by CFGFast is actually stored in the cfg model member. You just need to deserialize the cfg model and use it as the initial parameter of the CFGFast constructor to construct a CFGFast object.

**Comment by DarkBoulder** [comment]
> > I've met the same question: I want to dump CFGFast instance to disk and reload it to memory when needed. I found that CFGModelSerializer has the dump and load function, but it does not directly related to CFGFast. Can someone help me to solve this? Thanks!
> 
> Maybe you used it in a wrong way? CFG is essentially a graph structure (if I remember correctly because I haven't seen angr code for a long time :), the icfg recorded by CFGFast is actually stored in the cfg model member. You just need to deserialize the cfg model and use it as the initial parameter of the CFGFast constructor to construct a CFGFast object.

Thanks for your reply, now I can deserialize the CFGModel instance, but I don't know how to recover other attributes in CFGFast class (there are plenty of attributes, and CFGModel is just the CFGFast.model attribute). Here is my code: 

```python
def analyze_and_save_cfg(project:angr.Project, name):
    cfg = project.analyses.CFGFast(
            show_progressbar=True,
            data_references=True,
            normalize=True, 
        )

    cfg_serialized_data = cfg.model.serialize()
    with open(name, 'wb') as f:
        dill.dump(cfg_serialized_data, f)
    
    return cfg

def load_cfg(project:angr.Project, name):
    with open(name, 'rb') as f:
        cfg_serialized_data = dill.load(f)
    cfg = angr.knowledge_plugins.cfg.CFGModel.parse(
        cfg_serialized_data,
        cfg_manager=None, 
        loader=project.loader
    )
    return cfg
```

Do you know how to construct CFGFast object with CFGModel? Thanks!

**Comment by N3vv** [comment]
> > > I've met the same question: I want to dump CFGFast instance to disk and reload it to memory when needed. I found that CFGModelSerializer has the dump and load function, but it does not directly related to CFGFast. Can someone help me to solve this? Thanks!
> > 
> > 
> > Maybe you used it in a wrong way? CFG is essentially a graph structure (if I remember correctly because I haven't seen angr code for a long time :), the icfg recorded by CFGFast is actually stored in the cfg model member. You just need to deserialize the cfg model and use it as the initial parameter of the CFGFast constructor to construct a CFGFast object.
> 
> Thanks for your reply, now I can deserialize the CFGModel instance, but I don't know how to recover other attributes in CFGFast class (there are plenty of attributes, and CFGModel is just the CFGFast.model attribute). Here is my code:
> 
> def analyze_and_save_cfg(project:angr.Project, name):
>     cfg = project.analyses.CFGFast(
>             show_progressbar=True,
>             data_references=True,
>             normalize=True, 
>         )
> 
>     cfg_serialized_data = cfg.model.serialize()
>     with open(name, 'wb') as f:
>         dill.dump(cfg_serialized_data, f)
>     
>     return cfg
> 
> def load_cfg(project:angr.Project, name):
>     with open(name, 'rb') as f:
>         cfg_serialized_data = dill.load(f)
>     cfg = angr.knowledge_plugins.cfg.CFGModel.parse(
>         cfg_serialized_data,
>         cfg_manager=None, 
>         loader=project.loader
>     )
>     return cfg
> Do you know how to construct CFGFast object with CFGModel? Thanks!

@DarkBoulder I have encountered the problem you mentioned before, but I think the key lies in which attributes you want to use. If angr does not implement the corresponding deserialization definition file (protobuf file) for these attributes, then you can only expand the original code yourself.
