### ISSUE TITLE
Difference between blocks and basic_blocks

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#16]
There are two properties in `Function` class: `blocks` and `basic_blocks`. Printing them both, I see they are same list of start addresses of basic blocks. What's the difference between `Function.blocks` and `Function.basic_blocks`?

**Comment by ltfish** [comment]
Currently `basic_blocks` just return `self.blocks`, so they are the same.

**Comment by ronnychevalier** [comment]
Maybe `blocks` could be made private to make the API more clear?

**Comment by ltfish** [comment]
I believe it used to be `self._blocks`, then changed to `self.blocks` because people thought it is more Pythonic...

Just difficult to work with people of different tastes :-) Let me start a discussion among local angr team on this issue.
