### ISSUE TITLE
Missing Conditional Edge

### ISSUE THREAD

**Issue by F4lc0nCt** [angr/angr#160]
Hi!

I am currently working on the example you used in the _(State of) The Art of War: Offensive Techniques in Binary Analysis_.

```
#include<stdio.h>
#include<stdlib.h>
#include<string.h>


int run(char *data, unsigned int magic){
    char buff[32];

    if(magic==0x31337987){
        memcpy(buff, data, 100);
    }

    if(magic<100 && magic%15==2 && magic%11==6){
        memcpy(buff, data, magic);
    }

    int count=0;
    int i;
    for(i=0;i<100;i++){
        if (data[i] == 'Z') {
            count++;
        }
    }

    if (count >= 8 && count <= 16) {
        memcpy(buff, data, count*20);
    }

    return 0;

}


int main(int argc, char *argv[]){

    char *data = argv[1];
    int magic = atoi(argv[2]);

    return run(data, magic);

```

Therefore I have generated the CFGs (Fast and Accurate) to do my analysis (and to compare them) and I have worked on them. However, today I have realized that there were a problem during the construction of the CFGs, a conditional edge is missing corresponding to the condition `count>=8` in the `if` after the loop.

I have compiled the C code with gcc with no optimization (-O0) to be the closest as possible of the source code. I used the _angr-utils_ library to generate the following picture (The problem is located in the basic block 0x400628 (0x400566) run+0xc2, which is in the deepest branch of the graph)
![cfgfast_magic](https://cloud.githubusercontent.com/assets/20085973/16947689/bcdff816-4db0-11e6-985d-316c4d939183.png)

I have also checked directly in the successors list of the basic block (to be sure that the problem does not come from _angr-utils_) and the edge representing ‘count<8` is not present. I tried to dig into the construction of the CFGs but it was unsuccessful.

Do you know why angr does not represent it? Thank you.

**Comment by axt** [comment]
I don't know the solution to the problem, but maybe you will find this usefull:

If you use the following settings for CFGFast, the nodes probably not needed for your analysis (__libc_csu_init, deregister_tm_clones, etc.) will disappear, making the plotted CFG less messy:
```
 main_sym = proj.loader.main_bin.get_symbol("main")
 cfg = proj.analyses.CFGFast(fail_fast=False,
        start=main_sym.addr,
        end=main_sym.addr+main_sym.size,
        symbols=False,
        function_prologues=False,
        pickle_intermediate_results=False,
        collect_data_references=False,
        resolve_indirect_jumps=True,
        normalize=True)
```

**Comment by F4lc0nCt** [comment]
@axt Thank you for this piece of advice. I was using the start address and initial_state in the case of the CFGAccurate. But using these parameters was leading to have unconstrained  Exit States for the CFGAccurate, thus I stopped using them. When I switched to the CFGFast analysis, I totally forgot this possibility.

**Comment by ltfish** [comment]
> What are the best parameters for building the CFGAccurate without the nodes outside the "main"?

You can specify `call_depth=1` along with `starts=(0x4000a0,)`, where `0x4000a0` is the address of the `main` function.

**Comment by F4lc0nCt** [comment]
Thank you @ltfish. Good luck for the CGC.
