### ISSUE TITLE
How do I convert the symbolic constraints generated by angr into a form involving only program data?

### ISSUE THREAD

**Issue by huang-zhen** [angr/angr#1601]
---

**Comment by ltfish** [comment]
Not sure what you mean by "interpret".

If you have a state, add all constraints to the state by doing `state.add_constraints()` and then check if it is satisfiable by running `state.satisfiable()`. You can also pass extra constraints to `satisfiable()` by doing `state.satisfiable(extra_constraints=...)`.

**Comment by rhelmot** [comment]
The constraints generated by angr have the meaning that if the present variables are assigned in a manner such that every constraint evaluates to true, then execution in a real system will proceed down the same path as the angr state has. This is true of all symbolic execution systems.

**Comment by huang-zhen** [comment]
Thanks for the rapid reply. Maybe my question is not clear. I'm wondering how to convert the constraints generated by angr into a form involving only program data instead of symbolic variables. 

For example, how does the name num_bytes_11_64 in the constraints come from? Can I map it to an expression involving only program data, e.g. local variable -0x1c(%rbp) or global variable 0x400...?

**Comment by rhelmot** [comment]
You should use `state.solver.describe_variables()` instead of parsing the name.

**Comment by huang-zhen** [comment]
I tried to use state.solver.describe_variables() but it always throw an AttributeError exception on var.variables.

My code is as below.
        try:
                for p in state.solver.describe_variables(state.solver.constraints):
                        print '\t', p
        except AttributeError:
                print '\t', 'no variables'
                pass

Did I call describe_variable in the right way?

**Comment by rhelmot** [comment]
http://angr.io/api-doc/angr.html#angr.state_plugins.solver.SimSolver.describe_variables

You provide a single AST, not a list. Also I sincerely hope you're not using python 2.
