### ISSUE TITLE
CB{N}Z problem still exist

### ISSUE THREAD

**Issue by honghai0924** [angr/angr#1611]
---

**Describe the bug.**

It seems that the CB{N}Z problem is still there in the newest angr docker image.
The problem is supposed to be solved by [514](https://github.com/angr/angr/issues/514)

**Environment Information.**

The newest docker image without anything changed.

**To Reproduce.**

> (angr) angr@ 117984e1f32b:~/angr-dev/angr/tests$ python test_lifter.py
> Traceback (most recent call last):
>   File "test_lifter.py", line 21, in <module>
>     test_strict_block_ends_cbz()
>   File "test_lifter.py", line 14, in test_strict_block_ends_cbz
>     assert p.factory.block(1, strict_block_end=True).instructions == 2
> AssertionError

**Additional context.**

I looked around but couldn't find where the problem is. @rhelmot Could you give me some suggestions?

**Comment by rhelmot** [comment]
I am pretty sure that this is a bug in the build process for the angr docker image. When I run the test locally it passes and when I rebuild vex in the docker it passes. I'll look into this but in the meantime the workaround is to `make -f Makefile-gcc clean` in vex and `python setup.py build` in pyvex.

**Comment by honghai0924** [comment]
It works! Thank you.

**Comment by rhelmot** [comment]
Fixed in the latest image
