### ISSUE TITLE
Solver taking increasingly longer to evaluate a single byte of symbolic memory as global constraint count increases

### ISSUE THREAD

**Issue by sherrellbc** [angr/angr#1612]
Angr version 8.19.4.5
-------

I'm not convinced this is a bug, but it certainly is interesting behavior. I was trying to solve a CTF challenge that had approximately 88k basic blocks where each block would check one byte of the input buffer for correctness. The operation in each block is a simple one, where the shown CONST values change in each block: 

```
if(RANDOM_CONST0 == mem[i] ^ RANDOM_CONST1){
    goto next_basic_block;
}else{
    exiting_function()    //no return
}
```

For brevity's sake I'll just cut to the end where I countered lots of memory issues by writing a script that used `SimulationManager.step()`, manually dropped unwanted states, and manually evaluated each byte of the solution as I went. Following the evaluation I would also concretize the solved-for index of the input buffer by setting it to zero (this seemed to save _a lot_ of memory). 

At first I was getting roughly 21 bytes/s as angr symbolically stepped through each basic block. After a few hundred solves that number dwindled to about 10. After about 65k (there are approximately 88k in total) solved bytes I was getting only 0.33 bytes/s. At this point the script had also consumed about 5GB of RAM and taken 19 hours.

I was speaking with someone on the Slack channel and it seems that perhaps the following snippet of code exhibits the same degrading solving time that I was seeing:

```
s = p.factory.blank_state()
buf = claripy.BVS('large-buffer', 100000*8)
for i,b in enumerate(buf.chop()):
    s.add_constraints(b==(i%255))
a_byte = buf.get_byte(99999)
s.add_constraints(a_byte > 100, a_byte < 200)
s.solver.eval(a_byte)
```

On my machine it took 158 seconds to apply the constraints (2.5GB of RAM) and the `eval` step chugged along for a few minutes before being killed due to an out-of-memory condition. This test-case is very similar to the CTF I was working on, with the only difference being that my script was adding constraints with each basic block instead of adding a large number of them upfront. 

* If we are solving for only a single byte value, why does the time-to-solve seem proportionally related to the number of constraints added to other indicies of the buffer?

---------

For other references: 
[The CTF binary](http://s000.tinyupload.com/?file_id=88399206211278650157)

My solution maintains a single `active` state while using `SimulationManager.step()` to move through each basic block. I manually drop the bad states and evaluate a single byte of the solution at each step. There are three sizes of basic blocks in the binary (0x2d, 0x2f, and 0x30). I determine we made it to a "good" RIP by checking that we offset from the last basic block byte one of those values. Otherwise the state represents one that will eventually call the `badboy` function and exit.
```
#!/usr/bin/env python

import logging
import claripy
import angr
import monkeyhex

import time
import signal
import os
import IPython

def go():
    print('* Loading binary ...')
    
    p = angr.Project('ch30.bin')
    options = {
        angr.options.SYMBOL_FILL_UNCONSTRAINED_MEMORY,
        angr.options.ZERO_FILL_UNCONSTRAINED_REGISTERS,
        angr.options.DOWNSIZE_Z3,
        angr.options.SIMPLIFY_MEMORY_READS,
        angr.options.SIMPLIFY_MEMORY_WRITES
    }

    check_func = p.loader.find_symbol('check').rebased_addr
    badboy_func = p.loader.find_symbol('badboy').rebased_addr
    
    buf_addr = 0x100000
    init_state = p.factory.call_state(check_func, buf_addr, add_options=options, remove_options={angr.options.LAZY_SOLVES})
    sm = p.factory.simulation_manager(init_state)

    print('* Executing ...')

    # The first basic-block does not follow the same predicted sizes as the others,
    # so bootstrap the loop by manually finding a path to get us to the second block
    sm.explore(find=0x400b03, avoid=badboy_func)
    sm.drop(stash='avoid') \
            .drop(stash='deadended') \
            .drop(stash='active') \
            .unstash(from_stash='found', to_stash='active')

    with open('base64_encode.txt', 'w+') as f:
        # We start at 1 and manually write the first solved byte because we bootstrapped
        # the loop through the first basicblock
        buffer_len = 1
        f.write('T')
        prev_time = time.time()

        while(1):
            if(len(sm.active) != 1):
                print('Oops! len(sm.active) != 1')
                IPython.embed()

            rip_before = sm.active[0].solver.eval(sm.active[0].regs.rip)
            sm.active[0].simplify()
            sm.active[0].history.trim()
            sm.step()

            # Each basic-block is 0x2d, 0x2f, or 0x30 bytes in length
            # We only want to keep the states that have reached the next basic-block
            # and are not going down the path to call badboy. We can determine this
            # by checking that the RIP of the state is either 0z2d, 0x2f, or 0x30 bytes
            # ahead of the last basic-block reference
            for a in sm.active:
                rip_after = a.solver.eval(a.regs.rip)
                if (rip_after - rip_before) in (0x2d, 0x2f, 0x30):
                    f.write(chr(a.solver.eval(a.memory.load(buf_addr + buffer_len, 1))))
                    f.flush()

                    # Try to keep memory requirements low by setting memory to concrete
                    a.mem[buf_addr + buffer_len].uint8_t = 0

                    # Bookkeeping
                    buffer_len = buffer_len + 1
                    curr_time = time.time()
                    print('\r0x{:08x}/0x{:08x}, {:2.1f} bytes/s'.format(buffer_len, 88000, 1.0/(curr_time - prev_time)), end='')
                    prev_time = curr_time;
                else:
                    sm.active.remove(a)

            # Special case where we found the final basic-block; break
            if( (0x400000 + 0x3ec2b5) == sm.active[0].solver.eval(sm.active[0].regs.rip) ):
                break

if __name__ == '__main__':
#    logging.getLogger('angr.sim_manager').setLevel('DEBUG')
    go()
```

-------

Other questions about this solution:

* Why is so much memory being consumed? How can I prevent it?
    * I tried concretizing the symbolic memory after evaluating and that seemed to help somewhat
    * The only symbolic reference at each basic block is EAX once its reads in from the symbolic buffer. Everything else is concrete
    * Is the state getting too large? Each basic block is decoupled from the previous, save for the index value to evaluate in that block

**Comment by zardus** [comment]
I think I know what's going on here. The composite solver has a design flaw
that gives its runtime a linear multiplier in terms of the total number of
symbolic variables. This is something that's on my to-do list to resolve!

**Comment by sherrellbc** [comment]
Good to hear that the issue is known. Are you aware of any workarounds until a fix is implemented?

**Comment by ltfish** [comment]
I tried to come up with a workaround but I think the best way is to just fix it. I’ll jump in if Yan doesn’t fix it soon.

The memory usage is a different issue. You may enable REUSE_Z3_SOLVER to deal with it.

**Comment by sherrellbc** [comment]
@ltfish I edited my question above just as you posted yours. Is there a way to discard a constraint? 

As for REUSE_Z3_SOLVER, how does one enable it? I see it is a claripy feature. Is it as simple as:

`claripy._backend_z3.reuse_z3_solver = True`

What exactly is this doing? I've only found a reference to angr on twitter saying this can be used to combat high memory usage. Anyway, thanks for the tip.

**Comment by ltfish** [comment]
See https://github.com/angr/claripy/commit/b90cc62bb8a4b0f2a720b4d40945cdeb7a0e4270. It can be enabled via setting a environment variable.

It’s very easy to cause heap memory fragmentation if you create many solvers (as what we do in angr when composite solvers are enabled, which is the default setting). This option allows us to use the same Z3 solver instance again and again instead of creating a new instance for every solver frontend.

**Comment by ltfish** [comment]
@zardus any update?

**Comment by ltfish** [comment]
This problem should be resolved by the merge of https://github.com/angr/claripy/pull/164. Please reopen if it's still an issue for you.
