### ISSUE TITLE
angr is not define 

### ISSUE THREAD

**Issue by N0000000B** [angr/angr#1613]
Hi, i am new to python if this is a stupid question please pardon me, i am trying to load binary in angr with following commands 

from angr import *
import monkeyhex
proj = angr.Project("D:/mheboob/evil/dist/imageprot")

But its giving below error,
WARNING | 2019-06-17 14:50:30,240 | ←[31mangr.analyses.disassembly_utils←[0m | ←
[31mYour version of capstone does not support MIPS instruction groups.←[0m
Traceback (most recent call last):
  File "Angr-test.py", line 5, in <module>
    proj = angr.Project("D:/mheboob/evil/dist/imageprot")
**NameError: name 'angr' is not defined**

please help me

**Comment by ltfish** [comment]
Put `import angr` at the beginning of your file.

**Comment by N0000000B** [comment]
Done !!!

import angr
import monkeyhex
proj = angr.Project("D:\mheboob\evil\dist\imageprot")
print (proj.loader) 

This is working , Kudos for help
