### ISSUE TITLE
Ramblr bug when used with an arbitrary binary

### ISSUE THREAD

**Issue by jjang3** [angr/angr#1625]
---

**Describe the bug.**

I'm getting the "local variable 'label' referenced before assignment after using the ramblr analysis on an arbitrary binary (in my case, the "Hello World")

**Environment Information.**

The environment is Ubuntu 16.04 LTS and everything is set up from the angr-dev repo (using the virtualenv). I am able to work out the other test examples from the test_reassembler.py (such as test_exp_gpp(), etc) and was able to obtain the necessary patched binary along with the assembler .s files

**To Reproduce.**

Hello.c
`#include <stdio.h>`
`int main() { `
`char* string = "Hello World!\n"; `
`printf("%s", string); `
`return 0: }`

compiled with vanilla Clang
`clang -Wall -O0 hello.c`

using the modified ramblr script (derived from the test_reassembler.py) - simple example
`def test_ex_hello():`
`p = angr.Project('Hello'), auto_load_libs=False)`
`r = p.analyses.Reassembler(syntax="intel")`
`assembly = r.assembly(comments=True, symbolized=True)`

r.assembly is where the error occurs, I have attached the image to showcase this.

**Additional context.**

![image (1)](https://user-images.githubusercontent.com/42549923/60102779-5c099d80-972c-11e9-8c1d-844fdd9e96af.png)

Thank you very much!

**Comment by ltfish** [comment]
Can you please upload the binary that you used?

**Comment by jjang3** [comment]
Hello, sure thing, I will submit both the python script + binary file. Please let me know if anything is amiss
[codes.tar.gz](https://github.com/angr/angr/files/3327520/codes.tar.gz)

**Comment by jjang3** [comment]
Hi, sorry for the delay, I was out of the office until just now.
[codes.tar.gz](https://github.com/angr/angr/files/3327542/codes.tar.gz)

Here is the script + binary file, please let me know if there is anything amiss! Thank you

**Comment by ltfish** [comment]
Couldn't reproduce it. Can you try the latest angr on GitHub again?

**Comment by jjang3** [comment]
Hi @ltfish , thank you for your response.

Upon searching a lot of previously posted comments, I stumbled upon this similar question to mine which was issued last year (but from patcherex branch): 
https://github.com/angr/patcherex/issues/12#issuecomment-394908283 

which motivated me to install fresh angr and then install patcherex as well (which required a lot of other dependencies such as povsim, fidget, compilerex, etc..).

Then upon trying out again, it works! I haven't tried it just with just a fresh new installation of angr, but maybe my previous installed angr was funky and had some issues with different dependencies.

I'll upload my pip setup for anyone else if they get stuck in this similar problem, and thank you again @ltfish for your active help!

[requirements.txt](https://github.com/angr/angr/files/3335981/requirements.txt)

**Comment by ltfish** [comment]
Yeah... Patcherex does require a lot of dependencies (most of which are actually our historical debt from the CGC era).

**Comment by ltfish** [comment]
Also the angr on PyPI is still months old. We expect to solve this problem after we finish setting up our CI on Azure Pipelines.
