### ISSUE TITLE
Test_reassembler.py not working with other existing angr test cases (hello_world)

### ISSUE THREAD

**Issue by jjang3** [angr/angr#1630]
---

**Describe the bug.**

Hello, I wanted to test out other binaries in the /home/jay/angr-dev/binaries/tests/x86_64 directory with the test_reassembler.py and facing the issue regarding unsupported symbol.

**Environment Information.**

Ubuntu 16.04 LTS with angr installed using virtualenv (other test_reassembler examples work)

**To Reproduce.**

I have modified the test_reassembler.py to the following:
`p = angr.Project(os.path.join(test_location, "x86_64", "hello_world"), auto_load_libs=False) `
instead of having its original test binary (for example exgpp)

**Additional context.**

Here is the ipython --pdb information:
![image](https://user-images.githubusercontent.com/42549923/60139741-0dd0ba80-977d-11e9-8aa7-856d3f1cf20e.png)

Please let me know if there is any additional information needed. Thank you!

**Comment by ltfish** [comment]
I took a look. This `hello_world` binary is a PIE, so it doesn't really need all the guessing inside Reassembler to be able to reassemble it. This issue happens because we are trying to analyze data inside the ELF header as code for some reason. For now, please try a non-PIE binary instead.

**Comment by jjang3** [comment]
Thank you very much for your help!

**Comment by ltfish** [comment]
Don't close it yet... I'm fixing it.
