### ISSUE TITLE
Unlink simprocedure missing errno behavior

### ISSUE THREAD

**Issue by aheinric** [angr/angr#1633]
---

**Is your feature request related to a problem? Please describe.**
The unlink() function/syscall can set a diverse range of errno values. The simprocedure version of unlink doesn't model any of them, which causes incorrect execution of programs that use this interface.

The problem I'm specifically having is distinguishing failure because an existing file can't be removed, and failure because there is no file to remove.

**Describe the solution you would like.**
Add relevant errno assignments to the simprocedure.  I'm not sure if the simfs function gives enough data to decide which error to return on failure, so its return might need to be augmented, as well.

**Please include a sample of what *should* work if this feature is implemented.**
Currently, the marked branch in the following C code is unreachable:

```
int my_remove() {
   if(remove("/foo/bar")) {
      if(ERRNO == ENOENT) {
         //UNREACHABLE D:
         return 0
      }
      return 1
   }
   return 0
}
```

**Describe alternatives you have considered.**
Forcing the simfs remove() operation to succeed would make my problem go away, but it doesn't solve the general issue that code reading the errno values after a failure won't work properly.

**Additional context.**

**Comment by rhelmot** [comment]
Sounds not super hard. If there's not enough information returned from just the call to remove, the simprocedure can use the simfs apis to probe for what the situation was - there are no race conditions in angr :P

For guidance on how to use errno in simprocedures, look at angr/procedures/posix/dup.py. The use of `state.libc.ret_errno` correctly sets the global errno or the return value depending on if the procedure is being used as a syscall or a library function.

**Comment by embg** [comment]
@rhelmot I will work on this over the next few days and let you know if I have any questions.
