### ISSUE TITLE
Hooking vectors or function pointers

### ISSUE THREAD

**Issue by elouet** [angr/angr#1637]
---

I'm running some bare metal (ARM thumb) code, of which I would like to examine a small part in isolation. Not all the dependencies (memory initialization) are done. Among these there is a function pointer table (which isn't populated in the context I'm trying to execute). I would like to hook those functions with python routines.

What I've done is try to populate the vector array with an arbitrary value (outside the text section), and put a hook at this address. This does not seem to work.

api_base = 0x02023518
printapi = api_base + 0x1c
dummyvector_print = 0x02006101
state.memory.store( printapi, state.solver.BVV(dummyvector_print, 32))

proj.hook( dummyvector_print, lambda s:print("hooked !"))

That however doesn't result in any call to my hook, although the execution path I start at is quickly followed by such call. Is there anything I missed, or further documentation ?

**Comment by ltfish** [comment]
What's the memory endianness? Are you writing the pointer into memory with the correct endianness?

You can dump the history of your final state (`state.history.descriptions.hardcopy`) and see if it ever attempts to execute anything at the address of your hook.

**Comment by elouet** [comment]
I did try indeed to change endianness (little endian is being used), but that didn't suffice. The history dump shows empty, so I suppose I'm not running things the right way. My code is this : 

    sm = proj.factory.simgr(state)
    sm.explore(find=0x20048f9)

**Comment by elouet** [comment]
Managed to get it to work.
