### ISSUE TITLE
Syscall 122 is not found for arch ARMEL

### ISSUE THREAD

**Issue by Yellowbyte** [angr/angr#164]
Found a syscall error in this crackme(http://crackmes.de/users/gtksor/1337_arm/). 

All I did was tried to step through each block like this: 

....[initialization code to create pg as a path_group object]....
while len(pg.active) > 0:
   pg.step()
...[ERROR CODE]...

I have also attached an image of my terminal session that led to the error

![session](https://cloud.githubusercontent.com/assets/4835198/17157384/bc05b9f6-5343-11e6-8323-93287084d0b9.PNG)

**Comment by rhelmot** [comment]
This isn't any error in analysis, just that we don't support this syscall yet. (it looks like on arm, syscall 122 is `uname`).

We're very busy with the CGC right now, so we can't address this for the next few weeks, but it should be relatively straightforward for you to implement your own `uname` syscall SimProcedure and add it to the appropriate lists! Just look at `angr/simos.py` and search for `SimLinux`, then add an appropriate procedure in `simuvex/procedures/syscalls`.

Alternately, if you'd just like to bypass this without recording its affects, you can add the `BYPASS_UNSUPPORTED_SYSCALLS` state option.

**Comment by Yellowbyte** [comment]
Got it. Thanks
