### ISSUE TITLE
Hook duties

### ISSUE THREAD

**Issue by elouet** [angr/angr#1654]
---

I have a hook called, in spite of code that is not present in my simulation, through a function pointer (through `blx r3`). After the hook is called, nothing else seems to happen, so I am assuming my code is not returning. I would like to understand what the duties of a hook may be. Does the hook code have to restore function pointer (i.e. do `pop {pc}` on the SimState object passed as a parameter) ?

**Comment by elouet** [comment]
Not sure hooks can do the trick, I ended up using SimProcedure instead.

**Comment by elouet** [comment]
On thing though : the SimProcedure has a "state" member that is not documented, is this on purpose ? 
Using this is the only way I could find to address memory referenced by arguments in hooked function parameters.

**Comment by rhelmot** [comment]
SimProcedure.state is not supposed to be undocumented; pretty much everything operating on a state will have a `.state` property you can work with.

**Comment by elouet** [comment]
By undocumented I mean it's not listed on http://angr.io/api-doc/angr.html#module-angr.sim_procedure 
Maybe this is inherited ? I am not so familiar with python API docs.

**Comment by rhelmot** [comment]
There were just not documented. It's hard to keep documentation up to date. See the linked commit.
