### ISSUE TITLE
TypeBackend converts expression into a boolean instead of TypedValue and other quirks

### ISSUE THREAD

**Issue by fmagin** [angr/angr#1690]
---

**Describe the bug.**

Various weird unexpected results of `TypeBackend.convert`

Sane, though arguably that could be `SimTypeBool` instead of `TOP` ?:
`bt.convert(untyped_int_a == untyped_int_a)` => `TypedValue(TOP, <Bool True>)`

Unexpected return type `Bool` instead of `TypedValue` 
`bt.convert(typed_int_a == typed_int_a)` => `True`

Unexpected return type `Bool` that also is not what the expression evaluates too when simplified:
`e = typed_int_a == untyped_int_a`
`claripy.simplify(e)` => `<Bool True>`
`bt.convert(e)` => `False`

**Environment Information.**

Probably not an environment issue.

**To Reproduce.**

Setup:
```python
import claripy
import angr
from angr.sim_type import *
bt = angr.type_backend.TypeBackend()
from angr.type_backend import TypedValue, TypeAnnotation

typed_int_a = claripy.BVV(1, 8).annotate(TypeAnnotation(SimTypeInt(label=[])))
typed_int_b = claripy.BVV(2, 8).annotate(TypeAnnotation(SimTypeInt(label=[])))

untyped_int_a = claripy.BVV(1, 8)
untyped_int_b = claripy.BVV(2, 8)

```

**Comment by rhelmot** [comment]
This is arguably a bug in the claripy backend design, or at least an aspect that should be documented more clearly.

What happens is:
- each of the arguments of the `__eq__` ast are converted
- the backend then can't actually handle `__eq__` as an op
- the backend then tries just using the native `__eq__` operation on the `TypedObject` instances. This class doesn't have `__eq__` implemented, so it uses `object.__eq__`, which just checks if they are the same object. The return value is not `NotImplemented`, so the backend assumes the operation worked and returns it.

One workaround would be to implement `__eq__` on `TypedObject` as just returning `NotImplemented`. Another would be to implement processing the `__eq__` ASTs in `TypeBackend`. Another would be to add an option to the backend superclass to eliminate this behavior and just fail the conversion.
