### ISSUE TITLE
Q about support for loading multiple jar files

### ISSUE THREAD

**Issue by smclaugh** [angr/angr#1694]
A few changes are needed to allow for loading multiple jar files. Before giving the details below, my question is: Is this sort of thing a use case that you want to support? If not, then I guess we just have to put all classes into a single jar? Maybe there is some other way you intended this to go?

If it is a use case, I could try to get it working and do a pull request.

OK, details:

If I wanted to do this:

```python
p = angr.Project('x.jar', force_load_libs=['bla.jar'])
```

Then I would need the following to change a few lines [1] just to avoid an exception. Also, if I actually wanted code in `x.jar` to call something in `bla.jar`, We would need to change the use of `state.regs._ip_binary` [2] to some kind of dynamic lookup that scans classes / methods in the other loaded jar files.

[1]
```diff
diff --git a/cle/loader.py b/cle/loader.py
index 06c064e..15870ab 100644
--- a/cle/loader.py
+++ b/cle/loader.py
@@ -679,7 +679,8 @@ class Loader:
         for obj in objects:
             self._register_object(obj)
         for obj in objects:
-            self._map_object(obj)
+            if not isinstance(obj, Jar):
+                self._map_object(obj)
         for obj in objects:
             if isinstance(obj, (MetaELF, PE)) and obj.tls_used:
                 self.tls_object.register_object(obj)
@@ -1051,7 +1052,7 @@ class Loader:
 
 from .errors import CLEError, CLEFileNotFoundError, CLECompatibilityError, CLEOperationError
 from .memory import Clemory
-from .backends import MetaELF, ELF, PE, Blob, ALL_BACKENDS, Backend
+from .backends import MetaELF, ELF, PE, Blob, Jar, ALL_BACKENDS, Backend
 from .backends.tls import PETLSObject, ELFTLSObject, TLSObject
 from .backends.externs import ExternObject, KernelObject
 from .utils import stream_or_path
```
[2] https://github.com/angr/angr/blob/master/angr/engines/soot/engine.py#L80

**Comment by rhelmot** [comment]
@ltfish: you're the author of the jar loader, I need you to look at this. The diff doesn't quite look right to me, but idk how to proceed.

**Comment by smclaugh** [comment]
OK, after looking some more, I think the above is _not_ the way to do it.

Using:
```python
p = angr.Project('x.jar', force_load_libs=['bla.jar'])
```

Results in a different Jython process being started for each jar in `force_load_libs`.

Instead, if we do:

```python
p = angr.Project('x.jar', main_opts={'additional_jars': ['bla.jar']})
```

Then `soot_classpath` gets set appropriately. However, we now have the following issue in `soot_manager.py`:

```python
    def get_classes(self):
        classes = {}
        l.debug("Start converting classes")
        for raw_class in self.raw_classes:
            # TODO with this we only get classes for which we have all the code
            # soot also has classes with lower "resolving levels", but for those we may not have
            # the method list or the code, if we want them we cannot fully translate them
------------if raw_class.isApplicationClass():---------------
                soot_class = SootClass.from_ir(raw_class)
                classes[soot_class.name] = soot_class
        return classes
```

So we still don't get the classes from other jars in the `Lifter`. Given the TODO, I guess the goal of future development is to load library classes on demand via further calls to the Jython process. Is this correct?
