### ISSUE TITLE
call self.project._register_object with only one parameter

### ISSUE THREAD

**Issue by wapen** [angr/angr#1697]
In file angr\procedures\win32\dynamic_loading.py  on line 28:
    def register(self, obj): # can be overridden for instrumentation
        self.project._register_object(obj)
the func should have two parameters:
    def register(self, obj): # can be overridden for instrumentation
        self.project._register_object(obj, self.project.arch)

**Comment by rhelmot** [comment]
Thanks for reporting. It's fixed now.
