### ISSUE TITLE
Extracting external function names for PLT entries

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#17]
This is a feature request. 

I see external function names from PLT entries are named in patterns like `sub_4015d0`. I believe it's possible to extract the names of external functions from PLT entries. It would be great if you can add support for external function name.

**Comment by riyadparvez** [comment]
Sorry for opening plethora of issues and thanks for accepting the feature request.

Is there any API to know whether a function is internal function of the binary or an external function? If there's not, it would be great if you can add an API for that?

Thanks again.

**Comment by ltfish** [comment]
I think we will end up provide two separate lists for internal functions and external functions - but this is a @rhelmot question (since I'm a n00b on ELF). Let's see what his idea is on this.

**Comment by ltfish** [comment]
And on a side note, we enjoy reading issues you submitted. Thank you for being an angr user without getting angry all the time!

**Comment by rhelmot** [comment]
![image](https://cloud.githubusercontent.com/assets/2498805/9543880/4fa5f60e-4d31-11e5-8712-25bd9973c9e2.png)
 :)

I'll push as soon as tests pass.

**Comment by rhelmot** [comment]
The new API is in CLE: `project.loader.find_plt_stub_name(addr)`

**Comment by riyadparvez** [comment]
Thanks for implementing the feature request.
