### ISSUE TITLE
How to make `strstr` as a constraint?

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1701]
---

Hi, I'm looking into the implementation of `angr.SIM_PROCEDURES['libc']['strstr']`, which has an interesting code snippet drawing my attention:
```
        SOME CODE ...
        else:
            needle_length = self.state.solver.eval(needle_strlen.ret_expr)
            needle_str = self.state.memory.load(needle_addr, needle_length)

            chunk_size = None
            if MEMORY_CHUNK_INDIVIDUAL_READS in self.state.options:
                chunk_size = 1

            r, c, i = self.state.memory.find(haystack_addr, needle_str, haystack_strlen.max_null_index, max_symbolic_bytes=self.state.libc.max_symbolic_strstr, default=0, chunk_size=chunk_size)
        self.state.add_constraints(*c)
        return r
```
The `state.memory.find` function returns a default `0` if `needle_str` is not found in `haystack_addr`. 
However, in my case, the `haystack` is a symbolic variable. By default, this symbolic variable will be unconstrained ( or blank), in this way, leading to the `r` always be `<BV32 0x0>` and `c` always be `[ ]`. I try to make the engine to solve the `haystack` for me but failed.
My question can be put in this way, how should we solve a valid `haystack` when I want the `strstr(haystack, needle)!=NULL`?

**Comment by rhelmot** [comment]
`memory.find` is perfectly capable of working with symbolic haystacks.
