### ISSUE TITLE
angr fails to find an external function

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1713]
I'm working on a MIPS program, where `bind` is called for multiple times.
![image](https://user-images.githubusercontent.com/8875073/64485964-a42f5b00-d259-11e9-8bbe-d0c06ee90000.png)
The `bind` function is an external function shown as the below image
![image](https://user-images.githubusercontent.com/8875073/64485972-b4dfd100-d259-11e9-9341-4a5c1c2e7140.png)
However, in angr the block is like below
![image](https://user-images.githubusercontent.com/8875073/64485977-c6c17400-d259-11e9-8424-94d2618e4a93.png)
where `bind` function is treated as a memory location pointed by the pointer `gp`.

The compressed binary is attached.
[mips_test.zip](https://github.com/angr/angr/files/3587438/mips_test.zip)
Thanks.

**Comment by rhelmot** [comment]
angr is right, Ida is just giving you a simplified view of the disassembly.
It is loading the address of the bind function from the GOT. in this binary
gp is supposed to point to 0x5db8d0, and a pointer to bind is stored at
0x5D48E0.
