### ISSUE TITLE
TracerDesyncError: Address mismatch during single-stepping

### ISSUE THREAD

**Issue by Brucedh** [angr/angr#1718]
I've been trying to use tracer on CROMU_00030 (a CGC sample) to dynamically execute the trace generated by the provided pov input. 
The sample can be found here https://github.com/CyberGrandChallenge/samples/tree/master/cqe-challenges/CROMU_00030

This is the code I'm using:
```
import tracer

from angr.exploration_techniques.tracer import TracingMode

target = "/root/cgc/CROMU_00030/bin/CROMU_00030"

accepted_inp = "/root/cgc/CROMU_00030/pov/POV_00000.xml"

t = tracer.Tracer(binary=target, pov_file=accepted_inp, mode=TracingMode.Permissive, copy_states=True)

t.simgr.run()
```

Without `mode=TracingMode.Permissive` it throws the following error:
`angr.exploration_techniques.tracer.TracerDesyncError: Oops! angr did not follow the trace`

While by adding this mode, the error changes to:
`angr.exploration_techniques.tracer.TracerDesyncError: Address mismatch during single-stepping.`

To make tracer.py correctly parse an xml pov file I added the following line to https://github.com/angr/tracer/blob/master/tracer/tracer.py#L80
-> `s.preconstrainer.preconstrain_file(input.writes, s.posix.stdin, True)`
making it preconstrain `input.writes` in case the input is a pov_file, `input` otherwise.

I'm using the updated version of angr-dev.

Do you know how to solve this issue?

I've attached [CROMU30.zip](https://github.com/angr/angr/files/3601382/CROMU30.zip)
which contains the binary, the script and POV_00000.xml.

Thank you in advance!

**Comment by antoniobianchi333** [comment]
@ltfish @zardus

**Comment by rhelmot** [comment]
I can't extract your zip file (which seems to actually be a rar file). Can you upload the files in a different format?

In general, the tracer sucks and this issue will continue to pop up until the end of time.

@antoniobianchi333 congratulations on tagging the two people least likely to help with this issue

**Comment by ltfish** [comment]
> @antoniobianchi333 congratulations on tagging the two people least likely to help with this issue

Uh... now @rhelmot boosted this issue to the top of my pile of todos.

**Comment by Brucedh** [comment]
> In general, the tracer sucks and this issue will continue to pop up until the end of time.

Good to know

This is the real zip file 
[CROMU30.zip](https://github.com/angr/angr/files/3613125/CROMU30.zip)

I added also the trace generated by the pov file. The instruction that throws the error is 0x804a5ee at line 1091 of the trace, which corresponds to line 75 in https://github.com/CyberGrandChallenge/samples/blob/master/cqe-challenges/CROMU_00030/src/service.c#L75

**Comment by rhelmot** [comment]
What on earth version of tracer are you using? `copy_states` is an argument to the Tracer exploration technique, not the (quite frankly kind of deprecated) Tracer class from the tracer repository.

* the tracer repo isn't deprecated but you're only really supposed to use the QemuRunner in it to extract traces, then feed them directly to the tracer exploration technique. this should work regardless though

**Comment by rhelmot** [comment]
Yeah something seems to be wildly different between your configuration and mine. I hacked up your script until it looked good to me:

```python
import angr
import tracer

target = "CROMU_00030"
accepted_inp = "POV_00000.xml"
inp = tracer.TracerPoV(accepted_inp)

p = angr.Project(target)

trace = [int(line, 16) for line in open('accepted_trace.txt')]
t = angr.exploration_techniques.Tracer(trace=trace, copy_states=True)

state = p.factory.full_init_state(mode='tracing', stdin=angr.SimFileStream)
state.preconstrainer.preconstrain_file(inp.writes, state.posix.stdin, True)
simgr = p.factory.simulation_manager(state)

simgr.use_technique(t)
simgr.run()
```

But it's failing within the first five steps because your version of the trace is treating a `loop` instruction looping a single basic block as one instruction, and unicorn is reporting it as the same basic block many times.

**Comment by rhelmot** [comment]
Yeah, my version of the qemu tracer reports the loop as the same block many times. I have no idea what you're doing to generate that file. I'm going to keep going forward but at this point the bug report has devolved into "this binary won't trace".

**Comment by rhelmot** [comment]
okay! I actually see the problem. the thing is that the binary actually runs through the point where it crashes several times before actually crashing, and the tracer is being too cautious about stopping early as to not run through the crash. 2b441b766 fixes this.

**Comment by ltfish** [comment]
Wow eventually...

Good job @rhelmot !

**Comment by Brucedh** [comment]
Great, thank you very much rhelmot!
