### ISSUE TITLE
don't work with TLS (e.g. wyvern example)

### ISSUE THREAD

**Issue by inaz2** [angr/angr#172]
[angr-doc/examples/csaw_wyvern/solve.py](https://github.com/angr/angr-doc/blob/master/examples/csaw_wyvern/solve.py) don't work like below:

```
$ python solve.py
WARNING | 2016-08-03 06:37:07,865 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_ffffffffffff0060_58_64>
(snip)
WARNING | 2016-08-03 06:38:06,675 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_3ffffefffdfffe1_161_64>
Traceback (most recent call last):
  File "solve.py", line 54, in <module>
    print main()
  File "solve.py", line 39, in main
    pg.step(step_func=lambda lpg: lpg if len(lpg.active) == 1 else lpg.prune(), n=100000)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 515, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 306, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 207, in _one_path_step
    successors = a.step(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 317, in step
    self._make_sim_run(throw=throw)
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 343, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 127, in sim_run
    r = sim_proc_class(state, addr=addr, sim_kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/s_procedure.py", line 73, in __init__
    r = self._run(run_func, *args, syscall_name=syscall_name, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/s_procedure.py", line 116, in _run
    r = run_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex/procedures/ld-linux-x86-64___so___2/__tls_get_addr.py", line 13, in run
    return self.state.posix.tls_modules[mod_id] + offset
KeyError: 1
```

`SimStateSystem.posix.tls_modules` looks like uninitialized at current master (c60388c).

Thanks in advance.

**Comment by ltfish** [comment]
Apparently we are not testing it in our CI (see [here](https://github.com/angr/angr-doc/blob/master/test.py#L71)). We will look into possibly restoring this test case, and fix the issue you mentioned above. Thanks for reporting!

**Comment by rhelmot** [comment]
Wyvern has been broken for a while now! I will now attempt to fix it :)

**Comment by rhelmot** [comment]
So, I fixed the actual underlying problem that was causing wyvern to fail on my end (more relocation shenannigans), but not once did I encounter the same error as you posted up there. I think the problem is because loading wyvern attempts to load the shared libraries straight off your operating system, and there's something wrong with the libraries you're running right now.

wyvern runs natively, right? If so, can you post the output of `ldd ./wyvern`, and then upload the file `libs.tar.gz` that gets created by running this script in the same folder as the wyvern binary?

```python
import os
import angr

p = angr.Project('wyvern')
paths = [obj.binary for obj in p.loader.shared_objects.values() if os.path.exists(obj.binary)]
os.system('mkdir lib')
os.system('cp %s lib' % ' '.join(paths))
with open('paths.txt', 'w') as f: f.write('\n'.join(paths) + '\n')
os.system('tar -czf libs.tar.gz lib paths.txt')
os.system('rm -rf lib paths.txt')
```

**Comment by inaz2** [comment]
Sorry, I haven't used master commit (c60388c) and the errors I posted was under angr 4.6.6.29 on pypi.
Now I did Development install with latest commit (2f71892) and wyvern script works well!

I think we don't need to investigate above errors under angr 4.6.6.29.
But if you really need libs.tar.gz on my environment, ask me please.

Thank you for your work :+1:

**Comment by rhelmot** [comment]
:)
