### ISSUE TITLE
Get all instructions in IR, like a list

### ISSUE THREAD

**Issue by wonderluster** [angr/angr#1723]
How to simply disassemble a binary to IR, and get all the instruction opcode in a sequence, like a Python list?
For loops, we can expand it 10 times.

Any example for that? What I see from the example repo are all CTF-related, like solving a specific problem.

**Comment by ltfish** [comment]
`project.analyses.CFG()`.

**Comment by ltfish** [comment]
> For loops, we can expand it 10 times.

You'll have to manually modify the graph and unroll loops. It is not trivial.
