### ISSUE TITLE
Incorrect number of arguments passed to Z3; possibly from angr?

### ISSUE THREAD

**Issue by dnivra** [angr/angr#1728]
---

**Describe the bug.**

angr exits with an error from Z3 when running [CROMU_00006](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CROMU_00006):

```
Z3Exception: Incorrect number of arguments to fp.to_sbv
```

**Environment Information.**

```
angr environment report
=============================
Date: 2019-09-16 14:27:24.003163
Running in virtual environment at $HOME/.virtualenvs/angr-dev-py3
Platform: linux-x86_64
Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
######## angr #########
Python found it in $HOME/angr-dev/angr/angr
Pip version angr 8.19.7.25
Git info:
	Current commit 883f0e8eec377abfcd90e48ccbf594c5d9bafda4 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in $HOME/angr-dev/ailment/ailment
Pip version ailment 8.19.7.25
Git info:
	Current commit b8bacaa65480cffb8056fd44d2fa4627ea1832b3 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in $HOME/angr-dev/cle/cle
Pip version cle 8.19.7.25
Git info:
	Current commit 135a15ed7ec4326d61bd7c2ec7786eb504bf6d6f from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in $HOME/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.7.25
Git info:
	Current commit d67020a7fe15c8171955cf68f6f5f539654989f5 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in $HOME/angr-dev/claripy/claripy
Pip version claripy 8.19.7.25
Git info:
	Current commit d0b90051e3452648daaea5d0719fe3398df11fb7 from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in $HOME/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.7.25
Git info:
	Current commit 0a5daf50cc9de65442bbe7f8fee94d5034024c19 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in $HOME/.virtualenvs/angr-dev-py3/lib/python3.6/site-packages/z3
Pip version not found!
Couldn't find git info
######## unicorn #########
Python found it in $HOME/.virtualenvs/angr-dev-py3/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '$HOME/angr-dev/angr/angr/lib/angr_native.so', handle 35412b0 at 0x7f74c5d60e80>
unicorn: <CDLL '$HOME/.virtualenvs/angr-dev-py3/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2ca59f0 at 0x7f74c4d15f28>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f74c5c825f8>
z3: NOT FOUND
```

**To Reproduce.**

python script

```python
import angr
p = angr.Project("./CROMU_00006", auto_load_libs=False)
state = p.factory.full_init_state()
sm = p.factory.simulation_manager(state)
sm.run()
```

Binary: [CROMU_00006](https://github.com/zardus/cgc-bins/blob/master/all_unpatched/CROMU_00006)

Edit: Adding Z3 version for completeness.

```bash
$ pip freeze | grep z3
z3-solver==4.8.5.0
```

**Comment by rhelmot** [comment]
Your environment report is missing important information about z3 - can you post the result of `pip freeze | grep z3` in your virtualenv?

**Comment by rhelmot** [comment]
ok nvm I reproduced this. this looks like a really scary problem with z3 returning models that don't make any sense:

```
ipdb> p z3_model
[packet_4_stdin_4108_32 = 0,
 packet_1_stdin_4097_32 = 1324360715,
 packet_0_stdin_4096_32 = 16777216,
 packet_3_stdin_4105_32 = 0,
 fp.to_sbv = [(RTZ(), NaN) -> 1, else -> 0]]
```

like what the heck does this even mean

**Comment by rhelmot** [comment]
still no clue what's up. I'm hoping the weird line can just be ignored. Can you try adding `if n == fp.to_sbv: continue` after line 725 in backend_z3.py? If it doesn't crash, can you then check to see if the model it produces will actually drive execution to the given location, i.e. that it's a correct testcase?

**Comment by dnivra** [comment]
I didn't find a variable or parameter `n` in `BackendZ3._satisfiable`. Did you mean something else when you said `n`?

**Comment by rhelmot** [comment]
Whoops, looks like I wasn't on master. I meant line 716.

**Comment by dnivra** [comment]
I think ignoring `fp.to_sbv` is working fine: at least the script above to reproduce the issue does not crash and runs longer(I ran it for 10 mins; with z3 issue, it exits in maybe 2-3 mins). How do I check model generated by z3 is correct? I wasn't doing much else with `CROMU_00006` than just let the `SimulationManager` run as long as it can so unsure how to verify.

**Comment by rhelmot** [comment]
I was hoping you could do like reverse tracing where you dump the basic block trace from angr and then feed the input back into the program under qemu and make sure the trace matches. My worry is that the fp.to_sbv line is z3 telling us it is making some sort of unsound approximation in order to solve this, and the solution isn't actually valid.
