### ISSUE TITLE
Unicorn with loading libs error

### ISSUE THREAD

**Issue by MFaisalZaki** [angr/angr#1741]
Hello Sir,

I'm trying to use unicorn with angr to emulate the code and it crashes when loading the dlls, I'm attaching both the binary, code, and error log.
If you may guide me how to list all possible stashes for this packed binary.

Best regards.
[error-log.log](https://github.com/angr/angr/files/3693065/error-log.log)

[executing-code-in-angr.code.txt](https://github.com/angr/angr/files/3693067/executing-code-in-angr.code.txt)
[AntiD.exe.txt](https://github.com/angr/angr/files/3693068/AntiD.exe.txt)

**Comment by MFaisalZaki** [comment]
It’s a bug in dynamic loading when checking on .dll which is related to python 2

**Comment by fmagin** [comment]
No need to close this, this still needs to be fixed. Didn't realize you already opened an issue for this.

**Comment by MFaisalZaki** [comment]
I have made a quick patch:
in cle/loader.py after line 1002 add 
`if 'decode' in dir(spec):
      spec = spec.decode("utf-8") `
in /win32/dynamic_loading.py append replace ` if '.' not in lib:` with ` if b'.' not in lib:`

**Comment by fmagin** [comment]
The second change is definitely what is needed.
What are you trying to achieve with the first one? Do you have some traceback where this is the fix?

**Comment by MFaisalZaki** [comment]
For some dll files it asked to be str not bytes that’s why I convert them to str

**Comment by rhelmot** [comment]
There should be a different fix from the one you've provided. Can you provide a traceback for the error in cle/loader?

**Comment by MFaisalZaki** [comment]
[CLE-Loader-Traceback.txt](https://github.com/angr/angr/files/3694181/CLE-Loader-Traceback.txt)

**Comment by rhelmot** [comment]
Can you try your tests without any of your patches and instead adding `.decode('utf-8')` to line 9 of dynamic_loading.py, where it extracts the string from memory? Everything wants to be working with strings (I do not know if this is wise or not) and this seems to be the only outlier.

**Comment by MFaisalZaki** [comment]
It worked 😊😉 thanks this is even a better patch compared to mine.

**Comment by rhelmot** [comment]
Pushed the fix in the linked commit. thx for reporting.

btw, it's ma'am, not sir, actually. let's keep gender out of computers though.
