### ISSUE TITLE
show_progress_bar=True blocks pickling of CFG

### ISSUE THREAD

**Issue by raycewest** [angr/angr#1755]
In [7]: pickle.dumps(cfg, -1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/script in <module>
----> 1 pickle.dumps(cfg, -1)

TypeError: cannot serialize '_io.TextIOWrapper' object

In [8]: cfg
Out[8]: <CFGFast Analysis Result at 0x7f07cdfaef98>

Seems to stem from including the progress bar object in the CFG.

**Comment by ltfish** [comment]
Thanks for reporting. This issue will be fixed in PR #1762. However, you should consider pickling (or serializing) `cfg.model` instead of the entire `cfg`.
