### ISSUE TITLE
different path in angr than on cpu?

### ISSUE THREAD

**Issue by felberj** [angr/angr#1763]
---

**Describe the bug.**

When solving the 2019 seccon "follow-me" challenge (files [here](https://github.com/thebabush/WriteUpz/tree/master/2019_SECCON_CTF/follow-me)) I was using the following script:

https://gist.github.com/felberj/d0625256ee7644bde9201ebd51e29715

you need the following files:
- "calc_8e4bdd821b86bebbfa6c5191bfddd40dbb120916"
- "calc.trace_15993a223f9b4a3799251447a8f8198f1ff787ed"

(The pin tracer can be found here: https://github.com/goseungduk/CTF_WriteUp/tree/master/SECCON_2019/rev/follow_me)

As you can see, I am following a single path.
If we take a look at the last few instructions of the path, we have 7 times the instruction at "0x55f6b4d44a1f".

Now if we actually execute the program with the input generated at the end, we get a total of 10 times the execution of "0x55f6b4d44a1f".

I have no clue where the bug can be. I imagine it might be in the following places:

- my script
- the tracer
- angr (or some dependency of it)

Do you think the bug might be somewhere in angr? Because I have no clue how it could be in my script (according to the output, I am following it branch by branch).

**Environment Information.**

angr latest docker file

```
python -m angr.misc.bug_report
angr environment report
=============================
Date: 2019-10-21 19:06:32.000664
Running in virtual environment at /home/angr/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/angr/angr-dev/angr/angr
Pip version angr 8.19.7.25
Git info:
	Current commit 326fdd848fc087f3ca7880bca7781a1fa6024fe5 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/angr/angr-dev/ailment/ailment
Pip version ailment 8.19.7.25
Git info:
	Current commit b8bacaa65480cffb8056fd44d2fa4627ea1832b3 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/angr/angr-dev/cle/cle
Pip version cle 8.19.7.25
Git info:
	Current commit 340fb11d4f6c8f04a5273fe43203dea83e10c22c from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/angr/angr-dev/pyvex/pyvex
Pip version pyvex 8.19.7.25
Git info:
	Current commit d67020a7fe15c8171955cf68f6f5f539654989f5 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/angr/angr-dev/claripy/claripy
Pip version claripy 8.19.7.25
Git info:
	Current commit d0b90051e3452648daaea5d0719fe3398df11fb7 from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/angr/angr-dev/archinfo/archinfo
Pip version archinfo 8.19.7.25
Git info:
	Current commit 9348065ab79b9211d733e530150d602888026b37 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.6.0
Couldn't find git info
######## unicorn #########
Python found it in /home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/angr/angr-dev/angr/angr/lib/angr_native.so', handle 2295ea0 at 0x7f2c60ac4320>
unicorn: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 19f83e0 at 0x7f2c5fa91cf8>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f2c60a018d0>
z3: <CDLL '/home/angr/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 1c70300 at 0x7f2c5c928710>
```

**To Reproduce.**

included in the description above.

**Additional context.**

**Comment by ltfish** [comment]
Before looking into your samples more closely, I have to say that this may not be a bug. It might be the result of differences between angr's environment models and the actual model "on a CPU".

One example is that by default, we do not fully initialize the libc by executing `__libc_start_main`. Instead we use our own function summary (SimProcedure) `__libc_start_main`. If the program logic depends on things that are initialized differently, you'll see different behaviors in angr vs a real execution trace.

**Comment by felberj** [comment]
Thanks for your feedback! I think this is not the case. The whole execution depends on `main` and its arguments. It is a stack based calculator that calculates something based on its input. We get a path that the program follows and need to get a (there are many possible) input to the program.

**Comment by rhelmot** [comment]
So far as I can tell this program invokes undefined behavior deliberately designed to trip up angr based on our non-glibc heap implementation! The vector struct used to push and pop variables is 16 bytes long, but it is only allocated with a `malloc(8)` and then the data region is allocated immediately after that. In glibc, there will be padding for metadata after the allocated structure - unused, since it is never freed, so writing beyond the 8 bytes won't corrupt anything important. However, in angr, there is no gap between sequential allocations so the undefined behavior will cause the vector struct and its data buffer to overlap, leading to unexpected behavior.

In general, you could have detected this just by noticing the warning that uninitialized memory was being accessed. That's why we have that warning on by default!

I patched the binary so it allocates 16 bytes instead and then angr produces an input which executes that instruction the correct number of times.

(incidentally, turning on LAZY_SOLVES also speeds up this script by an enormous amount. this is basically what that option is for!)
