### ISSUE TITLE
Transition to networkx 2.4

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#1775]
https://networkx.github.io/documentation/stable/release/release_2.4.html

notably, strongly_connected_component_subgraphs was removed.

To resolve this issue, we need to fix everything and then make sure we're not using any deprecated features, since it doesn't look like we ever get any warning messages for using these deprecated features at runtime.

**Comment by fmagin** [comment]
The solution for `strongly_connected_component_subgraphs` should be fairly simple, the intended way is [strongly_connected_components](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.strongly_connected_components.html) plus [induced_subgraph](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.induced_subgraph.html).

**Comment by fmagin** [comment]
Started working on this in #1776
