### ISSUE TITLE
SimProcedure for libcrypto

### ISSUE THREAD

**Issue by theoremoon** [angr/angr#1779]
---

Hi all,

Is there a simprocedure for libcrypto?
I want to make speed up analysis for libcrypto functions. I think SimProcedure is good choice for doing this. 

Any way to (semi-automatically) implement SimProcedure for libcrypto or guide to implement SimProcedure by myself?

Thanks

**Comment by twizmwazin** [comment]
Our documentation for writing SimProcedures can be found here: https://docs.angr.io/extending-angr/simprocedures

**Comment by theoremoon** [comment]
hello, @twizmwazin . Thanks for fast reply! I'll read it.
