### ISSUE TITLE
Debloat `angr` data structures using dedicated serialisation classes

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#1789]
#1750 shows a way to debloat an object by extracting its encoding / decoding logic into a serializer class.
In this case, the `knowledge_plugins.functions.Function` moved its `serialize` and `parse_from_cmg` methods.

There are several places along the `angr` codebase where this pattern could be applied:
  - [ ] `angr/knowledge_plugins/cfg/cfg_model.py`
  - [ ] `angr/knowledge_plugins/cfg/cfg_node.py`
  - [ ] `angr/knowledge_plugins/cfg/memory_data.py`
  - [ ] `angr/knowledge_plugins/xrefs/xref_manager.py`
  - [ ] `angr/knowledge_plugins/xrefs/xref.py`
  - [ ] `angr/block.py`

For consistency, it would be nice to have those following the same structure.
In this case, this issue could serve as a reference if no one has the time or need to tackle this in one blow.

**Comment by spencer-burke** [comment]
This sounds interesting. I would like to try doing just one of these to see if it is not too advanced.
