### ISSUE TITLE
Crash CFGFast()

### ISSUE THREAD

**Issue by 2over12** [angr/angr#179]
So I don't know what is going on but I am analysing a simple binary with a glaring issue but when I attempt to do a CFGFast on it, it throws a bunch of warnings then crashes. 

If I compile the binary as a 32bit file it still throws the warning but does not crash and seems to generate the proper cfg.

The crash looks like this:

WARNING | 2016-08-12 21:13:57,209 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_602030_774_64>
WARNING | 2016-08-12 21:13:57,532 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_775_64>
WARNING | 2016-08-12 21:13:57,808 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_776_64>
WARNING | 2016-08-12 21:13:58,151 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:01,160 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:01,811 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_813_64>
WARNING | 2016-08-12 21:14:02,229 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_symbolic_read_reg_48_814_64_815_64_816_64)>
WARNING | 2016-08-12 21:14:02,780 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:03,362 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_128_824_64>
WARNING | 2016-08-12 21:14:03,884 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_830_64>
WARNING | 2016-08-12 21:14:04,730 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_20_855_64>
WARNING | 2016-08-12 21:14:06,708 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_28_880_64>
WARNING | 2016-08-12 21:14:07,531 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:07,979 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:09,118 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_929_64>
WARNING | 2016-08-12 21:14:09,934 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:10,283 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:11,342 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_40_973_64>
WARNING | 2016-08-12 21:14:11,964 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:12,431 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:12,764 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:13,612 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_reg_38_1012_64,reg_10_1013_64_1014_64)>
WARNING | 2016-08-12 21:14:14,105 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_reg_28_1017_64,reg_18_1018_64_1019_64)>
WARNING | 2016-08-12 21:14:14,471 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_18_1020_64>
WARNING | 2016-08-12 21:14:14,743 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_18_1021_64>
WARNING | 2016-08-12 21:14:15,314 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_28_1032_64>
WARNING | 2016-08-12 21:14:16,972 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:17,313 | simuvex.s_run | Too many possible syscalls. Concretizing to 1.
WARNING | 2016-08-12 21:14:18,222 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_reg_10_1059_64_1060_64)>
WARNING | 2016-08-12 21:14:19,505 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 reg_10_1083_64>
WARNING | 2016-08-12 21:14:19,915 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 mem_10_1084_64>
WARNING | 2016-08-12 21:14:20,905 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse(symbolic_read_reg_18_1088_64,reg_38_1087_64_1089_64)>
WARNING | 2016-08-12 21:14:20,962 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 0x2186d9c + SignExt(32, Reverse(unconstrained_read_1093_32))>
WARNING | 2016-08-12 21:14:21,365 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 0x401f2c0 + SignExt(32, Reverse(unconstrained_read_1114_32))>
WARNING | 2016-08-12 21:14:21,508 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 0x11360c4 + SignExt(32, Reverse(unconstrained_read_1118_32))>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg.py", line 56, in __init__
    CFGFast.__init__(self, **kwargs)
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 595, in __init__
    self._analyze()
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/forward_analysis.py", line 195, in _analyze
    self._entry_list_empty()
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 911, in _entry_list_empty
    jump_targets = list(set(self._process_indirect_jumps()))
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 1714, in _process_indirect_jumps
    resolvable, targets = self._resolve_jump_table_fast(entry.addr, entry.jumpkind)
  File "/home//.virtualenvs/angr/local/lib/python2.7/site-packages/angr/analyses/cfg_fast.py", line 1852, in _resolve_jump_table_fast
    load_addr_tmp = load_stmt.data.addr.tmp
AttributeError: 'Const' object has no attribute 'tmp'

The cpp file is attached:
[vuln.cpp.zip](https://github.com/angr/angr/files/416350/vuln.cpp.zip)

IDK I have just gotten into angr so I could be doing something completely wrong...

**Comment by rhelmot** [comment]
Hey, I'm unable to reproduce this. If you're using the version of angr on pip right now, that's a couple of months out of date, since we haven't done a release since the CGC ended! If you want to wait a little bit, I'll try to get release done as soon as I get through the backlog of issues and merge requests that have piled up over the last month, or if you want instant gratification, you could install angr/simuvex/claripy/cle/archinfo/pyvex from github. Those are all up to date!

**Comment by 2over12** [comment]
Just wanted to confirm for anybody having similar issues that installing from the github did fix whatever was going on

**Comment by rhelmot** [comment]
:)
