### ISSUE TITLE
Result of massive experiment: exception angr.errors.AngrCFGError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1798]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a 7zip renamed as a PNG because github doesn't accept 7z.
![CFG_FAIL-angr errors AngrCFGError](https://user-images.githubusercontent.com/3453847/68719489-6ad0df80-0569-11ea-8690-4855db79a97c.png)

Warning: might expand to many gigabytes.

**Comment by ltfish** [comment]
```
### Package: http://cdn-fastly.deb.debian.org/debian/pool/main/g/gst-python1.0/python3-gst-1.0-dbg_1.10.4-1_arm64.deb
### Binary: ./usr/lib/debug/.build-id/04/b04f96e6a8f0b52f20993e57ac048b858b1c86.debug
```

It does not have any executable sections.

**Comment by ltfish** [comment]
OK I think all of those binaries do not have non-empty executable sections. CFG was generating the expected exception.

**Comment by ltfish** [comment]
Thanks for doing the large-scale experiment though! Waiting for more results.
