### ISSUE TITLE
Get size of a native function

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#18]
I want to know the size of a native function in binary; similar to `size` in basic block. Any idea how can I get this?

**Comment by ltfish** [comment]
I don't think we have that interface in `angr`.

One thing you can do, is adding up sizes of all basic blocks inside a function, and subtract the duplicate parts.

I'm running out of cycles for the next three days. Maybe someone else in the team has time to implement this feature - or we are happy to take your contribution :-)

**Comment by rhelmot** [comment]
This is a value exported by the elf symbols, if they are present! If your binary is not stripped, the symbol with your function's name, accessible through CLE, has an attribute `size` or `sh_size` or something that gives you the size of the function, if memory serves.

In the case of stripped binaries, you will need to do something similar to what ltfish described. Somehow using a normalized CFG (what's the interface for that, I forget?) will help you avoid the duplicate parts thing.

**Comment by riyadparvez** [comment]
Thanks! Both of them worked.

Opened a relates issue: https://github.com/angr/cle/issues/6. Please have a look.
