### ISSUE TITLE
Result of massive experiment: exception angr.errors.SimSolverModeError during CFG creation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1801]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is a 7zip renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.
![CFG_FAIL-angr errors SimSolverModeError xz](https://user-images.githubusercontent.com/3453847/68734770-bfd81a00-0598-11ea-8933-534c4a0fd8d9.png)

**Comment by ltfish** [comment]
PR #1837 and #1838 should address all these failures.

**Comment by ltfish** [comment]
Now that two PRs are merged, I will close this issue (until the exact same bug is discovered later again).
