### ISSUE TITLE
Hooking

### ISSUE THREAD

**Issue by ljun85** [angr/angr#182]
In[1]:b = angr.Projcect('/bin/true')
In[2]:def set_rax(state):
                   state.regs.rax = 10
In[3]:b.hook(0x10000, set_rax, length=5)
In[4]:b.is_hooked(0x10000)
Out[4]: True
My issue is how could i trigger **set_rax**. May i exit from the python environment and run **/bin/true**?

**Comment by rhelmot** [comment]
It sounds like you're working your way through the documentation! I recommend continuing reading, maybe jumping to the [symbolic execution](http://docs.angr.io/docs/symbolic.html) section.

angr is, at its core, an emulator. Hooking is instrumentation for that emulator! To run the emulator as a symbolic execution engine, you should create an emulated state, then put that state in a path or a path group, and then start stepping that state forward. All of this is described in the documentation.

**Comment by ljun85** [comment]
Yes,  i'm working my way through the documentation. Thanks for your suggestion.
