### ISSUE TITLE
CFGFast: if condition checks for presence of a member function instead of calling the function

### ISSUE THREAD

**Issue by quoscient** [angr/angr#183]
https://github.com/angr/angr/blob/2f718925e2f6e3cd109075f4d798ca5130092681/angr/analyses/cfg_fast.py#L741

I suppose this should be self._seg_list.has_blocks(): ?

**Comment by ltfish** [comment]
Good catch!

**Comment by ltfish** [comment]
Should be fixed. Thanks for spotting it.

**Comment by axt** [comment]
This commit breaks cfgfast for me. 

I'm running cfgfast like this:
```
	cfgfst = proj.analyses.CFGFast(
	    collect_data_references=True, 
	    resolve_indirect_jumps=True,
	    normalize=True,
	    symbols=False, 
	    function_prologues=False, 
	    start=symb.addr, 
	    end=symb.addr+symb.size)
```

With the commit, the cfg will start with address 'start-1'.

**Comment by ltfish** [comment]
@axt confirmed, working on a fix right now.

**Comment by ltfish** [comment]
Commit d734a7a should fix this issue.

**Comment by axt** [comment]
@ltfish: Confirmed, its working again.

**Comment by ltfish** [comment]
@axt Thanks!
