### ISSUE TITLE
Result of massive experiment: exception ValueError during function decompilation

### ISSUE THREAD

**Issue by zardus** [angr/angr#1831]
From the CFG and decompilation experiment across architectures on Debian. Results attached, which have the packages and binaries and exceptions in question.

Attached is an xz renamed as a PNG because github doesn't accept xz. Warning: might expand to many gigabytes.

Big file: https://github.com/zardus/angr-megatest/blob/master/output/DECOMPILER_FAIL-ValueError.xz

**Comment by zardus** [comment]
@mborgerson , could you tackle this one?

**Comment by mborgerson** [comment]
Grepping through the log, there appear to be multiple distinct issues baked in:

1. `ValueError: Invalid size: Must be a integer power of 2 less than 16`
2. `ValueError: New mapping is overlapping with an existing element.`
3. `ValueError: not enough values to unpack (expected 2, got 1)`
4. `ValueError: The architecture being ppc64, the parameter `rtoc_value` should be provided.`

**Comment by zardus** [comment]
Good catch. Could you open 4 different issues for those?

**Comment by mborgerson** [comment]
I'm going to close this issue now that we have more narrow-scope issues filed.
