### ISSUE TITLE
How threads are handled in angr?

### ISSUE THREAD

**Issue by behnamben** [angr/angr#1836]
Does angr handle threads?

**Comment by rhelmot** [comment]
Short answer: no

Long answer: pthread_create is modeled as creating the target as an extra
successor so symbolic execution will be able to process each thread as a
separate path but they will never be able to interact. If you would like to
make thread support work in a real way let me know and I’ll give you some
ideas for my vision for how it could work, but it’ll be a big project.

**Comment by ltfish** [comment]
angr can be made to model threads and related issues (concurrency, race, etc.) if you put in the effort. All the building blocks are there, but we don't have readily available analysis to find threading-related bugs. Also keep in mind, such analysis tends to be expensive by nature.

A bit more on this topic: I think finding concurrency problems in real-world programs is still a big open research problem. There is some interesting work in this field in the past years. If you are interested, I would recommend you read some papers from Jeff Huang [1] at Texas A&M.

[1] https://parasol.tamu.edu/~jeff/

**Comment by ltfish** [comment]
Oh angr's CFG does "handle" threads, as in, you will see blocks recovered from thread entrances.

**Comment by behnamben** [comment]
I am currently doing annotation based data flow analysis on android binaries with angr . i have tried to handle threads in my own hackish way so i can make my taint analysis more precise. i would be happy to get your ideas about this problem in my case.
thank you.

**Comment by behnamben** [comment]
> Oh angr's CFG does "handle" threads, as in, you will see blocks recovered from thread entrances.

i wonder if my tainted data can be passed between threads, cause angr see them as separate paths.
i use angr cfg to analyse the node registers and find the leaking node in there.

**Comment by ltfish** [comment]
> i wonder if my tainted data can be passed between threads

You'll have to manually model such data tainting/dependencies.

**Comment by behnamben** [comment]
Can you give me some hints Dr.Wang ?
