### ISSUE TITLE
CFG contains incorrect nodes/edges after a non returning function

### ISSUE THREAD

**Issue by fmagin** [angr/angr#1844]
---

**Describe the bug.**

CFGFast generates a node and an edge to that node after a block that calls a function that is known to not return.

**Environment Information.**

This requires https://github.com/fmagin/cle/tree/macho-reloc and https://github.com/fmagin/angr/tree/libobjc to hook the runtime functions and identify `___stack_chk_fail` as non returning

**To Reproduce.**

```python
import angr
import os

# If run from angr-dev folder
# test_location = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'binaries', 'tests')


proj = angr.Project(os.path.join(test_location, 'armhf', 'FileProtection-05.arm64.macho'), load_options={ 'main_opts' : {'gen_relocs': True}})


# normalize doesn't seem to affect this, but is required to make the graph isomorphic to the IDA one in other aspects
cfg = proj.analyses.CFGFast( normalize=True)

# Some function that calls ___stack_chk_fail in one block
f = proj.kb.functions[0x100005528]

# Block that unconditionally calls ___stack_chk_fail
b = f.get_node(0x100005848)


# Confirming that other behaviour works
state = proj.factory.blank_state(addr=0x100005848)

simgr = proj.factory.simgr(state)
# This calls the simproc and terminates the state
simgr.explore()
```

```python
>>>  b.successors()
[<Function sub_1000064b0 (4294993072)>, <BlockNode at 0x10000584c (size 36)>]
>>> b.successors()[0].returning
False
```
I.e. the block has a BlockNode as a successor (that is in fact just the start of the next function, that is also correctly recognized as one as shown by `f = proj.kb.functions[0x10000584c]` ) despite calling a function that is known to not return.

**Additional context.**

There is a chance that messed up something with the relocations and subsequent auto hooking, but given that the stub function `sub_1000064b0` is correctly identified as not returning based on the SimProcedure not returning I would expect this to work.

**Comment by ltfish** [comment]
Fixed in #1854. Thanks for reporting!
