### ISSUE TITLE
Load a complete C project

### ISSUE THREAD

**Issue by xiaoxing521** [angr/angr#1851]
---

We have a complete compiled C project, such as wireshark. We want to load this software with angr and analyze it to extract the backwardslice that reaches a function in a static link library. How to load this project?

**Comment by twizmwazin** [comment]
Hello, thanks for your interest in angr! You can get started with our documentation here: https://docs.angr.io/. If all you are trying to do is understand behaviour in your own program, you may want to consider using a debugger such as GDB, which would allow you to set a breakpoint and see where a particular function is being called.

**Comment by ltfish** [comment]
> We want to load this software with angr and analyze it to extract the backwardslice that reaches a function in a static link library.

Loading the binary with its libraries is as simple as creating the angr project and specifying the path to the binary. You can also force loading certain libraries by specifying `force_load_libs=` when creating the project.

Calculating a backward slice on large projects such as Wireshark is extremely ambitious. Assuming you only care about control-flow dependencies (as in, no data dependencies), caveats are:

- Indirect jumps. Not all indirect jumps can be resolved. This will greatly reduce the accuracy of the CFG.
- Dynamically loaded libraries. Many libraries are loaded during runtime and it's difficult to determine which ones can be loaded statically.
