### ISSUE TITLE
angr got SimZeroDivisionException: divide by zero! when generating CFG

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1856]
---

**Describe the bug.**

I'm running `proj.analyses.CFGFast()` when I meet the error.

[goahead.zip](https://github.com/angr/angr/files/3907023/goahead.zip)

My test binary is uploaded as well.
Thanks.

**Environment Information.**
I'm running angr with version (8, 19, 4, 15). I got this information by `angr.__version__`.
The OS is ubuntu 18.04.

**Comment by ltfish** [comment]
Thanks for reporting the issue. The specific bug that you are referring to should have been fixed some time ago (I did not trigger it on my local machine). However, this binary triggered a few other bugs. Here are the PRs for the bugs triggered.

- https://github.com/angr/cle/pull/216
- https://github.com/angr/angr/pull/1857
- https://github.com/angr/angr/pull/1858
- https://github.com/angr/angr/pull/1859

Thank you again for reporting!
