### ISSUE TITLE
Error when using veritesting with a single avoid address

### ISSUE THREAD

**Issue by sam-b** [angr/angr#186]
While playing with the binary from  #127 I ran into the following error while trying to reproduce the crash with veritesting enabled.

`import angr
p = angr.Project("2", load_options={'auto_load_libs': False})
ex = p.surveyors.Explorer(avoid=0x401A0B,enable_veritesting=True).run()`

Causes the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/code/angr-dev/angr/angr/surveyor.py", line 235, in run
    self.step()
  File "/home/sam/code/angr-dev/angr/angr/surveyor.py", line 213, in step
    self.tick()
  File "/home/sam/code/angr-dev/angr/angr/surveyor.py", line 313, in tick
    boundaries.extend(list(self._avoid))
TypeError: 'int' object is not iterable
`

Looking at the code in Surveyor, I imagine this would be trigger with a single find argument as well:

`if self._enable_veritesting: # and len(p.successors) > 1:
                    # Try to use Veritesting!
                    if hasattr(self, '_find') and hasattr(self, '_avoid'):
                        # pylint: disable=no-member
                        boundaries = [ ]
                        if self._find is not None:
                            boundaries.extend(list(self._find))
                        if self._avoid is not None:
                            boundaries.extend(list(self._avoid))
`
I would submit a pull request but I'm not entirely sure where the best place to fix this is.

**Comment by zardus** [comment]
Sorry it took so long for me to get to this. It's been a bit crazy around here, as always.

Can you try this with path groups? Surveyors are very much obsolete and will hopefully be removed (or just aliased to PathGroup) sometime soon, but path groups should be able to support this functionality.
