### ISSUE TITLE
Can I control how angr resolves branching conditions (like to make it always create a new state without running the solver at all)

### ISSUE THREAD

**Issue by Gandalf098** [angr/angr#1864]
---

Well, first of all, thank you very much for this really awesome tool

now to get to the point

C doesn't allow for mod operator (the '%' operator in C returns the remainder) so usually in simplified C code people do like the following snippet:

```c
x = y % m;
if (x < 0) { x = x + m; }
```

that is a branch in the assembly (although idiv instruction may do it we assume the code compiled to be a branch (for other pragmatic reasons)

now my goal is given the value of x (and of course m) after the block have executed to get the value of y

that is easy in claripy or Z3 (sth like)
```python3
s = claripy.Solver()
x = claripy.BVS();y = claripy.BVS(); m = claripy.BVS()
s.add(x == y % m)
s.add(x == <value of x here>)
s.add(m == <value of m>)
s.eval(y)
```

the problem is angr assumes that to be a branch then creates two active states in the first loop (that operation is part of a loop with other operations)

I merge the two states once they start again (i don't know if it causes angr to hang later or not)

as I said the code actually loops on these operations, at the second iteration angr invokes the solver (hangs a lot inside the solver) when it gets to the if branch
and it detects (for some reason) that it will never enter the condition (idk how I mean I think it depends on the actual values) 

anyway I actually don't want it to try and figure out whether it will enter the loop or not  (as anyway I will merge them later)

the actual code is here 

```c
r[0] = x;
for (i=1; i<31; i++) {
r[i] = (16807LL * r[i-1]) % 2147483647;
if (r[i] < 0) {
r[i] += 2147483647;
  }
}
```
In the above code, I know one element of r[i] and want to get (a model that satisfies) the rest (r is about 1000 element)

Note: I know that there are probably other ways to solve that, but also I want to know if in general, Can I control angr behavior when it comes to determining states based on branching ?!

**Comment by rhelmot** [comment]
I am having trouble parsing out what you need exactly from your narrative but to answer the question in the title: the state option LAZY_SOLVES will make the solver assume that all nontrivial branch conditions can be taken either direction and will not run the solver.

**Comment by iGeek098** [comment]
Sorry 

I know my narrative agh, sorry

Anyway very much thanks I will try it (I thought I read some where that it was enabled by default 

thanks again
