### ISSUE TITLE
Incorrect handling of argument size when using USE_SIMPLIFIED_CCALLS

### ISSUE THREAD

**Issue by axt** [angr/angr#187]
Note: I've rewritten this after digging deeper in the problem!

Here is a simple code which uses only 16 bits from the ESI register (assuming we are on X86) for a comparison:
```
0x0:	cmp	si, 0x7f
0x4:	jg	0x1d
```

If we translate it to VEX, we get the following.
```
IRSB {
   t0:Ity_I16 t1:Ity_I16 t2:Ity_I16 t3:Ity_I32 t4:Ity_I32 t5:Ity_I1 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32

   00 | ------ IMark(0x0, 4, 0) ------
   01 | t2 = GET:I16(esi)
   02 | PUT(cc_op) = 0x00000005
   03 | t3 = 16Uto32(t2)
   04 | PUT(cc_dep1) = t3
   05 | PUT(cc_dep2) = 0x0000007f
   06 | PUT(cc_ndep) = 0x00000000
   07 | PUT(eip) = 0x00000004
   08 | ------ IMark(0x4, 2, 0) ------
   09 | t10 = x86g_calculate_condition(0x0000000e,0x00000005,t3,0x0000007f,0x00000000):Ity_I32
   10 | t5 = 32to1(t10)
   11 | if (t5) { PUT(eip) = 0x6; Ijk_Boring }
   NEXT: PUT(eip) = 0x0000001d; Ijk_Boring
}
```
Later in `simuvex/ccall.py` when `USE_SIMPLIFIED_CCALLS` option is specified, simuvex calls `pc_calculate_condition_simple` (added some comments about what happens in the function).

```python
   # Resolve the OP type, in this case it will be 'G_CC_OP_SUBW'
   op = data_inverted[platform]['OpTypes'][cc_op]
   # Extract the 'SUB' string from OP 
   op = op[8 : -1]
    # Extract the condition
   cond = [...]
   # Function to call, will be pc_actions_SUB_CondLE
   funcname = "pc_actions_%s_%s" % (op, cond)
   if funcname in globals():
       r = globals()[funcname](state, cc_dep1, cc_dep2, cc_ndep)
       return state.se.Concat(state.se.BVV(0, state.arch.bits - 1), r), []
```

The problem with this code is that it doesnt care about the size of the operation, which in this case is WORD (16bits), and it will run the same function for:
 - G_CC_OP_SUBB
 - G_CC_OP_SUBW
 - G_CC_OP_SUBL

Another question: maybe I understand the concepts wrong, but shouldn't be `0x6` the default exit, and `0x1d` the conditional one?

**Comment by axt** [comment]
Found another interesting thing! If I change the code like this: 
```diff
state = proj.factory.blank_state(addr=0x0, add_options={o.USE_SIMPLIFIED_CCALLS})
+print ESI, state.regs.esi
simrun  = proj.factory.sim_run(state)
```
The output will be changed to this:
```
ESI:  <BV32 reg_20_0_32>
Default exit          :  <BV32 0x1d>
Default exit guard    :  <Bool (0#16 .. Reverse(Reverse(reg_20_0_32)[31:16])) > 0x7f>
Conditional exit      :  <BV32 0x6>
Conditional exit guard:  <Bool (0#16 .. Reverse(Reverse(reg_20_0_32)[31:16])) <= 0x7f>
```

**Comment by axt** [comment]
I've digged deeper in this problem, and I think that the VEX output is not equivalent with the machine code above:

- the range of `si` can go from `[0x0000-0xFFFF]`
- the jump is taken in the range `[0x0080-0x7FFF]`, and not taken in `[0x8000-0xFFFF, 0x0000-0x007F]`, since `jg` is signed comparison.
- the VEX code does an unsigned extension to this at `03`: 16Uto32, so the value of `t3` will be in the range from `[0x00000000-0x0000FFFF]`
- now independent if we do signed or unsigned comparison in `x86g_calculate_condition`, the branches will be taken in `[0x00000080-0x0000FFFF]`, and not taken in `[0x00000000-0x0000007F]`

**Comment by axt** [comment]
If you would be okay with a patch like this (currently done only for the pc_actions_SUB_CondLE function in this example), I can send a pull-request.

Also please note that I've changed `<=` to `state.se.SLE` to get the correct conditions.

```diff
@@ -692,8 +703,8 @@ def pc_actions_SUB_CondNBE(state, arg_l, arg_r, cc_ndep):
 def pc_actions_SUB_CondL(state, arg_l, arg_r, cc_ndep):
     return _cond_flag(state, arg_l < arg_r)
 
-def pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep):
-    return _cond_flag(state, arg_l <= arg_r)
+def pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep, size):
+    return _cond_flag(state, state.se.SLE(state.se.Extract(size-1,0,arg_l), state.se.Extract(size-1,0,arg_r)))
 
 def pc_actions_SUB_CondNLE(state, arg_l, arg_r, cc_ndep):
     return _cond_flag(state, arg_l > arg_r)
@@ -730,8 +741,10 @@ def pc_calculate_condition_simple(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep,
     # Extract the operation
     cc_op = flag_concretize(state, cc_op)
     op = data_inverted[platform]['OpTypes'][cc_op]
+    size = data[platform]['OpSizes'][op[-1]]
     op = op[8 : -1]
 
+    
     # Extract the condition
     cond = None
     # TODO: Convert it to a table-lookup later
@@ -742,7 +755,7 @@ def pc_calculate_condition_simple(state, cond, cc_op, cc_dep1, cc_dep2, cc_ndep,
 
     funcname = "pc_actions_%s_%s" % (op, cond)
     if funcname in globals():
-        r = globals()[funcname](state, cc_dep1, cc_dep2, cc_ndep)
+        r = globals()[funcname](state, cc_dep1, cc_dep2, cc_ndep, size)
         return state.se.Concat(state.se.BVV(0, state.arch.bits - 1), r), []
```

**Comment by ltfish** [comment]
I'll review this issue as well as your patch tomorrow!

**Comment by ltfish** [comment]
> maybe I understand the concepts wrong, but shouldn't be `0x6` the default exit, and `0x1d` the conditional one?

VEX doesn't guarantee that the conditional exit in assembly always corresponds to the conditional exit in VEX IRSB.

**Comment by ltfish** [comment]
Regarding your patch: the bug you noticed is real, and I think your patch makes sense. Please give us a PR :-)

**Comment by axt** [comment]
Okay. I will send a PR in a few days.

**Comment by axt** [comment]
How far can I go with the PR? :)

Currently we have this kind of code:
```
def pc_actions_SUB_CondZ(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, arg_l == arg_r)

def pc_actions_SUB_CondBE(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, state.se.ULE(arg_l, arg_r))

def pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, state.se.SLE(arg_l, arg_r))
```
and only some of the functions are implemented.

If this change is valid (don't know the implications on VSA):
```
def pc_actions_SUB_CondZ(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, arg_l - arg_r == 0)

def pc_actions_SUB_CondBE(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, state.se.ULE(arg_l - arg_r, 0))

def pc_actions_SUB_CondLE(state, arg_l, arg_r, cc_ndep):
    return _cond_flag(state, state.se.SLE(arg_l - arg_r, 0))
```

Then we could create functions like:
```
pc_actions_op_SUB(arg_l, arg_r, cc_ndep)
    return arg_l + arg_r
pc_actions_op_ADD(arg_l, arg_r, cc_ndep)
    return arg_l + arg_r
```
and 
```
pc_actions_cond_LE(state, arg):
    return _cond_flag(state, state.se.SLE(arg, 0)) 
pc_actions_cond_Z(state, arg):
    return _cond_flag(state, arg == 0) 
```

so instead of A x B functions, we only need to implement A + B, where A is the number of ops, and B the number of conditions.

What do you think? Do you see any problems with this approach?

**Comment by ltfish** [comment]
It looks OK to me, and claripy backends should automatically handle different sizes.

However, now I don't understand why we cared about sizes in the normal ccalls (unsimplified ones). @zardus any explanation?

**Comment by axt** [comment]
When these functions are called ąs I see `cc_dep1` and `cc_dep2` is always the default arch size since it is extended to that size in VEX, and only the operation indicates how many bits to use from the variable. For example:
```
   01 | t2 = GET:I16(esi)
   02 | PUT(cc_op) = 0x00000005
   03 | t3 = 16Uto32(t2)
   04 | PUT(cc_dep1) = t3
   05 | PUT(cc_dep2) = 0x0000007f
   06 | PUT(cc_ndep) = 0x00000000
   07 | PUT(eip) = 0x00000004
```

So in the above examples, I would do something like this before calling the functions:
```
    cc_dep1_nbits = cc_dep1[nbits-1:0]
    cc_dep2_nbits = cc_dep2[nbits-1:0]

    funcname = "pc_actions_%s_%s" % (op, cond)
    if funcname in globals():
        r = globals()[funcname](state, cc_dep1_nbits, cc_dep2_nbits, cc_ndep)
```

**IMO, the only question is that are these expressions equivalent for claripy backends (also in terms of complexity to solve them)**:
```
state.se.ULE(arg_l, arg_r)
vs 
state.se.ULE(arg_l - arg_r, 0)
```

Because if they are, then we could "separate" the operations from the conditions, and reduce the number of functions needed to handle the cases from A x B (pc_actions_OP_COND()) to A + B (pc_actions_COND(pc_actions_OP()).

**Comment by ltfish** [comment]
> state.se.ULE(arg_l, arg_r)
> vs 
> state.se.ULE(arg_l - arg_r, 0)

Static analysis (like VSA) prefers the former to the later, and that was the point of having "simplified" ccall handlers initially.

**Comment by axt** [comment]
I thought so, thats why I asked!  

Btw, can you tell me, what is the VSA-friendly form of this expression? (note the `-` is replaced to `+`).
```
state.se.ULE(arg_l + arg_r, 0)
```

**Comment by ltfish** [comment]
It's fine as it is. The `Balancer` (see claripy) handles it.

**Comment by axt** [comment]
But this also means that these two forms are equivalently complex to solve? Or is it true only for the addition? 
```
state.se.ULE(arg_l, arg_r)
state.se.ULE(arg_l - arg_r, 0)
```

**Comment by ltfish** [comment]
`ULE(arg_l + arg_r, 0)` will be converted to `ULE(arg_l, -arg_r)` or `ULE(arg_r, -arg_l)`, depending on where the "core" (the unknown variable) is. Likewise, `ULE(arg_l - arg_r, 0)` will be converted to `ULE(arg_l, arg_r)` or `UGE(arg_r, arg_l)`. `ULE(arg_l, arg_r)` is just more natural, and in fact VEX IR generates a lot of such expressions. Without `Balancer`, only `ULE(arg_l, arg_r)` works. With `Balancer`, `ULE(arg_l - arg_r, 0)` also works, but it requires an extra conversion.

With that said, I think it's fine to have `ULE(arg_l - arg_r, 0)` generated from ccall handlers instead of `ULE(arg_l, argr)`. The only concern of mine is, that you might encounter more bugs in `Balancer`, which will be very annoying to debug :-)

**Comment by axt** [comment]
I made it with the support of both schemes:
- generic cond(op(..))  evaluation for the cases when we can't be more clever than having 0 on the right side of the expression
-  specialized op_cond() evaluation for the cases when we can be more clever

**Comment by ltfish** [comment]
The PR is merged in. Thank you very much :-)
