### ISSUE TITLE
Werid problem about regs initialization of SimState

### ISSUE THREAD

**Issue by 4B5F5F4B** [angr/angr#1879]
---

**Describe the bug.**

Hello all,

Please consider the following simpe thumb instructions
```
;block1
.text:00004F4A  MOV       R1, #0x2AF5F875
.text:00004F52  CMP       R0, R1
.text:00004F54 	BEQ.W     loc_52F8


;block2
.text:00004F60  CMP       R0, R1
.text:00004F62  BNE.W     loc_5330
```

Firstly, I symbolic execute block1(0x404FAB) like this

```
simmgr1   = project.factory.simulation_manager(project.factory.blank_state(addr=0x404F4B))
simmgr1.step()
```
and now simmgr1.active[0].regs.r1 is  <BV32 0x2af5f875>.

Then I create a blank state for block2(0x404F61), and initialize its regs using  simmgr1.active[0].regs
```
blank_state = project.factory.blank_state(addr=0x404F61)
blank_state.regs = simmgr1.active[0].regs
blank_state.ip = 0x404F61
simmgr2   = project.factory.simulation_manager(blank_state)
```

before I call simmgr2.step() to symbolic execute block2, I can se simmgr2.active[0].regs.r1 is  <BV32 0x2af5f875>, but after simmgr2.step retusns, simmgr2.active[0].regs.r1 turns to <BV32 reg_r1_2_32{UNINITIALIZED}>.

But If I initialize blank_state.regs.r1 expicitly in this way
```
blank_state = project.factory.blank_state(addr=0x404F61)
blank_state.regs.r1 = simmgr1.active[0].regs.r1
blank_state.ip = 0x404F61
simmgr2   = project.factory.simulation_manager(blank_state)
```

Then I call simmgr2.step(),  simmgr2.active[0].regs.r1 would be <BV32 0x2af5f875> all the time.

I want to know is this a bug or a special feature?

**Environment Information.**

Python3 + Angr 8.19.10.30

**Comment by rhelmot** [comment]
Hi! So the basic problem here is this line: `blank_state.regs = simmgr1.active[0].regs`

1) `regs` is not actually the plugin which contains the register data - that would be `registers`. `regs` is just a light wrapper allowing you to do named accesses to registers as attributes.
2) That's not a correct way to copy registers from one state to another. You want `new_state.register_plugin('registers', old_state.registers.copy())`

**Comment by 4B5F5F4B** [comment]
> Hi! So the basic problem here is this line: `blank_state.regs = simmgr1.active[0].regs`
> 
> 1. `regs` is not actually the plugin which contains the register data - that would be `registers`. `regs` is just a light wrapper allowing you to do named accesses to registers as attributes.
> 2. That's not a correct way to copy registers from one state to another. You want `new_state.register_plugin('registers', old_state.registers.copy({}))`

Thank you for your reply, I will close this issue.
