### ISSUE TITLE
Controlling Execution

### ISSUE THREAD

**Issue by ljun85** [angr/angr#188]
As said in [Controlling Execution](http://docs.angr.io/docs/paths.html):
In[1]:branched_left = p.successors[0]
In[2]:branched_right = p.successors[1]
In[3]:assert branched_left.addr != branched_right.addr
In[4]:after_branched_left = branched_left.step()[0]
In[5]:after_branched_right = branched_right.step()[0]

But:
In[6]:merged = branched_left.merge(branched_right)
In[7]:assert merged.addr == branched_left.addr and merged.addr == branched_right.addr

My issue is why does'nt **In[7]** confilict with **In[3]** ?

**Comment by rhelmot** [comment]
This looks like a bug in the docs! Give me one sec to fix it.

**Comment by rhelmot** [comment]
Fixed in https://github.com/angr/angr-doc/commit/97aeea5e508949137872463db3fadf8656816fd1

**Comment by ljun85** [comment]
Thanks very much.
