### ISSUE TITLE
Backtrack how a temporary variable is initialized in VEX

### ISSUE THREAD

**Issue by 4B5F5F4B** [angr/angr#1886]
---

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I want to backtrack how a temporay variable is initialized in VEX. Please consider following IR statements
```
   00 | ------ IMark(0x405f04, 2, 1) ------
   01 | t2 = GET:I32(r1)                               ;t2 is read from register R1
   02 | PUT(r0) = t2
   03 | ------ IMark(0x405f06, 2, 1) ------
   04 | t6 = GET:I32(r3)
   05 | PUT(cc_op) = 0x00000002
   06 | PUT(cc_dep1) = t2
   07 | PUT(cc_dep2) = t6
   08 | PUT(cc_ndep) = 0x00000000
   09 | PUT(pc) = 0x00405f09
   10 | ------ IMark(0x405f08, 2, 1) ------
   11 | PUT(itstate) = 0x00000000
   12 | t33 = CmpLE32S(t2,t6)                   	;t2 is used for comparing with t6
   13 | t32 = 1Uto32(t33)
   14 | t34 = 32to1(t32)
   15 | if (t34) { PUT(pc) = 0x405f93; Ijk_Boring }
   NEXT: PUT(pc) = 0x00405f0b; Ijk_Boring
```

When deal with stmt CmpLE32(t2, t6)， I want to know how t2 initialized

**Describe the solution you would like.**

I hope pyvex can add some APIs to track back all assign statemtns to a specific temporary variable

**Please include a sample of what *should* work if this feature is implemented.**

**Describe alternatives you have considered.**

**Additional context.**

**Comment by rhelmot** [comment]
The SSA form makes this easy enough that it's not worth having as a specific API.

```
def get_initializer(block, tmp):
  for stmt in block.statements:
    if stmt.tag == 'Ist_WrTmp' and stmt.tmp == tmp:
      return stmt
```
