### ISSUE TITLE
control_flow_sice

### ISSUE THREAD

**Issue by ljun85** [angr/angr#189]
As said in [Backward Slicing](http://docs.angr.io/docs/analyses/backward_slice.html):
In[1]:bs = b.analyses.BackwardSlice(cfg, control_flow_sice=True)
Out[1]:
File "<stdin>", line 1, in <module>
  File "/root/.virtualenvs/angr_env/local/lib/python2.7/site-packages/angr/analysis.py", line 99, in make_analysis
    oself.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'control_flow_sice'

Is this a bug?

**Comment by schieb** [comment]
It's a typo in the docs. Should read:
`>>> bs = b.analyses.BackwardSlice(cfg, control_flow_slice=True)`

See [backward_slice.py#L26](https://github.com/angr/angr/blob/master/angr/analyses/backward_slice.py#L26)

**Comment by ljun85** [comment]
Thank you.
