### ISSUE TITLE
The symbolic engine ignores a large code block

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1891]
Hi, I was analyzing a function in a MIPS binary. However, I found the symbolic engine just jumps over a large code block without any constraints generated (the code block is in the `cfg` and can be found in `pred_node.successors`.

![image](https://user-images.githubusercontent.com/8875073/71474540-f0a5a300-2816-11ea-8a46-de9344f10546.png)
The function I'm analyzing is called `check_remote_ip` and the block I'm refering to is 0x404e78.
[my_cgi.zip](https://github.com/angr/angr/files/4002392/my_cgi.zip)
Thanks in advance.

appendix:
My test script is like below:
```
# generate cfg first

start_state = proj.factory.blank_state(addr=0x404e38)
start_state.regs.gp = 0x4641b0
start_state.regs.t9 = 0x404e38
sm = proj.factory.simulation_manager(start_state)
sm.step(); step.stashes
```

**Comment by ltfish** [comment]
Without debugging your binary - I think what happens is that the `bne` at 0x404e70 leads the jump to take one branch (0x404f48), not the one that you want. What are the values of `v1` and `v0` at 0x404e70?
