### ISSUE TITLE
Bug-BinDiff

### ISSUE THREAD

**Issue by ljun85** [angr/angr#190]
I run angr's BinDiff on the obj file **tests/x86_64/bindiff_a** and **tests/x86_64/bindiff_b**. When i run command objdump on obj file **bindiff_a** and **bindiff_b**, i see the function **print_bad** are identical, and the function **print_good** belong to obj file  **bindiff_b** is unmatched. But this confilicts with result from the angr's BinDiff.

**Comment by ljun85** [comment]
For more, what is the goal of angr's BinDiff ? My mean is , what issue does the angr's BinDiff  can deal with?

**Comment by zardus** [comment]
This is a @salls question. We did just make some updates to bindiff that we need to push to github; just haven't had a chance to yet. It might resolve your issue!

**Comment by ljun85** [comment]
I'm looking forward the updates.

**Comment by salls** [comment]
This commit https://github.com/angr/angr/commit/11137c12087aea9d35aad2cc301c1710e194c77e should make it so you get the expected result. (This commit takes into account symbol names during the matching). 

The goal of angr's bindiff is to do a graph based comparison on the CFG to identify similarities and differences in executables. We've used it to analyze patches and it's also used in a current research project of ours.
