### ISSUE TITLE
Importing ABC from collections module is deprecated

### ISSUE THREAD

**Issue by tirkarthi** [angr/angr#1903]
Importing ABC from collections module was deprecated since Python 3.4 and removed in Python 3.9. Instances of this as below. I would like to raise a PR for this.

```
angr/knowledge_plugins/functions/function_manager.py
61:class FunctionManager(KnowledgeBasePlugin, collections.Mapping):
angr/knowledge_plugins/functions/function_manager.py
61:class FunctionManager(KnowledgeBasePlugin, collections.Mapping):
angr/sim_variable.py
232:class SimVariableSet(collections.MutableSet):
```

**Comment by rhelmot** [comment]
Yeah, this is something that should be fixed. You can submit that PR!

**Comment by ArionMiles** [comment]
I'd like to take this! @tirkarthi are these the only instances of collections import you were able to find in the codebase? If there are more I'd happily fix those as well 😄

**Comment by tirkarthi** [comment]
One more instance. Using grep to analyze the call sites helps. Thanks.

```
angr/vaults.py
45:class Vault(collections.MutableMapping):
```

**Comment by ArionMiles** [comment]
Since this project is py3 only, I shouldn't have to take care of py2 edge cases, should be simple enough, right?

**Comment by ArionMiles** [comment]
I've opened a PR. I've tried fixing as many instances I was able to find. Do take a look and let me know if I missed any 😄
