### ISSUE TITLE
X86 instruction loop does not end a block with size specified

### ISSUE THREAD

**Issue by ltfish** [angr/angr#1905]
**Describe the bug.**

When `size` is explicitly specified to `Block()`, the X86 instruction `loop` does not put an end to the current block, which messes the CFG. See 0x4010d3 in the following picture.

![image](https://user-images.githubusercontent.com/5071575/71873602-d30cef00-30dc-11ea-9b39-0cfa11c870a9.png)

**Environment Information.**

Latest angr and angr management.

**To Reproduce.**

Decode the basic block 0x4010a2 in binary angr-doc/examples/flareon2015_2/very_success.

**Additional context.**

The flag `strict_block_end` is lost if `size` is explicitly specified.

**Comment by rhelmot** [comment]
we did this already. you need `strict_block_end=True`

**Comment by ltfish** [comment]
This is a different issue. PR incoming.

**Comment by ltfish** [comment]
Ref: https://github.com/angr/angr/pull/1906
