### ISSUE TITLE
Asking the better way of assisting SE with static analysis

### ISSUE THREAD

**Issue by DongShuaike** [angr/angr#1916]
Hi, I'm recently thinking about how to facilitate the SE in angr with static analysis. 
Since the binary I'm analyzing has a lot of branches, just `sm.explore()` from the entry point until it reaches my targets is really time-consuming.
I got the idea from control dependency graph and finally obtain a set of potential control flow paths (consisting of multiple connected CFG blocks)(I have some self-defined rules so only a few branches are needed by me). My initial idea is to guide the simulation manager to preferrly/priorily take these selected paths so that I can collect all constraints in the end.

When it comes to the implementation, I got two different plans:
<1> Using `SimState.Inspect.b`, everytime a simulation manager reaches a branch, my breakpoint will invoke a callback, in which I can modify the `SimState.regs.pc` so that the control flow can follow my way.
<2> Implement a new `ExplorationTechnique`, in this way, the original simulation manager behavior will not be violated, I can select those states following the right branches and put them in a new stash, maybe called 'obedient'.

I'm preferring the first approach, since it is direct and easy to understand. Directly modifying the pc register can make sure all things happen as I wish. Could someone give me some hints on this? Thank you!

**Comment by rhelmot** [comment]
2 is the better option. if you modify the pc directly, you will be creating states for which you will not be able to generate testcases.
