### ISSUE TITLE
Some unsupported syscalls are bypassed without BYPASS_UNSUPPORTED_SYSCALLS

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#192]
the logic in `simos.py` causes unknown syscalls to be automatically served with the `stub` procedure when the region of supported syscalls is non-continuous. This is bad; the correct behavior is that these syscalls should not be served at all unless BYPASS_UNSUPPORTED_SYSCALLS is enabled.

Assigning fish because I think this is your code.

**Comment by ltfish** [comment]
Should be resolved. I'm closing this issue now.
