### ISSUE TITLE
CFG: Basic Block size

### ISSUE THREAD

**Issue by xiaohuajiao2nd** [angr/angr#193]
For function CFG, I have one question.

![1](https://cloud.githubusercontent.com/assets/7940452/17830758/b568d4ac-6707-11e6-823a-455169303c2c.png)

Suppose these 2 basic blocks in picture to be `A` (0x8048470, size 39) and `B` (0x8048497, size 23).  The CFGFast results have a basic block include both A and B. But no basic block only contains `A`. 

```
<BlockNode at 0x80485d1 (size 19)>
<BlockNode at 0x8048568 (size 34)>
<BlockNode at 0x80485ee (size 5)>
<BlockNode at 0x80484c4 (size 5)>
<BlockNode at 0x80484df (size 17)>
<BlockNode at 0x804851c (size 5)>
<BlockNode at 0x80485e4 (size 10)>
<BlockNode at 0x8048521 (size 17)>
<BlockNode at 0x80484da (size 5)>
<BlockNode at 0x8048563 (size 5)>
<BlockNode at 0x80484f0 (size 5)>
<BlockNode at 0x80484ae (size 5)>
<BlockNode at 0x8048537 (size 17)>
<BlockNode at 0x8048470 (size 62)>
<BlockNode at 0x8048532 (size 5)>
<BlockNode at 0x804858a (size 19)>
<BlockNode at 0x804854d (size 17)>
<BlockNode at 0x80485be (size 19)>
<BlockNode at 0x80484f5 (size 17)>
<BlockNode at 0x8048548 (size 5)>
<BlockNode at 0x8048506 (size 5)>
<BlockNode at 0x804850b (size 17)>
<BlockNode at 0x804859d (size 33)>
<BlockNode at 0x80484b3 (size 17)>
<BlockNode at 0x8048497 (size 23)>
<BlockNode at 0x80484c9 (size 17)>
<BlockNode at 0x804855e (size 5)>
```

According to the [Definition](https://en.wikipedia.org/wiki/Basic_block) of Basic block,
> One entry point, meaning no code within it is the destination of a jump instruction anywhere in the program.

The result is inconsistent with the definition. 

Then I failed to get my expected successors of A. :(

Is the Basic Block in Angr different with textbook definition?

Here is my test binary.
[a.zip](https://github.com/angr/angr/files/428242/a.zip)

**Comment by rhelmot** [comment]
There is no good way to understand that a basic block should end earlier than the earliest jump or branch before a CFG is completed and normalized. To construct a CFG with basic blocks that conform to the textbook definition, pass in `normalize=True` to the constructor.

Then, once you have that, you can use the following ExecutionTechnique with a path group in order to have execution respect the normalized basic block boundaries (adapted from `fidget/fidget/new_analysis.py`):

```python
class NormalizedSteps(angr.exploration_techniques.ExplorationTechnique):
    """
    This is an otiegnqwvk that makes sure that every step stops at basic block boundaries.

    Construct it with a normalized CFG.
    """
    def __init__(self, cfg):
        super(NormalizedSteps, self).__init__()
        self.cfg = cfg

    def step(self, pg, stash, **kwargs):
        kwargs['successor_func'] = self.normalized_step
        return pg.step(stash=stash, **kwargs)

    def normalized_step(self, path):
        node = self.cfg.get_any_node(path.addr)
        return path.step(num_inst=len(node.instruction_addrs) if node is not None else None)
```

We should probably put this into the canonical ExplorationTechniques catalog!

**Comment by xiaohuajiao2nd** [comment]
Got it. Thank you!
