### ISSUE TITLE
Keyerror when setting iropt to 0 in CFG

### ISSUE THREAD

**Issue by beratarik** [angr/angr#1934]
Hello,

  I am currently trying to use angr's backward slice in order to create a list of functions that are included on the slice for a given path. The sink is a write call, and one of the targets is the buffer that's being written. It works great until I give it an example that contains a function that takes in the buffer as a parameter, but does not modify it. The final output shouldn't have that function in the slice since it doesn't modify it, but it still gets listed as a dependency.

  My thought was that having iropt_level set to 1 in the cfg creation was causing it to think that the buffer was being modified in the irrelevant function due to some sort of optimization. However, if I try to switch to iropt_level 0, I always get an error. 99% of the time it's a keyerror from trying to access some output from the backward slice, which I think is because angr generates an incomplete or incorrect cfg and returns some empty data structure. This is the line for generating the cfg:
`cfg = proj.analyses.CFGEmulated(keep_state=True,
                                                        state_add_options=angr.sim_options.refs,
                                                        resolve_indirect_jumps=True,
                                                        fail_fast=True,
                                                        iropt_level=0,
                                                        context_sensitivity_level=0)`

**Describe the bug.**
Setting iropt_level to 0 when creating the cfg causes a keyerror, while keeping iropt_level at 1 causes the backward slice to be incorrect in specific cases. Main issue is inability to set iropt_level to 0.

**Environment Information.**
Output of `python -m angr.misc.bug_report` is attached
[report_and_example.zip](https://github.com/angr/angr/files/4098482/report_and_example.zip)

**To Reproduce.**
Source of example is also in 
[report_and_example.zip](https://github.com/angr/angr/files/4098484/report_and_example.zip)

**Comment by rhelmot** [comment]
I can't reproduce this on current master - with auto_load_libs=False, the cfg builds successfully, and with auto_load_libs=True it runs my machine out of memory.
