### ISSUE TITLE
cooperation

### ISSUE THREAD

**Issue by ljun85** [angr/angr#194]
Dear angr team, my company are looking forward to cooperating with your team in the field of binary analysis as stating in the paper _Offensive Techniques in Binary Analysis_.  You can email me, and tell me the price if you like.

**Comment by zardus** [comment]
Thanks for reaching out! We'd prefer to keep the github issues purely related to the project. I'm going to close this, but feel free to contact the angr team directly at angr-owner@lists.cs.ucsb.edu or on IRC.

Regarding cooperation in general, most of us are researchers in the security lab at UC Santa Barbara, where research takes up all of our available time. Normally, any cooperation we're looking for is academic (i.e., jointly working on some novel idea that we can publish together). That being said, sometimes, some of us do have time for side projects. It's definitely worth pinging us over email or IRC if you have a concrete idea!
