### ISSUE TITLE
symbion check_concrete_target_methods not comptaible with Cortex-M

### ISSUE THREAD

**Issue by alejoseb** [angr/angr#1947]
The method check_concrete_target_methods is not compatible with Cortex-M. Address 0x0 is valid for Cortex-M, so that control is not triggering the exception used to verify the implementation of the function concrete_target.read_memory.

https://github.com/angr/angr/blob/f0eea9a7e01c47989b62135873361da39704fe8c/angr/engines/concrete.py#L166

**Comment by degrigis** [comment]
Thanks for opening the Issue, I will look into this for the next Symbion's release!

**Comment by degrigis** [comment]
Simply removed this check to improve flexibility.
