### ISSUE TITLE
question about "Development install"

### ISSUE THREAD

**Issue by njupt-moon** [angr/angr#1948]
---

Hi, I follow the instructions listed in "Development install" (https://docs.angr.io/introductory-errata/install) to install angr, and I get the exception "ERROR: No matching distribution found for minidump==0.0.10 (from cle==8.20.1.7)". My PC runs Ubuntu 16.04 and python 3.5.2. Do you have any suggestions for solving this problem? Thanks!

**Comment by zardus** [comment]
Minidump only supports Python 3.6 and up, and CLE currently requires
minidump. You can either comment out the import of that part of CLE, or
switch to Python 3.6.

**Comment by twizmwazin** [comment]
We are also doing all of our testing on python 3.6, so 3.5 compatibility isn't really guaranteed at this point, even if we haven't directly used 3.6 features, yet. The best bet would be to install a newer version of Python, >= 3.6. angr-dev's setup.sh script allows you to reuse an existing virutalenv with the `-e` flag.
