### ISSUE TITLE
function_manager

### ISSUE THREAD

**Issue by ljun85** [angr/angr#195]
In[1]:b = angr.Project('/bin/true')
In[2]cfg = b.analyses.CFG()
In[3]cfg.function_manager.functions
Out[3]:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CFG' object has no attribute 'function_manager'

**Comment by rhelmot** [comment]
`cfg.function_manager` has been replaced with `cfg.functions`. Can you point me to the docs that need to be updated?

**Comment by ljun85** [comment]
Thanks very much. I got this from [here](http://www.tuicool.com/articles/3AFJBzz)

**Comment by ljun85** [comment]
For more, how could i print all the function name through cfg.functions?

**Comment by rhelmot** [comment]
That article is literally a copy-paste of an old version of our website, <http://angr.io>. You can get an updated version of the code in that article there.

`cfg.functions` is a dict-like mapping from function addresses to function names. You can access the function you like with `func = cfg.functions[addr]`, and the function's name with `name = func.name`.

**Comment by ljun85** [comment]
Thank you very much.
