### ISSUE TITLE
Question about Variable Recovery

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [angr/angr#1965]
---

Dear all,

I am quite new to angr, so I  apologize in advance for the basic questions. Currently, I am working on a binary reverse engineering project which needs to recover variables.

I came across your [Oakland 2016 paper](https://sites.cs.ucsb.edu/~vigna/publications/2016_SP_angrSoK.pdf), where you mention that "*On top of those access patterns, we perform a variable recovery for variables on both the stack and heap regions. Our implementation is similar to the variable recovery in TIE*". But I cannot find the document about variable recovery. Here are two quick questions I have:

1. Is angr's variable recovery algorithm almost the same as TIE's, or does angr additionally introduce some new techniques into TIE's original algorithm (to improve analysis)? 

2. If I just want to use the APIs, is the following example code correct?

```python
project = angr.Project("/bin/echo", load_options={'auto_load_libs': False})
cfg = project.analyses.CFG(normalize=True)
func = cfg.kb.functions[0x4006e0]   # the address of target function
kb = angr.KnowledgeBase(project)
vr = project.analyses.VariableRecovery(func, kb=kb)
variable_manager = vr.variable_manager[func.addr]
variable_manager.get_variables() 
```

Thanks very much.

**Comment by ltfish** [comment]
- The current implementations of `VariableRecovery` (both `VariableRecovery` and `VariableRecoveryFast`) have nothing to do with the original analyses mentioned in our paper. These two analyses do not utilize advanced type inference algorithms to recognize structs on heap.

- Your code snippet looks good to me. Using `VariableRecoveryFast` will probably give you better results.
