### ISSUE TITLE
CFGFast: crash in _process_irrational_functions

### ISSUE THREAD

**Issue by quoscient** [angr/angr#197]
The line https://github.com/angr/angr/blob/fb96563836d42e006dbc03bacac1e859519bc55f/angr/analyses/cfg_base.py#L1217 crashes CFGFast if `function.startpoint` is None. What surprised me is that the function had one node, nevertheless function.startpoint was empty.
Moving the check
```python
if not function.endpoints:
       # Function should have at least one endpoint
       continue
```
above the offending line causes the symptom to go away because `function.endpoints` is empty.

**Comment by ltfish** [comment]
It's... umm... weird. Can you please give me the binary that reproduces this issue?

**Comment by quoscient** [comment]
No longer reproducible with the latest version of angr
