### ISSUE TITLE
How does angr excavate object/ variable type information?

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr#1984]
I observed that TIE and artiste are one of the best approaches for type information extraction. Does angr use any of these? Or does it depend on some other technique?

I highly appreciate any paper/ approach suggestions in this domain. Thank you.

> EDIT: I saw the question on variable or object recovery, but that seems unrelated.

**Comment by ltfish** [comment]
Retypd is probably the best published technique for type inferencing on binary code so far: https://arxiv.org/abs/1603.05495

I'm trying to fully implement retypd in angr. It's currently WIP and I still need a lot of time to finish it. But we should soon be getting a somewhat usable version. It's on branch `feat/typehoon`.

There is also a branch `feat/type_inference` that @lockshaw implements. I'm not exactly sure what state that branch is in.

**Comment by ltfish** [comment]
Going back to the question in your title: angr does not really do much type inference at this moment. The closest thing in angr is the "type guessing" that is implemented in `CFGFast`.
