### ISSUE TITLE
Can't find branches that are not symbolic

### ISSUE THREAD

**Issue by burunkus** [angr/angr#1988]
---

How can I find the branches in a program that does not have a symbolic variable?
I have attached the binary of the program. As I step through this program, I would like to find the states at each branch whether the branch has a symbolic variable or not.

Address of the branch without a symbolic variable that is hidden during execution:
0x4007b6
Addresses of branches with Symbolic variables that are seen during execution:
0x4007a7
0x4007db

[test.zip](https://github.com/angr/angr/files/4295653/test.zip)

**Comment by rhelmot** [comment]
Are you sure you attached the right binary? That binary loads mapping `0x100000000:0x100180000`.

Could you also indicate what python code you're using exactly, preferably in the form of a testcase with an assert at the end which should pass but actually fails?

**Comment by burunkus** [comment]
I have reattached the binary:
[test.zip](https://github.com/angr/angr/files/4296167/test.zip)

Here is my Python code:
```python
import angr


def find_branches(proj, simgr):
    branches = []
    state = None
    while len(simgr.active) == 1:
        state = simgr.active[0]
        #print(simgr, simgr.active)
        if simgr.unsat:
            print(simgr.unsat)
        simgr.step()
    branches.append(state)
    #print()

    simgr = proj.factory.simgr(simgr.active[0], save_unsat=True)
    while len(simgr.active) == 1:
        state = simgr.active[0]
        #print(simgr, simgr.active)
        if simgr.unsat:
            print(simgr.unsat)
        simgr.step()
    branches.append(state)
    return branches


def test():
    proj = angr.Project('test', auto_load_libs=False)
    state = proj.factory.entry_state()
    simgr = proj.factory.simgr(state, save_unsat=True)

    branch_addresses = [0x4007a7, 0x4007b6, 0x4007db]
    branches = find_branches(proj, simgr)
    for i in range(len(branches)):
        assert hex(branches[i].addr) == hex(branch_addresses[i]), "Should be " + \
              str(hex(branch_addresses[1]))


if __name__ == '__main__':
    test()
```

**Comment by rhelmot** [comment]
Your `find_branches` code will explicitly not work with unsatisfiable branches - the only thing you look for is states which produce two active successors. This will, obviously, not detect when a state shows up in the unsat stash. The print logging does in fact show the unsat state you're looking for - 0x4007db is the result of 0x4007af (or as you have it written, 0x4007b6) branching.
