### ISSUE TITLE
angr adds wrong constraints to a state.

### ISSUE THREAD

**Issue by whj0401** [angr/angr#1993]
---

**Describe the bug.**

While doing symbolic execution, angr creates some constraints which should not exist.

**Environment Information.**

Date: 2020-03-11 19:13:14.863498
Running in virtual environment at /home/whj/.virtualenvs/angr2
Platform: linux-x86_64
Python version: 3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:04)
[PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
######## angr #########
Python found it in /home/whj/git/angr-dev2/angr/angr
Pip version angr 8.20.1.7
Git info:
        Current commit a90621f1ce2854a0e8181ce280b6be3d729f3083 from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/whj/git/angr-dev2/ailment/ailment
Pip version ailment 8.20.1.7
Git info:
        Current commit 5e6a5cc374bc9dd0597363e656a778a6c8bd1ae9 from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/whj/git/angr-dev2/cle/cle
Pip version cle 8.20.1.7
Git info:
        Current commit 6b833cb03b7c45903661ec87ec2602460f799441 from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/whj/git/angr-dev2/pyvex/pyvex
Pip version pyvex 8.20.1.7
Git info:
        Current commit f4753f85a8c18dae9dbb32301f8a7804efd36491 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/whj/git/angr-dev2/claripy/claripy
Pip version claripy 8.20.1.7
Git info:
        Current commit 8fc35a0ec4cc69b27795dd305a289a47d9f169e2 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/whj/git/angr-dev2/archinfo/archinfo
Pip version archinfo 8.20.1.7
Git info:
        Current commit 6581f6ac618c7db8d32fed10dda1e02097fea4f3 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/whj/.virtualenvs/angr2/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/whj/.virtualenvs/angr2/site-packages/unicorn
Pip version unicorn 1.0.2rc2
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/whj/git/angr-dev2/angr/angr/lib/angr_native.so', handle 2383cc0 at 0x7f5f4d95f6e0>
unicorn: <CDLL '/home/whj/.virtualenvs/angr2/site-packages/unicorn/lib/libunicorn.so', handle 21da9d0 at 0x7f5f53a61018>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00007f5f5323bcc8>
z3: <CDLL '/home/whj/.virtualenvs/angr2/site-packages/z3/lib/libz3.so', handle 20e8780 at 0x7f5f50ddc170>

**To Reproduce.**

The binary is `nl` of coreutils (8.28) and it is compiled with option '-O0'. Please get it from https://drive.google.com/file/d/1XpYdzN6Z-chQIEdkVYNEXFZCXgnks3TH/view?usp=sharing

`In[3]: p = angr.Project('nl', auto_load_libs=False, default_analysis_mode='symbolic')`
`In[4]: state = p.factory.blank_state(addr=4220521)`
`In[5]: state.block().pp()`
0x406669:	mov	qword ptr [rbp - 8], rax
0x40666d:	cmp	qword ptr [rbp - 8], -1
0x406672:	jne	0x40667b
`In[6]: sucs = state.step()`
`In[7]: sucs[0].solver.constraints`
Out[7]: 
[<Bool reg_rbp_0_64{UNINITIALIZED} == 0x7>,
 <Bool Reverse(reg_rax_1_64{UNINITIALIZED}[7:0] .. Reverse(reg_rax_1_64{UNINITIALIZED})[55:0]) == 0xffffffffffffffff>]

The constraint `<Bool reg_rbp_0_64{UNINITIALIZED} == 0x7>` should not exist. It seems angr compares both values `[rbp - 8]` and `rbp - 8` with -1.
**Additional context.**

**Comment by rhelmot** [comment]
Copied from slack:

That's not a bug, that's the best angr can do. What do you expect the result of loading from an unconstrained pointer to be? We have to concretize it in order to be able to continue execution.
