### ISSUE TITLE
when install simuvex for angr, it warns Could not find a version that satisfies the requirement gitdb>=4.0.1

### ISSUE THREAD

**Issue by lxy0816** [angr/angr#1995]
when I install simuvex, it says that"  Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.9->angr->simuvex) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.9->angr->simuvex)
"
the installation failed. Can you give me some guide?

**Comment by ltfish** [comment]
We merged SimuVEX into angr in 2017. There is no SimuVEX anymore. Please installed the latest angr instead.

**Comment by lxy0816** [comment]
But when I directly " pip install angr", it also give me the same error

**Comment by twizmwazin** [comment]
Is this in a clean virtualenv, or the old one from before? What if you try `pip install angr==8.20.1.7`?

**Comment by lxy0816** [comment]
Yeah. It's clean. Before install angr,I do not do anything to this env.
If I "pip install angr==8.20.1.7", it sasys
`ERROR: Could not find a version that satisfies the requirement angr==8.20.1.7 (from versions: 0.8.0, 0.8.1, 4.5.9.9b0, 4.5.9.9, 4.5.9.13, 4.5.9.13.post1, 4.5.9.14, 4.5.9.22, 4.5.9.29, 4.5.10.14, 4.5.10.15, 4.5.11.23, 4.5.12.12, 4.5.12.21, 4.5.12.28, 4.6.1.4, 4.6.1.12, 4.6.1.18, 4.6.1.30, 4.6.2.25, 4.6.3.15, 4.6.3.15.post1, 4.6.3.18, 4.6.3.28, 4.6.4.28, 4.6.5.27, 4.6.5.27.post1, 4.6.6.4, 4.6.6.4.post1, 4.6.6.10, 4.6.6.15, 4.6.6.16, 4.6.6.28, 4.6.6.29, 5.6.8.22, 5.6.10.5, 5.6.10.7, 5.6.10.12, 5.6.12.3, 6.7.1.13, 6.7.1.13.post2, 6.7.1.31, 6.7.3.26, 6.7.4.12, 6.7.6.9, 6.7.7.27, 6.7.7.31, 7.7.9.8, 7.7.9.8.post1, 7.7.9.14, 7.7.9.21, 7.7.12.16, 7.8.2.21, 7.8.6.16, 7.8.6.23, 7.8.7.1, 7.8.8.1, 7.8.9.26)
ERROR: No matching distribution found for angr==8.20.1.7`

**Comment by rhelmot** [comment]
It sounds like you're using python2. We stopped supporting python2 a long time ago (october 2018). We made an attempt to make it so that the last py2 release of angr would still work for a while into the future by pinning all our dependencies in that release, but it seems like some of the dependencies of the dependencies have stopped working under py2.

Switch to py3. It's 2020.

**Comment by Dascolee** [comment]
> when I install simuvex, it says that" Could not find a version that satisfies the requirement gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.9->angr->simuvex) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4)
> No matching distribution found for gitdb>=4.0.1 (from gitdb2>=2.0.0->GitPython==2.1.9->angr->simuvex)
> "
> the installation failed. Can you give me some guide?

你好我也遇到了同样的问题，请问你的问题解决了吗

**Comment by zardus** [comment]
@Dascolee yes, I think we solved it. The problem seemed to be a python2 environment. angr only supports python3.

**Comment by Dascolee** [comment]
> @Dascolee yes, I think we solved it. The problem seemed to be a python2 environment. angr only supports python3.

thank you ,I solved the problem. angr only supports python3 and version>3.6 ,my version is 3.5 ~~~~(>_<)~~~~

**Comment by Dascolee** [comment]
@zardus 
thank you ,I solved the problem. angr only supports python3 and version>3.6 , my version is 3.5 
~~(>_<)~~

**Comment by jiuge88** [comment]
Maybe the version of angr is too low. Maybe you can try Python 3 - M PIP install -- upgrade angr
