### ISSUE TITLE
Error with "claripy" module

### ISSUE THREAD

**Issue by chubbymaggie** [angr/angr#2]
After install angr, I am getting the following error:
```
$python -c "import angr"
No handlers could be found for logger "claripy"
Exception TypeError: "'NoneType' object is not callable" in  ignored
Exception TypeError: "'NoneType' object is not callable" in  ignored
```

Update: I installed angr on a 64bit Ubuntu 12.04 machine.

**Comment by jmgrosen** [comment]
The `No handlers could be found` message is a warning, not an error, so it should still work fine. It is annoying, though, so we'll look into getting rid of it. I'll leave this issue open for that.

The `Exception TypeError` messages are a bug somewhere in Z3's destructors. We're not quite sure why they don't pop up with everyone's use of Z3, so we'll also see if we can find the bug in Z3 or find a workaround.

**Comment by zardus** [comment]
To be clear: none of these are actually errors, and neither of them will affect your usage of angr.

**Comment by chubbymaggie** [comment]
That's clear now. Thank you for the prompt reply :+1:

**Comment by ltfish** [comment]
I think this issue has been fixed. Can someone confirm and close it?

**Comment by chubbymaggie** [comment]
I am not getting this error anymore. So, I think the issue is fixed.
