### ISSUE TITLE
Slow Control Dependence Analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#20]
I'm trying the CDG analysis. But it's been half an hour, I'm still not seeing any output. From my understanding, CDG analysis should be faster than the CFG analysis. Is there any secret option to make it faster?

```
proj = angr.Project('/bin/ls', load_options={'auto_load_libs': False})
cdg = proj.analyses.CDG()
```

Thanks.

**Comment by ltfish** [comment]
You are absolutely right. Control dependence analysis is simply converting a CFG to a CDG. So you want to pass in a CFG to CDG analysis to see why it's taking such a long time. Maybe it's spending an hour generating the CFG?

```
proj = angr.Project(blahblahblah)
cfg = proj.analyses.CFG(blah)
cdg = proj.analyses.CDG(cfg=cfg)
```

**Comment by riyadparvez** [comment]
On Thu, Sep 3, 2015 at 7:24 PM, ltfish <notifications@github.com> wrote:

> You are absolutely right. Control dependence analysis is simply converting
> a CFG to a CDG. So you want to pass in a CFG to CDG analysis to see why
> it's taking such a long time. Maybe it's spending an hour generating the
> CFG?
>
> proj = angr.Project(blahblahblah)
> cfg = proj.analyses.CFG(blah)
> cdg = proj.analyses.CDG(cfg=cfg)
>
>
I've tried this. Still the same, running for more than an hour until I
killed it. Any idea why this is happening?

**Comment by ltfish** [comment]
Can you please tell me which line takes most of the time? Is it creating CFG takes a long time, or creating the CDG?

**Comment by riyadparvez** [comment]
Creating CFG works just fine. It's the CDG that's taking so much time.

**Comment by ltfish** [comment]
Oops, let me try it out and see what's going on... thanks for reporting.

**Comment by ltfish** [comment]
I updated the implementation of CDG. Can you pull the latest angr and try it again?

**Comment by riyadparvez** [comment]
It is working. Thanks!
