### ISSUE TITLE
arm pc load

### ISSUE THREAD

**Issue by r4dr3fr4d** [angr/angr#2002]
I often see thunks like the following that are not resolved by the indirect jump resolvers when building a CFGFast.  My guess as to why they don't resolve the target is because they aren't technically jumps, but rather direct loads into the program counter.  Are these supposed to be detected/resolved?

```
mov.w r10, #<func pointer table or something>
ldr.w, pc, [r10+#<some offset>]
```

**Comment by ltfish** [comment]
We can easily detect them. Internally, we have an on-going research project that will handle such cases (and many more). While I can probably implement an indirect jump resolver for these cases within a week, I wouldn't ruin the fun from the student who's working on it.

If you want an estimate of when our research project will be done, I would say, six months.

**Comment by ltfish** [comment]
> My guess as to why they don't resolve the target is because they aren't technically jumps, but rather direct loads into the program counter.

They are indirect jumps. In ARM indirect jumps are simply writes to PC.

**Comment by mahaloz** [comment]
Hi @r4dr3fr4d could I possibly get the binary you reference?

**Comment by ltfish** [comment]
I believe we now properly resolve these cases on ARM binaries. Reopen if this is still an issue.
