### ISSUE TITLE
Change a value of concrete

### ISSUE THREAD

**Issue by KeuntaeShin** [angr/angr#2004]
There was a circumstance to find next IRSBs. And i expected  2 IRSBs. However, angr showed just one IRSB. After analyzing instructions, i noticed register r0 was fixed (concretized) and used for compare & branch. Also, state.regs.r0.concrete was confirmed as true reasonably.

I didn't provide any options for concretization of registers. I thought i could get the expected 2 IRSBs if i change the value of state.regs.r0.concrete  when the instruction pointer is reached before the compare & branch.

I got a result below:

    state.regs.r0.concrete = False
AttributeError: can't set attribute

Is there any way to make the register r0 to be not concretized always ?

**Comment by rhelmot** [comment]
`state.regs.r0 = claripy.BVS('r0', state.arch.bits)`

However, angr is an emulator. If the program loads a different value into r0, then r0 will hold that value. There is no way to guarantee it will "always" be symbolic.

**Comment by KeuntaeShin** [comment]
This is a proper solution.
