### ISSUE TITLE
After explore

### ISSUE THREAD

**Issue by KeuntaeShin** [angr/angr#2005]
I’m trying to find ALL IRSBs just prior to a target IRSB. For instance, if 0x172b is a target IRSB, there would multiple IRSBs to reach the one.
After a statement below:
sim.explore(find=address_of_target_code)

Several states were found like below:
[<SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>]

As well as, several IRSBs were remained as active state (It is not the one I expected.):
[<SimState @ 0x5264>, <SimState @ 0x13c1>,....]

After manual analyzing along instructions from the active SimStates still remained, i realized the 0x172b will be eventually reached from the remained SimStates.

Q1 : Why the SimStates, which were categorized as active, were remained?

Q2 : Is there any way to keep job of explore until all active states are consumed?

**Comment by rhelmot** [comment]
explore takes an argument for how many states it should find. `num_find=9999999` is probably something along the lines of what you want.

**Comment by KeuntaeShin** [comment]
THANKS to rhelmot!

I leave the result for this community.

After a statement below:
sim.explore(find=address_of_target_code)

Several states were found like below:
[<SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>]


After a statement below:
sim.explore(find=address_of_target_code,num_find=20)

Several states were found like below:
[<SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>, <SimState @ 0x172b>]

However the active states remained has been increased, also time-consumption has been increased with that.
