### ISSUE TITLE
How to get variable/ structure definitions

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr#2007]
---

From the documentation, I can see that [this](https://angr.io/api-doc/angr.html?highlight=cfg#angr.analyses.variable_recovery.variable_recovery_base.VariableRecoveryStateBase) class gives the variable definitions for the function.

What I did:

```
>>> proj = angr.Project('../../re_challenges/type_inference/a.out', auto_load_libs=False)
>>> vari = proj.analyses.VariableRecovery(proj.entry)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ruturaj/.local/lib/python3.8/site-packages/angr/analyses/analysis.py", line 111, in __call__
    oself.__init__(*args, **kwargs)
  File "/home/ruturaj/.local/lib/python3.8/site-packages/angr/analyses/variable_recovery/variable_recovery.py", line 409, in __init__
    function_graph_visitor = FunctionGraphVisitor(func)
  File "/home/ruturaj/.local/lib/python3.8/site-packages/angr/analyses/forward_analysis/visitors/function_graph.py", line 14, in __init__
    self.graph = self.function.graph
AttributeError: 'int' object has no attribute 'graph'
```
I tried different arguments like "main", etc., but it still gives me the above error. Note that the binary I am working with is a stripped binary.

```
#include <stdbool.h>
int do_decode(){}
int main()
{
  bool decode = false;
  char opt = getopt();
  switch (opt)
  {
    case 'd':
      decode =true;
      break;
    default:
      break;
  }
  if (decode) do_decode();
}
```
I would like to get the variable (including struct, arrays) information. For e.g. radare gives me:

```
var int64_t var_2h @ rbp-0x2
var uint32_t var_1h @ rbp-0x1
```

which is not perfect and not too bad.

**Comment by cq674350529** [comment]
Maybe you can refer to this for `VariableRecovery` usage.

https://github.com/angr/angr/blob/755dcb8b80907e95ae2d6b29c181ef9dc50193f3/tests/test_variablerecovery.py#L76-L92
