### ISSUE TITLE
Changing behaviour of z3 solver during symbolic execution (i.e tactics used)

### ISSUE THREAD

**Issue by CatBlower** [angr/angr#2013]
Hi, 
First of all thanks for all your work on angr, it's an awesome tools !

I'm currently interested in the use of z3 solver during analysis of some binary with symbolic execution. In this prospect, I was wandering if there is any simple way of changing the default behaviour of z3 in angr (i.e apply other tactics than :  **simplify, propagate-ineqs, propagate-values, unit-subsume-simplify**). For example use tactics like **qflra** or others (https://github.com/Z3Prover/z3/tree/master/src/tactic/smtlogics) ?

Don't know if it was better to ask this question in the claripy repo or in this repo ?

**Comment by rhelmot** [comment]
There isn't a good way to do this. We would welcome an interface for changing this somehow, though it'll be a little tricky because of how deeply buried the backend is, and how we will sometimes reuse the backend across states. (correct me if I'm wrong?)
