### ISSUE TITLE
win10+python3，when i install the pyvex ,a error occurs. The error is "error: Unable to build libVEX."

### ISSUE THREAD

**Issue by leslielee619** [angr/angr#2014]
---

I have already installed z3 by installing a VC++ enviroment, but i cant install pyvex. I look up some blog, find that they install angr in linux or windows+python2.
the error is as follow .
============================================================
    ERROR: Command errored out with exit status 1:
     command: 'd:\software\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LESLIE~1\\AppData\\Local\\Temp\\pip-install-6nk5jkv1\\pyvex\\setup.py'"'"'; __file__='"'"'C:\\Users\\LESLIE~1\\AppData\\Local\\Temp\\pip-install-6nk5jkv1\\pyvex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LESLIE~1\AppData\Local\Temp\pip-record-kd2sqrr6\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\software\python3\Include\pyvex'
         cwd: C:\Users\LESLIE~1\AppData\Local\Temp\pip-install-6nk5jkv1\pyvex\
    Complete output (4 lines):
    running install
    running build
    Building libVEX
    error: Unable to build libVEX.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\software\python3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LESLIE~1\\AppData\\Local\\Temp\\pip-install-6nk5jkv1\\pyvex\\setup.py'"'"'; __file__='"'"'C:\\Users\\LESLIE~1\\AppData\\Local\\Temp\\pip-install-6nk5jkv1\\pyvex\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LESLIE~1\AppData\Local\Temp\pip-record-kd2sqrr6\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\software\python3\Include\pyvex' Check the logs for full command output.

**Comment by rhelmot** [comment]
You need to be in the visual studio developer command prompt so the C compiler is in your $PATH.

**Comment by leslielee619** [comment]
Okay, i'll try it, tahks for your help.

**Comment by leslielee619** [comment]
Hello, i just install  visualcppbuildtools_full.exe solve the problem. i use VC++ command prompt to install pyvex. i find it just now, 哈哈.
