### ISSUE TITLE
Searching all path with same sequence

### ISSUE THREAD

**Issue by KeuntaeShin** [angr/angr#2017]
I expected that an output will be same from a snippet below:
```
sim.use_technique(angr.exploration_techniques.DFS())
…
sim.explore(find=address_of_target_code,num_find=1)
print(sim.found[0].history.bbl_addrs.hardcopy)
```

However the result was changed almost always whenever the script was executed with an identical target ELF file. For instance, sometimes 13 elements was printed, sometimes xx elements was printed.

What i found:
```
def step(self, simgr, stash='active', **kwargs):
        simgr = simgr.step(stash=stash, **kwargs)
        if len(simgr.stashes[stash]) > 1:            
            self._random.shuffle(simgr.stashes[stash])            
            simgr.split(from_stash=stash, to_stash=self.deferred_stash, limit=1)
```

I found that the implementation of DFS shuffles elements of list of simgr.stashes. So i commented that code.
```
def step(self, simgr, stash='active', **kwargs):
        simgr = simgr.step(stash=stash, **kwargs)
        if len(simgr.stashes[stash]) > 1:            
            #self._random.shuffle(simgr.stashes[stash])            
            simgr.split(from_stash=stash, to_stash=self.deferred_stash, limit=1)
```

After few executions, the results were not still fixed. What can i do to get identical elements whenever the above code is executed? (I’m not sure, but all concreted values could be symbolized to lead searching all path with same sequence)

**Comment by rhelmot** [comment]
I can add a parameter that lets you specify the seed for the DFS shuffling. But other kinds of nondeterminism should not be in angr. Can you upload a testcase that exhibits this behavior so I can look into it?
