### ISSUE TITLE
CFGFast None-Type bug

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#202]
The library where i try to build the CFG from is a stripped statically linked binary with libc statically linked. Compiler clang. 

The line cfg_base:757 returns None
`target_func = self.kb.functions.function(addr=target_addr)
 `
The line after gives the None-Type has no attribute returning exception.
`if target_func.returning is False:`
    `edges_to_remove.append((src, dst))`                   

The last edge is strange:
`...`
`[(BlockNode at 0x4a239 (size 22)>, <Function sub_108f0 (0x108f0)>, {'type': 'call'})]`
`[(<BlockNode at 0x4a22f (size 10)>, <Function sub_10160 (0x10160)>, {'type': 'call'})]`
`[(<BlockNode at 0x4a1e9 (size 18)>, <BlockNode at 0x4a177 (size 54)>, {'outside': False, 'type': 'transition'}), (<BlockNode at 0x4a1e9 (size 18)>, <Function sub_4a1fb (0x4a1fb)>, {'type': 'call'})]`

Couldn't build a suitable fix for this behaviour. 

[stripped_stat_test.zip](https://github.com/angr/angr/files/454624/stripped_stat_test.zip)

**Comment by ltfish** [comment]
This is indeed a bug. I'll take a look at it.

**Comment by AndyXan** [comment]
Thank you Itfish. I Tried to find a reasonable solution but, well - i'm not that deep into the code. 

Good luck!

**Comment by ltfish** [comment]
This issue should be resolved by commit eadfb4834111406c6573d30191eb0edafed01519.
