### ISSUE TITLE
Weird evaluation

### ISSUE THREAD

**Issue by KeuntaeShin** [angr/angr#2020]
I expected 4 or 5 from this script:

```
import angr

proj = angr.Project('/bin/true')
state = proj.factory.entry_state()

x = state.solver.BVS("x", 64)
y = state.solver.BVS("y", 64)

state.solver.add(x > y)
state.solver.add(y > 2)
state.solver.add(6 > x)

cnt = 100

while cnt > 0:
    print(state.solver.eval(x))
    cnt  = cnt - 1
```

However i got only 4:

> ...
> 4
> 4
> 4
> ...
> Process finished with exit code 0

1. Why i got only 4?
2. Is there any way to find all values, such that 4 and 5.

**Comment by rhelmot** [comment]
successive calls to eval will always use the same model. If you want multiple models you want one of other methods on solver, for example `eval_upto(n)`, which will give you a tuple of up to n distinct solutions.
