### ISSUE TITLE
Image generated by plot_cfg

### ISSUE THREAD

**Issue by KeuntaeShin** [angr/angr#2033]
When number of nodes is small, there is no trouble. However, i got more than 100,000 nodes and edges from below snippet:
`    cfg = project.analyses.CFGFast(function_starts=[0x1123])`

And then a png had been generated by:
`    plot_cfg(cfg, "png.png", asminst=True)`

The generated image was blurred so that the drawn text could not be identified. Can i control the resolution of image even thought the size of image is increased?

**Comment by rhelmot** [comment]
`plot_cfg` is from https://github.com/axt/angr-utils, which is not part of the angr suite. Open an issue there if you want help. If you want an officially supported way of visualizing CFGs, use https://github.com/angr/angr-management
