### ISSUE TITLE
A block is not in CFGAccurate,but I can find it with explore.

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#204]
Hi,
I meet some problems. When I try to find a node ,the address of which is  `0x401f45` ,in CFGAccurate, it return me null list `[]` (and CFGFast can return me the node `[<CFGNode parse_hex4 (0x401f45) [0]>]` ),but I can get a `found path` by using `path_group.explore(find=0x401f45,num_find=1)`.
So,what kinds of nodes the CFGAccurate will miss? 

Thanks a lot! Have a good day!

**Comment by ltfish** [comment]
`CFGAccurate` may fail to resolve some indirect jumps, and consequently misses all blocks that are only reachable when those jump targets are taken.
