### ISSUE TITLE
angr goes into an infinite loop

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr#2054]
---

**Environment Information.**

=============================
Date: 2020-04-12 09:10:52.989296
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.2 (default, Mar 20 2020, 17:00:00)
[GCC 5.4.0 20160609]
######## angr #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/angr
Pip version angr 8.20.1.7
Couldn't find git info
######## ailment #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/ailment
Pip version ailment 8.20.1.7
Couldn't find git info
######## cle #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/cle
Pip version cle 8.20.1.7
Couldn't find git info
######## pyvex #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/pyvex
Pip version pyvex 8.20.1.7
Couldn't find git info
######## claripy #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/claripy
Pip version claripy 8.20.1.7
Couldn't find git info
######## archinfo #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/archinfo
Pip version archinfo 8.20.1.7
Couldn't find git info
######## z3 #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/ruturaj/.local/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.1
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/ruturaj/.local/lib/python3.8/site-packages/angr/lib/angr_native.so', handle 1d8dd30 at 0x7f86d5c1d400>
unicorn: <CDLL '/home/ruturaj/.local/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 127bc50 at 0x7f86d4e1ef10>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f86d5b380a0>
z3: <CDLL '/home/ruturaj/.local/lib/python3.8/site-packages/z3/lib/libz3.so', handle 14b5e40 at 0x7f86d1dc0be0>

**Describe the bug.**

I have following code:

    #include <stdio.h>
    #include <stdlib.h>
    typedef void (*Handler)(void); /* A pointer to a handler function */
     /* The functions */
    void func3 (void) { printf( "3\n" ); }
    void func2 (void) { printf( "2\n" ); }
    void func1 (void) { printf( "1\n" ); }
    void func0 (void) { printf( "0\n" ); }
    Handler jump_table[4] = {func0, func1, func2, func3};
    int main (int argc, char **argv)
    {
     int value; /* Convert first argument to 0-3 integer (Hash) */
    value = atoi(argv[1]) % 4;
    if (value < 0) { value *= -1; } /* Call appropriate function (func0 thru func3) */
    jump_table[value]();
     }

I wrote a script (using angr api) to get the decompilation (pseudo code) output for each function:

    project = angr.Project(bin_path, load_options={'auto_load_libs': False})
    cfg = project.analyses.CFG(data_references=True, normalize=True)
    for func in cfg.functions.values():
        if func.name.startswith("__"):
            continue
        else:
            try:
                store[func.name] = project.analyses.Decompiler(func).codegen.text
            except:
                continue

For this program, angr goes in an infinite loop (it takes forever, I had to interrupt). Note that I installed the latest version of angr (using pip).

**Comment by ltfish** [comment]
Your code works on the latest master. Can you please pull both angr and ailment and try again?

**Comment by Ruturaj4** [comment]
Thanks fish, it works now.
