### ISSUE TITLE
how to use angr to test GNU Coreutils.

### ISSUE THREAD

**Issue by Chozmao** [angr/angr#207]
hi guys. is there any tutorial on how to use angr to test GNU Coretutils.-.-.
i need to evaluate the gains that Veritesting can provide by comparing it to "naive" symbolic execution.
so i need the Node,Path Coverage information.but actually i don't know how to start with that. 
Need some suggestions from you.
thanks.

**Comment by zardus** [comment]
No tutorial to do specifically that exists... What you would want to do, from the angr level, is:

1. Create an otiegnqwvk (http://angr.io/api-doc/angr.html#angr.exploration_techniques.ExplorationTechnique) that represents your analysis method. Naive symbolic execution on coreutils will get overwhelmed almost immediately (while we're at it, so will veritesting). You will definitely need to design some sort of prioritization and path filtering system. This can be as trivial as just keeping a random N of all the paths, but it should be something.
2. Run a PathGroup with that exploration technique to test naive symbolic execution.
3. Run a PathGroup with that exploration technique *and* a nested veritesting technique to test veritesting.
4. Compare.

The core take-away is that you'll need something like an ExplorationTechnique to guide your analysis.

With coreutils, you will also run into a lot of gotchas related to missing environment models (syscalls). You can read about these gotchas here: http://docs.angr.io/docs/gotchas.html

**Comment by zardus** [comment]
Whoops, looks like I typoed `ExplorationTechnique` as `otiegnqwvk` in my answer; sorry about that!

For now, I'll close this issue. Please reopen it if you have more questions.
