### ISSUE TITLE
Signed division operation is simulated as unsigned

### ISSUE THREAD

**Issue by AntonKukoba1** [angr/angr#2076]
When implementing the new platform I defined div instruction in the following way:
```
def compute_result(self, reg2, reg1):
    return reg2.signed / reg1.signed, reg2.signed % reg1.signed
```

While simulating the division operation, the partially correct vex instructions block is generated:
```
00 | ------ IMark(0x0, 4, 0) ------
   01 | t0 = GET:I32(r18)
   02 | t1 = GET:I32(r19)
   03 | t2 = DivS32(t0,t1) 
   04 | t3 = Mod32(t0,t1) <----
   05 | PUT(r18) = t2
   06 | PUT(r17) = t3
   NEXT: PUT = 0x00000004; Ijk_Boring
```
First of all it should put ModS32 here, just like DivS32. 

Secondly, when simulation is happening Div is used instead of SDiv in claripy, so the calculation result is totally wrong in case operands are negative numbers. The probem also affects Mod instruction too, e.g. it produces wrong result in case of negative numbers.

use t0 = 0xad45cf1a(-1387933926), t1 = 0xfff55224 (-699868)

The expected result of DivS32 in t2 is 0x7bf, Actual 0x0

There was an attempt to workaround the issue: https://github.com/angr/angr/commit/71aae4893ad77c4c696e6debefe44b5298330e30 but it's not enough to fix all the related effects.

**Comment by rhelmot** [comment]
@subwire this is at least partially for you, you need to split Mod (which you invented) into ModS and ModU. Then I can make it supported on the irop end.

In the meantime, you can just use the kosher divmod vex ops, which are implemented correctly I'm fairly certain.
