### ISSUE TITLE
`DepGraph` update is (probably) incorrect in `LiveDefinitions`

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#2079]
During a `ReachingDefinitionsAnalysis`, the `LiveDefinitions` state is updated depending on the definitions and uses found.
In particular, there is a `dep_graph` (for dependency graph) that is updated; this is a graph where nodes are `Definition`s, and edges represent the relation of dependency between these definitions (`a` is a successor of `b` if `a` uses `b`).

1) However, there is a **bug** in the [`_add_stack_use_by_def` method](https://github.com/angr/angr/blob/71aae4893ad77c4c696e6debefe44b5298330e30/angr/analyses/reaching_definitions/live_definitions.py#L346): an edge is added between a `Definition` and a `CodeLocation`!

2) It seems surprising that `_add_stack_use_by_def` updates the dependency graph, but `_add_register_use_by_def`, `_add_memory_use_by_def`, `_add_tmp_use_by_def` don't... Shouldn't this code (updating the graph) be moved at the end of the [_add_use_by_def method](https://github.com/angr/angr/blob/71aae4893ad77c4c696e6debefe44b5298330e30/angr/analyses/reaching_definitions/live_definitions.py#L246-L256)?

**Comment by ltfish** [comment]
I agree with what you proposed. Do you want to send a PR or should I fix them?

**Comment by Pamplemousse** [comment]
Cool. I am on it :)
