### ISSUE TITLE
angr decompiler - structure representation

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr#2080]
---

Is it possible to get the structure information using angr?

I have following code (unstripped):

```
#include <stdio.h>
#include <stdlib.h>
struct P
{
  int a;
  int b;
};

int main()
{
  struct P *p = (struct P*) malloc(sizeof(struct P));
  p->a = 4;
  p->b = 8;
  printf("%d\n", p->a);
  printf("%d\n", p->b);
  return 0;
}
```

Angr commandline with default options gives me following output:

```
void main()
{
    ir_1 = malloc(0x8);
    None = 4;
    None = 8;
    printf(0x400654<64>);
    printf(0x400654<64>);
    ir_7 = 0;
    rsp<8> = stack_base+8;
    return;
}
```

It doesn't identify the structure. For e.g. `ir_1` is a object of structure `P` in this case.

While IDA pro and ghidra on the other hand, correctly identifies that it is a structure and structure elements. Note that this is an unstripped binary. Is there any way in angr to do that?

**Comment by rhelmot** [comment]
This feature is under active development. It will come soon, probably in the next two months.
