### ISSUE TITLE
angr decompilation: type information in decompiler output

### ISSUE THREAD

**Issue by Ruturaj4** [angr/angr#2081]
---
Is there any way to get the data type information in the decompiler output?

Here is a c source code:

```
// int
#include <stdio.h>
int foo(int a){
  int b = a + 400;
  printf("%d\n", b);
  return b;}
int main()
{
  int a = 100;
  printf("%d\n", a);
  a = foo(a);
  printf("%d\n", a + 200);
  return 0;
}
```
I have stripped and used unstripped binary as well, but angr doesn't give me the data type information in the output.

```
void main()
{
    printf(0x400634<64>);
    ir_4 = foo();
    printf(0x400634<64>);
    ir_7 = 0;
    rsp<8> = stack_base+8;
    return;
}
```

For e.g. data type of ir_4 would be "int". So, it can be represented as - `int ir_4 =foo();`

Ida and ghidra on the other hand detects some notion of type in stripped and unstripped case as well. Radare gives me a custom type information.

**Comment by rhelmot** [comment]
Again, this is under active development. The relevant dev branch is [feat/typehoon](https://github.com/angr/angr/commits/feat/typehoon), though expect things to break.

**Comment by ltfish** [comment]
Type inference is partially implemented in the feat/typehoon branch. I plan to merge it in within the next few days. Just need to run more analysis on a larger scale and fix all crashes before merging that in.

**Comment by Ruturaj4** [comment]
@ltfish @rhelmot  Thanks so much for your replies. Is Typehoon the one implemented based on TIE paper?

**Comment by Ruturaj4** [comment]
I got it. Thanks btw.
