### ISSUE TITLE
Key error during CFGFast

### ISSUE THREAD

**Issue by blbi** [angr/angr#2094]
Hi, 
When i execute below code, i met `KeyError: 'sp'`
```python
proj = angr.Project('pdfinfo', auto_load_libs=True)
cfg = proj.analyses.CFGFast()
```
_pdfinfo_ binary is in _poppler-0.41.0_ 
I made this binary with this http://www.linuxfromscratch.org/blfs/view/7.9/general/poppler.html

what's the problem?

**Comment by ltfish** [comment]
Can you please post your compiled binary file so we can test on it?

**Comment by blbi** [comment]
This is the binary but it has library dependency so i think you'd better to compile through the [link](http://www.linuxfromscratch.org/blfs/view/7.9/general/poppler.html)
[pdfinfo.zip](https://github.com/angr/angr/files/4547328/pdfinfo.zip)

or this is static compile version of that 
[pdfinfo_static.zip](https://github.com/angr/angr/files/4547366/pdfinfo_static.zip)
but it doesn't show the same error
and `KeyError: 'sp'` error occurs only when the auto_load_libs option is true

**Comment by MNayer** [comment]
Same problem here, but with auto_load_libs=False. Here's the file that causes the problem:
[curl.tar.gz](https://github.com/angr/angr/files/4919494/curl.tar.gz)
It's the debian curl package (version 7.64.0-4+deb10u1) build with sbuild (build options "nostrip nocheck nodoc") on and for an amd64 machine.
