### ISSUE TITLE
breakpoints

### ISSUE THREAD

**Issue by ljun85** [angr/angr#210]
``` python
in[1]:s = b.factory.entry_state()
in[2]:def debug_func(state):
                 print "State %s is about to do a memory write!"
in[3]:s.inspect.b('mem_write', when=simuvex.BP_AFTER, action=debug_func)
out[3]:<BP after-action with conditions {}, no condition func, with action func>
```

Is **out[3]** as same as the expectations?

**Comment by rhelmot** [comment]
Yes! You've been returned a breakpoint object, which is, to my knowledge, totally useless to the end-user. Your breakpoint will now fire during actual emulation using the state `s`.

**Comment by rhelmot** [comment]
Also, in the future, when you're copying code from your terminal to a github issue, surround it with triple backticks and check the preview to make sure it appears correctly - the data inside the `<brackets>` was completely invisible until I edited your post! :)
