### ISSUE TITLE
angr usage question.

### ISSUE THREAD

**Issue by hdarwin** [angr/angr#212]
```
#include <stdlib.h>
int main(int argc, char *argv[]) {
	int value = atoi(argv[1]);
	value += 10;
	if (value == 'Z')
		asm("mov $0x41414141, %eax"); # 0x0804843f
	asm("mov $0x42424242, %eax");
}
```
```
#!/usr/bin/env python
import angr
p = angr.Project("./t")
arg1 = angr.claripy.BVS("arg1", 8*2)
st = p.factory.entry_state(args=["t", arg1])
pt = p.factory.path(st)
ex = p.surveyors.Explorer(start=pt, find=0x0804843f) # 0x0804843f <+52>:    mov    $0x41414141,%eax
ex.run()
print ex.found[0].state.se.any_str(arg1) # == 80
```
Like above code, if there are certain conditions to be met, we can use angr to find the expected input of argv[1] to reach 0x0804843f.

```
#include <stdlib.h>
int main(int argc, char *argv[]) {
	int value = atoi(argv[1]);
	value += 10;
	asm("mov $0x43434343, %eax"); # 0x08048439
}
```
This is simplified code from above, which I removed the conditional path. Yet, I still want to enforce the conditional check at a certain point. So I want to find out what argv[1] is required for 'value == 90' to be satisfied at location 0x08048439. I tried like below, but angr finds argv[1] to be 90 when we expect 80. Would there be a correct way to do this?

```
#!/usr/bin/env python
import angr
p = angr.Project("./t")
arg1 = angr.claripy.BVS("arg1", 8*2)
st = p.factory.entry_state(args=["t", arg1])
pt = p.factory.path(st)
ex = p.surveyors.Explorer(start=pt, find=0x08048439) # 0x08048439 <+46>:  mov    $0x43434343,%eax
ex.run()
ex.found[0].state.add_constraints(arg1 == 90) # this constraint answer me 90 not 80, 80 is what i want know
print ex.found[0].state.se.any_str(arg1)
```
this is my last try. if you think it is meaningless question just close issue please.

**Comment by rhelmot** [comment]
Hey! So you've stumbled onto a really important part of how angr works. Bitvectors, along with most other objects in angr are *immutable*, which means that they never change after being created. So, when you add the constraint that `arg1 == 90` and then ask for the value of arg1, of course it's 90! To accomplish what you're looking for, you need to extract the value of `value` from `ex.found[0].state` - it'll probably be `arg1 + 10` - and the constrain *that* to be equal to 90! Then, solving for arg1 will be asking for the value of arg1 in a state with the constraint `arg1 + 10 == 90`, so you should get 80.

This is probably the sort of thing we should document more explicitly!

**Comment by hdarwin** [comment]
thanks for you reply!
