### ISSUE TITLE
How to explore a state that can reach a certain basic block(by identifying the machine code or assembled code)

### ISSUE THREAD

**Issue by yinfeidi** [angr/angr#2129]
I want use angr to reach a basic block(know the address by dynamic gdb execution)，while the binary is usually compiled with PIE option, i cannot get the address of that BB. 
Is there an approach that can reach the BB by identifying the assembled code or machine code?

**Comment by rhelmot** [comment]
There is not. You should still be able to get the address of the basic block; you can either load the binary at the same address as gdb loads it (there are [tools for converting gdb output into loading directives](https://github.com/angr/cle/blob/master/tests/test_gdb.py)) or you can translate the addresses from gdb into addresses as they are linked in the executable, then add 0x400000 to convert them to angr's default PIC base.

**Comment by yinfeidi** [comment]
Thank you! 
It works.
