### ISSUE TITLE
getenv makes tracing fail

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#2140]
The problem is internally `env` has no order. And this will cause some trouble during tracing.(it iterates through all pointers)
My idea is to save `env` in `state.globals` during `state_entry` and then dynamically handle `setenv` and `getenv`. This will make tracing work on binary using these two functions.

However, before I do anything, I want to know your opinion.
@rhelmot

**Comment by rhelmot** [comment]
archr should synchronize the env precisely, including order. are you using archr?

**Comment by Kyle-Kyle** [comment]
yes. And it still cause desynchronization

**Comment by rhelmot** [comment]
I would cal this an archr bug then, since archr exports an env with an internal order, so the premise of this issue is supposed to be taken care of. Maybe it's an issue with extra environment variables like LD_PRELOAD and such being part of the traced environment but not the one that archr exports?

**Comment by Kyle-Kyle** [comment]
Make sense. I will deal with archr then.
