### ISSUE TITLE
Regression: "Hit a symbolic conditional operation."

### ISSUE THREAD

**Issue by SeyrN** [angr/angr#2149]
---
Hello,

It seems the "Gigantic refactor of SimState and SimEngines" (#1860) triggers a regression.

In attachment, you can find a script to reproduce the issue. Please let me know if you need further information.

Environment:
- linux (Arch Linux x86_64 5.6.11-arch1-1)
- python 3.8.2
- angr 8.20.1.17 (pip install)
- angr 8.19.10.30 (pip install)

Attachment: [script.zip](https://github.com/angr/angr/files/4629627/script.zip)

Best regards.

**Comment by rhelmot** [comment]
This was actually already fixed, in https://github.com/angr/angr/commit/71af12e966e710da3c7322220de26e3d9505bf3a! This is part of the new release 8.20.6.1.
