### ISSUE TITLE
Question about the path trace. it shows 'veritesting' in the output.

### ISSUE THREAD

**Issue by Chozmao** [angr/angr#215]
in my python script,i enable the veritesting technique in the path group.
```C
#include<stdio.h>
#include<stdlib.h>

int main(int i)
{
	int k=0;
	int j=0;
	if(i<5)
{
		switch(i)
	{
		case 0: 
			printf("hi it's Monday!\n");
			break;
		case 1:
			printf("hi it's Tuesday!\n");
			break;
		case 2:
			printf("hi it's Wednesday!\n");
			break;
		case 3:
			printf("hi it's Thursday!\n");
			break;
		default: printf("hi it's not a day!\n");
			break;
	}
	return 0;
}
	else 	
		for(i=0;i<10;i++)
	{
		if(j<3) 
		{
			k+=2;
			j+=1;
		}	
	}
	return k;
}
```
the output
```
<PathGroup with 1 active>
<Path with 0 runs (at 0x400526)>

<PathGroup with 6 active>
<Path with 3 runs (at 0x400400)>
<Path with 5 runs (at 0x400400)>
<Path with 5 runs (at 0x400400)>
<Path with 6 runs (at 0x400400)>
<Path with 3 runs (at 0x400400)>
<Path with 35 runs (at 0x4005c1)>

<PathGroup with 1 deadended, 5 active>
<Path with 4 runs (at 0x1000010)>
<Path with 6 runs (at 0x1000010)>
<Path with 6 runs (at 0x1000010)>
<Path with 7 runs (at 0x1000010)>
<Path with 4 runs (at 0x1000010)>

<PathGroup with 1 deadended, 5 active>
<Path with 5 runs (at 0x40057a)>
<Path with 7 runs (at 0x40056e)>
<Path with 7 runs (at 0x400586)>
<Path with 8 runs (at 0x400592)>
<Path with 5 runs (at 0x40059e)>

<PathGroup with 6 deadended>
how many steps you want to go further:0
address of deadended path0:<Path with 35 runs (at 0x4005c1)>
address of deadended path1:<Path with 5 runs (at 0x40057a)>
address of deadended path2:<Path with 7 runs (at 0x40056e)>
address of deadended path3:<Path with 7 runs (at 0x400586)>
address of deadended path4:<Path with 8 runs (at 0x400592)>
address of deadended path5:<Path with 5 runs (at 0x40059e)>
```
i use the command`for step in pg.deadended[5].trace:` `print step`, and there is only one deadended path(5) shows something special.
```
Veritesting
<SimIRSB 0x400594>
<SimIRSB 0x400400>
<SimProcedure puts>
```
i am not sure why it shows Veritesting instead of the trace of the path in the output. what's the meaning of it? is that because it merged the two paths(blue line in CFG) as one? which i have checked in the control flow graph that both paths will trigger the same `default case in C program`. But these two paths
were countered as two when i disabled the veritesting in path group. SO i got actually 7 deadended paths with disabling veritesting one more path than enabling veritesting. Is it correct?
![img_0651](https://cloud.githubusercontent.com/assets/20287349/18643765/c572b1b8-7ea6-11e6-889b-e2ca543ab54a.PNG)
thanks

**Comment by rhelmot** [comment]
> is that because it merged the two paths(blue line in CFG) as one?

Yes, that is exactly why it shows that string, and that is exactly the point of veritesting! Veritesting as a technique is meant to reduce state branching by identifying merge points and performing smart path merging. There is no reasonable string representation of exactly what veritesting does that we could put in the trace, since veritesting can operate on dozens of paths at once, merging paths that diverge wildly but reconvene at a merge point. Trying to stuff all that data in a string would be a nightmare!

You can read the original paper about veritesting [here](https://users.ece.cmu.edu/~dbrumley/pdf/Avgerinos%20et%20al._2014_Enhancing%20Symbolic%20Execution%20with%20Veritesting.pdf).

**Comment by Chozmao** [comment]
thanks for your explanation :-). @rhelmot.
