### ISSUE TITLE
Python logging not working when I import angr

### ISSUE THREAD

**Issue by poul1x** [angr/angr#2156]
---

I have several python modules, where I use python logging. When I import *angr* I can't see any logs printed on console. When I remove `import angr`, I can see logging output. What should I do to avoid angr's influence on my logging?

**Comment by poul1x** [comment]
```
root = logging.getLogger()
root.setLevel(logging.INFO)
```

**Comment by rhelmot** [comment]
If you run `logging.basicConfig()`, or set up any log formatters of your own, before `import angr` angr will not install any of its logging handlers.
