### ISSUE TITLE
Question about angr.kb.functions

### ISSUE THREAD

**Issue by frapik99** [angr/angr#216]
Hi,
I'm using angr on my VM and I'm interested to have angr.kb.functions for /bin/true but when i execute p.analysis.CFGFast() it takes ages. Is there a way to have angr.kb.functions populated without waiting the CFG to be created? Is there another way to access to the blocks of every internal function used by a project?

Thanks
F

**Comment by ltfish** [comment]
> Is there a way to have angr.kb.functions populated without waiting the CFG to be created?

I don't think so. Generally speaking, the notion of "functions" do not really exist in binaries. We have to recover the control flow graph before being able to tell you what functions there are in the binary.

... however, if there are symbols available with the binary you have (for example, a non-stripped version of an ELF binary), most functions in that binary will appear as symbols. You can get that information directly from cle (`project.loader.main_bin.symbols_by_addr`) without building a CFG.

**Comment by ltfish** [comment]
> when i execute p.analysis.CFGFast() it takes ages

That should not be the case. Make sure you are not loading any library with your project, otherwise CFGFast will try to recover the CFG of the entire library (which is probably libc in your case). The following code works:

```
proj = angr.Project("/bin/true", load_options={'auto_load_libs': False})
```

**Comment by frapik99** [comment]
Hi,
thanks for your answer. I tried with /bin/true as suggested and in few seconds the CFG was ready but when I tried with SSH I had the same problem. Can you try with SSH and let me know how long it does take please?

Thanks

**Comment by ltfish** [comment]
CFGFast shouldn't take too long to terminate. Can you please post your SSH binary?

**Comment by frapik99** [comment]
Hi,
this is the result on my box:
```
time python test.py 
WARNING | 2016-09-20 19:02:17,951 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
let's start
Done

real	21m48.119s
user	21m29.380s
sys	0m18.660s
```

As an example code I used:

```
import angr

proj = angr.Project("/usr/bin/ssh", load_options={'auto_load_libs': False})

print "let's start"
proj.analyses.CFGFast()

print "Done"
```

I have attached the ssh in the zip file.
[ssh.zip](https://github.com/angr/angr/files/483435/ssh.zip)

Thanks

**Comment by ltfish** [comment]
Reproduced. I think it's some sort of bug happened during the refinement stage. It was stuck at 56% for a very long time. Let me profile it and see why that happens.

Thanks for reporting!

**Comment by ltfish** [comment]
I think I know what's going on. I'll go and get lunch, and then fix it after that :-)

**Comment by frapik99** [comment]
Thanks,
I'm happy to retest it for you once you push the commit.

BTW, how did you checked the progress bar?

**Comment by ltfish** [comment]
Commit ddc014a fixes this issue.

> how did you checked the progress bar?

`proj.analyses.CFGFast(show_progressbar=True)` :-)

**Comment by frapik99** [comment]
Hi,
much better now :)

```
time python cfg.py 
WARNING | 2016-09-21 10:00:53,357 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
let's start
100% |#####################################| Elapsed Time: 0:01:25 Time: 0:01:25
Done

real	1m27.800s
user	1m25.716s
sys	0m2.068s
```

Thanks

**Comment by ltfish** [comment]
If you can, you should use Pypy - it is much faster.
