### ISSUE TITLE
ARM32: Unable to decode instruction

### ISSUE THREAD

**Issue by poul1x** [angr/angr#2164]
---

**Describe the bug.**

Unable to decode instruction `cmpcs`

![Capture](https://user-images.githubusercontent.com/31695750/83042665-953c4300-a04a-11ea-8706-140d58db7f62.PNG)

![Capture2](https://user-images.githubusercontent.com/31695750/83042669-966d7000-a04a-11ea-972a-149ada504e6f.PNG)

**Environment**

angr==8.20.1.7

**To Reproduce.**

Linux stretch ARM32 (armhf). Libc library

`strcmp` function
[libc.so.6.zip](https://github.com/angr/angr/files/4689897/libc.so.6.zip)

```python
    state_cmp = project.factory.blank_state(addr=cmp_addr)
    simulation = project.factory.simgr(state_cmp)
    simulation.step()
```

**Comment by ltfish** [comment]
Without debugging it: what’s `cmp_addr`? Make sure it’s odd since this is THUMB mode.

**Comment by poul1x** [comment]
cmp addr was `b682bdb8`. Of course, I don't remember image base

**Comment by poul1x** [comment]
Really strange. Now I have problems with decoding basic blocks of libc

**Comment by poul1x** [comment]
Yeah, no problems with decoding. Ida displays wrong address. Decoding `cmp_addr + 1` goes well

**Comment by poul1x** [comment]
My dynamic tool and IDA show me address is *even*. However it's odd. Fantastic

**Comment by poul1x** [comment]
How did you get that it's in THUMB mode?
It's compiled as `thumb2`

**Comment by ltfish** [comment]
> My dynamic tool and IDA show me address is even. However it's odd. Fantastic

Ref: https://stackoverflow.com/questions/37004954/function-address-in-arm-assembly-have-one-byte-offset

In THUMB mode (including `thumb2`, which I guess is just a variant of THUMB), addresses are odd since the last bit of an address is used to indicate the execution mode. angr chooses to stay loyal to the norm while IDA chooses to omit the last bit of the address and make all addresses even. They are both correct, I believe. As a user, you will need to do the conversion when switching between tools.

**Comment by poul1x** [comment]
In `thumb2` mode some addresses are odd, and some - even. `bx` instruction switches between `arm` and `thumb` modes. Now I don't have a plan, how to check the instruction is in `thumb` mode, because I always have even address and in some cases angr can not decode basic block at that address, and in other cases it gets wrong disassembly.

**Comment by ltfish** [comment]
> In thumb2 mode some addresses are odd, and some - even

I don't think this is correct. Ref: https://stackoverflow.com/questions/28669905/what-is-the-difference-between-the-arm-thumb-and-thumb-2-instruction-encodings

**Comment by poul1x** [comment]
Look at my exploration.
Instruction from main module:
```
# 1)
block = project.factory.block(0xB2E19AE4, num_inst=1)
# 2)
block
<Block for 0xb2e19ae4, 4 bytes>
# 3)
block.pp()
None
0xb2e19ae4:	cmp	r3, #0
# 4)
block.thumb
False
```
Instruction from libc:
```
# 1)
block = project.factory.block(0xB67F34E9, num_inst=1)
# 2)
block
<Block for 0xb67f34e9, 2 bytes>
# 3)
block.pp()
None
0xb67f34e9:	cmp	r1, #3
# 4)
block.thumb
True
```
Finally, I got conditions: 
* THUMB - odd address and 2-byte length
* ARM - even address and 4-byte length

Thanks, I've solved my problem!

**Comment by ltfish** [comment]
> THUMB - odd address and 2-byte length

Just saying, THUMB2 allows both 2-byte and 4-byte instructions.
