### ISSUE TITLE
CFGAccurate: nodes not normalized properly 

### ISSUE THREAD

**Issue by axt** [angr/angr#217]
After normalization, nodes returned by 'get_any_node()' are not normalized properly: if a node at address 'x' gets splitted by the normalization, calling 'get_any_node(x)' will return the unnormalized node, so the 'size', and 'instructions' are not reflecting that the node got splitted.

Just tested it with CFGAccurate, but the code is in CFGBase, so probably both cfg algos are affected.

@ltish I think you know about this, but I thought to open a ticket for it, since I would like to use it in a normalizedsteps exploration technique :-).

**Comment by ltfish** [comment]
Huh, this should be a solved issue - at least for CFGFast. Any test binary for me to test on?

**Comment by axt** [comment]
Attached a testcase. It only affects `CFGAccurate`
[test.zip](https://github.com/angr/angr/files/483802/test.zip)

**Comment by ltfish** [comment]
I looked into it. This is due to a bug in CFGAccurate that more than one `CFGNode` is created for the same SimRun key. Will push a fix soon after CI passes. Thanks for reporting!

**Comment by ltfish** [comment]
The issue should be resolved by commit 86e8aa2. Please check it out.

**Comment by axt** [comment]
Thanks, its working!
