### ISSUE TITLE
"isdigit - like" simprocedure implementation

### ISSUE THREAD

**Issue by poul1x** [angr/angr#2177]
---

Do you have sim procedures simulating behaviour of: `isalpha`, `isdigit`, `isalnum`, `isctrl` e.t.c. ?
If not, what is the best way to implement them?

**Comment by rhelmot** [comment]
At least in my tests, those functions compile down to a call to `__ctype_b_loc` and a table lookup from the return value, which is already implemented.

**Comment by poul1x** [comment]
I can not find them in SimProcedures

**Comment by rhelmot** [comment]
There is no simprocedure for isalpha etc because binaries compiled with those functions do not actually include a call to those functions. If you have a counterexample for this please show it to me.

**Comment by poul1x** [comment]
Ah, you mean, It's a compile time macro substitution? 
Now I'm compiling ARM binary without optimization. Call to *isdigit* is really inlined. But there's explicit call to *islower*, *isalnum*, e.t.c. May be compiling with `-O3` will help me.

[target.zip](https://github.com/angr/angr/files/4739981/target.zip)

<img src="https://user-images.githubusercontent.com/31695750/83944081-83f0f480-a809-11ea-8e34-d8dce55fb543.png" height="300" />

![image](https://user-images.githubusercontent.com/31695750/83944092-91a67a00-a809-11ea-8935-14c5511b1a37.png)

**Comment by rhelmot** [comment]
I see. In that case, it would be a good idea to implement those simprocedures. In that case, you could either implement them in a locale-aware way that looks up the ctype table, or you could implement them for a specific locale, which would probably be more efficient.

**Comment by poul1x** [comment]
Ok, do you have some manuals/samples how to do that?

**Comment by rhelmot** [comment]
https://docs.angr.io/extending-angr/simprocedures

for the code where the ctype table is initialized, that's here: https://github.com/angr/angr/blob/master/angr/procedures/glibc/__libc_start_main.py

**Comment by poul1x** [comment]
Ok, I'll try to do that
