### ISSUE TITLE
CFGAccurate: SimProcedures not marked

### ISSUE THREAD

**Issue by axt** [angr/angr#218]
If I hook some address, CFGAccurate doesn't marks it as a SimProcedure. 
CFGFast works fine. See the attached example.

[test.zip](https://github.com/angr/angr/files/483990/test.zip)

**Comment by ltfish** [comment]
Must be a bug. I'll take a look.

**Comment by ltfish** [comment]
See commit 13c12a3. This is a corner case in `CFGAccurate._create_cfgnode()`. Clearly I wasn't expecting anyone will manually create `ReturnUnconstrained` SimProcedures.

**Comment by ltfish** [comment]
Oh it should be resolved by that commit.

**Comment by axt** [comment]
Seems working! Thanks

**Comment by ltfish** [comment]
No problem!
