### ISSUE TITLE
Meet issue when i isntall angr

### ISSUE THREAD

**Issue by testworld** [angr/angr#22]
Installing collected packages: pyvex, claripy, simuvex, cle, decorator, pyelftools, pycparser, cffi, angr-z3, dpkt-fix, pefile, idalink, rpyc, plumbum
  Running setup.py install for pyvex
    Building libVEX
    error: vex: Not a directory
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/ocelot/axx/build/pyvex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-BoRmq0-record/install-record.txt:
    running install

running build

Building libVEX

error: vex: Not a directory

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/ocelot/axx/build/pyvex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-BoRmq0-record/install-record.txt failed with error code 1
Storing complete log in /home/ocelot/.pip/pip.log

**Comment by testworld** [comment]
fixed this by download libvex，but meet new issue when install pyvex,
managed --record /tmp/pip-V1rqG6-record/install-record.txt:
    running install

running build

Building libVEX

EXTRA_CFLAGS="-fPIC -w" make -f Makefile-gcc

make[1]: Entering directory `/home/ocelot/axx/build/build/pyvex/vex-dev'

make[1]: Nothing to be done for `all'.

make[1]: Leaving directory `/home/ocelot/axx/build/build/pyvex/vex-dev'

Building pyvex-static

error: pyvex_c: No such file or directory

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/ocelot/axx/build/build/pyvex/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-V1rqG6-record/install-record.txt failed with error code 1


seems to be can not find pyvex_c,but i already have pyvex_c folder

**Comment by rhelmot** [comment]
Can you tell us the operating system and processor you're using, and whether you're working in a virtualenv, in addition to the exact command you used to try to run the install?

**Comment by testworld** [comment]
tks for you reply,1)i working in ubuntu12.0.4  2)i use virtualenv 3) i use command sudo apt-get install python-dev libffi-dev build-essential virtualenvwrapper,and then mkvirtualenv angr ,and then pip install angr

**Comment by zardus** [comment]
I am not sure of the exact error you're running into, but 12.04 is generally not supported. If you get through this, you'll run into an issue compiling Z3. Could you try the install on a 14.04 box, or a newer release of any other distro? That should work.

**Comment by testworld** [comment]
works on 14,tks so much
