### ISSUE TITLE
Question: How to analyse a shared object

### ISSUE THREAD

**Issue by frapik99** [angr/angr#220]
Hi,
is it possible to load a shared object and analyse its exported function? How can I do it? I was thinking to just create a simple C program that load the .so that I need an let angr to do the rest.

Thanks

**Comment by axt** [comment]
I'm doing this to load shared libraries: 
```
project = angr.Project(bname, load_options={'auto_load_libs':False, 'main_opts': {'custom_base_addr': 0x0}})
```

**Comment by gitttt** [comment]
@axt And for dlls?

**Comment by frapik99** [comment]
Hi all,
I think the right approach would be something like:

```
import angr

project = angr.Project("/bin/true")

for i,l in project.loader.shared_objects.iteritems():
	print i


for i, s in l.symbols_by_addr.iteritems():
	print s.name
```

**Comment by rhelmot** [comment]
Hey! Sorry for letting this one drop. The code axt posted is correct as the best way to load a shared library, and the code you posted is correct for getting the symbols from a binary.

gittt: dlls are just shared objects for windows, so working with them should be the same, barring bugs in our loader :)

**Comment by frapik99** [comment]
Hi,
old thread but I still have the same problem. If i try to a load .so I have the following messages:

```
| cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
angr.call_stack | Returning to an unexpected address 0x0
angr.call_stack | Returning to an unexpected address 0x0
```

I'm using Ubuntu on a 64 bit arch.

Thanks
