### ISSUE TITLE
running symbolic execution with simfile

### ISSUE THREAD

**Issue by alikmli** [angr/angr#2211]
hi 
i have some problem with running symbolic execution with symbolic variables throw simfile in angr.
for example in sample code below:
```
#include <stdlib.h>
#include <stdio.h>


int sum(int x,int y){
	if(x==0 || y==0)
		return -2;
	int result=x+y;
	if(result >100 || result <0)
		return -1;
	return result;
}


void main(){
	printf("WelCome ******\n");
	int x;
	int y;
        printf("Enter two number: ");
        scanf("%d",&x);
        scanf("%d",&y);	
	int result=sum(x,y);

	if(result == -2)
		printf("zero is not premitted");
	else if (result == -1)
		printf("unbounded value!!");
	else if( result == 12)
		printf("your lucky\n");
	else
		printf("Go away\n");
}
```
i want to track symbolic variables in angr but i don't know how?! 
so i create two BVS and a simfile for two scanf in code as : 

```
proj=angr.Project('sum',load_options={'auto_load_libs':False})

x=claripy.BVS('x',32)

y=claripy.BVS('y',32)

simfile=angr.SimFileStream('/dev/stdin',content=x.concat(y))

entry=proj.factory.full_init_state(stdin=simfile)

simgr=proj.factory.simulation_manager(entry)

simgr.explore(find=lambda s:b'your' in s.posix.dumps(1))


```
but it doesn't work!! 

how can i  track symbolic vars in angr?
or how can i  run semi concrete  run with chosen variables in angr?

can anyone help me.

Thanks so much.

**Comment by emrahsariboz** [comment]
What is your filename?

**Comment by alikmli** [comment]
filename is sum.cpp

**Comment by alikmli** [comment]
when i use :
simgr.found[0].solver.eval(x,caset_to=bytes)
simgr.found[0].solver.eval(y,caset_to=bytes)

i get wrong values for x and y.

**Comment by emrahsariboz** [comment]
What is the error are you getting?

**Comment by alikmli** [comment]
there is no error.
actually it found a state.
but when i use for example:
simgr.found[0].solver.eval(x,cast_to=bytes)
i got a wrong result.(+11/0x...)

**Comment by alikmli** [comment]
there is no error.
actually it found a state.
but when i use for example:
simgr.found[0].solver.eval(x,cast_to=bytes)
i get a wrong result.(+11/0x...)
