### ISSUE TITLE
Memory leak when perform state explore in a loop

### ISSUE THREAD

**Issue by 1wc** [angr/angr#2222]
---

Hello! I use latest versions of angr to perform symbolic execution on a binary, but it suffers from memory leak.

1. I load the binary by `self._proj = angr.Project(binpath, load_options={'auto_load_libs': False}, use_sim_procedures=True)`
2. I make a symbolic argument as `simargv = claripy.BVS("tainted_argv", 0x10)` and use it to init a entry state. I also add some items to entry state's globals dict
```python
initial_state = self._proj.factory.entry_state(args=[binpath, option, simargv], add_options=[angr.options.LAZY_SOLVES])
initial_state.globals['param_index'] = 2
```
3. I init a sim_manager with the initial state and explore !!
```python
simgr = self._proj.factory.simulation_manager(initial_state)
simgr.explore(find=0x403081)
```
4. 2 & 3 are written in a function. When the simgr complete, the function return and execute again in a loop. As you can see, when the exploration of simgr succeed and the function returned, I wish the gc would free the used memory of that simgr. But after some time the memory is exhausted.
What can I do instead of restart the script？

Thanks

**Comment by 1wc** [comment]
A mini case to reproduce this issue is:
```python
import angr
import claripy

def test_angr(proj, option):
	argv1 = claripy.BVS("argv1", 0x10)
	initial_state = proj.factory.entry_state(args=["/path/to/bin", option, argv1], add_options=[angr.options.LAZY_SOLVES])
	simgr = proj.factory.simulation_manager(initial_state)
	simgr.explore(find = addr)

if __name__ == "__main__":
	proj = angr.Project("/home/liwc/base64", load_options={'auto_load_libs': False})
	
	test_angr(proj, "-f")
	test_angr(proj, "-g")
```
When the first test_angr finished, how can I free memory generated by `simgr.explore` ?

**Comment by ltfish** [comment]
Some reasons that I observed in the past (ranked from the most probable to the least probable):

- Z3 tends to cause serious heap fragmentation. If that is the case, recreating the entire Z3 solver (there is an API in Z3 to drop the solver completely) sometimes fixes the issue, but not always. The best way out of it is to restart the entire process. By the way, this is one of the reasons why we want to move to a multi-processing model where Z3 is put into a separate process.

- `claripy` has quite a few internal caches, especially the one that caches concrete BVVs globally (across states and objects). I don't remember where it is in claripy (@zardus ?), but I suspect that if you have a loop in your binary that iterates for millions of times and increments a concrete BVV by one at a time, you may fill up that cache.

- angr has an internal block cache for the most recent lifted 50000 blocks. See `VEXLifter._block_cache`. This is almost never the problem though.

The best way to tell is to use a Python-based memory profiler and analyze the Python heap usage. If you have a low Python heap usage but a high memory usage, Z3 is very likely to be the culprit.

**Comment by 1wc** [comment]
Thank you for your advice!
I investigated on this issue with the help of `memory_profiler` and as you say, it had a low Python heap usage but a high memory usage. Z3 is actully to be the culprit.
However, I observe that angr has a sim_option `DOWNSIZE_Z3` to do some cleanup for successors in function `_finalize`(https://github.com/angr/angr/blob/3b598e514fccb2931c7cb7ba844cf732190459cc/angr/engines/successors.py#L405), but it seems never to be called. Because I don't need to solve the constraints, I hack it and call `s.downsize()` manully. It partially resolve this issue.
