### ISSUE TITLE
Normalization and keep_state

### ISSUE THREAD

**Issue by axt** [angr/angr#223]
Some of the analyses (e.g: DDG, VFG) depend on a CFG which was generated with `keep_state=True`. 

But it seems to me, that normalization 'breaks' the final state property of the nodes. So I think it breaks the analyses depending on that.

To demonstrate this, here is a very simple example. Check the final state of the node `0x8048402`. In the normalized case, its missing. 

`normalize=False`:
![unnorm](https://cloud.githubusercontent.com/assets/759365/18810996/d0970092-82a4-11e6-95d4-d0324b77b2c2.png)

`normalize=True`:
![norm](https://cloud.githubusercontent.com/assets/759365/18810999/dc179bac-82a4-11e6-95f8-7a33e8c88a66.png)

**Comment by ltfish** [comment]
Good catch!

I didn't think of this problem before. Now obviously `normalize()` should handle those cases when a node is broken up into two.

I'm making some big changes on VFG right now, so I will embed a fix for this issue after I commit my other VFG changes.

**Comment by axt** [comment]
I've debugged this for a while before I realized what the real problem is, because I had a wrong concept at first about what 'fastpath mode' means :-). 

Now I have a better imagination about it, but may I ask you to explain it shortly, so I could have a more exact picture about it?

**Comment by axt** [comment]
Oh, and since you said you are touching VFG. I don't know if you saw this issue: https://github.com/angr/angr/issues/205 . I think its just 3 extra lines of code ;-).

**Comment by ltfish** [comment]
> Oh, and since you said you are touching VFG. I don't know if you saw this issue: #205 . I think its just 3 extra lines of code ;-).

That one has been solved locally :-)

**Comment by ltfish** [comment]
`fastpath` is basically a mode of concrete execution that allows the existence of symbolic values, but it will never try to push those symbolic values into the SMT solver backend. In `symbolic` mode, we query a solver for solutions, but in `fastpath` mode, we never query the solver - which is why it's _fast_.
