### ISSUE TITLE
Allow disabling simplification

### ISSUE THREAD

**Issue by Luluno01** [angr/angr#2236]
---

**Is your feature request related to a problem? Please describe.**

I would sometimes like to preserve the structure of some expressions without simplifying them since that would destroy the original structure and discard some useful information.

**Describe the solution you would like.**

I want Angr to allow me to 1) completely turn off expression simplification, or 2) turn off expression simplification for some "steps", or 3) "freeze" an expression to protect it from being simplified. Besides, 4) expression produced when simplification is turned off should be freezed to avoid further simplification.

**Please include a sample of what *should* work if this feature is implemented.**

```Python
# Completely disable
claripy.set_allow_simplification(False)

# Temporarily disable
simgr.run(allow_simplification=False)
simgr.step(allow_simplification=False)

# Selective disable
claripy.set_allow_simplification(False)
simgr.step()
claripy.set_allow_simplification(True)
simgr.step()

# Freeze an expression
x = claripy.BVS('x', 32)
expr = x & 0x1f
protectedExpr = expr.freeze()
print(protectedExpr & 0xff)  # Should print something like "x & 0x1f & 0xff"
```

**Describe alternatives you have considered.**

Bypassing `SimplificationManager` manually by modifying source code.

**Additional context.**

N/A

**Comment by rhelmot** [comment]
The "sanctioned" way to do this is to make your own class that implements the SimplificationManager interface and set `claripy.simplifications.simpleton` (short for simplification singleton) to an instance of it.

I _think_ you can also use the annotations interface to produce this effect. If you add an annotation which is not allowed to be relocated or eliminated, it should prevent simplification - see operations.py:53

**Comment by Luluno01** [comment]
Great thanks to you! Your helpful suggestions saved me from ugly workaround.
