### ISSUE TITLE
How to avoid <BV32 SignExt(16, x)> from being "simplified" to <BV32 x[15:15] .. x[15:15] .. ... .. x>

### ISSUE THREAD

**Issue by Luluno01** [angr/angr#2241]
---

I got `<BV32 SignExt(16, x)>` as `state.inspect.reg_write_expr` but got `<BV32 x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x[15:15] .. x>` as the actual value written. How to avoid this? `<BV32 SignExt(16, x)>` is preferable since it is more concise to be processed.

I stepped into Angr's source code and did not find any switch to turn such "simplification" off.

**Comment by ltfish** [comment]
Remove state options `SIMPLIFY_MEMORY_WRITES` and `SIMPLIFY_REGISTER_WRITES` from your state, or create your initial state with `remove_options=angr.sim_options.simplification`. However, there might still be places where we call into Z3 to simplify expressions that are not controlled by the above two state options. If you find these cases, report them as bugs.

**Comment by Luluno01** [comment]
`remove_options=angr.sim_options.simplification` works great! Very much obliged!
