### ISSUE TITLE
No bytes in memory for block 

### ISSUE THREAD

**Issue by TylerKann** [angr/angr#2245]
I have a function named test. I want to look at the function via angr. So what I think I want is : 
`state = proj.factory.call_state(addr = 0x64A)   `  (since that is what IDA is telling me).  However, when I try state.step()  (I am trying to navigate to the return, it tells me 
` no bytes in memory for block starting at 0x64A`
can anyone tell me why this error is occurring, and maybe how I can fix it? I am new to angr. Thanks! 

![image](https://user-images.githubusercontent.com/43652037/86850529-a70ffd80-c06e-11ea-8c17-8e378c4b6e7c.png)

**Comment by ltfish** [comment]
By default, angr loads PIE at offset 0x400000. So this block is at 0x40064a, unless you mapped the binary in angr to somewhere else.

**Comment by TylerKann** [comment]
Thanks a lot @ltfish
