### ISSUE TITLE
Block size is incorrectly reported as 0 for some non-zero sized blocks in native interface

### ISSUE THREAD

**Issue by dnivra** [angr/angr#2246]
**Describe the bug.**

The size of the block is incorrectly reported as 0 for some blocks in the block hook in `sim_unicorn.cpp`. An example of this is the block starting at `0x7a5eda` in [wyvern binary from CSAW 2015](https://github.com/angr/angr-doc/blob/master/examples/csaw_wyvern/wyvern) (assuming default load base addresses of all images as done in [wyvern solver](https://github.com/angr/angr-doc/blob/master/examples/csaw_wyvern/solve.py)).

However, I'm not sure if this a bug in unicorn. I emulated the block's bytes alone in unicorn(the same version as the one installed in the virtual environment) and the block size was correctly reported. I have attached an example C code emulating this block standalone in unicorn where the block size is reported correctly in the block hook(instructions for building and running this included below).

**Environment Information.**

Date: 2020-07-08 00:08:46.354635
Running in virtual environment at $HOME/.virtualenvs/angr-unicorn-bug
Platform: linux-x86_64
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]
######## angr #########
Python found it in $HOME/tmp/angr-dev/angr/angr
Pip version angr 8.20.7.6
Git info:
	Current commit ee2949e10cf42ae3077fe966fb1fdea1652005c3 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in $HOME/tmp/angr-dev/ailment/ailment
Pip version ailment 8.20.7.6
Git info:
	Current commit 3490c152766fe7df04dfa922fa58c03166676944 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in $HOME/tmp/angr-dev/cle/cle
Pip version cle 8.20.7.6
Git info:
	Current commit 70d40091c74b9125df223ed13ea5e43e5dd29667 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in $HOME/tmp/angr-dev/pyvex/pyvex
Pip version pyvex 8.20.7.6
Git info:
	Current commit 41d0582d0fcfa48d127eb66785495624b8da6328 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in $HOME/tmp/angr-dev/claripy/claripy
Pip version claripy 8.20.7.6
Git info:
	Current commit 6975d5b3e5cfbef05914df371358b21dd6fd7e8d from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in $HOME/tmp/angr-dev/archinfo/archinfo
Pip version archinfo 8.20.7.6
Git info:
	Current commit c48e4b40a6a1f7edab6bd0597fe3d5dda1d73e62 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in $HOME/.virtualenvs/angr-unicorn-bug/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.8.0
Couldn't find git info
######## unicorn #########
Python found it in $HOME/.virtualenvs/angr-unicorn-bug/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '$HOME/tmp/angr-dev/angr/angr/lib/angr_native.so', handle 361f290 at 0x7fc1f244b278>
unicorn: <CDLL '$HOME/.virtualenvs/angr-unicorn-bug/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2d54530 at 0x7fc1f8e3ee80>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fc1f9e45898>
z3: <CDLL '$HOME/.virtualenvs/angr-unicorn-bug/lib/python3.6/site-packages/z3/lib/libz3.so', handle 2fd8620 at 0x7fc1f5c0ccf8>

**To Reproduce.**

[The wyvern example solver from angr-doc/examples](https://github.com/angr/angr-doc/tree/master/examples/csaw_wyvern). A block ~where~ whose size is reported incorrectly in `hook_block` is the block starting at `0x7a5eda`.

**Additional context.**

Here are the instructions for emulating the same block standalone within unicorn. Within the angr virtual environment, extract the archive, run `make` to build the C source and `make run` to run the emulation.

[unicorn-sample.zip](https://github.com/angr/angr/files/4889083/unicorn-sample.zip)

**Comment by rhelmot** [comment]
This is known, and mentioned in sim_unicorn.cpp with a link to https://github.com/unicorn-engine/unicorn/issues/874. IMO it is a bug in unicorn, though I doubt quynh would accept a patch to change the behavior.

**Comment by dnivra** [comment]
I just realized the sample code I shared isn't correct: apparently angr splits the block into two and so I was actually not emulating the entire block but only first part. But, the size of both combined is less than MAX_BB_SIZE value in sim_unicorn so is it still related to the same issue(or is even an issue) in unicorn? I tried emulating both blocks together in unicorn and hook_block does get the correct block size. Is the bug triggered under very specific circumstances which I'm not recreating when emulating standalone?

**Comment by rhelmot** [comment]
honestly I have no idea. there may be an instruction count limit in addition to the byte count limit. It would help if you could post the disassembly of the problematic blocks.

**Comment by dnivra** [comment]
The two blocks are from `libstdc++`(and not the `wyvern` binary itself) on Ubuntu 18.04.4 64 bit(DEB package with .so file: https://packages.ubuntu.com/bionic/libstdc++6) starting at offset `0xa5eda`. Here's the disassembly of the two blocks(total instruction count 56; total byte count: 576):

Block 1(instruction count: 39; byte count: 399)
```
0x7a5eda:       lea     rax, [rip + 0x2db9f7]
0x7a5ee1:       mov     edx, 1
0x7a5ee6:       lea     rsi, [rip + 0x2e0233]
0x7a5eed:       lea     rdi, [rip + 0x2e0a0c]
0x7a5ef4:       mov     dword ptr [rip + 0x2e022a], 1
0x7a5efe:       mov     qword ptr [rip + 0x2e0227], 0
0x7a5f09:       add     rax, 0x10
0x7a5f0d:       mov     qword ptr [rip + 0x2e020c], rax
0x7a5f14:       mov     qword ptr [rip + 0x2e0219], 0
0x7a5f1f:       mov     qword ptr [rip + 0x2e0216], 0
0x7a5f2a:       mov     qword ptr [rip + 0x2e0213], 0
0x7a5f35:       mov     qword ptr [rip + 0x2e0210], 0
0x7a5f40:       mov     qword ptr [rip + 0x2e020d], 0
0x7a5f4b:       mov     qword ptr [rip + 0x2e020a], 0
0x7a5f56:       mov     qword ptr [rip + 0x2e0207], 0
0x7a5f61:       mov     qword ptr [rip + 0x2e0204], 0
0x7a5f6c:       mov     qword ptr [rip + 0x2e0201], 0
0x7a5f77:       mov     qword ptr [rip + 0x2e01fe], 0
0x7a5f82:       mov     qword ptr [rip + 0x2e01fb], 0
0x7a5f8d:       mov     qword ptr [rip + 0x2e01f8], 0
0x7a5f98:       mov     qword ptr [rip + 0x2e01f5], 0
0x7a5fa3:       mov     qword ptr [rip + 0x2e01f2], 0
0x7a5fae:       mov     qword ptr [rip + 0x2e01ef], 0
0x7a5fb9:       mov     qword ptr [rip + 0x2e01ec], 0
0x7a5fc4:       mov     qword ptr [rip + 0x2e01e9], 0
0x7a5fcf:       mov     qword ptr [rip + 0x2e01e6], 0
0x7a5fda:       mov     qword ptr [rip + 0x2e01e3], 0
0x7a5fe5:       mov     qword ptr [rip + 0x2e01e0], 0
0x7a5ff0:       mov     qword ptr [rip + 0x2e01dd], 0
0x7a5ffb:       mov     qword ptr [rip + 0x2e01da], 0
0x7a6006:       mov     qword ptr [rip + 0x2e01d7], 0
0x7a6011:       mov     qword ptr [rip + 0x2e01d4], 0
0x7a601c:       mov     qword ptr [rip + 0x2e01d1], 0
0x7a6027:       mov     qword ptr [rip + 0x2e01ce], 0
0x7a6032:       mov     qword ptr [rip + 0x2e01cb], 0
0x7a603d:       mov     qword ptr [rip + 0x2e01c8], 0
0x7a6048:       mov     qword ptr [rip + 0x2e01c5], 0
0x7a6053:       mov     qword ptr [rip + 0x2e01c2], 0
0x7a605e:       mov     qword ptr [rip + 0x2e01bf], 0
```

Block 2(instruction count: 17; byte count: 177)
```
0x7a6069:       mov     qword ptr [rip + 0x2e01bc], 0
0x7a6074:       mov     qword ptr [rip + 0x2e01b9], 0
0x7a607f:       mov     qword ptr [rip + 0x2e01b6], 0
0x7a608a:       mov     qword ptr [rip + 0x2e01b3], 0
0x7a6095:       mov     qword ptr [rip + 0x2e01b0], 0
0x7a60a0:       mov     qword ptr [rip + 0x2e01ad], 0
0x7a60ab:       mov     qword ptr [rip + 0x2e01aa], 0
0x7a60b6:       mov     qword ptr [rip + 0x2e01a7], 0
0x7a60c1:       mov     qword ptr [rip + 0x2e01a4], 0
0x7a60cc:       mov     qword ptr [rip + 0x2e01a1], 0
0x7a60d7:       mov     qword ptr [rip + 0x2e019e], 0
0x7a60e2:       mov     qword ptr [rip + 0x2e019b], 0
0x7a60ed:       mov     qword ptr [rip + 0x2e0198], 0
0x7a60f8:       mov     qword ptr [rip + 0x2e0195], 0
0x7a6103:       mov     qword ptr [rip + 0x2e0192], 0
0x7a610e:       mov     byte ptr [rip + 0x2e0193], 0
0x7a6115:       call    0x78b5a0
```
