### ISSUE TITLE
Handling Arithmetic Operation on NULL scratch.ins_addr

### ISSUE THREAD

**Issue by marcusp46** [angr/angr#225]
Greetings,

When running CFGAccurate with default configurations options and angr.Project() as :

`b_libc = angr.Project("/lib/x86_64-linux-gnu/libc.so.6",load_options {'auto_load_libs':False},use_sim_procedures=True)`

I get the following error in angr/factory.py at line 103:

`--> 103                     block_opts['max_size'] -= new_ip - addr`
`TypeError: unsupported operand type(s) for -=: 'NoneType' and 'long'`

Can you recommend a safe way to handle this?  Thanks :)

Marcus

**Comment by ltfish** [comment]
This issue was reported previously, but I couldn't reproduce it locally. Can you please give me the binary to reproduce it?

I believe it is a bug in angr.

**Comment by marcusp46** [comment]
Sure thing.

**Comment by ltfish** [comment]
Thanks in advance!

**Comment by marcusp46** [comment]
I am going to modify line 102 from :
` if 'max_size' in block_opts:`
to
 `if 'max_size' in block_opts and block_opts['max_size'] is not None:`

I am scanning the rest of the code base to see if this attribute is critical.  Off the top of your head, is this an important attribute?
