### ISSUE TITLE
Debugging Angr issues

### ISSUE THREAD

**Issue by afjoseph** [angr/angr#2267]
Hey guys, I love Angr and the project is very useful. Many times, however, I find that the binary is hanging and doing calculations that I really don't know where they are. Maybe Angr got stumped analyzing a libc function and maybe it had an issue not locating a dynamic library or maybe the function itself is too complicated and leads to a path explosion. Is there a way to know what Angr is doing at any given time? (maybe verbose logging?) From the jedis the use Angr all the time, I would love to know your strategy for debugging the question "what is Angr doing now?" and "how can I help it?"

If one can give me some guidance, I might be able to make a PR that has a "summary" function of where the hotspots are, what it's doing, why is it doing too much, etc. This will be a good first PR, I reckon. 

Many thanks for this fantastic project
 
P.S: I tried setting `logging.getLogger('angr.manager').setLevel(logging.DEBUG)`, but it just prints: `Stepping active of <SimulationManager with 3 active>`. Is there a way to make it print "where" it is working now? (which address/function)

**Comment by ltfish** [comment]
I tend to manually patch `sim_manager.py` and make it print out (or `logging.debug()`) `self.active` at every single step. This way I get to know where it's executing and where it gets stuck. SimulationManager was doing that before the giant refactor, but the related code was removed during the refactor, and no one cared enough to add it back in.

In general, I agree that it would be nice if there were better ways to tell what angr is currently doing and where it spends most time.

**Comment by rhelmot** [comment]
`logging.getLogger('angr.engines.engine').setLevel('INFO')`

**Comment by afjoseph** [comment]
Closing this since a combination of this solved my question:

```
logging.getLogger('angr.manager').setLevel('DEBUG')
logging.getLogger('angr.engines.engine').setLevel('DEBUG')
```

I'll work on a `simgr.summary(callback)` function where the callback can tell you what's happening now and provides the state there as well, but I don't wanna keep an issue open until that's done.

Many thanks, guys
