### ISSUE TITLE
explorer/path group find addr in first block problem

### ISSUE THREAD

**Issue by bannsec** [angr/angr#227]
I am first setting up a basic call to a program (entry_state in this case). Then, I attempt to break on some addr in the first "step". This break point is never hit. Looking through execution, it appears that the check for if you should break is performed after the first step.

Question two of this is: is it possible to break at a specific address that isn't the beginning of a block?

**Comment by ltfish** [comment]
> Looking through execution, it appears that the check for if you should break is performed after the first step.

That should be a bug (in design), and it should be fixed. PR welcome!

> is it possible to break at a specific address that isn't the beginning of a block?

Yes. `Path.step()` takes `max_size` and `num_inst`, which you can use to limit how many bytes/instructions you want to execute in the current step.

Take a look at the docstring of `Path.step()`.

**Comment by zardus** [comment]
The current check in explore *should* check for any address, not just the first one. That also sounds like a bug...
