### ISSUE TITLE
Incorrect symbolic memory addressing

### ISSUE THREAD

**Issue by Luluno01** [angr/angr#2274]
---

**Describe the bug.**

See "To Reproduce" section below.

**Environment Information.**

> angr environment report
> =============================   
> Date: 2020-07-24 01:10:23.897503
> Running in virtual environment at ?:\virtualenv\angr
> Platform: win-amd64
> Python version: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
> ######## angr #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\angr
> Pip version angr 8.20.7.6
> Couldn't find git info
> ######## ailment #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\ailment
> Pip version ailment 8.20.7.6
> Couldn't find git info
> ######## cle #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\cle
> Pip version cle 8.20.7.6
> Couldn't find git info
> ######## pyvex #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\pyvex
> Pip version pyvex 8.20.7.6
> Couldn't find git info
> ######## claripy #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\claripy
> Pip version claripy 8.20.7.6
> Couldn't find git info
> ######## archinfo #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\archinfo
> Pip version archinfo 8.20.7.6
> Couldn't find git info
> ######## z3 #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\z3
> Pip version z3-solver 4.8.8.0
> Couldn't find git info
> ######## unicorn #########
> Python found it in ?:\virtualenv\angr\lib\site-packages\unicorn
> Pip version unicorn 1.0.2rc4
> Couldn't find git info
> ######### Native Module Info ##########
> angr: <CDLL '?:\virtualenv\angr\lib\site-packages\angr\lib\angr_native.dll', handle 7ff857800000 at 0x1056d8ae100>
> unicorn: <CDLL '?:\virtualenv\angr\lib\site-packages\unicorn\lib\unicorn.dll', handle 7ffff0100000 at 0x1056b852df0>
> pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000001056B5F1C70>
> z3: <CDLL '?:\virtualenv\angr\Lib\site-packages\z3\lib\libz3.dll', handle 7fffeed60000 at 0x1056c747a60>

**To Reproduce.**

```Python
bv64 = claripy.BVS('x', 64)
# Symbolic memory addressing is broken
state.mem[state.regs.sp + 0x20].qword = bv64
print(state.mem[state.regs.sp + 0x20].dword)
# <uint32_t <BV32 Reverse(x_15_64[7:0] .. Reverse(x_15_64)[55:32])> at r13_init_13_32 + 0x20>
# Correct but <uint32_t <BV32 x_15_64[31:0]> at r13_init_13_32 + 0x20> is preferable
print(state.mem[state.regs.sp + 0x24].dword)
# <uint32_t <BV32 mem_3_16_32{UNINITIALIZED}> at r13_init_13_32 + 0x24>
# Incorrect, expecting <uint32_t <BV32 x_15_64[63:32]> at r13_init_13_32 + 0x20> at r13_init_13_32 + 0x24>

# Concrete memory addressing works fine
state.mem[0x00].qword = bv64
print(state.mem[0x00].dword)
# <uint32_t <BV32 x_15_64[31:0]> at 0x0>
# Correct
print(state.mem[0x04].dword)
# <uint32_t <BV32 x_15_64[63:32]> at 0x4>
# Correct
```

**Additional context.**

**Comment by rhelmot** [comment]
Fixed. This issue actually had nothing to do with symbolic memory addressing, but rather address space wrapping, since z3's first instinct on concretizing a fully symbolic value is to set it to -1 for some reason.
