### ISSUE TITLE
Callback on symbolic memory write?

### ISSUE THREAD

**Issue by afjoseph** [angr/angr#2283]
Is there a callback for symbolic memory writes?

Here's some context: I have a call to `fgets` in the program and I hooked it using `proj.hook(0x401060, angr.SIM_PROCEDURES['libc']['fgets']())`. The state looks like this:

```
buff_chars = [claripy.BVS('buff_%d' % i, 8) for i in range(1024)]
buff = claripy.Concat(*buff_chars + [claripy.BVV(b'\n')])
state = proj.factory.entry_state(
    addr=0x401186,
    stdin=angr.SimFile('/dev/stdin', content=buff),
)
```

The idea is that I'd like to see if `fgets` is **actually** using `buff` as a symbolic value. I tried to `simgr.active[0].memory.hex_dump(0x0, 0x4000)` after a couple of `simgr.step()` after `fgets` and couldn't find any symbolic writes.

Here's the assembly I'm working with (nothing special):

```
00401186  55                 push    rbp {__saved_rbp}
00401187  4889e5             mov     rbp, rsp {__saved_rbp}
0040118a  4883ec20           sub     rsp, 0x20
🔖0040118e  897dec             mov     dword [rbp-0x14 {var_1c}], edi
00401191  488975e0           mov     qword [rbp-0x20 {var_28}], rsi
00401195  bf00040000         mov     edi, 0x400
0040119a  e8f1feffff         call    malloc
0040119f  488945f8           mov     qword [rbp-0x8 {buff}], rax
004011a3  488b15e62e0000     mov     rdx, qword [rel stdin]
004011aa  488b45f8           mov     rax, qword [rbp-0x8 {buff}]
004011ae  be00040000         mov     esi, 0x400
004011b3  4889c7             mov     rdi, rax
004011b6  e8a5feffff         call    fgets
004011bb  488b05be2e0000     mov     rax, qword [rel stdout]
004011c2  be00000000         mov     esi, 0x0
```

Is there any way to know if the bitvector I'm using (`buff`) is actually being used as stdin for `fgets`?

**Comment by ltfish** [comment]
Use `SimInspect` to set a `mem_write` breakpoint. Implement your callback function as part of the breakpoint.

**Comment by afjoseph** [comment]
Beautiful!! For reference, this is the required reading: https://docs.angr.io/core-concepts/simulation#breakpoints

I'll RTFM myself and close the issue. Many thanks, Fish
