### ISSUE TITLE
The Construction of Code Property Graph in Angr

### ISSUE THREAD

**Issue by fpb1386** [angr/angr#2288]
---

angr can generate Abstract Syntax Tree (AST), Control Flow Graph (CFG) and Program Dependence Graph (PDG).
Could angr generate code property graph (CPG), which is a joint representation of AST, CFG and PDG?

**Comment by ltfish** [comment]
As of now, angr does not generate code property graphs. However, nothing stops you from manually building it using the building blocks that angr already provides.
