### ISSUE TITLE
Not enter into function during symbolic execution

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#230]
When symbolic execution, is there any way that directly returns from functions?

For example, if encountering  function foo(a,b),  the result shows something like

**add**(16, foo(symbol1, symbol2))

Just like step over in GDB.

**Comment by ltfish** [comment]
You can create a custom `SimProcedure` fur that function `foo`, and return a new named symbolic variable via `state.se.BVS(name, size)` as the return value. Then you use `project.hook()` to add a hook at the `foo` function.
