### ISSUE TITLE
Unsupported CCall armg_calculate_flags_nzcv

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#231]
When running angr symbolic execution on 32-bit ARM Linux kernel binary, this error is very common:

For example, when doing:

```
proj.factory.sim_block(pg.active[i].state)
```

or 

```
pathgroup.step()
```

The error often occurs:

```
simuvex.vex.expressions.ccall | Unsupported CCall armg_calculate_flags_nzcv
```

or

```
angr/local/lib/python2.7/site-packages/simuvex/vex/expressions/ccall.py", line 39, in _execute

raise UnsupportedCCallError("Unsupported CCall %s" % self._expr.callee.name)

simuvex.s_errors.UnsupportedCCallError: Unsupported CCall armg_calculate_flags_nzcv
```

**Comment by ltfish** [comment]
This ccall is not implemented. It'll be great if someone can implement it and give us a PR :-)

The whole ccall implementation is based on related code in VEX.

**Comment by moyix** [comment]
In case anyone else comes looking before this gets fixed, you can hack around this if necessary by adding `o.BYPASS_UNSUPPORTED_IRCCALL` to the state options.
