### ISSUE TITLE
How to create a SimFile and use SimSymbolicMemory?

### ISSUE THREAD

**Issue by JustAhmed** [angr/angr#2311]
---

Greetings!
So, i was going through some CTF challenges with angr and came across that [one](https://github.com/jakespringer/angr_ctf/tree/master/solutions/07_angr_symbolic_file)
it seems pretty straight forward to me but when i ran the script for the first time i got the following error:

`password_file = angr.storage.SimFile(filename, 'rb', content=symbolic_file_backing_memory, size=symbolic_file_size_bytes)
TypeError: __init__() got multiple values for argument 'content'` 

after researching the problem i found out that removing 'rb' from the parameters should solve the problem. Running the script again generated a different error but this time i can't figure it out. The error is: 
`File "solve.py", line 91, in main`
    `password_file = angr.storage.SimFile(filename, content=symbolic_file_backing_memory, size=symbolic_file_size_bytes)`
  `File "/home/user1/Angr/lib/python3.8/site-packages/angr/storage/file.py", line 179, in __init__`
    `raise TypeError("Can't handle SimFile content of type %s" % type(content))`
`TypeError: Can't handle SimFile content of type <class 'angr.state_plugins.symbolic_memory.SimSymbolicMemory'>`

I thought it may be related to the fact that i'm using python3, but i can't confirm that since anger is no longer supported for pytho2 so i'm kinda stuck at this point. Can i get a hint on how to solve/wrok around this porblem?
Many thanks for the awesome framework btw

**Comment by rhelmot** [comment]
angr_ctf is extremely outdated, as you may have guessed. these days, the correct way to instanciate a SimFile is not to create a SimSymbolicMemory (which as of a few days ago doesn't even exist anymore) but rather to just directly pass `password` as the `content` argument.

**Comment by JustAhmed** [comment]
Thank you for the reply. I actually tried passing `password` as the argument for `content` as well and the script ran with no errors but gave me no solution then, i found that the mapping between (the file name and where it should appear on the file system) and the angr.storage.SimFiles should be changed from:
` symbolic_filesystem = {
    filename : password_file
  }
  `
`initial_state.posix.fs = symbolic_filesystem`

To:
`initial_state.fs.insert(filename, password_file)`

that change did the trick for me

**Comment by rhelmot** [comment]
the best way to do this is in fact to pass `fs={filename: password_file}` to the state constructor.

**Comment by JustAhmed** [comment]
Yep. just gave it a try and it works. Thank you very much for your help and support!
