### ISSUE TITLE
Angr (or CLE) appears unable to resolve symbols for ntdll.dll

### ISSUE THREAD

**Issue by cythrauL** [angr/angr#2323]
---

I'm not sure if this is a bug.

Is there some-way of resolving calls to ntdll.dll in windows binaries. I have a function which I know is making a call to NtCreateFile:

![image](https://user-images.githubusercontent.com/5381474/92920043-86c33d00-f429-11ea-885f-15de7b0b15da.png)

However, Angr appears to be unable to resolve the target:

>>> p = angr.Project('myfile.dll', load_options={'auto_load_libs': False, 'preload_libs': ['ntdll.dll']})
>>> cfg = p.analyses.CFGFast()
>>> a = cfg.kb.functions[0x18000XXXX] #the function which calls ntdll
>>> b = [x for x in a.get_call_sites()][0] #the basic block which calls NtCreateFile
>>> c = a.get_call_target(b) #the call target which should resolve to ntdll::NtCreateFile
>>> cfg.kb.functions[c]
<Function UnresolvableCallTarget (0x180401040)>
>>>p.loader.shared_objects
OrderedDict([('ntdll.dll', <PE Object ntdll.dll, maps [0x180100000:0x1802e04d7]>), ('extern-address space', <ExternObject Object cle##externs, maps [0x180400000:0x180408000]>), ('cle##tls', <PETLSObject Object cle##tls, maps [0x180500000:0x180501800]>)])
>>> p.loader.find_symbol('NtCreateFile')
<Symbol "NtCreateFile" in ntdll.dll at 0x18019b430>
>>> n = _
>>> hex(n.rebased_addr)
'0x18019b430'
>>> hex(n.relative_addr)
'0x9b430'
>>> n.resolved
False

I'm trying to do src->sink analysis on some windows binaries for various APIs, is this not possible with the cfg?

My Angr version appears to be 8.20.7.27, and I'm using

Python 3.8.6rc1 (tags/v3.8.6rc1:08bd63d, Sep  7 2020, 23:10:23) [MSC v.1927 64 bit (AMD64)] on win32

**Comment by ltfish** [comment]
Our support for loading modern Windows executables and libraries is very untested at this moment. I will circle back to this issue during our Windows-support sprint, which will happen within the next few months.
