### ISSUE TITLE
CFGAccurate:  ClaripyZeroDivisionError in Claripy bv.py

### ISSUE THREAD

**Issue by marcusp46** [angr/angr#233]
Greetings,

I get a ClaripyZeroDivisionError in bv.py, line 13:

`---> 13         return f(self, o)`

I ran CFGAccurate with 

`b_simple = angr.Project("/home/marcusp/src/fsm_monitor/simple",load_options={'auto_load_libs':Tru
    ...: e},use_sim_procedures=False)`

and CFGAccurate with default parameters.  The target program is attached, and simple calls printf and nothing else.  Due to the target program's simplicity, I enabled auto_load_libs.  Any idea on how to handle this safely?  The call stack and target binary are attached.  Thanks :)

Marcus
[traceback.txt](https://github.com/angr/angr/files/516199/traceback.txt)
https://www.dropbox.com/s/job1pso0sqxcect/simple?dl=0

**Comment by ltfish** [comment]
@zardus Reading the traceback, it seems to me that this should be caught as a `SimuvexError`. I'm not expecting `ClaripyError`s from `state.se.any_int()`, or should I?

**Comment by zardus** [comment]
We don't currently catch all claripy errors. I am conflicted about whether we should or not. IMO, for now, the CFG should handle `ClaripyError`s in the same way as `SimError`s, and we should discuss further what to do long-term.

**Comment by ltfish** [comment]
I am sure I have fixed this issue.
