### ISSUE TITLE
An exception occurred in pyelftools when loading FDE information

### ISSUE THREAD

**Issue by ruotongyu** [angr/angr#2330]
---

**Describe the bug.**
WARNING | 2020-09-22 21:17:04,562 | cle.backends.elf.elf | An exception occurred in pyelftools when loading FDE information.
The above exception happened when Angr try to load ehframe info from strip binaries. 
It seems the ptelftools library fail to load FDE information in ehframe. 
I check the binaries with readelf --debug-dump=frames. The binary files have valid FDE information.

**Environment Information.**
![Screenshot from 2020-09-22 21-33-03](https://user-images.githubusercontent.com/25619082/93954984-c7ba2c00-fd1c-11ea-92e8-ac1d5d4bf697.png)

**To Reproduce.**

Here is one of the binary
[mysql.zip](https://github.com/angr/angr/files/5265020/mysql.zip)

**Additional context.**

**Comment by ltfish** [comment]
Are you using pyelftools from GitHub master or from PyPI?

**Comment by ruotongyu** [comment]
I re-build pyelftools from GitHub master. It works now.
