### ISSUE TITLE
angr_native.so NOT FOUND

### ISSUE THREAD

**Issue by KagamigawaMeguri** [angr/angr#2336]
pls forgive me for asking such a silly question, I have tried my best to find the answer.

When I use deflat\bogus_control_flow, it shows:
```
angr.state_plugins.unicorn_engine | failed loading "angr_native.so", unicorn support disabled (/root/Envs/angr/lib/python3.8/site-packages/angr-9.0.gitrolling-py3.8.egg/angr/lib/angr_native.so: cannot open shared object file: No such file or directory)
```

WSL 1 Ubuntu 18.04
use mkvirtualenv python3.8
and i install angr though download&install sequentially ailment, archinfo, pyvex, claripy, cle, angr instead of pip install angr, because pip install angr shows "No matching distribution found for claripy==9.0.gitrolling (from angr)"

Although this issue has no effect at the moment, but I am very curious about it.
Thank you for wasting time to answer my question.

**Comment by twizmwazin** [comment]
Our git versions (ending in `.gitrolling`) of projects and PyPI versions (ending in a number) are not compatible. It looks like you are trying to install angr from git without having first installed angr's dependencies from git. If you are using the git version of any of our projects, I recommend you do it using [angr-dev](https://github.com/angr/angr-dev) to save yourself a lot of time and effort.

Additionally, I tested installing angr 9.0.4446 from PyPI with python 3.6 and 3.8 on Ubuntu 18.04, WSL 1. In both cases they were able to install and the unicorn engine was loaded successfully. Please let me know if you have further questions!

**Comment by KagamigawaMeguri** [comment]
> 我们`.gitrolling`的项目的git版本（以结尾）和PyPI版本（以数字结尾）不兼容。看来您正在尝试从git安装angr，而没有先从git安装angr的依赖项。如果您使用的是我们任何项目的git版本，建议您使用[angr-dev](https://github.com/angr/angr-dev)进行操作，以节省大量时间和精力。
> 
> 此外，我测试了在Ubuntu 18.04，WSL 1上使用python 3.6和3.8从PyPI安装angr 9.0.4446的情况。在这两种情况下，他们都能够安装并且成功加载了独角兽引擎。如果您还有其他问题，请告诉我！

I clean everything and reinstalled my system to install angr, then it successed, i think that maybe a mess of other things was installed when I installed it for the first time.
Thank you for your patience and enthusiastic reply!
