### ISSUE TITLE
Error using simuvex unicorn plugin on MacOS

### ISSUE THREAD

**Issue by pwntester** [angr/angr#234]
I get an error when using the unicorn engine for the analysis:

`s = p.factory.blank_state(addr=0x401260, add_options=simuvex.o.unicorn, remove_options={simuvex.o.LAZY_SOLVES})`

I installed Angr in a pypy virtualenv so had to install unicorn manually (not available in pip), but I tried several unicorn scripts and they work ok and when installing Angr, it finds it:

`Requirement already satisfied (use --upgrade to upgrade): unicorn in /Users/alvaro/virtualenvs/angr_pypy/site-packages/unicorn-1.0-py2.7.egg (from simuvex->angr)`

but when I select the unicorn engine I get the following error (`add_options=simuvex.o.unicorn`):

```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "solve_rock_angr.py", line 40, in <module>
    print main()
  File "solve_rock_angr.py", line 25, in main
    pg.explore(find=0x401428, avoid=0x40186d)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 806, in explore
    n=n)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 830, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 520, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 311, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 208, in _one_path_step
    successors = a.step(**kwargs)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path.py", line 337, in step
    self._make_sim_run(throw=throw)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/path.py", line 368, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/angr/factory.py", line 167, in sim_run
    r = SimUnicorn(state, stop_points=stops)
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/simuvex/s_unicorn.py", line 29, in __init__
    self.state.unicorn.setup()
  File "/Users/alvaro/virtualenvs/angr_pypy/site-packages/simuvex/plugins/unicorn_engine.py", line 825, in setup
    self._uc_state = _UC_NATIVE.alloc(self.uc._uch, self.cache_key)
AttributeError: 'NoneType' object has no attribute 'alloc'
```

`_UC_NATIVE` seems to reference `sim_unicorn.dylib` in MacOS. Is this a simuvex library? I can only find `libunicorn.dylib` in my system.

Thanks,
A

**Comment by ltfish** [comment]
It is a simuvex library. It should be built when you run `pip install simuvex`, see [setup.py of SimuVEX, line 38](https://github.com/angr/simuvex/blob/master/setup.py#L38). It seems that your machine fails to compile the sim_unicorn native library. You can remove the `try... except...` in setup.py and then try again to see what happened during the procedure.

**Comment by rhelmot** [comment]
Here is what is going on:

- You have the unicorn engine python library installed
- The simuvex unicorn compatibility layer (sim_unicorn.dylib) failed to compile for your system at setup time.
- There's supposed to be a check that catches cases like this and simply doesn't use unicorn, but it looks like it was insufficient in this case. I just pushed some code that will print a more helpful error message and fall back to normal emulation.

If you installed unicorn after you installed simuvex, you need to rebuild simuvex.

If you installed unicorn from the official upstream github, you need to install it from [our fork](https://github.com/angr/unicorn).

**Comment by pwntester** [comment]
Thanks for the hints, I was doing some mistakes:

- I was using Unicorn from their repo. solved
- I was installing simuvex without the `build` targetm just the `install`

But I got some problems compiling sim_unicorn:

- MacOSX incompatibility:

```
Building sim_unicorn
gcc -fPIC -c -O3 -o log.o log.c
log.c:111:95: error: use of undeclared identifier '__NR_gettid'
        dprintf(log_fd, "[%s][%s][%d] %s():%d ", timestr, logLevels[ll].descr, (pid_t)syscall(__NR_gettid), fn, ln);
```

I solved this by adding the following code to log.c:

```
#if defined(__APPLE__)
  #if !defined(__NR_gettid)
    #define __NR_gettid SYS_gettid
  #endif
#endif
```

Now Im getting a second error:

```
sim_unicorn.cpp:1106:15: error: functions that differ only in their return type cannot be overloaded
mem_update_t *sync(State *state) {
~~~~~~~~~~~~~~^
/usr/include/unistd.h:601:7: note: previous declaration is here
void     sync(void);
~~~~     ^
```

which Im not sure what is the best wat to fix, any idea?

Thanks!
A

**Comment by rhelmot** [comment]
It's nice to work with someone who actually knows how to debug things for once :)

This actually looks like a bug. Some part of the OS X version of the c++ headers that we include must include unistd.h, which defines sync(2). On linux, this doesn't happen for whatever reason... The real bug is that we're using such a generic name for a function. I'll see about fixing this today.

**Comment by pwntester** [comment]
Awesome, thanks! I though about renaming the function myself, but I guess the PR would have few chances to get accepted :)

In the meantime, I was able to use angr (without unicorn) to try to solve a simple crackme for the first time, and its working ... well, more or less, it finds a path to the Win address, but the dumped stdin value is not correct. Im sure Im doing something wrong, will play with it more. What is the best place to discuss this kind of problems? the mailing list?

Thanks again!

**Comment by rhelmot** [comment]
Either the mailing list or opening another issue would be good!

**Comment by ltfish** [comment]
@pwntester Usually those issues regarding angr usage and "why doesn't angr work for crackme abc" go to the `angr` repo.

**Comment by pwntester** [comment]
Thanks, will do!

**Comment by ltfish** [comment]
@rhelmot Can we close this issue? I think you've already fixed it.

**Comment by rhelmot** [comment]
I have not fixed it :P

**Comment by rhelmot** [comment]
Now I have fixed it!

**Comment by rhelmot** [comment]
@pwntester additionally, I added the defines you said fixed an issue of yours to the bottom of log.h.

**Comment by pwntester** [comment]
Thank you @rhelmot !

I rebuilt simuvex with no errors this time, and `sim_unicorn.dylib` seems to be in the right place:

```
/Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg/simuvex/lib/sim_unicorn.dylib
```

I then install angr with `pip install angr` which finds simuvex installed by hand:

```
Requirement already up-to-date: simuvex>=5.6.10.7 in /Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg (from angr)
```

So far so good, but when I run angr with unicorn engine (`s = p.factory.full_init_state(args=['./rock'], add_options=simuvex.o.unicorn, remove_options={simuvex.o.LAZY_SOLVES})`), I get a bunch of:

```
ERROR   | 2016-10-11 12:22:21,792 | simuvex.plugins.unicorn | You are attempting to use unicorn engine support even though it or the simuvex compatibility layer isn't installed
```

I modified `unicorn_engine.py` plugin to make it a little bit more verbose and got:

```
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "solve_rock_angr.py", line 40, in <module>
    print main()
  File "solve_rock_angr.py", line 25, in main
    pg.explore(find=0x40149e, avoid=0x40186d)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 806, in explore
    n=n)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 830, in run
    return self.step(n=n, step_func=step_func, until=until_func, stash=stash)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 520, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 311, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path_group.py", line 208, in _one_path_step
    successors = a.step(**kwargs)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path.py", line 337, in step
    self._make_sim_run(throw=throw)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/path.py", line 368, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/angr/factory.py", line 160, in sim_run
    elif o.UNICORN in state.options and state.unicorn.check():
  File "/Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg/simuvex/plugins/unicorn_engine.py", line 1266, in check
    if unicorn is None or _UC_NATIVE is None:
UnboundLocalError: local variable 'unicorn' referenced before assignment
```

I basically copied the `unicorn` and `_UC_NATIVE` initializations to `def check(self)` (not sure why there were not initialized, maybe the caller code just import the unicorn plugin class and the global code does not get called ???). Anyway, I added the following lines to `check()`:

```
        try:
            import unicorn
        except ImportError:
            l.warning("Unicorn is not installed. Support disabled.")
            unicorn = None
        try:
            _UC_NATIVE = _load_native()
            _UC_NATIVE.logSetLogLevel(2)
```

And got the following error:

```
WARNING | 2016-10-11 12:34:56,226 | simuvex.plugins.unicorn | failed loading "sim_unicorn.dylib", unicorn support disabled (Cannot load library /Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg/simuvex/lib/sim_unicorn.dylib: dlopen(/Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg/simuvex/lib/sim_unicorn.dylib, 2): Library not loaded: libpyvex.dylib
  Referenced from: /Users/pwntester/virtualenvs/angr_pypy/site-packages/simuvex-5.6.10.7-py2.7.egg/simuvex/lib/sim_unicorn.dylib
  Reason: image not found)
```

But I checked that is actually installed in `/Users/pwntester/virtualenvs/angr_pypy/site-packages/pyvex/lib/libpyvex.dylib`

I guess its an OSX related problem, any ideas?

**Comment by rhelmot** [comment]
So libpyvex.dylib should be already loaded into memory by pyvex... can you check that `import pyvex; print pyvex.pvc` shows a reference to `/Users/pwntester/virtualenvs/angr_pypy/site-packages/pyvex/lib/libpyvex.dylib`? And can you check that that file has the `install_name` dylib attribute is set to `libpyvex.dylib` as well? Sorry, not sure how to refer to it correctly... it's the DT_SONAME dynamic tag in an ELF but I'm not sure what it's called in a mach-o.

I've been trying to get ahold of an OS X install to do testing on for myself!! sorry you're basically getting this thrown at you...

**Comment by ltfish** [comment]
I'll test it on a macOS install this afternoon!

**Comment by ltfish** [comment]
After spending more than three hours on my macOS Sierra install, I successfully configured angr with Unicorn-engine support. Here is what I did.

- Install virtualenv using pip. Create a new virtual environment `angr`.
- `brew install pkg-config libffi glib`
- `pip install angr` to install the latest version from PyPI.
- Fix `capstone` install by moving `/Users/<username>/.virtualenvs/angr/lib/python2.7/site-packages/Users/<username>/.virtualenvs/angr/lib/python2.7/site-packages/capstone/libcapstone.dylib` to `/Users/<username>/.virtualenvs/angr/lib/python2.7/site-packages/capstone/`. This is an issue of capstone PyPI package. We might submit a PR to them later.
- Clone [our fork of unicorn](https://github.com/angr/unicorn) and do `pip install .` to install the package.
- Uninstall SimuVEX by running `pip uninstall simuvex`, clone SimuVEX from https://github.com/angr/simuvex, and then run `python setup.py build` to build and `python setup.py install` to install SimuVEX with unicorn support. I'm not sure why `pip install simuvex` after `pip uninstall simuvex` still does not automatically compile with unicorn support.
- Now `import angr` should not complain anymore.

**Comment by rhelmot** [comment]
Note: the only thing special about our fork of unicorn at this point is that we have a stub setup.py in the root of the repository :P

**Comment by ltfish** [comment]
Update to my post:

I missed some important things there:

- I had to fix a bug in `simuvex/simuvex_c/Makefile` where we are not calling `pkg-config --libs glibc-2.0` to get correct configuration strings.
- I hard-coded absolute paths to `libunicorn` and `libpyvex` to Makefile to make the loader happy, otherwise it always complain about things like "Library not loaded: libunicorn.1.dylib".

Now I'm having a few other problems with the install - I'll see if they are solvable within the next hour, and I'll give up I cannot.

**Comment by rhelmot** [comment]
The paths are supposed to be handled by the new distribution system for the library objects - in simuvex/setup.py there's the `pkg_resources.get_resource_filename('lib', 'pyvex')` call which is supposed to get the path to libpyvex.dylib. That's the way it's supposed to happen...

**Comment by ltfish** [comment]
Phew... now it really works! I updated the original post to reflect what I did to make it work, though it was pretty hackish :-)

**Comment by rhelmot** [comment]
Uh, you should *absolutely not* have had to do the DYLIB_LIBRARY_PATH thing. fish, you should wait until I'm next to you to come up with the correct solutions to these problems...

**Comment by ltfish** [comment]
> you should absolutely not have had to do the DYLIB_LIBRARY_PATH thing

I agree, that's why the solution is **hackish**.

**Comment by pwntester** [comment]
Thank you guys! Just exporting the DYLIB_LIBRARY_PATH worked for me. One minor thing, I had to use: `/Users/pwntester/virtualenvs/angr_pypy/site-packages/pyvex/lib` rather than `/Users/pwntester/virtualenvs/angr_pypy/lib/python2.7/site-packages/pyvex/lib`. It seems that in my system the `libpyvex.dylib` library is not deployed to `/lib` in the python virtualenv directory. Actually none of the angr modules gets deployed there, only pip, wheel, setuptool, etc.

Thanks again!

**Comment by ltfish** [comment]
Depends on how much free time we have, we (@rhelmot and I) will get to the real problem either today or tomorrow, so you don't have to specify `DYLIB_LIBRARY_PATH` on macOS anymore in the future.

**Comment by dpnishant** [comment]
@ltfish Any update on this bug? I'm facing the exact same error and not been able to resolve it. Any help would be highly appreciated.

**Comment by ltfish** [comment]
We (mostly @rhelmot) made some effort, and now unicorn is put on PyPI. Can you please test if the version on PyPI works under macOS?

**Comment by dpnishant** [comment]
Thanks @ltfish for the quick reply. I tried to install angr with `pip install angr`. And whenever I try to `import angr` I get the following error:

```<type 'exceptions.OSError'> dlopen(/Users/<username>/env1/lib/python2.7/site-packages/simuvex/lib/sim_unicorn.dylib, 6): Library not loaded: libunicorn.1.dylib
  Referenced from: /Users/<username>/env1/lib/python2.7/site-packages/simuvex/lib/sim_unicorn.dylib
  Reason: image not found <traceback object at 0x110f5c170>```

**Comment by ltfish** [comment]
Well, then it was the same problem as before. Does exporting `DYLIB_LIBRARY_PATH` work for you?

**Comment by dpnishant** [comment]
@ltfish Pardon my ignorance but I'm not familiar with `DYLIB_LIBRARY_PATH`.

I'm installing angr as follows:

```➜  ~ pip install angr --no-cache-dir --no-binary all    
Collecting angr
  Downloading angr-6.7.1.13.post2.tar.gz (269kB)
    100% |████████████████████████████████| 276kB 1.2MB/s 
Requirement already satisfied: capstone in /Library/Python/2.7/site-packages (from angr)
Requirement already satisfied: networkx in /Library/Python/2.7/site-packages (from angr)
Collecting futures (from angr)
  Downloading futures-3.0.5-py2-none-any.whl
Requirement already satisfied: progressbar in /Library/Python/2.7/site-packages (from angr)
Collecting mulpyplexer (from angr)
  Downloading mulpyplexer-0.07.tar.gz
Collecting cooldict (from angr)
  Downloading cooldict-1.02.tar.gz
Collecting ana (from angr)
  Downloading ana-0.03.zip
Collecting archinfo>=6.7.1.13 (from angr)
  Downloading archinfo-6.7.1.13.tar.gz
Collecting pyvex>=6.7.1.13.post2 (from angr)
  Downloading pyvex-6.7.1.13.post2.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 7.2MB/s 
Collecting claripy>=6.7.1.13.post2 (from angr)
  Downloading claripy-6.7.1.13.post2.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 3.3MB/s 
Collecting simuvex>=6.7.1.13.post2 (from angr)
  Downloading simuvex-6.7.1.13.post2.tar.gz (186kB)
    100% |████████████████████████████████| 194kB 686kB/s 
Collecting cle>=6.7.1.13.post2 (from angr)
  Downloading cle-6.7.1.13.post2.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 5.5MB/s 
Collecting cachetools (from angr)
  Downloading cachetools-2.0.0-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx->angr)
  Downloading decorator-4.0.11-py2.py3-none-any.whl
Requirement already satisfied: pycparser in /Library/Python/2.7/site-packages (from pyvex>=6.7.1.13.post2->angr)
Requirement already satisfied: cffi>=1.0.3 in /Library/Python/2.7/site-packages (from pyvex>=6.7.1.13.post2->angr)
Collecting angr-only-z3-custom==9002 (from claripy>=6.7.1.13.post2->angr)
  Downloading angr-only-z3-custom-9002.tar.gz
Requirement already satisfied: bintrees in /Library/Python/2.7/site-packages (from simuvex>=6.7.1.13.post2->angr)
Collecting enum34 (from simuvex>=6.7.1.13.post2->angr)
  Downloading enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: dpkt-fix in /Library/Python/2.7/site-packages (from simuvex>=6.7.1.13.post2->angr)
Collecting unicorn (from simuvex>=6.7.1.13.post2->angr)
  Downloading unicorn-1.0.0rc2.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 6.0MB/s 
Requirement already satisfied: pyelftools in /Library/Python/2.7/site-packages (from cle>=6.7.1.13.post2->angr)
Requirement already satisfied: idalink in /Library/Python/2.7/site-packages (from cle>=6.7.1.13.post2->angr)
Collecting pefile (from cle>=6.7.1.13.post2->angr)
  Downloading pefile-2016.3.28.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 13.0MB/s 
Collecting z3-solver (from angr-only-z3-custom==9002->claripy>=6.7.1.13.post2->angr)
  Downloading z3-solver-4.5.1.0.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 3.9MB/s 
Requirement already satisfied: rpyc in /Library/Python/2.7/site-packages (from idalink->cle>=6.7.1.13.post2->angr)
Requirement already satisfied: future in /Library/Python/2.7/site-packages (from pefile->cle>=6.7.1.13.post2->angr)
Collecting plumbum (from rpyc->idalink->cle>=6.7.1.13.post2->angr)
  Downloading plumbum-1.6.3-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 14.3MB/s 
Installing collected packages: futures, mulpyplexer, ana, cooldict, archinfo, pyvex, z3-solver, angr-only-z3-custom, claripy, cachetools, enum34, unicorn, simuvex, pefile, cle, angr, decorator, plumbum
  Running setup.py install for mulpyplexer ... done
  Running setup.py install for ana ... done
  Running setup.py install for cooldict ... done
  Running setup.py install for archinfo ... done
  Running setup.py install for pyvex ... done
  Running setup.py install for z3-solver ... done
  Running setup.py install for angr-only-z3-custom ... done
  Running setup.py install for claripy ... done
  Running setup.py install for unicorn ... done
  Running setup.py install for simuvex ... done
  Running setup.py install for pefile ... done
  Running setup.py install for cle ... done
  Running setup.py install for angr ... done
Successfully installed ana-0.3 angr-6.7.1.13.post2 angr-only-z3-custom-9002 archinfo-6.7.1.13 cachetools-2.0.0 claripy-6.7.1.13.post2 cle-6.7.1.13.post2 cooldict-1.2 decorator-4.0.11 enum34-1.1.6 futures-3.0.5 mulpyplexer-0.7 pefile-2016.3.28 plumbum-1.6.3 pyvex-6.7.1.13.post2 simuvex-6.7.1.13.post2 unicorn-1.0.0rc2 z3-solver-4.5.1.0
```

and this is what I'm getting in the Python REPL

```➜  ~ python
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> try:
...     import angr
... except Exception as e:
...     print "Error: " + str(e)
... 
<type 'exceptions.OSError'> dlopen(/Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib, 6): Library not loaded: libunicorn.1.dylib
  Referenced from: /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib
  Reason: unsafe use of relative rpath libunicorn.1.dylib in /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib with restricted binary <traceback object at 0x108350ea8>
>>> 
```

What do you suggest I should do?

**Comment by ltfish** [comment]
Oh it says the reason right there: 
```
Reason: unsafe use of relative rpath libunicorn.1.dylib in /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib with restricted binary <traceback object at 0x108350ea8>
```

I'm not an expert with macOS, but I believe this is due to the SIP (which is imported from macOS El Capitan). It does not allow you to use relative rpath in sim_unicorn.dylib to reference libunicorn.

Some googling tells me that you can probably fix this problem by running `install_name_tool` on macOS, something like the following:

```
sudo install_name_tool <path_to_libunicorn.1.dylib> <repeat_path_to_libunicorn.1.dylib>
```

**Comment by dpnishant** [comment]
@ltfish I did issue the following command

```
sudo install_name_tool -change libunicorn.1.dylib /Library/Python/2.7/site-packages/simuvex/lib/libunicorn.1.dylib /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib
```

and now importing angr has a new 'image not found' error

```
Python 2.7.10 (default, Jul 30 2016, 19:40:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
<type 'exceptions.OSError'> dlopen(/Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib, 6): Library not loaded: /Library/Python/2.7/site-packages/simuvex/lib/libunicorn.1.dylib
  Referenced from: /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib
  Reason: image not found <traceback object at 0x10980fef0>
```

**Comment by ltfish** [comment]
Does `/Library/Python/2.7/site-packages/simuvex/lib/libunicorn.1.dylib` exist on your machine?

**Comment by rhelmot** [comment]
That file should never exist.

The following files should exist:

- `/Library/Python/2.7/site-packages/unicorn/lib/libunicorn.1.dylib`
- `/Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib`

**Comment by rhelmot** [comment]
Additionally, the error that is printed to your screen is not a fatal error. It is merely a logging message indicating that unicorn support failed to load. The rest of angr will function normally.

**Comment by ltfish** [comment]
Ah so the command you use for `install_name_tool` was wrong.

Try the following:

```
sudo install_name_tool -change libunicorn.1.dylib /Library/Python/2.7/site-packages/unicorn/lib/libunicorn.1.dylib /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib
```

You may have to recompile `sim_unicorn.dylib` first, if you didn't make a backup of the original version.

**Comment by dpnishant** [comment]
Sorry for reply late to this thread. I finally solved the issue as there was some confusion going on with the filenames and paths. So here is the thing, after I did `pip install angr`, there exists the following files

* `/Library/Python/2.7/site-packages/unicorn/lib/libunicorn.dylib`
* `/Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib`

Then I did run the following commands
* `sudo install_name_tool -change libunicorn.1.dylib /Library/Python/2.7/site-packages/unicorn/lib/libunicorn.dylib /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib`

* `sudo install_name_tool -change libpyvex.dylib /Library/Python/2.7/site-packages/pyvex/lib/libpyvex.dylib /Library/Python/2.7/site-packages/simuvex/lib/sim_unicorn.dylib`

And now I can `import angr` without any **_anger_**! 😉 Thanks a lot @ltfish @rhelmot for being consistently patient with me. 👍 😊

**Comment by ltfish** [comment]
@dpnishant thanks for sharing the information! This issue will be very useful before we get to the root of the problem and resolve it.

**Comment by phros** [comment]
Same issue here. After cloning and building the complete angr-dev repository I get the same message, just for linux. Don't know whether this helps....

`
<type 'exceptions.OSError'> ~/angr-dev/simuvex/simuvex/lib/sim_unicorn.so: cannot open shared object file: No such file or directory <traceback object at 0x7f5c77ff0bd8>`

**Comment by Dinatrix** [comment]
I just experienced the same error as @phros after cloning and building the angr-dev repo on linux (ubuntu 14.04)

**Comment by ltfish** [comment]
@phros @Dinatrix are you using macOS or Linux? This issue is only for macOS.

**Comment by Manouchehri** [comment]
taskgated is logging error -67062. Maybe it's codesigning related?

**Comment by Dinatrix** [comment]
@ltfish I had this error on Linux

**Comment by ltfish** [comment]
@Dinatrix feel free to open a new issue for your error then.

**Comment by Manouchehri** [comment]
Managed to get it working without too much effort. Just a single `ln -s` and `DYLD_LIBRARY_PATH`.

```bash
nitro:google2016_unbreakable_0 dave$ ln -s /usr/local/lib/python2.7/site-packages/unicorn/lib/libunicorn.dylib /usr/local/lib/python2.7/site-packages/unicorn/lib/libunicorn.1.dylib
nitro:google2016_unbreakable_0 dave$ DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib/python2.7/site-packages/unicorn/lib/:/usr/local/lib/python2.7/site-packages/pyvex/lib/ python2 solve.py
'CTF{0The1Quick2Brown3Fox4Jumped5Over6The7Lazy8Fox9}'
```
