### ISSUE TITLE
`Function.runtime_value()` is broken

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#2343]
**Describe the bug.** / **To Reproduce.**

```python
from angr.project import Project
project = Project('<A BINARY>', auto_load_libs=False) # get a binary containing functions
project.analyses.CFGFast()
function = project.kb.functions.function(name='main') # will fail with any function
function.runtime_values()
```

Leads to several errors:
  * There is no `_cfg` attribute for `FunctionManager`: easily corrected using `kb.cfgs['CFGFast'];
  * But then, `get_all_irsbs` is not an attribute of `CFGModel` (can't even find any occurences of it in the current codebase - although it was here before CFG was split into a model/view).
  * Maybe more, I did not go any further...

https://github.com/angr/angr/blob/0fdab305a121dbc7e0a723a71919676fe9428a61/angr/knowledge_plugins/functions/function.py#L537-L553

**Comment by ltfish** [comment]
Do you need that function? I believe `runtime_values()` can be removed.

**Comment by Pamplemousse** [comment]
No, I don't think I need it.
`VariableRecovery*` seems to give me the information I think I would need ^^

Do you want me to submit the PR to remove it?
