### ISSUE TITLE
Angr finds path but flag is wrong

### ISSUE THREAD

**Issue by pwntester** [angr/angr#235]
Hi,

I'm new to Angr and I was playing with it for the first time with the CSAW 2016 rock crackme. Its a very simple crackme where we have to hit an address avoiding another one within a loop. In order to do that, I have basically make the stdin symbolic, added some constraints about printable characters and use the path_group explorer to find a path that hits the Win address avoiding the Fail one:

```
import angr, simuvex

def main():
    p = angr.Project("rock", load_options={'auto_load_libs': True})
    #s = p.factory.entry_state(args=['./rock'], add_options=simuvex.o.unicorn, remove_options={simuvex.o.LAZY_SOLVES})
    # s = p.factory.blank_state(addr=0x401260, remove_options={simuvex.o.LAZY_SOLVES})
    s = p.factory.full_init_state(args=['./rock'], remove_options={simuvex.o.LAZY_SOLVES})

    # input needs to be 30 bytes long and new line
    for i in xrange(30):
        k = s.posix.files[0].read_from(1)
        s.se.add(k>0x20)
        s.se.add(k<0x7E)
        s.se.add(k!=0xA)
    # last character is new line
    k = s.posix.files[0].read_from(1)
    s.se.add(k==0xA)

    # reset the symbolic stdin's properties and set its length
    s.posix.files[0].seek(0)
    s.posix.files[0].length = 31

    pg = p.factory.path_group(s)
    pg.explore(find=0x40149e, avoid=0x40186d)

    print pg

    if len(pg.errored) > 0:
        print list(pg.errored[0].trace)
        print pg.errored[0].state
        pg.errored[0].retry()

    if len(pg.found) > 0:
        found_state = pg.found[0].state
        #import ipdb; ipdb.set_trace()
        return found_state.posix.dumps(0)

if __name__ == '__main__':
    print main()
```

I have tried several initializations, but finally using the full init one since its a c++ binary and Im not sure about Angr support in terms of SimProcedures, etc.

When I run it, It finds a path but the flag is wrong:

```
(angr_pypy) ~/CTFs/tasks/CSAW2k16/rock❯ python solve_rock_angr.py
<PathGroup with 82 active, 6 deadended, 1 found>
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
```

The binary can be found [here](https://github.com/pwntester/csaw2016_rock) and a write up of the challenge [here](https://github.com/ernw/ctf-writeups/tree/master/csaw2016/rock).

Please do not waste any time on this if you don't spot the error immediately, Im sure you all have better things to do :D

Thanks,
A

**Comment by ltfish** [comment]
I think the problem is with C++ library support inangr. This challenge binary uses many functions from libstdc++, which is not fully supported by angr. Honestly I have no idea what happens when you executing those functions in angr. It's worth looking into, but getting C++ support in angr is not one of our priorities at the moment.

**Comment by rhelmot** [comment]
I haven't looked at this at all, but based on what fish just said: angr can execute c++ code, but it's a lot more intensive and it really really requires that we've implemented all of the loading, relocating, thread-local storage support, etc stuff correctly. There's an example of solving a csaw challenge from last year (wyvern) with angr, and it does work, but it took several days for me to be able to track down and fix a couple of bugs in the aforementioned areas before angr could emulate it correctly. :(

**Comment by pwntester** [comment]
Thank you guys!
