### ISSUE TITLE
Memory Load in new Memory Model returns BitVec of longer size than specified.

### ISSUE THREAD

**Issue by fmagin** [angr/angr#2354]
**Describe the bug.**

Memory loads across page boundaries sometimes return a result that is not the specified length. I am not sure if this kind of read that triggers the bug in my case is even legal because the address overflows, but it can definitely happen in a fairly common symbolic execution scenario. 

**Environment Information.**

This reproduces in a new Python venv with simply `pip install angr`, but also in a current `master` environment with:

```
python -m angr.misc.bug_report
angr environment report
=============================
Date: 2020-10-21 16:19:29.506048
Running in virtual environment at /home/fmagin/.virtualenvs/tempenv-18a0293525720
Platform: linux-x86_64
Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
######## angr #########
Python found it in /home/fmagin/Projects/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
	Current commit 91fe089b95b4d303f0f9690956bd485076981d2b from branch master
	Checked out from remote origin: https://github.com/angr/angr.git
######## ailment #########
Python found it in /home/fmagin/Projects/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
	Current commit 0002d45d0585104872e12aab2b0bf064c61f2245 from branch master
	Checked out from remote origin: https://github.com/angr/ailment.git
######## cle #########
Python found it in /home/fmagin/Projects/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
	Current commit ae5b6093f9d32810dbad98c8877040ca1d24e62b from branch master
	Checked out from remote origin: https://github.com/angr/cle.git
######## pyvex #########
Python found it in /home/fmagin/Projects/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
	Current commit 99d249b3f25928a61a9417b7d461919a34c9e4b8 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex.git
######## claripy #########
Python found it in /home/fmagin/Projects/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
	Current commit 0c3669b41e1ce15d8c904cf57f16431dfecc120a from branch master
	Checked out from remote origin: https://github.com/angr/claripy.git
######## archinfo #########
Python found it in /home/fmagin/Projects/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
	Current commit d156e1c89d592ff7172a61b7a10c8c6c4c58dbb8 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo.git
######## z3 #########
Python found it in /home/fmagin/.virtualenvs/tempenv-18a0293525720/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.9.0
Couldn't find git info
######## unicorn #########
Python found it in /home/fmagin/.virtualenvs/tempenv-18a0293525720/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/fmagin/Projects/angr-dev/angr/angr/lib/angr_native.so', handle 55fb99a11570 at 0x7f07c5ea9ac0>
unicorn: <CDLL '/home/fmagin/.virtualenvs/tempenv-18a0293525720/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 55fb9915d0d0 at 0x7f07cad1afa0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f07cb91fa90>
z3: <CDLL '/home/fmagin/.virtualenvs/tempenv-18a0293525720/lib/python3.8/site-packages/z3/lib/libz3.so', handle 55fb99392dc0 at 0x7f07c8e4cfd0>
```

**To Reproduce.**
```python
import angr
import claripy

if __name__ == "__main__":
    project = angr.Project("/bin/ls") # or any other 64 bit binary. Maybe any other bitness has the same issue too
    state = project.factory.entry_state() 

    zero_addr = state.memory.load(0, size=8, endness='Iend_LE')
    state.solver.add(zero_addr == 0xffffffffffffffff)
    res: claripy.BV = state.memory.load(zero_addr, size=4, endness='Iend_LE')
    assert res.size() == 4 * 8, f"4 byte load returned {res.size() // 8 } bytes"
```
The resulting BV will be 72 bits in length.

If this value is then passed into the Vex Expression `32Uto64`, the resulting bitvector will be ZeroExtended by `-8` which will result in the Z3 exception: `z3.z3types.Z3Exception: b'invalid zero_extend application` 

Just loading from the address `0xffffffffffffffff` does not trigger this bug, address 0 has to be loaded and constrained first, so `cur_val` is set to `MO(<BV64 mem_0_31_64{UNINITIALIZED}>)` in the following line: https://github.com/angr/angr/blob/91a061977e2248bdff3cfd54e5a932e17cd96373/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py#L74
 
This also happens _sometimes_ if the constraint is `zero_addr != 0` instead of `zero_addr == 0xffffffffffffffff`. Specifically in all the cases where `zero_addr` is concretized to `0xffffffffffffffff`. This condition is probably met in many symbolic execution scenarios of the following pseudo code pattern.

```C

ptr1 = SOME_UNCONSTRAINED_VALUE
ptr2 = *ptr1 # ptr1 is concretized to 0
if (ptr2 != 0) {
    x = *ptr2 # ptr2 is concretized to 0xffffffffffffffff
}

```

**Additional context.**

`git bisect` confirmed that this was introduced by the new memory model, specifically commit 1c56b6131f2a34e3c31d240bce3272225069f784

**Comment by fmagin** [comment]
This seems like it would only ever be an issue in a scenario where you would want to use `angr.sim_options.UNDER_CONSTRAINED_SYMEXEC` anyway. I wasn't aware of this option before, and it might also be useful to add a warning similar to the existing one for uninitialized memory (which suggests `ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}`)  to the first memory load that has an underconstrained BVS as an address.

**Comment by rhelmot** [comment]
Fixed. I wasn't able to reproduce this with UltraPage, but it popped up with ListPage.

**Comment by fmagin** [comment]
Also fixed on my setup. Thanks!
