### ISSUE TITLE
Callgraph contains one erroneous node and edge

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr#2366]
**Describe the bug.**

After running `CFGFast`, I obtain a node and an edge in the `project.kb.callgraph` that should not be here:
  * The node is not the start of the function: it's the address of the latest statement of the beginning of the `.plt` section (before the entry of its first function);
  * The edge is between this node, and the first entry in the `.plt`.

Say you have the following:
```asm
;-- section..plt:
;-- .plt:
0x00401020      push    qword [0x00404008] ; [12] -r-x section size 64 named .plt
0x00401026      jmp     qword [0x00404010]
0x0040102c      nop     dword [rax]
;-- int puts (const char *s);
0x00401030      jmp     qword [reloc.puts] ; 0x404018
0x00401036      push    0
0x0040103b      jmp     section..plt
```

Then you would have `0x40102c --> 0x401030` in the callgraph.

**To Reproduce.**

I have observed a similar behavior with several different (dynamically linked) binaries; So I guess any would do...

```python
from angr import Project

project = Project(<ANY BINARY>, auto_load_libs=False)
cfg = project.analyses.CFGFast()

first_plt_function = list(filter(
    lambda f: f.is_plt,
    project.kb.functions.values()
))[0]

predecessor_addresses = list(map(
    lambda p: "%#x" % p,
    project.kb.callgraph.predecessors(first_plt_function.addr)
))

print(predecessor_addresses)
# now, you should see the address in `.plt`, and other places where the first entry is called
```

**Comment by ltfish** [comment]
`CFGFast._remove_redundant_overlapping_blocks()` is not working as expected. I never motivated myself enough to fix this bug.
