### ISSUE TITLE
angr provides wrong results in certain cases

### ISSUE THREAD

**Issue by flxflndy** [angr/angr#237]
I am currently playing around with angr and came along a small issue:
I have created two binaries which read input from a file and call a function based on their content.

The first parsing routine of test1:
```
char *pwdFun2 = "bbbb";
void parsing(char* input) {
	if (memcmp(input, pwdFun2, 4) == 0){
		fun2();
	}

}
```
The second parsing routine of test2:
```
char *pwdFun1 = "aaaa";
char *pwdFun2 = "bbbb";
void parsing(char* input) {
	if (memcmp(input, pwdFun1, 4) == 0)  {
                fun1();
        }
	else if (memcmp(input, pwdFun2, 4) == 0) {
		fun2();


	}
}
```

I have created a angr script which tries to find given function in a given binary.
```
#!/usr/bin/env python2
import angr
import sys
import simuvex
import logging
logging.basicConfig(level=logging.DEBUG) 
#logging.getLogger("simuvex.procedures.libc.memcmp").setLevel(logging.DEBUG)
#logging.getLogger("simuvex.procedures.libc.strncmp").setLevel(logging.DEBUG)

def getFuncAddress(cfg, funcName ):
	found = [
		addr for addr,func in cfg.kb.functions.iteritems()
		if funcName == func.name
		]
	if len( found ) > 0:
		print "Found "+funcName+"'s address at "+hex(found[0])+"!"
		return found[0]
	else:
		raise Exception("No address found for function : "+funcName)
def get_byte(s, i):
	pos = s.size() / 8 - 1 - i
	return s[pos * 8 + 7 : pos * 8]

def main(app, func):
	project = angr.Project(app, load_options={"auto_load_libs": False})
	cfg = project.analyses.CFG(fail_fast=True)
	addrfun1 = getFuncAddress(cfg, func)
	argv = [project.filename]
	argv1 = '/tmp/input'
	files = {'/tmp/input': simuvex.storage.file.SimFile("/tmp/input", "r", size=30)}
	s = project.factory.entry_state(args=[app,argv1],fs=files)
	path_group = project.factory.path_group(s)
	path_group = path_group.explore(find=addrfun1)
	found = path_group.found
	f1 =  path_group.found[0]
	print f1.state.posix.dumps(2)
	state = path_group.found[0].state
 	files = state.posix.files
	curr_file_id = max(files.keys())
	return state.posix.dumps(curr_file_id)

if __name__ == "__main__":
	
	if len(sys.argv) <2:
		print "wrong usage"
		sys.exit()

	print main(sys.argv[1], sys.argv[2])
```

The excpeted result is that both scripts run return the same string "bbbb" but only the first binary is handled correctly:

```
./solve2.py test1 fun2
Found fun2's address at 0x4006e7!

bbbb
```

```
./solve2.py test2 fun2

Found fun2's address at 0x4006e7!

bbb

```
Am I am doing something wrong, or is there a bug in angr?
I have attached the source and the binaries:
[angr_bug.zip](https://github.com/angr/angr/files/517742/angr_bug.zip)

**Comment by schieb** [comment]
There are a few things going on here...

First of all, malloc does not do any initialization[1]. So when you do something like:
```
text = malloc(fsize + 2);
fd = open("file", flags);
read(fd, text, fsize);
```
the contents of `text[fsize]` and `text[fsize+1]` are undefined (unconstrained in angr parlance). Therefore, "bbb" would be a valid solution if `text[3]` happens contain 'b' after the call to malloc. You can check this by inspecting the bytes returned by malloc after the call to read in angr. You can also see a discrepancy by comparing the bytes at `text` with the output of `posix.dumps(3)` in the "found" state. It is worth noting here that it is possible that `read` actually reads zero bytes[2], in which case an empty file could be a valid solution if malloc gave you a block of memory that happened to start with "bbbb".

Secondly, lseek is currently not implemented as a SimProcedure. So when encountered by angr, it will return an unconstrained value, and not do any seeking in the underlying SimFile.

To make the example work under angr, you could do one of the following:
- explicitly define fsize to 4
- use fopen, fread, and fseek (untested)
- use memset with malloc
- use calloc

As to why it works as expected in test1 but not test2, I have absolutely no idea. I think this should be looked into more closely.

[1] Technically, this behavior is OS specific, but it is good to assume that malloc does no initialization. For an interesting discussion, see [stackoverflow](http://stackoverflow.com/questions/8029584/why-does-malloc-initialize-the-values-to-0-in-gcc).
[2] [read(2)](http://linux.die.net/man/2/read)

**Comment by ltfish** [comment]
> Secondly, lseek is currently not implemented as a SimProcedure. So when encountered by angr, it will return an unconstrained value, and not do any seeking in the underlying SimFile.

This is a note to myself: we should print out warnings when running library functions that do not have a SimProcedure for them.

**Comment by flxflndy** [comment]
Ok thanks for helping me :)
Using a fix size to read the buffer solved the problem for me.
