### ISSUE TITLE
Add support of ['Iop_8Uto24', 'Iop_16Uto24', 'Iop_24to8', 'Iop_24to16'] operations

### ISSUE THREAD

**Issue by DennyDai** [angr/angr#2371]
I'm trying to use angr for AVR binaries, with the lifter in angr/angr-platforms:wip/avr.
AVR has some weird 24-bits values so the lifter will produce some "unsupported" casting operations.
```
['Iop_8Uto24', 'Iop_16Uto24', 'Iop_24to8', 'Iop_24to16']
```

It seems angr has implemented a general method to parse and simulate all Iop_\*to\* operations, and above operations are not supported because they are not added to the list of operations (?).

As a temporary solution, I added
```python
all_operations += ['Iop_8Uto24', 'Iop_16Uto24', 'Iop_24to8', 'Iop_24to16']
```
after [line 70 in irop.py](https://github.com/angr/angr/blob/master/angr/engines/vex/claripy/irop.py#L70), and it works great

but what should be a proper way to add support for those operations?

**Comment by antoniobianchi333** [comment]
@ltfish
