### ISSUE TITLE
Why entry_point option doesn't change the CFG result?

### ISSUE THREAD

**Issue by ymgh96** [angr/angr#2383]
---

I try to use from CFGFast function on a binary in two cases. First I get the CFG from the entry point of the project (entry0), second I set the entry_point option in the project object and get the CFG from another point of the project (main function).<br/>
But gained results are same! why did this happen?<br/>
```
binary_name = "aabb-dddd-with-function"
p1 = angr.Project('../../z_examples/'+binary_name, load_options={'auto_load_libs': False})
p2 = angr.Project('../../z_examples/'+binary_name, load_options={'auto_load_libs': False}, main_opts={'entry_point': 0x400657})\
print(p1.factory.entry_state())
print(p2.factory.entry_state())
cfg_fast1 = p1.analyses.CFGFast()
cfg_fast2 = p2.analyses.CFGFast()
print("It has %d nodes and %d edges" % (len(cfg_fast1.graph.nodes()), len(cfg_fast1.graph.edges())))
print("It has %d nodes and %d edges" % (len(cfg_fast2.graph.nodes()), len(cfg_fast2.graph.edges())))
```
```
<SimState @ 0x400570>
<SimState @ 0x400657>
It has 74 nodes and 92 edges
It has 74 nodes and 92 edges
```

**Comment by rhelmot** [comment]
CFGFast uses a linear scan algorithm, which can pick up blocks that are not referenced from the entry point. You can adjust the recursive descent with several parameters to the CFGFast constructor.
