### ISSUE TITLE
Code is only loaded from CLE and not from Symbion concrete memory

### ISSUE THREAD

**Issue by awto** [angr/angr#2384]
If an interesting function in a shared library, I use Symbion to reach it with concrete execution, but after symbolic execution doesn't work because it only looks for code in CLE, and there are only segments from the main executable. So this works only if I load the shared libraries to CLE, but this won't work if the code is generated in the runtime.

Here is the script excerpt (the full one is in the attachment):

```python
avatar_gdb = AvatarGDBConcreteTarget(avatar2.archs.X86_64, "localhost", 3333)
proj = angr.Project("./main", concrete_target=avatar_gdb,
                    use_sim_procedures=True)
entry = proj.factory.entry_state()
entry.options.add(angr.options.SYMBION_SYNC_CLE)
simgr = proj.factory.simgr(entry)
simgr.use_technique(
    angr.exploration_techniques.Symbion(find=[0x7ffff7fc50f9]))
simgr.run()
found = simgr.found[0]
found.block()
```

This crashes in angr/angr/engines/vex/lifter.py:228 with:

```
Exception has occurred: SimEngineError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
No bytes in memory for block starting at 0x7ffff7fc50f9.
  File "/home/azureuser/angr-dev/angr/angr/engines/vex/lifter.py", line 228, in lift_vex
    raise SimEngineError("No bytes in memory for block starting at %#x." % addr)
  File "/home/azureuser/angr-dev/angr/angr/block.py", line 61, in __init__
    vex = self._vex_engine.lift_vex(
  File "/home/azureuser/angr-dev/angr/angr/factory.py", line 320, in block
    return Block(addr, project=self.project, size=size, byte_string=byte_string, vex=vex,
  File "/home/azureuser/angr-dev/angr/angr/sim_state.py", line 598, in block
    return self.project.factory.block(*args, backup_state=self, **kwargs)
  File "/home/azureuser/ocilab/bugs/run.py", line 24, in <module>
    found.block()
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

Before it looked only in CLE for the code where the shared library isn't loaded to.

[binaries.tar.gz](https://github.com/angr/angr/files/5545547/binaries.tar.gz)
[env.txt](https://github.com/angr/angr/files/5545508/env.txt)

**Comment by degrigis** [comment]
Thank you for opening this, I will look into this asap!

**Comment by XMUsuny** [comment]
You may using proj.loader.dynamic_load() and proj.loader.memory.add_backer() to load shared library at runtime, when it is not loaded as the concrete_target is set.

**Comment by degrigis** [comment]
To mitigate this issue you can either follow @XMUsuny's suggestion or use the ```support_selfmodifying_code=True``` option when creating a state. 
This will force the VEX lifter to fetch code from the `ConcreteTarget` and therefore filling the pages with generated code or library not mapped inside CLE. 
I attach an example script with a slightly modified version of your library `liblib`.

[binaries_2.zip](https://github.com/angr/angr/files/6535925/binaries_2.zip)

**Comment by awto** [comment]
thanks, this works for me
