### ISSUE TITLE
Question:  Text Section Scan in CFGAccurate

### ISSUE THREAD

**Issue by marcusp46** [angr/angr#239]
Good Afternoon,

For testing purposes, I am analyzing a program that simply calls `printf` then exits. 

`auto_load_libs` is enabled and `use_sim_procedures` is disabled.

I am expecting just a few basic blocks, but I get over 100K basic blocks.  Is it the intent of CFGAccurate to generate CFGNodes for unused code in the libraries as well?  This is just for my understanding of the design objectives.  Thanks :)

Marcus

**Comment by ltfish** [comment]
> Is it the intent of CFGAccurate to generate CFGNodes for unused code in the libraries as well?

Yes. If you don't want to include libraries, you can set `auto_load_libs` to False.

**Comment by zardus** [comment]
There might also be quite a few basic blocks pulled in by calling printf. Consider that printf might use malloc, which will pull in all the heap management code, which will pull in the memory management code, error management code, etc.

**Comment by ltfish** [comment]
Clarify: `CFGAccurate` does not perform a linear scan to cover the entire address space. Its CFG recovery algorithm is purely based on connectivity, which is to say, it shouldn't include code blocks that are not reachable* from your starting point.

\* `CFGAccurate` performs forced execution to follow all branches, so unsatisfiable branches are still considered as "reachable".
