### ISSUE TITLE
gdb dump memory file explore?

### ISSUE THREAD

**Issue by Matr1X-00** [angr/angr#2391]
I used the gdb command "dump memory"  to get a file.Here is in IDA.

![image](https://user-images.githubusercontent.com/74032171/99529452-c9c9ff80-29da-11eb-99f6-51b789848fd6.png)

I want to use angr to get the string in esi.
Here is my script.

```
proj = angr.Project("./disass", load_options={
    'main_opts': {
        'backend': 'blob',
        'arch': 'i386',
    },
})
print(proj.loader)
init_state = proj.factory.blank_state(addr=5)
pwd = init_state.solver.BVS('pwd',8*16)
init_state.memory.store(0x100000,pwd)
init_state.regs.esi = 0x100000
init_state.regs.edx = 0
init_state.regs.eax = 0
init_state.regs.ebx = 0
init_state.regs.edi = 0

print("**debug**")
#print(init_state.regs.edx)
#print(init_state.regs.esi)
print(init_state.regs.ip)
print(init_state.memory.load(0x100000,128))

sm = proj.factory.simgr(init_state)
is_good = 0x2B9
is_bad = 0x2B4
sm = sm.explore(find = is_good,avoid = is_bad)
#print(init_state.regs.ip)
found = sm.found

if len(found) > 0:
    result = found[0].solver.eval(pwd,cast_to = bytes)
    print(result)
else:
    print("failed!")
```

The result is no found.I'm confused.
Looking forward to your reply.

**Comment by rhelmot** [comment]
You haven't provided enough information to figure out what's wrong. Your script specifies you're trying to find address 0x2b9, but this is not included in your disassembly dump and there are no jumps to it.

**Comment by Matr1X-00** [comment]
I'm sorry.
Here is the gdb memory dump file.
[gdb_memory_dump_file](https://github.com/Matr1X-00/hide_on_bush/blob/main/disass)

**Comment by rhelmot** [comment]
It is not possible to reach 0x2b9 without going through 0x2b4 in your script. The maximum value of eax at the branch is 0x1038f6c (i.e `0xff * 0x4e04 + 0xff * 0xb690`, verified using angr), which is definitely less than 0x17ad591. You probably want to pick a different avoid address.

**Comment by Matr1X-00** [comment]
Thanks for your reply.
