### ISSUE TITLE
how to generate a windows  exe file's function call graph w/ symbol names?

### ISSUE THREAD

**Issue by gthaker** [angr/angr#2396]
---

From a single file C program I have build both a Linux  ELF (non-stripped) executable and a windows Debug build (.exe file and .pdb files + a few others). I am able to generate a function call graph for the ELF executable without issues by following:

https://github.com/axt/angr-utils/blob/master/examples/plot_cg/plot_cg_example.py

However, for Windows binary (using the 'pe' backend)  the generated call graph does not show function names symbolically. (I get addresses in the call graph nodes). How can I achieve a windows PE executable file function call graph w/ symbolic names? I have  the corresponding .pdb file, but I don't see a way I can load/use it with angr.

**Comment by rhelmot** [comment]
the state of pdb parsing in python is pretty bleak - there is exactly one library, `pdbparse`, and it doesn't seem to work. I submitted a pull request against it fixing all the bugs I was able to fix, but who knows how well it will scale.
