### ISSUE TITLE
Can I patch so file use angr?

### ISSUE THREAD

**Issue by huhuang03** [angr/angr#2405]
I want change arm so file.

I want jump to B location at A location, and want to nop between A and B if able. And I want **save the change** to so file.

Can I do this by angr, or what other python library can do this? Thank you.

**Comment by ltfish** [comment]
Patcherex is the official binary patching tool that uses angr. However, it does not support ARM.

You may want to take a look at LIEF.

**Comment by huhuang03** [comment]
Thank you! For now I use keystone and change the file directly.
