### ISSUE TITLE
Waiting too long when gnerating CFG?

### ISSUE THREAD

**Issue by fpb1386** [angr/angr#2406]
I went some problem when I want to generate CFG from a large amount binaries.

I use the suggested way "CFGFast()" to generate CFG.

But, in some cases, I enter the following output. 

angr.storage.memory_mixins.default_filler_mixin | Filling register ftop with 8 unconstrained bytes referenced from 0x0 (not part of a loaded object)

And, the generation program will stuck at the CFG generation step.

Could angr provide some timeout mechanism when generating CFG?

Thus, angr could step over some challenging binaries to same a lot of time.

**Comment by ltfish** [comment]
Do you know at which binary angr was stuck? You can post the binary here.

**Comment by fpb1386** [comment]
The binary file is shown in the following:
[nf_tables_api.zip](https://github.com/angr/angr/files/5640577/nf_tables_api.zip)
The analysis of this file is stuck for one hour.

**Comment by fpb1386** [comment]
Another binary file:
[af_irda.zip](https://github.com/angr/angr/files/5647219/af_irda.zip)
The analysis of this file is also stuck for one hour.
