### ISSUE TITLE
Tracer woes on Ubuntu bionic

### ISSUE THREAD

**Issue by edmcman** [angr/angr#2409]
---

**Describe the bug.**

Traces of true on my Ubuntu bionic machine cannot be replayed.

**Environment Information.**

```
angr environment report
=============================
Date: 2020-12-09 15:07:20.605244
Running in virtual environment at /home/ed/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0]
######## angr #########
Python found it in /home/ed/Documents/angr-dev/angr/angr
Pip version angr 8.20.6.1
Git info:
	Current commit e2060225edaf9ac09231ba6d1dd5853c16a98b32 from branch tracing_bandaids
	Checked out from remote ed: https://edmcman@github.com/edmcman/angr
######## ailment #########
Python found it in /home/ed/Documents/angr-dev/ailment/ailment
Pip version ailment 8.20.6.1
Git info:
	Current commit 0002d45d0585104872e12aab2b0bf064c61f2245 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/ed/Documents/angr-dev/cle/cle
Pip version cle 8.20.6.1
Git info:
	Current commit eda15d5a8541492b3bf763391adf36d60b6f66b8 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/ed/Documents/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
	Current commit 9233dc5d00a130b4ffb9ccf5a83631b034226e67 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/ed/Documents/angr-dev/claripy/claripy
Pip version claripy 8.20.6.1
Git info:
	Current commit 8e413620c19faa5851676c92388590ad5b54d92f from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/ed/Documents/angr-dev/archinfo/archinfo
Pip version archinfo 8.20.6.1
Git info:
	Current commit f5712a1fe0fbc315c4e9bbcf96582e139f745b33 from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/ed/.virtualenvs/angr/lib/python3.6/site-packages/z3
Pip version z3-solver 4.8.7.0
Couldn't find git info
######## unicorn #########
Python found it in /home/ed/.virtualenvs/angr/lib/python3.6/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: None
unicorn: <CDLL '/home/ed/.virtualenvs/angr/lib/python3.6/site-packages/unicorn/lib/libunicorn.so', handle 2822b40 at 0x7f784f15f7f0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f78500ecb70>
z3: <CDLL '/home/ed/.virtualenvs/angr/lib/python3.6/site-packages/z3/lib/libz3.so', handle 2a82180 at 0x7f784bff4710>
```

**To Reproduce.**

Run `nose2 tests.test_angr_tracing` from archr on Ubuntu bionic

**Additional context.**

[Here is my analysis of the low-level issue.](https://gist.github.com/edmcman/bd24f2f24549f7ed55fdec1909eab1dc) TLDR: There is a symbolic branch that doesn't matter in libc init.

The larger issue is that there is no permissive mode equivalent before synchronizing with the entry point of the program.  I propose something like the following: https://github.com/angr/angr/compare/master...edmcman:tracing_bandaids

**Comment by rhelmot** [comment]
https://github.com/angr/angr/pull/2441 (specifically the new `fast_forward_to_entry=False` option) should address the specific problem cited here, but there will be a lot more problems moving forward if you are trying to do basic block traces.

**Comment by edmcman** [comment]
Thanks for this!

> but there will be a lot more problems moving forward if you are trying to do basic block traces.

Would you mind elaborating on this?  I am planning on using the archr traces, and I haven't seen any type of tracing in angr besides basic block traces.

I've been fighting with angr to replay even simple traces... I've been wondering if I might be better off trying to import traces that [record more information](https://github.com/panda-re/panda).

**Comment by rhelmot** [comment]
look at the linked PR for a summary of where I got trying to improve angr's trace replay capabilities. Long story short, if you use simprocedures you have to have simprocedures for practically everything because inlined code in libc can break the abstraction boundary, and if you don't use simprocedures you run into the fact that we don't have a way to initialize all the loader data structures, which libc can depend on.

There are various projects floating around to trace using other kinds of artifacts (notably syscall records), but none of them are very stable.
