### ISSUE TITLE
Identifier Analysis does not work with Windows SimOS on Linux

### ISSUE THREAD

**Issue by olaughlj** [angr/angr#2413]
When attempting to use the Identifier Analysis on a PE file on Ubuntu 20.04 with angr 9.0.5002 and python 3.8.5, I received the following exception:

>   File "/home/xxxx/.local/lib/python3.8/site-packages/angr/analyses/identifier/runner.py", line 33, in __init__
>     project.simos.syscall_library.update(SIM_LIBRARIES['cgcabi_tracer'])
> AttributeError: 'SimWindows' object has no attribute 'syscall_library'

This appears to be because SimWindow is not based off SimCGC (like the *ix flavors are) that this attribute does not exist in the class.

As a note this does not seem to occur with angr 9.0.5002 on my Windows machine scanning the same binary and python 3.8.6.

**Comment by ltfish** [comment]
The Identifier analysis does not support non-CGC binaries, as stated [here](https://github.com/angr/angr/blob/master/angr/analyses/identifier/identify.py#L45).
