### ISSUE TITLE
How to let angr correctly identify positive integer and negative integer?

### ISSUE THREAD

**Issue by Asteria-BCSD** [angr/angr#2426]
---

I am analyzing a 32 bit program. I want to eval a symbolic value by `solver`, but the result is unexpected.
Result:
```
hex(solver.min(func_ast))
Out[2]: '0x7ffffff9'
hex(solver.max(func_ast))
Out[3]: '0xfffffff8'
```

I mean in 32 bit program, 0x7ffffff9 is a positive value, 0xfffffff8 is a negative value. But in the result 0xfffffff8 is a return value of `solver.max()`. How to let angr kown it is working with a 32 bit program.
 I will appreciate if someone would answer my question.

**Comment by Asteria-BCSD** [comment]
> I am analyzing a 32 bit program. I want to eval a symbolic value by `solver`, but the result is unexpected.
> Result:
> 
> ```
> hex(solver.min(func_ast))
> Out[2]: '0x7ffffff9'
> hex(solver.max(func_ast))
> Out[3]: '0xfffffff8'
> ```
> 
> I mean in 32 bit program, 0x7ffffff9 is a positive value, 0xfffffff8 is a negative value. But in the result 0xfffffff8 is a return value of `solver.max()`. How to let angr kown it is working with a 32 bit program.
> I will appreciate if someone would answer my question.

```
solver.state.project.arch.bits
Out[6]: 32
```

**Comment by rhelmot** [comment]
it's not about the program being 32-bit, it's that min and max solve for unsigned values. There's no way to change that but you can work with it.

`solver.min(func_ast, extra_constraints=(func_ast.SLT(0),))` will give you the smallest negative result. Technically it will give you the smallest unsigned number whose signed representation is negative, but that's the same as what you want.

**Comment by Asteria-BCSD** [comment]
Thanks very much
