### ISSUE TITLE
Load symbolic memory value, instead of a concrete one

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#244]
When I use symbolic execution to do `path.step()`, the value loaded from memory locations with unknown values are directly set to `0`, instead of a symbolic one like `mem_deadbeef_0_32`.

For example, 

```
c05331a8:   e1d035ba    ldrh    r3, [r0, #90]   ; 0x5a
c05331ac:   e3130004    tst r3, #4
c05331b0:   0a000005    beq 0xc05331cc
```

`[r0, #90]` is a concrete location, with unknown value. Angr loads 0 into r3. This makes `beq 0xc05331cc` only has one successor.

How to configure it correctly, to change the value in r3, from 0 to a symbolic expression?

The situation is similar when dealing with STREX in ARM.

For example:

```
strex   r1, r2, [r3]
```

Angr will directly set `r1` to `0`.

**Comment by zardus** [comment]
Unless you're messing with the default options, any uninitialized access *should* return a symbolic value. Are you sure that this piece of memory is uninitialized? What is it pointing to (i.e., bss, stack, etc)?

**Comment by hypersimple** [comment]
Is there any approach that I can represent memory access by something like [r0 + 4] (the value in memory address (r0 + 4) ), instead of mem_x_32 ?

**Comment by ltfish** [comment]
If you want to do it during symbolic execution (i.e. on a path obtained from symbolic execution in angr), it will require dependency tracking along the path, as well as AST parsing. We don't have any approach that is publically available for you to do it. You can implement it by yourself.

**Comment by zardus** [comment]
This is very possible to implement using SimInspect. You will need to hook
the mem_read event and replace the resulting read value with the AST of the
address. You'll probably want to have your SimInspect hook annotate the ast
(ast.annotate) with a claripy annotation to track the fact that it's the
result of a read, as opposed to the actual value r0+4.

**Comment by hypersimple** [comment]
Is there any way to rewrite a symbolic claripy AST?

For example, replace all the constants in an AST with a certain symbol, or with a certain number.

I can parse an AST, but how to construct one back like using `claripy.BVS()`?

**Comment by zardus** [comment]
There are a few ways to do it.

1. Using `ast.replace` allows you to replace subtrees in the AST with other ASTs. There's also a version of that function (`ast.replace_dict`) that takes a dictionary as a replacement mapping.
2. By creating a Claripy Backend (http://angr.io/api-doc/claripy.html#claripy.backend.Backend). This will allow you to easily process the tree with your backend visitor and return a new AST as the backend object.
3. By manually recreating the AST. You can use the `claripy.ast.BV` constructor and pass in the operation and arguments.

If you know all the constants, then the first option is probably easiest, by passing in a dict of constants->replacements. If the constants are something you have to process, I would go with the second option. The third option is kind of a hack.

**Comment by hypersimple** [comment]
How to do it for constants? For all constants I think I can just enumerate them.

But for programming, if I would like to replace <BV32 r0 + 0x4> with <BV32 r0 + 0x666>, I tried sth like

replacements[claripy.BVS('0x4', 32, explicit_name=True).cache_key] = claripy.BVS(0x666, 32)
replacements[0x4] = 0x666
replacements[claripy.BVS(0x4, 32)] = claripy.BVS(0x666, 32)

ast.replace_dict(replacements)

But none of them works...

**Comment by hypersimple** [comment]
Follow the above, I successfully do it by using 

    replacements = {claripy.BVV(0x4, 32).cache_key:claripy.BVV(0x666, 32)}

For all the constants, is there any better way other than enumeration?

**Comment by zardus** [comment]
The better way, if enumeration is tedious, is to create a claripy backend that does the replacement and then call `new_ast = your_backend.convert(old_ast)`.

**Comment by hypersimple** [comment]
How to replace symbolic memory values in an AST?

For example, the BV is

`<BV32 mem_ffffffa4_11_32>`

I tried 

    replacements[claripy.BVS('mem_ffffffa4_11_32', 32).cache_key] = claripy.BVS('mem', 32)

and 
    replacements[claripy.BVS('mem_ffffffa4', 32).cache_key] = claripy.BVS('mem', 32)

and some other combinations, no one works.

**Comment by zardus** [comment]
When you create the new BVS to use as the replacement, claripy appends a unique identifier to it, making it a different BVS. There are two ways to avoid this:

1. Use the `explicit_name=True` keyword argument when creating the BVS: ```replacements[claripy.BVS('mem_ffffffa4_11_32', 32, explicit_name=True).cache_key] = claripy.BVS('mem', 32)```

2. Use the actual original AST:
```replacements[original_ast] = claripy.BVS('mem', 32)```

**Comment by maxwell-bland** [comment]
Ran into what looks like this problem today. I solved it not by doing AST substitution but by hacking out the following. Not sure if all the other bugs are ironed out, but maybe this will help someone:

(Note that the use of `str(addr)` rather than checking for equivalence in the solver is incorrect but fast, of course.)

```python                                                                                              
def mark_symbolic_read(self, s, addr):                                                  
    l = s.get_plugin('log')                                                             
    for e_objs in [e.objects for e in l.events_of_type('fresh_symbolic_read')]:         
        if str(addr) == e_objs['read_addr']:                                            
            return False                                                                
    l.add_event('fresh_symbolic_read')                                                  
    l.events[-1].objects['read_addr'] = str(addr)                                       
    return True                                                                         
                                                                                        
def tag_memory_write(self, s):                                                          
    addr = s.inspect.mem_write_address                                                  
    if addr.concrete:                                                                   
        return                                                                          
    self.mark_symbolic_read(s, addr)                                                    
                                                                                        
def fresh_symbolic_read(self, s):                                                                                                                                
    addr = s.inspect.mem_read_address                                                   
    if addr.concrete:                                                                   
        return                                                                          
                                                                                        
    if self.mark_symbolic_read(s, addr):                                                
        symbolic_var = s.solver.BVS(f"symbolic_read", 8*s.inspect.mem_read_length)      
        if s.project.arch.memory_endness == 'Iend_LE':                                  
            symbolic_var = claripy.Reverse(symbolic_var)                                
        s.memory.store(addr, symbolic_var, s.inspect.mem_read_length, inspect=False)    
```

Then:

```python
self.entry_state.inspect.b('mem_write', when=angr.BP_BEFORE, action=self.tag_memory_write)     
self.entry_state.inspect.b('mem_read', when=angr.BP_BEFORE, action=self.fresh_symbolic_read)  
```
