### ISSUE TITLE
Loop Control/Unrolling

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#245]
During symbolic execution, is there any way to control the loop unrolling or related behaviors?
Are there any default configurations there?

**Comment by zardus** [comment]
There are two contexts in which your question makes sense:

1. If you're using Veritesting (http://angr.io/api-doc/angr.html#angr.exploration_techniques.veritesting.Veritesting), it does loop unrolling as an optimization to reduce branching. You can control how the loops are unrolled by passing the `loop_unrolling_limit` argument to the underlying analysis (https://github.com/angr/angr/blob/master/angr/analyses/veritesting.py#L167).

2. If you're doing normal symbolic execution, you can use the LoopLimiter (http://angr.io/api-doc/angr.html#angr.exploration_techniques.looplimiter.LoopLimiter) technique to discard paths that are looping more than you want them to. You can also write your own techniques to do this fairly easily. Unfortunately, there doesn't seem to be docs for this at the moment. I opened https://github.com/angr/angr-doc/issues/93 to remind ourselves to get to these when have a moment :-)

**Comment by hypersimple** [comment]
Thanks for the reply.

So how to use the LoopLimiter?

Just insert

    angr.exploration_techniques.looplimiter.LoopLimiter(count=5, discard_stash='spinning')

into the code?

What does the `discard_stash='spinning'` mean?

**Comment by rhelmot** [comment]
```
limiter = angr.exploration_techniques.looplimiter.LoopLimiter(count=5, discard_stash='spinning')
pg = project.factory.path_group(...)
pg.use_technique(limiter)
pg.step(...)
```

The LoopLimiter is an exploration technique (or "otiegnqwvk", a name that I prefer), which means that it's some logic that affects how path groups work, and once you attach it to a path group, the path group will behave differently, in this case dropping all paths that loop for more than 5 times into a separate stash. The `discard_stash` parameter controls the name of the stash that  the looping path will be put into.

**Comment by hypersimple** [comment]
Any way that I can use it on `path`? It seems that it has to be a path_group.

**Comment by rhelmot** [comment]
It has to be a path group. You can wrap a path in a path group by calling `project.factory.path_group(path)`.
