### ISSUE TITLE
Trace seems ambiguous - ASLR slides

### ISSUE THREAD

**Issue by trentn** [angr/angr#2458]
---

**Describe the bug.**

When adding a Tracer technique to a simulation manager, I receive an error:
```AngrTracerError: Trace seems ambiguous with respect to what the ASLR slides are for <ELF Object simple_overflow_stdin, maps [0x555555554000:0x5555555580bf]>. This is surmountable, please open an issue.```

I believe this is related to the changes here: https://github.com/angr/angr/commit/579c50afb11463fba656392e2c2944db6a279d18?branch=579c50afb11463fba656392e2c2944db6a279d18&diff=split#diff-1bc096394f30f61699d3d320830286d1f1844485a65e52a7d9f7c48728af15e4

Specifically the new `_locate_entry_point` and `_filter_idx` functions.

**Environment Information.**

I've replicated this in two slightly different environments. Here is the report for one of them:
```
angr environment report
=============================
Date: 2021-01-05 15:48:02.741997
Running in virtual environment at /opt/venv
Platform: linux-x86_64
Python version: 3.7.9 (default, Oct 13 2020, 21:10:49) 
[GCC 8.3.0]
######## angr #########
Python found it in /opt/venv/lib/python3.7/site-packages/angr
Pip version angr 9.0.gitrolling
Couldn't find git info
######## ailment #########
Python found it in /opt/venv/lib/python3.7/site-packages/ailment
Pip version ailment 9.0.gitrolling
Couldn't find git info
######## cle #########
Python found it in /opt/venv/lib/python3.7/site-packages/cle
Pip version cle 9.0.gitrolling
Couldn't find git info
######## pyvex #########
Python found it in /opt/venv/lib/python3.7/site-packages/pyvex
Pip version pyvex 9.0.gitrolling
Couldn't find git info
######## claripy #########
Python found it in /opt/venv/lib/python3.7/site-packages/claripy
Pip version claripy 9.0.gitrolling
Couldn't find git info
######## archinfo #########
Python found it in /opt/venv/lib/python3.7/site-packages/archinfo
Pip version archinfo 9.0.gitrolling
Couldn't find git info
######## z3 #########
Python found it in /opt/venv/lib/python3.7/site-packages/z3
Pip version z3-solver 4.8.9.0
Couldn't find git info
######## unicorn #########
Python found it in /opt/venv/lib/python3.7/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/opt/venv/lib/python3.7/site-packages/angr/lib/angr_native.so', handle 5635c7e46e30 at 0x7fd6678f7950>
unicorn: <CDLL '/opt/venv/lib/python3.7/site-packages/unicorn/lib/libunicorn.so', handle 5635c70f2c80 at 0x7fd666b9b890>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fd6677c3990>
z3: <CDLL '/opt/venv/lib/python3.7/site-packages/z3/lib/libz3.so', handle 5635c736db50 at 0x7fd6648a8290>
```

**To Reproduce.**

I've include a script and binary to replicate the issue, as well as the files to build the simple binary.
[simple_overflow_stdin.zip](https://github.com/angr/angr/files/5771247/simple_overflow_stdin.zip)

**Additional context.**

I am trying to replicate some functionality that the Rex project performs. So the script is a mash up of code pulled from Rex and various test scripts.

**Comment by rhelmot** [comment]
I believe I've fixed this - the linked issue makes your binary able to begin tracing using the script provided, though it errors out halfway through.

**Comment by trentn** [comment]
I will have to get around to testing this. As a follow up for now:

Since posting the issue originally, I've been using a workaround I implemented in archr (https://github.com/trentn/archr/tree/strace_parsing) to extract the library offsets from QEMU's strace output. (this isn't a foolproof method - other stuff in stderr can really mess with the parsing - which is why I have not put in a pull request in archr). This allows me to turn off the 'aslr' option.
