### ISSUE TITLE
Angr can not identify functions.

### ISSUE THREAD

**Issue by shouguoyang** [angr/angr#2463]
---

**Describe the bug.**

After get the cfg with `project.analyses.CFGFast()`, I iterate the `cfg.function` and print all function names.
The result shows angr can only identify part of them. So so many results are like below:
```
sub_81d948
sub_81d960
sub_81d9a3
sub_81d9b0
sub_81d9dc
sub_81d9f7
sub_81da56
sub_81da60
sub_81dacd
sub_81db02
sub_81db10
sub_81dbd6
sub_81dbe0
sub_81dc4c
sub_81dd7b
sub_81dd80
sub_81ddcb
sub_81ddd0
sub_81de37
sub_81deab
sub_81df2a
sub_81dfb6
sub_81e054
sub_81e060
sub_81e0c9
sub_81e0d0
sub_81e12c
sub_81e130
sub_81e156
sub_81e160
sub_81e1a7
sub_81e1b0
sub_81e372
sub_81e380
sub_81e3a9
sub_81e3b0
sub_81e462
sub_81e470
sub_81e52f
sub_81e530
sub_81e5bf
sub_81e5c0
sub_81e5e5
sub_81e5f0
sub_81e644
sub_81e66b
sub_81e6a5
```
Angr can get the 737 function names but 1694 function names in IDAPro results.

**Environment Information.**

**To Reproduce.**

**Additional context.**

[freetype-2.4.zip](https://github.com/angr/angr/files/5781116/freetype-2.4.zip)

**Comment by ymgh96** [comment]
I have the same problem on CGC binaries like CROMU_00036 from [this repository](https://github.com/zardus/cgc-bins/tree/master/all_unpatched). I try two below codes and the results are same.
```
idfer = proj.analyses.Identifier()
for funcInfo in idfer.func_info:
    print(hex(funcInfo.addr), funcInfo.name)
```
Or
```
cfg_fast = proj.analyses.CFGFast()
for z_node in cfg_fast.graph.nodes():
    print(cfg_fast.kb.functions[z_node.addr].name)
```
