### ISSUE TITLE
fail to retrieve NT_FILE note

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#2470]
I just added support for NT_FILE in shellphish-qemu here: https://github.com/shellphish/shellphish-qemu/commits/wip/halfway_tracing

Now the coredump generated by QEMU will have NT_FILE and `readelf` recognizes it.

Now `angr` is supposed to load libraries separately as standalone ELF objects. However, it loads it as a huge ELFCore object.

**Comment by Kyle-Kyle** [comment]
a samle coredump generated by the patched QEMU is here: https://gist.github.com/Kyle-Kyle/92371cad52f772a38e9a0eed9cf0551b

**Comment by Kyle-Kyle** [comment]
@rhelmot @ltfish

**Comment by rhelmot** [comment]
`[16:51:24] [cle.backends.elf.elfcore] |  WARNING: Could not load /home/kylebot/Desktop/haccs/halfway-tracing/stack_smash; core may be incomplete`

This warning shows up whenever the "inversion" process of turning the core into several smaller objects fails. Are you getting anything similar?

**Comment by Kyle-Kyle** [comment]
yes. I'm debugging this. there are a lot of issues invoved.
1. handling of mappings that are not backed by files is missing
2. how to deal with coredump generated in a remote env(may be just specify the libraries during loader initialization)
3. there is a bug in the parsing of NT_PRPSINFO either in QEMU or pyelftools. (ps: the result of `file` command suggests QEMU's implementation may be correct)

**Comment by rhelmot** [comment]
so 1) you should not include in your dumps NT_FILE entries which do not actually have a filename attached, 2) I agree this is not something which is fixed yet, I will add a switch to help with this, and 3) can you elaborate?

**Comment by Kyle-Kyle** [comment]
1) you are right, I'm going to fix my patch in QEMU
3) it is used to retrieve the name of the executable from the core dump. `file <coredump>` gives me the correct executable name but pyelftools gives me some trash followed by the correct name. I'm reading the source code of `QEMU`, `pyelftools` and `Linux` to figure out which is correct.

**Comment by rhelmot** [comment]
just pushed a wip/halfway_tracing to cle which adds the remote filename mapping feature. untested, but it should be pretty basic

**Comment by Kyle-Kyle** [comment]
thanks!

**Comment by rhelmot** [comment]
```
[+] In [11]: d[1].n_desc.pr_fname                                                                                                                                                                                                                         
Out[11]: b'stack_smash\x00\x00\x00\x00\x00'

[+] In [12]: d[1].n_type                                                                                                                                                                                                                                  
Out[12]: 'NT_PRPSINFO'
```

seems to be working for me?

**Comment by Kyle-Kyle** [comment]
ah. the core dump I sent you is 64bit, which is correct. the bug is in 32bit version. (and it is a bug, confirmed by kernel code)
If you are interested. 
here is the patch
~~~
diff --git a/elftools/elf/structs.py b/elftools/elf/structs.py
index b9203c6..0c6a809 100644
--- a/elftools/elf/structs.py
+++ b/elftools/elf/structs.py
@@ -389,10 +389,10 @@ class ELFStructs(object):
                 self.Elf_xword('pr_flag'),
                 self.Elf_half('pr_uid'),
                 self.Elf_half('pr_gid'),
-                self.Elf_half('pr_pid'),
-                self.Elf_half('pr_ppid'),
-                self.Elf_half('pr_pgrp'),
-                self.Elf_half('pr_sid'),
+                self.Elf_word('pr_pid'),
+                self.Elf_word('pr_ppid'),
+                self.Elf_word('pr_pgrp'),
+                self.Elf_word('pr_sid'),
                 String('pr_fname', 16),
                 String('pr_psargs', 80),
             )
~~~

**Comment by rhelmot** [comment]
Opened https://github.com/eliben/pyelftools/pull/348 for it

**Comment by Kyle-Kyle** [comment]
lol. I also opened PR. 
whatever. as long as it is fixed

**Comment by Kyle-Kyle** [comment]
For future reference. If a bug like this happen in ELFCore, it's because QEMU somehow fucks up auxv. I tried to fix it in QEMU. But it disappeared after I inserted my debug code.
~~~
~/src/angr-dev/cle/cle/loader.py in _internal_load(self, preloading, *args)
    655                 l.info("Skipping load request %s - already loaded", main_spec)
    656                 continue
--> 657             obj = self._load_object_isolated(main_spec)
    658             objects.append(obj)
    659             objects.extend(obj.child_objects)

~/src/angr-dev/cle/cle/loader.py in _load_object_isolated(self, spec)
    837             l.debug("... loading with %s", backend_cls)
    838 
--> 839             result = backend_cls(binary, binary_stream, is_main_bin=self.main_object is None, loader=self, **options)
    840             result.close()
    841             return result

~/src/angr-dev/cle/cle/backends/elf/elfcore.py in __init__(self, executable, remote_file_mapping, *args, **kwargs)
     34         self._remote_file_mapping = remote_file_mapping if remote_file_mapping is not None else {}
     35 
---> 36         self.__extract_note_info()
     37 
     38         self.__reload_children()

~/src/angr-dev/cle/cle/backends/elf/elfcore.py in __extract_note_info(self)
     76                         self.__parse_prpsinfo(note.n_desc)
     77                     elif note.n_type == 'NT_AUXV':
---> 78                         self.__parse_auxv(note.n_desc.encode('latin-1'))
     79                     elif note.n_type == 'NT_FILE':
     80                         self.__parse_files(note.n_desc)

~/src/angr-dev/cle/cle/backends/elf/elfcore.py in __parse_auxv(self, desc)
    245                 value = bytearray()
    246                 while True:
--> 247                     byte = self.__dummy_clemory[pos]
    248                     if byte == 0:
    249                         break

~/src/angr-dev/cle/cle/memory.py in __getitem__(self, k)
    235                     except KeyError:
    236                         pass
--> 237         raise KeyError(k)
    238 
    239     def __setitem__(self, k, v):

KeyError: 15
~~~

**Comment by Kyle-Kyle** [comment]
4 bytes of auxv some how gets omitted. It may have something to do with how QEMU rounds up the name size. But I'm not sure.

**Comment by Kyle-Kyle** [comment]
Everything related to NT_FILE has been resolved. Now core dumps can be loaded successfully into `angr`. And most importantly, it's not a hack. Thank you for the help @rhelmot 
It's time to lose this issue.
