### ISSUE TITLE
AttributeError: 'AnnotatedCFG' object has no attribute 'model'

### ISSUE THREAD

**Issue by kzLiu2017** [angr/angr#2478]
When I used the annotated cfg(acfg) from backward slice as a parameter of explore(find = 0x500140, cfg = acfg), I got an error "AttributeError: 'AnnotatedCFG' object has no attribute 'model'". And I didn't find how to get another type cfg from a backward slice. Can you give me some advice. Thanks so much.

---

**Comment by rhelmot** [comment]
the explorer is not designed to take a CFG for the purposes of only executing a slice, it only uses the CFG to quickly test whether addresses are reachable from other addresses. If you want to execute a slice, you should use the Slicecutor exploration technique.
