### ISSUE TITLE
Help solving an exercise

### ISSUE THREAD

**Issue by frala19871987** [angr/angr#250]
Hi,
I'm trying to solve the following challenge: https://www.root-me.org/en/Challenges/Cracking/ELF-CrackPass. The binary is stripped and with a check with a ptrace ( i patched it ). I was trying to solve it using the following code:

```
import angr

FIND_ADDR = 0x8048630
AVOID_ADDR = (0x8048632, 0x804869f)
MAIN_START = 0xf7e0e540


def main():
    proj = angr.Project('./Crack', load_options={"auto_load_libs": False})
    argv1 = angr.claripy.BVS("argv1", 0xE * 8)
    initial_state = proj.factory.entry_state(args=["./Crack", argv1])

    initial_path = proj.factory.path(initial_state)
    path_group = proj.factory.path_group(initial_state)
    path_group.explore(find=FIND_ADDR, avoid=AVOID_ADDR)
    found = path_group.found[0]
    return found.state.se.any_str(argv1)


if __name__ == '__main__':
    main()
```

Unfortunately the right path is not found. Can anyone help me to solve it please?

Thanks

**Comment by schieb** [comment]
Why are you avoiding 0x804869f?

**Comment by frala19871987** [comment]
Hi,
because it is print an error message there if the password is wrong.

Thanks

**Comment by schieb** [comment]
In the binary that I downloaded, avoiding 0x804869f completely eliminates the possibility of finding the win state at 0x8048630. Perhaps your version is different - you did mention that you patched it.

Could you please upload your version?

Also, I noticed that it calls `__ctype_b_loc` which is currently not implemented in simuvex, although it may not actually matter in this case. @Itfish Are you still thinking about [adding a warning when running unimplemented `SimProcedures`](https://github.com/angr/angr/issues/237#issuecomment-252535913)?

**Comment by schieb** [comment]
One more thing, it looks like the precision flag in format string is unimplemented (or incorrect). So, as of now, angr cannot solve this natively.

**Comment by frala19871987** [comment]
@schieb Thanks for your help. I patched only the ptrace call and I think it does not matter to angr anyway.

I hope @ltfish can tell us if it will be possible in the future.

Thanks

**Comment by zardus** [comment]
@frala19871987, the way to currently deal with the precision format string would be to hook the call with some python code that approximates the effects. Making these one-off hooks generally helps angr a lot with these sort of binaries.

Alternatively, you can implement precision support for format strings! We'd really appreciate that, but dealing with symbolic data in format strings is pretty hard. If you're interested, the relevant code is here: https://github.com/angr/simuvex/blob/master/simuvex/s_format.py
