### ISSUE TITLE
CFGFast Endless Loop

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#251]
Hello again, 

i'm having another - rather unusual case here.  I'm analyzing parts of openssl_1.0.1f static library (ssl_txt.o) in libssl.a, compiled with android cross compilier using clang. The text section size is 668 bytes and CFGFast leads to an endless loop, e.g. the estimated remaining time does not even show up. So the problem lies within the initialization i suppose. 

I had this problem a couple of times when i analyzed android art compiled files (.oat) which is a bit hacky because of loading problems, so i didn't report until now. But now it happened with a quite regular binary.

[ssl_txt.zip](https://github.com/angr/angr/files/546252/ssl_txt.zip)

A good new week :) - I'm clueless on this one

**Comment by zardus** [comment]
@ltfish is our only hope :-)

**Comment by rhelmot** [comment]
So it's certain that it's a bug if cfgfast doesn't terminate, but angr is absolutely not equipped to analyze static libraries right now. It does not have the correct relocations implemented.
