### ISSUE TITLE
SimSegfaultException: Stack page initialization can cause invalid heap collision error

### ISSUE THREAD

**Issue by trentn** [angr/angr#2516]
---

**Describe the bug.**

A binary that accesses the stack in a non-linear pattern, can cause a `SimSegfaultException(STACK_ADDRESS (stack collided with heap)` error.

This occurs in `angr/storage/memory_mixins/paged_memory/stack_allocation_mixin.py` when angr initializes a stack page and updates the `red_pageno` but "skips" a page. If the program later accesses the uninitialized "skipped" page, it can trigger the heap collision check even though it should be a valid stack page access and a page should be initialized. The heap collision will trigger when trying to initialize the page preceding the new `red_pageno` page. 

This happens when the binary has a function with a stack frame larger than one page in size, and first writes stack memory more than one page beyond what has been initialized, and then writes to memory in the 'hole'.

An abstract example:
Angr attempts to initialize stack pages in this order:
0x7fffffffffef -> 0x7fffffffffee -> 0x7fffffffffec -> 0x7fffffffffed.
Upon initializing 0x7fffffffffed, a heap collision error will be triggered because 0x7fffffffffec is the `red_pageno`.

**Environment Information.**

```
angr environment report
=============================
Date: 2021-02-04 12:11:44.690975
!!! runninng in global environment.  Are you sure? !!!
Platform: linux-x86_64
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/trent/angr/angr
Pip version angr 9.0.gitrolling
Git info:
        Current commit 5c264a51f6f62a17a4bb88e8e8bbbf601e961943 from branch master
        Checked out from remote origin: http://github.com/angr/angr
######## ailment #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/ailment
Pip version ailment 9.0.gitrolling
Couldn't find git info
######## cle #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/cle
Pip version cle 9.0.gitrolling
Couldn't find git info
######## pyvex #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/pyvex
Pip version pyvex 9.0.gitrolling
Couldn't find git info
######## claripy #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/claripy
Pip version claripy 9.0.gitrolling
Couldn't find git info
######## archinfo #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/archinfo
Pip version archinfo 9.0.gitrolling
Couldn't find git info
######## z3 #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.9.0
Couldn't find git info
######## unicorn #########
Python found it in /home/trent/.local/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/trent/angr/angr/lib/angr_native.so', handle 1c06c70 at 0x7f83328f2100>
unicorn: <CDLL '/home/trent/.local/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 10bfe80 at 0x7f83455091c0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f8346123100>
z3: <CDLL '/home/trent/.local/lib/python3.8/site-packages/z3/lib/libz3.so', handle 13370f0 at 0x7f8342c4dfa0>
```

**To Reproduce.**

I discovered the issue in a much larger binary, so I have written a minimized example that triggers the behavior.
[breaks.tar.gz](https://github.com/angr/angr/files/5928154/breaks.tar.gz)
With newer versions of GCC, you will need to disable stack-collision-protection to compile binaries that exhibit this behavior. (See the included Makefile)

**Additional context.**

I have implemented a work-around to the problem, but it currently relies on a hardcoded stack address prefix.
https://github.com/trentn/angr/commits/stackpage_initialization_fix

Even if I can obtain the initial stack address (and handle cases where this code is executed before having that address) I'm not really convinced that this is the ideal place to catch this bug. Keeping track of the heap and stack pages separately would probably be a better solution.
I haven't managed to grok enough of how the memory management is handled to write such a solution though, and I figured I could at least document the bug for now, with a work-around.

**Comment by rhelmot** [comment]
so like, angr's behavior mirrors linux's behavior precisely, at least from my understanding of the problem. gcc's stack-collision-protection is designed to solve this exact problem; it's a compiler bug otherwise.

I did a bit more reading on the subject and it looks like there does exist a mitigation in linux in the form of [making the guard region 1mb instead of 4k](https://lwn.net/Articles/725832/), so that would be the most "correct" fix.

**Comment by trentn** [comment]
So, the example binary is operating within the initial stack mapping from the kernel - it's not actually jumping past the guard page.

As an aside:
I came across the behavior in a binary which apparently wasn't compiled with the newer `-fstack-clash-protection` option. (I didn't compile it and extracted it from some other target for analysis). From what I can find, there will likely be plenty of software that is also not compiled with that option- seeing as it's only GCC-8+ that has the new feature. 
In fact clang is only JUST getting to implementing a similar feature (https://blog.llvm.org/posts/2021-01-05-stack-clash-protection/). Compiling the example program with the default clang version on Ubuntu 20.04 (10.0.0-4ubuntu1) with default options will produce a binary which triggers the error in angr.

**Comment by rhelmot** [comment]
I see. I've implemented the preallocation in the linked PR, can you test if that solves your problem for you?

**Comment by trentn** [comment]
This solves the particular issue which was triggering the heap error.
