### ISSUE TITLE
Detect tail call for "Ijk_Call"

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#252]
I set something like `path.jumpkinds.hardcopy[-1] == 'Ijk_Call':`, but if the function has a tail call like `b   0xdeadbeef`, the effect to hook function calls like `Ijk_Call` will not be triggered. 
How to detect tail calls in Angr to implement function call hooking?

**Comment by ltfish** [comment]
Why is that a tail call? I think that's a tail _jump_.

angr does not do anything special in terms of detecting tail jumps.

**Comment by rhelmot** [comment]
You probably want to hook on basic-block-start that calls a callback whenever the address is the address of a known function.
