### ISSUE TITLE
Get return value from function call (call_state)

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#253]
If using `proj.factory.call_state;  path = proj.factory.path(state);  path1 = path.step(num_inst=1)` to symbolically execute a function, how to get the return value (r0 in ARM) when the function returns?

I tried to use deadend to find it, but there is no deadend for `pg = proj.factory.path_group(path)` found.

I also tried to directly return the `r0` value when the execution finishes, but it only returns one path's value and usually an "over-executed" one.

I also tried to find return-like instructions at the end or middle of the function, regarding it as a hooking point. But there is no such hook, and usually there are tail calls or something else at the end of a function.

**Comment by rhelmot** [comment]
call_state can take a parameter for the address it should return to! Set it to return to a special address and then run pathgroup.explore to search for that address.

**Comment by hypersimple** [comment]
I set  `ret_addr` to `0xdeadbeef` in `call_state`. 
But if checking PC value for each step, I found the execution flow never goes there (and no error exists either).

**Comment by rhelmot** [comment]
Well then where is it stepping? It sounds like execution is either getting stuck somewhere or going off the rails at some point. You should follow a single path and see if it's going where you expect.
