### ISSUE TITLE
ClaripyOperationError when ADC+RCR

### ISSUE THREAD

**Issue by ercoppa** [angr/angr#254]
Hi,

I am analyzing a obfuscated binary that contains the following x86 code:

```
adc cx, di
rcr cl, 0x7b 
```

But my path ends as _errored_:

```
(Pdb) pg.errored[0].error
ClaripyOperationError("args' length must all be equal",)
```

From my understanding this is due to line 311 (function `pc_actions_ADC`) in `simuvex/vex/ccall.py`:
`arg_r = cc_dep2 ^ old_c`
In particular, the _extra check_ (`length_same_check`) performed on the arguments of operator `^` fails. By adding a breakpoint in `pc_actions_ADC()`, I can see that `cc_dep2` is 16 bits, while `cc_ndep` (`old_c = cc_ndep & data[platform]['CondBitMasks']['G_CC_MASK_C']`) is 32 bits. Interestingly, in `pc_calculate_rdata_all_WRK`:

```
cc_dep1_formal = cc_dep1_formal[nbits-1:0]
cc_dep2_formal = cc_dep2_formal[nbits-1:0]
# TODO: does ndep need to be extracted as well?
```

It seems that the answer should be yes at least in the context of ADC. Am I wrong? 
However, if I do that I have other `ClaripyOperationError`s later on.

**Comment by zardus** [comment]
It definitely looks like a bug on our side! @ltfish or @rhelmot, do you have a moment to look into this? Otherwise, I'll try to get to it when I get back from CCS.

**Comment by ltfish** [comment]
I can confirm it is a bug on our side. Not sure if I have time to get to it before next week though.

**Comment by zardus** [comment]
@rhelmot just pushed a fix to gitlab. We just need to make sure all is good and then push it out.

**Comment by ltfish** [comment]
SimuVEX commit f6134e89 and 8db040ee should fix this issue. Please pull the latest simuvex from GitHub before we make the next release. Thanks for reporting!

**Comment by ercoppa** [comment]
Thank you for the fix. Meanwhile, I have done a similar fix locally. The only difference wrt your fix is that on line 323 in `simuvex/vex/ccall.py`. Your commit:

    of = ((arg_l ^ arg_r ^ -1) & (arg_l ^ res))[0]

My fix:

    of = ((arg_l ^ arg_r ^ -1) & (arg_l ^ res))[nbits-1]

With your fix I don't get the right result when running:

        clc
        movb    $100, %al
        movb    $100, %cl
        adcb    %al, %cl
        jo  over
        jc  carry
    down:
        movl    $0, %eax
        jmp end
    over:
        movl    $1, %eax
        jmp     end
    carry:
        movl    $2, %eax
    end:
        // eax should be 1 but is 0
        ret

I think your fix is wrong, but please double check my fix since I am not sure that it's right.

**Comment by rhelmot** [comment]
If you see your fix producing correct results that my fix doesn't, your fix is probably right! I just did something I thought it would work and checked it against the example in the OP, without consulting any outside knowledge about the desired effect of the computation.

Could you submit a pull request making that change and then updating angr/tests/test_rcr.py to test for the correct behavior? You can add your sample code as a pull request on the binaries repo too, if you like.

**Comment by ercoppa** [comment]
I have done three PR:
- angr/simuvex#41: fix the issue 
- angr/binaries#8: i386 binary
- #267: test script

I did not touched test_rcr.py since the related binary has not been yet pushed to angr/binaries

**Comment by rhelmot** [comment]
Merged. Did you want to make any changes to test_rcr?

**Comment by ercoppa** [comment]
No. Thank all of you.

You can close the issue.
