### ISSUE TITLE
ReachingDefinitionsAnalysis ListIndexError

### ISSUE THREAD

**Issue by swthorn** [angr/angr#2546]
---

Getting an error when I run ReachingDefinitionsAnalysis on some binaries pointing to this line: https://github.com/angr/angr/blob/master/angr/analyses/reaching_definitions/engine_vex.py#L183 

Couple of questions related to this:
- CFGFast MUST be generated before doing a ReachingDefinitionsAnalysis. Should it be this way? This is probably a good assumption but I was using a CFGEmulated. Wondering if this can be changed to just use any CFG that's available?
- this get_all_nodes() function is returning an empty list in my situation and I'm getting a ListIndexError. Could this be because of a decoding/lifting error in my binary - a bunch of these errors print when I load the binary.

For now, I have made the following change in my local version of angr:

```python

function_address = (
self.project.kb
    .cfgs['CFGFast']
    .get_all_nodes(self._codeloc().ins_addr, anyaddr=True)[0]
    .function_address if len(self.project.kb
                             .cfgs['CFGFast']
                             .get_all_nodes(self._codeloc().ins_addr, anyaddr=True)) > 0 else 0
)
```

**Comment by mahaloz** [comment]
Hi @swthorn in the past RDA was only CFGFast I believe, but now it appears to support Emulated based on this line: https://github.com/angr/angr/blob/b0f9ec9ba721efc88cf6f29242c902806256b7e0/angr/analyses/reaching_definitions/reaching_definitions.py#L144 

To fix this, we just need to get the most accurate CFG, if I am looking at your code right @Pamplemousse.
