### ISSUE TITLE
ConvenientMappingsMixin can be optimized

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#2548]
need to build a ChainMapCOW to delay the addition of new children

**Comment by ltfish** [comment]
I profiled it under CPython only, and under influence of a 103 fever. Can you profile it again with PyPy to see if `ChainMap.new_child()` really causes a 20% slowdown?

**Comment by ltfish** [comment]
https://github.com/angr/angr/pull/2555 is merged. Close this issue.
