### ISSUE TITLE
A quality problem / bug

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#255]
Sry Itfish :/

Today i'm coming with something i noticed lately. It's about the knowledge base / functions for statically linked ARM-32 binaries. It's not a bug I think, well maybe it's both a bug and a quality problem.

Situation: 
I have a function - starting at some Address, let's say 0xC. This function is correctly identified in the knowledge base, however it's got exactly 1 block instead of 6.
And then .. i have a second function in the knowledge base, lets say Address 0xA. And it has the needed 6 blocks. However, the function starts with an `andeq foo`, meaning a nop. The correct function entry 0xC has a correct [usually used] function prologue `push stuff` but missing blocks. And this does not happen only with andeqs, but also with.. other stuff like `bleq, andhi, ...`.

`In [10]: len(list(b.kb.functions.get(0x80C0C).blocks))`
`Out[10]: 1`

`In [3]: b.factory.block(0x80C0C).capstone.pp()`
`0x80c0c:   push    {r4, r5, r6, r7, r8, sb, sl, fp, lr}`
`0x80c10:   ldrb    r7, [r0, #5]`
`0x80c14:   sub sp, sp, #0x1c`
`0x80c18:   ldrb    r6, [r0, #4]`
`0x80c1c:   ldrb    r3, [r0, #1]`
`...`

`In [11]: len(list(b.kb.functions.get(0x80C08).blocks))`
`Out[11]: 6`
`In [5]: b.factory.block(0x80C08).capstone.pp()`
`0x80c08:   andeq   sl, r7, r0, ror r8`
`0x80c0c:   push    {r4, r5, r6, r7, r8, sb, sl, fp, lr}`
`0x80c10:   ldrb    r7, [r0, #5]`
`0x80c14:   sub sp, sp, #0x1c`

For testing purposes i wrote a badly written and possible idiotic testing skript to preprocessing functions. I want the functions with the correct number of blocks. So basically what i do is to check all function entries, record them in a dictionary. If a function entry has weird andeqs, eors, ... at the beginning i remove the them and recalculate the entry address. If the entry address is already recorded in the function dict, i'll check which of the two functions has the bigger number of blocks. And it yields way better results. 

```
`func_dict = {}         
for f in b.kb.functions.items():
    entry = f[1].get_node(f[0])
    if entry is not None and check_function_entry(b, f) == True:
        func_entry_block = b.factory.block(f[0])            

        # NEW
        #print "real", real_entry_addr
        i = 0                
        while i < len(func_entry_block.capstone.insns) and func_entry_block.capstone.insns[i].insn.mnemonic == 'andeq' : # maybe add eor
            i += 1

        new_func_entry = func_entry_block.capstone.addr + i*4

        #print "new", new_func_entry

        if func_dict.has_key(new_func_entry) == True:
            if b.kb.functions.get(new_func_entry) is not None and len(list(b.kb.functions.get(f[0]).blocks)) >  len(list(b.kb.functions.get(new_func_entry).blocks)):
                func_dict[new_func_entry] = f
        else:
            func_dict[new_func_entry] = f´
```

`In [6]: funcs = analysis.semantic_transform.function_sanatizer.pre_prepare_funct
   ...: ions(b, 0)`
`In [7]: len(funcs)`
`Out[7]: 7964`

`In [8]: len(b.kb.functions.items())`
`Out[8]: 9224`

The reduction with only removing beginning andeqs from entry blocks and acceping only the funciton with a larger number of blocks leads to a function reduction of 1200. So this basically is no small quality issue. 

I'm not sure if thats intended, or on the todo list. I think in the long run a predefined function prologue option for the knowledge base would be good, or move predefined prologue checks in process irrational functions. However, the main problem that 2 equal functions have a different amount of blocks is quite annoying, especially if the wrong entry point has the correct number of blocks.

Greetings

**Comment by ltfish** [comment]
We already have similar functionalities implemented in `CFGFast` - take a look at `CFGFast._remove_redundant_overlapping_blocks()`. Currently there is only logics for x86 and x64 binaries (fully covering GCC and clang, partially covering MSVC). If you want, you can add a check of the current architecture, and put your preprocessing (in fact it's postprocessing for basic blocks) code there. PR welcome!
