### ISSUE TITLE
Need coherent database for storing performance results

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#2553]
It is basically impossible to track performance regressions in angr. Here are some thoughts on a good way to make this less of a nightmare:

- We should have a standard perf test format, ideally a module containing a single `main` function which takes 40-60 seconds to run. Then, there should be a script to run the test and then store the performance data into a database
- This database should contain enough information to differentiate any two runs from each other. It doesn't necessarily need to contain info for a reproducable build, but it should at least hash the current git hashes + any modified files of pyvex archinfo angr etc, as well as the current pip freeze.
- If there are any modified files the user should be prompted to describe what exactly is being changed/tested. building this into the workflow will save us a lot of headache.
- The database should also contain machine spec info, most importantly so that we can identify changes that come from switching machines, and as a secondary concern so that we can tell what cpu/memory features contribute to what kinds of performance.
- The script should make some attempt to isolate the performance characteristics of a machine by erroring out if the system utilization is too high or a laptop is not plugged in. basic stuff like that.
- I don't think this is feasible to run in any sort of CI environment because the shared tenancy will create too much noise. If we want to have this set up as nightly, it should be a cronjob on a dedicated machine.

**Comment by zardus** [comment]
We do have the resources to devote a dedicated server to CI right now. That
might be the route for the perf tests?

**Comment by rhelmot** [comment]
https://github.com/rhelmot/perfharness now exists. It should be trivial to hook up to a cronjob.

![image](https://user-images.githubusercontent.com/2498805/110742744-1dfc2800-81f4-11eb-9200-2a35d9d10ded.png)
