### ISSUE TITLE
Identify Basic block error?

### ISSUE THREAD

**Issue by Ma5ker** [angr/angr#2557]
---

The problem:
Angr shows  different basic blocks from QEMU and handle bbl in different ways on different program.

When using angr to analyze this program 
[KPRCA_00023_bin.zip](https://github.com/angr/angr/files/6116471/KPRCA_00023_bin.zip), it shows different bbls from QEMU.

Here is the diff point:
![result](https://user-images.githubusercontent.com/26860295/110643049-9f50bc00-81ee-11eb-883b-4326bf2b9b04.png)

angr doesn't split the basic block into two bbl( 0x8048710 ~ 0x8048716 and 0x804871b ~ 0x8048729),but qemu result have two bbl addr( 0x8048710 and  0x804871b ), which will cause a sync error when using `Tracer`, shown in the image

![angr_00023](https://user-images.githubusercontent.com/26860295/110643878-81d02200-81ef-11eb-871a-2b11e5002a1c.png)
  
However when I test it with another similar sample, angr shows different result.

![result2](https://user-images.githubusercontent.com/26860295/110644946-8ba65500-81f0-11eb-9dea-e826abd1eadc.png)

Why different bbl result on similar inst or anything wrong with my understandingof it?

**Comment by Ma5ker** [comment]
sorry for my poor English

**Comment by ltfish** [comment]
This is because we treat `call $+5; pop reg` as a get_pc pseudo instruction. You need to align angr traces and Qemu traces manually and handle such cases.

**Comment by rhelmot** [comment]
In general, we have a million edge case detections in `tracer.py` in order to fix divergences like this. If you want, you can add this case to there and give us a pull request, we would really appreciate that!
