### ISSUE TITLE
Clean up states for each execution run

### ISSUE THREAD

**Issue by hypersimple** [angr/angr#256]
I tried to run Angr for two different binaries. But there are usually errors existing for the second one.
I already re-assign values to `state`, `proj`, `path`, `pathgroup`, and put them into a function, regard them as local variables. But it seems there is still something remaining there, like memory unit symbols. And therefore some path execution error exists in path.step().

Since I need to use result saved from the first binary, and compare it to the second one.

How to completely clean up these states and get a healthy run?

**Comment by salls** [comment]
Do you mean you are making two different angr.Project instances and the second one doesn't work correctly. And if you close Python and run the second one on its own it works correctly?

Could be some caching gone wrong. If you have any more details to help me reproduce the problem, I would appreciate it

**Comment by hypersimple** [comment]
I think it might be cache issues. If I insert a `print 'PC:',path.state.regs.pc`, the problem seems gone... But do not know if it can exist elsewhere.

**Comment by ltfish** [comment]
This is very weird... can you please give us your script and binaries that you are working on, so we can debug it locally?
