### ISSUE TITLE
Multi-thread problem when using Symbion

### ISSUE THREAD

**Issue by XMUsuny** [angr/angr#2575]
Hi, I'm using Symbion to synchronize angr with a tcp server after the server receives a tcp packet. This server creates new thread to handle this event. I simply set the decision address to the address of the "recv" function. However, I find that the gdbserver exits during synchronization. I have tested other server such as vsftpd and it works well (with only one thread).
So, could you give me some suggestions for this multi-thread problem?

**Comment by degrigis** [comment]
I know you closed it a while ago, but, is this still an issue for you? If Yes, can you give me an example script?
