### ISSUE TITLE
How to extract the number of parameters used by a function?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#258]
Hi,
is there a way for counting a function parameters before this function is called?

Thanks

**Comment by ltfish** [comment]
Not right now. This is something in development.

**Comment by frapik99** [comment]
Thanks,
how are you approaching it?

**Comment by ltfish** [comment]
Some basic-level data flow analysis on individual functions. It will analyze the calling convention of each function.

**Comment by frapik99** [comment]
Thanks,
I'll wait this update.
