### ISSUE TITLE
Im using angr CFGFast() and Im getting an error.

### ISSUE THREAD

**Issue by anzosasuke** [angr/angr#2581]
---

I was trying to get  cfg = p.analyses.CFGFast()
i Got this error. What am i doing wrong?

ERROR   | 2021-03-30 12:10:20,023 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x848050 of function 0x7987e0.
ERROR   | 2021-03-30 12:10:20,422 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_64HLto128.
ERROR   | 2021-03-30 12:10:20,426 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_64HLto128.
ERROR   | 2021-03-30 12:10:21,519 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_64HLto128.
ERROR   | 2021-03-30 12:10:21,522 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_64HLto128.
ERROR   | 2021-03-30 12:10:31,321 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported statement type CAS.
ERROR   | 2021-03-30 12:10:31,321 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_CasCmpNE64.
ERROR   | 2021-03-30 12:10:31,323 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported statement type CAS.
ERROR   | 2021-03-30 12:10:31,323 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_CasCmpNE64.
ERROR   | 2021-03-30 12:10:31,326 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported statement type CAS.
ERROR   | 2021-03-30 12:10:31,326 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_CasCmpNE64.
ERROR   | 2021-03-30 12:10:31,327 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported statement type CAS.
ERROR   | 2021-03-30 12:10:31,327 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_CasCmpNE64.
ERROR   | 2021-03-30 12:10:38,527 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_ExpCmpNE64.
ERROR   | 2021-03-30 12:10:38,527 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Unop Iop_Clz64.

**Comment by KaneTW** [comment]
Getting this on the current version. What was the resolution?

**Comment by ltfish** [comment]
@KaneTW these “errors” are handled internally by CFGFast. They are just warnings to users and can usually be safely ignored.

**Comment by KaneTW** [comment]
Ah, thanks, got it.
