### ISSUE TITLE
Error in tracer exploration technique due to incorrect return value type

### ISSUE THREAD

**Issue by dnivra** [angr/angr#2586]
**Describe the bug.**

In tracer exploration technique, `crash_windup` has different return types at different parts of function(https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py#L812 vs https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py#L877). This causes a problem because the caller expects an unpackable type to be returned(https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py#L300).

**Environment Information.**

Date: 2021-04-04 15:02:44.184739
Running in virtual environment at /home/dnivra/.virtualenvs/angr-dev
Platform: linux-x86_64
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/dnivra/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
        Current commit 319288d5b349bc9e8748e62f8d0539829cbe379c from branch master
        Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/dnivra/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
        Current commit 7c06ad3ef08063f86016021fcd03aab55b929d0a from branch master
        Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/dnivra/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
        Current commit e027a28b27791246494a6ae5b4c995857485895d from branch master
        Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/dnivra/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
        Current commit ff7e97766b889c5e258dbd0034473aa89ff81259 from branch master
        Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/dnivra/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
        Current commit ebd13139129e900c087964b54d5c3aa0067506d3 from branch master
        Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/dnivra/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
        Current commit 437b194538ccb0bf118b4b674613b88832b0b342 from branch master
        Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.9.0
Couldn't find git info
######## unicorn #########
Python found it in /home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/dnivra/angr-dev/angr/angr/lib/angr_native.so', handle 3288f50 at 0x7f87b5c45d30>
unicorn: <CDLL '/home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 29be8d0 at 0x7f87b5018e20>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f87b5b6a7c0>
z3: <CDLL '/home/dnivra/.virtualenvs/angr-dev/lib/python3.8/site-packages/z3/lib/libz3.so', handle 2c1da40 at 0x7f87b2677a90>

**To Reproduce.**

[This zip file](https://github.com/angr/angr/files/6255431/angr-bug-2586-repro.zip) has script, binary and POV file to reproduce this issue.

**Comment by Kyle-Kyle** [comment]
I think in this special case, where the pointer is concrete but the code is symbolic, you can just return the same state as both last_state and crash_state

**Comment by dnivra** [comment]
Added Kyle's suggestion in [fix/tracer-user-controlled-code-handling-bug](https://github.com/angr/angr/tree/fix/tracer-user-controlled-code-handling-bug). Test case added seems to work fine so guess the fix works fine. Will send PR with this fix after [this PR on binaries repo](https://github.com/angr/binaries/pull/72) is approved and merged.

**Comment by dnivra** [comment]
Fixed in PR #2591.
