### ISSUE TITLE
How to run angr starting from main function instead of a subfunction?

### ISSUE THREAD

**Issue by 040840308** [angr/angr#2589]
Hi, everyone, 

I tried to load a process memory and run angr on it. However, the entry_state or blank_state option always starts from a thread subfunction with a little code, leaving a large of code unexplored. 

Why this happen? Is it possible to explore from the main function automatically? 

Thanks!

**Comment by 040840308** [comment]
> If you know where the main function is, you can manually specify the start address for symbolic exploration:
> 
> ```
> state = proj.factory.blank_state(your_main_func_addr)
> simgr = proj.factory.simgr(state)
> ```
> 
> You may experience other issues when you are running symbolic exploration on a memory dump. For example, due to lack of symbols, SimProcedures may not apply. This might make it difficult for you to even run through `__libc_start_main`.

Thanks first.
If I want to run symbolic exploration on a memory dump, is it possible to identify the main_func_addr automatically instead of specifying it manually?

Thanks

**Comment by rhelmot** [comment]
You can parse it out as the first argument to `__libc_start_main` from the program entry point. angr doesn't have any tool to do this for you automatically, but it's an easy analysis to write. Just symbolically execute the first basic block from the real program entry point and take the first argument from the registers or the stack.

**Comment by ltfish** [comment]
> angr doesn't have any tool to do this for you automatically

Actually we do: https://github.com/angr/angr/blob/master/angr/procedures/glibc/__libc_start_main.py#L146
