### ISSUE TITLE
About Decompiled output.

### ISSUE THREAD

**Issue by anzosasuke** [angr/angr#2590]
---

I want a decompiled output in angr. I got disassembled ouput. I am looking the angr.analyses.Decompiler but I am not able to see the output. Can you please help?

**Comment by mborgerson** [comment]
Try `codegen.text` on the Decompiler Analysis Result. For example:
```python
import angr
p = angr.Project('angr-dev/binaries/tests/i386/fauxware', auto_load_libs=False)
c = p.analyses.CFGFast(normalize=True)
d = p.analyses.Decompiler(p.kb.functions['main'])
print(d.codegen.text)
```

**Comment by anzosasuke** [comment]
Thank you so much.
