### ISSUE TITLE
addr param is ignored when using full_init_state

### ISSUE THREAD

**Issue by quetz** [angr/angr#2599]
**Describe the bug.**
What title says. If state is created using `full_init_state` supplied addr is ignored.

**To Reproduce.**
```
import angr
proj = angr.Project('/bin/ls')
state = proj.factory.full_init_state(addr = 0xdeadbeef)
state2 = proj.factory.blank_state(addr = 0xdeadbeef)
```
At this point state.regs.rip is _loader_addr while state2.regs.rip is 0xdeadbeef as expected.

**Additional context.**
It happens because `kwargs['addr']` gets overwritten here https://github.com/angr/angr/blob/277f84f92867e3d0df5a0b8fd10248f7ff3405c6/angr/simos/linux.py#L374

And while we are at it, what's the reason to have `full_init_state` if it basically forwards everything to `blank_state`?

**Comment by rhelmot** [comment]
The answer to your final question is the reason for your initial question - the point of `full_init_state` is to give you a state that starts at the LinuxLoader simprocedure to run all the initializers. It doesn't give you a fully initialized state, it gives you a state that will be initialized by its execution.

**Comment by quetz** [comment]
Thanks for explanations. Still, it seems like a bug that `addr` param is mentioned in docs, yet it is ignored by `full_init_state`

**Comment by rhelmot** [comment]
You're right! I just fixed it.
