### ISSUE TITLE
Enhancement: Voting in BoyScout

### ISSUE THREAD

**Issue by chubbymaggie** [angr/angr#26]
I am currently analysing a proprietary firmware that has several modules and each runs on different processor. However, when I use `BoyScout` to determine the architecture, it always returns `X86` (due to highest no. of pattern matches). When I print the `votes` dictionary, this is what I get.

`[('X86', 'Iend_LE', 3086), ('AMD64', 'Iend_LE', 3078), ('ARMEL', 'Iend_LE', 118), ('ARMEL', 'Iend_BE', 32), ('MIPS32', 'Iend_LE', 1), ('AARCH64', 'Iend_LE', 0), ('AARCH64', 'Iend_BE', 0), ('PPC64', 'Iend_LE', 0), ('PPC32', 'Iend_LE', 0), ('MIPS64', 'Iend_LE', 0), ('MIPS32', 'Iend_BE', 0), ('MIPS64', 'Iend_BE', 0), ('PPC64', 'Iend_BE', 0), ('PPC32', 'Iend_BE', 0)]`

So, will it be better to print the `vote` dictionary and let the user decide?

**Comment by ltfish** [comment]
You can always get the `votes` dictionary manually and make a decision. `arch` and `endianness` are just based on the voting result. I don't think printing anything out makes any sense, since none of our analysis prints anything out.

**Comment by chubbymaggie** [comment]
I understand.
I have one more question, as in my case, is there anyway I can determine what segment of code runs in what architecture?

**Comment by ltfish** [comment]
I'm afraid angr does not support that right now. We assumes the whole binary belongs to the same architecture.

**Comment by rhelmot** [comment]
isn't the issue more along the lines that boyscout's detection itself is flawed, biased toward architectures with shorter/more prologues?

And couldn't the per-segment arch detection just be implemented by giving boyscout start and end addresses in which to confine the search?

**Comment by ltfish** [comment]
I agree it is flawed in the sense that it biases towards those architectures with shorter/more prologues. The code is not god's words. I'm happy to take any improvements of `BoyScout`.

For the per-segment architecture detection, I think @rhelmot's idea should work, but you should implement start/end support in `BoyScout`, manually load the blob, and specify start/end prior to running your analysis.

> I'm afraid angr does not support that right now. We assumes the whole binary belongs to the same architecture.

To make it clear, I was saying for anything other than `BoyScout`, there is probably no easy way for `angr` to support different architectures for different segments in the same binary.

**Comment by chubbymaggie** [comment]
@rhelmot @ltfish Thank you for your suggestions.
As mentioned by @ltfish it seems there is no easy way for `angr` to support multiple architectures in the same binary. 
However, now I am trying to limit the analysis by giving the `start/end` addresses, which kinda suits my requirement. If I get this right, I am happy to contribute back :)

Thank for the great tool and the support guys :+1:

**Comment by ltfish** [comment]
No problem. You are always welcome :-)
