### ISSUE TITLE
How to wrap run functions?

### ISSUE THREAD

**Issue by hrx1** [angr/angr#2603]
---

Hello,

I'm trying to log system call traces which are simulated during symbolic execution of ELF file. My idea was to decorate SimProcedure.run method, but since angr depends on reflection, it didn't work. Later I wanted to decorate __init__ of SimProcedure, but that didn't work as well.

Can anyone suggest how to log every system call with it's parameters and return value?

Things I've tried are documented here: https://gitlab.com/hSpajic/angr-syscall-trace in files simproc_aspect.py and simproc_aspect_int.py

**Comment by rhelmot** [comment]
You should use SimInspect with the `syscall` breakpoint :) https://docs.angr.io/core-concepts/simulation#breakpoints

**Comment by hrx1** [comment]
> You should use SimInspect with the `syscall` breakpoint :) https://docs.angr.io/core-concepts/simulation#breakpoints

I have successfully created a breakpoint, but breakpoint function takes state as parameter. How to get called system call and it's arguments?

```
import angr
import inspect
import logging

logging.getLogger('angr').setLevel('INFO')

def syscall_before_func(*args):
    print("I've made a syscall")
    print(*args)

if __name__ == '__main__':
    FILE_NAME = 'if_else'

    fd = open('results/' + FILE_NAME + '_bp.systrace', 'w')

    proj = angr.Project(FILE_NAME, load_options={'auto_load_libs': True, 'except_missing_libs': True},
                        use_sim_procedures=False)

    entry = proj.factory.entry_state()
    entry.inspect.b('syscall', when=angr.BP_AFTER, action = syscall_before_func)

    proj.factory.simulation_manager().run()
    simgr = proj.factory.simgr(entry)
    simgr.run()
```

**Comment by rhelmot** [comment]
Try accessing state.inspect.simprocedure? It should contain the instance of the syscall procedure object which can be used to access the arguments and the return value.

**Comment by hrx1** [comment]
state.inspect.simprocedure is set to None, just as simprocedure[_addr | _name | _result].
I have found state.plugins['scratch'].sim_procedure which contains display_name (currently fstat) with num_args = 2, but still cannot find used arguments and return value

**Comment by hrx1** [comment]
Also, breakpoint is set for only one system call (fstat), while with `strace` function I get all of the following (syscall sorted by name, and duplicates removed):
```
access
arch_prctl
brk
close
execve
+++ exited with 0 +++
exit_group
fstat
lseek
mmap
mprotect
munmap
openat
read
write
```

**Comment by rhelmot** [comment]
If you want to see all the syscalls, you will need to load the project with `use_sim_procedures=False` and use a `full_init_state` instead of `entry_state`. Otherwise, we will intercept the syscalls at the libc wrapper level and never make it to the syscall instruction. You might still miss some syscalls since angr doesn't (can't!) emulate the full process of the loader running and mapping the libraries, but those calls aren't very important and don't really vary from binary to binary.

You should be able to use `proc.arg(n)` to load the nth argument of the syscall, and you should be able to access `proc.ret_expr` to load the return value. You'll want to be using the BP_AFTER breakpoint.

**Comment by hrx1** [comment]
I still can't get it to work... Only 1 system call is detected

Code I'm using:
```
import angr
import logging

logging.getLogger('angr').setLevel('WARNING')

def syscall_action_builder(fd):
    def syscall_action_func(state):
        fd.write("I've made a syscall!\n")
    return syscall_action_func

if __name__ == '__main__':
    FILE_NAME = 'if_else'

    trace_fd = open('results/' + FILE_NAME + '_bp.systrace', 'w')

    proj = angr.Project(FILE_NAME, load_options={'auto_load_libs': True, 'except_missing_libs': True},
                        use_sim_procedures=False)

    start_state = proj.factory.full_init_state()
    start_state.inspect.b('syscall', when=angr.BP_AFTER, action = syscall_action_builder(trace_fd))

    simgr = proj.factory.simgr(start_state)
    simgr.run()
```

**Comment by rhelmot** [comment]
Here's the output I get from running your program (slightly modified)

```
I've made a syscall! fstat
I've made a syscall! brk
I've made a syscall! brk
I've made a syscall! read
I've made a syscall! fstat
I've made a syscall! fstat
I've made a syscall! write
I've made a syscall! write
I've made a syscall! lseek
I've made a syscall! lseek
I've made a syscall! exit_group
I've made a syscall! exit_group
```

I'll look into the statically linked case. It's very possible we just don't have a solid enough environment model to support this.

**Comment by rhelmot** [comment]
The statically linked case is experiencing state explosion. This is at least partially because our `readlink` syscall is unimplemented and the program gets into a loop calling it repeatedly. In general, you can debug state explosions by getting a debug shell (`ipython --pdb script.py` and then hitting ctrl-c) and examining `state.solver.constraints` to tell what the source of the symbolicity is.

**Comment by hrx1** [comment]
> Here's the output I get from running your program (slightly modified)

First I used default angr from pip (installed in virtualenv as suggested in a tutorial), which is angr-9.0.6642 (I suppose from looking into `angr-9.0.6642.dist-info` folder). Should I install manually latest version from git?

**Comment by rhelmot** [comment]
Maybe? Try upgrading to 9.0.6790 first. There haven't been any important commits since then. It might also be an issue with angr not supporting the libc on your system - that support is very brittle since we have to emulate a lot of things from the loader.

**Comment by hrx1** [comment]
@rhelmot thank you very much for your time and patience!!!

At first, I used Ubuntu 18.04 and, just to be precautious, I've updated to 20.04. After that, pip automatically installed 9.0.6790 and now script above works. I believe it's because of the angr upgrade, but it's possible that it has to do with ubuntu 18.04

**Comment by hrx1** [comment]
I still cannot get arguments and returned value of syscall. state.inspec.simprocedure is still set to None.
Is it None in your case too?

This is used code:

```
def parse_args(inst, fd):
    if inst.is_continuation or not inst.use_state_arguments:
        fd.write("cannot parse args\n")
        raise Exception("Cannot parse args!")
    return [inst.arg(_) for _ in range(inst.num_args)]

def syscall_action_builder(fd):
    def syscall_action_func(state):
        simproc = state.scratch.sim_procedure
        simproc.state = state
        args = parse_args(simproc, fd)
        simproc.state = None
        fd.write("{}-{}:{}\n".format(simproc.library_name, simproc.display_name, str(args)))
    return syscall_action_func


if __name__ == '__main__':
    FILE_NAME = 'if_else'

    trace_fd = open('results/' + FILE_NAME + '_bp.systrace', 'w')

    proj = angr.Project(FILE_NAME, load_options={'auto_load_libs': True, 'except_missing_libs': True},
                        use_sim_procedures=False)

    start_state = proj.factory.full_init_state()
    start_state.inspect.b('syscall', when=angr.BP_AFTER, action = syscall_action_builder(trace_fd))

    simgr = proj.factory.simgr(start_state)
    simgr.run()
```

**Comment by hrx1** [comment]
@rhelmot I think I solved it. I don't have deeper understanding of the framework, but I think that SimProcedure wasn't passed to 'syscall' breakpoints.

I've added that change to my fork, and the change is visible here: https://github.com/hrx1/angr/commit/6b6b83cc5e4b83b77b405000bfb88cb540a86f1e

**Comment by rhelmot** [comment]
Oh! Yes, that patch is very important, and also very correct. You can submit that as a pull request and I'll hit merge right away.

**Comment by hrx1** [comment]
Here it is https://github.com/angr/angr/pull/2606

I think this issue can be closed. Commit in the pull request wasn't only solution to issues mentioned here. Most of them were solved by rhelmot, and the only cause was my lack of knowledge about this framework - so, rhelmot, thank you very much!

**Comment by rhelmot** [comment]
glad I could help :)
