### ISSUE TITLE
Angr program using explore module seemingly exits before it can get the expected results.

### ISSUE THREAD

**Issue by TacticalCream** [angr/angr#2611]
---

Hey. I'm new to angr and trying to learn how to use it effectively. While looking at a example by John Hammond of angr being used in a ctf challenge (https://youtu.be/RCgEIBfnTEI) I tried to go through and replicate the solution to the challenge. When I recreated the code myself I got a weird warning and no result.

So I found and copied the original code from the writeup (https://github.com/Dvd848/CTFs/blob/master/2020_GoogleCTF/Beginner.md) to check if I had just missed something in my own code, but it still gets the exact same warning and no result:

![image](https://user-images.githubusercontent.com/43989793/115616849-f919cb00-a2f0-11eb-9a21-820133a3e461.png)

I don't know what the issue is, as I have not been able to find anything of use regarding this warning or the perceived problem myself.

The code in question:
```python
#!/usr/bin/env python

import angr
import claripy

FLAG_LEN = 15
STDIN_FD = 0

base_addr = 0x100000 # To match addresses to Ghidra

proj = angr.Project("./a.out", main_opts={'base_addr': base_addr}) 

flag_chars = [claripy.BVS('flag_%d' % i, 8) for i in range(FLAG_LEN)]
flag = claripy.Concat( *flag_chars + [claripy.BVV(b'\n')]) # Add \n for scanf() to accept the input

state = proj.factory.full_init_state(
        args=['./a.out'],
        add_options=angr.options.unicorn,
        stdin=flag,
)

# Add constraints that all characters are printable
for k in flag_chars:
    state.solver.add(k >= ord('!'))
    state.solver.add(k <= ord('~'))

simgr = proj.factory.simulation_manager(state)
find_addr  = 0x101124 # SUCCESS
avoid_addr = 0x10110d # FAILURE
simgr.explore(find=find_addr, avoid=avoid_addr)

if (len(simgr.found) > 0):
    for found in simgr.found:
        print(found.posix.dumps(STDIN_FD))

```
Interestingly it does return a garbage value for the flag when I comment out the following lines:

```python
# Add constraints that all characters are printable
for k in flag_chars:
    state.solver.add(k >= ord('!'))
    state.solver.add(k <= ord('~'))
```

So I think it might have something to do with it timing out or being stopped. I tried running strace on the program, but I couldn't find any red flags myself. I'm including the last few lines just in case, though:
![image](https://user-images.githubusercontent.com/43989793/115618657-4b5beb80-a2f3-11eb-9048-b6b0e6ca915e.png)

Any help would be greatly appreciated.

**Comment by rhelmot** [comment]
Are you sure it's not just exiting having found zero applicable state? Try adding `print(simgr)`, unindented, to the end of your file.

**Comment by rhelmot** [comment]
That output indicates that it was not possible to find a path that reached the find address without touching the avoid address.

I can't find a copy of the challenge binary so I can't debug this for myself, but I suspect that the problem is that you're unnecessarily constraining stdin - try removing the entire `stdin=flag` line from the state constructor, it should be a lot less brittle.

**Comment by TacticalCream** [comment]
That seems to have done something. The program now returns the flag

![image](https://user-images.githubusercontent.com/43989793/116615822-22170d00-a93c-11eb-89a8-2c8c22964f5c.png)

However the results of the program are not entirely consistent anymore. It appears like there is a 50/50 chance of the program returning the flag or the garbage value that was previously filtered.

![image](https://user-images.githubusercontent.com/43989793/116616147-9ce02800-a93c-11eb-8bcc-62b5f39684cb.png)

The warning related to stdin is also no longer displaying. 

I am still curious of how you would go about filtering out the garbage value, but the program is functional at this point.
When it comes to the challenge binary I don't want to force you to download any executable files directly from this forum post, so I am including the download link to the file on the google servers:
[https://storage.googleapis.com/gctf-2020-attachments-project/f0c3f1cbf2b64f69f07995ebf34aa10aed3299038b4a006b2776c9c14b0c762024bc5056b977d9161e033f80ff4517556d79af101088b651b397a27d4a89f2a1](url)

**Comment by rhelmot** [comment]
After execution is finished, you can add constraints on `state.posix.stdin.content[0][0]`.

**Comment by TacticalCream** [comment]
I'm not sure how I would go about adding constraints on that. I was not able to find any documentation on stdin.content and I'm not sure what the array indexing is for. 
If I add `state.posix.stdin.content[0][0]` at any point in the program the interpreter returns this error:
![image](https://user-images.githubusercontent.com/43989793/116778118-60ade400-aa70-11eb-88c7-41cfdd6084d6.png)

**Comment by rhelmot** [comment]
You need to add the constraints on the found state, not the initial state. States are immutable with respect to execution.
