### ISSUE TITLE
x86_64 of Windows Constraint problem

### ISSUE THREAD

**Issue by Qfrost911** [angr/angr#2612]
---

When I was doing the OLLVM bcf experiment.  I hooked all lib functions including strcmp.
![QQ截图20210424111427](https://user-images.githubusercontent.com/58380176/115945409-44e59380-a4ee-11eb-9148-3267e8a783bb.png)
And after debugging, the strcmp  has indeed been hooked.
![QQ截图20210424111600](https://user-images.githubusercontent.com/58380176/115945453-7b231300-a4ee-11eb-8e28-0af8d421e85b.png)
![QQ截图20210424112005](https://user-images.githubusercontent.com/58380176/115945605-10260c00-a4ef-11eb-805a-6414aea2ee09.png)

The strcmp function should return an unconstrained result，after the code block, the symbolic execution should split into two states. But after debugging, it is found that the result of symbolic execution of the code block on the left is considered to be unreachable.
I don’t know if this is a problem with my code or there is a bug in angr under Windows.

**Comment by Qfrost911** [comment]
This is my code:

`# 加载二进制文件
proj = angr.Project(filename, load_options={'auto_load_libs': False})

# 获取目标函数所有基本块
target_blocks = set()
cfg = proj.analyses.CFGFast()
cfg = cfg.functions.get(start_address).transition_graph
print("[*] All Node:")
for node in cfg.nodes():
    if node.addr >= start_address and node.addr <= end_address:
        target_blocks.add(node)
        print(node)

# Hook掉目标函数中调用的所有其他函数
function_size = end_address - start_address + 1
all_target_block = proj.factory.block(start_address,function_size)
for ins in all_target_block.capstone.insns:
    if ins.mnemonic == 'call':
        proj.hook(int(ins.op_str, 16), angr.SIM_PROCEDURES["stubs"]["ReturnUnconstrained"](), replace=True)
        print("Hook:", ins.op_str)


# 从目标函数开始，simgr.step()逐块执行，一直到没有active状态为止（可以认为是运行结束）
control_flow = set()
state = proj.factory.blank_state(addr=start_address, remove_options={angr.sim_options.LAZY_SOLVES})
simgr = proj.factory.simulation_manager(state)
control_flow.add(state.addr)
while len(simgr.active) > 0:        # 类BFS  每碰到一个跳转就会分裂出两个新的active状态（前提是两个状态都是可达的）
    for active in simgr.active:
        control_flow.add(active.addr)       # 将符号执行能遍历到的所有基本块的地址保存到control_flow中
        print("[*]Add:", hex(active.addr))
        simgr.step()
print("\n\n\n")
print("[*] control_flow:", [hex(x) for x in control_flow])
# handled_blocks = set([node.addr for node in target_blocks if not node.addr in control_flow])
# print("[*] handled_blocks:", [hex(x) for x in handled_blocks])

# nop掉没有被执行到的基本块
base_address = proj.loader.main_object.mapped_base
distinct_blocks = set()
patched_addrs = []
with open(filename, 'rb') as inp:
    data = bytearray(inp.read())
for block in target_blocks:
    if block.addr in distinct_blocks:
        continue
    distinct_blocks.add(block.addr)
    if block.addr in control_flow:
        for child in cfg.successors(block):
            if child.addr < start_address or child.addr > end_address:
                continue
            if child.addr not in control_flow:
                distinct_blocks.add(child.addr)
                patched_addrs.append(hex(child.addr))
                write_nops(data, child.addr - base_address - TEXTMAP_OFFSET + TEXTRAW_OFFSET, child.size)
            else:
                # write_nops(data, block.addr - base_address - TEXTMAP_OFFSET + TEXTRAW_OFFSET, block.size)
                pass

# 最后将去混淆的结果保存到另一个文件中
name, suffix = split_suffix(filename)
outpath = name + '_recovered' + suffix

with open(outpath,'wb') as out:
    out.write(data)
print(f'Patched {len(patched_addrs)} unreachable blocks: {patched_addrs}')
print(f'Recovered file is saved to: {outpath}')`

**Comment by rhelmot** [comment]
I can't debug this without the binary you're trying to analyze. Can you please upload your target binary?

**Comment by Qfrost911** [comment]
> I can't debug this without the binary you're trying to analyze. Can you please upload your target binary?


[bcf.zip](https://github.com/angr/angr/files/6404035/bcf.zip)

**Comment by rhelmot** [comment]
There is a bug in your python code:

```
while len(simgr.active) > 0:       
    for active in simgr.active:
        control_flow.add(active.addr)       
        print("[*]Add:", hex(active.addr))
        simgr.step()
```

You want simgr.step() to be indented one tab less.

**Comment by Qfrost911** [comment]
Thank you so much for your help to solve this problem.
