### ISSUE TITLE
Handle if condition in hook

### ISSUE THREAD

**Issue by Leopounet** [angr/angr#2614]
---

I haven't found any way to correctly handle if-conditions in hooks. Let's say we have this VEX IR at address `0x4011d7`:

```
00 | ------ IMark(0x4011d7, 2, 0) ------
01 | t1 = GET:I64(cc_op)
02 | t2 = GET:I64(cc_dep1)
03 | t3 = GET:I64(cc_dep2)
04 | t4 = GET:I64(cc_ndep)
05 | t5 = amd64g_calculate_condition(0x000000000000000e,t1,t2,t3,t4):Ity_I64
06 | t0 = 64to1(t5)
07 | if (t0) { PUT(rip) = 0x4011ff; Ijk_Boring }
NEXT: PUT(rip) = 0x00000000004011d9; Ijk_Boring
```

In my specific case (but it can be extended to other uses), I would like to "hack" the if statement, so that it always leads to `0x4011d9` but if `t0` is true, I want to increment a variable (say 'hacked_if') before going to `0x4011d9`. The question is, how do I do that in the hook, because `t0` is most likely not a concrete value.

I know how to compute `t0` in Python (I think) but I have no clue what to do with it then, I clearly can't use it in an if statement. I hope it makes sense.

Also, as a sidenode, is there a way to write hooks as VEX IR directly (like not a python function, but just some plain text with the VEX IR syntax)?

**Comment by rhelmot** [comment]
You can use an if-then-else expression: `my_var = my_var + claripy.If(t0, 1, 0)`.

There isn't a good way to write hooks as VEX IR. there definitely isn't a good way to translate code from the vex pretty-printed syntax to the vex data structures.

**Comment by Leopounet** [comment]
In the end, it didn't turn out to be what I wanted exactly.

What I actually need, I think, is to be able, in the hook, to test a symbolic condition and create new paths for every possible value. For example, in the example above, what I would like to do (in the hook):

```py
# that's what I would need, the values would be {0}, {1} or {0, 1} because t0 is a BV1
possible_values_t0 = get_possible_values(t0) 
if 0 in possible_values_t0:
    # continue assuming t0 == 0 (and do other stuff)

if 1 in possible_values_t0:
    # continue assuming t0 == 1 (and do other stuff)
```

I hope this makes sense, does anyone know how this could be achieved?

**Comment by rhelmot** [comment]
You want to set NO_RET and directly use `self.successors.add_successor`. Take a look at how UserHook does it: https://github.com/angr/angr/blob/290fbfd629fcb053e0ce605956ce36250dbdce20/angr/procedures/stubs/UserHook.py
