### ISSUE TITLE
load hand written asm program failed

### ISSUE THREAD

**Issue by tovain10071991** [angr/angr#262]
I code a asm program as follow:
```
# hello.s
.section .text
.global _start
_start:
  movq $0, %rdi
  movq $60, %rax # SYS_exit
  syscall
```

if I execute the command；
```
$ as -o hello.o hello.s
$ ld --dynamic-linker=/lib64/ld-linux-x86-64.so.2 hello.o -lc -o hello
```
where link libc ( it is unnecessary but it is not wrong when not linking libc)
then I construct Project with error:
```
>>> p = angr.Project("./hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 107, in __init__
    self.loader = cle.Loader(self.filename, **load_options)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 94, in __init__
    self._load_main_binary()
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 154, in _load_main_binary
    is_main_bin=True)
  File "/usr/local/lib/python2.7/dist-packages/cle/loader.py", line 266, in load_object
    loaded = backend(path, compatible_with=compatible_with, filetype=filetype, is_main_bin=is_main_bin, **options)
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/elf.py", line 179, in __init__
    self.__register_segments()
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/elf.py", line 319, in __register_segments
    self.__register_dyn(seg_readelf)
  File "/usr/local/lib/python2.7/dist-packages/cle/backends/elf.py", line 361, in __register_dyn
    self.deps = map(self.strtab.get_string, self.deps)
  File "/usr/local/lib/python2.7/dist-packages/elftools/elf/sections.py", line 69, in get_string
    s = parse_cstring_from_stream(self.stream, table_offset + offset)
  File "/usr/local/lib/python2.7/dist-packages/elftools/common/utils.py", line 53, in parse_cstring_from_stream
    chunk = stream.read(CHUNKSIZE)
  File "/usr/local/lib/python2.7/dist-packages/cle/memory.py", line 238, in read
    out = self.read_bytes(self._pointer, nbytes)
  File "/usr/local/lib/python2.7/dist-packages/cle/memory.py", line 116, in read_bytes
    b.append(self.get_byte(i, orig=orig))
  File "/usr/local/lib/python2.7/dist-packages/cle/memory.py", line 87, in get_byte
    raise KeyError(k)
KeyError: 4194808 # 0x4001f8
```

where the 0x4001f8 is end of executable LOAD program:
```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x0000000000000150 0x0000000000000150  R E    8
  INTERP         0x0000000000000190 0x0000000000400190 0x0000000000400190
                 0x000000000000001c 0x000000000000001c  R      1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x00000000000001f8 0x00000000000001f8  R E    200000
  LOAD           0x0000000000000f30 0x0000000000600f30 0x0000000000600f30
                 0x00000000000000d0 0x00000000000000d0  RW     200000
  DYNAMIC        0x0000000000000f30 0x0000000000600f30 0x0000000000600f30
                 0x00000000000000d0 0x00000000000000d0  RW     8
  GNU_RELRO      0x0000000000000f30 0x0000000000600f30 0x0000000000600f30
                 0x00000000000000d0 0x00000000000000d0  R      1
```

My OS:
```
$ uname -a
Linux user-PC 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by schieb** [comment]
`where link libc ( it is unnecessary but it is not wrong when not linking libc)`

It may not be "wrong" in the sense that it will execute properly, but it looks like explicitly linking to a dynamic library without referencing any of its symbols prevents `ldd` from constructing the corresponding symbol table for the reference to that dynamic object (libc). The dynamic section looks like this:
```
$ readelf -d hello

Dynamic section at offset 0x1a8 contains 8 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000004 (HASH)               0x400178
 0x0000000000000005 (STRTAB)             0x400188
 0x0000000000000006 (SYMTAB)             0x400188
 0x000000000000000a (STRSZ)              11 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000000 (NULL)               0x0
```
Note that `STRTAB` and `SYMTAB` should point to different objects (more specifically, different sections) but in this case they point to the same address: the string table (.dynstr). This does not cause an issue during execution because there are no symbols to resolve.

I doubt the gcc devs would consider this a bug but it is definitely a bug in cle.

**Comment by tovain10071991** [comment]
The Dynamic section is as follow:

$ readelf -a ./hello | less

Dynamic section at offset 0xf30 contains 8 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000004 (HASH)               0x4001b0
 0x0000000000000005 (STRTAB)             0x4001d8
 0x0000000000000006 (SYMTAB)             0x4001c0
 0x000000000000000a (STRSZ)              11 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000000 (NULL)               0x0

There are no relocations in this file.

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Symbol table '.dynsym' contains 1 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 

Symbol table '.symtab' contains 14 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000400190     0 SECTION LOCAL  DEFAULT    1 
     2: 00000000004001b0     0 SECTION LOCAL  DEFAULT    2 
     3: 00000000004001c0     0 SECTION LOCAL  DEFAULT    3 
     4: 00000000004001d8     0 SECTION LOCAL  DEFAULT    4 
     5: 00000000004001e3     0 SECTION LOCAL  DEFAULT    5 
     6: 00000000004001f8     0 SECTION LOCAL  DEFAULT    6 
     7: 0000000000600f30     0 SECTION LOCAL  DEFAULT    7 
     8: 0000000000600f30     0 OBJECT  LOCAL  DEFAULT    7 _DYNAMIC
     9: 0000000000601000     0 OBJECT  LOCAL  DEFAULT    7 _GLOBAL_OFFSET_TABLE_
    10: 0000000000601000     0 NOTYPE  GLOBAL DEFAULT    7 _edata
    11: 0000000000601000     0 NOTYPE  GLOBAL DEFAULT    7 _end
    12: 00000000004001e3     0 NOTYPE  GLOBAL DEFAULT    5 _start
    13: 0000000000601000     0 NOTYPE  GLOBAL DEFAULT    7 __bss_start

$ objdump -s ./hello | less

...
Contents of section .dynsym:
 4001c0 00000000 00000000 00000000 00000000  ................
 4001d0 00000000 00000000                    ........        
Contents of section .dynstr:
 4001d8 006c6962 632e736f 2e3600             .libc.so.6.     
Contents of section .text:
 4001e3 48c7c700 00000048 c7c03c00 00000f05  H......H..<.....
Contents of section .dynamic:
 600f30 01000000 00000000 01000000 00000000  ................
 600f40 04000000 00000000 b0014000 00000000  ..........@.....
 600f50 05000000 00000000 d8014000 00000000  ..........@.....
 600f60 06000000 00000000 c0014000 00000000  ..........@.....
 600f70 0a000000 00000000 0b000000 00000000  ................
 600f80 0b000000 00000000 18000000 00000000  ................
 600f90 15000000 00000000 00000000 00000000  ................
 600fa0 00000000 00000000 00000000 00000000  ................
 600fb0 00000000 00000000 00000000 00000000  ................
 600fc0 00000000 00000000 00000000 00000000  ................
 600fd0 00000000 00000000 00000000 00000000  ................
 600fe0 00000000 00000000 00000000 00000000  ................
 600ff0 00000000 00000000 00000000 00000000  ................
...

 I am not clear about if it's essentially same in our case and what the relationship is between raise KeyError(k) with k = 0x4001f8 where is the end of .text section and dynamic section.

$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.27
$ gcc --version
gcc (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005

**Comment by schieb** [comment]
That is interesting. Could you upload your binary?

**Comment by schieb** [comment]
When cle is asked to read from an address that it is not backing, it throws an exception. pyelftools does just that by reading in [chunks](https://github.com/eliben/pyelftools/blob/4228ea065543ceaf4c8e679af2c7323d1bb12043/elftools/common/utils.py#L49) while searching for the end of a string of unknown length. Unfortunately the chunk size is not caller-configurable. With `CHUNKSIZE = 1`, the exception is not triggered.

I think there are two options.

1. Make `CHUNKSIZE` caller-configurable.
2. Add a bounds check to [`read_bytes`](https://github.com/angr/cle/blob/6fee360b928a4f9b344c9f6d4bafae0ec1b8e712/cle/memory.py#L110) and document the possibility of returning less than what was requested.

**Comment by tovain10071991** [comment]
I'm sorry because i make a mistake in what I say in previous commit: 0x4001f8 is after the end of LOAD program not end of .text section.

The assembly and the binary layout is above.

The data read in get_byte is contents from begin of binary to 0x4001f7. But CHUNKSIZE in parse_cstring_from_stream is fixedly 64.

Thank you for your help and explanation!

**Comment by rhelmot** [comment]
@schieb thank you so much for getting to the bottom of this while I was away! Option 2 is absolutely the correct option here - the read/write/seek interface on Clemory objects is meant to emulate a typical python file stream, where you are by no means required to return the requested length. I will push a fix for this shortly...
