### ISSUE TITLE
self-modifying code and angr

### ISSUE THREAD

**Issue by ercoppa** [angr/angr#263]
Hi,

Consider the following self-modifying x86 code:

    00000000004006af <f>:
      4006af:   31 c0                   xor    %eax,%eax
      4006b1:   b9 0a 00 00 00          mov    $0xa,%ecx

    00000000004006b6 <L>:
      4006b6:   89 0d 01 00 00 00       mov    %ecx,0x1(%rip)        # 4006bd <L+0x7>
      4006bc:   05 78 56 34 12          add    $0x12345678,%eax
      4006c1:   ff c9                   dec    %ecx
      4006c3:   75 f1                   jne    4006b6 <L>
      4006c5:   c3                      retq

Assume that this code is inside a writable+executable section. Unfortunately, there are few problems when analyzing this code using angr (notice that `support_selfmodifying_code=True` is always used):

- if `opt_level>=1` (VEX optimazione level) and `num_inst!=1` then this x86 code is wrongly translated into:
   [when pc = 0x4006af]

      IRSB {
               t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I64 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I64 t10:Ity_I32 t11:Ity_I64 t12:Ity_I32 t13:Ity_I64 t14:Ity_I64 t15:Ity_I64 t16:Ity_I64 t17:Ity_I32 t18:Ity_I64 t19:Ity_I32 t20:Ity_I64 t21:Ity_I64 t22:Ity_I64 t23:Ity_I64 t24:Ity_I32 t25:Ity_I64 t26:Ity_I64 t27:Ity_I64 t28:Ity_I64 t29:Ity_I64 t30:Ity_I64 t31:Ity_I64 t32:Ity_I64 t33:Ity_I1 t34:Ity_I64 t35:Ity_I64 t36:Ity_I64 t37:Ity_I64 t38:Ity_I64 t39:Ity_I64 t40:Ity_I64 t41:Ity_I64 t42:Ity_I1 t43:Ity_I32 t44:Ity_I1
       00 | ------ IMark(0x4006af, 2, 0) ------
       01 | ------ IMark(0x4006b1, 5, 0) ------
       02 | PUT(pc) = 0x00000000004006b6
       03 | ------ IMark(0x4006b6, 6, 0) ------
       04 | STle(0x00000000004006bd) = 0x0000000a
       05 | ------ IMark(0x4006bc, 5, 0) ------
       06 | PUT(rax) = 0x0000000012345678
       07 | ------ IMark(0x4006c1, 2, 0) ------
       08 | t29 = GET:I64(cc_ndep)
       09 | t40 = amd64g_calculate_rflags_c(0x0000000000000003,0x0000000000000000,0x0000000012345678,t29):Ity_I64
       10 | t30 = t40
       11 | PUT(cc_ndep) = t30
       12 | PUT(cc_op) = 0x000000000000001b
       13 | PUT(cc_dep1) = 0x0000000000000009
       14 | PUT(cc_dep2) = 0x0000000000000000
       15 | PUT(rcx) = 0x0000000000000009
       16 | PUT(pc) = 0x00000000004006c3
       17 | ------ IMark(0x4006c3, 2, 0) ------
       18 | t43 = 64to32(0x0000000000000009)
       19 | t42 = CmpEQ32(t43,0x00000000)
       20 | t41 = 1Uto64(t42)
       21 | t38 = t41
       22 | t44 = 64to1(t38)
       23 | t33 = t44
       24 | if (t33) { PUT(rip) = 0x4006c5L; Ijk_Boring }
       NEXT: PUT(rip) = 0x00000000004006b6; Ijk_Boring
       }
       
   [after first jump at the end of BB, when pc = 0x4006b6]

       IRSB {
       t0:Ity_I64 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I64 t8:Ity_I32 t9:Ity_I64 t10:Ity_I64 t11:Ity_I64 t12:Ity_I64 t13:Ity_I32 t14:Ity_I64 t15:Ity_I64 t16:Ity_I64 t17:Ity_I64 t18:Ity_I64 t19:Ity_I64 t20:Ity_I64 t21:Ity_I64 t22:Ity_I1 t23:Ity_I64 t24:Ity_I64 t25:Ity_I64 t26:Ity_I64 t27:Ity_I64 t28:Ity_I64 t29:Ity_I32 t30:Ity_I32 t31:Ity_I64 t32:Ity_I64 t33:Ity_I32 t34:Ity_I64 t35:Ity_I64 t36:Ity_I64 t37:Ity_I64 t38:Ity_I1 t39:Ity_I32 t40:Ity_I1

       00 | ------ IMark(0x4006b6, 6, 0) ------
       01 | t7 = GET:I64(rcx)
       02 | t29 = 64to32(t7)
       03 | t6 = t29
       04 | STle(0x00000000004006bd) = t6
       05 | ------ IMark(0x4006bc, 5, 0) ------
       06 | t9 = GET:I64(rax)
       07 | t30 = 64to32(t9)
       08 | t8 = t30
       09 | t3 = Add32(t8,0x0000000a)
       10 | t31 = 32Uto64(t8)
       11 | t10 = t31
       12 | t32 = 32Uto64(t3)
       13 | t12 = t32
       14 | PUT(rax) = t12
       15 | ------ IMark(0x4006c1, 2, 0) ------
       16 | t33 = 64to32(t7)
       17 | t13 = t33
       18 | t5 = Sub32(t13,0x00000001)
       19 | t18 = GET:I64(cc_ndep)
       20 | t34 = amd64g_calculate_rflags_c(0x0000000000000003,t10,0x000000000000000a,t18):Ity_I64
       21 | t19 = t34
       22 | PUT(cc_ndep) = t19
       23 | PUT(cc_op) = 0x000000000000001b
       24 | t35 = 32Uto64(t5)
       25 | t20 = t35
       26 | PUT(cc_dep1) = t20
       27 | PUT(cc_dep2) = 0x0000000000000000
       28 | t36 = 32Uto64(t5)
       29 | t21 = t36
       30 | PUT(rcx) = t21
       31 | PUT(pc) = 0x00000000004006c3
       32 | ------ IMark(0x4006c3, 2, 0) ------
       33 | t39 = 64to32(t20)
       34 | t38 = CmpEQ32(t39,0x00000000)
       35 | t37 = 1Uto64(t38)
       36 | t27 = t37
       37 | t40 = 64to1(t27)
       38 | t22 = t40
       39 | if (t22) { PUT(rip) = 0x4006c5L; Ijk_Boring }
       NEXT: PUT(rip) = 0x00000000004006b6; Ijk_Boring
       }

which will produce a very different result/execution. In particular, it will loop almost indefinitely. Notice that even Valgrind returns a wrong result. I think VEX is making some wrong assumptions when lifting this x86 code (e.g., when doing some optimization passes).

- if  `opt_level=0` or  `num_inst=1`: it will not loop indefinitely but still returns a wrong result (`eax=0x64`). Notice that when `num_inst=1`, pyVEX will not "wrongly" translate this x86 code since the optimization scope is too small (a single instruction, instead of a BB).

-  if  (`opt_level=0` or  `num_inst=1`) and `translation_cache=False`: we get the correct result

Some observations:
- `support_selfmodifying_code=True` does not seem to guarantee a correct execution in presence of self-modifying code
- when `support_selfmodifying_code=True`, `opt_level` should be set to `0`. Alternatively, angr doc should warn the user about possible wrong translations. I think that this a bug of Valgrind but they probably will not care since Valgrind is not designed for testing self-modifying code. On the other hand, angr aims even at this target (this is my intuition, correct me if I am wrong).
- when `support_selfmodifying_code=True`, `translation_cache` should be automatically set to `False`.

What do you think?

Let me know if you want my angr script and/or a working binary.

**Comment by ltfish** [comment]
You are definitely right that `support_selfmodifying_code=True` does not guarantee a correct execution in presence of self-modifying code. VEX (and inherently, PyVEX) assumes the code being lifted is not self-modifying.

angr does not guarantee good support for self-modifying code either - we had some hacks put together to support self-modifying code, and so far everything seems to work, until you open this issue :-) Now it's time to fix it.

The solution as I see it is almost the same as what you suggested: when `support_selfmodifying_code=True`, translation cache should be disabled, and `opt_level` should be set to 0.

PR welcome!

**Comment by salls** [comment]
I think if the code modifies the current block we have to single step to actually guarantee correctness. But the speed tradeoff would be pretty huge

**Comment by rhelmot** [comment]
I wrote the current self-modifying code support. There are in fact very thorough checks to make sure that in the case of code that modifies the current block we halt execution and restart with a re-lifted block from the current address. You're right that the IRSB cache is going to get in the way of this - if we disable it if either we are executing writable memory or support_selfmodifying_code is true, then everything should work perfectly.

**Comment by ltfish** [comment]
@rhelmot We can also perform a proper check for IRSB cache and update the block accordingly every time a block is modified. Not having the cache at all might have a huge impact over the speed.

**Comment by ercoppa** [comment]
Thank you for your quick replies. 

I also agree that, in presence of a write in a executable section, selective invalidation of the IRSB cache is the right approach in the long-term, otherwise there will be a huge impact.

In the last few days, I have also looked at the paper "Symbolic Execution of Obfuscated Code" by Babak Yadegari et al. appeared at ACM CCS 2015. angr is able to deal smoothly with Example 3.1 and Example 3.2. On the hand, the example (referred as "symbolic code") shown in Figure 3 (which I rewrote like [this](https://gist.github.com/ercoppa/5f8eb9d0f9b39b138509733a5f3137dc)) is not handled correctly.  This is not unexpected since the general problem is very hard to approach. However, angr should warn the user when some "symbolic code" is evaluated: right now, when some symbolic bytes are executed, it will just call the solver, concretize them (considering the first _random_ solution obtained by Z3, see `_bytes_from_state()` in `lifter.py`) and then lift these concrete bytes to VEX. Although this strategy is very reasonable, I think that angr could, at least, evaluate if more than one solution is possible for the symbolic bytes and warn the user about this fact. To deal with some "easy" cases, it could even evaluate if the number[*] of possible solutions are less than a threshold and in this case fork the state for each possible solution. It is likely that several of these forked states will probably execute some illegal code and thus die very soon. This strategy is similar to what angr does when a symbolic read is performed. The main difference is that you can't use ite expression, but you are forced to fork.

What do you think about "symbolic code"? 

[*] a range check is a more practical approach

**Comment by ltfish** [comment]
@ercoppa I also read that paper before. I have to say that the "symbolic code" is not something we would care about normally. While we are very happy to take PRs to make it work, I don't think any of us will spend our time in implementing that feature.

And in general, I doubt how often you'll see "symbolic code" in real life.

**Comment by ercoppa** [comment]
Invalidating the cache is not trivial:
- a cache entry is indexed by `(addr, insn_bytes, max_size, num_inst, thumb, opt_level)`
- dirty addresses due to a IRSB are tracked by `state.scratch.dirty_addrs`
- to invalidate a cache entry as soon as some addresses are marked as dirty, we have to check if the entry is inside the cache... but to generate the cache key, we also need to know `(insn_bytes, max_size, num_inst, thumb, opt_level)` used in the past (trying all the possible combinations is not the best approach). However, if we are dealing with self-modifying code, we can assume that `opt_level=0`. I don't think we can make other assumptions on `(max_size, num_inst, thumb)` (they could be changed during a project lifetime)
- another approach requires to invalidate an entry when the lifter looks for it (hence `(insn_bytes, max_size, num_inst, thumb, opt_level)` are known) but this requires to keep track of dirty addresses across different IRSB. I don't like this strategy.

**Comment by ercoppa** [comment]
Invalidating the cache is not a trivial task:
- a cache entry is indexed by `(addr, insn_bytes, max_size, num_inst, thumb, opt_level)`
- dirty addresses due to a IRSB are tracked by `self.state.scratch.dirty_addrs`
- to invalidate an entry as soon as an address inside it has been touched, we have to search for it in the cache. To do so, we have to generate a cache key. However, we don't know `(insn_bytes, max_size, num_inst, thumb, opt_level)` used in the past when inserting the entries in the cache. In case of self modifying-code, `opt_level=0`. But we can't make similar assumptions on the other values since they could change during the lifetime of a project.
- another approach could be to invalidate an entry when the lifter looks for it in the cache. Hence, ` insn_bytes, max_size, num_inst, thumb, opt_level)` are known. We then need to check if the one of addresses related to the cache entry has been touched by the program. However, this requires to keep track of dirty address across different IRSB. This seems expensive.

**Comment by zardus** [comment]
The other problem is that the cache is on the project level, whereas the
block in question might be modified in different ways by different blocks.
We could get around this by including a hash of the code in the cache entry
index, though.

**Comment by rhelmot** [comment]
We don't need to invalidate cache entries as soon as they're touched - we can wait until the end of a block to do that. In the case of a modification that requires immediate attention, a SimReliftException will be raised and [this code](https://github.com/angr/angr/blob/master/angr/factory.py#L96) can take care of it. We should add code there to immediately invalidate entries, and some code later in the code, probably further out in `sim_run`, to handle invalidating blocks other than the current one. To support this, the block cache will need to have some additional data stored mapping address ranges to blocks - multiple blocks can be cached for a given address, so how this works could be tricky... we might want to keep some kind of tree structure of cache entries indexed on block start address, so for a given write address we can quickly tell if it touches a region of memory where blocks are cached, and if so which blocks to invalidate.

**Comment by zardus** [comment]
tbh, given all the other stuff on our plate, I would just turn the cache off for self-modifying code...

**Comment by ercoppa** [comment]
PR #266 disable the translation cache and set opt level to 0 when support_selfmodifying_code is true.

**Comment by ltfish** [comment]
Thanks. I just replied in the PR, please check it out :-)

**Comment by ercoppa** [comment]
My changes have been merged. I close the issue. Feel free to re-open it. Thank you all.
