### ISSUE TITLE
Is there an option to limit the time spent in checking a path constraint is satisfiable?

### ISSUE THREAD

**Issue by KiNa4Uc** [angr/angr#2647]
The following code is a snippet of obfuscated code. The (x + y) * (x & y) != (x & y) * (x & y) + (x | y) * (x & y) is an opaque predicate whose value is always false.
`int x, y;

int main()
{
    if ((x + y) * (x & y) != (x & y) * (x & y) + (x | y) * (x & y)) {
        printf("Bogus");
    }
    return 0;
}`

When I used Z3 to check this predicate, the check method of z3.solver can not return in 10mins.
`from z3 import *
import time

x, y = BitVec("x", 32), BitVec("y", 32)
s = Solver()
s.add((x + y) * (x & y) != (x & y) * (x & y) + (x | y) * (x & y))
t1 = time.time()
print(s.check())
t2 = time.time()
print(t2 - t1)`

However, when I used angr to detect this predicate, it can check the bogus path is unreachable in 300s. So....I mean, is there an option to limit the time spent in checking a path constraint is satisfiable? And the initial value is 300s? I had looked through the document, but I found nothing about this.

`import angr
import claripy
import time

def print_constraint(state):
    global t_k
    print("time:", time.time() - t_k)
    print(str(state.inspect.added_constraints))
    t_k = time.time()

proj = angr.Project(r"C:\Users\chengrui\source\repos\ConsoleApplication6\Debug\ConsoleApplication6.exe", auto_load_libs = False)
state = proj.factory.entry_state(addr=0x00411860)
state.inspect.b("constraints", when = angr.BP_AFTER, action = print_constraint)
state.satisfiable()
a = claripy.BVS("a", 32)
b = claripy.BVS("b", 32)
state.mem[0x41A138].int = b
state.mem[0x41A13C].int = a
sm = proj.factory.simgr(state)
t_k = time.time()

sm.explore(find=0x004118DE)
print(len(sm.found))

The output is:

> time: 0.001989126205444336
(<Bool True>,)
time: 0.0
(<Bool False>,)
time: 0.011999368667602539
(<Bool (b_1_32 & a_0_32) * (b_1_32 + a_0_32) == (b_1_32 & a_0_32) * (b_1_32 & a_0_32) + (b_1_32 & a_0_32) * (b_1_32 | a_0_32)>,)
time: 0.10073256492614746
**_(<Bool (b_1_32 & a_0_32) * (b_1_32 + a_0_32) != (b_1_32 & a_0_32) * (b_1_32 & a_0_32) + (b_1_32 & a_0_32) * (b_1_32 | a_0_32)>,)
time: 300.07384490966797_**

Thanks.

**Comment by rhelmot** [comment]
The magic timeout value is stored on `state.solver._solver.timeout`, in milliseconds.
