### ISSUE TITLE
(Tab) Completion in IPython

### ISSUE THREAD

**Issue by Mikevin** [angr/angr#2656]
Note:
I'm not sure if this is an issue on my side but I have a question that may be useful to document. It's a simple question but the answer might not be so I chose to make it publicly visible and searchable here instead of Slack. I hope that's ok.

Situation:
I'm new to angr and using ipython to explore and learn. As I understand, using ipython to explore a project is one of the main use-cases of angr.

One of the main benefits I tend to use frequently is using tab completion to figure out the api and plan my approach accordingly.

I also set my logging levels to either debug or info to catch any issues.

Often when triggering completion angr gives me warnings or seemingly modifies state. One such example is state.regs.<TAB>
If inunderstand correctly accesing regs triggers concretization, which is a useful shortcut but isn't my intention when using completion.

I've also encountered situations where completion triggers a slow operation but sadly I haven't documented a reproducible example since I initially though I messed up myself. If I encounter this again I'll try to document the issue and maybe even try my hand at fixing it.

Question(s):
What can I do to avoid triggering side-effects with tab-completion? Is there a general rule on what's safe?

If this is something that can be improved in angr itself I'm willing to take a look, I'm looking for an excuse to contribute anyway but I need some info/pointers before I dive into this. Maybe I just overlooked some piece of documentation,  or missed relevant github issues when I searched for this.

Unrelated Note:
Thanks for such a great tool/ framework.  I barely understand half of its features and it's already helped me immensely in my small hobby project of documenting the memory map and boot process of an obscure routers ARM7 Asic by concretizing on-chip constants from a dump of the bootloader and the routers UART output during boot.

**Comment by rhelmot** [comment]
So the good news is that your use case is 100% one that we have explicitly designed angr in support of. I use tab completion to navigate stuff all the time.

For the slow operations, I've found that disabling jedi's "smart" autocompletion doesn't affect the validity of the results but does speed things up quite a bit. Sticking this in my ipython profile's startup directory does the trick:

```
import IPython
py = IPython.get_ipython()
py.Completer.use_jedi = False
```

However, I'm not sure what we can do to avoid side effects. Assuming you're talking about typing `state.regs.al.` and hitting tab, there's nothing we can do to tell IPython that this access may have side effects. I've been wishing for an annotation we can use to tell autocompleters that something is or isn't safe, but afaik that's not implemented and I don't have the expertise with IPython's codebase to add it.

The silver lining, though, is that none of these side effects should ever actually change anything with respect to the correctness of execution or analysis. I'm pretty sure we've made sure that no function which intuitively should be "pure" can ever change state in a way that isn't just filling a cache. If you run into any situation where tab completion causes future queries to return different results, definitely submit that as a bug.

**Comment by Mikevin** [comment]
> So the good news is that your use case is 100% one that we have explicitly designed angr in support of. I use tab completion to navigate stuff all the time.

Great!

> 
> For the slow operations, I've found that disabling jedi's "smart" autocompletion doesn't affect the validity of the results but does speed things up quite a bit. Sticking this in my ipython profile's startup directory does the trick:
> 
> ```
> import IPython
> py = IPython.get_ipython()
> py.Completer.use_jedi = False
> ```
> 
Thanks, I will try this, could this be something that would be useful to add to the documentation? I haven't seen a tips/tricks doc so I'm not sure where it could fit. Maybe the something like the angr strategies cheat sheet?

> However, I'm not sure what we can do to avoid side effects. Assuming you're talking about typing `state.regs.al.` and hitting tab, there's nothing we can do to tell IPython that this access may have side effects. I've been wishing for an annotation we can use to tell autocompleters that something is or isn't safe, but afaik that's not implemented and I don't have the expertise with IPython's codebase to add it.

Maybe I accidentally triggered that one but I think I've experienced it with a more top-level item. I'll keep an eye out for any situations now that I know more about the situation.

Angr immediately convinced me of it's power by advanced and complex analysis techniques through a relatively simple and explorable API,  being able to drop into IPython and play around made me drop any fears I had about me being unfamiliar with its' underlying concepts. If I had experienced any slowdowns/unexpected mutation of state earlier on I might have moved on, feeling too intimidated at the thought of having to debug an application, framework and it's concepts before even familiarizing myself with it. 

This experience and it's potential of making binary analysis more accessible, to me, is worth a lot so about the possibility of annotions/some configuration of ipython:
I was actually thinking the same thing, an annotation would be perfect for this, I don't have any real  expertise in IPython also but I'll look around for any solutions. 
> 
> The silver lining, though, is that none of these side effects should ever actually change anything with respect to the correctness of execution or analysis. I'm pretty sure we've made sure that no function which intuitively should be "pure" can ever change state in a way that isn't just filling a cache. If you run into any situation where tab completion causes future queries to return different results, definitely submit that as a bug.

Same thing as above, I'm certain I've experienced this and it was something related to completing regs, angr concretizing stuff, resulting in an error when using this state later on. It might be some complex chain of actions that triggered it or maybe it wasn't actually in the exact same state as the retry I did afterwards. Again, I'll make sure to report any encounters of this now that I know that could be a problem on angr's side instead of my unfamiliarity.

**Comment by ltfish** [comment]
https://github.com/angr/angr-doc/commit/bc74c8e966518930466edf2c9ee85e2b1b0f3852
