### ISSUE TITLE
Question: How to identify a path throughout exploration?

### ISSUE THREAD

**Issue by tj-byun** [angr/angr#268]
Hi, while I was implementing my own `ExplorationTechnique` as @rhelmot advised me, I faced an issue where I cannot identify a path as the same one after it *steps* forward (I was relying on `is` and `id()`). I want to implement an `ExplorationTechnique` so that I can limit the number of times a path encounters a certain `eip`, but it's not possible unless I can annotate the path somehow or identify the path even after it steps forward. Is there an existing way to do so?

Thank you!

**Comment by rhelmot** [comment]
You can store arbitrary information in the `path.info` variable! This dictionary will be shallow-copied from a path to each of its successors.

**Comment by bntejn** [comment]
Oh, I missed that; that'll solve my problem. Thank you again for a quick reply, @rhelmot !
