### ISSUE TITLE
Creating local variables

### ISSUE THREAD

**Issue by Leopounet** [angr/angr#2686]
---

Hi, is there a way to create local variables, that is variables that exist in the current state and all of its children, grand-children and so on (but if a descendant modifies the variable, it should not affect the ancestors). Something similar to state.globals basically. I could do that through the memory but I don't know in advance where I can write in memory without affecting the program, hence I'd rather not use it.

**Comment by rhelmot** [comment]
you can either allocate yourself some memory on the heap using `state.heap.allocate()`, or you can use `state.callstack.locals`, which should have the same semantics as `globals` but is scoped per-function call.

**Comment by Leopounet** [comment]
I guess allocating on the heap should work, thank you. Also (idk if I should open another issue), is there a way to cast a BV32 to a BV1 (it's done in the VEX representation but I can't find a way to do it in Python, the best I found was BV32 to BV8 with get_byte)?

**Comment by rhelmot** [comment]
you can extract arbitrary substrings of bitvectors with the slice syntax. You can get just the least significant bit with bv[31].

**Comment by Leopounet** [comment]
Okay everything is working, thank you. But I still have another question, do you know why in the VEX representation, calls are always shifted by one byte (it doesn't alter anything though). For example, I have a function at address `0x08003798` but when it is called, the VEX IR is :

```py
PUT(itstate) = 0x0
PUT(lr) = 0x080015ef
PUT(pc) = 0x08003799
```

And then, I also wonder, do I have to add this offset when I create hooks and modify the `pc` reg?

**Comment by rhelmot** [comment]
https://docs.angr.io/introductory-errata/faq#why-are-some-arm-addresses-off-by-one

For your second question, yes.
