### ISSUE TITLE
How to get all actions of a path?

### ISSUE THREAD

**Issue by JodieAllen** [angr/angr#270]
hi,I used `path_group.explore(find=0x400636)` to get a `found path`  ,then I used `path.actions` to get actions of this `found path`,but I find I can not get all actions of this path, which means I missed some blocks' actions, for example, the addr_trace of the path is `0x400686,0x4006af,0x400647` and I used `path.actions` only to get actions of block `0x400686`.

So,Is there a way to get all actions of a path? I want to know which registers and memory area a path has operated ,so I want to know  all actions of a path.

Thanks a lot!

**Comment by rhelmot** [comment]
Hello! You can add the state option `simuvex.o.TRACK_ACTION_HISTORY` in order to prevent the discarding of old actions. This is disabled by default because it is very memory-intensive.
