### ISSUE TITLE
CLE issue on OSX Sierra

### ISSUE THREAD

**Issue by 0x4a47** [angr/angr#271]
Hi, 

I have just installed Angr on OSX Sierra and am having an issue with the CLE loader. 

The error(s) are as follows: 

> ERROR
>    | 2016-11-24 14:34:33,431 | cle.loader | Loading error when loading /bin/ls with backend IDABin
> Traceback (most recent call last):
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/loader.py", line 266, in load_object
>     loaded = backend(path, compatible_with=compatible_with, filetype=filetype, is_main_bin=is_main_bin, **options)
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/backends/idabin.py", line 21, in __init__
>     raise CLEError("Install the idalink module to use the IDABin backend!")
> CLEError: Install the idalink module to use the IDABin backend!
> ERROR   | 2016-11-24 14:34:33,432 | cle.loader | Loading error when loading /bin/ls with backend Blob
> Traceback (most recent call last):
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/loader.py", line 266, in load_object
>     loaded = backend(path, compatible_with=compatible_with, filetype=filetype, is_main_bin=is_main_bin, **options)
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/backends/blob.py", line 21, in __init__
>     raise CLEError("Must specify custom_arch when loading blob!")
> CLEError: Must specify custom_arch when loading blob!
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/angr/project.py", line 107, in __init__
>     self.loader = cle.Loader(self.filename, **load_options)
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/loader.py", line 94, in __init__
>     self._load_main_binary()
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/loader.py", line 154, in _load_main_binary
>     is_main_bin=True)
>   File "/Users/a/.virtualenvs/angr/lib/python2.7/site-packages/cle/loader.py", line 272, in load_object
>     raise CLEError("All backends failed loading %s!" % path)
> cle.errors.CLEError: All backends failed loading /bin/ls! 
> 

Have tried to reinstall, can't seem to shake the error. 

I have also installed angr on debian and have no issues. Only seems to happen on my OSX box.

**Comment by ltfish** [comment]
CLE doesn't have a native loader for MachO files. I heard there is a MachO file loader being developed somewhere (@rhelmot was in touch with the author a while ago), not sure when we can have access or include it in angr.

**Comment by 0x4a47** [comment]
@ltfish ahhh okay, that makes sense. I always assumed it did based on the fact that it can be installed on OSX. Im assuming until CLE has the loader, OSX binaries are incompatible with Angr or is some functionality still available?

**Comment by ltfish** [comment]
You can use the IDA backend to load MachO binaries and whatever binary format that IDA supports. Or you can use angr on macOS to analyze binaries of other formats (like ELF or PE).

**Comment by 0x4a47** [comment]
@ltfish Awesome, any documentation on this apart from **https://github.com/angr/cle/issues/35** or is this one for me to sort out myself.

**Comment by ltfish** [comment]
Unfortunately we don't have manpower to write a documentation on idalink or the IDA backend at the moment :-( It was definitely working last time I used it. Try to figure out by yourself, and if it doesn't work, open an issue to ask us!

**Comment by 0x4a47** [comment]
Fair enough! Thanks @ltfish

**Comment by ltfish** [comment]
No problem. Just updated my answer, maybe you want to give it a look.

**Comment by 0x4a47** [comment]
Ahh legend! Appreciate it.
