### ISSUE TITLE
SimulationManager with all stashes empty (1 errored)

### ISSUE THREAD

**Issue by nathanebar** [angr/angr#2710]
when I use explore it sends me back this error
![errored](https://user-images.githubusercontent.com/57418604/120352309-539f4180-c309-11eb-9c45-57d6aab24bb1.PNG)
I don't now why?

**Comment by ltfish** [comment]
You can print out the execution history to see why it ended up executing code at 0x993aed03:

```python
print(_.errored[0].state.history.descriptions.hardcopy()[-100:])
```

**Comment by nathanebar** [comment]
![hardcopy1](https://user-images.githubusercontent.com/57418604/120366365-3e7ddf00-c318-11eb-9c7f-a07f6d2fbd7b.PNG)
![hardcopy2](https://user-images.githubusercontent.com/57418604/120366368-3faf0c00-c318-11eb-8be7-2bba694cf52f.PNG)
![hardcopy3](https://user-images.githubusercontent.com/57418604/120366366-3f167580-c318-11eb-8166-7b7bbea9144a.PNG)

**Comment by rhelmot** [comment]
That information doesn't mean anything to us - you need to use it to reverse engineer the behavior of your binary to determine what the emulator thinks it's doing.
