### ISSUE TITLE
Problem between angr and binary file

### ISSUE THREAD

**Issue by josslalou** [angr/angr#2711]
Good evening, I have been stuck for several weeks on the same problem I hope you can help me: I wrote a code in c (available below) which checks if my password is "1337" I want to solve it using angr but it doesn't work (the python code using angr is also below) if you can tell me if something is missing in the code.
thank you
the code in c :
![image](https://user-images.githubusercontent.com/57400419/120382523-6a0ac480-c32c-11eb-8288-8e9509a8ad0c.png)
the code of python with angr :
![image](https://user-images.githubusercontent.com/57400419/120379871-1054cb00-c329-11eb-8758-72b61f64a572.png)
The result :
![image](https://user-images.githubusercontent.com/57400419/120379896-1a76c980-c329-11eb-95fd-7484f6214235.png)
the binary file :
[new.zip](https://github.com/angr/angr/files/6580262/new.zip)

**Comment by ltfish** [comment]
Post the binary file please.

Also, I would appreciate it if the title of your issue is more self-explanatory.

**Comment by josslalou** [comment]
thanks , I modified the title and I added the binary file

**Comment by rhelmot** [comment]
```
>>> project._sim_procedures
{
...
 5243068: <SimProcedure __stdio_common_vfscanf (stub)>,   
...
```

The (stub) is the important part. scanf is not being hooked, so input is never reaching your emulated code.

So there are a couple of problems:

1. scanf is named weirdly, so it's not being hooked automatically 
2. I don't particularly understand why you're using vfscanf directly. does msvc link in the implementation of scanf but not vfscanf?
3. we don't actually support the `v` variants of printf and scanf yet. It shouldn't be too too hard, but it's work that I can't focus on right now.

**Comment by josslalou** [comment]
i understand what you say , but don't know what the solution to resolve this problem ...
(if you have an idea please)
thanks 
joss

**Comment by josslalou** [comment]
thanks !

**Comment by josslalou** [comment]
you know how can you find a password of type string without specifying in which register it is stored?

**Comment by rhelmot** [comment]
In general, you need to specify where something is stored in order to access it :P

If you know where it is stored in memory, you can load it directly from memory.
