### ISSUE TITLE
How to limit the stdin length ,if i have already know the length of the right password?

### ISSUE THREAD

**Issue by the-fog** [angr/angr#2718]
such as the rigit password is 0x10 len.If not limit the length,it will take much more time .

**Comment by the-fog** [comment]
I only see examples that limit the length of command line parameters.

**Comment by rhelmot** [comment]
pass `stdin=input_bitvector` to the state constructor. However, this will prevent some functions like scanf("%s") and fgets from working as efficiently as they could.

**Comment by the-fog** [comment]
Can i control the time or eip to pass stdin? Since i know when it will call fgets.

**Comment by the-fog** [comment]
I faced a binary file that it called init function before fgets.If i init state after fgets ,it will not get the right password.

**Comment by rhelmot** [comment]
I don't understand your question? You have to initialize stdin at the same time as you create your state, and you have to create your state at an address which will capture all the program effects you want to analyze moving forward.

**Comment by the-fog** [comment]
I mean if i want to pass stdin to fgets , how to define the input_bitvector?

**Comment by rhelmot** [comment]
same way as always, `claripy.BVS('name', length_in_bits)`

**Comment by the-fog** [comment]
OK,thank you!
