### ISSUE TITLE
Need help to do hook function 

### ISSUE THREAD

**Issue by josslalou** [angr/angr#2719]
Hi !
after all , thanks to your help , we have a second problem now : we have a simple file exe with flag = code precise and we dont succeed to resolve this simple challenge beacuse there are functions not understand by angr as we have to do the functions hooks (seem not complicate ) but we need help ! 
i send you : the binary file (this is the simple challenge)
and the start of my code 
i need help for the hook functions 
thanks 
joss Lalou
[level1a.zip](https://github.com/angr/angr/files/6625555/level1a.zip)

![image](https://user-images.githubusercontent.com/57400419/121397413-f6d10600-c95c-11eb-940d-9bf6c670fd80.png)

**Comment by rhelmot** [comment]
`proj.hook(0x4010D3, scanf())`
`proj.hook(0x4010F0, printf())`

**Comment by josslalou** [comment]
![image](https://user-images.githubusercontent.com/57400419/121404823-03595c80-c965-11eb-9625-269d9f838f33.png)
this is not work ....

**Comment by josslalou** [comment]
thanks you very much 👍
