### ISSUE TITLE
Decompiler freezes trying to process MD5 core function

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#2721]
Try decompiling the MD5Transform function in [md5c.o](https://github.com/angr/angr/files/6634225/md5c.o.gz). It takes longer than I care to wait.

![image](https://user-images.githubusercontent.com/2498805/121592731-eae25400-c9ef-11eb-858d-3af72a1905ee.png)

Seemingly, the culprit is `ailment.Expression.__eq__`, which makes sense since this will obviously create extremely deep ASTs. Do we want to add hash-consing to ailment?

**Comment by ltfish** [comment]
Thanks for reporting. The culprit is indeed the extremely deep ASTs - hash consing is a good idea. Let me see how to add it easily.
