### ISSUE TITLE
Program that runs in an infinite loop ....

### ISSUE THREAD

**Issue by diegoviesta** [angr/angr#2726]
Hi, 
I'm just starting to take an interest in this fantastical python library! 
I practiced on some nice CTFs :-),
 but there is one that still stands up to me and I don't understand why, 
the python code runs without stopping, without telling me what the error is and without showing me the flag!
thank you for your help!
(please look at the binary file as well as the python file below)
![image](https://user-images.githubusercontent.com/85805209/121889648-2ba8d880-cd22-11eb-927e-555d554d808f.png)
![image](https://user-images.githubusercontent.com/85805209/121889115-7d9d2e80-cd21-11eb-8c1b-12657a6a60ae.png)
[amazing.zip](https://github.com/angr/angr/files/6648131/amazing.zip)

**Comment by rhelmot** [comment]
The problem is that you've hooked the address of vscanf, not scanf. Changing the hook to be at 0x41169F, the analysis finds one found state, though the code to extract the answer seems wrong - edx is 0x1 in my tests.

**Comment by diegoviesta** [comment]
ok, I did indeed change the hook, what I don't understand is that: I have read a lot about hook functions and ctf resolutions with angr , here the case is not hard: I want to receive a string whose first letter is: b, the second a, the last h and the penultimate c, without putting constraints in the code in python, angr should know how to solve this kind of exercise simply with my code? if not I do not understand why?

**Comment by diegoviesta** [comment]
Ok, I understand your thinking, I'm trying to test the special cases of angr, in the case of floats for example, hooks don't seem to work ...
[float.zip](https://github.com/angr/angr/files/6656365/float.zip)
![image](https://user-images.githubusercontent.com/85805209/122071419-63d21900-cdff-11eb-820e-87171d8c7fe8.png)

![image](https://user-images.githubusercontent.com/85805209/122071340-574dc080-cdff-11eb-9513-40cca27ed141.png)

**Comment by diegoviesta** [comment]
if you have an idea ..

**Comment by diegoviesta** [comment]
Is there a way to stop the explore function if it never stops? With a predefined time for example? thank you

**Comment by rhelmot** [comment]
You can pass the `n` parameter to the explore function to cause it to stop early if nothing is found after n steps.

**Comment by diegoviesta** [comment]
thanks

**Comment by diegoviesta** [comment]
and if i want to hide the "warning message " in console , how do that ?

**Comment by rhelmot** [comment]
Which warning message? If you want to turn off all logged warnings, you can do that with the python logging module.
