### ISSUE TITLE
State errored with "Symbolic pointer to (format) string"

### ISSUE THREAD

**Issue by nathanebar** [angr/angr#2728]
I'm trying to find the password for this challenge but I'm stuck on an error that I don't understand. 
If anyone could  it to me pls
![errorP](https://user-images.githubusercontent.com/57418604/122098831-ff708300-ce19-11eb-955b-6c08b3872a8a.jpg)
[bin.zip](https://github.com/angr/angr/files/6657590/bin.zip)
![image](https://user-images.githubusercontent.com/57418604/122099238-71e16300-ce1a-11eb-8a28-6b524a1cc695.png)

thank you!

**Comment by rhelmot** [comment]
This means that the program passed a pointer which was a symbolic value to printf or scanf. angr's symbolic executor can't handle this case because it explodes the state space beyond any reasonable ability to control it.

**Comment by nathanebar** [comment]
ok thank you
