### ISSUE TITLE
DDG Docs

### ISSUE THREAD

**Issue by 2over12** [angr/angr#274]
I am trying to trace a pointer to memory  allocated on the heap back to its original malloc. I figured the way to do this would be via the ddg but I can not find any documentation for a the ddg except that it is a networkx graph. I am wondering if there is some documentation for it someplace I am not looking.

**Comment by schieb** [comment]
I cannot help you with DDG but there is another fairly simple way to map a pointer back to the IP (or other context information) that issued the malloc. I would go about this by adding a dictionary to the [libc plugin](https://github.com/angr/simuvex/blob/master/simuvex/plugins/libc.py) (or your own plugin) and editing the [malloc SimProcedure](https://github.com/angr/simuvex/blob/master/simuvex/procedures/libc___so___6/malloc.py) to update the mapping every time memory is allocated. The mapping could contain the starting heap address, size, and context information such as the IP, callstack or the even the stackframe itself.

**Comment by zardus** [comment]
When he has some time, I know @ltfish is planning on documenting the DDG a bit so that other people than himself can use it. In the meantime, he'll have to wander in and enlighten us when he has a chance.

**Comment by 2over12** [comment]
Alright I appreciate the responses Ill look into what schieb recommended, not entirely positive that I get what your saying, but I'll try it.

**Comment by schieb** [comment]
See https://github.com/angr/simuvex/issues/46#issuecomment-264739016 for details on creating a new plugin.

**Comment by frapik99** [comment]
Hi,
I would also be interested to understand if using the DDG it is possible to trace the "dependencies" of a variable. For example, considering a malloc, is it possible to extract from the DDG how the malloc's first parameter was created?

Thanks

**Comment by ltfish** [comment]
@frapik99 it is.
