### ISSUE TITLE
Help solving an exercise

### ISSUE THREAD

**Issue by frapik99** [angr/angr#275]
Hi all,
suppose I have this C code:

```
#include<stdlib.h>
int main(int argc, char *argv[]) {
	int a = atoi(argv[1]);
	a = a - 10;
	int b = a + 1;
	if ( b > 3 )
	    malloc(b);
}
```

Once compiled the call to malloc is at ```0x00000000004005a6```

With angr I would like to obtain the min value for argv1 if I have the malloc to be called. The solution should be 13 but I cannot have that result. My code is the following:

```
import angr

def main():
	proj = angr.Project('./example', load_options={"auto_load_libs": False})
	argv1 = angr.claripy.BVS("argv1", 64)
	initial_state = proj.factory.entry_state(args=["./example", argv1]) 

	initial_path = proj.factory.path(initial_state)
	path_group = proj.factory.path_group(initial_state)
	path_group.explore(find=0x00000000004005a6)
	found = path_group.found[0]
	print found.state.se.min(argv1)

if __name__ == '__main__':
    main()
```

My output is:

```
3112040326038040883
```

Can you explain me why please?

Thanks

**Comment by esanfelix** [comment]
Hi,

You are looking at the solution as an integer while argv[1] it is actually a string. If you look at it as a string, and decode it, here is what you get:

```
>>> '2b30303030303133'.decode('hex')
'+0000013'
>>>
```

That said, I am not quite sure how state.se.min() behaves with strings exactly (I presume alphabetically?) and what you really want is probably to find the minimum value for the output of atoi(argv[1]) rather than argv[1] itself.

**Comment by frapik99** [comment]
@esanfelix Thanks, how did you get 2b30303030303133?

**Comment by esanfelix** [comment]
@frapik99 just convert the number to hexadecimal...

**Comment by frapik99** [comment]
@esanfelix dumb question... Thanks

**Comment by frapik99** [comment]
Hi,
if I try the following example:

```
#include<stdlib.h>

int main(int argc, char *argv[]) {
	int a = atoi(argv[1]);

	if ( a < -99  || a > 60000 )
		a = 9;
	else
		malloc(a);
}
```

The min value is always zer? Is ```min``` able to return negative value?

**Comment by ltfish** [comment]
`se.min()` is unsigned.

**Comment by frapik99** [comment]
@ltfish thanks, how can I have the min value but signed?

**Comment by ltfish** [comment]
You can add a new constraint that limits the most significant bit of your symbolic variable `argv1` to 0 (positive numbers) or 1 (negative numbers), and then call `se.min()` or `se.max()` respectively.

**Comment by axt** [comment]
@frapik99  check `get_signed_range` function here: https://github.com/axt/angr-utils/blob/master/angrutils/expr.py
