### ISSUE TITLE
Can't install angr via pip (ValueError: 'format' in __slots__ conflicts with class variable)

### ISSUE THREAD

**Issue by duesee** [angr/angr#277]
I'm running into this issue:

```
Collecting progressbar (from angr)
  Using cached progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ohceatl8/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip-build-ohceatl8/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip-build-ohceatl8/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/home/user/angrenv/lib/python3.5/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
```
Any suggestions? Would have tried to fix it myself, but the meta-classes scared me :-)

Just in case:
Linux 4.8.11-1-ARCH x86_64 GNU/Linux
Python 3.5.2
virtualenv 15.0.3
gcc (GCC) 6.2.1 20160830

**Comment by zardus** [comment]
Unfortunately, angr doesn't yet work in Python 3. This is *definitely* on
the roadmap (note to self: we should have a roadmap doc), but just not
something we have the manpower for yet.

If you're interested in looking into Python 3 compatibility, the best way
would probably be to start with the various angr sub-projects (claripy,
simuvex, cle, pyvex) and move on to angr itself afterwards.

Sorry for being stuck a bit in the past ;-)

**Comment by duesee** [comment]
Oh, this was not on my checklist. Thanks!
