### ISSUE TITLE
How to use mode "tracing" on Android armeabi-v7a?

### ISSUE THREAD

**Issue by Youlor** [angr/angr#2774]
When I use project  default_analysis_mode="tracing", IR lifted failed (State errored with "IR decoding error at 0x8a8a5c. You can hook this instruction with a python replacement using project.hook(0x8a8a5c, your_function, length=length_of_instruction)."), because of the [strlen] function [easy_libc_strlen] called is thumb mode and [strlen] function in another so(libc.so) .
c code:
```c
EXPORT
int easy_libc_strlen(const char*s) {
    char *s2 = (char *)malloc(strlen(s) + 1);
    memset(s2, 0, strlen(s) + 1);
    memcpy(s2, s, strlen(s) + 1);
    int len = strlen(s2);
    free(s2);
    return len;
}
```
python code:
```python
proj = angr.Project(SO_PATH, auto_load_libs=True, ld_path=LD_PATH, default_analysis_mode="tracing")
simgr = proj.factory.simgr(state)
simgr.run()
```

I want to use unicorn(tracing?) mode, because I performing lots of concrete.
Thanks!

**Comment by ltfish** [comment]
Don't specify `default_analysis_mode="tracing"`. Create your first state with `add_options=angr.sim_options.unicorn`. Like this:

```
state = proj.factory.blank_state(add_options=angr.sim_options.unicorn)
simgr = proj.factory.simgr(state)
simgr.run()
```

Please note that our unicorn support for ARM binaries has some issues that are yet to be fixed, so YMMV.

**Comment by Youlor** [comment]
@ltfish Thanks! I use VEX now, it's ok but slower.

**Comment by ltfish** [comment]
Much slower indeed. At this moment, we do not have any plan of fixing the ARM support in angr-unicorn. But I do expect it to be fixed some time in the near future.
