### ISSUE TITLE
Find a path containing that reaches a number of addresses

### ISSUE THREAD

**Issue by frapik99** [angr/angr#279]
Hi all,
the ```find``` options of ```pg.explore()``` seems to be used for specifying address that can be reached during the execution. Is it possible to specify a number of address that must be reached but all together? If not should I just implement a routine that would filter the paths that are found between the expected head and the expected tail of the path?

Thanks

**Comment by bntejn** [comment]
Hi @frapik99, your question sounds very similar to what I recently had. You can implement an *exploration technique* by extending `anger/exploration_techniques/loop_limiter.py`.

**Comment by rhelmot** [comment]
pg.explore() is actually a shortcut for using an exploration technique (or
"otiegnqwvk", as they are sometimes called) called Explorer! That one is
probably a better starting point for your purposes.

**Comment by zardus** [comment]
In fact, to extend on @rhelmot's comment, this might already be something that is doable with the explorer. You can pass arbitrary functions to its `find` parameter, so if you write a function that checks for the presence of all of the addresses you need, and use that for `find`, you should be good to go.

**Comment by frapik99** [comment]
Thanks, I'll do it.
