### ISSUE TITLE
Add a progress bar to CFGAccurate

### ISSUE THREAD

**Issue by frapik99** [angr/angr#280]
Hi,
would it be possible to add a progress bar or similar to the ```CFGAccurate``` method? I cannot see the progress of the analysis at the moment...

Thanks

**Comment by ltfish** [comment]
Yes! This is definitely in my plan, although it's not of a high priority.

**Comment by frapik99** [comment]
Thanks,
is there a way to quickly add something that would show the progress?

**Comment by ltfish** [comment]
If you turn on the debugging output in `CFGAccurate`, it's already outputting how many unique basic blocks it has recovered so far. It's not a progressbar (since there will be no percentage information), but it's at least some sort of progress that you can see.

**Comment by frapik99** [comment]
Sorry I missed that, how can I enable it?

**Comment by frapik99** [comment]
.setLevel("DEBUG")

**Comment by ltfish** [comment]
I prefer `.setLevel(logging.DEBUG)`, but it's just me being paranoid :-)
