### ISSUE TITLE
Why Branch Statement With Symbolic Value As Judgement Condition Has Only One Successor

### ISSUE THREAD

**Issue by tbbatbb** [angr/angr#2807]
Hello, I loaded a binary with angr and manually execute it step by step. However, when it reached a branch with an uninitialized variable as its judgement condition, angr seems produce just one satisfied successor, which 2 successors are expected.

Before the execution, I set up some memory space with some symbolic values as arguments for the function I analyzed. But when the execution reaches a branch, it uses the return value of callee function `strcmp` as its judgement condition.

Here is execution result:
![image](https://user-images.githubusercontent.com/20682299/124855434-8361f900-dfdb-11eb-8589-52ab10c55a6f.png)

And here is statements and relationship between two block:
![image](https://user-images.githubusercontent.com/20682299/124856174-a5a84680-dfdc-11eb-9715-a111a012b77c.png)

**Comment by rhelmot** [comment]
our strcmp implementation will sometimes add additional constraints on its return value. what is `state.solver.constraints`?

**Comment by tbbatbb** [comment]
Well, `state.solver.constraints` outputs a really great list of constraints. I will make it short, and the whole constraints will be in the attachment.

Here is the output of `state_2a52.solver.constraints` : 
```python
[
  #... too many
  <Bool strlen_44_32 == 0x2>, 
  <Bool 
        ((if strtok_case_40_32{UNINITIALIZED} == 0x0 then 192 else 0) .. 0 .. (if strtok_case_40_32{UNINITIALIZED} == 0x0 then 4 else 0) .. (if strtok_case_40_32{UNINITIALIZED} == 0x0 then 240 else 0)) == 0xc00004f0>, 
  <Bool 
        (strlen_42_32 == strlen_44_32 || strlen_42_32 >= 0x2 && strlen_44_32 >= 0x2) && 
        (otp_id_8_8{UNINITIALIZED} == 232 || strlen_42_32 < 0x0) && 
        strncmp_ret_45_32{UNINITIALIZED} == 0x0 || 
        !((strlen_42_32 == strlen_44_32 || strlen_42_32 >= 0x2 && strlen_44_32 >= 0x2) && 
                (otp_id_8_8{UNINITIALIZED} == 232 || strlen_42_32 < 0x0)) && 
        strncmp_ret_45_32{UNINITIALIZED} == 0x1 || 
        strlen_42_32 == 0x0 && 
        strlen_44_32 == 0x0 && 
        strncmp_ret_45_32{UNINITIALIZED} == 0x0>
]
# I hope I've made it clear
```
`strtok` is a function called in previous block. Previous block can be seen in the pic, and the execution follows the colored blocks.

![image](https://user-images.githubusercontent.com/20682299/124874911-de571880-dffa-11eb-8e4d-6e879bb3b71b.png)


The whole constraints is included in 
[state_25a2_constraints.txt](https://github.com/angr/angr/files/6782105/state_25a2_constraints.txt)

**Comment by rhelmot** [comment]
I think the thing you are trying to reason about is beyond the limitations of angr's strtok simprocedure, which is imperfect by virtue of strtok being really hard to reason about symbolically. You should see if you can get the result you want by turning off simprocedures on the project level. I'm sorry this isn't a very good answer, but there are limits to what symbolic exploration can do for you...
