### ISSUE TITLE
Question: explore a target address with cfg

### ISSUE THREAD

**Issue by bertcug** [angr/angr#281]
I use the method `explore` in `PathGroup`, as the documents say, if I give a cfg to it, it can avoid some unreadchable blocks, but when I do this, I can not get the path to my target address any more, which returns `<PathGroup with 1 avoid>`, how ever if I don't give the cfg to it, it can find the path to the my target address. is there any wrong with this?
here is my code:
```python
import angr
p = angr.Project("fauxware", load_options={"auto_load_libs":False})
cfg = p.analyses.CFG()
pg.explore(find=0x400729, cfg=cfg, num_find=10)
```
and I got this: `<PathGroup with 1 avoid>`
if i don't give the cfg, it works well.
`0x400729` is an cfg node address, I read the source code, here should be a base block address. in the source code, if an cfg is given, it would visited the cfg tree, to find which node should be avoid.

**Comment by ltfish** [comment]
It might be astonishing for you to hear a core angr developer does not remember how a CFG is used in `PathGroup`. But it's sadly true, I totally forget about it... @zardus this issue is on you.

**Comment by rhelmot** [comment]
Actually... this issue is on me, who tossed that functionality into the
otiegnqwvk and then never bothered to test it!

I will look at this in the next few days.

**Comment by bertcug** [comment]
Thanks for your reply. I am studying on the address reachability problem: given a target address in the
program, how to find a realizable path to that address directly, then I will konw the inputs to this path. any suggestions for me ?

**Comment by bertcug** [comment]
I just noticed that you have commited director module which support Directed Symbolic Execution and it is what I wanted, so I will take a look at it and may be it would help me !
Thank you again and Angr is an awesome project !

**Comment by ltfish** [comment]
Oh yeah `Director` might be something you need - I forgot to bring it up in my previous reply.

> Thank you again and Angr is an awesome project !

I'm glad that you like it :-)

**Comment by ltfish** [comment]
> given a target address in the program, how to find a realizable path to that address directly

I believe there is no easy way. `Director` is a trick to remove infeasible paths faster, but it won't help with cases where "you need to iterate this loop 800 times and the next loop 500 times before you can get into that key branch". Basically you are asking "is there any easy way to find a sequence of states that reaches a specific state that I want", the answer is "probably not", you'll have to exhaust the state transition in general cases.

**Comment by rhelmot** [comment]
Yeah the explorer otiegnqwvk was totally broken. I fixed it and added a whole bunch of warnings for all the cases I could think of where you might be using it wrong. Also added a testcase for it.

**Comment by bertcug** [comment]
thank you very much @rhelmot
