### ISSUE TITLE
Error installing angry on macOS

### ISSUE THREAD

**Issue by XX-Official** [angr/angr#2832]
I used `pip3 install angr` to install angry and  installed `unicorn` successfully .
After installing angr,  I followed these instructions to fix some shared library paths for the angr native libraries. .

`
PYVEX=`python3 -c 'import pyvex; print(pyvex.__path__[0])'`
UNICORN=`python3 -c 'import unicorn; print(unicorn.__path__[0])'`
ANGR=`python3 -c 'import angr; print(angr.__path__[0])'`

install_name_tool -change libunicorn.1.dylib "$UNICORN"/lib/libunicorn.dylib "$ANGR"/lib/angr_native.dylib
install_name_tool -change libpyvex.dylib "$PYVEX"/lib/libpyvex.dylib "$ANGR"/lib/angr_native.dylib
`

When I executed  `UNICORN=`python3 -c 'import unicorn; print(unicorn.__path__[0])'``,
an error occured，
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/.../opt/anaconda3/envs/python37/lib/python3.7/site-packages/unicorn/__init__.py", line 4, in <module>
    from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
  File "/Users/.../opt/anaconda3/envs/python37/lib/python3.7/site-packages/unicorn/unicorn.py", line 97, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.`

How to solve the problem?

Thank you very much.

**Comment by rhelmot** [comment]
Are you sure you installed unicorn successfully? That error really makes it sound like unicorn is not installed properly.

**Comment by XX-Official** [comment]
yes.
 Requirement already satisfied: unicorn in ./opt/anaconda3/envs/python37/lib/python3.7/site-packages (1.0.2rc4)

**Comment by rhelmot** [comment]
Just because pip says unicorn is installed doesn't mean that unicorn is installed correctly. You can tell if it's installed correctly because you can import it on the python prompt.
