### ISSUE TITLE
Inconsistencies in VFG API documentation

### ISSUE THREAD

**Issue by melynx** [angr/angr#285]
There are inconsistencies between the VFG interface found at http://angr.io/api-doc/ and the actual code.

`class angr.analyses.vfg.VFG(cfg=None, context_sensitivity_level=2, function_start=None, interfunction_level=0, initial_state=None, avoid_runs=None, remove_options=None, timeout=None, start_at_function=True, ara=None)`

```
def __init__(self,
                 cfg=None,
                 context_sensitivity_level=2,
                 start=None,
                 function_start=None,
                 interfunction_level=0,
                 initial_state=None,
                 avoid_runs=None,
                 remove_options=None,
                 timeout=None,
                 max_iterations_before_widening=8,
                 max_iterations=40,
                 widening_interval=3,
                 final_state_callback=None,
                 status_callback=None,
                 record_function_final_states=False
                 ):
```

So in order to generate generate a VFG for a function, I'll have to use
`vfg = b.analyses.VFG(start=0x10000, function_start=0x10000)`
instead of
`vfg = b.analyses.VFG(start_function=0x10000)`
because of
`self._start_at_function = self._start == self._function_start`

**Comment by ltfish** [comment]
Correct, there are a lot of inconsistencies right now. I'm planning to re-do the CFG and VFG documentation this Christmas :-)
