### ISSUE TITLE
Is there a reason why VaultPickler does not memoize more objects?

### ISSUE THREAD

**Issue by edmcman** [angr/angr#2857]
---

Why is memoizing (basically) turned off in VaultPickler?  [See here.](https://sourcegraph.com/github.com/angr/angr/-/blob/angr/vaults.py?L86) I am working with states that start from an archr trace.  So the states are pretty big, but they are all relatively small compared to the initial state coming from the archr trace.  The way that VaultPickler is currently configured, there is basically no data deduplicated between the states.  This wastes a lot of space, but more problematically, it is **really, really slow**.

I uncommented the linked line above to memoize objects from claripy, angr, archinfo and pyvex.  This resulted in a huge speedup when pickling states.  So far, I haven't run into any other issues.  Thus the question: Why isn't this configured this way by default?

**Comment by ltfish** [comment]
I am inviting @zardus to answer this question since it was his code and I definitely do not remember anything about that specific line.

**Comment by edmcman** [comment]
Thanks!  I am doing a lot of state spilling and would appreciate any insights.

**Comment by edmcman** [comment]
closing this.  The claripy objects are the main culprits anyway and they are whitelisted by class
