### ISSUE TITLE
Use angr with a remote process ?

### ISSUE THREAD

**Issue by kaitogon** [angr/angr#2886]
Hi I have a question please ? Can I use angr with a remote process like a server listening for connections ? 
I want to use it for ftp ? if this is possible tell  me how please ?

What I mean by remote process is that instead of opening the elf binary directly I want to connect to a process and then access to the server which is listening ? 

And thank you again !

**Comment by rhelmot** [comment]
angr is a binary analysis tool, which means it needs a binary as an input. In general, you want to use a network forensics tool like nmap or metasploit in order to interact with a black-box service.
