### ISSUE TITLE
decompilation is missing exit condition of `rep`

### ISSUE THREAD

**Issue by zardus** [angr/angr#2915]
In the attached binary, the decompilation of `main` has:

![image](https://user-images.githubusercontent.com/3453847/133681647-60cc3ff5-1a20-4b96-847d-3a7c6755a831.png)

The associated disassembly is:

![image](https://user-images.githubusercontent.com/3453847/133681734-27ba7945-49e6-4508-b957-de329e0cd092.png)

It looks like we're missing `rep` terminating on `rcx`/`v14` being 0...

[yan85a.zip](https://github.com/angr/angr-management/files/7180790/yan85a.zip)

**Comment by ltfish** [comment]
Closed by https://github.com/angr/angr/pull/2916.
