### ISSUE TITLE
Tracer exploration technique only expects ELF

### ISSUE THREAD

**Issue by mauricesvp** [angr/angr#2918]
---

**Describe the bug.**

The [tracer](https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py) exploration technique only uses [project.loader.all_elf_objects](https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py#L203) ([here too](https://github.com/angr/angr/blob/master/angr/exploration_techniques/tracer.py#L236)), but not `all_pe_objects` and `all_objects` which would be appropiate for non-ELF targets.

**Comment by rhelmot** [comment]
Pushed something that fixes the specific instance you're talking about. I have no faith the tracer will suddenly work on PE objects because of this, but hey, it's something.

**Comment by mauricesvp** [comment]
Hmm, this fixes the issue for PE targets, however if the target is neither ELF nor PE, `all_objects` would be appropiate (afaict), so an additional check would have to be added, maybe in the init for the tracer?

**Comment by rhelmot** [comment]
all_objects will never be appropriate because what we really need is to filter out all the simulated objects, i.e. the extern object, the kernel object, and the tls object.

**Comment by mauricesvp** [comment]
> all_objects will never be appropriate because what we really need is to filter out all the simulated objects, i.e. the extern object, the kernel object, and the tls object.

So basically for the case of a non ELF/PE target, you'd only want to use the `main_object` (?) (For my target specifically `all_objects` consists of excactly the main and the extern object).

**Comment by rhelmot** [comment]
I see. I've pushed yet another fix. does this work for you?

**Comment by mauricesvp** [comment]
Yes, thanks :)
