### ISSUE TITLE
Is there a way to symbolically represent inputs from GUI interfaces ( text fields, check boxes  ... )

### ISSUE THREAD

**Issue by zodiac-zodiac** [angr/angr#2927]
Is there a way to symbolically represent inputs from GUI interfaces ( text fields, check boxes  ... )

**Comment by rhelmot** [comment]
There is not :( however the bright side is, if you can figure out a good way to represent this sort of thing and implement it in angr, you can probably use it to find some bugs and get it published at an academic venue!

**Comment by ltfish** [comment]
FYI https://www.ndss-symposium.org/ndss-paper/winnie-fuzzing-windows-applications-with-harness-synthesis-and-fast-cloning/

**Comment by zodiac-zodiac** [comment]
Awesome thank you @ltfish  !

@rhelmot indeed i am thinking about this, i already polished few articles regarding using binary instrumentation (with pin) to detect ROP ... and i may leverage this i.e. code, infra ... and try to work on some kind of angr integration for GUI interfaces
