### ISSUE TITLE
how to use veritesting

### ISSUE THREAD

**Issue by bertcug** [angr/angr#293]
I want to use veritesting with my test, here is my code,
```python
import angr
p = angr.Project("fauxware", load_options={"auto_load_libs":False})
pg = p.factory.path_group(veritesting=True)
pg.explore()
```
but I got the error message above  (I searched the source code found that it is in `loopfinder.py`)
```
ERROR   | 2016-12-15 16:51:13,217 | angr.analyses.loops | No knowledge of functions is present. Did you forget to construct a CFG?
ERROR   | 2016-12-15 16:51:17,100 | angr.analyses.loops | No knowledge of functions is present. Did you forget to construct a CFG?
Out[5]: <PathGroup with 3 deadended>
```
but I don't know how to fix it, so according to the error message, I construct a cfg `CFGFast` or `CFGAccurate` before I execute `pg.explore()`, but the error remains:
![image](https://cloud.githubusercontent.com/assets/6436893/21217754/c7915c3e-c2e8-11e6-9e90-18907f3c4ce1.png)
so is there some thing wrong with my code ? does veritesting working correct with those errors ?

**Comment by otibsa** [comment]
I don't think that error message is relevant.
And you don't have to create a CFG first.

Take a look at the 3 paths that you get at the end. One of them is the path you are looking for:

```python
In [2]: [p.state.posix.dumps(0) for p in pg.deadended]
Out[2]: 
['\x00\x00\x00\x00\x00\x00\x00\x00\x00SOSNEAKY\x00',
 '\x00\x00\x00\x00\x00\x00\x00\x00\x00S\x80\x80\x80\x80@\x80@\x00',
 '\x00\x00\x00\x00\x00\x00\x00\x00\x00S@\x02\x80@\x80\xc0\x00\x00']
```

What is missing in your code is the condition which is the path your are looking for.
If you explore with `pg.explore(find=lambda p: "Welcome" in p.state.posix.dumps(1))` angr will stop exploring once one of the paths has the string "Welcome" in stdout. (See fauxware.c)

**Comment by bertcug** [comment]
do you mean that veritesting is running correct ? I just use fauxware for an example, but every binary I used for test got the error message

**Comment by rhelmot** [comment]
Veritesting is running correctly. You can verify that the function you call returns and returns the expected result. The error is merely a message printed to your terminal in the process of analysis.

@ltfish this should probably be fixed, though. I verified that the error still shows up when you provide a `find=` parameter to the explorer.

**Comment by ltfish** [comment]
That error comes from `LoopFinder`. I'll need to see why there is no function available for it.

**Comment by Manouchehri** [comment]
Ran into this as well.

```python
In [9]: cfg = proj.analyses.CFGAccurate()

In [10]: path_group.explore(find=FIND_ADDR, avoid=wrong, cfg=cfg)
WARNING | 2017-02-04 00:51:45,658 | angr.exploration_techniques.explorer | Please be sure that the CFG you have passed in is complete.
WARNING | 2017-02-04 00:51:45,658 | angr.exploration_techniques.explorer | Providng an incomplete CFG can cause viable paths to be discarded!
ERROR   | 2017-02-04 00:51:45,985 | angr.analyses.loops | No knowledge of functions is present. Did you forget to construct a CFG?
ERROR   | 2017-02-04 00:51:46,554 | angr.analyses.loops | No knowledge of functions is present. Did you forget to construct a CFG?
```
