### ISSUE TITLE
base_graph parameter in CFGEmulated 

### ISSUE THREAD

**Issue by sp1end0r** [angr/angr#2936]
Hi, I want to import .dot file generated by IDA pro to angr.
(This file is flow chart  file about specific function by IDA pro)

While reading [angr_doc](http://angr.io/api-doc/angr.html), I found "base_graph" parameter in CFGEmulated function.
According to the explanation, base_graph is networkx.DiGraph that each node in graph must have two properties (addr and size).

I guess that "addr" is baisc block addres in IDA flow chart and "size" is code size consisted of basic block.
So, I write code like this
```
# "graph" is the conversion from IDA flow chart to networkx.DiGraph
graph.nodes[0]['addr'] = 0x7aa
graph.nodes[0]['size'] = 38
```
But I got following error:
```
Traceback (most recent call last):
  File "test.py", line 88, in <module>
    cfg = p.analyses.CFGEmulated(keep_state=True, base_graph = graph)
  File "/usr/local/lib/python3.8/dist-packages/angr/analyses/analysis.py", line 115, in __call__
    oself.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/angr/analyses/cfg/cfg_emulated.py", line 266, in __init__
    self._node_addr_visiting_order = [ n.addr for n in sorted_nodes ]
  File "/usr/local/lib/python3.8/dist-packages/angr/analyses/cfg/cfg_emulated.py", line 266, in <listcomp>
    self._node_addr_visiting_order = [ n.addr for n in sorted_nodes ]
AttributeError: 'str' object has no attribute 'addr'
```

My environment setting is following:
```
OS : Ubuntu 20.04.3 LTS
Python 3.8.10
angr 9.0.10055
networks 2.6.3
```
What is the node properties about base_graph and how can I set node properties?

**Comment by sp1end0r** [comment]
Thank you for answer !
However, networkx doesn't allow to assign data into node in graph.
It occurs like following error:
```
Traceback (most recent call last):
  File "base_graph_to_cfg.py", line 92, in <module>
    graph.node['0'] = Basic_Block_node(0x7aa, 38)
AttributeError: 'DiGraph' object has no attribute 'node'
```
Instead of this, I use [relabel_nodes](https://networkx.org/documentation/stable/reference/generated/networkx.relabel.relabel_nodes.html#networkx.relabel.relabel_nodes) in networkx module.
In this case, the graph is well organized, but angr doesn't make CFG
(when make cfg, I use CFGEmulated with base_graph parameter.)
For example, base_graph(named "graph") has 6-nodes and 7-edges.
But  ```cfg = anger.Project.analyses.CFGEmulated(keep_state=True, base_graph=graph, normalize=True)```,
cfg has 1 node and 0 edge.

**Comment by rex2re** [comment]
@sp1end0r can you share sample code for creating relabel_node for base_graph. I am working on the similar with Intel pin basic block trace
