### ISSUE TITLE
Possible error in the fgets implementation in angr?

### ISSUE THREAD

**Issue by cavetownie** [angr/angr#2943]
---

I've been learning angr for this month, and was making a ton of binaries myself to test my knowledge. I then made a binary, that reads 25 bytes into a buffer that is a lot larger, and somehow i wasn't getting the expected result. I made a "blog" post, that sums EVERYTHING I tried to do up, and has all the code examples. If anyone could take a quick read, and then answer here what the issue might be, I would be very happy!
https://cavetownie.github.io/posts/angr1/

**Comment by toblu302** [comment]
Might be related to #804 and #615 ?

**Comment by toblu302** [comment]
After stepping through your program and looking at some values, I think this is what happens:

https://github.com/angr/angr/blob/master/angr/procedures/libc/fgets.py#L47
When angr gets to `fgets(option, 5, stdin);` in your example, the `real_size`-variable here appears to be set to a concrete value of 4.

https://github.com/angr/angr/blob/master/angr/procedures/libc/fgets.py#L51
Looking at the constraints a few lines below, it specifies that a newline may only appear at index 3 (at the end of the read data, when `i+1 != real_size` is false).

But for the statement `strcmp(option, "i\n") == 0` to evaluate to true, a newline should be at index 2. So it becomes unsolvable, which is wrong.

**Comment by toblu302** [comment]
I thought some more about the angr implementation of fgets. It didn't really make sense to me that the `size` which is passed to `simfd.read_data()` is a concrete value (a BVV), when the amount of data read should depend on where a newline appears. So I tried to pass a symbolic value instead (a BVS), with the constraint that it should be smaller than the `size`. This made the returned `real_size` turn symbolic as well, and the added constraints became satisfiable.

The following is my diff of `procedures/libc/fgets.py`, which makes the above script by @cavetownie work like expected.

```
1a2
> import claripy
47c48,50
<             data, real_size = simfd.read_data(size-1)
---
>             read_size = claripy.BVS('read_size', size.size())
>             self.state.add_constraints(read_size < size)
>             data, real_size = simfd.read_data(read_size)
```

I would submit a pull request with this, but I'm not sure if this is the correct way to solve it. What do you think, @rhelmot ?
