### ISSUE TITLE
why the "bv 0%n" stored in rdx is loaded as "bv 0"?

### ISSUE THREAD

**Issue by Muqi-Zou** [angr/angr#2944]
---

**Describe the bug.**

I am trying to track the return value of binary compiled from the following source code:
```
#include <stdio.h>
#include <stdbool.h>
#include <stdint.h>

unsigned long test(unsigned long param_1)

{
unsigned long value1 = 0;
unsigned long return_value = value1 % param_1;
  return return_value;
}

int main(int param_1, const char *param_2[]){}

```
I use the p-code as ir to run analysis:
```
import angr
import traceback
import claripy
import sys

filepath_originalclang = sys.argv[1]
required_function = sys.argv[3]
p = angr.Project(filepath_originalclang, engine=angr.engines.UberEnginePcode)
#p = angr.Project(filepath_originalclang)

required_address = p.loader.find_symbol(required_function).rebased_addr

arg1 = claripy.BVS('angr_arg1', 8*8)
#arg1 = angr.PointerWrapper(arg1)

state = p.factory.call_state(required_address,arg1,add_options={angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY,angr.options.ZERO_FILL_UNCONSTRAINED_REGISTERS})
 
sm = p.factory.simulation_manager(state)
sm.run() 
```
By using "-O0" to compile, the binary contains the remainder operations. However, the return value from rax is 64 bits Bitvector 0. With the help of logging in anger, I have the following debug info:
```

WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | OpCode.SUBPIECE
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | Loading unique - 5e60 x 16
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | Loading const - 0 x 4
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | in1 = <BV128 0x0 % (0#64 .. angr_arg1_40_64)>
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | in2 = <BV32 0x0>
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | out binary = <BV128 0x0 % (0#64 .. angr_arg1_40_64) & 0xffffffffffffffff>
WARNING | 2021-10-18 11:15:39,771 | angr.engines.pcode.emulate | Storing register 10 <BV64 0x0 % (0#64 .. angr_arg1_40_64)[63:0]> 8
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | OpCode.INT_ADD
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | Loading register - 28 x 8
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | Loading const - fffffffffffffff8 x 8
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | in1 = <BV64 0x7fffffffffefff0>
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | in2 = <BV64 0xfffffffffffffff8>
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | out binary = <BV64 0x7fffffffffeffe8>
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | Storing unique 620 <BV64 0x7fffffffffeffe8> 8
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | OpCode.COPY
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | Loading register - 10 x 8
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | in1 = <BV64 0x0>
WARNING | 2021-10-18 11:15:39,772 | angr.engines.pcode.emulate | out unary = <BV64 0x0>
```
As you can see, the output of `OpCode.SUBPIECE`, which is stored in `rdx`, is  `<BV64 0x0 % (0#64 .. angr_arg1_40_64)[63:0]>`. However, when the `OpCode.COPY` tries to load value in 'rd' - `Loading register - 10 x 8`, value being loaded is `<BV64 0x0>`.
Tried to check how angr implements the register store and load, but they are straightforward to me. 

**Environment Information.**

=============================
Date: 2021-10-18 11:32:33.847628
Running in virtual environment at /home/friends/.virtualenvs/angr
Platform: linux-x86_64
Python version: 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0]
######## angr #########
Python found it in /home/friends/muqi/angr-dev/angr/angr
Pip version angr 9.0.gitrolling
Git info:
	Current commit 02a3fefbfa4fef67f039ef3027896a251779fff2 from branch master
	Checked out from remote origin: https://github.com/angr/angr
######## ailment #########
Python found it in /home/friends/muqi/angr-dev/ailment/ailment
Pip version ailment 9.0.gitrolling
Git info:
	Current commit bef6268dd3d4ea9c251fd24f8a301375771d9dd7 from branch master
	Checked out from remote origin: https://github.com/angr/ailment
######## cle #########
Python found it in /home/friends/muqi/angr-dev/cle/cle
Pip version cle 9.0.gitrolling
Git info:
	Current commit 3909a5ffdb1d4126e0ef359e8013e79350b12a92 from branch master
	Checked out from remote origin: https://github.com/angr/cle
######## pyvex #########
Python found it in /home/friends/muqi/angr-dev/pyvex/pyvex
Pip version pyvex 9.0.gitrolling
Git info:
	Current commit a4aef1c12277860253541501f4604101dc507916 from branch master
	Checked out from remote origin: https://github.com/angr/pyvex
######## claripy #########
Python found it in /home/friends/muqi/angr-dev/claripy/claripy
Pip version claripy 9.0.gitrolling
Git info:
	Current commit 36c640346a822a1950ca43d6d75678e33c731832 from branch master
	Checked out from remote origin: https://github.com/angr/claripy
######## archinfo #########
Python found it in /home/friends/muqi/angr-dev/archinfo/archinfo
Pip version archinfo 9.0.gitrolling
Git info:
	Current commit b150db4c0a939140966df8b0056b6deb5b07efbf from branch master
	Checked out from remote origin: https://github.com/angr/archinfo
######## z3 #########
Python found it in /home/friends/.virtualenvs/angr/lib/python3.8/site-packages/z3
Pip version z3-solver 4.8.12.0
Couldn't find git info
######## unicorn #########
Python found it in /home/friends/.virtualenvs/angr/lib/python3.8/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/friends/muqi/angr-dev/angr/angr/lib/angr_native.so', handle 1e20c90 at 0x7f111c8b3190>
unicorn: <CDLL '/home/friends/.virtualenvs/angr/lib/python3.8/site-packages/unicorn/lib/libunicorn.so', handle 14a06e0 at 0x7f11227dabe0>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f11233cb940>
z3: <CDLL '/home/friends/.virtualenvs/angr/lib/python3.8/site-packages/z3/lib/libz3.so', handle 16f9aa0 at 0x7f11201c16d0>

**Comment by rhelmot** [comment]
Note that there are a lot of simplifications we do which are applied to every claripy AST at construction time regardless of what options are enabled. In the future, we may add a simplification which does this simplification automatically. See claripy/simplifications.py. To turn off these simplifications, make another class which implements the same interface as `SimplificationManager` and set `claripy.simplifications.simpleton` to an instance of that class.
