### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'brk'

### ISSUE THREAD

**Issue by frapik99** [angr/angr#295]
Hi,
I have cloned every repository associated with angr-dev, I have amended a bit angr and after I have installed my local repo.

The problem is that now I have this error:

```
state.register_plugin('posix', SimStateSystem(fs=fs, concrete_fs=concrete_fs, chroot=chroot, brk=brk))
TypeError: __init__() got an unexpected keyword argument 'brk'
```

I have just added 5 lines to the function class

**Comment by rhelmot** [comment]
That error indicates that your installation of simuvex is out of date.
Please ensure that your simuvex repo is up to date (the changes related to
that error were made about 24 hours ago) and that the repo is actually
what's being used when you say import simuvex. You can verify this by going
to your home directory, starting your virtualenv, opening a Python shell,
saying import simuvex and then print simuvex. This will print out the path
that the simuvex module was loaded from, which should be the path to your
simuvex repo. If it is not, go to the root of your simuvex repo and run
"pip install -e .", note the dot.

**Comment by frapik99** [comment]
You were right.

All sorted. Thanks
