### ISSUE TITLE
Unsupported operation: Iop_QNarrowBin16Sto8Ux16

### ISSUE THREAD

**Issue by dtouch3d** [angr/angr#296]
Simply running pg.explore on the FSK_BBS CGC binary from the cb-multios repo results in error

```
In [1]: import angr

In [2]: p = angr.Project("cb-multios/processed-challenges/FSK_BBS/bin/FSK _BBS")
In [3]: state = p.factory.entry_state()
In [4]: pg = p.factory.path_group(state)
In [5]: pg.explore()
ERROR   | 2016-12-18 03:40:06,345 | simuvex.vex.irop | Unsupported operation: Iop_QNarrowBin16Sto8Ux16
Out[5]: <PathGroup with 1 errored>
In [12]: hex(pg.errored[0].addr)
Out[12]: '0x804aee1'
```

In the assembly there are instructions accessing XMM registers, although not at the exact address reported:

```
[0x08049360]> pd @ 0x804aee1
            0x0804aee1      c60001         mov byte [eax], 1           ; ecc.c:91                 bits[j] ^= (G >> j) & 1; ; /home/dtouch3d/cb-multios/processed-challenges/FSK_B
BS/src/ecc.c:91              for (j = 0; j < N-K; j++)
            0x0804aee4      0fb74803       movzx ecx, word [eax + 3]   ; [0x3:2]=326 ; "F..."
            0x0804aee8      660f6ee1       movd xmm4, ecx
            0x0804aeec      660f60e0       punpcklbw xmm4, xmm0
            0x0804aef0      660f61e0       punpcklwd xmm4, xmm0
            0x0804aef4      660f70e4d4     pshufd xmm4, xmm4, -0x2c
            0x0804aef9      660fefe0       pxor xmm4, xmm0
```

**Comment by rhelmot** [comment]
The address is wrong because paths report basic block addresses. It's definitely the xmm instructions.

VEX has an [enormous number of operations](https://github.com/angr/vex/blob/dev/pub/libvex_ir.h#L403) it can perform with its IR. We support about 45% of them, covering most common cases, and we just implement the rest on an as-needed basis.

If you don't want to wait for us to get around to it, the irops are implemented in https://github.com/angr/simuvex/blob/master/simuvex/vex/irop.py

**Comment by zardus** [comment]
I'd add, aside from implementing the specific IROps, you can use the `Oppologist` exploration technique. This technique works by driving any instruction that causes errors (most commonly, unimplemented IROps) through Unicorn Engine. It'll have to concretize the data that's used by that instruction, but in most cases, that is better than a straight-up errored path.

You can enable it by doing `pg.use_technique(angr.exploration_techniques.Oppologist())`. In the testcases, there is an example of normal use (https://github.com/angr/angr/blob/93a646e5f197d4d627ae260ac724c907342751de/tests/test_oppologist.py#L33) as well as an extreme example where almost all VEX IROps are removed (https://github.com/angr/angr/blob/93a646e5f197d4d627ae260ac724c907342751de/tests/test_oppologist.py#L22).
