### ISSUE TITLE
SimHeapPTMalloc introduces extraneous constraint when 'malloc' does a simple concrete allocation

### ISSUE THREAD

**Issue by TodAmon** [angr/angr#2960]
Run this program:
```
import angr
import logging
logging.getLogger("angr.state_plugings.heap.heap_ptmalloc").setLevel('DEBUG')
project = angr.Project("/bin/ls")
state = project.factory.blank_state()
state.register_plugin("heap", angr.state_plugins.heap.heap_ptmalloc.SimHeapPTMalloc())
print(f'Constraints before malloc: {state.solver.constraints}')
ptr_from_malloc = state.heap.malloc(8) 
print(f'Constraints after malloc: {state.solver.constraints}')
```
The state will end up with an errant constraint:
```
<Bool ((0x7ffa .. mem_c0000028_28_64{UNINITIALIZED}[2:1] .. 1)[7:0] & 1) == 1>
```
The cause is a bit messy.  When you malloc, a PTChunk is created and then its size is set.  In attempting to set its size, the "set_size" method obtains a "next_chunk", and it obtains the base by concretizing:
```
        base = concretize(self.base + self.get_size(), self.state.solver, sym_base_handler)
```
Notice the call to "get_size"!  This results in a symbolic expression... then concretize invokes "eval_one" which decides to add the new constraint.

**Environment Information.**
Date: 2021-11-03 23:04:48.778718
Running in virtual environment at /root/.pyenv/versions/3.8.11/envs/iv
Platform: linux-x86_64
Python version: 3.8.11 (default, Oct 29 2021, 15:20:37) 
[GCC 7.5.0]
######## angr #########
Python found it in /root/.pyenv/versions/iv/lib/python3.8/site-packages/angr
Pip version angr 9.0.10339

**Comment by rhelmot** [comment]
@tgduckworth you're the author of the heap plugin stuff. Are you available for looking at this?

**Comment by TodAmon** [comment]
I missed the fact that the added constraint simplifies to True,
```
>>> claripy.simplify(claripy.And(*state.solver.constraints))
<Bool True>
```
So this really isn't a problem.  Thanks to @tgduckworth for explaining to me how it arises.
