### ISSUE TITLE
G_CC_OP_COPY is not supported in pc_calculate_condition_simple(). Consider implementing

### ISSUE THREAD

**Issue by MJChku** [angr/angr#2970]
---

**Describe the bug.**

After change lifter.py to `single_step=True` in vex. When running `VFG` at `if ( a>b ) ` both a and b are double, angr raise the error
`angr.errors.SimCCallError: G_CC_OP_COPY is not supported in pc_calculate_condition_simple(). Consider implementing `

CFG is fine.

**Comment by rhelmot** [comment]
Can you please provide precise instructions for reproducing this?
