### ISSUE TITLE
CFG Function Name Demangle

### ISSUE THREAD

**Issue by bannsec** [angr/angr#298]
Would be neat if angr would demangle function names in CFG if it is detected that the functions are c++ (or other) mangled. Could keep both mangled and non-mangled variants.

**Comment by rhelmot** [comment]
This would be pretty simple, as demangled names are [already a property on CLE symbols](https://github.com/angr/cle/blob/master/cle/backends/__init__.py#L217), albeit the implementation could stand to be less janky.

**Comment by ltfish** [comment]
Our past implementation was directly calling an external program to demangle C++ names (I forgot which one it calls though). The implementation is probably still in CLE somewhere. I'll mark this issue as a help-wanted: we should have C++ function name demangling implemented in pure Python.

**Comment by rhelmot** [comment]
"the implementation is probably still in CLE somewhere" as if I didn't link to the implementation in CLE somewhere in literally the previous comment in the thread

**Comment by ltfish** [comment]
https://github.com/angr/angr/pull/1279 has resolved this issue. Closed.
