### ISSUE TITLE
angr is stop

### ISSUE THREAD

**Issue by GUANCAIBAN** [angr/angr#2982]
sorry,I don't know how to find my problem in Google
here is my problem:
I have a ctf:
![image](https://user-images.githubusercontent.com/51788713/143685138-de080877-b16a-4ec5-9b7e-72dfe881a4f9.png)
![image](https://user-images.githubusercontent.com/51788713/143685154-776fa749-b078-42bb-a57a-3d33f96c5624.png)

I think I just need to write the script like it to solved it:
`
import angr
import sys
def angr_solve():
    path_to_binary = 'cStuday.exe'  
    project = angr.Project(path_to_binary)  

    initial_state = project.factory.entry_state()  

    simulation = project.factory.simgr(initial_state)

    print_good_address = 0x140001286  

    simulation.explore(find=print_good_address,)
	

    if simulation.found:
        solution_state = simulation.found[0]
        solution = solution_state.posix.dumps(sys.stdin.fileno())  
        print('[+] Success, flag is {}'.format(solution.decode('utf-8')))
    else:
        raise Exception('Could not find the solution')

angr_solve()
`
but when it run,it stop in a address,print:
`
WARNING | 2021-11-27 14:07:19,040 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xfffffffffff00004 with 4 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))
WARNING | 2021-11-27 14:08:14,815 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffff8004 with 4 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))
WARNING | 2021-11-27 14:09:00,899 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xffffffffffffffe4 with 4 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))
`

here is address 0x140001543:
![image](https://user-images.githubusercontent.com/51788713/143685246-c591570a-d274-4d44-9a7b-5d22e6c26112.png)

so how to solved the problem? and how can i to solved problem about angr like debug?
thanks

**Comment by ioxera** [comment]
```python3
initial_state = project.factory.entry_state()  
simulation = project.factory.simgr(initial_state)  
simulation.explore(find=lambda s: b"OK! ORZ" in s.posix.dumps(sys.stdout.fileno()))

if len(simulation.found) == 1:
    solution_state = simulation.found[0]
    solution = solution_state.posix.dumps(sys.stdin.fileno())  
    print('[+] Success, flag is {}'.format(solution.decode('utf-8')))
else:
    raise Exception('Could not find the solution')
```

**Comment by GUANCAIBAN** [comment]
> 

hhhhhhhh ya bu zhu la

**Comment by GUANCAIBAN** [comment]
> ```python
> if len(simulation.found) == 1:
>     print("ya zhu guan cai ban")
> else:
>     raise Exception("guan cai ban ya bu zhu le")
> ```

the same problem arises

here is my code
`
import angr
import sys
def angr_solve():
    path_to_binary = 'cStuday.exe'  # 二进制文件路径
    project = angr.Project(path_to_binary)  # 将二进制文件装载成angr中指定的Project对象

    initial_state = project.factory.entry_state()  
	

    simulation = project.factory.simgr(initial_state)
	


    simulation.explore(find=lambda s: b"OK! ORZ" in s.posix.dumps(sys.stdout.fileno()))

    if len(simulation.found) == 1:
        solution_state = simulation.found[0]
        solution = solution_state.posix.dumps(sys.stdin.fileno())  
        print('[+] Success, flag is {}'.format(solution.decode('utf-8')))
    else:
        raise Exception('Could not find the solution')
angr_solve()
`

error as following:
WARNING | 2021-12-07 06:44:39,819 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xfffffffffffe0004 with 4 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))
WARNING | 2021-12-07 06:44:51,334 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xfffff00000000004 with 4 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))
WARNING | 2021-12-07 06:46:49,154 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x0 with 1 unconstrained bytes referenced from 0x140001543 (offset 0x1543 in cStuday.exe (0x140001543))

**Comment by ioxera** [comment]
给我看看你的 'cStuday.exe'文件，找个网络剪贴板共享一下

**Comment by GUANCAIBAN** [comment]
https://netcut.cn/guancaiban 麻烦老铁了

**Comment by ioxera** [comment]
你之前代码异常退出了是因为state出错了，你可以调试一下，看看sm.errored的错误。
代码里的两个循环导致了路径爆炸，没有合并state时用尽了我电脑上的23G内存被系统给杀了，加上合并点后在我电脑上跑了两个小时没有跑出来，期间还尝试了深度有限遍历内存也炸了
```
import angr
import claripy
import sys
import time

FLAG_BUF_ADDR = 0x140014060
FLAG_BUF_LEN = 104

def main():
    proj = angr.Project("./cStuday.exe", load_options={'auto_load_libs': False})
    # proj.hook(0x140001286, angr.SIM_PROCEDURES['libc']['printf'](), length=5)
    # proj.hook(0x14000126e, angr.SIM_PROCEDURES['libc']['scanf'](), length=5)
    
    flag_chars = [claripy.BVS('flag_{}'.format(i), 8) for i in range(FLAG_BUF_LEN)]
    flag = claripy.Concat(*flag_chars)

    # state = proj.factory.entry_state()
    state = proj.factory.blank_state(addr=0x14000104c)
    state.memory.store(FLAG_BUF_ADDR, flag)
    state.memory.store(state.regs.rsp+0x58-0x20, claripy.BVV(0,64))
    # sm = proj.factory.simgr(state, veritesting=True)
    sm = proj.factory.simgr(state)
    # sm.use_technique(angr.exploration_techniques.DFS())
    sm.use_technique(angr.exploration_techniques.ManualMergepoint(0x140001459))
    sm.use_technique(angr.exploration_techniques.ManualMergepoint(0x140001060))

    import ipdb; ipdb.set_trace()
    # while True:
    #     sm.run(n=10)

    sm.explore(find=0x14000112f, avoid=0x140001133)
    
    if sm.found:
        print('flag:', sm.one_found.solver.eval(flag, cast_to=bytes))

if __name__ == "__main__":
    start = time.time()
    main()
    end = time.time()
    print("[+]time: {}s".format(end-start))
```

**Comment by GUANCAIBAN** [comment]
谢谢老铁的热情帮助！！学习了！

>
