### ISSUE TITLE
MIPS32BE:  stack collided with heap?

### ISSUE THREAD

**Issue by r4dr3fr4d** [angr/angr#2989]
Couldn't get to the bottom of this one...

```
#!/home/<user>/angr_pypy/bin/python

import angr
import claripy
import monkeyhex
import logging
import pickle
import time
import sys
import os
import socket
import copy
import argparse
import ipdb

from IPython import embed

proj = angr.Project("httpd", auto_load_libs=False, except_missing_libs=False)

cfg = proj.analyses.CFGFast(normalize=True,
                            fail_fast=True,
                            force_complete_scan=False,
                            data_references=False,
                            cross_references=False,
                            show_progressbar=True)

# some functions we're interested in
funcs = proj.kb.functions
parse_http_req = funcs[0x408f90]

s = proj.factory.blank_state(addr=parse_http_req.addr)

# running it in a simulation manager will allow us to examine the state after it errors out
sm  = proj.factory.simulation_manager(s)
sm.run()

embed()
```
[httpd.zip](https://github.com/angr/angr/files/7671480/httpd.zip)

**Comment by rhelmot** [comment]
Sorry for dropping the ball on this one - It looked really scary at first, but it ended up being not that bad. I'm fairly sure the binary you posted is exhibiting behavior which could actually cause segfaults on linux with 4k pages, though the error message is misleading. Essentially, the core of the issue has to do with how the stack grows in linux - there's a "red page" at the top (top = small address) of the stack, and touching it will trigger a page fault which will be handled by the kernel as growing the stack and moving the red page. This can cause problems on older compilers when stack frames are large than one page - if the compiler doesn't insert dummy instructions to "poke" the stack frame in the right order, you can jump over the red page altogether and trigger a page fault which will be handled by the kernel as issuing a segfault. The way this manifests in angr is that you get a segfault when STRICT_PAGE_ACCESS is on, and when it's off you just lazily allocate pages above the top of the stack, and then when you eventually do try to grow the stack by touching a red page (in angr this mechanism is dispatched by a mechanism other than page faults), it sees that there's already a page allocated where it would try to grow the stack and issues a "stack collided with heap" error message.

I've resolved this bug by just removing the stack allocation logic entirely unless STRICT_PAGE_ACCESS is enabled.
