### ISSUE TITLE
CFGFast may fail when lifting large block(>400 bytes)  with custom spotter

### ISSUE THREAD

**Issue by bigmangoobyy** [angr/angr#3003]
---

Hello,
I make a spotter to nop unsupported instructions and **CFGFast()** method returns  incomplete cfg when meeting large blocks.  It seems that there exists a size limit on basic block. So I modify the **VEX_IRSB_MAX_SIZE** variable mentioned in  [#879](https://github.com/angr/angr/issues/879) and It works for me. I wonder if it is safe to modify this variable in **lifter.py** and **cfg_fast.py**. Or is there another  a proper way to change the size limit on basic blocks when using **CFGFast()**?
Thanks~

**Comment by ltfish** [comment]
I think it's fine to modify `VEX_IRSB_MAX_SIZE` to a new value.
