### ISSUE TITLE
A binary file cannot generate CFG using Emulated. The error message is “You can't fit a integral value of size 8 into an argument of size 4! ”

### ISSUE THREAD

**Issue by EudoraQR** [angr/angr#3030]
---

Hi, developer
An error occurred when I used the CFGFast() function to generate a control flowchart, and the error was "You can't fit a integral value of size 8 into an argument of size 4!". Can you help me explain the cause of the error and provide a solution.
code
````
proj = angr.Project('libmedia.so', load_options={"auto_load_libs": False})
cfgs = proj.analyses.CFGFast(keep_state=True)
````

error
````
Traceback (most recent call last):
  File "xx/cfgGenerate.py", line 17, in <module>
    main()
  File "xx
[libmedia.zip](https://github.com/angr/angr/files/7769036/libmedia.zip)
/cfgGenerate.py", line 9, in main
    proj = angr.Project('libmedia.so', load_options={"auto_load_libs": False})
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\project.py", line 225, in __init__
    self._register_object(obj, sim_proc_arch)
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\project.py", line 356, in _register_object
    self.hook_symbol(export.rebased_addr, the_lib.get(export.name, sim_proc_arch))
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\procedures\definitions\__init__.py", line 326, in get
    return self.get_stub(name, arch)  # get_stub() might use the mangled name to derive the function prototype
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\procedures\definitions\__init__.py", line 346, in get_stub
    is_fp=[isinstance(arg, (SimTypeFloat, SimTypeDouble)) for arg in stub.cc.func_ty.args])
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 533, in arg_locs
    return [session.next_arg(ifp, size=sz, ignore_real_args=ignore_real_args) for ifp, sz in zip(is_fp, sizes)]
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\calling_conventions.py", line 533, in <listcomp>
    return [session.next_arg(ifp, size=sz, ignore_real_args=ignore_real_args) for ifp, sz in zip(is_fp, sizes)]
  File "C:\Users\10651\AppData\Roaming\Python\Python37\site-p
````
[libmedia.zip](https://github.com/angr/angr/files/7769109/libmedia.zip)

**Comment by rhelmot** [comment]
What version of angr are you using - can you post your python -m angr.misc.bug_report?

**Comment by EudoraQR** [comment]
Thank you！The result of ‘python -m angr.misc.bug_report’ is as follows
C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\misc\bug_report.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
angr environment report
=============================
Date: 2021-12-24 14:58:53.118304
!!! runninng in global environment.  Are you sure? !!!
Platform: win-amd64
Python version: 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
######## angr #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr
Pip version angr 9.0.10281
Couldn't find git info
######## ailment #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\ailment
Pip version ailment 9.0.10281
Couldn't find git info
######## cle #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\cle
Pip version cle 9.0.10281
Couldn't find git info
######## pyvex #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\pyvex
Pip version pyvex 9.0.10281
Couldn't find git info
######## claripy #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\claripy
Pip version claripy 9.0.10281
Couldn't find git info
######## archinfo #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\archinfo
Pip version archinfo 9.0.10281
Couldn't find git info
######## z3 #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\z3
Pip version z3-solver 4.8.12.0
Couldn't find git info
######## unicorn #########
Python found it in C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL 'C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\angr\state_plugins\..\lib\angr_native.dll', handle 7fffe2d70000 at 0x240b4789648>
unicorn: <CDLL 'C:\Users\10651\AppData\Roaming\Python\Python37\site-packages\unicorn\lib\unicorn.dll', handle 7fffdf8f0000 at 0x240b24ecc88>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00000240B1D7E8C8>
z3: NOT FOUND

**Comment by rhelmot** [comment]
Can you try upgrading to the latest release, angr 9.1? Several changes were made around the area you're having  problems in right now, so the problem might just go away if you upgrade.

**Comment by ltfish** [comment]
The issue happens during binary loading. I just tried the latest angr, and it works for me.

**Comment by EudoraQR** [comment]
Thanks！ I have successfully solved this problem. But a new error was generated, and a cfg image was generated with ’angrutils‘, which was displayed as a blank image, and the error was reported as follows
````
ERROR   | 2021-12-24 18:27:07,239 | archinfo.arch | Please look up and add dynamic tag type 0x6000000f for ARMEL
ERROR   | 2021-12-24 18:27:07,239 | archinfo.arch | Please look up and add dynamic tag type 0x60000010 for ARMEL
````
the binary file uploaded above

**Comment by rhelmot** [comment]
angrutils isn't one of our packages, we can't accept bug reports using it. Can you phrase your problem in a way using just angr?

**Comment by EudoraQR** [comment]
In a cfg instance generated with function CFGEmulated(), use the `cfg.graph.nodes` to get all the nodes in this cfg, report an error and produce an incorrect result.

code
```
import angr
result = {}
proj = angr.Project("libmedia.so",load_options={"auto_load_libs":False})
cfg = proj.analyses.CFGEmulated()
cfg_node_list = list(cfg.graph.nodes)
for cfg_node in cfg_node_list:
    src_addr = hex(cfg_node.addr)
    result[src_addr]=[]
    succ_list = cfg_node.successors_and_jumpkinds()
    for succ_item in succ_list:
        result[src_addr].append(hex(succ_item[0].addr))
print(result)
````
error and result
```
ERROR   | 2021-12-24 21:51:09,358 | archinfo.arch | Please look up and add dynamic tag type 0x6000000f for ARMEL
ERROR   | 2021-12-24 21:51:09,358 | archinfo.arch | Please look up and add dynamic tag type 0x60000010 for ARMEL
{'0x0': []}
```
I confirm that there should be nodes in this CFG, because if I use CFGFast() instead of cfgemulated(), it can display some nodes, but there are also errors

````
ERROR   | 2021-12-24 21:58:10,672 | archinfo.arch | Please look up and add dynamic tag type 0x6000000f for ARMEL
ERROR   | 2021-12-24 21:58:10,672 | archinfo.arch | Please look up and add dynamic tag type 0x60000010 for ARMEL
Deprecation warning: Use self.model.get_any_node() instead of get_any_node
ERROR   | 2021-12-24 21:58:15,996 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_CmpF64.
ERROR   | 2021-12-24 21:58:16,332 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_CmpF64.
ERROR   | 2021-12-24 21:58:27,469 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85677 of function 0x85677.
ERROR   | 2021-12-24 21:58:27,469 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85676 of function 0x85676.
ERROR   | 2021-12-24 21:58:27,470 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85687 of function 0x85687.
ERROR   | 2021-12-24 21:58:27,471 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85686 of function 0x85686.
ERROR   | 2021-12-24 21:58:27,472 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85697 of function 0x85697.
ERROR   | 2021-12-24 21:58:27,472 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x85696 of function 0x85696.
ERROR   | 2021-12-24 21:58:27,473 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x856a7 of function 0x856a7.
ERROR   | 2021-12-24 21:58:27,473 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x856a6 of function 0x856a6.
ERROR   | 2021-12-24 21:58:27,474 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x856b7 of function 0x856b7.
ERROR   | 2021-12-24 21:58:27,474 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x856b6 of function 0x856b6.
{'0x57125': [], '0x57131': ['0x571b5', '0x5714b'], '0x571e1': ['0x571f9', '0x571eb'], '0x57219': ['0x52a14'], '0x57231': ['0x85185'], '0x57239': ['0x52a20'], '0x57259': ['0x52a20'], '0x5727d': ['0x52a20'], '0x572a5': ['0x52a20'], '0x572d1': ['0x57363', '0x572ed'], '0x5754d': ['0x851c5'], '0x575b9': [], '0x578d5': [], '0x58009': ['0x5801b', '0x58013'], '0x58159': ['0x58169', '0x5815b'], '0x58171': ['0x58191', '0x58173'], '0x58199': ['0x581b5', '0x5819b'], '0x581bd': ['0x581ef', '0x581bf'], '0x581f7': [], '0x58259': ['0x5827b'], '0x58285': ['0x582a7'], '0x582b1': ['0x582db'], '0x582e5': ['0x58315', '0x582f1'], '0x5831d': ['0x58339', '0x5832d'], '0x5833d': ['0x52c18'], '0x5835d': [], '0x58369': ['0x583ed', '0x58383'],
......
````

**Comment by rhelmot** [comment]
You can see the problem in that cfgemulated has a single node at address 0: cfgemulated only knows how to start from the entry point when you don't specify where to start analysis, and shared objects have a null entry point. You need to specify where to begin analysis if you want to use cfgemulated.

**Comment by EudoraQR** [comment]
Thank you very much, the problem has been solved. Finally, there is a question, why can I use the function CFGEmulated() with this binary with the default entry position instead of specifying the entry point CFGEmulated(start=int), the reason is that the latter has a main function in this binary?
[bubble.zip](https://github.com/angr/angr/files/7776528/bubble.zip)

**Comment by rhelmot** [comment]
That binary is not a shared object, so it has a meaningful entry point set in its ELF header.
