### ISSUE TITLE
the state object of the program‘s  exit point

### ISSUE THREAD

**Issue by XX-Official** [angr/angr#3031]
The function `entry_state` can return a state object representing the program at its entry point, is there any function which is similar to this function can return the state object of the program‘s  exit point ？

**Comment by rhelmot** [comment]
There is no such concept. What problem are you trying to solve that you need a state which can never produce any successors?

**Comment by ltfish** [comment]
A program runs until it either invokes a syscall that terminates the process (such as `exit` on Linux) or hits a non-resumable event (such as undecodeable instructions).
