### ISSUE TITLE
Significant (3x) load time regression beginning in 9.0.10339

### ISSUE THREAD

**Issue by cwgreene** [angr/angr#3036]
---

**Describe the bug.**
3x load time regression in angr beginning with angr-9.0.10339

Version 9.0.10281
```
$ time python3 -m angr # version 9.0.10281
/usr/bin/python3: No module named angr.__main__; 'angr' is a package and cannot be directly executed

real	0m1.973s
user	0m1.842s
sys	0m0.131s
```
Version 9.0.10381
```
$ time python3 -m angr

/usr/bin/python3: No module named angr.__main__; 'angr' is a package and cannot be directly executed

real	0m6.119s
user	0m5.884s
sys	0m0.236s
```

**Environment Information.**
Similar performance on old macbook and ec2 instance (should be reproducible on a bare ec2 instance).

**To Reproduce.**
Compare versions 9.0.10281 and 9.0.10339 using the command

```
$ time python3 -m angr
```

**Comment by cwgreene** [comment]
So part of the issue seems to be the new win32 definitions. About a second is being spent in those new files directly, and sim_types is having a *lot* more calls. I think that accounts for most of the differences. Here are the results of running

```
$ python -m cProfile ang.py
```

where `ang.py` is
```python
import angr
```

[timings339.txt](https://github.com/angr/angr/files/7778358/timings339.txt)
[timings281.txt](https://github.com/angr/angr/files/7778357/timings281.txt)

**Comment by ltfish** [comment]
Six seconds is definitely too long. Which version of CPython are you using? This is in my Ubuntu VM with CPython 3.8.10:

```
$ time python -c "import angr"

real	0m3.212s
user	0m3.156s
sys	0m0.368s
```

This is a known issue in my todo list, but I don't have a very good solution at this moment. A simple solution, while less preferred, is delaying the loading of all SimProcedures until they are first used.

**Comment by ltfish** [comment]
By the way, can you please run `python -X importtime -c "import angr"` for me?

**Comment by ltfish** [comment]
Also, can you please check if there are .pyc files under `angr/angr/procedures/definitions/__pycache__/`?

**Comment by ltfish** [comment]
Please let me know if #3036 fixes this issue for you.

**Comment by ltfish** [comment]
> and sim_types is having a lot more calls

@rhelmot On a second thought, you probably have an idea of what's going on here...

**Comment by cwgreene** [comment]
Import times:
[import_times.txt](https://github.com/angr/angr/files/7778931/import_times.txt)
Should I still test your branch?

**Comment by cwgreene** [comment]
```
$ cd ~/.local/lib/python3.8/site-packages
$ ls angr/angr/procedures/definitions/__pycache__
ls: cannot access 'angr/angr/procedures/definitions/__pycache__': No such file or directory
```

**Comment by ltfish** [comment]
> ls: cannot access 'angr/angr/procedures/definitions/__pycache__': No such file or directory

I think this is the problem. For some reason (which is beyond my speculation), CPython is not generating .pyc files for all .py files under `angr/angr/procedures/definitions/`. As a result, every time you import angr, CPython has to re-parse and re-load all those API definition files, which significantly increases the loading time.

> Should I still test your branch?

Based on your `import_times.txt`, PR #3037 will probably cut your loading time by ~2 seconds. I do think you should figure out why `.pyc` files are not generated. With `.pyc` files, angr should load within 1.5 seconds.

**Comment by ltfish** [comment]
> (Previous version of this comment was looking at the wrong directory)

Oh nvm then.

**Comment by cwgreene** [comment]
I have confirmed that your branch fixes the issue. Also, cold start on master is about 12 seconds prior to creating the pycache files. Second run is about 6 seconds. The branch takes 2 seconds.

**Comment by cwgreene** [comment]
> EDIT: You do have .pyc files. I suppose your machine is just slower than my VM...
Running on an 2015 macbook and an underpowered t2.medium instance, both are about 6 seconds off of master. Just tested an m5.2xlarge and that's about 3.5 seconds.

**Comment by ltfish** [comment]
Thanks! I will merge the PR once tests pass.

Apparently the more expensive EC2 instance is indeed running faster ;)
