### ISSUE TITLE
Comprehensive Tutorial for Angr

### ISSUE THREAD

**Issue by brendabrandy** [angr/angr#304]
Hi I was a recent user of Angr and I feel that there is a lack in tutorial of angr in terms of using it to its full extent. The documentation describes each process well but lack a fully story on how to link stuff together. I am thinking of finding a series of CTF challenges / crackmes that we could use to walk through angr and binary analysis in general. Does anyone have ideas on what resources I can find to accomplish this?

**Comment by frapik99** [comment]
hi @brendabrandy , have you already seen this repo: [https://github.com/angr/angr-doc](url)

Thanks

**Comment by brendabrandy** [comment]
@frapik99 I did seen the aforementioned repo, but I don't think it's coherent enough. I was thinking of formulating it into a course that can string the examples in angr-doc. I also saw someone trying to make a large course from it but not a lot of people followed up with the thread after September -- hence my idea of making the tutorial more coherent and accessible for beginners.

**Comment by frapik99** [comment]
Hi @brendabrandy, as a curiosity, what do you feel is missing at the moment in the doc?

**Comment by zardus** [comment]
Making the docs more coherent (and also more complete, of course) has always been a big goal, but manpower has been an issue. However, earlier this month, we presented a tutorial at ACSAC, and developed some examples that could be useful toward this goal: https://github.com/angr/acsac-course. Those could be used to flesh out the "angr course" (https://github.com/angr/angr-doc/blob/master/docs/course.md).

**Comment by brendabrandy** [comment]
@frapik99 : I mostly want some sort of a table of contents where people can click on and look at a walkthrough (not just python comments) on how to use different portions of angr, such as symbolic execution / disassembly etc. The current docs are actually filled with examples, which was nice, but they haven't been organized in a way that a person who's new to dynamic disassembly could figure out in a short period of time. @zardus Thanks a lot for the link! I think my first goal would be to fill in the TO-DO list in the course.md

**Comment by frapik99** [comment]
@brendabrandy I think it would be useful to everyone. Are you working on it?

**Comment by brendabrandy** [comment]
@frapik99 yes i am! I am on vacation for a few days -- so i'm going to work on it afterwards.

**Comment by frapik99** [comment]
excellent @brendabrandy . Thanks

**Comment by jbgrunewald** [comment]
Was there anything concrete put together for this? I'd love to take a look and learn more.

I was recently tasked with using angr for a course project. I found the trivial use cases to be quite straight forward, but the course expected solutions to more complicated scenarios. One example was using the solver to find the many possible CNC commands for a piece of malware. We need to dynamically generate constraints and continue executing to find all possible commands in a single run.

**Comment by zardus** [comment]
The closest that I've seen is https://github.com/jakespringer/angr_ctf. It hasn't kept up with all the angr developments, but forks of it have kept up closer. It doesn't cover everything, but it's a good way to get started.
