### ISSUE TITLE
In the binary file with debugging information, by the line number in the source code, I want to find the function and block address corresponding to this line of code

### ISSUE THREAD

**Issue by EudoraQR** [angr/angr#3051]
---

hello, developer
I have a sources code file and a binary file which compiled with debugging information.
I want to use a line number in the source code to find in the binary the address of the function to which the line number belongs and the address of the block of code where the line number is located.
Is there an API that meets this need or is similar？

**Comment by rhelmot** [comment]
`project.loader.main_object.addr_to_line`

**Comment by EudoraQR** [comment]
Is there an example of using this API?I use the following code but output an empty dictionary
’‘’
proj = angr.Project('bubble', load_options={"auto_load_libs": False})
    print(proj.loader.main_object.addr_to_line)
‘’‘

**Comment by EudoraQR** [comment]
Is there an example of using this API?I use the following code but output an empty dictionary
```
proj = angr.Project('bubble', load_options={"auto_load_libs": False})
print(proj.loader.main_object.addr_to_line)
```

**Comment by ltfish** [comment]
When creating the project, you need to specify `load_debug_info=True`.

**Comment by EudoraQR** [comment]
Thanks! The problem has been solved successfully
