### ISSUE TITLE
I would like to know the meaning of some warnings that i have faced using angr

### ISSUE THREAD

**Issue by Kappablanca** [angr/angr#3052]
---

Hello I am currently working with angr to perform my final degree project, specifically i am using angr to analyze some binaries looking for the addresses where they have loops. During my work i have found sometimes this kind of warnings offered by angr:

`WARNING` | 2021-11-05 16:41:29,587 | [37mangr.analyses.cfg.cfg_base[0m | [37mUnexpected edge with ins_addr being None: <CFGENode filterbank_main+0xab 0x40059b[22]> -> <CFGENode filterbank_main+0xb3 0x4005a3[14]>, data = {'jumpkind': 'Ijk_Boring', 'stmt_idx': None, 'ins_addr': `None}.[0m`

The result that i have obtained in binaries where i faced this warning  was the analyzer finding loops in nonsense addresses so i would like to know where i could find some information about what is the meaning of this warnings and why they could happen.
Other information that I think may be relevant is that more has happened to me when trying to analyze binaries compiled with clang-llvm compiler and O2 optimization level.
Thank you so much !

**Comment by ltfish** [comment]
It's "unexpected" because I believe it shouldn't have happened but yet it does. If you can post the binary here, I can look into what is going on and fix the bug.

**Comment by Kappablanca** [comment]
This is the binary where the warning that i have posted comes from: 
[filterbank_O2_llvm.zip](https://github.com/angr/angr/files/7822849/filterbank_O2_llvm.zip)
And this is the complete log file that i have generated for the binary:
[filterbank_O2_llvm_log.txt](https://github.com/angr/angr/files/7822842/filterbank_O2_llvm_log.txt)
The log file includes every warning that i have obtained for this binary, all of them looks like being a similar problem as the previously posted one. 
Some information about the binaries im working with, that i just have realized i have not mentioned, is that all of them are compiled for x86-64 architecture.
Thank you for the help.

**Comment by Kappablanca** [comment]
I have not included the analyzer which im using to get the loops information from the binaries in previous message sorry.
It is an adaptation from a previous version that my project tutor had created to do the same kind of analysis for 32 bits arm architecture.
[mkff.py.zip](https://github.com/angr/angr/files/7823202/mkff.py.zip)

**Comment by Kappablanca** [comment]
@ltfish 
Sorry for taking your time.
My project tutors have insisted to me to ask again since probably my replay was in a wrong way or there were more important tasks to attend to at that time. The binary i was using in my first post was this https://github.com/tacle/tacle-bench/blob/master/bench/kernel/filterbank/filterbank.c compiled with clang-llvm using O2 level optimization for AMD64 architecture. Also, i have compiled this binary using gcc with O0 and O2 and clang with O0 and i haven't found this kind of warning. If the problem resulting to be an actual bug instead of me performing a wrong job i could share more binaries where i have found this kind of problems using both compilers and optimization levels.
Thank you so much.
