### ISSUE TITLE
angr ran out of my 64G RAM

### ISSUE THREAD

**Issue by bertcug** [angr/angr#306]
I'm doing some tests on [pwn-ropeman](https://github.com/nsslab-yin/pwn-ropeman/blob/master/4/ropeman), which is 46KB, and it may cause a state explosion problem, it ran out the 64 RAM of my server, so we do some measurement on where and why it could cost so much rams, which we use pytracemalloc and I got these data: 
`step 4300 used 60413440K`, it can only step 4300 steps. the meory usage are below(sorted by linenum, Top 20):

| File | linenum | size | count | average |
|--------|-------|------|-------|---------|
| claripy/frontends/constrained_frontend.py | 25 | 5175 MiB | 642314 | 8449 B |
| claripy/frontend_mixins/constraint_deduplicator_mixin.py | 12 | 4694 MiB | 53518 | 89.0 KiB |
| simuvex/storage/paged_memory.py | 129 | 4171 MiB | 218670 | 19.0 KiB |
| claripy/frontends/composite_frontend.py | 32 | 3536 MiB | 108316 | 33.0 KiB |
| angr/path_history.py | 57 | 1707 MiB | 188582 | 9494 B |
| simuvex/s_event.py | 12 | 577 MiB | 788921 | 768 B |
| simuvex/storage/paged_memory.py | 34 | 563 MiB | 2108823 | 280 B |
| simuvex/storage/paged_memory.py | 825 | 556 MiB | 2513284 | 232 B |
| simuvex/storage/paged_memory.py | 35 | 554 MiB | 2077918 | 280 B |
| simuvex/storage/paged_memory.py | 62 | 536 MiB | 65134 | 8633 B
| simuvex/storage/paged_memory.py | 189 | 385 MiB | 321979 | 1254 B |
| simuvex/storage/paged_memory.py | 181 | 385 MiB | 321962 | 1255 B |
| simuvex/s_event.py | 13 | 210 MiB | 789012 | 279 B |
| simuvex/storage/memory.py | 294 | 196 MiB | 268650 | 768 B |
| simuvex/storage/paged_memory.py | 143 | 196 MiB | 268529 | 767 B |
| simuvex/plugins/scratch.py | 66 | 157 MiB | 107459 | 1540 B |
| archinfo/arch.py | 48 | 157 MiB | 53851 | 3072 B |
| angr/path.py | 72 | 142 MiB | 61344 | 2443 B |
| simuvex/storage/file.py | 58 | 118 MiB | 161576 | 766 B |
| simuvex/s_action.py | 56 | 95.0 MiB | 1561704 | 64 B |

the data sorted by file( Top 10 ):

| File | Size | Count | Average |
|------|------|-------|---------|
| simuvex/storage/paged_memory.py | 7466 MiB | 8412246 | 930 B |
| claripy/frontends/constrained_frontend.py | 5175 MiB | 646941 | 8389 B |
| claripy/frontend_mixins/constraint_deduplicator_mixin.py | 4697 MiB | 75849 | 63.0 KiB |
| claripy/frontends/composite_frontend.py | 3630 MiB | 284664 | 13.0 KiB |
| angr/path_history.py | 1779 MiB | 1322558 | 1410 B |
| simuvex/s_event.py | 837 MiB | 1762377 | 498 B |
| angr/path.py | 226 MiB | 750573 | 316 B |
| simuvex/storage/memory.py | 204 MiB | 391427 | 547 B |
| archinfo/arch.py | 200 MiB | 161764 | 1299 B |
| simuvex/plugins/scratch.py | 174 MiB | 212966 | 858 B |

here is my code:
```python
binary = os.path.join(basedir, "test/pwn-ropeman/4/ropeman")
proj = angr.Project(binary, load_options={"auto_load_libs":False})
state = proj.factory.entry_state(add_options=simuvex.o.unicorn | {"BYPASS_UNSUPPORTED_SYSCALL"},
                                 concrete_fs=True)
pg = proj.factory.path_group(state, veritesting=True)
pg.explore(find=0x804995e)
```

**Comment by bertcug** [comment]
as I know, `claripy/frontends/constrained_frontend.py`, `constraint_deduplicator_mixin.py`, `composite_frontend.py` these three file is doing some thing about constraints. the `page_memory.py` also use a lot memory, so is this normal if my testcase caused a path explosion ? the testcase is just 46 KB, if it could use so much memory, how about others, such as core-utils .

**Comment by bertcug** [comment]
this is the memory used by steps
![memory_by_step](https://cloud.githubusercontent.com/assets/6436893/21561161/e1687aae-cea3-11e6-89f3-ef445af8801c.png)

**Comment by zardus** [comment]
Thanks for looking into this!

In general, path explosion is an endemic problem to symbolic exploration. Large binaries basically guarantee it, but small binaries can trigger it as well. There are famous examples, used by papers in the field, that are one or two dozen lines of code.

Could you check how many paths are in the path group (posting the output of `print pg` would work)? It's possible that either some deduplication is not working as expected, or our memory model duplicates considerably more data than expected. That's what the linear increase compared with the length of the path hints at for me, anyways.

**Comment by bertcug** [comment]
I've been runnning a test on the path count as you mentioned above, and here is the results:[path_explosion.txt](https://github.com/angr/angr/files/680520/path_explosion.txt)
memory used grows with  `deadended` path, how every the `avtive` is around 20. but the `deadend` is useless to me, because I want to find the paths which reach a target address. could I don't store the `deadend` paths to save memory ?

**Comment by rhelmot** [comment]
The easy way would be to pass `step_func=lambda lpg: lpg.drop('deadended')` into `pg.explore()`

**Comment by bertcug** [comment]
OK, thank you, I'll try !

**Comment by bertcug** [comment]
step_func should be `step_func=lambda lpg: lpg.drop(stash='deadended'),`

**Comment by frapik99** [comment]
@bertcug could you share your code? I'd be interested to understand how to monitor the RAM usage.

Thanks

**Comment by bertcug** [comment]
@frapik99 I use pytracemalloc, in python 2.7 which you should patch and compile python, and here is my code use pytracemalloc:
```python
#coding=utf-8
import angr, simuvex
import os, gc, sys
import tracemalloc


def get_memory():
    pid = os.getpid()
    cmd = "ps -e -o 'pid,rsz' | grep %d | awk '{print $2}'" % pid
    mem = int(os.popen(cmd).read())
    return mem

tracemalloc.start()

basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
binary = os.path.join(basedir, "test/pwn-ropeman/4/ropeman")
print basedir, binary
proj = angr.Project(binary, load_options={"auto_load_libs": False})
addr = 0x804995e  # 194 ropeman.c
state = proj.factory.entry_state(concrete_fs=True)
pg = proj.factory.path_group(state, veritesting=True)

i = 0
while len(pg.active) > 0:
    pg.step(100)
    i += 100

    mem = get_memory()
    print "\n=================== step %d used %dK ==============================\n" % (i, mem)

    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.statistics('filename')

    print("[ Top 20 ]")
    for stat in top_stats[:20]:
        print stat

    snapshot.dump("mem/%d.step" % i)
```
I also do this test by using `gc` module:
```python
#coding=utf-8
import angr, simuvex
import os, gc, sys

def get_memory():
    pid = os.getpid()
    cmd = "ps -e -o 'pid,vsz' | grep %d | awk '{print $2}'" % pid
    mem = int( os.popen(cmd).read() )
    return mem

basedir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
binary = os.path.join(basedir, "test/pwn-ropeman/4/ropeman")
print basedir, binary
proj = angr.Project(binary, load_options={"auto_load_libs":False})
addr = 0x804995e   #194 ropeman.c
state = proj.factory.entry_state(add_options=simuvex.o.unicorn | {"BYPASS_UNSUPPORTED_SYSCALL"},
                                 concrete_fs=True)
pg = proj.factory.path_group(state, veritesting=True)

mem_target = 1024*1024   # records start from 1G 
limit_mem = 20*1024*1024 # ended at 20G

i = 0
while len(pg.active) > 0:
    pg.step()
    i += 1

    mem = get_memory()
    print "step %d used %dK" % (i, mem)
    if mem > limit_mem:
        sys.exit(0)

    if mem > mem_target:
        objs = gc.get_objects()
        objs.sort(key=sys.getsizeof)
        out_f = open("mem/%d_objs.txt" % i, "w")
        out_f.write("step %d used %dK\n\n" % (i, mem))

        for obj in objs[-20:]:
            try:
                out_f.write("%d, %s\n" % (sys.getsizeof(obj), obj.cell_contents.__str__()) )
            except:
                out_f.write("%d, %s\n" % (sys.getsizeof(obj), obj.__str__()))
        out_f.flush()
        out_f.close()

        mem_target += 500 * 1024  #每次递增500M
```
