### ISSUE TITLE
Hooks only work at the beginning of a basic block

### ISSUE THREAD

**Issue by ocean1** [angr/angr#309]
Hooks are only executed if placed at the beginning of a basic block (i.e. you cannot hook a call instruction with arg "lenght=5" to skip the instruction)

**Comment by ltfish** [comment]
I confirmed it. @rhelmot could you please confirm it? I'll fix it after your confirmation.

**Comment by zardus** [comment]
This is how it is. Everything in angr happens on a basic block basis, and when it doesn't (i.e., the `find` and `avoid` addresses in the exploration technique), it's cause it was specifically worked around.

To work around it in this case, we'd have to do a set intersection between the basic blocks and the hook addresses every time we lift a block. Probably a reasonable cost to avoid the confusion, though.

**Comment by ltfish** [comment]
> To work around it in this case, we'd have to do a set intersection between the basic blocks and the hook addresses every time we lift a block. Probably a reasonable cost to avoid the confusion, though.

Or alternatively, set the `max_size` to the `next_hook_addr - block_addr`. We'll have to make `Project._sim_procedures` an AVL tree to avoid the cost.

**Comment by rhelmot** [comment]
no.... I added code at one point to do this already. It must have broken at some point.

**Comment by rhelmot** [comment]
Actually, the code is working correctly and there's even a testcase that depends on it working correctly. (test_hooks)

One thing that could be happening is that the full-length basic block could be cached, and then you're adding the hook, and then the cached block is being used, running over the mid-block hook. Can you disable the basic block cache and check that the problem goes away? If so, we can add the list of hook addresses to the cache key...
