### ISSUE TITLE
Export angr docs to PDF

### ISSUE THREAD

**Issue by srobertjames** [angr/angr#3103]
**Desired:** Be able to read through docs.angr.io offline as a PDF

**Current:** docs.angr.io can only be read online in a browser

**Solution:** PDF Export of docs.angr.io.  Ideally this could be automated as part of the release process.

docs.angr.io is a great resource to learn angr.  Given the amount to learn, it's difficult to just look up the docs on the fly; a new angr user may need to make time to actually _read through the docs in order_.

Can you please enable export of docs.angr.io to PDF? I believe Gitbook allows this, but only if you (ie the repo owner) enable it.  Otherwise, perhaps this could be done offline, using pandoc or another too.

**Comment by rhelmot** [comment]
I enabled export as pdf. You may now download to your heart's content!

**Comment by srobertjames** [comment]
Thank you.  I'm not seeing the option to Export as PDF on the site, however.  Perhaps only admins are enabled to do it?

Can you confirm that non-admins are enabled to export (pls post the url to do so), or, simply check in the PDF to github (which others might find helpful as well) or even this ticket?

**Comment by rhelmot** [comment]
I just checked, and the "export to pdf" link is visible on the top of the left-hand sidebar in an incognito window. Perhaps clear your caches?

**Comment by srobertjames** [comment]
Bizarre: I'm looking at docs.angr.io and not seeing it.  I tried Chrome Incognito and also Firefox (which had never gone to the site before).  Screenshots below.  Am I looking in the wrong pace?

![image](https://user-images.githubusercontent.com/662612/151056989-4bd8f9bf-e59b-4ede-a836-1c047cb6e3c6.png)

![image](https://user-images.githubusercontent.com/662612/151057092-c3f63295-2dc9-4079-b00a-79a7051fc9e9.png)

**Comment by rhelmot** [comment]
I'm sorry, I meant the right hand sidebar.

![image](https://user-images.githubusercontent.com/2498805/151057312-00ec7932-55bc-4141-9921-a5c6f4922db0.png)

**Comment by srobertjames** [comment]
Bizarre: I do not see _any_ of those, except for Search.

![image](https://user-images.githubusercontent.com/662612/151063249-ea7b5fb4-66e6-4230-9844-be2fc1164f00.png)

**Comment by rhelmot** [comment]
I believe your screen resolution is too low. Try zooming out.

**Comment by srobertjames** [comment]
Fantastic! That solved it.  Note that in my default res, even Ctrl-F didn't find the "Export" link - it's not scrolled but rather completely unrendered.  Thank you for your help.
