### ISSUE TITLE
How to generate acyclic callgraph efficiently?

### ISSUE THREAD

**Issue by Icegrave0391** [angr/angr#3105]
---

Hey, I'd like to know if there is any way to efficiently generate an acyclic function callgraph (unroll all the loop calls and recursive calls)?

I tried to use the following code, to remove all the loops in the original call graph by repeated calling to `nx.find_cycle()` in a brute-force way:
```
new_cg = project.kb.callgraph.copy()
try:
    while True:
        prune_edge = list(nx.find_cycle(new_cg, orientation="original"))[-1]
        new_cg.remove_edge(prune_edge[0], prune_edge[1])
except:
    continue
```
However, it won't work when analyzing large binaries, such as `vim`.

**Comment by rhelmot** [comment]
You probably want to do a depth-first search, keeping track of anything you've seen before, and then remove any edges which go to things you've seen before.
