### ISSUE TITLE
crash in class angr.calling_conventions.MicrosoftAMD64ArgSession

### ISSUE THREAD

**Issue by Thomyrock** [angr/angr#3108]
Hi, I've been encountering a crash in class `angr.calling_conventions.MicrosoftAMD64ArgSession`. It seems that in  commit 3090a97c73a74187f3bfdb85aa61856d064569f5, in file `angr.calling_conventions.py`, `SimCC`'s property `both_args` was replaced by `memory_args` almost everywhere, except for `MicrosoftAMD64ArgSession`, which causes an AttributeError.
Is it a bug or am I wrong somewhere ?
Thanks

**Comment by rhelmot** [comment]
Nope, you're spot on. I've pushed what I'm pretty sure is a fix.
