### ISSUE TITLE
Unsupported operation: Iop_ZeroHI96ofV128

### ISSUE THREAD

**Issue by veasgdfsf** [angr/angr#3109]
---

I am running symbolic execution on the Arm SIMD instruction "fmaxnm" and find that 'Iop_ZeroHI96ofV128' is not implemented. Could you give me some hints on how I am implement it myself? A pointer to how to implement it is also appreciated. Thanks!

**Comment by rhelmot** [comment]
All ops are implemented in https://github.com/angr/angr/blob/master/angr/engines/vex/claripy/irop.py - this doesn't look like an op whose implementation can be genericized, so you probably want to implement it similar to, for example, _op_Iop_MAddF64.

**Comment by veasgdfsf** [comment]
Thanks for your timely response! I will look at it!
