### ISSUE TITLE
angr handles unconstrained stdin differently than omitted stdin

### ISSUE THREAD

**Issue by srobertjames** [angr/angr#3129]
---

**Describe the bug.**

angr script works correctly if `stdin` omitted from `entry_state()`, but fails if any form of stdin passed (e.g. `stdin=angr.SimFileStream(name='stdin', has_end=False)`.

Task: https://github.com/jakespringer/angr_ctf/blob/master/dist/scaffold15.py
Binary: https://github.com/jakespringer/angr_ctf/blob/master/dist/15_angr_arbitrary_read

```
if True: # Change this to False and the script succeeds
    entry_state = proj.factory.entry_state(stdin=angr.SimFileStream(name='stdin', has_end=False)) # FAILS
else:
    entry_state = proj.factory.entry_state() # SUCCEEDS
```

**Environment Information.**

**To Reproduce.**

See above.  My script works fine if I don't set _anything_ for stdin.  But if I set something: be it `stdin=flag` (where flag is a BVS), `stdin=angr.SimFileStream(name='stdin', content=flag, has_end=False)`, or even `stdin=angr.SimFileStream(name='stdin', has_end=False)`, it fails.

This is all even if `flag` has no constraints on it.

1. Why does setting an unconstrained stdin cause it to fail?
2. If we don't specify `stdin` in `entry_state()`, are there other ways to constrain it? `posix.dumps` always goes concrete.  I tried reading stdin as a file, but it doesn't allow seeking back.

**Comment by srobertjames** [comment]
Re #2 above, https://github.com/jakespringer/angr_ctf/blob/master/dist/scaffold17.py#L94 shows a technique which no longer seems to work:

```
for byte in solution_state.posix.files[sys.stdin.fileno()].all_bytes().chop(bits=8):
      solution_state.add_constraints(byte >= ???, byte <= ???)
```

but this gives

```
    for byte in sol.posix.files[sys.stdin.fileno()].all_bytes().chop(bits=8):
AttributeError: 'SimSystemPosix' object has no attribute 'files'
```

**Comment by rhelmot** [comment]
By default, stdin is a [SimPackets](http://angr.io/api-doc/angr.html#angr.storage.file.SimPackets). This helps with modeling things like scanf, since there can be arbitrary-sized input elements that change size depending on solving results. We just can't model that without blowing up the state with the standard address-space approach to modeling stdin.

For 2), we don't maintain angr_ctf. It's just jake springer's project, and he seems to have abandoned it.

**Comment by srobertjames** [comment]
Thanks! My target binary indeed has a scanf("%u %s").  I think it would clarify if I told you what I'm trying to accomplish:

* The user inputs a password to the binary, consisting of a digits followed by arbitrary chars
* The script successfully solves them! It prints them via `posix.dumps(0)`.
* But I'd like to constrain the chars to be printable.  Right now, the script solves them with upper ascii, which can't be typed.
* I'm struggling to determine **how I can constrain stdin** to be printable (or, at least, how to constrain stdin when it will be processed by scanf)

The following attempts to constrain stdin do not work:

1. Constraining `posix.dumps` doesn't work (obviously), because its concrete
2. Google shows me some older scripts constraining `sol.posix.files[0].all_bytes()`, but that method no longer seems supported
3. Specifying `stdin=flag` doesn't work; angr says `angr.simos.simos | stdin is constrained to ... bytes (has_end=True). If you are only providing the first ... bytes instead of the entire stdin, please use stdin=SimFileStream(name='stdin', content=your_first_n_bytes, has_end=False)`.  I believe that warning is out of date and should now instruct to use `SimPackets`.
4. Using SimFileStream fails, even without any constraints or stdin val.  I presume this is because the advanced scanf needs SimPackets.
5. Using SimPackets causes the script to run and work if but only if I do not attempt to associate content with a BV:

```
entry_state = proj.factory.entry_state(stdin=angr.SimPackets(name='stdin')) # Works! But stdin is not constrained
entry_state = proj.factory.entry_state(stdin=angr.SimPackets(name='stdin', content=[(flag, flag_len)])) # Fails, no solution found, even if no constraints whatsoever on flag
```

6. If I do something similar to the last line, but set `flag_len = 10`, which is the number of characters in the `%u` of the scanf, the script works properly, but of course only constrains the `%u`, and not the chars afterwards.

My question boils down to:  **How can I symbolically constrain stdin?** For example, to be only printable.  In my case, **I can do this for the first chars that are scanf'd, but not the remaining ones.**

Perhaps if the binary uses scanf, I need to structure the stdin SimPackets to match the lengths that will be read? I'm not sure how to do this.

**Comment by srobertjames** [comment]
Additional experimentation shows the following works:
```
PRINTABLE_ONLY = True
if PRINTABLE_ONLY:
    flag_len = 10
    flag = claripy.BVS('flag', flag_len*8)
    pw2_len = 20
    pw2 = claripy.BVS('pw2', pw2_len*8)
    space = claripy.BVV(b' ')
    entry_state = proj.factory.entry_state(stdin=angr.SimPackets(name='stdin', content=[(flag, flag_len), (space, 1), (pw2, pw2_len)]))
    for c in pw2.chop(8):
        entry_state.solver.add(c >= 0x20, c <= 0x7f)
else:
    entry_state = proj.factory.entry_state()
```

Can I conclude the following:

1. The only way to constrain stdin is to specify it as a SimPackets
2. If you do specify stdin as SimPackets, and you use scanf, you must split stdin into a list of `(BV, number_of_bytes_scanf_consumes_in_each_individual_gulp)`

Is that correct? If no: What is the better way to constrain stdin? If yes: Can you elaborate on why scanf requires SimPackets broken up like that? What if we don't know the details of scanf's reads in advance?

**Comment by rhelmot** [comment]
Your investigation and conclusions are entirely correct. SimPackets was not designed with preconstraining in mind - in fact, several optimizations were written into scanf et al. which assume that the input that comes out of scanf _cannot_ be preconstrained. I don't _think_ these should cause problems if you hack around them though...?

My suggestion for this is for you to write a custom scanf simprocedure which instruments the values parsed out of the input (this is a bit of a misnomer, as the optimizations I referred to before are that scanf works by constraining the input to be the serialization of the output instead of the other way around) to be constrained to the values you want to input. If you need even more control, you can try writing your own SimFile class that precisely controls what data it yields.

**Comment by srobertjames** [comment]
Thanks! This issue is now satisfactorily closed.
