### ISSUE TITLE
Errored state getting pruned

### ISSUE THREAD

**Issue by Thomyrock** [angr/angr#3132]
Hi,
I went through something a bit tricky, so I wanted to check if this is a mistake or the intended behaviour.
I had a program running in a simulation manager, and a breakpoint was fired. Inside the breakpoint function, I was using the `solver.eval()` method without checking the expression's satisfiability (shame on me), so an unsat error was raised. The error got silently caught inside `SimulationManager.step_state()` which pruned the state.
Shouldn't this state go to the "errored" stash instead?

**Comment by ltfish** [comment]
Any states raising exceptions inside breakpoint functions that are invoked by `step_state()` should generally go to the `errored` stash. What you described might be a result of another exception handler in the call stack catching the unsat error raised in your breakpoint function.

I can only guess what might be going on. If you post a script and your binary that reproduce this issue, I can take a look at what went wrong.

**Comment by Thomyrock** [comment]
Here is how to trigger the bug :

``` python
import angr
import claripy


def sim_proc_bp(state):
    bvs = claripy.BVS("test", 32)
    state.solver.eval(bvs, extra_constraints=[1 == 0])  # unsat error


def trigger_bug():

    proj = angr.Project("hello_world")

    entry = proj.factory.entry_state()
    # any bp would do
    entry.inspect.b("simprocedure", angr.BP_BEFORE, action=sim_proc_bp)

    sim = proj.factory.simulation_manager(entry)
    sim.run()

    print("errored :", len(sim.errored))
    print("pruned :", len(sim.pruned))


if __name__ == "__main__":
    trigger_bug()
```

For the binary, any would do (here, I used a simple "Hello World").

**Comment by rhelmot** [comment]
I believe the culprit is [this stanza in sim_manager.py](https://github.com/angr/angr/blob/b4f439781d250bb020b108c2c4a434b74ba264c4/angr/sim_manager.py#L407). It seems to have the exact behavior which you're describing, which suggests that someone in the past thought this was desirable. I do agree that this is at the very least unintuivive. I'm going to try removing this and seeing if any tests fail.
