### ISSUE TITLE
How to use StringS and StrLen

### ISSUE THREAD

**Issue by srobertjames** [angr/angr#3144]
angr now has [StringS](https://github.com/angr/claripy/blob/master/claripy/ast/strings.py) and StringV support.

I'd like to do something like:
```
# s is angr.SimState
pw = claripy.StringS('pw', 0x20) # pw is a C string between 0 and 19 chars
s.memory.store(s.regs.rsi, pw) # store pw to buf pointed at by rsi
s.regs.rax = s0.StrLen(s0, 64) # set rax to strlen(buf)
```

However, I get error `<State errored with "unknown decl op Z3_OP_INT2BV">`

What is the proper way to use StringS and StrLen? I cannot find them documented anywhere; even the `strings.py` file doesn't show how to use StrLen.

**Comment by rhelmot** [comment]
The honest answer is I don't know. The string support was added by a bunch of students using angr for java bytecode analysis, and there was never any explanation for how to use it for normal symbolic execution that I'm aware of.

**Comment by srobertjames** [comment]
Ahh.  What, then, would be the equivalent using *known* angr methods? How can I say: make a symbolic string up to N chars, and put the true len L (L <= N) into this BV?

**Comment by rhelmot** [comment]
Unfortunately, the only good way to do this is to construct for each offset into the string an expression indicating whether the string terminates at that offset, and then construct a tree of these expressions that looks something like: if terminated(0) then 0 else if terminated(1) then 1 else ...

**Comment by srobertjames** [comment]
Wow, that tree could get quite complex for a decent size string; I'm surprised it would be tractable.

What if we made a BVS n that would be strlen, and added two constraints:

1. pw[n*8:n*8+8] = 0
2. for each i in range(0,32): i >= n or pw[i*8:i*8+8] != 0

Constraint 2 could be omitted; for many cases, this would still run fine.

What do you say to that?

**Comment by srobertjames** [comment]
How does the angr SimProcedure strlen handle this? Could we simply use that?

Something like:
```
pw = claripy.BVS('pw',32*8)
pw_len = angr.SIM_PROCEDURES['strlen'].run(pw)
```

**Comment by rhelmot** [comment]
I'm pretty sure that'll just do the tree building exercise.

I _think_ your proposed solution would work? Try it out!
