### ISSUE TITLE
Resilience with Named Errors is broken.

### ISSUE THREAD

**Issue by fmagin** [angr/angr#3145]
**Describe the bug.**

`with self._resilience(name="Named Error"):` crashes when an exception is thrown

**Environment Information.**
Happens on current `master` and on current stable PyPI.

**To Reproduce.**
```python
from angr import Analysis, register_analysis, Project


class FailingAnalysis(Analysis):
    def __init__(self):
        with self._resilience(name="Named Error"):
            raise Exception


register_analysis(FailingAnalysis, "FailingAnalysis")


if __name__ == "__main__":
    proj = Project("/bin/ls", load_options={"auto_load_libs": True})
    a = proj.analyses.FailingAnalysis()


```

**Additional context.**
In `angr.analyses.analysis.Analys` `named_errors`  is set to  `defaultdict(list)` and `angr.analyses.analysis.Analysis._resilience` seems to treat it as such by simply using `self.named_errors[name].append(error)` without checking if the key is present. But in `angr.analyses.analysis.AnalysisFactory` it is set to `oself.named_errors = {}` i.e. a regular dict, and it then crashes when actually using resilience with a name because the key isn't in the dictionary.

**Comment by rhelmot** [comment]
From slack: it seems that this has been broken for the last 7 years. Do we want to just get rid of this functionality?

**Comment by fmagin** [comment]
As far as I understand it @rhelmot introduced the change that made `named_errors` a dict of lists instead of just one error per name with a322e229
But that should have never actually worked because `named_errors` was set to a dict again during analysis creation https://github.com/angr/angr/blame/a322e229cf713f6f246e6d24f527afc4011d430f/angr/analysis.py#L76

this line has survived until today, and the fix would have been trivial change to make initialize it to a `defaultdict(list)` or even just to remove the line. So my best guess is that no one that ran into this cared enough to even report it

**Comment by rhelmot** [comment]
I went and applied the simple fix. I think at some point we may want to look into moving away from the super-jank analyses setup where classes are manually initialized, and maybe when that happens it will be more obvious what the utility of having an analysis class in the first place is.

**Comment by fmagin** [comment]
+1 for moving away from the current analysis hub jankyness.
Is there any issue tracking that discussion? Want to make sure that whatever it ends up being plays well with type checking.
