### ISSUE TITLE
An error occurred while analysis the CFG of the mips program.

### ISSUE THREAD

**Issue by liupuz** [angr/angr#3154]
An error occurs when I use angr to analyze the CFG of the mips program (net-cgi). 
The error message is shown below.

>  File "/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py", line 106, in _resolve
    gp_used = self._is_gp_used_on_slice(project, b)
  File "/home/user/PycharmProjects/pythonProject/venv/lib/python3.8/site-packages/angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py", line 183, in _is_gp_used_on_slice
    stmt = block.vex.statements[block_stmt_idx]
IndexError: list index out of range

The code is shown below.
```
import angr
proj = angr.Project(net-cgi, auto_load_libs=False)
cfg = proj.analyses.CFG()
```

The net-cgi can be found in [net-cgi.zip](https://github.com/angr/angr/files/8160732/net-cgi.zip)

**Comment by liupuz** [comment]
I noticed that the block address where the error occurred is a struct
![403064](https://user-images.githubusercontent.com/43575651/156150729-4a52f3fe-c01d-4339-8875-2dd1de558aa6.png)

**Comment by ltfish** [comment]
Thanks for reporting!

@capysix I believe this is the same bug as you were experiencing :)
