### ISSUE TITLE
Dynamic bitvector creation skips viable paths

### ISSUE THREAD

**Issue by bagelbyte** [angr/angr#3157]
Hello there :candy: 

**Describe the bug.**

angr is (presumably) coming to an unsat condition based on how symbolic values are being generated and mapped to memory addresses

**Environment Information.**
Running `angr==9.0.10409` on an ubuntu 20.04 x86_64 machine

**To Reproduce.**
take the following c code

*test.c*
```C 
#include <stdio.h>

void main(int argc, char* argv[]){
    if(argv[1][1] == 'c'){
        printf("you did it\n");

        if(argv[2][0] == 'c'){
            if(argv[2][1] == 'a'){
                printf("but now you reeeeally did it\n");
            }
        }
    }
    else{
        printf("whatever\n");
    }
}
```

compile this with `gcc -no-pie test.c`

and then in angr

```python 

import angr
p = angr.project("a.out")
s = p.factory.simgr(p.factory.entry_state())
s.explore(find=lambda s: b"reeeeally" in s.posix.dumps(1))
```

which gives the output

```
In [12]: s.explore(find=lambda s: b"reeeeally" in s.posix.dumps(1))
WARNING | 2022-03-04 16:02:41,873 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x1 with 1 unconstrained bytes referenced from 0x401158 (main+0x22 in a.out (0x401158))
WARNING | 2022-03-04 16:02:42,402 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x0 with 1 unconstrained bytes referenced from 0x401176 (main+0x40 in a.out (0x401176))
Out[12]: <SimulationManager with 3 deadended>
```

however, this clearly is a possible path

```
➜  /tmp ./a.out ac ca
you did it
but now you reeeeally did it
```

**What I assume the problem is**

from the `explore` output above, we see 

```WARNING | 2022-03-04 16:02:41,873 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x1 with 1 unconstrained bytes referenced from 0x401158 (main+0x22 in a.out (0x401158))
WARNING | 2022-03-04 16:02:42,402 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x0 with 1 unconstrained bytes referenced from 0x401176 (main+0x40 in a.out (0x401176))```
```
with angr interpreting `argv[1][1] == 'c'` as a condition onto memory address `0x1`, and subsequently `argv[2][0] == 'c'` as a condition onto memory address `0x0`. However when we reach the `argv[2][1] == 'a'` statement, I assume its trying to again map `argv[2][1]` to address `0x1`, which would be unsat, so angr skips the path

**Comment by rhelmot** [comment]
If you want to explore programs with symbolic argv, you need to specify the argv in the state constructor: `entry_state(args=['./a.out', claripy.BVS("argv_1", SIZE*8), ...])`. Right now angr is emulating the program exhibiting undefined behavior, since it is not checking argc and thus overreading the argv array.

**Comment by bagelbyte** [comment]
ah makes sense. thanks for the quick response!
