### ISSUE TITLE
Development install issue

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#316]
Hi!

I've been attempting to install a development version of angr following https://docs.angr.io/INSTALL.html , but when I execute ./setup.sh , I get an error ./setup.sh: line 46: [: missing ']'

Looking at that line of the script, it looks to have a matching bracket?
line 46: if [ "$TRAVIS" == "true"]; then

Additionally, I didn't catch this error at first and tried to install the dependencies it listed. a sudo pip install libxslt1-dev and sudo pip install libxml2-dev both failed with "Could not find a version that satisfies the requirement of [package] (from versions: ) No matching distribution found for [package]" Would this be a symptom of the setup script error or am I not installing these correctly?

Thanks for the help!

**Comment by zardus** [comment]
`libxslt1-dev` and `libxml2-dev` should be installed via `apt-get`, not `pip` :-)

As for the setup.sh error, it looks like we screwed something about about three weeks ago. I'm tracking it down!

**Comment by Dinatrix** [comment]
Ah yes that would do it for the dependencies.

Thanks for looking into it!

**Comment by schieb** [comment]
Fixed with https://github.com/angr/angr-dev/commit/8f9d4ec5899519d8511dd2d324e0f11945f38414

**Comment by zardus** [comment]
Exactly :-)

Please reopen if the problem persists!
