### ISSUE TITLE
angr development install setup.sh fail part 2

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#318]
Haha me again...

After installing the dependencies I used the updated setup.sh script but received an error ("[!!] Something failed to install. Check /tmp/pip-20858 for details, or read it here: ") after "NOTE: removing angr-management...". There are several warnings throughout the log but the errors toward the end appear when trying to make the specific components? (unicorn, etc)

I've attached the pip-20858 as I'm not entirely sure where to go from here.
[pip-20858.txt](https://github.com/angr/angr/files/705024/pip-20858.txt)

**Comment by zardus** [comment]
Could you try the setup again? There have been a lot of changes over the last week, and now the docker container on docker hub (https://hub.docker.com/r/angr/angr/) works again, so your setup might work as well.

**Comment by Dinatrix** [comment]
The updated setup script worked! Thanks again

**Comment by zardus** [comment]
Good to hear!
