### ISSUE TITLE
Different behavior on two binaries that are compiled from the same source code

### ISSUE THREAD

**Issue by Hanseltu** [angr/angr#3205]
---

Hi, may I report some possible issues in angr here? Thanks!

**Describe the bug.**

I think there may be two possible issues in angr's execution.
* 1. `angr` explores the same path in deadended states, however, based on the discussion [here](https://app.slack.com/client/T03LGALRN/C3PSH3G13), it may should not be frequently happened. (I found many other cases that have the same issue but I only manually reduce one to report)
* 2. `angr` misses execution path in the binary compiled with `clang` while it can be found in the binary compiled with `gcc`, which is related to my previous report and discussion (https://github.com/angr/angr/issues/3172#issuecomment-1072054744)

**Environment Information.**

I run in an ubuntu 18.04 system and used the trunk version of `gcc` and `clang`, with the `angr-dev` version. The binaries are both compiled with `-O3`.

**To Reproduce.**

```
(angr) $ python3 angr-test.py b-gcc-trunk-O3 
<SimulationManager with 5 deadended>
No. 0  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 73 77 
input:  b''
org b:  b'\xb9\xe600ui\xb79' b'70' b'0\xe7'
hex b:  00ui9 70 0
No. 1  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77 
input:  b''
org b:  b'd2466E9F' b'1c' b'51'
hex b:  d2466E9F 1c 51
No. 2  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77 
input:  b''
org b:  b'\xb9\xe600ui\xb79' b'70' b'B'
hex b:  00ui9 70 B
No. 3  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 73 77 
input:  b''
org b:  b'79o\x1e&a\x15~' b'>x' b'0\xc1'
hex b:  79o&a~ >x 0
No. 4  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77 
input:  b''
org b:  b'ee00bF0f' b'r0' b'67'
hex b:  ee00bF0f r0 67
(angr) $ python3 angr-test.py b-clang-trunk-O3 
<SimulationManager with 1 deadended>
No. 0  solution:
output:  0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 73 77 
input:  b''
org b:  b'00aaaAz\xe2' b'\x00\xc3' b'\xe1@'
hex b:  00aaaAz  @
```
From the above information, there are indeed some duplicate paths in `angr`'s exploration in `b-gcc-trunk-O3`. Is it a normal behavior in `angr`? (PS: Again, the number indicates a block id in source code, same as the issue reported in https://github.com/angr/angr/issues/3172)

Furthermore, the path `0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77` is missed when exploring the binary compiled by `clang`. However, such a path can happen in `b-clang-trunk O3`'s native execution. Taking  a solution in `b-gcc-trunk-O3` for example:
```
(angr) $ ./b-gcc-trunk-O3 D2466E9F +C -4
0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77
(angr) $ ./b-clang-trunk-O3 D2466E9F +C -4
0 3 10 12 15 18 15 18 47 47 47 47 47 47 47 47 47 47 47 56 56 56 56 56 64 71 77 
```
We can confirm that this path can be executed in `b-clang-trunk-O3` natively. Should `angr` catch the same paths in both binaries as they come from the same source code? If not, why does `angr` miss some of the paths in one of the binaries?

**Additional context.**

Here are the reproduced files, including the binaries, source code, and python script to run `angr`.
[reproduced-files.zip](https://github.com/angr/angr/files/8322347/reproduced-files.zip)

Thank you so much for your time and I hope the possible "issues" I reported are not useless noise to you.

Best regards,
Haoxin

**Comment by rhelmot** [comment]
I can't look at this right away, but here are some debugging tips for you to be able to tackle this on your own:

- I would not rely on stdout as a reliable indicator of what a "path" means - instead, I would look at `state.history.bbl_addrs`. This is the binary-level representation of what path was taken during a state's history, specifically, which basic blocks are executed. If you have two states with the same path by _that_ metric, then I would like to hear about it. As it stands, my guess is that there are multiple paths through the binary which produce the same output.
- My guess for the outputs missed by angr on the clang binary is the same as the second example from the previous issue - I believe that clang is collapsing multiple control flow paths into a single path via smart arithmetic and conditional moves. Look at the control flow graphs for clang's output (left) vs gcc's output (right):

![image](https://user-images.githubusercontent.com/2498805/159540947-a26e5d52-1b18-4587-b43f-8900f806b2d2.png)

angr will definitely find more paths through gcc's binary!

**Comment by rhelmot** [comment]
I thought about this a bit more. I think a good way for you to get a concrete correspondence between source and binary paths is to replace your printfs with calls to unique noinline functions. i.e. instead of `printf("44 ")` you could do `marker_44()` and then earlier `void __attribute__((noinline)) marker_44(void) { printf("44 "); }`

**Comment by Hanseltu** [comment]
Hi @rhelmot. Thank you so much for your insightful comments and helpful thoughts, which really make sense to me!

Binary is kind of magic but interesting to me, let me keep exploring :-) (I just close this for now as it may not be necessary to be opened ~)
