### ISSUE TITLE
Semantics of preconstrainer interface is confusing or wrong

### ISSUE THREAD

**Issue by edmcman** [angr/angr#3212]
**Describe the bug.**
Consider:
```
preconstrainer.preconstrain(value, exp1)
preconstrainer.remove_preconstraints()
preconstrainer.preconstrain(value, exp2)
```

After this sequence of calls, I expect `exp2 == value`, but **not** `exp1 == value`.  Right now, angr constrains both.  If this is intentional, how do I obtain my desired behavior?  If not, that is the bug.

**Describe the solution you would like.**

My personal preference would be to adjust the preconstrainer to match my expected behavior.  Also I would like 10 BTC and a unicorn.

**Please include a sample of what *should* work if this feature is implemented.**

See above.

**Describe alternatives you have considered.**

I am going to manually clear `preconstrainer.preconstraints` and `preconstrainer.variable_map` but I shouldn't have to do that as the user.

**Comment by rhelmot** [comment]
The intended behavior of remove_preconstraints is not to discard all preconstriaints, but rather, to pull the preconstraints out of the solver to free up the state space, perhaps temporarily. One example of how this is useful is the `reconstraint` method, which re-adds subsets of the preconstraints based on which independent variable sets are difficult to solve.

I can add a warning when you preconstraint the same thing twice, but you'd be better off migrating your constraints to a different solver if you want to add different preconstraints.

**Comment by rhelmot** [comment]
in addition to adding a warning in the linked commit, I also changed the behavior so it won't re-add every single preconstraint when you add one of them. this should fix your use case, though I still think you might be misusing the preconstrainer. who knows! this shit is old as hell and none of us use it anymore!

**Comment by ltfish** [comment]
@rhelmot doesn’t Rex still use it?

**Comment by edmcman** [comment]
> I also changed the behavior so it won't re-add every single preconstraint when you add one of them. this should fix your use case

Thanks!  This makes a lot more sense in my opinion.

> though I still think you might be misusing the preconstrainer

> I can add a warning when you preconstraint the same thing twice, but you'd be better off migrating your constraints to a different solver if you want to add different preconstraints.

I think I understand the confusion.  I am preconstraining two different variables.  The arguments to preconstrain are value, var rather than var, value.  (Seems weird to me too.)

I probably should have `s/exp/var/g` in my original issue which didn't help.
