### ISSUE TITLE
possible bug in LoopFinder analysis

### ISSUE THREAD

**Issue by ocean1** [angr/angr#322]
possible bug in the loopfinder analysis in the following CGC sample:
[CROMU_00015.zip](https://github.com/angr/angr/files/705586/CROMU_00015.zip)

```python
p = angr.Project('CROMU_00015')
cfgfast = p.analyses.CFGFast()
loops = p.analyses.LoopFinder(functions=[f for f in p.kb.functions.itervalues() if f.name == 'cityMenu'])
```
which results in the following warning being emitted:
> angr.analyses.loops | Bad loop: more than one entry point (<BlockNode at 0x8048750 (size 5)>, <BlockNode at 0x80480db (size 19)>)

**Comment by ltfish** [comment]
This was due to the jump-table parsing being broken. I'm testing a fix right now. Thanks for reporting.

**Comment by ocean1** [comment]
thanks!
