### ISSUE TITLE
Preconstraints and solver optimizations

### ISSUE THREAD

**Issue by edmcman** [angr/angr#3250]
I am using preconstraints combined with Tracer.  Say I have an input variable `foo`, which is preconstrained to "hello\x00".

If I call the `strlen` SimProcedure, I get a bunch of constraints saying that `foo[0] != 0` and `foo[1] != 0` and so on.

At some point, if I call `min`, it invokes claripy's simplification process.  Since `foo[0] = 'h'`, the constraint `foo[0] != 0` is trivially true, and claripy removes it.

This is great until I remove the preconstraints, and `foo[0] != 0` is no longer trivially true.

Is there an easy way to tell angr/claripy to avoid removing "redundant" constraints?  Ideally, it would only do this in the solver that has preconstrained variables.

**Comment by rhelmot** [comment]
I like your solution a lot. As you can see in the linked issue, this has come up in the past, but I didn't realize there was such an easy solution. Thanks!
