### ISSUE TITLE
How to get contents of a file when the file is argv?

### ISSUE THREAD

**Issue by JodieAllen** [angr/angr#327]
Hi,
I try to find a path in a test program and get the input of this path. In the test program , I use function `open` to open a file and the file is `argv[1]`,like this ```fd = open(argv[1], O_RDONLY) ```. When I get a path,I can not solve the file to get input. I try to call ```path.state.posix.dumps(3)``` ,but get Nothing. Then , I try the  follow commands
```
    arg1=claripy.BVS("arg1",64)
    start_path=proj.factory.path(args=[proj.filename,arg1])
```
And use `path.state.se.any_str(arg1)` to solve the symbol,but I also did not get what I want.
Are there some commands that I can use to get the  contents of a file ?

Thanks a lot!

**Comment by rhelmot** [comment]
Hello! Unless you want angr to do different things depending on different filenames that can be passed in, you probably want to pass in a concrete filename, something like `args=[proj.filename, "input_file"]`.

angr will open the input file, and assign it a file descriptor, just like linux. This file descriptor will usually be 3. To dump out the contents of file 3 as a concrete string, run `path.state.posix.dumps(3)`.

**Comment by JodieAllen** [comment]
@rhelmot Thank you very much. It is what I want.
