### ISSUE TITLE
Strange result“BV64 0x7fffffffffeff68>” when I use the function history.events.hardcopy()

### ISSUE THREAD

**Issue by EudoraQR** [angr/angr#3276]
---

Hi! developer
When I used the function history.events.hardcopy() to get the access memory address, I was surprised by the result "<SimActionData __libc_start_main() reg/read: rsp ---->> <BV64 0x7ffffffffffeff68>>" , is this result normal or is it caused by accessing an uninitialized memory address? And other results are normal "<SimActionData __libc_start_main() reg/read: rcx ---->> <BV64 0x4012a0>>"

**Comment by rhelmot** [comment]
All those are completely normal. 0x7ffff... is the default initial stack address on 64 bit arches.
