### ISSUE TITLE
Angr archinfo (arch.bits) assumes consistent address word size

### ISSUE THREAD

**Issue by grant-h** [angr/angr#329]
While developing a new VEX lifter and archinfo definition, I've noticed that there is no way to specify a default memory load size versus the size of an instruction pointer. This problem arose while developing an 8-bit architecture in which the size of IP = 16-bits, registers 8-bits, and memory loads 8-bits. If I set `arch.bits = 8` then when `simuvex/vex/irsb.py` generates `Ijk_FakeRet`, it will have the wrong target address size, causing only part of the `state.regs.ip` to be overwritten.

This leads to errors when using `sim_run` in `CFGAccurate` to generate a list of successor states.
Is this a limitation of angr and co-projects or am I missing something?

**Comment by rhelmot** [comment]
I believe the best solution currently is to set arch.bits = 16. Off the top
of my head I can't think of anything but the instruction pointer that is
affected by that field, and the assumption that the instruction pointer is
arch.bits wide is pretty hard coded.

**Comment by ltfish** [comment]
@rhelmot We have many places assuming `arch.bits` being the size of the instruction pointer. Maybe this is a good time to split `arch.bits` from `arch.ip_size` (or other names).

@grant-h May I ask what architecture does your lifter work on?

**Comment by grant-h** [comment]
A quick grep shows arch.bits being used all over, even for things like stack pops and pushes. This worried me a bit as I don't know the code as intimately as you all. My hack to fix this was just to make the part in `simuvex` where fake rets are generated use a different bit width instead of arch.bits. It would be nice to have a different variable for the instruction pointer though!

--------------
As a side story, the instruction pointer and memory layout have been the two hardest things to get right during this project. Here's why:

I've written a nearly complete VEX 8051 lifter (`8051_toIR`) and disassembler (`py8051`), which I've tied in to Angr through simuvex and archinfo. This was a project in of itself (and I'd like to upstream it to you), but once I got most instructions implemented, I moved on to actually executing 8051-based VEX IR with Angr. This is where some problems started arising. Angr was written for modern, "desktop" operating systems, meaning they have virtual memory and are most likely 32 or 64 bits. Correspondingly, VEX and Valgrind were written the same way, which bleeds in to Angr. For more embedded, "bare metal" architectures like 8051, there are some peculiarities that show up.

The first is the memory aliasing problem. 8051 has three distinct address spaces: RAM (including SFRs), code, and XDATA (external RAM). All three address spaces start at address 0x00 and are accessed by different versions of mov (`mov`, `movc`, and `movx`). This is an issue as just using pure VEX Store and Load leads to there being no way to figure out which memory segment needs to be accessed just from an IRSB. My solution to this was to use a VEX CCall with a prototype of `addr i8051g_memory(addr, segment_t)` in order to rebase memory accesses. For example, `movx A, @DPTR` which roughly translates to
```
------ IMark(0x0, 1, 0) ------
dptr_addr = i8051g_memory{0x4c49a0}(16Uto32(0x82:I16), 0x0:I8):I32)
dptr_value = LDle:I16(dptr_addr)

PUT(0) = LDle:I8(i8051g_memory{0x4c49a0}(16Uto32(dptr_value), 0x3:I8):I32)
PUT(36) = 0x1:I32
```
now uses the CCalls to take address 0x82 (DPTR) to SFR_BASE+0x82 and address DPTR to XDATA_BASE+DPTR.

The problem with this approach is that now it is possible for memory load addresses to go beyond 16-bits as we are utilizing memory ranges to communicate memory access segments. This approach was an alternative to changing or adding VEX instructions to naturally handle this case, which could break the FFI and prevent upstreaming. VEX has a word size setting that now has to be extended to 32-bits, even though the instruction pointer or any individual address space can never go beyond 64kb in reality. So now memory accesses have to be rewritten and my instruction pointer in VEX guest state has to be 32-bits or asserts get triggered in VEX. This means even though my IP in hardware is 16-bits, I have to emulate it as 32-bits, but store/load it to memory (through a call or ret) using only 2 bytes to be accurate.

The other issue related to memory is that the 8051 has memory mapped IO and registers. This means a write to address 0x7 is also a write to the R7 register in the 0th bank. I handled these aliases using `state.inspect` by getting complete mediation on all register/memory writes/reads.

Overall it has been a headache fixing these issues, which mostly stem from VEX limitations and 8051's strange architecture.

**Comment by rhelmot** [comment]
I am actually going to be giving a talk in the valgrind devroom at FOSDEM next month about the issues we've encountered in using libvex for purposes beyond its initial intent! I will definitely bring this up :)

The ccall approach looks good. There's a similar thing that happens in x86 for using segment selectors. Don't worry about the addresses surpassing 16 bits; it looks like we'll definitely need to split out the different concepts of "word size" into separate fields.

My initial instinct is to say that your access-rewriting approach of emulating a 16-bit register to the guest and a 32-bit register to the host is correct. Time will tell if it's a good solution or just a hack...

with regard to MMIO, we are internally working on writing lifters for some IoT architectures, some of which also have this property. We've decided that the solution will be that there will soon be support in simuvex for `state.registers` and `state.memory` to be aliases to the same region.

**Comment by grant-h** [comment]
@rhelmot Great to hear :) VEX is pretty amazing, but Angr is definitely pushing the envelope.

The CCall plus the {reg,mem}_{read,write} hooks are working great so far! No major issues, but coming to that solution wasn't so easy.

For MMIO, it would be great to have multiple address spaces as well, (i.e `state.mem["xdata"][0x200]`, `state.mem["sfr"][0x82]`), or something that solves that problem.

**Comment by rhelmot** [comment]
What if `state.memory` was always a flat address space, but `state.mem` could be indexed with a string like that to add a base address, like your ccalls?

Also, a quick aside: we prefer it stylized "angr", lowercase a, in all places, including at the beginning of sentences :)

**Comment by zardus** [comment]
We *could* technically use the same code that we use to support register names in `state.registers.load` to support "named" memory regions in `state.memory.load`, too...

**Comment by grant-h** [comment]
> **rhelmot commented on Jan 19**
> With regard to MMIO, we are internally working on writing lifters for some IoT architectures, some of which also have this property. We've decided that the solution will be that there will soon be support in simuvex for `state.registers` and `state.memory` to be aliases to the same region.

I haven't been paying too much attention to this, but is this going to be landing soon?

> My initial instinct is to say that your access-rewriting approach of emulating a 16-bit register to the guest and a 32-bit register to the host is correct. Time will tell if it's a good solution or just a hack...

So far it's good and bad -- good because it works well for plain symbolic execution, but bad because checking memory ranges on symbolic variables isn't 100% sound and the CFG generation 'fastpath' mode doesn't execute CCalls. Also backwards slicing seems to get bothered by CCalls as well.

**Comment by rhelmot** [comment]
- The people who were supposed to do the IoT analysis project have been suspiciously silent in terms of bugging me about things not working, so those probably are not being worked on.
- Yeah, that is something that was brought up at FOSDEM - the valgrind devs hate ccalls just as much as we do. libvex actually tries to remove all the ccalls it possibly can in the optimization step - individual ccalls have "flatten to IR" functions which try to remove them. I don't think that would work in this case, but in the future we should avoid ccalls as the solution to our problems where possible...

Another solution could potentially be to extend the IR to have a "load" command which additionally lets you specify a memory region. This would be pretty nasty and invasive to the memory model, but it would be totally correct as far as I'm aware.
