### ISSUE TITLE
Wrong type stub in `Pylance`

### ISSUE THREAD

**Issue by syheliel** [angr/angr#3290]
**Is your feature request related to a problem? Please describe.**
some methods and attributes are not found in the type stub generated by `pylance` plugin in VScode.
![image](https://user-images.githubusercontent.com/45957390/162564488-c95d111d-1186-4ba9-b569-d772036bb813.png)

**Describe the solution you would like.**
Add some type annotation for proper classes. For py2, you can add them by using comment.
**Please include a sample of what *should* work if this feature is implemented.**
`Pylance` should no longer throw errors on common usage.

**Comment by ltfish** [comment]
1. We don't support Python 2.
1. It seems that there is something wrong with your local Python indexer, since it should be trivial for your local indexer to infer that `proj` is a `Project` instance.
1. Type hinting in PyCharm works fine for me. Maybe you want to switch to PyCharm?

**Comment by syheliel** [comment]
@ltfish Hi, I have tried to close the `Pylance` plugin and Type hinting can work fine in VScode. 
I'm not familiar with the type-stub generation process of `Pylance`, I guess that the type hint mechanism used by `Pylance` is less powerful than `Python` plugin in VScode and Pycharm and you need to add some additional type information to make it work.  
I noticed that there is a job named `Lint Lint` in Azure Pipelines. Is it a static type checker like `mypy`?

**Comment by ltfish** [comment]
> I guess that the type hint mechanism used by Pylance is less powerful than Python plugin in VScode and Pycharm

Possibly. I am not a Pylance user, so I don't really know the details.

> you need to add some additional type information to make it work.

We will definitely not add additional type information just to support Pylance. Feel free to add whatever type annotations to your local copy of angr to support Pylance.

> I noticed that there is a job named Lint Lint in Azure Pipelines. Is it a static type checker like mypy?

No. We are using Pylint for linting the code. While using mypy (or any other static type checker) is nice, it is not one of our high-priority tasks.

**Comment by ltfish** [comment]
It seems that Pylance should work well for angr. Are you sure your local Pylance (or its configuration) is not broken, by any chance?
