### ISSUE TITLE
It would be exciting if it could be compatible with ghidra's IR and Graph

### ISSUE THREAD

**Issue by bmax121** [angr/angr#3301]

**Comment by ltfish** [comment]
We support P-Code (to some extent). So if you want to use P-Code instead in angr, go for it.

I’m not sure what you mean by “being compatible with Ghidra’s graph.”

**Comment by bmax121** [comment]
Thanks for your replay. I found that angr's control-flow-graph is not particularly accurate, even CFGFast. What's worse is when the code is obfuscated by OLLVM. But Ghidra can analysic the cfg accuratey. So I wonder if angr can make a symbolic execution use P-Code and make a Ghidra's cfg. I know it's quite difficult.

**Comment by ltfish** [comment]
> I found that angr's control-flow-graph is not particularly accurate, even CFGFast

That's unexpected. Maybe you want to post the binary so we can take a look?
