### ISSUE TITLE
Reassembler usage

### ISSUE THREAD

**Issue by vfoltsgt** [angr/angr#3302]
I'm trying to get assembler code from Reassembler that I can compile/link back into a binary. So far I came up with code like this:
```python
import angr
p = angr.Project("hello.elf", load_options={'auto_load_libs': False})
asm = p.analyses.Reassembler()
with open("hello.S", "w") as f:
    f.write(asm.assembly())
```

After adding ".intel_syntax noprefix" to the resulting "hello.S" (it is missed due to a bug here, should be "s += "\n".join(all_assembly_lines)": https://github.com/angr/angr/blob/master/angr/analyses/reassembler.py#L2154) I'm still cannot get a valid object file:
```shell
gcc -o hello hello.S
/tmp/ccbrOE1i.o: file not recognized: file format not recognized
```

Also, I tried "asm.assembly(symbolized=False)" since labels (label_N) inserted into the assembly code are undefined anyway. It did not work either. Any suggestions?

**Comment by ltfish** [comment]
> /tmp/ccbrOE1i.o: file not recognized: file format not recognized

What is `ccbrOE1i.o`? I don't think "file format not recognized" has anything to do with the assembly file itself. If Reassembler fails, you should see the compiler or assembler complaining about missing labels, incorrect instructions, or non-existent external symbols.

**Comment by vfoltsgt** [comment]
It is somehow related to the assembly file because if I reduce it manually to function "_start" only then it links (but crashes when run).

"ccbrOE1i.o" - is some temporary object file used by gcc. You can get a similar result with:
```shell
as -o hello.o hello.S
ld hello.o
hello.o: file not recognized: file format not recognized
```

**Comment by ltfish** [comment]
Can you run `file hello.o` and see what the output is?

**Comment by vfoltsgt** [comment]
```shell
file hello.o
hello.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

**Comment by ltfish** [comment]
Can you post your `hello.o`?

**Comment by vfoltsgt** [comment]
[hello.o.zip](https://github.com/angr/angr/files/8497551/hello.o.zip)

**Comment by ltfish** [comment]
This `hello.o` is broken (i.e., not a valid reloctable object file). How did you generate it? Can you post the assembly code?

**Comment by vfoltsgt** [comment]
I'm attaching both "hello.elf" and "hello.S". "hello.elf" is the original "Hello World" binary and "hello.S" is produced by the script at the very beginning of this discussion.
[hello.zip](https://github.com/angr/angr/files/8498965/hello.zip)
