### ISSUE TITLE
Cannot store `bytearray` objects using `state.memory.store`

### ISSUE THREAD

**Issue by LukeSerne** [angr/angr#3308]
**Is your feature request related to a problem? Please describe.**
I want to save a `bytearray` without converting it to a `bytes` object.

**Describe the solution you would like.**
It would be nice if I could pass a `bytearray` to `state.memory.store` like I can with `bytes` objects.

**Please include a sample of what *should* work if this feature is implemented.**
```python
state.memory.store(0x4_0000, bytearray([1, 2, 3]))
```

**Describe alternatives you have considered.**
Converting the `bytearray` to `bytes`, but this creates a copy that is wasteful.

**Additional context.**
When currently attempting this, you get an error. This happens because only `bytes` is checked for, and not `bytearray`.
```
File "~/.local/lib/python3.8/site-packages/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 68, in _convert_to_ast
  raise TypeError("Bad value passed to memory", thing) from None
TypeError: ('Bad value passed to memory', bytearray(b'\x01\x02\x03'))```

**Comment by rhelmot** [comment]
Fixed. It seems that there was already support for this in claripy, so it was as easy as whitelisting the additional types to support :)
