### ISSUE TITLE
How to add constraints to deal with problems caused by out-of-bounds int types in c programs

### ISSUE THREAD

**Issue by DQP2375** [angr/angr#3312]
Hello developers! I'm using angr to explore conditional branches, for example opaque predicate `x * x < 0` result is always false, after we symbolize input x, we get this constraint during exploration: `[<Bool scanf_hook_57_32 * scanf_hook_57_32 <s 0x0>]` , from a mathematical point of view, `x*x<0` does not hold, but in the c language the range of the Int type is `[-2**32-1, 2**32-1]`, but due to the symbolic x calculation The latter result is out of range, which leads to the establishment of `x*x<0` in the program. How can we solve the problem that this symbol vector is out of bounds in the calculation of the int type in C language.
At present, I know that I can add constraints to the symbolic vector x to control the range, but I don't know how to control whether the result of their calculation will exceed the range of the int type and cause an exception.
For example, BV2Int(a, is_signed=False) is provided in z3, which can handle this above problem. I wonder if there is a related method in angr as well.

```
int main(int argc, char const *argv[])
{
    int x = 0;
    scanf("%d", &x);
    if (x * x < 0)
    {
        x = x + 1;
    }
    else
    {
        x = x - 1;
    }
    printf("x=%d\n", x);
    return 0;
}
```

Currently angr can explore the branch x*x<0, that is, there exists such a solution satisfying this constraint, how do I go about it, for example what constraints to add to control the results of these calculations can not be out of bounds and generate exceptions that are not mathematically logical

**Comment by rhelmot** [comment]
There is no real way to solve the problem you're talking about. angr is a pure cpu emulator and has no notion of data types that are not simple bitvectors. Arithmetic will always produce the results a real cpu would produce with the given registers.

**Comment by DQP2375** [comment]
thank you for your reply! I have a few more questions to ask you:
1. How to convert a bit-vector symbol to an output of int or unsigned int type
2. I use angr to explore the code path, and run to the constraints obtained by if (x>3) [<Bool 0x0 <=s 0x1 + scanf_d_49_32 * scanf_d_49_32>, <Bool !(0xffffffff + scanf_d_49_32 <=s 0x3 )>, <Bool 0x3 + (0xffffffff + scanf_d_49_32) * (0xffffffff + scanf_d_49_32) + 0xffffffff * (0x3ffffffff + scanf_d_49_32[29:0] .. 0) <=s 0x0>], I want to know what 0xffffffff does in it, and the meaning of scanf_d_49_32[29:0]
#include "stdio.h"
int test(int x)
{
     int y = 0;
     int z = 1;
     if (x * x + z < 0)
     {
         x = x + 1;
     }
     else
     {
         x = x - 1;
     }
     if (x > 3)
     {
         if (x * x - 4 * x + 3 > 0)
         {
             x = x + 1;
         }
     }
     printf("y=%d\n", y);
     return x;
}

int main(int argc, char const *argv[])
{
     int x = 0, y = 0;
     scanf("%d", &x);
     y = test(x);
     return 0;
}

**Comment by rhelmot** [comment]
1. Claripy (our wrapper over z3) does not support the notion of integer types, only bitvectors. If you want to perform a solve and convert a bitvector to a concrete integer, you can use `state.solver.eval(bv)`.
2. 0xffffffff is the twos-compliment encoding of negative one. scanf_d_49_32 is a symbolic bitvector created to represent the output of scanf. [29:0] represents a bit-extract function extracting the low-order 30 bits from the operand bitvector.
