### ISSUE TITLE
Find path to a specific address

### ISSUE THREAD

**Issue by Zerotistic** [angr/angr#3325]
Hello. I've been searching for a way to find the "path" to a specific address, but cannot find a way to do so.
Take the following program: <br>
```c
#include <stdio.h>

int pwn_me()
{
	char my_buf[20] = {'\x00'};
	gets(my_buf);
	return 0;
}

int menu()
{
	char value[10];
	puts("You've multiple choice");
	puts("1) nothing");
	puts("2) pwn_me()");
	puts("3) nothing");
	fgets(value, 5, stdin);
	int num = atoi(value);
	return num;
}

void main()
{
	while(1)
	{
		int choice = 0;
		choice = menu();
		if(choice == 2){
			pwn_me();
		}
		else {
			puts("That did nothing\n\n");
		}
	}

	
}
```

Using a script that i made, i can find the `gets()` address, as well as the function address it is in. But i can't find a way to make angr find the "path" to that `gets()`. It should find that by sending "2", i'll get there.
I've tried using the following snippet, but it doesn't seems to works. Note that all given addresses are correct
```py
proj = angr.Project(self.properties['binary'])
init_state = proj.factory.entry_state()
simulation = proj.factory.simgr(init_state)
print_good = int(vuln['pwn_me']['gets'], 16)
simulation.explore(find=print_good)

if simulation.found:
	solution = simulation.found[0]
	print('input: ', solution.posix.dumps(0))
else:
	print('Cannot find path')
```
Do you have any resources, or ideas on how i could do so? 

Thank you very much to anyone who will take the time to help me!

**Comment by rhelmot** [comment]
Have you tried following this advice? https://docs.angr.io/introductory-errata/faq#why-isnt-symbolic-execution-doing-the-thing-i-want

**Comment by Zerotistic** [comment]
Hi, i'll check it out and try. Thanks.
