### ISSUE TITLE
angr on windows got an error when veritesting enabled

### ISSUE THREAD

**Issue by cha5126568** [angr/angr#334]
I successfully installed angr on Windows.
Most of the angr examples worked fine.
![222](https://cloud.githubusercontent.com/assets/13634407/22173242/1c870b6a-e000-11e6-81d5-2fd96ac24975.PNG)
However, there is an error when enable_veritesting or veritesting enabled.
![default](https://cloud.githubusercontent.com/assets/13634407/22173243/232aecf2-e000-11e6-9fed-1fa52b49155f.PNG)
So I tried to remove the LAZY_SOLVES option. And then, The following error occurred:
![22](https://cloud.githubusercontent.com/assets/13634407/22173245/29b4bd00-e000-11e6-9cd2-09dc8c2e5dfd.PNG)
How can i fix this problem that may result from windows environment?
( Sorry for my english xD)

**Comment by ltfish** [comment]
Those warnings or errors are actually handled by angr. Without removing `LAZY_SOLVES`, do you get the expected result?

**Comment by cha5126568** [comment]
that code is angr-doc/examples/defcamp_r200 and r100. when i run that codes on linux, i get the expected result. but run on windows   i get on error.

**Comment by rhelmot** [comment]
I've reproduced your bug on my windows install. I have no idea what's causing it though!

**Comment by rhelmot** [comment]
Oh, probably should clarify for the angr devs: I let the code run for about 15 minutes and instead of solving it just took up more and more ram, so there's definitely a problem somewhere
