### ISSUE TITLE
bit-vector symbol overflow problem

### ISSUE THREAD

**Issue by DQP2375** [angr/angr#3340]
Hello dear angr developers!
I'm learning and using angr recently. In the process of binary program symbolic execution, some variables will be symbolized into bit vector symbols, and the final constraint expression will be submitted to the backend (such as z3) for solving through claripy.

**My question is, does angr take into account the overflow of the bit vector sign during its operation?**（I found that z3 provides a solution to avoid bit vector overflow in some operations.）

Hope you can answer me! Thanks for reading and thank you in advance!

**Comment by rhelmot** [comment]
angr's emulated arithmetic is semantically correct with respect to how cpu words are processed, so any overflow that would happen on a CPU will also happen in angr.
