### ISSUE TITLE
CFGFast Unsupported Binop Iop_F64toI32S.

### ISSUE THREAD

**Issue by wizard0** [angr/angr#3357]
Hi developers, I got a problem when I use CFGFast to get the CFG of `jhead`:
WARNING | 2022-05-27 19:20:52,839 | cle.backends.tls | The provided object has an invalid tls_data_size. Skip TLS loading.
ERROR   | 2022-05-27 19:20:53,277 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_F64toI32S.
ERROR   | 2022-05-27 19:20:53,283 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_F64toI32S.
ERROR   | 2022-05-27 19:20:53,293 | angr.analyses.cfg.indirect_jump_resolvers.jumptable.JumpTableProcessor | Unsupported Binop Iop_F64toI32S.

Can you help me explain the cause of the error and provide a solution?
code:
```
proj = angr.Project("/home/zhd/Desktop/testcases/jhead/jhead_directed", load_options={"auto_load_libs":False})
obj = proj.loader.main_object
cfg = proj.analyses.CFGFast()
```

**Comment by rhelmot** [comment]
Just because you see an error message printed doesn't mean there was an unrecoverable fatal error! The analysis should have continued and you should have gotten access to a functioning CFG object. 

If you find that the missing op is impacting the quality of the results, I can link you guidelines on implementing it.

**Comment by wizard0** [comment]
> Just because you see an error message printed doesn't mean there was an unrecoverable fatal error! The analysis should have continued and you should have gotten access to a functioning CFG object.
> 
> If you find that the missing op is impacting the quality of the results, I can link you guidelines on implementing it.

Thank you! I will check it.
