### ISSUE TITLE
Angr may explore a false-positive path

### ISSUE THREAD

**Issue by Hanseltu** [angr/angr#3358]
---

###  **Describe the bug.**

The problem is that angr may explore a path that is unlikely to be executed.

### **Environment Information.**

The testing binary `test` is compiled with `-Os` under the current development version of GCC, and I used the latest version of `angr-dev` to execute the binary.

### **To Reproduce.**

`angr-test.py`
```
# -*- coding: utf-8 -*-
import angr
import claripy
import sys

target_binary = sys.argv[1]
sym_input = claripy.BVS("sym_input", 2*8)
p = angr.Project(target_binary, load_options={'auto_load_libs': False})
state = p.factory.entry_state(args=[target_binary, sym_input],add_options={angr.options.ZERO_FILL_UNCONSTRAINED_MEMORY,
                                           angr.options.ZERO_FILL_UNCONSTRAINED_REGISTERS})
sm = p.factory.simulation_manager(state)
#sm.run()
marker = bytes("b718b", "utf-8")
sm.explore(find=lambda s: marker in s.posix.dumps(1))
print(sm)

# constrain the symbolic input to fall within printable range
for byte in sym_input.chop(bits=8):
    state.add_constraints(byte >= 'A'.encode(), byte <= 'Z'.encode())

for i in range(len(sm.found)):
    print("No.", i, " solution:")
    print("output: ", sm.found[i].posix.dumps(1).decode('utf-8'))
    b1 = sm.found[i].solver.eval(sym_input, cast_to=bytes).rstrip(b'\x00')
    print("org b: ", b1)
    print("hex b: ", b1.decode("utf-8", "ignore"))
```

```
$python3 angr-test.py test
<SimulationManager with 1 active, 1 found>
No. 0  solution:
output:   b0b  b2b  b142b  b644b  b718b 
org b:  b'\x8a\xb0'
hex b:  
```

Similar to #3172, I used the markers to differentiate different blocks, and the sequences (e.g., "b0b  b2b  b142b  b644b  b718b") mean various blocks being executed.

I found this problem as angr can not replay the explored path as reported in #3172, and then I try to diagnose this issue what happened here. As a result, I found that angr may explore a false-positive path. The evidence can be found in Lines 100-107 in the source code `test.c` (attached in the following). We can observe that after executing `marker_644()`, it's unlikely (or impossible) to directly execute `marker_718()` as the body of *for-loop* statement starting from line 104 must be executed.

One thing I want to mention is that this behavior only occurs when the binary is compiled in the development version of GCC, while other versions do not have such a problem. The GCC version I used is `gcc version 13.0.0 20220518 (experimental) (GCC) `. Can this issue be in GCC compiler or angr? I guess angr should have good capabilities to successfully handle it?

### **Additional context.**

Here are the reproduced files, including the binarie `test`, source code(`test.c` and `test-E.c` which is compiled with `gcc -E`), and python script `angr-test.py` to run angr.
[reproducer.zip](https://github.com/angr/angr/files/8787645/reproducer.zip)

Could you please take a look at this issue when you are free?

Thank you so much for your time!
Best regards,
Haoxin

**Comment by rhelmot** [comment]
There was a bug in our eflags computation, which, from what I can tell, dates back to [december 2013](https://github.com/angr/angr/commit/92de807576c14b6f44dfc2f28a8f4c8525f17ade). It's been fixed. Thanks for your great work finding and triaging this!

**Comment by Hanseltu** [comment]
Hi @rhelmot, No problem! Good to hear this is a real bug and I am also surprised this tricky bug is lurk for such a long time! 

Thank you again for your fixing!
