### ISSUE TITLE
Got IR decoding error with Thumb-2 instruction set

### ISSUE THREAD

**Issue by OtterV** [angr/angr#3363]
---

I use unicorn support when do angr thing
```
state = proj.factory.full_init_state(addr=start_addr, add_options=angr.options.unicorn)

# init...

simgr = proj.factory.simulation_manager(state)
simgr.run()
```
and I got nothing, it didn't completely executed and warning
```
WARNING | 2022-05-31 00:06:04,294 | angr.state_plugins.unicorn_engine | Flag registers for ARMEL not set in native unicorn interface.
WARNING | 2022-05-31 00:06:04,313 | angr.state_plugins.unicorn_engine | Flag registers for ARMEL not set in native unicorn interface.
```

So, I want to know what does it mean?
Thx

**Comment by OtterV** [comment]
Oh, I found that simgr._errored stored the error infomation
```
[<State errored with "IR decoding error at 0x40601c. You can hook this instruction with a python replacement using project.hook(0x40601c, your_function, length=length_of_instruction).">]
```
It seems that angr could not handle this situation
```
.text:00006018                 LDRD.W          R2, R3, [SP,#8+var_8]
.text:0000601C                 LDRB            R0, [R1,R2]
.text:0000601E                 EOR.W           R0, R0, #0x15
.text:00006022                 STRB            R0, [R1,R2]
.text:00006024                 ADDS            R0, R2, #1
```
It seems that angr doesn't support Thumb-2 instructions.

**Comment by OtterV** [comment]
I have solved my problem by using `thumb` param
```
simgr.run(thumb=True)
```

**Comment by ltfish** [comment]
The intended solution: `state = proj.factory.full_init_state(addr=start_addr | 1, add_options=angr.options.unicorn)`.

Like ARM, angr uses the last bit in addresses to determine the THUMBness.

**Comment by OtterV** [comment]
I try to set start_addr and I got unexpected result, but adding `thumb=True` as mentioned above can make it run as my expectation.
```
WARNING | 2022-06-01 13:13:56,725 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory with an unspecified value. This could indicate unwanted behavior.
WARNING | 2022-06-01 13:13:56,725 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2022-06-01 13:13:56,726 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2022-06-01 13:13:56,726 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2022-06-01 13:13:56,726 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2022-06-01 13:13:56,726 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0x70 with 4 unconstrained bytes referenced from 0x400065 (offset 0x65 in libyaqcore.so (0x65))
WARNING | 2022-06-01 13:13:56,853 | angr.storage.memory_mixins.default_filler_mixin | Filling memory at 0xd with 1 unconstrained bytes referenced from 0x400099 (offset 0x99 in libyaqcore.so (0x99))
```
Maybe my hook `start_addr` behavior influence it?

**Comment by ltfish** [comment]
Essentially `thumb=True` just forces the last bit of your address to 1, which should be the same as specifying an odd address to start execution.

**Comment by rhelmot** [comment]
I wouldn't be surprised if there were a bug in unicorn which under some circumstances can "lose" the thumb bit, causing execution to halt at an even address. With thumb=True specified at the simgr level, angr will kick the state back to an odd address on every engine invocation.

**Comment by OtterV** [comment]
> Essentially `thumb=True` just forces the last bit of your address to 1, which should be the same as specifying an odd address to start execution.

But it performed actually differently.
Maybe it's because I first use a SimProcedure before jump to thumb things code...

And about Unicorn Engine, could I get some Information about it somewhere? I didn't find much about it.

**Comment by rhelmot** [comment]
Unicorn engine is https://www.unicorn-engine.org/. Our interface to it is https://github.com/angr/angr/blob/master/angr/state_plugins/unicorn_engine.py and https://github.com/angr/angr/blob/master/native/sim_unicorn.cpp.

I found https://github.com/angr/angr/issues/2725, which seems to describe your exact problem.
