### ISSUE TITLE
Question on unitialized memory

### ISSUE THREAD

**Issue by lks9** [angr/angr#3372]
I plan using angr for a project so I just did some experiments to see if things work in the way I expect before getting started. 

My question is on unitialized memory and I have attached a C program and its binary.

[uninitialized.zip](https://github.com/angr/angr/files/8834867/uninitialized.zip)

When executing `unitialized` it just prints out the value of an unitialized integer. This value changes every time I execute it on my computer:

```
$ ./unitialized
22099
```

However, when symbolically executing the file with angr, I always get `0` as the value:
```Python
import angr
p = angr.Project("uninitialized")
sm = p.factory.simulation_manager(p.factory.entry_state())

# 0x4011a1 is line 8 in unitialized.c
sm.explore(find=0x4011a1)
s2 = sm.found[0]

# prints only one solution "<BV64 0x0>" for the variable "y"
print(s2.mem[0x404014].int64_t)
```

So angr seems to fill the unitialized memory with zero. But I want angr to fill it with a symbolic value. To do a concretization later, like this:
```Python
y = s2.memory.load(0x404014, 8)
s2.add_constraints(y == 22099)
```
However, then the state simply becomes unsatisfiable.

I played with some state options but nothing seems to work. I have seen how to do it for command line arguments with a symbolic claripy variable. But not for uninitialized (local) variables. And I would prefere to do it without explicitly introducing a symbolic variable. Is there a way? Thank you very much in advance!

**Comment by mborgerson** [comment]
Execution is not identical to how it runs on your local machine, so this value in stack may be initialized differently (to 0) when your main function runs. You can create a call state for the main function and uninitialized stack data will be symbolic by default. e.g.

```
sm = p.factory.simgr(p.factory.call_state(p.kb.functions['main'].addr))
```

**Comment by lks9** [comment]
Thank you very much for the quick reply. Your solution worked well. I only needed to call `p.analysis.CFG()` to fill `p.kb.functions`.

> Execution is not identical to how it runs on your local machine, so this value in stack may be initialized differently (to 0) when your main function runs.

So, there is some initialization going on in angr that does not happen on a local machine? Wouldn't that be a **bug** in angr?
I played a bit with `factory.call_state()`, `factory.entry_state()` and `factory.blank_state()` and got:

```Python
import angr
p = angr.Project("uninitialized", load_options={'auto_load_libs': False})
p.analyses.CFG()
start_addr = p.kb.functions['_start'].addr
main_addr = p.kb.functions['main'].addr

sm_e1 = p.factory.simulation_manager(p.factory.entry_state())
sm_e1a = p.factory.simulation_manager(p.factory.entry_state(addr=start_addr))
sm_e2 = p.factory.simulation_manager(p.factory.call_state(start_addr))
sm_e3 = p.factory.simulation_manager(p.factory.blank_state(addr=start_addr))
sm_m1 = p.factory.simulation_manager(p.factory.entry_state(addr=main_addr))
sm_m2 = p.factory.simulation_manager(p.factory.call_state(main_addr))
sm_m3 = p.factory.simulation_manager(p.factory.blank_state(addr=main_addr))

line8_addr = 0x4011a1
sm_e1.explore(find=line8_addr)
sm_e1a.explore(find=line8_addr)
sm_e2.explore(find=line8_addr)
sm_e3.explore(find=line8_addr)
sm_m1.explore(find=line8_addr)
sm_m2.explore(find=line8_addr)
sm_m3.explore(find=line8_addr)

s_e1 = sm_e1.found[0]
s_e1a = sm_e1a.found[0]
s_e2 = sm_e2.found[0]
s_e3 = sm_e3.found[0]
s_m1 = sm_m1.found[0]
s_m2 = sm_m2.found[0]
s_m3 = sm_m3.found[0]

y_addr = 0x404014
print(s_e1.mem[y_addr].int32_t)
print(s_e1a.mem[y_addr].int32_t)
print(s_e2.mem[y_addr].int32_t)
print(s_e3.mem[y_addr].int32_t)
print(s_m1.mem[y_addr].int32_t)
print(s_m2.mem[y_addr].int32_t)
print(s_m3.mem[y_addr].int32_t)
```

For `s_e1` and `s_e1a` the memory is initialized to 0 and for all other cases the memory is UNINITIALIZED. Even if the execution was started at `_start`. And `entry_state()` seems to do the strange 0 initialization only when started at `_start` and not when started at `main`.
