### ISSUE TITLE
test_decompiler.TestDecompiler.test_decompilation_excessive_condition_removal is failing

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#3377]
This appears to have begun with commit 360b09d9cd0c93120fc52d79e6d1e613c34774ea

**Comment by mborgerson** [comment]
- The tested binary is a mach-o. We fail to pick up libc functions here. CLE reports that this binary has no sections.
- The function being decompiled calls `getc()` stub with an unresolved jump out. After the patch, the jump-out is treated as a (non-returning) UnresolvableJumpTarget function, so `getc()` also becomes non-returning causing premature function exit and test failure.
- Details:
  - Before the patch, two addresses that were not mapped to any section were considered to be in the same section by `CFGBase::_addrs_belong_to_same_section`.
     - `_determine_function_returning` checks if the stub function jump out is a function. One was not created for this unresolvable jump target (in `CFGBase::_graph_traversal_handler`), so stub function returning is not determined.
     - In `_post_analysis` the undetermined returning behavior of the function is set to `True` becaues it has an endpoint.
  - The patch adds a test for this condition now such that two addresses that cannot each be mapped to a section are tested for being in the same segment.
     - With the stub and its jump target being separate segments, `CFGBase::_addrs_belong_to_same_section` returns `False`, prompting a function to be generated in `CFGBase::_graph_traversal_handler`. The generated func is an `UnresolvableJumpTarget`, which does not return.
      - `_determine_function_returning` checks if the stub function jump out has a function. Now it does, and because it is an `UnresolveableJumpTarget` it has `NO_RET`, and forces the stub to be non-returning as well.
      - You can work around this by setting `skip_unmapped_addrs=False`

* I think the behavior here is correct in handling these unresolved jump targets: we don't know so should not assume by default; however `call`s are treated as returning if the target is unresolved, so this is a bit inconsistent. We could check the unresolved jump out of the call stub and handle it similarly. Maybe it should be configurable with `assume_unresolved_call_targets_returning` or something.
* We should improve mach-o support and pick up these imports (IDA does).
* In the mean time, perhaps we should replace this test binary with one we have better support for. Maybe I'm missing something about why this is a mach-o to begin with. We don't have source for this binary in the binaries repo. Looks like it is [this](https://github.com/kgabis/brainfuck-c/). I've compiled it for Linux and the test passes.

**Comment by rhelmot** [comment]
Unless @ltfish jumps in with an objection, I approve replacing that binary with an ELF.
