### ISSUE TITLE
page_addr of None when merging states

### ISSUE THREAD

**Issue by f4c31e55** [angr/angr#3380]
When merging states, an exception is thrown in the page store:

```
[repro.tar.gz](https://github.com/angr/angr/files/8857397/repro.tar.gz)

~/.local/lib/python3.8/site-packages/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py in store(self, addr, data, size, endness, memory, page_addr, cooperate, **kwargs)
    120                 # trim the unnecessary leading bytes if there are any
    121                 full_bits = len(data.object)
--> 122                 start = (page_addr + addr - data.base) & ((1 << memory.state.arch.bits) - 1)
    123                 if start >= data.base + data.length:
    124                     raise SimMemoryError("Not enough bytes to store.")

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by rhelmot** [comment]
The only thing that looks sketchy about what you're doing is the rampant merging. Can you try replacing your merge-at-every-step logic with either veritesting or manualmergepoints and see if the same bug pops up?

**Comment by f4c31e55** [comment]
So the simple version of this, that works directly on the binary, works great under Veritesting. I ca't use Veritesting for this as it complains about lifting blocks because I've dynamically added the code it's executing. I didn't know about ManualMergepoint and gave it a go, but it doesn't seem to be merging states at all.

**Comment by rhelmot** [comment]
In that case, can you try your analysis directly on the binary with the merge-at-every-step logic?

**Comment by f4c31e55** [comment]
merge at every step works directly on the binary
I rewrote a small piece of the ManualMergepoint and it seems to be making progress and not failing the merge. Perhaps there are points in the execution where memory is somehow inconsistent between the states and that hurts the merge logic?

**Comment by rhelmot** [comment]
It is very possible that merge has a broken edge case this is hitting, especially somewhere in ultra page. I'm not sure how to go about tracking it down... it would be nice if we had some sort of checker which after every merge verified that every changed memory location must be equivalent across states with the constraint that the merge condition goes one way.

**Comment by f4c31e55** [comment]
I guess it did just end up as a merge stress test. Thanks for looking into it. I'll proceed with writing a custom ManualMergepoint
