### ISSUE TITLE
(ARM) b.loader.main_bin.plt -> strange address

### ISSUE THREAD

**Issue by phros** [angr/angr#339]
Hello,

I have a simple hello word binary ([run.zip](https://github.com/angr/angr/files/723599/run.zip), ARM). For visualizing the control flow graph, I want to filter branches to external symbols, in this case printf. For detecting these branches I check the addresses stored in the PLT:

```
In [3]: b.loader.main_bin.plt
Out[3]: {'__libc_start_main': 66284, u'printf': 66268}

In [4]: hex(66268)
Out[4]: '0x102dc'
```

While in the actual code branches for invoking printf are targeting the address: 0x102e0. Is this a bug from CLE or am I missing something?

objdump output looks like this:
```
000102cc <printf@plt-0x14>:
   102cc:       e52de004        push    {lr}            ; (str lr, [sp, #-4]!)
   102d0:       e59fe004        ldr     lr, [pc, #4]    ; 102dc <_init+0x1c>
   102d4:       e08fe00e        add     lr, pc, lr
   102d8:       e5bef008        ldr     pc, [lr, #8]!
   102dc:       00010d24        .word   0x00010d24

000102e0 <printf@plt>:
   102e0:       e28fc600        add     ip, pc, #0, 12
   102e4:       e28cca10        add     ip, ip, #16, 20 ; 0x10000
   102e8:       e5bcfd24        ldr     pc, [ip, #3364]!        ; 0xd24

000102ec <__libc_start_main@plt>:
   102ec:       e28fc600        add     ip, pc, #0, 12
   102f0:       e28cca10        add     ip, ip, #16, 20 ; 0x10000
   102f4:       e5bcfd1c        ldr     pc, [ip, #3356]!        ; 0xd1c
```

Thanks

**Comment by ltfish** [comment]
I looked into it, it's a bug in cle. Our hackish PLT detection believes printf starts at 0x102dc since the pointer at 0x102dc is decodable as ARM code. I'll make a (equally hackish) patch to it.

**Comment by ltfish** [comment]
The related code is [here](https://github.com/angr/cle/blob/master/cle/backends/metaelf.py#L124).

**Comment by ltfish** [comment]
[This commit](https://github.com/angr/cle/commit/352a6df9dfb2252f896a0f7f3199133de78184c6) fixes your issue. Thanks for reporting. It will be merged to master once internal tests pass. You'll have to update CLE after that.

Can I use your ARM binary to add a new test case for CLE?

**Comment by phros** [comment]
Thanks a lot! Sure, you can have the binary!

**Comment by ltfish** [comment]
> Sure, you can have the binary!

Thank you :-)
