### ISSUE TITLE
Accessing "uninitialized" memory in C structs

### ISSUE THREAD

**Issue by frediramos** [angr/angr#3408]
We are currently using angr `v9.2.6` to symbolically execute an implementation of a C Hashmap. We have however encountered some problems where angr is accessing what it thinks to be uninitialized memory, but that was in fact initialized. 

To illustrate this, we symbolically execute the following, fully concrete, test on our target hashmap implementation. 
```c
#Define BUCKETS 1

int main(){

  //Create hashmap with one bucket
  hashmap_t map = hashmap_new(BUCKETS);

  //Insert 1 key-value pair (concrete key and value)
  char key1[] = "abcde1111" ;
  int value1 = 1;

  hashmap_set(map, key1, &value1, sizeof(int));
  int* ptr1 = (int *) hashmap_get(map, key1);
}
```
This test allocates a hashmap and uses it to store a single key/value pair using the `hashmap_set` function; then, it immediately retrieves the value associated with the stored key from the hashmap using the `hashmap_get` function.

The hashmap itself is implemented using simple structures and arrays, as illustrated bellow. You can find the code full [here](https://gist.github.com/Richard-W/9568649).

```
    hashmap_t
+----------------+
|     size       |
|    *fields     |
|       |        |
+----------------+
|       |        |
|       |        |     hashmap_entry          
|   +--------+   |     +----------+     +----------+
|   | size   |   |     | Key      |-----| Key      |-----
|   | *entries---|---->| Value    |     | Value    |
|   +--------+   |     +----------+     +----------| 
|       |        |
|       |        |
|       |        |
|  hashmap_field |
|   +--------+   |     +----------+     +----------+
|   | size   |   |     | Key      |-----| Key      |-----
|   | *entries---|---->| Value    |     | Value    |
|   +--------+   |     +----------+     +----------| 
|       |        |
|      ...       |


```
When running this test, we observed that angr tries to access uninitialized memory during the call to the `hashmap_get` function given below. In particular, when iterating through the array of `hashmap_entries`, angr treats the access to the `key` field of the `entry` structure as if it was uninitialized memory. We do not understand why this is the case given that field was set to a concrete value.

```c
void *hashmap_get(hashmap_t map, char *key) {
  
  int hash = hashmap_hash(key, map->size - 1);
  struct hashmap_field *field = map->fields + hash;
  struct hashmap_entry *entry;

  int i;
  for(i = 0; i < field->size; i++) {
    entry = field->entries + i;
    
    // entry->key points to unitialized memory
    
    if(strcmp(entry->key, key) == 0) {
      return memcpy(malloc(entry->len), entry->val, entry->len);
    }
  }
  return NULL;
}
```

We have executed this Hashmap implementation before with other symbolic execution tools so we are fairly confident that this behaviour is not caused by a bug in the code. Even so, we include the code for the `hashmap_set` function below.
```c
void hashmap_set(hashmap_t map, char *key, void *value, size_t length) {
  int hash = hashmap_hash(key, map->size - 1);
  struct hashmap_field *field = map->fields + hash;
  struct hashmap_entry *entry;

  int i;
  /* Check if entry with the same key already exists in field. */
  for(i = 0; i < field->size; i++) {
    entry = field->entries + i;
    if(strcmp(entry->key, key) == 0) {
      free(entry->val);
      goto set_val;
    }
  }
  /* Create new entry */
  if(value == NULL) return;
  field->size++;
  field->entries = realloc((void*) field->entries, field->size * sizeof(struct hashmap_entry));
  entry = field->entries + field->size - 1;
  entry->key = strdup(key);

  set_val:
  if(value != NULL) {
    entry->val = memcpy(malloc(length), value, length);
    entry->len = length;
  } else {
    free(entry->key);
    field->size--;

    if(entry != (field->entries + field->size)) {
      memcpy((void*) entry, (void*) (field->entries + field->size), sizeof(struct hashmap_entry));
    }

    /* Shrink field */
    field->entries = realloc((void*) field->entries, field->size * sizeof(struct hashmap_entry));
  }
}
```
Note that the `key` field is initialized using the `strdup` function (`entry->key = strdup(key);`) which we implement concretely as:
```c
char* strdup(char * str){
  int size = strlen(str);
  char* dest = malloc(size+1);
  strcpy(dest, str);
  return dest;
}
```
For this particular test we use concrete library implementations for all the required libc functions, with the exception of the heap functions (`malloc`, `free` and `realloc`), for which we use angr's default Simprocedures. Furthermore, we have tried both of angr's Heap plugins: `SimHeapPTMalloc` and `SimHeapBrk` without success. 

Finally, we also give the configuration for our angr driver script for you to assess.

```python
p = Project(binary, exclude_sim_procedures_list=ignore_list)

opt = options.TRACK_SOLVER_VARIABLES
state = p.factory.entry_state(mode='symbolic', add_options={opt,})

state.register_plugin('heap', SimHeapPTMalloc())
sm = p.factory.simulation_manager(state)

sm.run()
```

**Comment by rhelmot** [comment]
Can you please provide the binary file meant to be used with your driver script?

**Comment by frediramos** [comment]
> Can you please provide the binary file meant to be used with your driver script?

Of course.

**Comment by frediramos** [comment]
> Can you please provide the binary file meant to be used with your driver script?

Of course, [test0.zip](https://github.com/angr/angr/files/8980637/test0.zip)

**Comment by rhelmot** [comment]
Somehow, your malloc seems to be interpreted by the compiler as returning a 32 bit value. Look at the disassembly for the calls to malloc, they're all followed by `cdqe`. angr's default heap is at 0xc0000000, so trying to sign extend this will return 0xffffffffc0000000, which is definitely pointing to uninitialized memory.

Did you bypass some compiler warnings about implicitly defining malloc and needing to add a header?

**Comment by frediramos** [comment]
Yes, we definitely bypassed those warnings. However, it seems that setting the ```heap_base``` to a 64bit value as follows might have done the trick.
```python
SimHeapPTMalloc(heap_base=0x0000000000000000))
```
I still need to run some more tests just to make sure, but if nothing else comes up I will just close the issue. 
Thank you very much for the help and fast response.
