### ISSUE TITLE
Backer is Empty - empty segment during binary loading 

### ISSUE THREAD

**Issue by HIPERION2021** [angr/angr#3409]
---

**Describe the bug.**

When trying to load a binary using blob backend (for an android firmware) the binary file is divided in segments but 2 of those segments are empty, as soon as the program gets an empty segment it will throw an error (Backer Empty) and stop. The issue was solved for elf files on a 2021 commit by making the if not data: statement return instead of rise ErrorValue() and then in elf.py marked those empty segments to avoid using them. I'm facing the issue in a blob (as previously stated).  

**Environment Information.**

angr environment report
=============================
Date: 2022-06-25 03:54:32.703466
Running in virtual environment at /home/esteban/angr
Platform: linux-x86_64
Python version: 3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
######## angr #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/angr
Pip version angr 9.2.6
Couldn't find git info
######## ailment #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/ailment
Pip version ailment 9.2.6
Couldn't find git info
######## cle #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/cle
Pip version cle 9.2.6
Couldn't find git info
######## pyvex #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/pyvex
Pip version pyvex 9.2.6
Couldn't find git info
######## claripy #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/claripy
Pip version claripy 9.2.6
Couldn't find git info
######## archinfo #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/archinfo
Pip version archinfo 9.2.6
Couldn't find git info
######## z3 #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/z3
Pip version z3-solver 4.8.17.0
Couldn't find git info
######## unicorn #########
Python found it in /home/esteban/angr/lib/python3.10/site-packages/unicorn
Pip version unicorn 1.0.2rc4
Couldn't find git info
######### Native Module Info ##########
angr: <CDLL '/home/esteban/angr/lib/python3.10/site-packages/angr/state_plugins/../lib/angr_native.so', handle 22c3110 at 0x7f012916d900>
unicorn: <CDLL '/home/esteban/angr/lib/python3.10/site-packages/unicorn/lib/libunicorn.so', handle 1c82020 at 0x7f012d643820>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f012e102e30>
z3: NOT FOUND

**To Reproduce.**

https://github.com/fiberx/fiber/archive/refs/heads/master.zip
this is a link to Fiber repo, the binaries are in the example folder and are called angler_img_20170513 and angler_img_20170513.sym (the symbol table should you need it) 

**Additional context.**

I'm using a modified version of Fiber and I'm not importing simuvex (since it was migrated to angr) but as the loader is being used as id in the script (utils.py) you should be able tor reproduce the error by loading the aforemention binary.

The terminal output is as follows:
angr) $ python ext_sig.py
Probed image base address: ffffffc000080000
WARNING | 2022-06-25 03:47:56,532 | cle.backends.blob | No entry_point was specified for blob angler_img_20170513, assuming 0
Traceback (most recent call last):
  File "/home/esteban/angr/fiber/ext_sig.py", line 372, in <module>
    ext_sig()
  File "/home/esteban/angr/fiber/ext_sig.py", line 228, in ext_sig
    b = load_kernel_image(argv1,ARCH,BASE,segments=code_segments)
  File "/home/esteban/angr/fiber/utils_sig.py", line 48, in load_kernel_image
    b = angr.Project(path, load_options=load_options, arch=arch)
  File "/home/esteban/angr/lib/python3.10/site-packages/angr/project.py", line 137, in __init__
    self.loader = cle.Loader(self.filename, concrete_target=concrete_target, **load_options)
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/loader.py", line 133, in __init__
    self.initial_load_objects = self._internal_load(main_binary, *preload_libs, *force_load_libs, preloading=(main_binary, *preload_libs))
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/loader.py", line 689, in _internal_load
    obj = self._load_object_isolated(main_spec)
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/loader.py", line 871, in _load_object_isolated
    result = backend_cls(binary, binary_stream, is_main_bin=self.main_object is None, loader=self, **options)
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/backends/blob.py", line 61, in __init__
    self._load(file_offset, mem_addr, size)
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/backends/blob.py", line 82, in _load
    self.memory.add_backer(mem_addr - self.linked_base, string)
  File "/home/esteban/angr/lib/python3.10/site-packages/cle/memory.py", line 184, in add_backer
    raise ValueError("Backer is empty!")
ValueError: Backer is empty!

**Comment by HIPERION2021** [comment]
as an update I tried loading the different segments only if they are not empty (len > 0) but then, when I tried to call CFGAccurate angr throw an error saying that there's no plugin called CFGAccurate.

**Comment by HIPERION2021** [comment]
I found out that GFGAccurate was refactored to CFGEmulated. That made everything run to complition. still, as Im not an expert on angr, Is what I did allowed? or theres some negative consequences to ignore blocks with length = 0?

**Comment by ltfish** [comment]
What do you want to do? In most cases, you may want to use `CFGFast` (the default CFG) instead of `CFGEmulated`.

Loading a binary with empty segments should probably not fail with exceptions. @rhelmot

**Comment by HIPERION2021** [comment]
I'm trying to use the CFG to analyze a function and locate specific line of code, then make a binary signature that can be used to identify the presence of that line in the binary (It is what that Fiberx/fiber repo should do, just that their code is not working, I'm modifying it and fixing some bugs). What I did was changing the _load function on blob.py to load the segment to memory only if size > 0. Then the empty blocks are not being loaded. That made it pass the exception, but when I try to use CFGEmulated to analyze functions, most of them return that there is no nodes on the segment (which doesn't seems right). That's why I asked if skipping the empty blocks may mess up the addresses on the loaded bin? (I'm trying to understand why the CFG cant find any nodes in an entire function.)
I will try CFGFast also, if you find that my solution to the Empty Backer is faulty please let me know, I need to get this project going. Of course, if I I can help in anyway to solve the issue also let me know how.
