### ISSUE TITLE
How to extract the pointer's address value used by fread?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#341]
Hi,
within my C code I used ```fread``` but I don't know how to get the pointer's value. I the application was compiled with gcc I don't have any problem but if compiled with clang ( always 64 bit arch ) I have problems. I do something like:

```
target = cc.arg(node.input_state, 0)
address = node.input_state.se.any_int(target)
print address
```

I have always 0. If i print ```target.varibles``` I have ```('reg_40_5_64', None, None, None, False, False, None)```. How can I obtain the value in this case?

Thanks

**Comment by ltfish** [comment]
Does clang use a different calling convention for `fread`?

**Comment by frapik99** [comment]
Hi,
I don't think so... I have also checked ```node.input_state.regs.rdi``` and I have 0. Should I try something different?

Thanks

**Comment by ltfish** [comment]
My gut feeling is that the calling conventions are different. Posting the binary here will be very useful.

**Comment by frapik99** [comment]
Hi,
you can download the file from here: [https://ufile.io/50c67](url)

Thanks

**Comment by schieb** [comment]
The first argument to fread should be a pointer. Your are passing it a dereferenced stack value instead, which on my system ends up being `_start`. In angr, it would likely end up being unconstrained.

You did not post source code but the fix will likely involve adding an `&` to the first argument.
The assembly at `0x4006b8` will then change from `mov rdi, [rbp-0x18]` to `lea rdi, [rbp-0x18]`.

**Comment by frapik99** [comment]
Thank solved
