### ISSUE TITLE
Install/Build from pip currently failing

### ISSUE THREAD

**Issue by jlamendo** [angr/angr#343]
Building via pip on Debian Jessie ( kali rolling ) and ubuntu (linux subsystem for windows ) currently fails when compiling simuvex, stating that uc_context_free is not defined in this scope.

Most likely an issue with pip not fetching the latest commit of simuvex, https://github.com/angr/simuvex/commit/89a952fb23c3ec3f2e28aa20c17a625acf810b6e 

I was able to get the build working by creating a virtualenv, installing the latest simuvex from git, and then using pip to install angr, confirming my suspicion. I'm not intimately familiar with how build dependency versions are specified with pip, but the specified simuvex version does need to be updated.

Thanks for all your hard work on this - angr is amazing!

**Comment by rhelmot** [comment]
Known. The unicorn API changed a few days ago. This has already been fixed on github and will be fixed on pypi as soon as we make a release.
