### ISSUE TITLE
test_memory.test_mv_crosspage_store FAIL

### ISSUE THREAD

**Issue by FantasqueX** [angr/angr#3437]
---

**Describe the bug.**

Currently, test_memory.test_mv_crosspage_store fails.
```
$ python -m nose2 -v test_memory.test_mv_crosspage_store
test_memory.test_mv_crosspage_store ... FAIL

======================================================================
FAIL: test_memory.test_mv_crosspage_store
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fanta/angr/angr/tests/test_memory.py", line 616, in test_mv_crosspage_store
    assert state.solver.eval_one(all_bytes.one_value()) == (1337 << 40) | 13371337
AssertionError

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
```
This test was introduced in https://github.com/angr/angr/commit/f265867a184b9ec37c2a396700e28fe4d738b8c2 . However, it fails even when I check out at that commit. Angr CI just skips this test. So I file this issue to prevent this test failing being forgotten.

**Comment by FantasqueX** [comment]
Sorry, This issue is because I didn't use git version angr to test. It's correct when my local angr updates.

**Comment by ltfish** [comment]
I am always happy that an issue resolves itself :)
