### ISSUE TITLE
Stop angr from filling memory regions

### ISSUE THREAD

**Issue by vm2p** [angr/angr#3476]
Hi,

I used angr a few years ago to develop a project with the goal of analyzing binary executables. It was some time ago, and the angr version I was using at the time was 7.8.9.26, which I also believe is the last one that is compatible with Python 2. Now, I'm trying to revive the project, updating the codebase to Python 3 and using the latest version of angr.

One of the most significant differences I noticed is that angr now fills unknown regions (either memory or addresses) by generating some unconstrained symbolic variable. I get the following message:

```
The program is accessing register with an unspecified value. This could indicate unwanted behavior.
angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
1) setting a value to the initial state
2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
```

This message occurs after I create an angr Project and then creating a CFG using `analyses.CFGFast`. 

I believe this is causing some differences between the two solutions (the one that uses angr 7.8.9.26 and the one that uses the latest angr version). How can I tell angr to don't generate those unconstrained symbolic variables? I believe the solution is to add ZERO_FILL_UNCONSTRAINED_MEMORY and ZERO_FILL_UNCONSTRAINED_REGISTERS to the state options but I actually can't find where to update the state options. 

So, if I have the following code:

```
p = angr.Project(path_to_binary, auto_load_libs=load_libs)
cfg = p.analyses.CFGFast()
```

where is the most suitable place to update the state options?

Thank you very much in advance!

**Comment by rhelmot** [comment]
I believe in that old version, angr still filled memory with unconstrained symbolic variables, it was just silent about it.

**Comment by rhelmot** [comment]
@ltfish you should figure out how to make that message not show up when doing a cfgfast analysis :)

**Comment by vm2p** [comment]
Thank you!

**Comment by ltfish** [comment]
I fixed a bunch of such warning messages when running CFG analysis. This has to be a case that I could not trigger with trivial binaries. I would appreciate it if @vm2p can post the binary that displays this behavior.
