### ISSUE TITLE
angr native does not seem to be built when using latest (65.0.1) setuptools when using editable builds

### ISSUE THREAD

**Issue by dnivra** [angr/angr#3487]
**Describe the bug.**

angr's native interface is not built correctly when using the latest setuptools(65.0.1 as of writing). Things seem to work fine when using setuptools 64.0.1 or earlier but things don't work correctly with 64.0.2, so I assume everything newer than that version is a problem. Since this seems to affect building native libraries, pyvex is also likely affected: `libpyvex.so` does not seem to be built and importing pyvex fails when using 64.0.2 and 65.0.1. However, pinning setuptools version in pyvex and angr alone didn't seem to work from what I tried. I resorted to pinning setuptools version in `setup.sh` in `angr-dev` and it worked so perhaps some other repo is also affected?

Edit: This is possibly only an issue when using editable builds(I guess that's what `angr-dev` scripts setup?). Installing angr 9.2.14 from PyPI when using latest setuptools seems to work fine.

**To Reproduce.**

A fresh install of angr using `angr-dev` should reproduce this.

**Additional context.**

Possibly relevant: angr/angr#3484 and pypa/setuptools#3522 (this is about 65.0.0 though)

**Comment by twizmwazin** [comment]
This is only an issue with editable installs, and for now the only solution is to use an older setuptools (<64 in CI). If you use --no-build-isolation (as angr-dev and angr ci do), then the pinned version in pyproject.toml is ignored since it is built in the existing environment. The issue doesn't seem to be unique to us, and once setuptools is fixed I'll pin the version to the fixed version in pyproject.toml and the relevant install scripts.

**Comment by dnivra** [comment]
Ah so pyproject.toml is ignored in that specific build approach; that's why pinning in there didn't work. Looks like this might be an issue in angr-dev and not angr; maybe this issue should be transferred to that repo? Should the version of setuptools used should be pinned in `angr-dev`'s `setup.sh`?

**Comment by twizmwazin** [comment]
As of setuptools 65.1 they've documented how to use the "legacy editable" mode via an environment variable. If that works with angr dev that is probably preferable to pinning old versions, in angr dev and in CI. If possible we should also make whatever changes are necessary to be compatible with whatever the new way of doing things is.

**Comment by ltfish** [comment]
I think using the legacy mode is acceptable. But I also want to know why their changes broke our install, and if possible, we should make our editable install be compatible with the new changes in setuptools.

**Comment by twizmwazin** [comment]
I tested various commits of setuptools between versions 64.0.1 and 64.0.2, and I found that this commit appears to be the culprit, as builds begin failing after this: https://github.com/pypa/setuptools/commit/048633afd7d6e4f852766d06c975ad602a035193

**Comment by twizmwazin** [comment]
I tested commits between versions 64.0.1 and 64.0.2, this commit appears to be where our builds begin to fail: https://github.com/pypa/setuptools/commit/048633afd7d6e4f852766d06c975ad602a035193

**Comment by twizmwazin** [comment]
Alright it seems that `pip install -e` is no longer calling setuptools' develop command, it is now calling the `editable_wheel` command. Adding in an override in pyvex that is the same as the develop command appears to have fixed the issue locally.

**Comment by twizmwazin** [comment]
This issue is fixed as of 7a35d5d0a6046ad9f3303022c498eba4322a22d0. angr-dev and CI still use the old pinned version, but angr and pyvex should now work correctly in newer setuptools.
