### ISSUE TITLE
Difference between angr bindiff and zynamics BinDiff?

### ISSUE THREAD

**Issue by gitttt** [angr/angr#35]
As there is no documentation about the bindiff feature of angr, it would be interesting to know what the differences compared to zynamics BinDiff are.
Do they have the same purpose and underlying functioning?

**Comment by salls** [comment]
I will try to add documentation sometime soon. 

angr's bindiff is based off of this paper http://static.googleusercontent.com/media/www.zynamics.com/en//downloads/bindiffsstic05-1.pdf which I believe describes the initial implementation of zynamics BinDiff. The two tools should serve similar purposes, although the lack of a gui for angr's bindiff makes it a little harder to use for manual analysis. 

They both try to match functions and basic blocks and determine which have changed. I know zynamic's bindiff includes a little more functionality and uses more features for matching.

**Comment by gitttt** [comment]
I see. Thank you for the info.
