### ISSUE TITLE
IFuncResolver breaks functionality of Project.hook_symbol

### ISSUE THREAD

**Issue by carter-yagemann** [angr/angr#3503]
---

**Describe the bug.**

angr currently inserts `IFuncResolver`s by directly writing to the GOT: https://github.com/angr/angr/blob/3090a97c73a74187f3bfdb85aa61856d064569f5/angr/simos/linux.py#L121-L124

As a result, if someone tries to hook the corresponding symbol (e.g., `strrchr`) with their own simproc, the new simproc will not be invoked.

**To Reproduce.**

1. Load an ELF program that imports `strrchr`.
2. Use `Project.hook_symbol` to hook `strrchr` with an arbitrary simproc.
3. Step into `strrchr`'s PLT and observe that the new simproc is not invoked.

**Comment by rhelmot** [comment]
Fixed. This one was a doozy!
