### ISSUE TITLE
How to print a SimAction?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#351]
Hi,
is there an easy way for printing a ```SimAction``` like ```SimActionData```, ```SimActionOperation```?. I'd like to have something: ```tmp write(t0,t1)```

Thanks

**Comment by zardus** [comment]
We have a `__repr__` defined on it (here: https://github.com/angr/simuvex/blob/master/simuvex/s_action.py#L30), but it might not be very helpful. We probably wouldn't be against an improved `__repr__` or `__str__`.

**Comment by ltfish** [comment]
> We probably wouldn't be against an improved __repr__ or __str__.

Correction:  we wouldn't be against an improved `__repr__` or `__str__`.
