### ISSUE TITLE
Obtaint a real value for a temporary VEX variable

### ISSUE THREAD

**Issue by frapik99** [angr/angr#352]
Hi all,
supposed I'm considering the instruction ```STle(t10) = t10``` is it possible to have a concrete value for ```t10``` so i don't to track all the changes?

Thanks

**Comment by ltfish** [comment]
Do you want to obtain the value of `t10` or to give it a custom concrete value during execution?

**Comment by frapik99** [comment]
Hi,
I would like to have the value of ```t10```

Thanks

**Comment by ltfish** [comment]
Assuming `state` is the program state after execution, you can access `state.scratch.temps[10]` to get `t10`.

**Comment by frapik99** [comment]
Perfect thanks
