### ISSUE TITLE
Obtain all states from a path

### ISSUE THREAD

**Issue by frapik99** [angr/angr#354]
Hi,
is it possible to track all the states within a path found using ```pg.explore```? I need to access to the ```temps``` at every state.

If not, suppose I have a VEX instruction like ```t10 = Sub64(t11,0x0000000000000008)``` what would be the best way to calculate the value of ```t10```?

Because I have the cfg I think I might do something like:

```
state = (cfg.get_any_node(address)).final_states[0]

# from now use state.scratch.temps
```

is it wrong? Maybe in some case I don't have a final state? Can I know when please?

Thanks

**Comment by zardus** [comment]
There's currently no ready-to-go option to do this. States *are* kept on the PathHistory objects that on the paths and on the PathHierarchy (pg._hierarchy), but states that yield only one successor are eventually turned into weak references and discarded.

The easiest thing to do short-term is to disable this discarding. This can be accomplished with:

```diff
--- a/angr/path_history.py
+++ b/angr/path_history.pydiff --git a/angr/path_history.py b/angr/path_history.py
index 5043f4f..d634dd6 100644

@@ -131,7 +131,8 @@ class PathHistory(object):
         Demotes this PathHistory node, causing it to convert references to the state
         to weakrefs.
         """
-        self._state_strong_ref = None
+        return
+        #self._state_strong_ref = None
```

After this, you should be able to walk up the path history (path.history._parent._parent._parent and so on) and get the state attribute of each. There's also the `HistoryIter` to help you iterate through histories.

**Comment by frapik99** [comment]
@zardus excellent it seems to work, I'll find to loop through all of them. I would suggest to add an option like ```TRACKE_HISTORY_STATES``` and have ```found.states()``` if possible.

Thanks a lot

**Comment by frapik99** [comment]
Hi,
I have another doubt... Suppose to have this C program:

```
#include<stdlib.h>
#include<stdio.h>
#include<string.h>

int sum(int a, int b) {
        return a+b;
}

int main() {
        int a = 1001;
        short s = 0;
        int x = 0;
        char c[100],d;
        FILE *fd = fopen("nullclang32","rb");

        memset(&c, 0x00, 100);

        fread(c, 2,1, fd);

        c[0] = (4 - c[1] * 7 / 1) | 1;
        int b = sum(c[0],8) * 2;

        if ( b > 5 ) {
                b = 2;
                c[0] = b;
                b = c[0];
                malloc(b);
        }
}
```
I have generated all the states using 

```
for h in list(found.history_iterator):
			s = h.state

			if ( not s == None ):
				states[s.ip.args[0]] = s
```

The problem that when i reach the fopen I have something like:

```
------ IMark(0x1000050, 2, 0) ------
Analysing the instruction 0x1000050L
t3 = GET:I64(offset=16)
t2 = LDle:I8(t3)
```

The problem is that the ```t3``` is not in state.scratch.temps... Can you compile the C code and tell me why please? I guess ```0x1000050L``` is not a right address beacuse if I print the assembly I have:

```
0x1000050:	add	byte ptr [rax], al
0x1000052:	add	byte ptr [rax], al
0x1000054:	add	byte ptr [rax], al
0x1000056:	add	byte ptr [rax], al
0x1000058:	add	byte ptr [rax], al
0x100005a:	add	byte ptr [rax], al
0x100005c:	add	byte ptr [rax], al
0x100005e:	add	byte ptr [rax], al
``` 

Thanks in advance

**Comment by zardus** [comment]
Is this a problem for just the state at that address, or for all states?

**Comment by rhelmot** [comment]
The problem is that that's a SimProcedure address. No reasoning about IRSBs or temps for that step will make sense.

**Comment by frapik99** [comment]
Thanks @zardus and @rhelmot , how do you suggest to avoid to analyse that status once I have already the ```found``` path? Use something like ```is_symprocedure```?

I'll try to create a PR for having the states from the path. If you have a suggestion on how to add a new option and in particular this please let me know.

Thanks

**Comment by rhelmot** [comment]
You can check that an address is a SimProcedure hook by running `project.is_hooked(addr)`. That's the best way to do it.

**Comment by frapik99** [comment]
Thanks a lot @rhelmot , all sorted.

Thanks
