### ISSUE TITLE
some default types alignment raise exceptions

### ISSUE THREAD

**Issue by tharvik** [angr/angr#3551]
when accessing `alignment` of some types definied in `ALL_TYPES`, it raises `TypeError` or `ValueError`.
you can trigger it with
```python
[v.alignment for v in angr.types.ALL_TYPES.values()]
```

the list of currently failings types are:
* `TypeError: '>' not supported between instances of 'NotImplementedType' and 'NotImplementedType'`
  * `$_IO_wide_data`, `__mbstate_t`, `aiocb`, `aiocb64`, `obstack`, `sigevent`, `sigval`
* `ValueError: max() arg is an empty sequence`
  * `$_IO_codecvt`, `_IO_iconv_t`, `_IO_lock_t`, `argp_child`, `argp_state`, `drand48_data`, `random_data`

the `ValueError` is triggered by zero field struct, used when forward declaring some self-referencing types.

**Comment by ltfish** [comment]
I suppose we should ignore all types whose `.alignment` returns NotImplemented?

Assigning this issue to @rhelmot since I am not exactly sure my proposed fix is correct.

**Comment by rhelmot** [comment]
The line you posted will always fail because alignment doesn't mean anything until a type has an arch. I added some logic to raise a more friendly exception when this is the case, and resolved the rest of the issues.
