### ISSUE TITLE
ERROR happends while I am getting CFG gragh for an binary file generated by python under linux

### ISSUE THREAD

**Issue by Lost-little-dinosaur** [angr/angr#3555]
Hi

I am using angr to try to generate a CFG diagram for a binary file generated by python under linux, but I get the following error
![image](https://user-images.githubusercontent.com/82520400/194811872-7659f757-9c07-40ac-95bb-08f3e2f6a02b.png)

here are my code:

```python
import angr
from angrutils import plot_cfg, plot_cg, plot_cdg, plot_dfg

path = "generate"
p = angr.Project(path, load_options={'auto_load_libs': False})

cfg_emulated = p.analyses.CFGEmulated(keep_state=True)
```

I don't now what kind of binary file does angr support to generate CFG gragh, because I can success run this code if I change the file into another file which generated by C languaue under Liunx. That means angr isn't supprt some kind of binary file such as generated by pyhton, although the file's function is very simple (because it's sourse code is just down bellow:

```python
while True:
    a = input("please input：")
    print("you have inputed" + a)

```

**Comment by rhelmot** [comment]
None of those errors are fatal - you should still get a meaningful result out of the analysis.

**Comment by Lost-little-dinosaur** [comment]
Sorry to bothering you, but I just can't get the CFG gragh that I wanted....
It will error out like this after very long running, if these error occurr, angr-utils can't visulise the CFG gragh of my file 
![image](https://user-images.githubusercontent.com/82520400/194987687-d761b64b-51c1-460c-b3e1-82585a8610a7.png)

**Comment by rhelmot** [comment]
That crash is in angrutils, which is not something we maintain. You should take it up with the appropriate maintainers.

**Comment by Lost-little-dinosaur** [comment]
OK, thank you for your answer
