### ISSUE TITLE
How to get CFGBase.normalized if CFGFast instance and CFGEmulated instance not available?

### ISSUE THREAD

**Issue by xrkk** [angr/angr#3578]
### Question

When loading pre-stored project file from disk, cfgs can be accessed through `p.kb.cfgs` which result in `CFGModel` instance, and CFGFast or CFGEmulated instance is no longer available (except performing analyses again, which is not what I want.). But the `normalized` attribute is only available in CFGBase. 

How can I check if cfg is normalized or not through CFGModel? I checked source code and could not find any solution.

**Comment by xrkk** [comment]
Maybe through checking `normalized` attribute of all functions?

**Comment by rhelmot** [comment]
I actually ran into this issue a few day ago. I asked fish about it and got the response that it was an oversight in the refactor that brought us CFGModel and that we should try to move the normalized attribute to CFGModel.
