### ISSUE TITLE
`angr` corrupts log records

### ISSUE THREAD

**Issue by zwimer** [angr/angr#3584]
### Description

`angr` corrupts log records so subsequent log handlers cannot use them cleanly (for example, it injects ascii escape codes to color log output into the log record). It does so here: 
https://github.com/angr/angr/blob/bd89ce4fcf76619c8aeb06d1746ae5939ea5d800/angr/misc/loggers.py#L74 and https://github.com/angr/angr/blob/bd89ce4fcf76619c8aeb06d1746ae5939ea5d800/angr/misc/loggers.py#L79

There are 3 obvious fixes to this:
1. Copy the log record before editing it- the downside is the overhead of a log record copy on each log
2. Convert our custom handler to a custom formatter, do _not_ call `super().format(record)` in it; this removes the ability for users to set custom format strings for the angr logger, unless we roll that ourself.
3. Convert our custom handler to a custom formatter, parse the output of `super().format(record)` and adapt it- this is the wrong option.

I think 2 is ok if the overhead of 1 is worry-some. We already define our own format (which itself does not work). Additionally, if 2 is implemented, `angr` will no longer corrupt records so users can add their own log handlers easily if they desire something special.

### Steps to reproduce the bug

```python
import angr
import logging
logging.getLogger().addHandler(logging.StreamHandler())
logging.getLogger().setLevel(logging.DEBUG)
logging.info("abc")
```

The final line outputs:
```
>>> logging.info("abc")
INFO    | 2022-10-28 17:22:06,680 | root | abc
abc
```

Note that both `abc` strings are colored; which means angr corrupts the log record the stream handler uses.

### Environment

Master: https://github.com/angr/angr/commit/691ec5ec220301be7aabf8650adaeb6cf1006421

**Comment by zwimer** [comment]
@ltfish Do you have any opinions?

**Comment by ltfish** [comment]
> which means angr corrupts the log record the stream handler uses.

I believe this has been the intent of the CuteHandler since the very beginning: It makes all logging messages -- regardless of whether they are generated by angr or not -- colorful and pretty.

So the discussion here should be whether the CuteHandler's behavior is desired or not. To me, I feel it _should_ handle all logging messages.

If we decide CuteHandler should not mess with non-angr logging output, then 2 seems a viable option to me.

**Comment by zwimer** [comment]
In that case, we could also add a 4th option: Corrupt the log record, but by adding previously non-existing fields. That is, instead of editing `record.msg` add `record.colored_msg`.

That said, I think non-corruption via 2 is beneficial; it will allow users to more easily use angr and angr's log infra without having issue using their own log infra.

**Comment by ltfish** [comment]
@rhelmot what do you think?

**Comment by rhelmot** [comment]
`record.colored_msg` is totally acceptable.

**Comment by rhelmot** [comment]
2 is also totally acceptable.

**Comment by twizmwazin** [comment]
I like option 2. I don't think we should be doing really any backend log handling as angr is not a logging library, but if we want some sort of default for cli usage it should be simple and easy to replace with something better if that's what the user wants.
