### ISSUE TITLE
How can I solve with 'jmp  $5'?

### ISSUE THREAD

**Issue by YsielX** [angr/angr#3596]
### Question

angr will parse the 'jmp $5' along with the following block, I want to separate it, just like IDA. 
![屏幕截图 2022-11-05 011528](https://user-images.githubusercontent.com/93875470/200036642-037fdfd4-b5fd-4d78-8847-c6cae471c0ee.png)
What should I do?

**Comment by ltfish** [comment]
An easy solution: Use `block.capstone.insns` to detect the instruction of `jmp $+5`, and then manually limit the size of these blocks to right after the `jmp $+5` instruction when lifting them.

May I ask why this change matters to you?

**Comment by YsielX** [comment]
> An easy solution: Use `block.capstone.insns` to detect the instruction of `jmp $+5`, and then manually limit the size of these blocks to right after the `jmp $+5` instruction when lifting them.
> 
> May I ask why this change matters to you?

But the step() function of the angr simulator still cannot use jmp $+5 as a breakpoint. How should I solve this problem?

I'm using angr to handle a class of variants of ollvm - control flow flattening, and its relevant nodes are not limited to pre-distribute nodes, so need to be added manually.

**Comment by ltfish** [comment]
I feel you can definitely solve control-flow flattening without forcing block breaks at `jmp $+5`. It should not matter for your analysis.

> But the step() function of the angr simulator still cannot use jmp $+5 as a breakpoint. How should I solve this problem?

You can add the logic that I mentioned at https://github.com/angr/angr/blob/6e9e6a0cc8d3d1ffc1431fac8b3f3bed187897c9/angr/engines/vex/lifter.py#L240. It will ensure `jmp $+5` will always end a block.

**Comment by YsielX** [comment]
> I feel you can definitely solve control-flow flattening without forcing block breaks at `jmp $+5`. It should not matter for your analysis.

Sure, but it's the most convenient way to do it I can think of.
> > But the step() function of the angr simulator still cannot use jmp $+5 as a breakpoint. How should I solve this problem?
> 
> You can add the logic that I mentioned at
> 
> https://github.com/angr/angr/blob/6e9e6a0cc8d3d1ffc1431fac8b3f3bed187897c9/angr/engines/vex/lifter.py#L240
> . It will ensure `jmp $+5` will always end a block.

okey,I'll try
