### ISSUE TITLE
Angr disassembly gets confused after malloc 

### ISSUE THREAD

**Issue by abduqasem** [angr/angr#3599]
### Description

Hello,
I come across the following example (as I show in the figures); from the figures, we can see that angr disassembly miss reverses the sample while ghidra successfully.
the two inputs to strcat, angr treat them as the same parameters (point to the same locations). I think this happens because of the effects of malloc.
My question is, how can I address this issue with angr. My current implementation depends on angr.
![angr](https://user-images.githubusercontent.com/47875913/200095700-40ad5716-29b4-4e86-812f-e57509d96d1a.png)
![gidra](https://user-images.githubusercontent.com/47875913/200095702-96898c57-a644-4943-b74f-2bc677cf8a9a.png)

[mips_snprintf.zip](https://github.com/angr/angr/files/9942720/mips_snprintf.zip)

### Steps to reproduce the bug

[mips_snprintf.zip](https://github.com/angr/angr/files/9942722/mips_snprintf.zip)
[display.zip](https://github.com/angr/angr/files/9942731/display.zip)

**Comment by ltfish** [comment]
It's the same bug reported in https://github.com/angr/angr/issues/3403. I'm working on it.

**Comment by ltfish** [comment]
@abduqasem Can you please confirm that the [linked PR](https://github.com/angr/angr/pull/3600) fixes your issue?

**Comment by abduqasem** [comment]
hello @ltfish 
Unfortunately, it does not fix it yet.
from the figure at address 0x4007c4, we can see that, you manage to address the a0 register, but you eliminate a1 register. strcat function receive two inputs(a0, a1). in your new fix, there is no existence for a1
![01](https://user-images.githubusercontent.com/47875913/200097923-e6c1ed80-16e3-4837-86c6-deb9162e9b92.png)

**Comment by abduqasem** [comment]
Sorry @ltfish 
you have fixed the issue. Because you added a new block, i get confused because it is no longer synchronized with ghidra, which is not a problem.

one more think, when I used you new fix,
ModuleNotFoundError: No module named 'angr.storage.memory_mixins.paged_memory.pages.multi_values
which I need it for RDA
