### ISSUE TITLE
Performance / CPU load

### ISSUE THREAD

**Issue by gitttt** [angr/angr#36]
I am running angr in an Ubuntu vmware virtual machine. When I do CPU-intensive tasks, e.g. CFG creation, the CPU load stays between 52 and 54%. I have two CPUs configured for the VM and I would like to let the CPU load go higher than those 54%. Unfortunately, I couldn't find a configuration option to achieve this. Is there a way to allow angr use more CPU?

**Comment by ltfish** [comment]
Currently angr only utilizes a single CPU core :-(

With some improvements of the CFG generation algorithm, I think I can eventually parallelize the CFG creation. It won't happen soon, but it will arrive some time in the near future.

**Comment by riyadparvez** [comment]
Are you considering a portfolio SMT solver?

**Comment by ltfish** [comment]
@riyadparvez Thanks for the prompt. I have never heard of the term "portfolio SMT solver" before. Will read the paper and see if we can use it.

**Comment by riyadparvez** [comment]
@ltfish S2E team has done some benchmarking with both portfolio and incremental version Z3 solver. You can read the blog post: http://dslab.epfl.ch/blog/2015/07/26/encoding-symbolic-expressions.html

**Comment by ltfish** [comment]
@riyadparvez Perfect :-)

**Comment by dgutson** [comment]
Was there any update about creating the CFG in parallel?
