### ISSUE TITLE
_handle_CmpLT in SimEngineLightVEXMixin did some <= comparision?

### ISSUE THREAD

**Issue by xrkk** [angr/angr#3603]
### Question

As handler of `CmpLT` in class SimEngineLightVEXMixin (in `angr/engines/light/engine.py`), the code did some `expr_0 <= expr_1` operation. I didn't find any documentation about this. Is it correct?

```py
    def _handle_CmpLT(self, expr):
        args, r = self._binop_get_args(expr)
        if args is None: return r
        expr_0, expr_1 = args

        if self._is_top(expr_0) or self._is_top(expr_1):
            return self._top(1)

        return expr_0 <= expr_1
```

**Comment by ltfish** [comment]
It's a bug! Thanks for catching it.
