### ISSUE TITLE
Bug in SimEngineRDVEX: Some memory stores are ignored

### ISSUE THREAD

**Issue by 3553x** [angr/angr#3623]
### Description

The `if.. elif` construct for handling stores fails to consider addresses which are bitvectors. As a result such stores are ignored and this results in an incomplete dependency graph.

### Steps to reproduce the bug

This binary can be used to reproduce the issue (I compiled it without PIE):
```c
#include <stdio.h>

int global_int = 0;

void main(int argc, char** argv) {
	global_int++;
	return;
}
```

Here is the python script:
```python
#!/usr/bin/env python3
import angr
import angr.analyses.reaching_definitions.dep_graph as dep_graph

path = "/home/schlaf/angr-dev/angr/bug/test_binary"
p = angr.Project(path, auto_load_libs=False)

cfg = p.analyses.CFGFast()

main_fun_addr = 0x00401106
main_fun = cfg.functions.get_by_addr(main_fun_addr)

d = dep_graph.DepGraph()

rd = p.analyses.ReachingDefinitions(subject=main_fun, dep_graph=d, track_calls=True)

graph = d.graph
for e in graph.edges:
    print(e)
```

You can see that an edge, which represents the store to `global_int` is missing.
If we fix this, then `(<Definition {Atom:<Reg 16<8>>, Codeloc:<0x401117 id=0x401106[38] contextless>}>, <Definition {Atom:<Mem 0x404014<4>>, Codeloc:<0x40111a id=0x401106[43] contextless>}>)` appears.

I will open a pull request soon.

### Environment

Your report script does not work for some reason. I confirmed this bug in an angr-dev environment. The last commit on angr is: 71987233ff3fdbb3fa404970a7a56057cbb9ec0d from Nov 7th.

**Comment by ltfish** [comment]
Sorry that it took me a while before I got the time and energy to sit down and think through the problem. Your fix is definitely right. I've never seen this case because I was only testing the AIL engine of RDA.

Thank you for the fix!
