### ISSUE TITLE
How do you activate the PCode lifter when loading a project?

### ISSUE THREAD

**Issue by br0kej** [angr/angr#3629]
### Question

Hey Folks,

I have installed the most recent version of `angr` and have been experimenting with it. Awesome so far!

I would like to experiment with the PCode lifting and then symbolic execution over it but can't seem to find any reference to the Pcode engines within the `9.2.26` docs site.

How do I go about setting this up?

**Comment by mborgerson** [comment]
Check out the tests: https://github.com/angr/angr/blob/9eee067cb87d2342b7df882800dede311dacf822/tests/engines/pcode/test_pcode.py#L23
