### ISSUE TITLE
How to list all the functions in a .so file.

### ISSUE THREAD

**Issue by frapik99** [angr/angr#363]
Hi,
I have loaded a ```.so``` file doing something like:

```
lib = cle.Loader("lib.so")
so = lib.shared_objects["anotherlib.so.16"]
```

Now i can print the functions exported by the ```.so``` using ```so.plt``` but I don't see all of them but only those marked as ```T``` by ```nm``` and not marked as ```t``` can I know why? How can I obtain all of them?

Thanks

**Comment by rhelmot** [comment]
This information can be found here: http://angr.io/api-doc/cle.html#cle.backends.Backend

You are working with ELF files, so you can use any of the attributes under `Backend`, `MetaELF`, or `ELF`. In this case you probably want `symbols_by_addr`. Keep in mind that this will include non-function symbols as well.
