### ISSUE TITLE
Tracer exploration technique changes ip addresses of old states

### ISSUE THREAD

**Issue by lks9** [angr/angr#3635]
### Description

The Tracer exploration manager seems to change the ip of a state

```python
t = angr.exploration_techniques.Tracer(trace)
simgr.use_technique(t)
state0 = simgr.active[0]
state0.ip  # returns <BV64 0x400580>
simgr.run()
state0.ip  # returns <BV64 0x721dd0>
```

See below for the full example

### Steps to reproduce the bug

Run the following and observe that the reported ip changes.

```python
import os
import angr
import tracer

filename = "binaries/tests/x86_64/fauxware"
p = angr.Project(filename)

stdin=b"A" * 18
try:
    ld_linux = p.loader.linux_loader_object.binary
except:
    ld_linux = None

runner = tracer.QEMURunner(
    project=p,
    input=stdin,
    ld_linux=ld_linux,
    library_path=set(
            os.path.dirname(obj.binary) for obj in p.loader.all_elf_objects
    ),
    record_stdout=True,
)

# now trace it...
trace = runner.trace

s = p.factory.full_init_state(
    mode="tracing",
    stdin=angr.SimFileStream,
    remove_options={angr.options.CPUID_SYMBOLIC},
)
s.preconstrainer.preconstrain_file(stdin, s.posix.stdin, True)

simgr = p.factory.simulation_manager(
    s, hierarchy=None,
)
t = angr.exploration_techniques.Tracer(trace)
simgr.use_technique(t)
# simgr.use_technique(angr.exploration_techniques.Oppologist())

state0 = simgr.active[0]

print(state0.ip)

simgr.run()

print(state0.ip)  # prints a different value!
```

I also filed a pull request #3636 for the test.

### Environment

https://github.com/angr/tracer needs to be installed

### Additional context

I wanted to understand the input format of `angr.exploration_techniques.Tracer(trace)`, which is undocumented. By looking into the `test_tracer.py` I noticed that it is a list of instruction addresses. But then I stumbled upon this.

**Comment by ltfish** [comment]
I think this is the expected behavior. To get a better speed, tracer does not make any copies of states during tracing. Rather, it reuses the existing state.

If you want to make sure the initial state is not changed during tracing, please initialize Tracer using a copy of the state: `state.copy()`.

**Comment by lks9** [comment]
Thanks!
