### ISSUE TITLE
Paths in shared objects

### ISSUE THREAD

**Issue by frapik99** [angr/angr#364]
Hi,
I'm trying to understand how well angr can create paths for executable that are calling functions that are within ```.so``` file. Let's suppose my executable uses ```lib.so```. I'm able to generate the path between the beginning of the executable ( ```main``` function ) and the function ```A``` that is part of ```lib.so```. However,  ```A``` calls ```A1``` and ```A2``` but in the path I cannot see the call to them... How is it that possible? maybe because I'm passing the option ```auto_load_libs``` to ```False```?

Thanks

**Comment by rhelmot** [comment]
There is no fundamental difference between how angr processes shared objects versus executable files. It is possible that auto_load_libs=False has impacted your analysis, but only if your execution would need to go through an imported function.

This issue is extremely vague, and as such we can't really help you. My only advice is that angr is a processor emulator. If you think there is a problem with how emulation is happening, you should look at the path trace and follow along with it in a disassembler and see where what you expect to happen diverges from what actually happens, and why this is. This is a general technique that you should apply to debugging problems with angr before submitting issues.

**Comment by frapik99** [comment]
Hi @rhelmot , yes I need to go through the imported function as well. So I think my solution would be to set ```auto_load_libs``` to ```True``` the negative impact would be the performance for sure... Is there a way to consider only a specific ```so``` rather than all of them? If I want to consider only ```mylib.so``` how should I do it?

Thanks

**Comment by frapik99** [comment]
In reality I'm mainly interested to load a ```so``` "call" a function a follow the execution...

**Comment by rhelmot** [comment]
That's a pretty good question. I think the best way to do that would be to set `auto_load_libs=True` and then for every function you *don't* want to step into, use `hook_symbol` to stub it out with `simuvex.Procecures['stubs']['ReturnUnconstrained'], or whatever else is appropriate.

**Comment by frapik99** [comment]
Thanks @rhelmot , I'll try to load everything with ```auto_load_libs``` to ```True``` and see if it works.

At the moment with the debug on I can see that all stuck during the loading... If it happens again I'll open another issue :)

Thanks

**Comment by frapik99** [comment]
@rhelmot Is there a way to know the function that is considered at the moment so, after, I can decide to add ```hook_symbol``` or not? I'll try to clarify my self: supposed that the project used ```a.so``` and ```b.so```and I want to use ```hook_symbol``` for all the functions that are part of ```a.so``` except few of them so I would like to "follow the flow" and mark on a paper which functions are called and only later use ```hook_symbol``` on them. Is it possible?

Thanks

**Comment by rhelmot** [comment]
Yes, that is possible, and yes, that will do about the same as `auto_load_libs=False`.

You ought to experiment with these things yourself before asking questions about them!

**Comment by frapik99** [comment]
@rhelmot I edited the post after so I wasn't able to show my experiment in the first place. Even if I try with that loop the ```CFGAccurate``` takes forever and all the RAM is eaten, I think I'm missing something else.

Thanks

**Comment by frapik99** [comment]
Hi,
I have done some experiment with ```pngpixel``` checking all the paths using ```pg.step()``` and manually checking ```pg.active```. The problem is that when the ```pg``` encounters ```png_create_read_struct``` it generates an incredible number of paths and it "stays there". I would like to understand the best approach to avoid this condition and continue until the ```png_malloc```. Should I create a SimProcedure for ```png_create_read_struct```?

Thanks again

**Comment by rhelmot** [comment]
Yes.
