### ISSUE TITLE
CFG generation is really slow sometimes on binaries with many indirect jumps

### ISSUE THREAD

**Issue by xxr0ss** [angr/angr#3667]
### Description

Since commit 61090316d8a81751903cb8c2d7cb0456f9d1d99a (I've tested this commit and an early one), It seems the process cfg get generated is switched to a new one. And you can see many ERRORs in logs:
```
ERROR    | 2022-12-15 15:17:24,516 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop XXX
```

For certain binaries, it's getting really slow to generate CFG. In my case, a 1.5MB binary took 6 minute.
```
ERROR    | 2022-12-15 16:38:41,437 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_64HLtoV128.
# ... a lot of ERRORs
ERROR    | 2022-12-15 16:49:48,406 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Binop Iop_MullS32.
done after 369.8980860710144s
```

### Steps to reproduce the bug

```python
import angr
import logging
import time

logging.getLogger('pyvex.lifting.libvex').setLevel(logging.ERROR)

project = angr.Project(
    './lib.so',
    load_options={'auto_load_libs': False}
)

start_time = time.time()
print('generating cfg')
cfg = project.analyses.CFGFast(normalize=True, force_complete_scan=False)

print(f'done after {time.time() - start_time}s')
```

A sample arm64 binary:
[lib.zip](https://github.com/angr/angr/files/10235256/lib.zip)

### Environment

No problem, within 1 minutes: before 72077cac9c9aff89e078b81d7b19c6bb8604f9d3
Logged errors, over 4 minutes: since 61090316d8a81751903cb8c2d7cb0456f9d1d99a

**Comment by xxr0ss** [comment]
When using AM, setting "resolve indirect jump" in "Control-Flow Graph Recovery" disabled would make it much faster.

**Comment by ltfish** [comment]
While we should get rid of these unsupported ops (by supporting them), I am not entire sure that they are the cause of slow CFG recovery. I'll need to debug CFG recovery on your binary to see why it's slow.

Also, 6 minutes is not that slow on a 1.5 MB ARM binary, tbh.

**Comment by xxr0ss** [comment]
I see @ltfish. I just had a rough test again to get comparison result on another computer:

older: within 1 minute,  newer: over 4 minute

For convinience this time I just installed angr 9.2.25 and 9.2.29 from pypi. This result should be close to before & after commit https://github.com/angr/angr/commit/61090316d8a81751903cb8c2d7cb0456f9d1d99a.

**Comment by ltfish** [comment]
Oh great. I've been looking for extreme cases where that PR would significantly increase the CFG building time. I'll improve the performance soon.

**Comment by ltfish** [comment]
```
ipdb> pp cfg.jump_tables
{5016632: <IndirectJump 0x4c8c38 - ins 0x4c8c4c jumptable@0x52ee60 with 13 entries>,
 5017376: <IndirectJump 0x4c8f20 - ins 0x4c8f2c jumptable@0x52ee70 with 5 entries>,
 5079388: <IndirectJump 0x4d815c - ins 0x4d816c jumptable@0x52f010 with 5 entries>,
 5080832: <IndirectJump 0x4d8700 - ins 0x4d8710 jumptable@0x52f018 with 5 entries>,
 5220000: <IndirectJump 0x4fa6a0 - ins 0x4fa6b0 jumptable@0x5301f4 with 5 entries>,
 5221820: <IndirectJump 0x4fadbc - ins 0x4fadcc jumptable@0x5301fc with 5 entries>,
 5269348: <IndirectJump 0x506764 - ins 0x506778 jumptable@0x530734 with 4 entries>,
 5324276: <IndirectJump 0x513df4 - ins 0x513e00 jumptable@0x5318a8 with 4 entries>,
 5324872: <IndirectJump 0x514048 - ins 0x514054 jumptable@0x5318ac with 4 entries>,
 5367740: <IndirectJump 0x51e7bc - ins 0x51e7d0 jumptable@0x53213c with 76 entries>,
 5369180: <IndirectJump 0x51ed5c - ins 0x51ed68 jumptable@0x532188 with 76 entries>,
 5369784: <IndirectJump 0x51efb8 - ins 0x51efc4 jumptable@0x5321d4 with 76 entries>,
 5371980: <IndirectJump 0x51f84c - ins 0x51f858 jumptable@0x532220 with 16 entries>,
 5386804: <IndirectJump 0x523234 - ins 0x523248 jumptable@0x532398 with 5 entries>,
 5387064: <IndirectJump 0x523338 - ins 0x52334c jumptable@0x5323a0 with 13 entries>,
 5388928: <IndirectJump 0x523a80 - ins 0x523a94 jumptable@0x5323b0 with 50 entries>,
 5391168: <IndirectJump 0x524340 - ins 0x524354 jumptable@0x53244c with 4 entries>,
 5391300: <IndirectJump 0x5243c4 - ins 0x5243d8 jumptable@0x532450 with 4 entries>,
 5393500: <IndirectJump 0x524c5c - ins 0x524c70 jumptable@0x532454 with 4 entries>,
 5398044: <IndirectJump 0x525e1c - ins 0x525e30 jumptable@0x532480 with 4 entries>,
 5421124: <IndirectJump 0x52b844 - ins 0x52b850 jumptable@0x5325a8 with 19 entries>,
 5423784: <IndirectJump 0x52c2a8 - ins 0x52c2bc jumptable@0x532ffc with 60 entries>}
```

With PR 3824, it takes 18 seconds on my laptop.

**Comment by ltfish** [comment]
Thank you for providing the binary - What's the license of this binary? Can we use it as a test case for angr CI?

**Comment by xxr0ss** [comment]
Thank you for this PR @ltfish! It's much faster!

> What's the license of this binary? Can we use it as a test case for angr CI?
I'm glad that the binary helps, but sorry that I'm not quite sure about that.

I do find that, on any random arm64 binaries I tested, this PR has an average of  2x-5x speedup.
[android_libs.zip](https://github.com/angr/angr/files/10790548/android_libs.zip)
