### ISSUE TITLE
Different disassembly results between block.pp() and arm-none-eabi-objdump

### ISSUE THREAD

**Issue by B03901108** [angr/angr#3668]
### Description

In harness.py, I used angr to load an ARM elf (Drone.elf) and pretty-print the assembly of its entry block. It gave
```Reset_Handler:
8004f45 lsls r1, r4, #0xc
8004f47 lsrs r0, r4, #0xf
```

However, when I used "arm-none-eabi-objdump -D Drone.elf >Drone.objdump.disasm" to disassemble the elf file, the entry became

```08004f44 <Reset_Handler>:
8004f44: 2100 movs r1, #0
8004f46: e003 b.n 8004f50 <LoopCopyDataInit>
```

I tried to figure out the reason with the following capstone code:
```
from capstone import *
cs = Cs(CS_ARCH_ARM, CS_MODE_MCLASS | CS_MODE_THUMB)
with open('./Drone.bin', 'rb') as f: binCode = f.read()
for i in cs.disasm(binCode[ 0x4f44 : 0x4f48 ], 0x8004f44):
  print('0x%x:\t%s\t%s' % (i.address, i.mnemonic, i.op_str))
for i in cs.disasm(binCode[ 0x4f45 : 0x4f49 ], 0x8004f45):
  print('0x%x:\t%s\t%s' % (i.address, i.mnemonic, i.op_str))
```

The above prints out

```0x8004f44: movs r1, #0
0x8004f46: b #0x8004f50
0x8004f45: lsls r1, r4, #0xc
0x8004f47: lsrs r0, r4, #0xf
```

Therefore, I wonder if angr did not notice that the oddity of the entry address is to denote the THUMB mode, and if angr directly used 0x8004f45 as the literal entry address.

### Steps to reproduce the bug

The attached zip file contains the tested elf file (Drone.elf), its bin file (Drone.bin), the objdump results (Drone.objdump.disasm), and my angr Python script (harness.py).
[test_Drone_elf.zip](https://github.com/angr/angr/files/10242321/test_Drone_elf.zip)

### Environment

Ubuntu 18.04.6 LTS
Python 3.8.0
angr 9.2.28
capstone 5.0.0
unicorn 2.0.1.post1

### Additional context

The angr slack channel (help) has some discussions about this issue. Although the elf file is for ARM Cortex-M, and this was not specified in the angr project constructor, project.arch still showed <Arch ARMCortexM (LE)>. Also, specifying arch='cortex-m' did not resolve the issue.

**Comment by B03901108** [comment]
In the slack discussions, some found that
1) state.block().disassembly.pp() gives the correct results, and
2) a pull request (https://github.com/angr/angr/pull/3619) seems like a fix to this issue.

**Comment by ltfish** [comment]
#3619 has been merged. Can you please verify if this issue has been fixed?

Sorry that this bug has been around for so long.

**Comment by MustBastani** [comment]
#3619 hasn't fixed the issue. `block.pp()` uses `analyses.Disassembly` with `ranges` ([here](https://github.com/angr/angr/blob/master/angr/block.py#L260)), and Disassembly analysis creates a new block for each of the ranges. The new block doesn't keep THUMB-ness of the original block ([here](https://github.com/angr/angr/blob/master/angr/analyses/disassembly.py#L1009)).

`block.disassembly.pp()` gives the correct results.

**Comment by ltfish** [comment]
@MustBastani I just tried the original script and it printed out the expected output. It seems to me that #3619 adjusted how `addr` is calculated before passing it to `analyses.Disassembly` in `ranges`. Can you try it again with the most recent angr on the master branch?

**Comment by MustBastani** [comment]
Sorry that I forgot to mention that #3619 adjusted address calculation correctly, and now, the original script prints the expected output. But it is still possible to get different disassembly results using pretty print method because of the issue mentioned in my previous comment. For example:
```Python
import angr
print(angr.__version__)  # 9.2.32.dev0
proj = angr.Project("Drone.elf", arch="cortex-m")
cfg = proj.analyses.CFGEmulated(keep_state=True, starts=[0x08004f45], call_depth=0)
f = cfg.kb.functions.get_by_addr(0x08004f45)
b = f.get_block(0x08004f45)
for block in f.blocks:
    print(block)
## List of blocks:
# <Block for 0x8004f45, 4 bytes>
# <Block for 0x8004f51, 10 bytes>
# <Block for 0x8004f49, 18 bytes>
# <Block for 0x8004f5b, 4 bytes>
# <Block for 0x8004f65, 6 bytes>
# <Block for 0x8004f5f, 12 bytes>
# <Block for 0x8004f6b, 4 bytes>
# <Block for 0x8004f6f, 4 bytes>
# <Block for 0x8004f73, 4 bytes>
# <Block for 0x8004f77, 2 bytes>
```
The output of `b.pp()`:
```
         Reset_Handler:
8004f45  lsls    r1, r4, #0xc
```
The output of `b.disassembly.pp()`:
```
0x8004f45:      movs    r1, #0
0x8004f47:      b       #0x8004f51
```
I also tried this:
```Python
b = f.get_block(0x08004f44)
print(b.thumb)  # False
b.pp()
#          Reset_Handler:
# 8004f45  movs    r1, #0x0
# 8004f47  b       #0x8004f51
# 
# 8004f49  ldrh    r3, [r1, r5]
```
which is wrong in a different way. The block at `8004f47` disassembled correctly but it shouldn't print the next block at `8004f49`. Also the block at `8004f49` dissasembled incorrectly (should be `ldr     r3, [pc, #0x2c]`).

The output of `b.disassembly.pp()`:
```
0x8004f44:      movs    r1, #0
0x8004f46:      b       #0x8004f50
0x8004f48:      ldr     r3, [pc, #0x2c]
0x8004f4a:      ldr     r3, [r3, r1]
```

**Comment by ltfish** [comment]
@MustBastani Can you please try PR #3694?

**Comment by ltfish** [comment]
The bug is fixed for me. Please reopen the issue if the bug still persists for you. Thanks!
