### ISSUE TITLE
How angr handles the alignment instructions

### ISSUE THREAD

**Issue by bluesadi** [angr/angr#3678]
### Question

I had a function in a Thumb binary at addr 0x40050C

![image](https://user-images.githubusercontent.com/35004522/208851305-b5103d1c-6a0f-41a2-87ba-0ee6b1ec3344.png)

I printed all function addresses using the code below:
```py
import angr

proj = angr.Project('test', load_options={'auto_load_libs': False})
cfg = proj.analyses.CFGFast()
funcs = [hex(funcaddr) for funcaddr in cfg.kb.functions]
print(funcs)
```
Output:
```
[... '0x40050b', '0x40050d' ...]
```
That's kind of confusing because I know '0x40050d' is the original address plus the offset (0x1) in Thumb mode, but I don't quite understand why '0x40050b' also counts as a function address.

When I printed the IRSB at 0x40050b, the entry instruction `PUT(pc) = 0x0040050d` also baffles me.
```py
print(proj.factory.block(0x40050b).vex)
```

Output:
```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I32 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I32 t15:Ity_I32 t16:Ity_I32 t17:Ity_I32 t18:Ity_I32 t19:Ity_I32 t20:Ity_I32 t21:Ity_I1 t22:Ity_I1 t23:Ity_I32 t24:Ity_I32 t25:Ity_I32 t26:Ity_I32 t27:Ity_I32 t28:Ity_I32 t29:Ity_I32 t30:Ity_I32 t31:Ity_I32 t32:Ity_I32 t33:Ity_I1 t34:Ity_I32 t35:Ity_I32 t36:Ity_I32 t37:Ity_I1 t38:Ity_I32 t39:Ity_I32 t40:Ity_I32 t41:Ity_I32 t42:Ity_I1 t43:Ity_I32 t44:Ity_I32 t45:Ity_I1 t46:Ity_I1 t47:Ity_I1 t48:Ity_I1 t49:Ity_I32 t50:Ity_I32

   00 | ------ IMark(0x40050a, 2, 1) ------
   01 | PUT(pc) = 0x0040050d
   02 | ------ IMark(0x40050c, 2, 1) ------
   03 | t24 = GET:I32(sp)
   04 | t23 = Sub32(t24,0x00000008)
   05 | PUT(sp) = t23
   06 | t5 = And32(t23,0xfffffffc)
   07 | t26 = GET:I32(r7)
   08 | STle(t5) = t26
   09 | t27 = Add32(t5,0x00000004)
   10 | t28 = GET:I32(lr)
   11 | STle(t27) = t28
   12 | ------ IMark(0x40050e, 2, 1) ------
   13 | PUT(r7) = t23
   14 | PUT(pc) = 0x00400511
   15 | ------ IMark(0x400510, 2, 1) ------
   16 | t50 = LDle:I32(0x00400520)
   17 | ------ IMark(0x400512, 2, 1) ------
   18 | t38 = Add32(t50,0x00400516)
   19 | PUT(r3) = t38
   20 | ------ IMark(0x400514, 2, 1) ------
   21 | PUT(r0) = t38
   22 | ------ IMark(0x400516, 4, 1) ------
   23 | PUT(itstate) = 0x00000000
   24 | PUT(lr) = 0x0040051b
   NEXT: PUT(pc) = 0x004003cc; Ijk_Call
}
```

It may influence results of some static analyses, so I am writing to ask why 0x40050b counts as a function/node address, and the purpose of the fake instruction at `IMark(0x40050a, 2, 1)`.

[test.zip](https://github.com/angr/angr/files/10275853/test.zip)

**Comment by ltfish** [comment]
In angr, all THUMB code is at odd addresses while ARM code is at even addresses. So for THUMB blocks and functions that you see in IDA, add 1 to their addresses when using in angr.

**Comment by ltfish** [comment]
Also `IMark(0x40050a, 2, 1)` is not a "fake instruction." It's an "instruction marker" that indicates the beginning of the instruction (in this case, 0x40050a + 1) and the size of the instruction (in this case, 2).

**Comment by bluesadi** [comment]
Yes. I understood that '0x40050d' is 0x40050c (as shown in IDA) plus one, but I don't understand the meaning of 0x40050b.

And sorry about the confusing. I meant `01 | PUT(pc) = 0x0040050d` by "fake instruction", because it doesn't exist in IDA's decompiling results.

**Comment by ltfish** [comment]
> Yes. I understood that '0x40050d' is 0x40050c (as shown in IDA) plus one, but I don't understand the meaning of 0x40050b.

ARM uses the last bit of an address to indicate the mode (0 for ARM and 1 for THUMB). angr simply respects that while IDA uses a separate virtual register (called T register iirc) to record if an address should be in ARM mode or THUMB mode.

> And sorry about the confusion. By "fake instruction", I meant the `01 | PUT(pc) = 0x0040050d` instruction at addr `0x40050a`, because it doesn't exist in IDA's decompiling results.

Note that VEX's IR is side-effect free, which means *all* effects of an instruction are explicitly expressed in VEX statements.

Maybe you are wondering why the first instruction at 0x40050b modifies pc to 0x40050d, and the following instructions no longer modify pc. This is because of libVEX's optimization (and I have no idea why it does not optimize away the first PUT(pc) statement). You can lift the block with `opt_level=0` and see what the original, unoptimized block looks like. In the unoptimized VEX block, I believe every instruction will be updating pc.

**Comment by bluesadi** [comment]
Thanks for your detailed explanations! Maybe I still didn’t state my main point clearly.

0x40050d corresponds to the address of function test1 in IDA (0x50C), while 0x40050b (corresponding to 0x50a in IDA, as shown in the very first picture) is not the address of any block or function.

My main question is, why angr identifies 0x40050b as a function. Had the address discarded from the function list, seemingly the CFG would still be correct.

**Comment by ltfish** [comment]
Oh!

I think it's because IDA identifies the alignment instruction at 0x40050a and excluded it from the function body while angr's CFG recovery failed to do so. The logic is implemented [here](https://github.com/angr/angr/blob/2e627c88fc89e52984229b08c3f1ebc023dfcc2d/angr/analyses/cfg/cfg_base.py#L1306).

Is this function not called by anything else in the same binary?

**Comment by bluesadi** [comment]
No. The predessors of 0x40050b is an empty list. In contrast, 0x40050d has two predecessors. 

Thanks! I will take a look at the implementation :)

**Comment by ltfish** [comment]
So the problem must be that angr's CFG recovery failed to identify the alignment instruction in this case. Given that 0x40050a is not 16-byte or 8-byte aligned, we probably did not even try to identify alignment instructions at the beginning of this function.

**Comment by bluesadi** [comment]
I see. It seems not a serious problem. If you don’t have any recent plans to fix it (within a few months), I can try to fix it.

**Comment by ltfish** [comment]
Oh!

You'll want to get all functions whose `.alignment` is False :)
