### ISSUE TITLE
install angr on mac os

### ISSUE THREAD

**Issue by PatchDiscovery** [angr/angr#3679]
### Question

I tried to install angr on mac os.
After installing angr, I followed the instructions to execute the following lines:
```
PYVEX=`python3 -c 'import pyvex; print(pyvex.__path__[0])'`
UNICORN=`python3 -c 'import unicorn; print(unicorn.__path__[0])'`
ANGR=`python3 -c 'import angr; print(angr.__path__[0])'`
```
a mistake occured.

`WARNING | 2022-12-21 23:05:44,209 | angr.state_plugins.unicorn_engine | failed loading "angr_native.dylib", unicorn support disabled (dlopen(/Users/xx/opt/anaconda3/envs/python37/lib/python3.7/site-packages/angr/lib/angr_native.dylib, 0x0006): Library not loaded: @rpath/libunicorn.1.dylib
  ...
`
But I make sure that unicorn has already installed.

How to solve the problem?

**Comment by rhelmot** [comment]
are you following the instructions at https://docs.angr.io/introductory-errata/install#mac-os-x ? The instructions there are designed to get rid of that warning when you finish them.

**Comment by PatchDiscovery** [comment]
> are you following the instructions at https://docs.angr.io/introductory-errata/install#mac-os-x ? The instructions there are designed to get rid of that warning when you finish them.

Yes. I first used `pip3 install unicorn==` to install unicorn and then install angr.

**Comment by rhelmot** [comment]
You need to run the rest of the commands from that section. They will get rid of that warning.

**Comment by PatchDiscovery** [comment]
> You need to run the rest of the commands from that section. They will get rid of that warning.

I  ran the all the following lines,

`PYVEX=`python3 -c 'import pyvex; print(pyvex.__path__[0])'`
UNICORN=`python3 -c 'import unicorn; print(unicorn.__path__[0])'`
ANGR=`python3 -c 'import angr; print(angr.__path__[0])'`

install_name_tool -change libunicorn.1.dylib "$UNICORN"/lib/libunicorn.dylib "$ANGR"/lib/angr_native.dylib
install_name_tool -change libpyvex.dylib "$PYVEX"/lib/libpyvex.dylib "$ANGR"/lib/angr_native.dylib`

But the warning  still exists.

**Comment by rhelmot** [comment]
Did those lines, perhaps, show some errors themselves?

**Comment by PatchDiscovery** [comment]
When running the third line`ANGR=`python3 -c 'import angr; print(angr.__path__[0])'``， the warning showed `WARNING | 2022-12-21 23:05:44,209 | angr.state_plugins.unicorn_engine ...`. Except it, there were other errors when ran the all lines.

**Comment by rhelmot** [comment]
can someone else who knows anything about macos please chime in? I suspect the problem is about libunicorn.1.dylib vs libunicorn.2.dylib but I have no way to test or verify anything.

**Comment by ltfish** [comment]
Can you run this command:
```
python3 -c 'import unicorn; print(unicorn.__path__[0])'
```
and post the output?

**Comment by PatchDiscovery** [comment]
> python3 -c 'import unicorn; print(unicorn.__path__[0])'
The output is:
`/Users/xx/opt/anaconda3/envs/python37/lib/python3.7/site-packages/unicorn`

**Comment by ltfish** [comment]
Can you run this command and post the output:

```
python3 -c "from unicorn import unicorn as uc; print(uc._uc)"
```

**Comment by PatchDiscovery** [comment]
> python3 -c "from unicorn import unicorn as uc; print(uc._uc)"

`<CDLL` 'libunicorn.dylib', handle 7ff908324af0 at 0x7fad1e0ccf90>`

**Comment by ltfish** [comment]
Gah it does not give you the full path :/ 

How about the following command:

```
python3 -c "from unicorn import unicorn as uc; print(uc._path)"
```

**Comment by ltfish** [comment]
(I've never tried to install angr in an anaconda environment on MacOS, and I do not have any devices for me to do so...)

**Comment by PatchDiscovery** [comment]
> Gah it does not give you the full path :/
> 
> How about the following command:
> 
> ```
> python3 -c "from unicorn import unicorn as uc; print(uc._path)"
> ```

there was no output when running the command.

**Comment by ltfish** [comment]
Amazing, so it's the global load... can you see where `libunicorn.dylib` is in your virtual environment? It's probably somewhere inside `/Users/xx/opt/anaconda3/envs/python37/lib/python3.7/site-packages/unicorn`. Please post the full path to the library here.

**Comment by PatchDiscovery** [comment]
> Amazing, so it's the global load... can you see where `libunicorn.dylib` is in your virtual environment? It's probably somewhere inside `/Users/xx/opt/anaconda3/envs/python37/lib/python3.7/site-packages/unicorn`. Please post the full path to the library here.

I can not find `libunicorn.dylib`  in the virtual environment.

**Comment by ltfish** [comment]
Ouch. Can you try to find `libunicorn.dylib` on your entire disk?

**Comment by PatchDiscovery** [comment]
> Ouch. Can you try to find `libunicorn.dylib` on your entire disk?

I followed the instructions and tried to install angr in the base python environment. And it works. 

I compared the unicorn in the two python environments.
base: unicorn V2.0.1  libunicorn.2.dylib(./lib/python3.8/site-packages/unicorn/lib)
Virtual: unicorn  V1.0.2 (I can not find libunicorn.dylib)

**Comment by ltfish** [comment]
Interesting - I don't know why your anaconda environment had unicorn 1.0.2 installed. Maybe manually installing unicorn 2 (from PyPI) there would have solved the issue?

We dropped unicorn 1.0 support some time ago.
