### ISSUE TITLE
Duplicate definitions

### ISSUE THREAD

**Issue by zwimer** [angr/angr#3684]
### Description

In `ccall.py`:

`def amd64g_create_mxcsr(state, sseround):`
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L966
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1359

`def amd64g_check_ldmxcsr(state, sseround):`
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L943
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1362

In `callsite_maker.py`: (though these may differ as one is local and one global)
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/analyses/decompiler/callsite_maker.py#L11
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/analyses/decompiler/callsite_maker.py#L17

In `__init__.py`:
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/soot/expressions/__init__.py#L23
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/soot/expressions/__init__.py#L48

In `javavm.py`: (though these may differ as one is local and one global)
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/simos/javavm.py#L3
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/simos/javavm.py#L465

In `regioned_memory_mixin.py`:
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py#L19
https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py#L53

### Environment

Master

**Comment by zwimer** [comment]
How I think these should be addressed:
1. `def amd64g_create_mxcsr(state, sseround):` Keep https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1359 but move it to here https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L966

2. `def amd64g_create_mxcsr(state, sseround):` @ltfish Thoughts? They are different methods

3. `callsite_marker.py` Keep https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/analyses/decompiler/callsite_maker.py#L11 and delete https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/analyses/decompiler/callsite_maker.py#L17

4. `__init__.py` Keep https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/soot/expressions/__init__.py#L23 and remove https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/soot/expressions/__init__.py#L48

5. `javavm.py` Keep https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/simos/javavm.py#L3 and remove https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/simos/javavm.py#L465

6. `regioned_memory_mixin.py` This import seems delayed on purpose? We could just do add an `if RegionedMemory==None:` before the second import and a `RegionedMemory=None` if the conditional import does not occur? Is it being delayed just to increase import time? @ltfish

**Comment by ltfish** [comment]
> Thoughts? They are different methods

It seems that both `amd64g_create_mxcsr` are the same. We can keep one of them.

> `regioned_memory_mixin.py`

The duplication in `regioned_memory_mixin.py` is fine. I don't see why they are duplicates. You should ignore everything protected by `if TYPE_CHECKING`.

**Comment by zwimer** [comment]
@ltfish I made a typo, the differing methods are `amd64g_check_ldmxcsr` here: https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L943 https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1362

**Comment by zwimer** [comment]
Concerning `regioned_memory_mixin.py`, to avoid lint issues, I did:
```python
if TYPE_CHECKING:
    from angr.sim_state import SimState
    from angr.storage.memory_mixins import RegionedMemory
else:
    RegionedMemory = None
```

Followed later by:
```python
            global RegionedMemory
            if RegionedMemory is None:
                from angr.storage.memory_mixins import RegionedMemory
```

**Comment by ltfish** [comment]
> Concerning `regioned_memory_mixin.py`, to avoid lint issues, I did:
> 
> ```python
> if TYPE_CHECKING:
>     from angr.sim_state import SimState
>     from angr.storage.memory_mixins import RegionedMemory
> else:
>     RegionedMemory = None
> ```
> 
> Followed later by:
> 
> ```python
>             global RegionedMemory
>             if RegionedMemory is None:
>                 from angr.storage.memory_mixins import RegionedMemory
> ```

This is highly unconventional and it only reduces readability.

**Comment by ltfish** [comment]
> @ltfish I made a typo, the differing methods are `amd64g_check_ldmxcsr` here:
> 
> https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L943
> 
> https://github.com/angr/angr/blob/9a3926655e10ead4a8efd411ad42fb80dd747998/angr/engines/vex/claripy/ccall.py#L1362

`amd64g_check_ldmxcsr` at line 1362 should only be used if `mxcsr` is symbolic at runtime, which I think almost never happens. When concrete, the two functions are equivalent.

So if you want to be really sure about it, you can merge two functions and add a check on the symbolicity of `mxcsr`.

**Comment by zwimer** [comment]
> `amd64g_check_ldmxcsr` at line 1362 should only be used if `mxcsr` is symbolic at runtime, which I think almost never happens. When concrete, the two functions are equivalent.

I am not sure I understand; at the moment, when you import this module, the second definition immediately overwrites the first- which is to say if we removed the first at line 943 the code would functionally operate the same way, albeit slightly faster due to less code parsing. The function at 1362 should always be used, never the one at 943. 

> So if you want to be really sure about it, you can merge two functions and add a check on the symbolicity of `mxcsr`.

Sure about what? And instead of merging, we could just remove the first if we want to keep all functionality the same.

**Comment by zwimer** [comment]
> This is highly unconventional and it only reduces readability.

There are other ways, but I would like to fix this lint error as it would be the only remaining one in `angr` after this PR for this category of checks. That said, upon closer inspection, why do we import `RegionedMemory` during type checking here at all? `RegionedMemory` is used exclusively right below the second import, and nowhere else, as far as I can tell. We could perhaps remove that first import?

**Comment by ltfish** [comment]
> > This is highly unconventional and it only reduces readability.
> 
> There are other ways, but I would like to fix this lint error as it would be the only remaining one in `angr` after this PR for this category of checks. (And sadly the linter does not provide a comment flag to ignore this one issue). That said, upon closer inspection, why do we import `RegionedMemory` during type checking here at all? `RegionedMemory` is used exclusively right below the second import, and nowhere else, as far as I can tell. We could perhaps remove that first import?

You are absolutely right. The first import can simply be removed.

**Comment by ltfish** [comment]
> I am not sure I understand; at the moment, when you import this module, the second definition immediately overwrites the first- which is to say if we removed the first at line 943 the code would functionally operate the same way, albeit slightly faster due to less code parsing. The function at 1362 should always be used, never the one at 943.

You are describing the current behavior, and I was describing the ideal behavior. For symbolic execution, the less complex an expression we create, the faster the execution will be. This is why I strongly prefer the implementation at Line 943 for all concrete `mxcsr`.

**Comment by zwimer** [comment]
> You are describing the current behavior, and I was describing the ideal behavior. For symbolic execution, the less complex an expression we create, the faster the execution will be. This is why I strongly prefer the implementation at Line 943 for all concrete `mxcsr`.

Got it. I'll update the PR then mark it as ready to be reviewed.
