### ISSUE TITLE
angr decompiles "setb" incorrectly

### ISSUE THREAD

**Issue by Muqi-Zou** [angr/angr#3698]
### Description

As decompiling the attached binary, whose source code can be found [here](https://github.com/coreutils/gnulib/blob/08ba9aaebff69a02cbb794c6213314fd09dd5ec5/lib/c-ctype.h#L310), and disassembled as:
![image](https://user-images.githubusercontent.com/54459497/210126595-138267df-2110-4d54-b2c7-f167ca123c8d.png)
angr decompiles it as:
```
int c_isupper(unsigned long a0)
{
    unsigned long v1;  // rax

    return v1;
}
```

### Steps to reproduce the bug

binary is attached:
[basenc.zip](https://github.com/angr/angr/files/10326870/basenc.zip)

### Environment

latest angr

**Comment by ltfish** [comment]
https://github.com/angr/angr/pull/3701 should fix this bug. Thanks for reporting!

Can you please verify that your `basenc` is from coreutils?

**Comment by ltfish** [comment]
FYI it now decompiles to

```
char c_isupper(unsigned long a0)
{
    return (unsigned int)a0 - 65 < 26;
}
```

**Comment by Muqi-Zou** [comment]
> #3701 should fix this bug. Thanks for reporting!
> 
> Can you please verify that your `basenc` is from coreutils?

Thanks! sure thing, I would check once your commit is merged

**Comment by Muqi-Zou** [comment]
Thanks, it is fixed now!
