### ISSUE TITLE
angr misses the condition containing array

### ISSUE THREAD

**Issue by Muqi-Zou** [angr/angr#3699]
### Description

decompiling the function "base_len", whose source code can be found [here](https://github.com/coreutils/gnulib/blob/08ba9aaebff69a02cbb794c6213314fd09dd5ec5/lib/basename-lgpl.c#L52), and disassembly code as followed:
![image](https://user-images.githubusercontent.com/54459497/210127243-0794c6d9-6190-465a-bea7-81e475e07e62.png)
angr misses the decompilation of "cmp byte ptr [rbx+rax-0x1],0x2f", only has "v1>=2" in the condition:
```
int base_len(char *a0)
{
    unsigned long long v1;  // rcx
    unsigned long long v2;  // rax

    v1 = strlen(a0);
    while (true)
    {
        v2 = v1;
        if (v1 >= 2)
        {
            v1 = v2 - 1;
            return v2;
        }
        return v2;
    }
}
```
as a comparison, ghidra decompiles as:
```
ulong base_len(char *param_1)

{
  ulong local_18;

  for (local_18 = strlen(param_1); (1 < local_18 && (param_1[local_18 - 1] == '/'));
      local_18 = local_18 - 1) {
  }
  return local_18;
}
```

### Steps to reproduce the bug

binary is attached:
[tac.zip](https://github.com/angr/angr/files/10326898/tac.zip)

### Environment

latest angr

**Comment by ltfish** [comment]
Thanks for reporting! This looks like a bug. I'll get to it later.
