### ISSUE TITLE
Status of calling convention detection and DDG analysis

### ISSUE THREAD

**Issue by drone-rites** [angr/angr#370]
This is a question, not an issue.

I'd like to have calling convention detection and the ability to generate DDGs in order to identify and trace "variable-like entities" through CFGs.

The plain DDG class only supports x86 and VSA_DDG is broken (generated graphs contain nodes and no edges). Are there fixes in the works or should I start working on fixes?

Similar for CC detection, is this still being worked on?

Thanks for any info. Maybe we could get a public Slack or IRC channel going? Apologies if it already exists and I missed it!

**Comment by rhelmot** [comment]
https://angr.slack.com

#angr on freenode

:)

**Comment by rhelmot** [comment]
wait right you probably need this http://angr.io/invite.html

**Comment by mattrepl** [comment]
Thanks!

**Comment by ltfish** [comment]
Calling convention detection is being worked on internally right now. DDG is being fixed (see the `re/ddg` branch), VSA_DDG will be removed in the future (since DDG will take input from VFG as well). The development is going on very slowly since we are busy as always, but yes, it will happen.

**Comment by mattrepl** [comment]
Thanks for the news. Anything I can do to help with either?

**Comment by 0xbc** [comment]
Ahoy - I'm interested in this topic (as well as using DDG for the BackwardSlice analysis) . Any ballpark on the DDG refactoring progress @ltfish? Not trying to hassle, just interested to know so I can plan ahead. Likewise, happy to try and help out with the effort if you can point me in the right direction.

**Comment by ltfish** [comment]
I'm working on some fundamental (maybe not gigantic, but definitely big) changes with @zardus to allow simpler development of static analysis. The first real static analysis that will come out, though being simple, is an analysis called _variable recovery_ that recognizes register, stack, and heap variables for a single function. No ETA yet, but I'll push myself harder.

**Comment by ltfish** [comment]
Oh DDG refactor will follow that.

**Comment by 0xbc** [comment]
Cool - thanks for the update!

**Comment by mattrepl** [comment]
Hah, I've been working on, and have some basic support for, variable recovery using angr. Will your and @zardus' work will be on a public branch?

**Comment by ltfish** [comment]
@mattrepl It will be put on a public branch when `import angr` works. Now the code is so incomplete that even import fails :-)

But yes, we are not hoarding or hiding anything (why do so?).

It'll be helpful if you can share your variable recovery as well!

**Comment by ltfish** [comment]
One more reason that it hasn't been put on GitHub yet: there are some underlying renaming and refactoring effort going on, and that is impacting other two branches (`re/ddg` and `fix/function_returning_checks`). I need to figure out how to split my changes into individual commits and properly inject them into different branches.
