### ISSUE TITLE
Return type recovery error, angr decompiles void function as int return function

### ISSUE THREAD

**Issue by Muqi-Zou** [angr/angr#3700]
### Description

Decompiling function "set_quoting_style", whose source code looks like:
```
void
set_quoting_style (struct quoting_options *o, enum quoting_style s)
{
  (o ? o : &default_quoting_options)->style = s;
}
```
angr considers it as an int return function:
![image](https://user-images.githubusercontent.com/54459497/210127429-1f9d4a3d-56c9-4cdf-83b8-543a852aa89f.png)
```
int set_quoting_style(unsigned long a0, unsigned long a1)
{
    *((unsigned int *)(a0 != 0? a0 : 4239984)) = a1;
    return (a0 != 0? a0 : 4239984);
}
```

I also note that ghidra can decompile its return type correctly, not sure how ghidra does it though:
```
void set_quoting_style(undefined1 *param_1,undefined4 param_2)

{
  if ((undefined4 *)param_1 == (undefined4 *)0x0) {
    param_1 = default_quoting_options;
  }
  *(undefined4 *)param_1 = param_2;
  return;
}
```

### Steps to reproduce the bug

binary is attached:
[getlimits.zip](https://github.com/angr/angr/files/10326912/getlimits.zip)

### Environment

latest angr

**Comment by ltfish** [comment]
angr decompiler determines whether a function returns any value or not by analyzing its call sites. You can enable it by invoking `project.analyses.CallingConvention(..., analyze_callsites=True)`. `analyze_callsites` is set to `False` by default as a compromise for speed.

**Comment by Muqi-Zou** [comment]
Not exactly, the code generated above is with `analyze_callsites=True`.

**Comment by ltfish** [comment]
Here is what I got using the latest master branch:

```
long long set_quoting_style(unsigned long a0, unsigned long a1)
{
    *((unsigned int *)(a0 != 0? a0 : 4239984)) = a1;
    return (a0 != 0? a0 : 4239984);
}
```

The exact bug you mentioned has probably been fixed during the past few days.

**Comment by Muqi-Zou** [comment]
> set_quoting_style

I am a bit doubt about this fix, since both source code and ghidra give us void as the function's return type. And it is now long long rather than void.
