### ISSUE TITLE
Fail to decompile certain functions after commit 2b08ff32

### ISSUE THREAD

**Issue by xxr0ss** [angr/angr#3711]
### Description

Certain functions are not decompiled in AM, pseudocode is not shown in Code View when pressing F5.

I've tried to look into it and found `self.function.prototype.returnty` is used even when it's `None`, which caused decompilation to fail.
![image](https://user-images.githubusercontent.com/31790712/210333061-b00bc4fa-c76b-403a-9c3c-c61e3572b8c7.png)

### Steps to reproduce the bug

Try to decompile sub_1000005034

[check_passwd_arm64_flat.zip](https://github.com/angr/angr/files/10335540/check_passwd_arm64_flat.zip)

### Environment

Since commit 2b08ff3248be17f3f531fadd8309020c094d4fec

**Comment by ltfish** [comment]
Fixed by #3712.
