### ISSUE TITLE
How to find simple instruction patterns using angr

### ISSUE THREAD

**Issue by liona24** [angr/angr#3713]
### Question

Hey,

I am playing around with angr and I am having trouble achieving a seemingly simple goal of finding basic data / control flow patterns.

Let's say I want to find functions that do something like "increment x, if something related to x return". 
I approached the problem like that:
- construct a CFG using `project.analyses.CFGFast()`
- find functions using `cfg.kb.functions[..]`
- inspect basic blocks of each function using `func.blocks`

At this point I feel like the VEX IR should prove useful, however implementing the whole data flow tracking seems overkill to me, there should be something similar already, right?

I also considered emulating each basic block, annotating results of `Add32` instructions that have a constant 1 operand and doing some simple taint analysis as described here: https://blog.k3170makan.com/2020/11/sporecrawler-binary-taint-analysis-with.html.

Is this the way to go? Also, how would I correlate VEX IR and emulated statements?
It would be nice if you could provide me some code to get me started.

Consider this VEX IR f.e.:
```
In [26]: b.vex.pp()
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I32 t8:Ity_I32 t9:Ity_I32 t10:Ity_I64 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I64 t15:Ity_I64 t16:Ity_I64 t17:Ity_I64 t18:Ity_I64 t19:Ity_I64 t20:Ity_I32 t21:Ity_I64 t22:Ity_I64 t23:Ity_I64 t24:Ity_I32 t25:Ity_I64 t26:Ity_I64 t27:Ity_I64 t28:Ity_I64 t29:Ity_I64 t30:Ity_I64 t31:Ity_I64 t32:Ity_I64 t33:Ity_I64 t34:Ity_I1 t35:Ity_I64 t36:Ity_I64 t37:Ity_I64 t38:Ity_I64 t39:Ity_I64 t40:Ity_I64 t41:Ity_I32 t42:Ity_I32 t43:Ity_I64 t44:Ity_I64 t45:Ity_I1 t46:Ity_I32 t47:Ity_I32 t48:Ity_I1

   00 | ------ IMark(0x401122, 1, 0) ------
   01 | t0 = GET:I64(rbp)
   02 | t16 = GET:I64(rsp)
   03 | t15 = Sub64(t16,0x0000000000000008)
   04 | PUT(rsp) = t15
   05 | STle(t15) = t0
   06 | ------ IMark(0x401123, 3, 0) ------
   07 | PUT(rbp) = t15
   08 | ------ IMark(0x401126, 4, 0) ------
   09 | t2 = Sub64(t15,0x0000000000000010)
   10 | PUT(rsp) = t2
   11 | PUT(rip) = 0x000000000040112a
   12 | ------ IMark(0x40112a, 3, 0) ------
   13 | t18 = Add64(t15,0xfffffffffffffffc)
   14 | t21 = GET:I64(rdi)
   15 | t41 = 64to32(t21)
   16 | t20 = t41
   17 | STle(t18) = t20
   18 | PUT(rip) = 0x000000000040112d
   19 | ------ IMark(0x40112d, 3, 0) ------
   20 | t22 = Add64(t15,0xfffffffffffffff8)
   21 | t25 = GET:I64(rsi)
   22 | t42 = 64to32(t25)
   23 | t24 = t42
   24 | STle(t22) = t24
   25 | PUT(rip) = 0x0000000000401130
   26 | ------ IMark(0x401130, 4, 0) ------
   27 | t26 = Add64(t15,0xfffffffffffffff8)
   28 | t9 = LDle:I32(t26)
   29 | t7 = Add32(t9,0x00000001)
   30 | STle(t26) = t7
   31 | PUT(rip) = 0x0000000000401134
   32 | ------ IMark(0x401134, 4, 0) ------
   33 | t30 = Add64(t15,0xfffffffffffffff8)
   34 | t13 = LDle:I32(t30)
   35 | PUT(cc_op) = 0x0000000000000007
   36 | t43 = 32Uto64(t13)
   37 | t32 = t43
   38 | PUT(cc_dep1) = t32
   39 | PUT(cc_dep2) = 0x0000000000000064
   40 | PUT(rip) = 0x0000000000401138
   41 | ------ IMark(0x401138, 2, 0) ------
   42 | t46 = 64to32(0x0000000000000064)
   43 | t47 = 64to32(t32)
   44 | t45 = CmpLE32S(t47,t46)
   45 | t44 = 1Uto64(t45)
   46 | t39 = t44
   47 | t48 = 64to1(t39)
   48 | t34 = t48
   49 | if (t34) { PUT(rip) = 0x401141; Ijk_Boring }
   NEXT: PUT(rip) = 0x000000000040113a; Ijk_Boring
}
```

Thanks for your help.

**Comment by rhelmot** [comment]
So, such an operation is fairly non-trivial. You may want to look into purely static heuristic-based pattern matching on the VEX IR, for example, "does this block contain an add followed by a store", and then after that do a more substantial dataflow analysis.

**Comment by rhelmot** [comment]
You may also want to look into [angrop](https://github.com/angr/angrop).

**Comment by ltfish** [comment]
Alternatively, decompile all functions in angr and run pattern-matching on decompilation output.

**Comment by ltfish** [comment]
Basically you have a few options:

- Pattern-matching on the VEX IR level.
- Pattern-matching on statically generated data-flow graphs at VEX IR level (see angrop and angr's reaching definition analysis).
- Pattern-matching on the AIL level.
- Pattern-matching on statically generated data-flow graphs at AIL level (see angr's reaching definition analysis).
- Pattern-matching on the decompilation output level.

They each comes with its own perks and quirks.

**Comment by liona24** [comment]
Thanks for your input. I'll have a look at the reaching definition analysis later. For now I went with a pattern matching approach based on the CFG + VEX IR, leaving the data flow to some basic heuristics
