### ISSUE TITLE
Want global variables uninitialized

### ISSUE THREAD

**Issue by lks9** [angr/angr#3715]
### Question

Happy new year!

I want to start symbolic execution somewhere in the mid of a program (to avoid "expensive" computation) and ran into a problem. It seems that global variables are always initialized (to 0 or to the constant value as given in the c source code).

The problem arises when starting symbolic execution somewhere where the initial values already got overwritten. In the following example, I want to execute `foo`, while ignoring the original initial value (which is `0`) for `global_var`:

```C
#include<stdio.h>

int global_var;

void foo(void) {
    if (global_var > 0) {
        printf("Yes!!\n");
    } else {
        printf("No_o.\n");
    }
}

void expensive_computation(void) {
    global_var = 42;
}

int main(void) {
    expensive_computation();
    foo();
    return 0;
}
```
For the concrete example see `demo`, `demo.c`, `symex_demo.py` in [demo.zip](https://github.com/angr/angr/files/10339022/demo.zip).

Question: How to do this?

I don't want to iterate over all global variables to make them symbolic. Ideal it would be if the loader just leaves all global variables uninitialized.

Thank you very much in advance!

**Comment by rhelmot** [comment]
the loader doesn't have the ability to store things as symbolic data, only concrete. You'll want to use the loader metadata, i.e. the ranges of the .data and .bss sections, and store symbolic bytes to all of those addresses.

**Comment by lks9** [comment]
Thanks for the prompt answer! This seems what I would need, any more info on angr specifics? Otherwise I would just try to look into it.

**Comment by rhelmot** [comment]
Yeah - project.loader.sections will give you the list of sections, iterate for the writable ones (or just the .data and .bss sections), then store symbolic bytes to each range of addresses.

**Comment by lks9** [comment]
Thank you very much, I got it working!

```python
sections = p.loader.main_object.sections
for section in sections:
    if section.name == ".data" or section.name == ".bss":
        data = state.solver.BVS("data", 8*(section.max_addr- section.min_addr))
        state.memory.store(section.min_addr, data)
```
