### ISSUE TITLE
Understand unicorn output

### ISSUE THREAD

**Issue by frapik99** [angr/angr#373]
Hi,
can you help me to understand this output please?

```
INFO    | 2017-02-25 08:19:48,012 | simuvex.plugins.unicorn | started emulation at 0x4012f9 (1000000 steps)
INFO    | 2017-02-25 08:19:48,014 | simuvex.plugins.unicorn | mmap [0x401000, 0x401fff], 5 (symbolic)
INFO    | 2017-02-25 08:19:48,016 | simuvex.plugins.unicorn | mmap [0x7fffffffffe0000, 0x7fffffffffeffff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,019 | simuvex.plugins.unicorn | mmap [0x6010000, 0x601ffff], 3
INFO    | 2017-02-25 08:19:48,022 | simuvex.plugins.unicorn | mmap [0x602000, 0x602fff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,023 | simuvex.plugins.unicorn | mmap [0x400000, 0x400fff], 5
INFO    | 2017-02-25 08:19:48,025 | simuvex.plugins.unicorn | mmap [0x7000000, 0x7000fff], 5
INFO    | 2017-02-25 08:19:48,037 | simuvex.plugins.unicorn | finished emulation at 0x7000080 after 3 steps: STOP_STOPPOINT
INFO    | 2017-02-25 08:19:48,076 | simuvex.plugins.unicorn | started emulation at 0x40175d (1000000 steps)
INFO    | 2017-02-25 08:19:48,077 | simuvex.plugins.unicorn | mmap [0x401000, 0x401fff], 5 (symbolic)
INFO    | 2017-02-25 08:19:48,079 | simuvex.plugins.unicorn | mmap [0x7fffffffffe0000, 0x7fffffffffeffff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,081 | simuvex.plugins.unicorn | mmap [0x6010000, 0x601ffff], 3
WARNING | 2017-02-25 08:19:48,082 | simuvex.plugins.unicorn | fetching empty page [0x0, 0xfff]
INFO    | 2017-02-25 08:19:48,103 | simuvex.plugins.unicorn | finished emulation at 0x401777 after 1 steps: STOP_EXECNONE
INFO    | 2017-02-25 08:19:48,120 | simuvex.engines.unicorn_engine | not enough runs since last unicorn (100)
INFO    | 2017-02-25 08:19:48,125 | simuvex.engines.unicorn_engine | not enough runs since last unicorn (99)
```

**Comment by zardus** [comment]
Sure:

```
INFO    | 2017-02-25 08:19:48,012 | simuvex.plugins.unicorn | started emulation at 0x4012f9 (1000000 steps)
```

Here, angr diverts to unicorn engine, beginning with the basic block at 0x4012f9. The maximum step count is set to 1000000, so if execution stays in Unicorn for 1000000 blocks, it'll automatically pop out (to avoid hanging in an infinite loop).

---------------------------------------

```
INFO    | 2017-02-25 08:19:48,014 | simuvex.plugins.unicorn | mmap [0x401000, 0x401fff], 5 (symbolic)
INFO    | 2017-02-25 08:19:48,016 | simuvex.plugins.unicorn | mmap [0x7fffffffffe0000, 0x7fffffffffeffff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,019 | simuvex.plugins.unicorn | mmap [0x6010000, 0x601ffff], 3
INFO    | 2017-02-25 08:19:48,022 | simuvex.plugins.unicorn | mmap [0x602000, 0x602fff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,023 | simuvex.plugins.unicorn | mmap [0x400000, 0x400fff], 5
INFO    | 2017-02-25 08:19:48,025 | simuvex.plugins.unicorn | mmap [0x7000000, 0x7000fff], 5
```

angr performs lazy mapping of data that is accessed by unicorn engine, as it is accessed. 0x401000 is the page of instructions that it is executing, 0x7fffffffffe0000 is the stack, and so on. Some of these pages are symbolic, meaning that they contain at least some data that, when accessed, will cause execution to abort out of Unicorn.

---------------------------------------

```
INFO    | 2017-02-25 08:19:48,037 | simuvex.plugins.unicorn | finished emulation at 0x7000080 after 3 steps: STOP_STOPPOINT
```

Execution stays in Unicorn for 3 basic blocks (a computational waste, considering the required setup), after which it reaches a simprocedure location and jumps out to execute the simproc in angr.

---------------------------------------

```
INFO    | 2017-02-25 08:19:48,076 | simuvex.plugins.unicorn | started emulation at 0x40175d (1000000 steps)
INFO    | 2017-02-25 08:19:48,077 | simuvex.plugins.unicorn | mmap [0x401000, 0x401fff], 5 (symbolic)
INFO    | 2017-02-25 08:19:48,079 | simuvex.plugins.unicorn | mmap [0x7fffffffffe0000, 0x7fffffffffeffff], 3 (symbolic)
INFO    | 2017-02-25 08:19:48,081 | simuvex.plugins.unicorn | mmap [0x6010000, 0x601ffff], 3
```

After the simprocedure, execution jumps back into Unicorn.

---------------------------------------

```
WARNING | 2017-02-25 08:19:48,082 | simuvex.plugins.unicorn | fetching empty page [0x0, 0xfff]
INFO    | 2017-02-25 08:19:48,103 | simuvex.plugins.unicorn | finished emulation at 0x401777 after 1 steps: STOP_EXECNONE
```

Execution bounces out of Unicorn almost right away because the binary accessed the zero-page.

---------------------------------------

```
INFO    | 2017-02-25 08:19:48,120 | simuvex.engines.unicorn_engine | not enough runs since last unicorn (100)
INFO    | 2017-02-25 08:19:48,125 | simuvex.engines.unicorn_engine | not enough runs since last unicorn (99)
```

To avoid thrashing in and out of Unicorn (which is expensive), we have cooldowns (attributes of the `state.unicorn` plugin) that wait for certain conditions to hold (i.e., no symbolic memory accesses for X blocks) before jumping back into unicorn when a unicorn run is aborted due to anything but a simprocedure or syscall. Here, the condition it's waiting for is for 100 blocks to be executed before jumping back in.

**Comment by frapik99** [comment]
Thanks @zardus for your explanation. Is it possible with unicorn to emulate even code within shared libraries? I'm doing some experiment with pngpixel as you can see in my other issues and I have problem finding a path that goes after ```png_create_read_struct```, so maybe it would be better to emulate the code rather than create a SimProcedure for it. If possible can someone add an example to the docs?

Thanks a lot

**Comment by rhelmot** [comment]
Yes. Unicorn is a pure CPU emulator, and knows nothing of binaries or code layout. angr provides that code to it the same as all other code.

A page on using unicorn would definitely be good to have in the docs.

**Comment by zardus** [comment]
Unfortunately, our the workload doesn't look good for the next while to be able to get to it on this example :-(. That being said, I can try to keep helping through here.

The specific issue that kicks it out of Unicorn is a null pointer dereference (`WARNING | 2017-02-25 08:19:48,082 | simuvex.plugins.unicorn | fetching empty page [0x0, 0xfff]`). I would analyze that basic block (either `0x40175d` or the block after it), see what memory it's dereferencing, and see if it's 0 in the angr state that's being passed into Unicorn.

**Comment by frapik99** [comment]
@zardus thanks for your help. I think I understood why it stops :)

```
0x0000000000401758 <+1119>:	callq  0x400c80 <fwrite@plt>
0x000000000040175d <+1124>:	mov    -0x84(%rbp),%eax
0x0000000000401763 <+1130>:	mov    -0x8(%rbp),%rdi
0x0000000000401767 <+1134>:	xor    %fs:0x28,%rdi
0x0000000000401770 <+1143>:	je     0x401777 <main+1150>
0x0000000000401772 <+1145>:	callq  0x400b40 <__stack_chk_fail@plt>
0x0000000000401777 <+1150>:	leaveq 
0x0000000000401778 <+1151>:	retq  
```

It is at the end of ```pngpixel```.

I'm trying to reproduce it passing the necessary parameters to ```pngpixel``` but I still encounter the possible bug I found in claripy.

I would pass the 3 parameters in this way:

```
proj = angr.Project('./pngpixel', load_options={"auto_load_libs": False})
argv1 = angr.claripy.BVV(100, 64)
argv2 = angr.claripy.BVS(200, 64)
argv3 = how to create a string as a parameter?
initial_state = proj.factory.entry_state(args=["./fairlight", argv1,argv2,argv3])
```

How can i create a string as a parameter?

**Comment by zardus** [comment]
Regarding the second question, that's more of a pure Unicorn question, and I don't have an answer for you. My guess is "not out of the box", as I don't see how that can work performantly by Unicorn, and Unicorn doesn't really include a disassembler.

Regarding the other issue, I want to make sure some things:

1. Earlier in the thread, you asked about libraries. However, you're loading the project with `load_options={"auto_load_libs": False}`. This stops libraries from being loaded, which will mean that you cannot execute the library functions (with or without Unicorn). Are you sure you shouldn't be loading the libraries?
2. `argv2 = angr.claripy.BVS(200, 64)` doesn't make sense. A `BVS` is a bit-vector symbol that should have a name and a size. Furthermore, these arguments *are* the symbolic string command-line arguments to the program. By making a 64-bit argv2, you're creating an 8-character argument. Same with argv1: you're passing, on the command line, `\x64\x00\x00\x00\x00\x00\x00\x00`. In another scenario, what you might do is:

```
project = angr.Project(...)

# make a 32-byte symbolic flag
argv1 = angr.claripy.BVS("flag", 32*8)

# use full_init_state instead of entry_state to run all the library initializers
initial_state = project.factory.full_init_state(args=["./challenge", argv1])
```

Let me know if this is useful.

**Comment by frapik99** [comment]
thanks @zardus I'll try to clarify a bit. My final goal is verify how it is possible with angr to analyse ```pngpixel``` and obtain a path between main and ```png_create_struct_data``` but also going inside the shared libraries used by ```pngpixel```. Obviously I need to have ```keep_state``` set to ```True``` because after the path is found I need to work the path. This being said your are right I need to set ```auto_load_libs``` to ```True```, I made a mistake copying the code. Regarding your second comment, yes I made another mistake I should use ```BVV``` I think. I hope I clarify my self now.

One final comment, ```pngpixel``` needs to have 3 parameters, the first two must be int and the third a string that would be the png file that will be opened. I think I can create the first two using ```argvX = angr.claripy.BVV(100, 32)``` but I have no idea how to create the third that would a constant string such as ```file.png```.

Thanks to other comments I understood that a function declared in so can be "skipped" using ```self.project.hook_symbol("function_name", simuvex.SimProcedures['stubs']['ReturnUnconstrained'])``` so I'm doing it over all the functions but ```png_create_read_struct``` is it the wrong approach?

if you could show me an example code for obtaining this path would be really appreciated. Would be faster if I emulate the code with ```unicorn``` and just after extract what I need from the found path?

Thanks for your time

**Comment by frapik99** [comment]
Hi,
I have realised that the ```png_create_read_strcut``` is probably replaced by a ```SimProcedure```.

```
png_create_read_struct
Analysing 0x400c30L
0x400c30:	jmp	qword ptr [rip + 0x2014aa]
t2 = LDle:I64(0x00000000006020e0)

right after...

Analysing 0x100ee40L
0x100ee40:	sub	rsp, 0x10
0x100ee44:	xor	r9d, r9d
0x100ee47:	xor	r8d, r8d
0x100ee4a:	push	0
0x100ee4c:	call	0x1004dc8
```

Am I correct? Can I know why? Maybe function that are part of the ```plt``` are replaced in this way. I would like to have the original function an not this one if possible.

Thanks

**Comment by zardus** [comment]
It does look like that's valid code in `0x100ee40`. My guess is that's where your png library was loaded. Can you check in CLE `project.loader.shared_objects` (http://angr.io/api-doc/cle.html), and using `project.is_hooked` (http://angr.io/api-doc/angr.html#angr.project.Project.is_hooked) to make sure `0x100ee40` isn't hooked?

**Comment by frapik99** [comment]
Hi @zardus ,
I have checked within the shared object and I had this result: ```(u'libpng16.so.16', <ELF Object libpng16.so.16.28.0, maps [0x1000000:0x123200f]>)``` so I think I didn't properly understand and the code was successfully going at ```0x100ee40``` that was the address of ```png_create_read_struct```. I assume that the other calls such as ```0x1004c8``` are other calls necessary to the ```png_create_read_struct```.

I have checked ```0x100ee40``` and it is not hooked, so I think the original code is called.

I have also found the same code within ```pngpixel``` via ```gdb```:

```
0x7fd933b6be40  <png_create_read_struct+0>  sub rsp, 0x10
0x7fd933b6be44  <png_create_read_struct+4>  xor r9d, r9d   ← $pc
0x7fd933b6be47  <png_create_read_struct+7>  xor r8d, r8d
0x7fd933b6be4a  <png_create_read_struct+10>  push 0x0
0x7fd933b6be4c  <png_create_read_struct+12>  call 0x7fd933b61dc8
```

```
gef➤  info share
From                To                  Syms Read   Shared Object Library
0x00007fd933d90aa0  0x00007fd933dabde0  Yes         /lib64/ld-linux-x86-64.so.2
**0x00007fd933b62010  0x00007fd933b835db  Yes (*)     /usr/lib/x86_64-linux-gnu/libpng16.so.16**
0x00007fd9337de910  0x00007fd9339082c3  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007fd9335a6220  0x00007fd9335b7469  Yes (*)     /lib/x86_64-linux-gnu/libz.so.1
0x00007fd9332a5680  0x00007fd9333118da  Yes         /lib/x86_64-linux-gnu/libm.so.6
(*): Shared library is missing debugging information.
gef➤  
```

So I think was can conclude that it is working but I didn't realise it at the beginning. Am i right?

Thanks for all

**Comment by zardus** [comment]
I think things are mostly working correctly, but the fact that unicorn stops on a null pointer dereference is very strange. I think understanding *what* is dereferenced is important -- my guess is that there is something that is not being initialized properly.

**Comment by frapik99** [comment]
Problem solved

Thanks
