### ISSUE TITLE
Symbolic Execution on Binary With File as Input

### ISSUE THREAD

**Issue by iceeeeee** [angr/angr#374]
Hi,

How could I use symbolic execution to run a x86_64 binary with a file as an input? I write a simple test file, which simply read the file provided by argv and print the content of that file out. Then I run following commands:

```
b = angr.Project('./testfile')
state = b.factory.entry_state()
path = b.factory.path(state)
pg = b.factory.path_group(path)
pg.explore()
```

Returns:
`<PathGroup with 1 errored>`

I think the reason cause this problem may be the initialize code use various memory locations which angr cannot automatically detect. Is this correct? If true, how to solve this problem? If not, what is the reason of this problem and how to fix it?

Thanks
Ice

**Comment by rhelmot** [comment]
You can debug this problem by getting the errored path out of the path group:

`epath = pg.errored[0]`

And then printing the error:

`print epath.error`

And then obtaining a debug shell at the error site:

`epath.debug()`

**Comment by frapik99** [comment]
@iceeeeee ,
can you do something like:

```
# use full_init_state instead of entry_state to run all the library initializers
initial_state = project.factory.full_init_state(args=["./testfile", "filename"])

Thanks
```
