### ISSUE TITLE
Undefined names

### ISSUE THREAD

**Issue by zwimer** [angr/angr#3742]
### Description

Running `ruff` on `angr` master gives back multiple undefined name errors.

Some of these are likely due to typos, like `Pendingjob` should probably be `PendingJob`; some are likely due to python2, like `reduce` is no longer a python builtin but rather part of functools. Etc.

We could remove check on the autogenerated code (or maybe we want to fix the autogenerated code generators).

If all errors below are resolved by a given PR, it should also no longer disable this check in `pyproject.toml`.

### Steps to reproduce the bug

1. In `pyproject.toml`, comment out `"F821"`.
1. Run `ruff .`

### Additional context

```
(dev) zwimer@Lotus ~/D/c/m/angr> ruff .                                                          pre-commit!
angr/analyses/cfg/cfg_emulated.py:1245:27: F821 Undefined name `Pendingjob`
angr/analyses/datagraph_meta.py:26:15: F821 Undefined name `DataGraphError`
angr/analyses/datagraph_meta.py:31:19: F821 Undefined name `DataGraphError`
angr/analyses/datagraph_meta.py:96:15: F821 Undefined name `DataGraphError`
angr/analyses/decompiler/decompiler.py:26:25: F821 Undefined name `PeepholeOptimizationStmtBase`
angr/analyses/decompiler/decompiler.py:26:63: F821 Undefined name `PeepholeOptimizationExprBase`
angr/analyses/loop_analysis.py:118:36: F821 Undefined name `SootLocal`
angr/analyses/loop_analysis.py:183:38: F821 Undefined name `SootValue`
angr/engines/pcode/arch.py:40:13: F821 Undefined name `l`
angr/engines/pcode/arch.py:67:13: F821 Undefined name `l`
angr/exploration_techniques/cacher.py:101:41: F821 Undefined name `file`
angr/misc/bug_report.py:22:21: F821 Undefined name `angr`
angr/misc/bug_report.py:23:24: F821 Undefined name `unicorn`
angr/misc/bug_report.py:24:22: F821 Undefined name `pyvex`
angr/protos/cfg_pb2.py:23:3: F821 Undefined name `_CFGNODE`
angr/protos/cfg_pb2.py:24:3: F821 Undefined name `_CFGNODE`
angr/protos/cfg_pb2.py:25:3: F821 Undefined name `_CFG`
angr/protos/cfg_pb2.py:26:3: F821 Undefined name `_CFG`
angr/protos/cfg_pb2.py:27:3: F821 Undefined name `_MEMORYDATA`
angr/protos/cfg_pb2.py:28:3: F821 Undefined name `_MEMORYDATA`
angr/protos/cfg_pb2.py:29:3: F821 Undefined name `_MEMORYDATA_MEMORYDATATYPE`
angr/protos/cfg_pb2.py:30:3: F821 Undefined name `_MEMORYDATA_MEMORYDATATYPE`
angr/type_backend.py:34:20: F821 Undefined name `reduce`
angr/type_backend.py:55:20: F821 Undefined name `reduce`
angr/type_backend.py:76:20: F821 Undefined name `reduce`
angr/type_backend.py:97:20: F821 Undefined name `reduce`
angr/type_backend.py:118:20: F821 Undefined name `reduce`
Found 27 error(s).
```

**Comment by rhelmot** [comment]
Some triage:

- angr/type_backend.py is 100% unused and should be removed. It was an experiment from a while ago.
- We might want to fully disable linting for the autogenerated stuff, or at least leave this check permanently disabled for angr/protos
- bug_report.py does dynamic imports and modifies globals(). Dunno the right way to typecheck this.
- cacher has the comment `DO NOT USE THIS - THIS IS FOR ARCHIVAL PURPOSES ONLY`. Maybe remove it.
- the missing logger in pcode/arch.py is just straight up a bug and should be added
- LoopAnalysis is essentially unmaintained, but I think people are actually using it
- The missing names in decompiler are just missing imports but are otherwise harmless because they're type annotations
- datagraph_meta seems to be genuinely broken.
- Pendingjob is a typo.

**Comment by zwimer** [comment]
@rhelmot This is likely a topic for a different thread, but regarding the autogenerated code, my plan is:
1. If we do not control this code (like google generated code), disable all linting
2. If we control this code, apply all linting non-stylistic linting (line too long will be ignored, but undefined name will not be). So far my linter is 2/3 for finding bugs in autogen'd code- 3/3 if this is a bug and not just a false positive; this can help us improve our code that does the generation.
3. After fixing bugs, per-file (or if needed per-directory) disable only the lint checks that are needed to pass.
We can discuss this more in slack if you dislike this idea or have comments though.

**Comment by twizmwazin** [comment]
For type annotations, we should still be importing everything, potentially under an `if typing.TYPE_CHECKING` guard.
