### ISSUE TITLE
When Symbolic Execution encounter with Side Effect

### ISSUE THREAD

**Issue by shelvenzhou** [angr/angr#375]
I can hook a function to return UNCONSTRAINED, but for function like
`
int foo(int *bar)
`
How to label _bar_ as UNCONSTRAINED?

**Comment by rhelmot** [comment]
You will need to write a SimProcedure to do this. Here is a procedure to do this:

```python
class ReturnUnconstrainedOutparam(simuvex.SimProcedure):
    def run(self, bar):
        self.state.mem[bar].int = state.se.BVS('bar_val', state.arch.bits)
        return state.se.BVS('return_val', state.arch.bits)
```

You can use this class to hook that function. A guide on programming SimProcedures is [here](https://docs.angr.io/docs/simprocedures.html).

**Comment by shelvenzhou** [comment]
Thanks
