### ISSUE TITLE
Windows smoketest passes without doing anything

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#3753]
### Description

The windows smoke test is passing in <1 minute without any indication that it actually installs and imports angr.

**Comment by syheliel** [comment]
seems that a `&` is missing to split different cmd in https://github.com/angr/angr/blob/2534b49b7d69d3ab11fcb99c228ebb046b0fb926/.github/workflows/smoketest.yml

**Comment by syheliel** [comment]
fixed in #3758, has tested in my CI: https://github.com/syheliel/angr/actions/runs/3964251941/jobs/6792938011
