### ISSUE TITLE
Displaying graph from CFG does not display full graph

### ISSUE THREAD

**Issue by smuthayan** [angr/angr#3769]
### Question

Hello. I am trying to display a graph of nodes. 

I can display 10 nodes with ease but after I encounter a certain indirect jump, the graph stops printing nodes and edges.  I've tried stepping over and seeing what the value of the RSI register was and it pointed to the correct path. If I run a simulation with proj.factory.simgr, it also continues on the same path without error.

I read the source code from cfg_emulated.py couldn't find anything related to a "max number of blocks to hold".

Any help would be appreciated,I've attached related pictures and code below.

```python
from bingraphvis import DotOutput
from bingraphvis.angr import *
from bingraphvis.angr.x86 import *

import angr;

proj = angr.Project("F:/analysis/driver.sys", load_options={'auto_load_libs':False})
#start_state = proj.factory.blank_state(mode="static")
state = proj.factory.entry_state()
cfg = proj.analyses.CFGEmulated(keep_state=True)
simgr = proj.factory.simgr(state)

print("This is the graph:", cfg.graph)

vis = AngrVisFactory().default_cfg_pipeline(cfg, asminst=True, vexinst=False)
vis.set_output(DotOutput('EAC' + '_angr_asm', format="png"))
vis.process(cfg.graph)
vis = AngrVisFactory().default_cfg_pipeline(cfg, asminst=False, vexinst=True)
vis.set_output(DotOutput('EAC' + '_angr_vex', format="png"))
vis.process(cfg.graph)
```
Console Output
```
This is the graph: DiGraph with 10 nodes and 11 edges

Process finished with exit code 0
```

![graph](https://user-images.githubusercontent.com/49108786/215411943-4b2210ae-ade2-45a0-80a5-bcb30eb7fd27.png)

**Comment by rhelmot** [comment]
Performing indirect jump resolution is quite difficult. If the simulation manager is able to follow the jump, maybe try performing a CFGEmulated analysis instead?

**Comment by smuthayan** [comment]
> Performing indirect jump resolution is quite difficult. If the simulation manager is able to follow the jump, maybe try performing a CFGEmulated analysis instead?

I thought I already was doing a CFGEmulated analysis with 
```python
cfg = proj.analyses.CFGEmulated(keep_state=True)
```

**Comment by rhelmot** [comment]
In that case, you may want to try CFGFast - it has jumptable resolution heuristics.

**Comment by smuthayan** [comment]
Thank you.
