### ISSUE TITLE
cs:program_invocation_name in simos.py for ELF 

### ISSUE THREAD

**Issue by Traxes** [angr/angr#379]
Hello,

My binary had several Anti-Debug Techniques and after quite some debugging time i figured out angr does not set program_invocation_name automatically. Since the name was in the Flag calculation it screwed me.

Might be a good addition for the future.
Cheers,
Traxes

**Comment by zardus** [comment]
Thanks for the heads up! I'm sure someone will get to this eventually :-)

How did you solve this in the end? Hacked it into your script?

**Comment by Traxes** [comment]
Pretty much... just wrote it into the state :).
