### ISSUE TITLE
Can angr build CFG without dynamic technique?

### ISSUE THREAD

**Issue by XingweiLin** [angr/angr#381]
Hi all,
I have a question about how does angr build CFG.
I noticed that Angr needs dynamic tech to build CFGAccurate.
![image](https://cloud.githubusercontent.com/assets/15721702/23687744/0d559788-03eb-11e7-82de-3225a1313f2c.png)
My detail question is: Does angr need to run the program(dynamic tech) to build CFG? Can it build CFG without running the program(only based on static analysis)?

**Comment by ltfish** [comment]
angr only utilizes the concept of Dynamic Forced Execution. When using `CFGAccurate`, it does not run the program, instead it simulates the execution to generate a CFG.

For pure CFG recovery without simulation, you want `CFGFast`.

**Comment by XingweiLin** [comment]
@ltfish Thanks for your reply.
I got it.
