### ISSUE TITLE
the deference between DFG and DDG

### ISSUE THREAD

**Issue by fumingxiaosheng** [angr/angr#3818]
### Question

In angr docs,I found that DFG have been removed from angr 7.8.7.1.
Recently,I have to use tools related to data flow.But I can not tell the difference between DFG ang DDG analysing tools angr provides.So,what is the definition of these two,and how to distinguish them.

**Comment by ltfish** [comment]
DDG relies on simulation (which is done when running `CFGEmulated`) results, while IIRC DFG was a pure-static version of DDG. We removed DFG because it was contributed by someone who could no longer maintain it, and the new static analysis stack (such as RDA) in angr is way more powerful than DFG.

**Comment by fumingxiaosheng** [comment]
thanks a lot
