### ISSUE TITLE
Inconsistent execution

### ISSUE THREAD

**Issue by frapik99** [angr/angr#382]
Hi,
I'm still experimenting with ```pngpixel``` but I have encountered a weird behaviour even if I'm able to generate the path between the ```main``` and ```png_malloc```. The problem is that when ```png_malloc_base``` is called ```malloc`` should be also called few instructions after:

```
0x7ffff7bb1970  <png_malloc_base+32>  mov rdi, rsi   ← $pc
**0x7ffff7bb1973  <png_malloc_base+35>  jmp 0x7ffff7bab100 <malloc@plt>**
0x7ffff7bb1978  <png_malloc_base+40>  nop DWORD PTR [rax+rax*1+0x0]
0x7ffff7bb1980  <png_malloc_base+48>  xor eax, eax
0x7ffff7bb1982  <png_malloc_base+50>  ret 
```

```
**0x7ffff7bab100  <malloc@plt+0>  jmp QWORD PTR [rip+0x22d1da]        # 0x7ffff7dd82e0   ← $pc**
0x7ffff7bab106  <malloc@plt+6>  push 0x59
```
The symbolic execution can correctly reach that point:

```
Block starting @0x100b970L
0x100b970:	mov	rdi, rsi
**0x100b973:	jmp	0x1005100**
```

but at that address I have the following block:

```
Block starting @0x1005100L
0x1005100:	jmp	qword ptr [rip + 0x22d1da]
```

consequently the following block is executed:

```
Analysing 0x100bb5eL
0x100bb5e:	test	rax, rax
0x100bb61:	je	0x100bb65
```

I cannot really understand why the execution jumps to ```0x100bb5e```. Do you have an idea why?

Should I check if the ```malloc``` is hooked?

Thanks

**Comment by frapik99** [comment]
Hi,
please note this:

```
0x7ffff7bab100  <malloc@plt+0>  jmp QWORD PTR [rip+0x22d1da]        # 0x7ffff7dd82e0   ← $pc
```

So ```0x1005100``` should be ```malloc@plt+0``` but instead it goes off track...

Thanks

**Comment by zardus** [comment]
So that is a plt stub that reads the next target from the GOT, so it does a read from `0x12322da` (0x1005100 + 0x22d1da) and jumps there. Are you sure that the value stored there is not `0x100bb5e`?

**Comment by frapik99** [comment]
Hi @zardus , I did not check because I did not know how to do it, but for sure if tracing the same project with gdb it jump at the beginning of the ```malloc```... Why not in that case?

Thanks

**Comment by schieb** [comment]
@frapik99 Minor correction in case you didn't figure it out already:

RIP-relative addressing is relative to the *next* instruction so you will want to check the memory starting at ```0x12322E0``` (0x1005106 + 0x22d1da) instead of ```0x12322da```.

**Comment by zardus** [comment]
Haha, oops, good point :-)

**Comment by frapik99** [comment]
Hi both,
@zardus I have done as you suggested and now the flow jumps to the correct address. Continuing to follow it i have spot another difference:

```
0x43bfd0  <__libc_start_main+704>  mov eax, DWORD PTR [rsp+0x1c]
0x43bfd4  <__libc_start_main+708>  add eax, DWORD PTR [rsp+0x14]
0x43bfd8  <__libc_start_main+712>  cmp eax, 0x2f
0x43bfdb  <__libc_start_main+715>  mov DWORD PTR [rsp+0x14], eax
0x43bfdf  <__libc_start_main+719>  ja 0x43c07c <__libc_start_main+876>   ← $pc	TAKEN [Reason: !C && !Z]
```

instead the symbolic execution does not take it and goes to ```0x43bfe5``` ( next instruction ). The function called before was ```_dl_x86_cpu_features```.

How do you think it can be fixed?

Thanks

**Comment by frapik99** [comment]
Hi,
I have checked and the original execution does this:

```
0x7ffff7bab100  <malloc@plt+0>  jmp QWORD PTR [rip+0x22d1da]        # 0x7ffff7dd82e0   ← $pc
0x7ffff7bab106  <malloc@plt+6>  push 0x59
0x7ffff7bab10b  <malloc@plt+11>  jmp 0x7ffff7baab60
```

the jump @0x7ffff7bab100 it seems to be "ignored" (???) and the next instruction executed was ```push 0x59``` how is it possible?

Another question, in order to check the content I put a break point at ```0x1005100``` because of the instruction ```0x1005100:	jmp	qword ptr [rip + 0x22d1da]``` doing ```path.state.inspect.b('instruction', when=simuvex.BP_BEFORE, instruction=0x1005100, action=track)```. Is it correct?

Anyway the ```track``` function is something is:

```
def track(state):
   print "30 bytes @0x12322E0", state.memory.load(0x12322e0, 30)
   print "30 bytes @0x12322E0", state.se.any_int(state.memory.load(0x12322e0, 30))

```

and the result:

```
30 bytes @0x12322E0 <BV240 0xa000000500000000e000000500000000a0d9010100000000e06900010000>
30 bytes @0x12322E0 1104279417543370902724876840660642573526253163889186603980666106986692608
```

**Comment by schieb** [comment]
@frapik99 I suggest that you read up on lazy binding and the PLT/GOT. Then step through an example in a debugger.

In short, the indirect jump target will originally be the very next instruction in that stub which will first push an identifier and then pass control to the dynamic linker. The dynamic linker will pop the identifier, use it to locate the function you are trying to call (`malloc`), copy the address of that function to the GOT slot that is used in `0x7ffff7bab100  <malloc@plt+0>  jmp QWORD PTR [rip+0x22d1da]`, and jump into `malloc`.

Next time your code calls `malloc` via the PLT, its address has already been resolved and placed into the GOT, so control will flow (in)directly to `malloc`.

**Comment by rhelmot** [comment]
I've not been paying attention to this thread, if there are problems with lazy evaluation, you can make linux's behavior match angr's by setting the environment variable `LD_BIND_NOW=1`

**Comment by frapik99** [comment]
thanks @schieb and @rhelmot I'll follow your suggestions and let you know my progresses :)

Thanks again

**Comment by frapik99** [comment]
Solved thanks. It was my fault. Thanks for the suggstion @schieb
