### ISSUE TITLE
"real" execution different from the "symbolic" execution

### ISSUE THREAD

**Issue by frapik99** [angr/angr#383]
Hi,
I have statically compiled ```pngpixel``` via this command ```gcc pngpixel.c -o pngpixel -static -lpng -lz -lm```. While I was comparing the symbolic execution with the "real" one within the ```libc_start_main``` function I noticed a difference in the flow:

```
gef➤  disas __libc_start_main
Dump of assembler code for function __libc_start_main:
   0x000000000043bd10 <+0>:	push   r13
   0x000000000043bd12 <+2>:	push   r12
   0x000000000043bd14 <+4>:	xor    eax,eax
   0x000000000043bd16 <+6>:	push   rbp
   0x000000000043bd17 <+7>:	push   rbx
   0x000000000043bd18 <+8>:	mov    rbp,rdx
   0x000000000043bd1b <+11>:	mov    r12,rcx
   0x000000000043bd1e <+14>:	mov    r11d,esi
   0x000000000043bd21 <+17>:	mov    r10,rdi
   0x000000000043bd24 <+20>:	sub    rsp,0x28
   0x000000000043bd28 <+24>:	cpuid  
   0x000000000043bd2a <+26>:	cmp    ebx,0x756e6547
   0x000000000043bd30 <+32>:	mov    DWORD PTR [rip+0x2fb44e],eax        # 0x737184 <_dl_x86_cpu_features+4>
   0x000000000043bd36 <+38>:	mov    DWORD PTR [rsp+0x10],0x0
   0x000000000043bd3e <+46>:	sete   sil
   0x000000000043bd42 <+50>:	cmp    ecx,0x6c65746e
   0x000000000043bd48 <+56>:	mov    DWORD PTR [rsp+0x14],0x0
=> 0x000000000043bd50 <+64>:	sete   al
   0x000000000043bd53 <+67>:	mov    DWORD PTR [rsp+0x18],0x0
   0x000000000043bd5b <+75>:	test   sil,al
   0x000000000043bd5e <+78>:	je     0x43bd6c <__libc_start_main+92>
```

The "real" execution does not take the jump at ```0x000000000043bd5e``` but the symbolic execution yer. Can you help me to understand why please?

Suppose this is a bug... is there a way that I can force the execution to not take that jump?

I have attached the file because I think you will need it.

Thanks
[pngpixelstatic.zip](https://github.com/angr/angr/files/834764/pngpixelstatic.zip)

**Comment by zardus** [comment]
Ahh, I see. This looks like it's jumping based on the return of the `cpuid` instruction `cmp    ebx,0x756e6547` and `cmp    ecx,0x6c65746e` are checking for parts of "Genuine Intel" in little endian.

The cpuid stuff is implemented here: https://github.com/angr/simuvex/blob/master/simuvex/engines/vex/dirty.py#L28

My guess is that switching CPUID to the `CORRECT_amd64g_dirtyhelper_CPUID_avx_and_cx16` function would fly. To do this, you'd need to take out the line https://github.com/angr/simuvex/blob/master/simuvex/engines/vex/dirty.py#L63, change the name of `CORRECT_amd64g_dirtyhelper_CPUID_avx_and_cx16` to `amd64g_dirtyhelper_CPUID_avx_and_cx16`, and make sure that it's actually being run (by checking the IR of the block containing the `cpuid` instruction). Then at least this part should line up properly, I think.

**Comment by zardus** [comment]
I should add that we specifically return some baseline cpu for `cpuid` so that, given the choice, libc will use less-optimized, simpler-to-analyze versions of various functions; it's not just a random choice to add inconvenience into the process :-)

**Comment by frapik99** [comment]
Hi both,
@zardus I have done as you suggested and now the flow jumps to the correct address. Continuing to follow it i have spot another difference:

```
0x43bfd0  <__libc_start_main+704>  mov eax, DWORD PTR [rsp+0x1c]
0x43bfd4  <__libc_start_main+708>  add eax, DWORD PTR [rsp+0x14]
0x43bfd8  <__libc_start_main+712>  cmp eax, 0x2f
0x43bfdb  <__libc_start_main+715>  mov DWORD PTR [rsp+0x14], eax
0x43bfdf  <__libc_start_main+719>  ja 0x43c07c <__libc_start_main+876>   ← $pc	TAKEN [Reason: !C && !Z]
```

instead the symbolic execution does not take it and goes to ```0x43bfe5``` ( next instruction ). The function called before was ```_dl_x86_cpu_features```.

How do you think it can be fixed?

Thanks

**Comment by zardus** [comment]
I think a nicer way would be to hook that part of the code using `project.hook`. You can simply create a zero-length hook at 0x43bfd4 and write 0x2f into it to pass the comparison.

**Comment by frapik99** [comment]
Thanks @zardus I'll do it.
