### ISSUE TITLE
Add a hook on the return value of dlsym

### ISSUE THREAD

**Issue by Rlyown** [angr/angr#3834]
### Question

Hi!

There is a C language program using libdl. And  I want to add a hook on the external symbol `testRead` to capture the parameters of the function call. 

In this case, angr cannot find this symbol. Can I do it by changing the return value of dlsym? 

```c
#include <dlfcn.h>
#include <stdio.h>

#define LIBPATH "libfunc.so"

int main(int argc, char *argv[]) {
    void *handler = dlopen(LIBPATH, RTLD_LAZY);
    if (handler == NULL) {
        printf("ERROR:%s:dlopen\n", dlerror());
        return -1;
    }

    void (*testRead)(int) = dlsym(handler, "testRead");
    if (testRead == NULL) {
        printf("ERROR:%s:dlsym\n", dlerror());
        return -1;
    }

    testRead(1);

    dlclose(handler);
    return 0;
}
```

**Comment by ltfish** [comment]
You definitely can. You can also just add a hook right after it returns from `dlsym` and overwrites `rax` (assuming it's x86-64).
