### ISSUE TITLE
How to reduce constraints of a state or ban solver when symbolic execution？

### ISSUE THREAD

**Issue by WordDealer** [angr/angr#3835]
### Question

I have known that state.solver.add() can help me to add constraints，so I can avoid some paths。but I want to symbolic execution for every block，including the wrong path，so I need to reduce the constraints. I have tried to use all_successors instead of successors, but it will raise SimUnsatError("Got an unsat result") from e . Not only reduce constraints but also someway to ban solver when we are symbolic execution is useful. I need your help,thank you very much.

**Comment by ltfish** [comment]
To reduce constraints, you will want to modify `state.solver.constraints` (it's a list, so just remove constraints that you don't need), and then re-create child solvers by doing `state.solver._solver._solvers.clear()` (assuming you are using the default composite solver).

**Comment by rhelmot** [comment]
To "ban the solver" and allow exploration to continue down unsatisfiable paths, add the state option LAZY_SOLVES. This isn't a silver bullet, since sometimes the solver MUST be invoked in order to continue execution, for example, to handle symbolic memory indexing, but it'll do a lot.

**Comment by WordDealer** [comment]
[test.tar.gz](https://github.com/angr/angr/files/10864986/test.tar.gz)
this is the python and binaries file. my fianlly goal is to analyse all paths in a function, including some unsat paths

**Comment by WordDealer** [comment]
thank you very much  your answers is useful ,I will test them it in some bigger functions.
