### ISSUE TITLE
Loading an angrdb is slow

### ISSUE THREAD

**Issue by mborgerson** [angr/angr#3837]
### Description

Loading an angrdb for a non-trivial binary can take upwards of **20 seconds**. Apparently most of the time is spent just re-lifting blocks to determine instruction addresses. We should either make node reconstruction lazier or cache the addresses to reduce this insane startup cost.

![load_db py-2023-03-01T17:25:25-07:00](https://user-images.githubusercontent.com/8210/222299428-a74c40ef-01bf-4c17-b41d-8d7350a68d6a.svg)

Ideally saving and loading the db would be near-instant, but we can at least fix loading to begin with.

### Steps to reproduce the bug

An example benchmark:

```python
#!/usr/bin/env python
import angr
from angr.angrdb import AngrDB
import os.path
import time

bin_path = '/usr/bin/qemu-mips'

time_start = time.time()
proj = angr.Project(bin_path, auto_load_libs=False)
proj.analyses.CFGFast(normalize=True)
time_end = time.time()
print(f'Creating project took {time_end - time_start:.3f} seconds')

db_path = os.path.basename(bin_path) + '.adb'
time_start = time.time()
angrdb = AngrDB(project=proj)
angrdb.dump(db_path, kbs=[proj.kb])
time_end = time.time()
print(f'Saving angrdb took {time_end - time_start:.3f} seconds')

time_start = time.time()
db = AngrDB()
db.load(db_path)
time_end = time.time()
print(f'Loading angrdb took {time_end - time_start:.3f} seconds')
```

```
Creating project took 66.311 seconds
Saving angrdb took 9.528 seconds
Loading angrdb took 24.057 seconds
```

### Environment

angr @ cb6f234a04b94e81954c74d79ce49c6711ea54b2

**Comment by ltfish** [comment]
With #3857:

```
Creating project took 186.788 seconds
Saving angrdb took 9.995 seconds
Loading angrdb took 14.440 seconds
```
