### ISSUE TITLE
stat on non-existing file

### ISSUE THREAD

**Issue by lks9** [angr/angr#3889]
### Description

When symbolically executing the following binary, angr does not execute the if-clause and explores only the else-branch with output "nothing\n". However, when executing the binary it prints "c0de\n".

Binary:

[stat_test.zip](https://github.com/angr/angr/files/11138282/stat_test.zip)

The code is here:

```C
#include <stdio.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

int main(int argc, char **argv) {
    struct stat statbuf;
    if (stat("FILE_DOES_NOT_EXIST.txt", &statbuf) < 0) {
        printf("c0de\n");
    } else {
        printf("nothing\n");
    }
    return 0;
}
```

### Steps to reproduce the bug

I am actually not sure if this is a bug or just needs some different configuration. You can use the following python script:

```python
import angr
p = angr.Project("stat_test")
simgr = p.factory.simgr()
simgr.explore(find = lambda s: s.posix.dumps(1) == b'c0de\n')
# <SimulationManager with 1 deadended>
simgr2 = p.factory.simgr()
simgr2.explore(find = lambda s: s.posix.dumps(1) == b'nothing\n')
# <SimulationManager with 1 found>
```

Expected: explore finds both c0de and nothing.

### Environment

Just the default.

### Additional context

This comes from the https://github.com/lks9/src-tracer, when trying to replay the busybox binary, see also #3883. The code above is simpler but bears the same problem I have when replaying a trace I recorded from busybox. Busybox wants to open `/etc/busybox.conf` which does not exist on my computer, so the syscall `SYS_stat` returns `-2`.

I am not using `state.fs.mount` for a concrete filesystem because I want to keep the filesystem abstract/symbolic.

**Comment by rhelmot** [comment]
Try removing the state option `angr.options.ALL_FILES_EXIST`?

**Comment by lks9** [comment]
Even with ALL_FILES_EXIST I get the same result:

```python
import angr
p = angr.Project("stat_test")
state = p.factory.full_init_state()
state.options["ALL_FILES_EXIST"]= False
simgr = p.factory.simgr(state)
simgr.explore(find = lambda s: s.posix.dumps(1) == b'c0de\n')
# <SimulationManager with 1 deadended>
simgr2 = p.factory.simgr(state)
simgr2.explore(find = lambda s: s.posix.dumps(1) == b'nothing\n')
# <SimulationManager with 1 found>
```

**Comment by rhelmot** [comment]
can you try creating the state with `remove_options={angr.options.ALL_FILES_EXIST}`? some options only take effect at state creation time.

**Comment by lks9** [comment]
Now I tried and got the same result again.

**Comment by rhelmot** [comment]
Looks like our stat implementations don't know how to do anything other than succeed.

**Comment by rhelmot** [comment]
https://github.com/angr/angr/blob/fa1a54764dac03fa2ac3b94cb8b3de6326865853/angr/procedures/linux_kernel/fstat64.py

**Comment by lks9** [comment]
Thank you very much for looking into it. Ideally, there would be three options:

1) All unknown files exists. This is the current behavior for `open` with `ALL_FILES_EXIST` and for `stat` regardless of the settings.
2) Only explicitly known files exists. This is the current behavior for `open` without `ALL_FILES_EXIST`.
3) No assumptions on unknown files, which would meen that any unknown file might or might not exists. I would suggest a new option `ANY_FILE_MIGHT_EXIST`.

Only if with option 3 all possible execution paths could be explored without assuming the existance or non-existance. The execution path would split when trying to `open` or `stat` such a file.

**Comment by rhelmot** [comment]
That would be very very complicated - it's difficult to split the state at the level of abstraction that makes decisions about the filesystem. The only thing I can think of is that you would have to either a) raise an exception indicating the state needs to be split and restart the step with two states, or you can modify every single filesystem simprocedure to respect this option.

**Comment by lks9** [comment]
Ok, for `open` I now have draft in #3895. I found out that there is actually no need to split the state since a symbolic result for `open` is sufficient. The result value could includes -1 and any fd value. When trying to do something with this symbolic fd (e.g. `read`), the fd gets constrained to a concrete value by pre-existing angr-magic.

I have also thought about `stat` which is basically identical to `open` and `fstat` on the result, only with a different errno if file does not exist. I think 90% of code does not care about the specific errno, so if fixing `stat` is too complicated one could simply emulate it within angr using `open` and `fstat`.

**Comment by rhelmot** [comment]
hm... that works, but I really do not like the reliance on "pre-existing angr magic". If I were you, I would actually run the `open` all the way through to the end, allocating a file descriptor, and then return `claripy.If(file_exists, fd, -1)`. That way you're guaranteed that any future operations on the file descriptor (if it is concretized to the exists-case) will actually touch the right file in the underlying emulated system.

**Comment by lks9** [comment]
Ok, I ended up implementing it as you suggested. It was much more to change than initially anticipated. I hope this can be of use, I also added a test case but I can't make any guarantees that the code is actually well-behaved in all corner cases.
