### ISSUE TITLE
Share libc SimProcedures across OS's

### ISSUE THREAD

**Issue by schieb** [angr/angr#389]
There has been much time and effort spent developing the libc SimProcedures. It is kind of a shame that we cannot *easily* use them on an arbitrary `SimOS`. One problem is that many of the more complex SimProcedures access both the `posix` and the `libc` plugins, and obviously, using a version of libc does not imply posix compliance. Of course, there will be many variations in individual procedures across actual implementations of the C standard library (e.g., glibc vs. BSD libc vs. msvcrt) but there are certainly a lot that overlap considerably, if they are not completely identical (from our point of view). With the [future posix abstractions](https://github.com/angr/simuvex/issues/71) in mind, now would be a good time to start adding abstractions to the libc SimProcedures.

I recently spoke with @ltfish who imagined a three layered approach:

> - *very* abstracted cores, like s_format.py. I believe string operations (like `strlen`, `strcpy`) and memory operations (`memcpy`, `malloc`, `free`) should have their cores implemented as such.
> - SimProcedures. those are real implementations that use those cores and implement a library method. If those SimProcedures are important, they should be made platform-independent (instead of `libc.so.6`, we simply put its library name as `libc` or `angr-libc`)
> - light weight wrappers around SimProcedures, which allows you to easily reuse any existing SimProcedures on any other OS, or any other library implementation.

Feel free to discuss your ideas/concerns here!

**Comment by zardus** [comment]
In general, this sounds good. I like the idea of a `simuvex.utils` or something with stuff like SimFormat, utilities to get a strlen, a symbolic heap model, and so on.

Do we really need the middle piece, though? If we have a generalized "abstract" strlen, can't we just have single-line SimProcedure that calls it? I might be missing something here.

**Comment by rhelmot** [comment]
Oh we actually solved this! Good stuff.
