### ISSUE TITLE
Caller not returning expected results

### ISSUE THREAD

**Issue by bannsec** [angr/angr#39]
Hey,

I've been working on understanding the Caller surveyor, and in doing so used the "npc" challenge from HITCON 2015 as the example. In that challenge, the first part contains a very convoluted function that effectively just checks the length of the input.

When I force the answer with "callable", I can find one path that returns non-zero (input 88). However, when I use "Caller", it returns informing me that the only path that should ever return is 0x0.

Here are the steps to recreate:

import angr
b = angr.Project("npc")
p = b.factory.path()
length = p.state.memory.load(0x1000,4)
c = b.surveyors.Caller(0x402980,(0x1000,),start=p)
print tuple(c.iter_returns())

NPC File: http://filebin.ca/2KtRrvR9YhZf/npc

**Comment by rhelmot** [comment]
@zardus callable doesn't use caller internally, I don't even know how caller works anymore... does this look like anything but code rot to you?

Owlz: it's very possible caller is just broken and you shouldn't use it. I mean you shouldn't use it, period, callable is a much more polished interface that's been given a lot more maintenance. I don't know what the correct behavior of NPC is, again, zardus can help there.

**Comment by Owlz** [comment]
Does callable allow you to do similar things to Caller? For instance, in theory the ability to map the possible outcomes of a function seems handy. Of course I could still do that a bit more manually by starting angr on that function as well. The only thing I've used callable for so far have been discrete questions where I give in an actual input instead of symbolic input.

**Comment by zardus** [comment]
Having that functionality in Callable somehow would be cool, but I think the whole point of Callable was to abstract that :-)

I'll take a look at Caller when I have a chance to try to at least track this down, but more design thought is definitely required.
