### ISSUE TITLE
Some Symbolic Execution Related Usage Questions

### ISSUE THREAD

**Issue by iceeeeee** [angr/angr#393]
Hi all,

I have some question during the use of angr symbolic execution. These questions may very basic.

1. When I use Path class and Path.step() function to do the symbolic execution on a binary, some path addresses are located in .rodata section of the binary. Do you have any idea how this happens?

2. I tried to use the following command to load the binary, I think all the shared libraries are also loaded. How could I make Path go into the library functions? During my test, the path didn't go into library.
`b=angr.Project(file_path)`

3. Could I ONLY load some specified libraries? Would the following command work? Or do you have any suggestion to load a specific library?:
`b = angr.Project(file_path, load_options={'auto_load_libs':False, 'force_load_libs': library_name})`

Thank you for your time.

**Comment by frapik99** [comment]
Hi @iceeeeee ,
I cannot answer to all your question but I hope  this can help:

Question 2:
If you want to do that I think you have to set ```'auto_load_libs': True```

Question 3:
I think angr uses the opposite approach, it loads everything except explicitly excluded. Please try using ```load_options={'skip_libs': ['shared.so']}```

Thanks

**Comment by zardus** [comment]
Regarding the first problem, could you check the block *before* execution ends in rodata and see where it should be going? It's hard to speculate otherwise...

**Comment by iceeeeee** [comment]
@zardus @frapik99 Thanks, I can try to figure problem 1 out by myself. 

I have another question. When I try to run concolic execution, I pass the argument to angr by the following method:
`state = b.factory.entry_state(args=list_of_args)`
Is this the right way to pass the argument to angr?

There is a case that the argument passed to angr is a file, in which case the symbolic execution engine would use too much resources and hard to finish. For the same binary, without passing any argument to it could be easily finished. My guess is that when passing a file as an argument, angr would make every data read from that file as a symbol which exhausted resource. Is it correct?

My question is, what is the reason that without passing a file as an argument would let the symbolic execution easily finished? And would the traces get from this case be correct?
What's more, if I need a file as an argument to do the concolic execution by angr, what should be the right way to do it?

Thanks

**Comment by frapik99** [comment]
@iceeeeee , I would guess that probably, due to the fact you don't pass the proper number/type of parameters, the executions terminates prematurely. Consider a case there your project does something like:

```
if ( argc < 3 )
   exit(0);
```

My suggestion is to pass the file as necessary and use a ```step_func``` in order to see if there is a path explosion or similar. Please not that angr has also ```concrete_fs``` but I don't know if this would help to solve your problem.

Thanks
