### ISSUE TITLE
How to handle indirect jump?

### ISSUE THREAD

**Issue by shelvenzhou** [angr/angr#395]
For assembly like `call    dword ptr [edx+1Ch]`, in which `edx` itself is a symbolic value, angr will go unconstrained, is there any way to handle this? E.g. like any way to hook the indirect jump with certain offset

**Comment by zardus** [comment]
angr can definitely handle this if there are reasonable constraints on `edx`. It only gives up if the symbolic formula representing `edx` has too many solutions (currently, this is arbitrarily set to over 256). If there are *no* constraints on edx, where would you want angr to jump? That info might help form a possible approach to fixing your problem.

**Comment by shelvenzhou** [comment]
@zardus yes I can understand the situation. 
This question can be linked with #396 . I'm facing with a complicated struct which is not easy to manually construct, so I try to re-use the constructor through `factory.callable()`, and so the constraints can be passed when encountered with indirect jump.
Any suggestions for this target? Because this kind of problems is barely involved in the examples from the docs. Thanks!

**Comment by zardus** [comment]
My suggestion would be to make sure that `edx` has proper constraints on it. When angr goes unconstrained, can you check the constraints (in `state.se.constraints`) on `edx`, the max and min values of it, and so on?

**Comment by shelvenzhou** [comment]
@zardus since I have to skip the construction of the object to get rid of path exploration, it seems to hard to depend on the constraints on `edx`.
So my solution is to use breakpoint to inspect the jump target before exit basic block, and directly set the `eip` and `eax` to "fake return".

**Comment by zardus** [comment]
That sounds reasonable, yeah. You can also use a hook for this, if you know where the return happens.
