### ISSUE TITLE
PointerWrapper is missing

### ISSUE THREAD

**Issue by shelvenzhou** [angr/angr#396]
At the bottom of https://docs.angr.io/docs/structured_data.html, `b.factory.callable.PointerWrapper` is mentioned if I try to pass a pointer to the Callable, but in angr 6.7.1.31, it seems that it is missing.
Now I try to make a constructor Callable, and use it to init an object. The constructor is in the form of `bool MyClass(void *this)`. So how can I allocate an BVV, pass its address to it and let it init my object? Thanks.

**Comment by rhelmot** [comment]
```python
>>>> import angr
>>>> p = angr.Project('/bin/true')
>>>> p.factory.callable.PointerWrapper
<class 'simuvex.s_cc.PointerWrapper'>
>>>> 
```

It looks like it exists just fine to me?

**Comment by shelvenzhou** [comment]
eh, my bad. Thanks!
