### ISSUE TITLE
Too Much Python, Do God's Work

### ISSUE THREAD

**Issue by trustednstaller** [angr/angr#3967]
### Description

`angr` - amazing.  No doubt about it.  The granularity and modularity of the design is to be admired.  I get it, initially probably easier to get things up and rolling with the Python, but it is enough. Let's port `angr` to a native language - rust, zig, etc. - and get serious here.

**Comment by rhelmot** [comment]
lol

We're working on it. The truth of the matter is that we don't believe all of angr is mature enough to solidify it by rewriting in not-python. All the basic components, like claripy, memory, and stepping, will be replaced eventually.

**Comment by rhelmot** [comment]
I will say I appreciate the sheer gall it takes to come into an open source project and be like "yo please rewrite this whole thing" but you do have to understand this is a gigantic undertaking and is unlikely to be completed anytime soon. We have an in progress rewrite of claripy in c++ publicly availability, but it has huge problems in terms of maintainability and having to bow to the complexity of how people used it in python.

**Comment by ltfish** [comment]
Python will continue to play a big role in angr's code base while we gradually migrate angr core into C++. Our major concern is for a Python-based implementation is performance, and we hope moving the angr core into C++ will help solve this issue.

Please come to visit the angr code base in a few years to appreciate a more native implementation of angr.

**Comment by ltfish** [comment]
> Let's port angr to a native language

I noticed that you used "Let's." Do let us now if you want to be part of this migration effort :)

**Comment by trustednstaller** [comment]
> > Let's port angr to a native language
> 
> I noticed that you used "Let's." Do let us now if you want to be part of this migration effort :)

Very perceptive, because I certainly do :) Anything here I could be involved in in porting the core of angr, I am more than happy to assist in. Sure, you can appreciate the gal but I didn't say "yo, please rewrite asap. k. thx. bye".  Just wanted to put it out there, as I said, you're doing God's work here. But in all seriousness, I would be interested in the porting efforts. DMs are open.

**Comment by trustednstaller** [comment]
And I understand the magnitude here, not implying this doesn't come with it's own headaches. Implying it's worth it to go through them

**Comment by ltfish** [comment]
I appreciate your enthusiasm!

> DMs are open.

I am not not exactly sure how to DM on GitHub. Please feel free to reach us at [angr-dev@asu.edu](mailto:angr-dev@asu.edu).
