### ISSUE TITLE
Z3 solver runs out of memory

### ISSUE THREAD

**Issue by lks9** [angr/angr#3972]
I have a problem with the Z3 solver using to much memory resources. As a result, the python process gets killed. simgr.explore() never returns.

If I use the LAZY_SOLVES option then everything goes through. However, when I run `s.satisfiable()` I get the same:

```
>>> simgr.deadended[0].satisfiable()
Killed
```

### Edit

Edit: I could finally was able to convert it into a simple angr example, see my second comment below. Actually, it seems like loading a bool value out of symbolic memory is too much...

### Questions:

* Any advises?
* Could this be a bug in angr?
* How can I see the input to the Z3 solver?
* Is there an option for angr to prevent running out of memory? It would be a bit more helpful if angr kills Z3 instead of linux killing the python process.

Thanks in advance!

### Binaries and Scripts:

~~I am sorry, but I could not convert this into a simple angr example.~~ (**see my second comment**)

I am using my [src-tracer](https://github.com/lks9/src-tracer) but underneath is angr. And angr calls `z3_solver_sat` (actually, very often but there is one place where it gets stuck every time).

The binaries `busybox_trace` and `busybox_retrace` are compiled from musl-libc and busybox using the instructions [src-tracer](https://github.com/lks9/src-tracer). Then the `xxxx.trace` was created by running
```
busybox_trace echo hello
```

The `retrace.py` is in my [src-tracer](https://github.com/lks9/src-tracer). The function `check_suid` in the recorded (sub)trace is [here](https://github.com/mirror/busybox/blob/1_34_stable/libbb/appletlib.c#L553). This function calls getgid which can be found [here](https://github.com/bminor/musl/blob/f5f55d6589940fd2c2188d76686efe3a530e64e0/src/unistd/getgid.c#L4):

The binaries and the trace: 
[echo.tar.gz](https://github.com/angr/angr/files/11533659/echo.tar.gz)

```
$ retrace.py busybox_retrace 2023-05-22-142045-24703813-appletlib.c.trace --seek 217
DEBUG    | 2023-05-22 18:08:26,590 | src_tracer.retrace | Starting with function "check_suid"
DEBUG    | 2023-05-22 18:08:26,685 | src_tracer.retrace | Fbdd check_suid --count 0
DEBUG    | 2023-05-22 18:09:30,721 | src_tracer.retrace | N
DEBUG    | 2023-05-22 18:09:30,743 | src_tracer.retrace | F4c6 getgid --count 3
DEBUG    | 2023-05-22 18:09:30,749 | src_tracer.retrace | R --count 6
DEBUG    | 2023-05-22 18:09:30,759 | src_tracer.retrace | F4b __syscall0 --count 7
DEBUG    | 2023-05-22 18:09:30,774 | src_tracer.retrace | R --count 9
Killed
```

With `--add-options LAZY_SOLVES` it goes through. The deadended state is correct, as the function returned. However, when I call `satisfiable()`, python still gets killed.

```
$ python -i retrace.py busybox_retrace 2023-05-22-142045-24703813-appletlib.c.trace --seek 217 --add-options LAZY_SOLVES
DEBUG    | 2023-05-22 18:26:11,413 | src_tracer.retrace | Starting with function "check_suid"
DEBUG    | 2023-05-22 18:26:11,500 | src_tracer.retrace | Fbdd check_suid --count 0
DEBUG    | 2023-05-22 18:26:11,518 | src_tracer.retrace | N
DEBUG    | 2023-05-22 18:26:11,527 | src_tracer.retrace | F4c6 getgid --count 3
DEBUG    | 2023-05-22 18:26:11,532 | src_tracer.retrace | R --count 6
DEBUG    | 2023-05-22 18:26:11,541 | src_tracer.retrace | F4b __syscall0 --count 7
DEBUG    | 2023-05-22 18:26:11,553 | src_tracer.retrace | R --count 9
DEBUG    | 2023-05-22 18:26:11,570 | src_tracer.retrace | N
DEBUG    | 2023-05-22 18:27:12,057 | src_tracer.retrace | N
DEBUG    | 2023-05-22 18:27:12,070 | src_tracer.retrace | T
DEBUG    | 2023-05-22 18:27:12,080 | src_tracer.retrace | F4e7 setgid --count 11
...
DEBUG    | 2023-05-22 18:27:13,431 | src_tracer.retrace | F1093 llist_free --count 185
DEBUG    | 2023-05-22 18:27:13,448 | src_tracer.retrace | N
DEBUG    | 2023-05-22 18:27:13,454 | src_tracer.retrace | R --count 188
DEBUG    | 2023-05-22 18:27:13,468 | src_tracer.retrace | R --count 189
WARNING  | 2023-05-22 18:27:13,476 | src_tracer.retrace | Could not find F at all in simgr <SimulationManager with 1 deadended>

>>> simgr.deadended[0].satisfiable()
Killed
```

**Comment by lks9** [comment]
Sorry, I figured out what the problem was:

```Python
import angr
import claripy
p = angr.Project("busybox_retrace")
state = p.factory.blank_state()

state.solver.eval_upto(state.mem[p.loader.main_object.get_symbol("suid_cfg_readable").rebased_addr].bool.resolved, 2)
# [False]

# make all globals symbolic
sections = p.loader.main_object.sections
for section in sections:
    if section.name == ".data" or section.name == ".bss":
        data = state.solver.BVS("data", 8*(section.max_addr- section.min_addr))
        state.memory.store(section.min_addr, data)

state.solver.eval_upto(state.mem[p.loader.main_object.get_symbol("suid_cfg_readable").rebased_addr].bool.resolved, 2)
# Killed
```

The last part, I got from #3715. Any ideas?

**Comment by rhelmot** [comment]
Oh, yeah, you're creating a BVS that's really really big. When you try to solve for just a slice of it, z3 will try to construct a satisfiable value for the whole bigint, which is extremely not a good idea. You should store one BVS per byte, or better, one BVS per bss symbol.

**Comment by lks9** [comment]
Thank you very much for the super fast answer!! 

> You should store one BVS per byte, or better, one BVS per bss symbol.

I got it working with per byte! Per symbol would be a lot harder to implement because there are a lot with different types and sizes.

```Python
import angr
import claripy
p = angr.Project("busybox_retrace")
state = p.factory.blank_state()

state.solver.eval_upto(state.mem[p.loader.main_object.get_symbol("suid_cfg_readable").rebased_addr].bool.resolved, 2)
# [False]

# make all globals symbolic
sections = p.loader.main_object.sections
for section in sections:
    if section.name == ".data" or section.name == ".bss":
        for i in range(section.max_addr- section.min_addr):
            data = state.solver.BVS("data" + str(i) + section.name, 8)
            state.memory.store(section.min_addr + i, data)

state.solver.eval_upto(state.mem[p.loader.main_object.get_symbol("suid_cfg_readable").rebased_addr].bool.resolved, 2)
# [False, True]
```
