### ISSUE TITLE
Multiple errors with CFGFast and SimProcedures

### ISSUE THREAD

**Issue by axt** [angr/angr#399]
When calling a SimProcedure the following problems occur:
- return edges are added to the PLT-node instead of the simprocedure
- an extra UnResolvableTarget node is added to the PLT nodes.

I've created a very simple example:
```
int main () { f(); }

int f () {
  FILE * file = fopen("binary", "rb");
  fclose (file);
  return 0;
}
```
Here is the generated CFG

:

![cfgasm](https://cloud.githubusercontent.com/assets/759365/24255229/2c5db678-0fe5-11e7-8a16-70d70730a29f.png)

**Comment by ltfish** [comment]
I also noticed this issue several days ago. I'll fix it in my own `fix/function_returning_checks` branch soon.

**Comment by axt** [comment]
@ltfish I've checked your branch `fix/function_returning_checks`. I know its still in progress, but maybe these could help (maybe it has also something to do with the wrong return edges). 

Noticed that the knowledge base of `CFGFast` and `CFGAccurate` is different. (I assume it shouldn't be.)

Please have a look on it:
```
<CFGAccurate Analysis Result at 0x7f48b1710350>
#PLT node
In : project.kb.functions[freadplt]
Out: <Function fread (0x80483b0)>
In : project.kb.functions[freadplt].transition_graph.nodes()
Out: [<BlockNode at 0x80483b0 (size 6)>, <Function fread (0x9000030)>]
In : project.kb.functions[freadplt].endpoints
Out: []

#SimProcedure node
In : project.kb.functions[fread]
Out: <Function fread (0x9000030)>
#__repr__ of HookNode throws an exception because self.size is None
In : map(type,project.kb.functions[fread].transition_graph.nodes())
Out: [angr.knowledge.codenode.HookNode]
#__repr__ of HookNode throws an exception because self.size is None
In : map(type,project.kb.functions[fread].endpoints)
Out: [angr.knowledge.codenode.HookNode]
```

```
<CFGFast Analysis Result at 0x7fb7debb6350>
#PLT node
In : project.kb.functions[freadplt]
Out: <Function fread (0x80483b0)>
In : project.kb.functions[freadplt].transition_graph.nodes()
Out: [<HookNode <class 'simuvex.procedures.libc___so___6.fread.fread'> at 0x9000030 (size 0)>, <BlockNode at 0x80483b0 (size 6)>]
In : project.kb.functions[freadplt].endpoints
Out: [<BlockNode at 0x80483b0 (size 6)>]

#SimProc node
In : project.kb.functions[fread]
Out: <Function fread (0x9000030)>
In : project.kb.functions[fread].transition_graph.nodes()
Out: [<HookNode <class 'simuvex.procedures.libc___so___6.fread.fread'> at 0x9000030 (size 0)>]
In : project.kb.functions[fread].endpoints
Out: []
```

**Comment by axt** [comment]
After branch merge:

- The `UnresolvableTarget` nodes disappear
- The return edges are still added to the PLT instead of the SimProcedure

![cfgfst_asm](https://cloud.githubusercontent.com/assets/759365/25096254/baa61ac4-239f-11e7-96ad-755234ef9744.png)

**Comment by axt** [comment]
Seems fixed on branch, thanks!

**Comment by ltfish** [comment]
The branch is merged to master. I'm closing this issue.
