### ISSUE TITLE
Problems when install in windows

### ISSUE THREAD

**Issue by vancaho** [angr/angr#40]
Hi, As I work on windows platform, so I follow the instructions to install angr in windows. I download the z3 binary and copy it to C:\Z3\ path, and set Z3PATH=C:\Z3\bin, and install the capstone for python binary(capstone-3.0.4-python2.7-win32.exe). Then I run "pip install angr" command.
The command returns the following error:

  Running setup.py install for angr-z3
    Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;**file**='c:\users\ppaw\appdata\local\temp\pip-build-s6b3rp\angr-z3\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\ppaw\appdata\local\temp\pip-5nvyuf-record\install-record.txt --single-version-externally-managed --compile:
    WARNING: '' not a valid package name; please use only.-separated package names in setup.py
    running install
    running build
    Configuring Z3
    error: [Error 193] %1 is not a valid win32

```
----------------------------------------
```

Command "C:\Python27\python.exe -c "import setuptools, tokenize;**file**='c:\users\ppaw\appdata\local\temp\pip-build-s6b3rp\angr-z3\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\ppaw\appdata\local\temp\pip-5nvyuf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\ppaw\appdata\local\temp\pip-build-s6b3rp\angr-z3

How to solve the above error? Thanks very much

**Comment by rhelmot** [comment]
I've never successfully installed angr from pip on Windows, and I have no
idea how to parse that error... I would recommend installing directly from
the repositories.

None of us that are involved in the distribution of angr are very
Windows-savvy, sorry...

**Comment by vancaho** [comment]
I install z3 manually, then can I remove the Z3 requirement and continue installation?

**Comment by rhelmot** [comment]
Yes, that should help. It might be necessary, in fact.

**Comment by vancaho** [comment]
How to remove the Z3 from the requirement and continue? As I use the "pip install angr" command to install angr, I cannot find the requirement.txt file.

**Comment by rhelmot** [comment]
I strongly recommend not using the pip distribution, but if you really want
to you can probably tell pip to ignore all dependencies and install only
the package specified. You'll have to manually do this for all
dependencies, though.
