### ISSUE TITLE
install angr on a python3.9:alpine3.18 docker image

### ISSUE THREAD

**Issue by ducorduck** [angr/angr#4017]
### Question

Hi, 
I'm trying to install angr on a python3.9:alpine3.18 docker image. After manually installing all requirement package with 
`apk add --no-cache python3-dev py3-setuptools build-base libxml2-dev libxslt-dev git libffi-dev cmake readline-dev libtool debootstrap debian-archive-keyring glib-dev pixman-dev qt5-qtdeclarative-dev nasm libressl-dev` 
and archinfo, pyvex, cle, claripy and ailment, 
i installed angr with `pip install angr` and encounter this error 
```
Building wheel for angr (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for angr (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      <string>:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      running bdist_wheel
      running build
      Building angr_native
      cc -O3 -fPIC -c -o log.o log.c
      g++ -O3 -fPIC -std=c++11 -I "/tmp/pip-build-env-tj867hfy/overlay/lib/python3.9/site-packages/unicorn/include" -I "/tmp/pip-build-env-tj867hfy/overlay/lib/python3.9/site-packages/pyvex/include" -o angr_native.so log.o sim_unicorn.cpp -lunicorn -lpyvex -L "/tmp/pip-build-env-tj867hfy/overlay/lib/python3.9/site-packages/unicorn/lib" -L "/tmp/pip-build-env-tj867hfy/overlay/lib/python3.9/site-packages/pyvex/lib" -shared
      In file included from /usr/include/limits.h:40,
                       from /usr/include/fortify/stdlib.h:30,
                       from /usr/include/c++/12.2.1/cstdlib:75,
                       from /usr/include/c++/12.2.1/bits/stl_algo.h:69,
                       from /usr/include/c++/12.2.1/algorithm:61,
                       from sim_unicorn.cpp:4:
      sim_unicorn.hpp:17:23: error: expected unqualified-id before numeric constant
         17 | static const uint16_t PAGE_SIZE = 0x1000;
            |                       ^~~~~~~~~
      make: *** [Makefile:40: angr_native.so] Error 1
      error: Error while building angr_native: Command '['make']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for angr
  Building wheel for psutil (pyproject.toml) ... done
  Created wheel for psutil: filename=psutil-5.9.5-cp39-abi3-linux_x86_64.whl size=277007 sha256=8b495364e46c6a67e357c9d59023d9f799b964e30e661fa1d2ef0d2e94b81049
  Stored in directory: /root/.cache/pip/wheels/74/d1/7d/d9ae7d9aea0f1cebed73f37868df7b5f3333e7f30163b3e558
Successfully built psutil
Failed to build angr
ERROR: Could not build wheels for angr, which is required to install pyproject.toml-based projects
```
Any insight on how to fix it?

**Comment by ducorduck** [comment]
Hello, 
Since it has been quite a while from the time this was posted, any comment would be very much appreciated.

**Comment by twizmwazin** [comment]
The error is in building the unicorn package, not angr. If you're looking for an easy solution, use a glibc based distro (ubuntu, debian, fedora, are all fine) and then you won't need to deal with compiling anything since pre-built wheels are available. If you really want to use alpine, you would need to solve the unicorn issue or you could modify angr to install without building angr_native and skip the unicorn dependency.

**Comment by ltfish** [comment]
I tried to look into this issue but do not have cycles until a week from now. I suspect the problem is related to stdint.h on Alpine. Switching to a different distro will allow you to use wheels, which should be a quick solution for now.

**Comment by lks9** [comment]
Thank you for the insight. We explicitly chose alpine because we could succesfully instrument musl and other packages using our source tracer to record the control flow trace. Instrumenting glibc did not work at that point. The replay step is using angr, so it would be convenient to have angr run in alpine, too. Alternative would be to do the instrumentation, compilation and recording on a different computer than the replay step.

We do not use unicorn, so this would be fine. How do we modify angr to skip the unicorn dependency? Perhaps this is not too hard?

**Comment by twizmwazin** [comment]
It should be as simple as commenting out unicorn as a dependency in project.toml, setup.cfg, and the call to _build_native in setup.py. We would like to support this at some point in the future so if you run into any surprises while doing this, feedback would be appreciated.

**Comment by stef** [comment]
the problem is that musl defines PAGE_SIZE in limits.h, 

if you change https://github.com/angr/angr/blob/master/native/sim_unicorn.hpp#L17
into 
```c
static const uint16_t ANGR_PAGE_SIZE = 0x1000;
```

and later in the same file at https://github.com/angr/angr/blob/master/native/sim_unicorn.hpp#L482
```c
typedef taint_t PageBitmap[ANGR_PAGE_SIZE];
```

it all works as expected.

**Comment by rhelmot** [comment]
Good detective work! I'll commit that fix right away, thank you!

**Comment by stef** [comment]
glad to help! angr rocks! <3
so i have to thank you fine angr people!
