### ISSUE TITLE
pass struct type parameters in SimProcedure

### ISSUE THREAD

**Issue by XingweiLin** [angr/angr#403]
@ltfish 
When I want to pass `struct` type parameters to `self.call`, I wrapped elements into turple,but when the program dynamic run, it can only get the first element.
Testcase: 
![image](https://cloud.githubusercontent.com/assets/15721702/24343759/b88fac4c-12fa-11e7-8226-33397398565b.png)

Script:
![image](https://cloud.githubusercontent.com/assets/15721702/24343776/cd898b2c-12fa-11e7-97c7-0a568c6275d8.png)
![image](https://cloud.githubusercontent.com/assets/15721702/24343780/d82db5a8-12fa-11e7-9a4e-d321d16656d6.png)

Report:

> WARNING | 2017-03-27 14:25:52,130 | angr.path_group | No completion state defined for path group; stepping until all paths deadend
into Caller run.
into after_call.
<PathGroup with 1 deadended>
i is:1994
j is:0
0x4004d0L
0x4004a0L
0x4000020L
0x4006d0L
0x400450L
0x400465L
0x400703L
0x400708L
0x400590L
0x4005b8L
0x400530L
0x400552L
0x40071dL
0x400726L
0x4000030L
0x400661L
0x4005bdL
0x400490L
0x4000050L
0x4005f0L
0x400490L
0x4000050L
0x400604L

**Comment by XingweiLin** [comment]
source and binary files:
https://drive.google.com/file/d/0Bzz4AEqLq0iOMmpta25SZTVpQnM/view?usp=sharing
https://drive.google.com/file/d/0Bzz4AEqLq0iOZlNUTFdyTnQ2aGM/view?usp=sharing

**Comment by frapik99** [comment]
Hi @XingweiLin 
I'm sorry if I'm missing something but, in my head, it not clear what you are trying to achieve... Do you want to call func4 with an arbitrary value? Do you want to change it at runtime?

Thanks

**Comment by XingweiLin** [comment]
@frapik99 
Sorry, it's my fault. I didn't explain it clearly.
What I want to do is pass `struct` type parameters in `SimProcedure`, angr has a doc says that I can utilize tuples to contain the elements of `struct`.
`struct metaData {  int i;  int j;}`
I want to wrap two `int` type parameter into `tuple` and pass to `self.call`,but when I got the `stdout`,there was only the first element could be obtained by angr,which you can see the report:

> WARNING | 2017-03-27 14:25:52,130 | angr.path_group | No completion state defined for path group; stepping until all paths deadend
into Caller run.
into after_call.
<PathGroup with 1 deadended>
i is:1994
j is:0

This issue I have discussed with @ltfish ,and he said it's a bug of angr, and I should post it in github.
And I can utilize `SimStackArg` to avoid this bug.
So I post it to github, but didn't explain clearly, sorry.

**Comment by frapik99** [comment]
Hi @XingweiLin ,
no need to apologize :) So you consider your problem solved isn't it? I hope so :)

Thanks

**Comment by XingweiLin** [comment]
@frapik99 
Umm,
I haven't solved this problem although I use `SimStackArg`.
There are still some problems.

**Comment by frapik99** [comment]
Hi @XingweiLin ,
reviewing the ```test1``` project it seems that you want to call the ```func4``` when the ```main``` is called. I'm guessing this because the ```func4``` stays at the address ```0x4005bd```. Based on this guess I would suggest you to use a ```Hook```. Is it this code useful:

```
import angr

def print_params(state):
        print state.se.any_int(state.memory.load(state.regs.rdi,4, endness='Iend_LE'))
        print state.se.any_int(state.memory.load(state.regs.rdi+4,4, endness='Iend_LE'))

test1 = angr.Project("./test1", load_options={'auto_load_libs':False})
state = test1.factory.entry_state()
pg = test1.factory.path_group(state)
test1.hook(0x000000000040069a, print_params)
pg.explore()
```

```rdi``` is the pointer to the struct, so rdi+4 is the second value that you are looking for i think.

The output should be:

```
python test1.py 
1994
1993
```

HTH

**Comment by XingweiLin** [comment]
Hi @frapik99 
Thanks for your suggestion, but this isn't what I want.
I want to utilize `SimProcedure` to `Hook` a specified function and run the other binary function.
I need pass parameters to `self.call` in the static instrumentation process, instead of getting the original parameters.

**Comment by rhelmot** [comment]
The problem is that with no typing information, angr will assume that the integers passed in the struct are of type `long`, i.e. a full wordsize, and will therefore layout the struct incorrectly. The solution is to pass in a function prototype:

```python
import angr
import simuvex

class Caller(simuvex.SimProcedure):
    IS_FUNCTION = True

    def run(self, target_addr=None, target_cc=None):
        struct_data = simuvex.s_cc.PointerWrapper((1234, 5678))
        self.call(target_addr, [struct_data], 'after_call', cc=target_cc)

    def after_call(self, target_addr=None, target_cc=None):
        pass

def main():
    p = angr.Project('test')
    ty = simuvex.s_type.parse_defns('void foo(struct data {int i; int j;} *x);')['foo']
    cc = p.factory.cc(func_ty=ty)
    p.hook(p.kb.labels.lookup('main'), angr.Hook(Caller, target_addr=p.kb.labels.lookup('func4'), target_cc=cc))

    pg = p.factory.path_group()
    pg.run()
    print pg.one_deadended.state.posix.dumps(1)

if __name__ == '__main__':
    main()
```

This got me the following output:

```
i is 1234
j is 5678
```

**Comment by XingweiLin** [comment]
@rhelmot 
The code has a problem.
> Traceback (most recent call last):
  File "/home/lin/Desktop/angr/src/main/python/angr/analysisOther.py", line 39, in <module>
    cc = project.factory.cc(func_ty=ty)
  File "/home/lin/Desktop/angr-dev/angr/angr/factory.py", line 290, in cc
    func_ty=func_ty)
  File "/home/lin/Desktop/angr-dev/simuvex/simuvex/s_cc.py", line 786, in __init__
    super(SimCCSystemVAMD64, self).__init__(arch, args, ret_val, sp_delta, func_ty)
  File "/home/lin/Desktop/angr-dev/simuvex/simuvex/s_cc.py", line 233, in __init__
    self.func_ty = func_ty if func_ty is None else func_ty.with_arch(arch)
  File "/home/lin/Desktop/angr-dev/simuvex/simuvex/s_type.py", line 79, in with_arch
    return self._with_arch(arch)
  File "/home/lin/Desktop/angr-dev/simuvex/simuvex/s_type.py", line 496, in _with_arch
    out = SimTypeFunction([a.with_arch(arch) for a in self.args], self.returnty.with_arch(arch), self.label)
AttributeError: 'NoneType' object has no attribute 'with_arch'  
Process finished with exit code 1

**Comment by rhelmot** [comment]
I pushed an update to simuvex yesterday to resolve this problem.

**Comment by XingweiLin** [comment]
```
# go to angr-dev 
./git_all.sh pull
# if vex fails when do ./git_all.sh pull, do the following steps:
cd vex; git reset --hard origin/master
cd pydex; python setup.py build
cd simuvex; python setup.py build
```
