### ISSUE TITLE
Is AIL good as BNIL ?

### ISSUE THREAD

**Issue by alom4hdi** [angr/angr#4034]
### Question

Is AIL good as BNIL ?

**Comment by ltfish** [comment]
AIL is closer to HLIL in Binary Ninja IL I would say.

**Comment by alom4hdi** [comment]
@ltfish Can we access lower level of it like Binja ?
and another questions.
does angr support SSA ?
Can we use Angr for analysing large binaries ?

**Comment by mborgerson** [comment]
Block level IR can be accessed through IRSBs with `block.vex`. Yes angr supports SSA and can be used for large binaries.
