### ISSUE TITLE
Path.step() use too much resource

### ISSUE THREAD

**Issue by iceeeeee** [angr/angr#406]
Hi all,

I tried running symbolic execution on a 140 KB binary with a 1.3 MB library in a machine with 24GB memory. 

In some `path.step()`, the angr takes really a long time and uses really a lot of memory to move on.
In the end, the analysis is killed by system in one of `path.step()`. The reason is it uses too much memory.

I would be appreciate, if anyone could explain what part inside `step` function would use so much memory. And is there a way to solve this problem. For example, is it possible to predict if one step is able to solve according to the resources.

Thanks.

**Comment by zardus** [comment]
It's very hard to predict the amount of resources that will be used during a step. Plus, it heavily depends on the program you're analyzing. You might be running of memory in the constraint solver (mostly out of our control) or in the symbolic memory implementation, or a number of other reasons. A good first step would be to profile the process memory with one of the python memory profilers out there, then we can better reason about what's going on.

**Comment by frapik99** [comment]
@iceeeeee , my 2 cents, can you verify what instruction is considered when you do ```path.step()``` please? I had a similar problem while reading a file but using ```concrete_fs=True``` I was able to solve it.

Thanks

**Comment by iceeeeee** [comment]
@frapik99 , Thanks for your hints. I will verify the instruction again and let you know in a few days, I am really busy these days. Btw, where did you add `concrete_fs=True`? In `path.step(concrete_fs=True)`?

Thanks

**Comment by frapik99** [comment]
@iceeeeee , no it is an option that you can pass when you create a state ```ice.factory.full_init_state(..., concrete_fs=True,...)```

HTH
