### ISSUE TITLE
Interpret outputs of DDG

### ISSUE THREAD

**Issue by roj4s** [angr/angr#407]
After :  b = angr.Project('/bin/true', load_options={'auto_load_libs': False})
           cfg = b.analyses.CFGAccurate(keep_state=True)
           ddg = b.analyses.DDG(cfg)
          ddg.data_graph.nodes()[0]   # It outputs  A: <<Reg 144 8> @ <0x401646 0x401646(11)>>
         ddg.graph.nodes()[0]     # It outputs B: <0x403664 0x403645(44)>

Whats a interpretation of A and B, what each element stands for. Thanks in advance.

**Comment by axt** [comment]
As far as I know:

Nodes of the statement graph (B) are of type `CodeLocation`, which identifies an instruction in `VEX`.
Edges represent a dependency between two `VEX` instructions.

Check this example DDG statment graph of a simple program:
https://raw.githubusercontent.com/axt/angr-utils/master/examples/plot_ddg/simple1_ddg_stmt.png


Nodes of the data graph (A) are of type `ProgramVariable`, which is a pair of (`SimVariable`, `CodeLocation`, boolean). 

`SimVariable` can be 
- `SimRegisterVariable`,
- `SimTemporaryVariable`
- `SimMemoryVariable`, or its subclass `SimStackVariable`. 

CodeLocation is the same as above, and the third boolean parameter (called `initial`) is explained later.

Check `s_variable.py` in `simuvex` for more details on those. 

So the nodes represent a location in the program, where a given variable is read or written.  

Edges of the graph represent relations between the ProgramVariables. They have several types:
- use: using the previous definition of a variable (if its the first use of the variable, and no previous definition exists, then we indicate this through setting the initial flag to True)
- kill: overwriting the previous definition of a variable.
- mem_addr: using the variable as the address of a store/load operation
- mem_valu: using the variable as the value of a store operation

Check this example DDG data graph to get the concepts better:
https://raw.githubusercontent.com/axt/angr-utils/master/examples/plot_ddg/simple1_ddg_data.png

**Comment by Lightninghkm** [comment]
@axt Could you provide the pictures again because the links are expired, thanks.

**Comment by cq674350529** [comment]
@Lightninghkm You can find pictures through history commits of `angr-utils` repository, e.g. https://github.com/axt/angr-utils/tree/e17dd00f9e2077f14a5edf1c014658da183eaf4a . After this commit, the images are removed.
