### ISSUE TITLE
Docs search does not properly match substrings

### ISSUE THREAD

**Issue by zardus** [angr/angr#4070]
### Description

Docs search should search the API.

### Steps to reproduce the bug

Try searching for an API.

### Environment

docs.angr.io

### Additional context

I like to search for API.

**Comment by twizmwazin** [comment]
Fixed by contacting RTD support and disabling their custom search. Now API docs should be properly indexed by sphinx.

**Comment by twizmwazin** [comment]
See this issue for future followup: https://github.com/readthedocs/readthedocs.org/issues/10254
