### ISSUE TITLE
angr can't detect some of the functions in binary

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#41]
If you use `objdump` to disassemble the binary you can find `srec_scan` function. But with angr, I've extracted the CFG from the binary, in the `cfg.function_manager.functions`, I don't see `srec_scan` function.

Please find the binary in here: https://drive.google.com/file/d/0B5jqCZluyyOPaFRFM0c5RVBUazQ/view?usp=sharing

**Comment by ltfish** [comment]
This is because `CFG` does not take symbol addresses into consideration right now. This functionality will be added soon!
