### ISSUE TITLE
Procedures "strtol" may not work well on 64-bit program due to "max_strtol_len" limit

### ISSUE THREAD

**Issue by GhostFrankWu** [angr/angr#4102]
### Description

As max_strtol_len set to 11  ( [len(str(2**31)) + 1](https://github.com/angr/angr/blob/master/angr/state_plugins/libc.py#L1182) ), atol hook may not get correct result for constraint that need return value >= `0x2540be400`, which is a small value for 64-bit programs.  

### Additional context

Is this a feature for performance concern and need to be fixed manually by setting max_strtol_len for each libc plugin?

**Comment by ltfish** [comment]
It is because of performance concerns. You can adjust the limit according to your specific use cases.
