### ISSUE TITLE
A simple program which angr cannot solve.

### ISSUE THREAD

**Issue by 92wyunchao** [angr/angr#4129]
### Question

when I use angr to help me solve the input to reach 'find you', angr cannot give the right solution which should be a string including  'bbc'. In fact,  maybe once is the correct output in five times.
here is the c  source code.
`int main()
  {
    char arr1[20];
    char arr2[20];
    read(0,arr1,10);
    const char* arr3 = "bbc";
    strcpy(arr2,arr1);
    char* ret = strstr(arr2, arr3);
    if (ret == NULL)
    {
      printf("sorry\n");
    }
    else
    {
      printf("find you:%s\n", ret);
    }
    return 0;
  }
`

here is the angr script.
`p = angr.Project('./mytest',auto_load_libs=True)
 s = p.factory.entry_state()
 sm = p.factory.simgr(s)
 sm.explore(find=0x8049295)
 if sm.found:
     print(sm.found[0].posix.dumps(0))
`
I run the script many times, it It seems difficult for angr to give the correct answer. It seems to be related to strcpy function, because if I delete strcpy, everything is OK. To reproduce, I upload the built binary as an attachment.  
[mytest.zip](https://github.com/angr/angr/files/12512644/mytest.zip)

**Comment by mborgerson** [comment]
Thanks for reporting. This behavior is caused by a bug, I'll fix it.

**Comment by 92wyunchao** [comment]
Thanks for your work.
I run the angr script five times in the patched enviroment , but the relusts are as follows:
b'\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00'
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
b'bbc\x04\x00\x80\x00\x02\x00\x00'
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

we can see only the fourth result is right. It seems the problem still exists. This is really werid.

**Comment by mborgerson** [comment]
With the script and binary linked above, on my machine 5 runs are consistently correct:

```
b'bbc\x00\x00\x00 \x02 \x02'
b'bbc\x00\x00\x00 \x02 \x02'
b'bbc\x00\x02\x00@\x02\x80\x08'
b'bbc\x00\x00\x00 \x02\x00\x02'
b'bbc\x00\x00\x00 \x02 \x02'
b'bbc\x00\x00\x00 \x02\x00\x02'
```

Are you testing with the same script and binary sent originally above?
