### ISSUE TITLE
is there any way to run reaching defination analysis on ail graph?

### ISSUE THREAD

**Issue by za233** [angr/angr#4149]
### Question

I want to run dataflow analysis on ail graph, and found ReachingDefinationAnalysis which may meet my needs. But when I start using the interface it provides,i found out it can only support querying result for machine code and running on separated ail block. So I would like to know if there is a way to run on ail graph and directly query the result of the ReturningDefinition of a AIL statement.

**Comment by ltfish** [comment]
RDA on AIL is heavily used in angr decompiler but is extremely undocumented. Before I get time to document it properly, you probably want to take a look at how angr decompiler (especially clinic.py, ail_simplifier.py, and block_simplifier.py) are using RDA on AIL.
