### ISSUE TITLE
Symbolic execution on windows binary

### ISSUE THREAD

**Issue by otelo29200** [angr/angr#415]
Hey,

When I analyze fauxware.c given in the examples sections everything is ok when compiled in ELF. But if compile it in PE format, puts goes nuts and throw a bunch of error to tell it is unconstrained.

`WARNING | 2017-04-05 11:09:31,885 | simuvex.engine.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 unconstrained_ret_puts_21_32>`
`WARNING | 2017-04-05 11:09:32,621 | simuvex.engine.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 unconstrained_ret_puts_30_32>`

My question is : why is there this difference between the two and how would it be possible to fix it ?

**Comment by schieb** [comment]
There is definitely a difference between using angr on a binary compiled on Windows vs Linux.

However, from your output it looks like you are simply not hooking `msvcrt.puts` with `libc.puts`, which kicks in the default `ReturnUnconstrained` SimProcedure. You can either hook the call instruction, or the `msvcrt.puts` symbol itself. See the Hooks section [here](https://docs.angr.io/docs/simprocedures.html).
