### ISSUE TITLE
Reassembler example?

### ISSUE THREAD

**Issue by pfsun** [angr/angr#417]
Could you please provide a reassembler example that would explain how to use the reassembler to do reassemble based on the Ramblr paper? Thanks!

**Comment by ltfish** [comment]
That will arrive, just not recently since I'm a little overwhelmed right now. Sorry.

**Comment by pfsun** [comment]
@ltfish Don't worry. Just let me know when you have the concrete example. Thanks :-)

**Comment by ClemensElflein** [comment]
Hi! I am currently writing a seminar thesis about Ramblr and it would be great to try it out.
Could you point me in a direction where to start? The documentation does not seem to include Ramblr. Am I missing something? The paper states that it should be included in angr. Thanks!

**Comment by zardus** [comment]
You can check it out in `project.analyses.Reassembler`. To see a usage of
it, check out github.com/shellphish/patcherex, our patching engine for the
CGC.

**Comment by eternalklaus** [comment]
I've also read interestingly about your paper, `Ramblr`, 
But now, I still cannot find the example code of it.  :( 
Would you please upload example code about it? 
Just a short code would be very helpful for me :) Thanks!

**Comment by ltfish** [comment]
`Ramblr` is the code name for the reassembler analysis... so you should check out Patcherex and see how the reassemble backend is used there.

**Comment by eternalklaus** [comment]
Thanks. 
It seems like `reassembler.py` inside `angr/analyses` has the features that came up from your paper, `Ramblr`.

Is there any possible way to get the disassembly that symbolized by `ramblr` feature?
ex) input : `test_elf` --ramblr--> `test_elf.s`

I'd really appreciate if you provide a simple test script about it.
Thanks!!!
