### ISSUE TITLE
How to get a state for _init

### ISSUE THREAD

**Issue by frapik99** [angr/angr#422]
Hi,
@zardus whiel suggested me to modify the ```demote``` function in order to have all the states in a path. I have a case in which I don't have the state. Suppose to have this function:

```
0000000000004b40 <_init>:
    4b40:	48 83 ec 08          	sub    $0x8,%rsp
    4b44:	48 8b 05 85 d4 22 00 	mov    0x22d485(%rip),%rax        # 231fd0 <_DYNAMIC+0x218>
    4b4b:	48 85 c0             	test   %rax,%rax
    4b4e:	74 05                	je     4b55 <_init+0x15>
    4b50:	e8 eb 08 00 00       	callq  5440 <png_set_invert_mono@plt+0x10>
    4b55:	48 83 c4 08          	add    $0x8,%rsp
    4b59:	c3                   	retq   
```

After the call I want to have the state for ```_init``` but there are not states starting at ```0x1004b55``` supposing that the library was loaded at ```0x1000000```. How can solve it? Should I just use the state at ```0x10004b40```?

Thanks

**Comment by ltfish** [comment]
If your path indeed returns to 0x1004b55 and you are logging all states, you will have the state at 0x1004b55 for sure.

However your description is not very clear. Why do you consider the state starting at 0x1004b55 "the state for `_init`"? What is the state for `_init` in your definition?

**Comment by frapik99** [comment]
Hi @ltfish ,
a quick overview, I have save all the states apply the solution described here [354](https://github.com/angr/angr/issues/354). Once done something like:

```
		for h in list(found.history_iterator):
			s = h.state
			if ( not s == None ):
				states[hex(h.addr)] = s
```

I think the state of ```_init``` cannot start at ```4b55``` because they are 2 different blocks. Should I do soemthing different for saving all the states?

Thanks

**Comment by frapik99** [comment]
I solved it

Thanks
