### ISSUE TITLE
state.scratch.temps is empty

### ISSUE THREAD

**Issue by frapik99** [angr/angr#423]
Hi,
the VEX representation of one instruction is the following:

```
00 | ------ IMark(0x20205a0, 2, 0) ------
   01 | t0 = GET:I64(r13)
   02 | t16 = GET:I64(rsp)
   03 | t15 = Sub64(t16,0x0000000000000008)
   04 | PUT(rsp) = t15
   05 | STle(t15) = t0
   06 | PUT(pc) = 0x00000000020205a2
```

As you can see the code is within a library (libc). I use the state obtained from the PathHistory but the ```state.scratch.temps``` dictionary is empty. Am I doing something wrong or is there a reason?

Thanks

**Comment by frapik99** [comment]
Hi,
another interesting case I found is:

```
t3 = GET:I64(offset=72)
STle(t3) = t2
```

There is no reference to ```t3``` in ```state.scratch```. is it because ```t3``` "points" a registry? How can I deal with that case?

Thanks

**Comment by ltfish** [comment]
My guess is that you didn't get the correct state. `state.scratch` will be discarded every time it is about to be used by the processing engine (`SimEngineVEX` in this case). If `scratch.temps` is empty, I think you might be retrieving an initial state of the next block instead of a final state of the previous block.

**Comment by frapik99** [comment]
Thanks @ltfish , I retrived the state doing:

```
for h in list(found.history_iterator):
    state = h.state
```

isn't correct? How should I do it instead?

Thanks

**Comment by frapik99** [comment]
I would add a personal comment and see what you opinion is. Because I'm doing a loop on ```block.vex.statements``` I don't it is the best approach to discard ```scratch.temps``` because during a loop (e.g. ```rep stosq```) I cannot access to the destination anymore... I think you want in someway to save resource so I think you could discard them after so a user can still use it during an analysis like mine.

What are you idea? maybe add an option for making the user decide the behavior?

Thanks

**Comment by frapik99** [comment]
@ltfish , I have encountered again this problem so I would like to have your comment again.

I have the following block:

```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32

   00 | ------ IMark(0xa0020a6, 6, 0) ------
   01 | t3 = GET:I32(esi)
   02 | t2 = Add32(t3,0xffff71a0)
   03 | PUT(edx) = t2
   04 | PUT(ip) = 0x0a0020ac
   05 | ------ IMark(0xa0020ac, 4, 0) ------
   06 | t5 = GET:I32(esp)
   07 | t4 = Add32(t5,0x00000024)
   08 | t6 = LDle:I32(t4)
   09 | PUT(esi) = t6
   10 | ------ IMark(0xa0020b0, 2, 0) ------
   NEXT: PUT(eip) = 0x0a0020bd; Ijk_Boring
}
```
```
0xa0020a6:	lea	edx, dword ptr [esi - 0x8e60]
0xa0020ac:	mov	esi, dword ptr [esp + 0x24]
0xa0020b0:	jmp	0xa0020bd
```

When the VEX instruction ```03``` is considered in ```state.scratch.temps``` ```t2``` is not present anymore. Based on your comment I think because ```temps``` is about to being used... So what would be the best approach for keeping the ```temps```? I'm trying to implement a new analysis an I need ```temps``` for every single VEX instruction.

Thanks
