### ISSUE TITLE
fread missing from cfg.kb.functions

### ISSUE THREAD

**Issue by frapik99** [angr/angr#425]
Hi,
I have created a cfg for ```pngpixel``` but I have noticed that the function ```fread``` is not exposed via ```cfg.kb.functions``` instead other functions like ```strlen``` are exposed. I have created the cfg doing:

```
cfg = self.project.analyses.CFGAccurate(context_sensitivity_level=0, keep_state=True)
```

Any idea why this is not working?

Thanks

**Comment by ltfish** [comment]
This is probably because `fread` is not called by any other function/block that `CFGAccurate` recovers.

**Comment by frapik99** [comment]
Thanks @ltfish , I'm not sure of this because ```fread``` was called in the path I was able to obtained after I created the ```CFG```. Am I missing something?

Thanks

**Comment by ltfish** [comment]
In that case, I'm not sure. Maybe you can paste the binary somewhere so I can debug it?

**Comment by frapik99** [comment]
@ltfish , sure. It is pngpixel and it attached.

Thanks
[pngpixel.zip](https://github.com/angr/angr/files/922388/pngpixel.zip)
