### ISSUE TITLE
How to use concrete_fs along with constraints

### ISSUE THREAD

**Issue by frapik99** [angr/angr#427]
Hi,
I was reading the example ```asisctffinals2015_license``` and I was wondering if ti is possible to mix ```concrete_fs=True``` along with some constraints created ad hoc for some part of the file. Let's suppose the first 10 bytes must be ```0xff``` but after that the very first  byte must be only ```0xaa``` or ```0xbb``` and the rest of the file must meet a particular structure that would be really complex to describe. Having a well format file as input what would be the best way for describing this kind of file? Should I just create a ```SimFile``` and for the part I don't care just add a constraint that would enforce the byte to be the same as  what I found within the file?

Thanks

**Comment by frapik99** [comment]
Solved

**Comment by ekilmer** [comment]
Would you mind posting a short description of how you solved it? (or even better a small portion of the code you used?) I'm curious. Thank you!
