### ISSUE TITLE
How to pass a SimFile as parameter?

### ISSUE THREAD

**Issue by rmary77** [angr/angr#428]
Hi all,
I'm trying to understand how to use ```SimFile``` but i have few problems. I can do all but i need to understand how to pass a symbolic file to the project as 3rd parameter. Im able to creafe it because i followed an exmple on the repo, the problem is that example does not pass the file as parameter... Can you show me how to do it?

Thanks

**Comment by ltfish** [comment]
What are you trying to do? Why do you want to "pass a symbolic file to the project as 3rd parameter"? The third parameter of `Project` is `ignore_functions`, which does not seem to take `SimFile` objects.

**Comment by rmary77** [comment]
@ltfish my goal is to pass within args parameter of full_init_state a simfile so after i can place constraints on the file structure like state.se.min(...)

Thanks

**Comment by rmary77** [comment]
@ltfish I want to try to better describe my goal because maybe I was not so clear before.Let's suppose I hav an executable that taks as input one file, it does the sum of the first three bytes and if the sum is ```0x0a``` it print a success message else an error. The only requirement is that the first byte myt be ```0x02```. This is just a simple example that would help me to undertand how to create ```SimFile```s, add constraints and obtain the file's content. As I said I'm able to create the initial state via ```full_init_state``` but I don't know how to pass my ```SimFile``` as parameter. I'm aware that ```full_init_state``` has a parameter called ```args``` right for that but I don't know how to pass the file. In addition, I create bfore the state and after the ```SimFile``` like in the example where it is necessary to find the license. So, my queston is, how can I pass the ```SimFile``` to my executable and once I found the right path print the file's content?

Thanks

**Comment by tirzaz** [comment]
This [example](https://github.com/angr/angr-doc/blob/1a88bb03972ff33e8b0ee321818ea379ca2c8653/examples/asisctffinals2015_license/solve.py)  can help you . Put the 3rd argument of your program via argv [] to the same value as your simFile name.

**Comment by rmary77** [comment]
Thanks @tirzaz , i solved using ```posix.fs```. I'll try your solution as well later.

Thanks a lot
