### ISSUE TITLE
Purpose of cfg.get_paths() given the existence of PathGroup.explore etc ?

### ISSUE THREAD

**Issue by gitttt** [angr/angr#43]
I was wondering what the purpose of the cfg.get_paths(...) method is. The function results in a call to networkx.all_simple_paths, i.e. other than for trivial examples, it will take almost forever. In addition, why would one use this method to find a path in the CFG if there are possibilities such as PathGroup.explore(...) or surveyors.Explorer(find=...). Am I missing something? E.g. a way to restrict the cfg.get_paths to a certain length or "call-depth" ?

**Comment by ltfish** [comment]
@kereoz

**Comment by kereoz** [comment]
Hi @gitttt , this was part of an experimental feature,  but in the end we haven't really used it is not really useful by itself. The idea was to find subgraphs within the CFG in a purely static manner. This is quite different from what you would get out of Explorer or stepping PathGroups, as those two involve symbolic execution as opposed to pure static analysis. I would ignore this for now, or if you are after something finding a path in the CFG, I would use dijkstra_path() (from networkx) or something equivalent.

**Comment by gitttt** [comment]
Hi @kereoz , thanks for your immediate reply and your hint to take a look at dijkstra_path().
