### ISSUE TITLE
How to give a value to an environment variable.

### ISSUE THREAD

**Issue by tirzaz** [angr/angr#431]
Even that SimStates takes `env` argument , but it is not working, and the function `getenv` is not modelized as a libc function.

**Comment by zardus** [comment]
There are currently two options:

1. You can try loading libc (with `auto_load_libs=True`). However, libc is
extremely complicated to analyze, calls out to many unimplemented syscalls,
and will generally cause big problems. You might be able to alleviate this
by using a simpler libc (not glibc), but it's tricky.
2. You can implement a getenv simprocedure. If you have the state creation
code save off a copy of the env dict into the state.libc plugin, it
shouldn't be too bad to do.

I wish I had better news :-)
