### ISSUE TITLE
CFG performance bottlenecks for large binaries

### ISSUE THREAD

**Issue by axt** [angr/angr#434]
As discussed with @ltfish, this is just a memo of known CFG performance bottlenecks:

**1)** For binaries with lot of symbols, CFGFast has some performance bottlenecks:

The pending_entry lookup runs worst case in O(n), but entry_list_empty is called also O(n) times, so in worst case this will end up in O(n^2) complexity, causing a slow-down for binaries with lots functions:

```python
    def _entry_list_empty(self):

        if self._pending_entries:
            # look for an entry that comes from a function that must return
            # if we can find one, just use it
            entry_index = None
            for i, entry in enumerate(self._pending_entries):
                src_func_addr = entry.returning_source
                if src_func_addr is None or src_func_addr not in self.kb.functions:
                    continue
                function = self.kb.functions[src_func_addr]
                if function.returning is True:
                    entry_index = i
                    break

            if entry_index is not None:
                self._insert_entry(self._pending_entries[entry_index])
                del self._pending_entries[entry_index]
                return
```
To illustrate this behavior, on this graph, the x-axis represent subsequential `_entry_list_empty` calls, while the y-axis shows the number of iterations needed till a valid entry is found. The runtime is the area below the 'curve':
![entry_index](https://cloud.githubusercontent.com/assets/759365/25215624/fee08016-259e-11e7-8f40-adcdee695497.png)

**2)** In `make_functions` in `cfg_base`, this part of code triggers the slow-path of `get_any_node`, since most of the looked-up addresses are not present in the `_nodes_by_addr` dict. It can cause a major slow-down, if the number of nodes is around 500k.
```python
        secondary_function_nodes = set()
        # add all function chunks ("functions" that are not called from anywhere)
        for func_addr in tmp_functions:
            node = self.get_any_node(func_addr)
            if node is None:
                continue
            if node.addr not in blockaddr_to_function:
                secondary_function_nodes.add(node)
```

**Comment by ltfish** [comment]
The second one is easily solvable. The first one is harder.

The graph you made is nice :-)

**Comment by zardus** [comment]
With the modern speed of CFGFast, can we close this?

**Comment by ltfish** [comment]
I believe I have fixed both issues mentioned in this issue. Close.
