### ISSUE TITLE
Incorrect Goto edges reported from Region Simplifier

### ISSUE THREAD

**Issue by mahaloz** [angr/angr#4358]
### Description

On the test case `test_tail_tail_bytes_ret_dup`, with the new ReturnDuplicator, we are unable to duplicate one of the returns because the `self._goto_manger` in the pass reports the following:
`0x401edd -> 0x401f14`

This is incorrect. The correct edge is:
`0x402080 -> 0x401f14`

This is because we record Gotos in the RegionSimplifier pass, which only has knowledge of the Region (not the individual blocks that cause an edge). In this graph: 
<img width="647" alt="image" src="https://github.com/angr/angr/assets/21327264/e8f0b782-555c-45de-b4f2-7f3a39d7d270">

The `0x401edd` is the starter of this region, and is chosen as the source for the goto edge. 

### Steps to reproduce the bug

Use the `test_tail_tail_bytes_ret_dup` test case.

**Comment by ltfish** [comment]
A somewhat relevant change is in https://github.com/angr/angr/pull/4722.
