### ISSUE TITLE
Possible bug: TypeError while looking for a path

### ISSUE THREAD

**Issue by frapik99** [angr/angr#436]
Hi,
I'm now trying to perform few test on [pngpixel](https://github.com/fcoulombe/libpng/blob/master/contrib/examples/pngpixel.c) on a 32bit arch. My goal is just to find the path from the beginning of the ```main``` function until the first instruction after the ```fopen```.

My code is the following:

```
import angr
import simuvex
b = angr.Project("pngpixel", load_options={"auto_load_libs":True})
cfg = b.analyses.CFGAccurate(context_sensitivity_level=0, keep_state=True)
main = b.kb.functions.function(name="main")
argv1 = angr.claripy.BVS(10, 32 * 2)
argv2 = angr.claripy.BVS(10, 32 * 2)

initial_state = b.factory.full_init_state(args=["/tmp/pngpixel", argv1,argv2,"/tmp/magnify.png"],concrete_fs=True, addr=main.addr, add_options=simuvex.o.unicorn, remove_options={simuvex.o.LAZY_SOLVES})

initial_path = b.factory.path(initial_state)
path_group = b.factory.path_group(initial_state)

In [19]: path_group.explore(find=0x08048f41)
Out[19]: <PathGroup with 2 errored>
```

I tried to print the error and I got the following message:

```
In [23]: path.error
Out[23]: TypeError('file() argument 1 must be encoded string without null bytes, not str')
```

So I had 2 errored paths, from my initial analysis is seemed that the file name was not properly constrained for some reason.

Do you have time to have a look on it and tell me if I'm doing something wrong please?

In order to save time I have also attached pngpixel for you.

Thanks
[pngpixel32.zip](https://github.com/angr/angr/files/948790/pngpixel32.zip)

**Comment by frapik99** [comment]
One more comment that I hope would help, with an hardcoded file name the problem is not present...

Thanks

**Comment by zardus** [comment]
Could you send along a stacktrace (should be easy to get one from `path.retry()`? Otherwise, I can try to find some time to rerun your stuff, but it might not be for a bit...

**Comment by frapik99** [comment]
@zardus I'm sorry for the late response. I'll do it in the next few days.

HTH
