### ISSUE TITLE
Error when loading `Path` from `ana`

### ISSUE THREAD

**Issue by axt** [angr/angr#437]
If I try to serialize a path with `ana`, and then load it back, when accessing `path.addr`
```python
    @property
    def addr(self):
        return self.state.se.any_int(self.state.regs.ip)
```
I get an error:
```python
#ReferenceError: weakly-referenced object no longer exists
     32         try:
     33             return state.registers.load(k, inspect=inspect, disable_actions=disable_actions)
     34         except KeyError:
---> 35             return super(SimRegNameView, self).__getattribute__(k)
```

If I replace the `self._get_weakref()` with `self` in `s_state`, then it works fine:
```python
        for p in self.plugins.values():
            p.set_state(self._get_weakref() if not isinstance(p, SimAbstractMemory) else self)
```

- Is this expected behavior or an error?
- Why is SimAbstractMemory handled differently?

**Comment by zardus** [comment]
If I remember correctly, there was some dumb bug in `SimAbstractMemory` that I wasn't able to track down when I was first putting in the weakref stuff, so I just special cased it with the thinking that I'll go back and fix it later (of course, that never happens).

It's definitely an error. I'll try to get to a fix. Probably, we should just return the strong reference on pickle and swap it with a weak reference when unpickling.

**Comment by zwimer** [comment]
We no longer support `ana`.
