### ISSUE TITLE
Issue with `__str__` Usage in angr Following Recent pyvex Commit

### ISSUE THREAD

**Issue by hwu71** [angr/angr#4395]
### Description

I just wanted to give you a heads-up about something I ran into after a recent pyvex update. The commit [0f32e9db](https://github.com/angr/pyvex/commit/0f32e9dbb790d9eef3f13d32e877b57784946d55) changed the `__str__()` function to `_pp_str()` in pyvex, but it looks like angr is still using the old `__str__` in a few places.

For example, there's a spot in [jumptable.py, line 2061](https://github.com/angr/angr/blob/73c42ef2104c1a353d2adb5723d769c98828ebc9/angr/analyses/cfg/indirect_jump_resolvers/jumptable.py#L2061) where the old method is used, and it's throwing a TypeError like this:
```
TypeError: __str__() got an unexpected keyword argument 'arch'
```
I believe updating these references in angr to match the pyvex changes should resolve the issue. Just thought I'd let you know so we can keep everything working smoothly in the angr framework.

### Environment

tag = 9.2.82

**Comment by twizmwazin** [comment]
We shouldn't be calling _pp_str in angr because it is a private method. I think we should change it to pp_str in pyvex and then fix its usage here.
