### ISSUE TITLE
What are the difference between states and final_states?

### ISSUE THREAD

**Issue by rmary77** [angr/angr#440]
hello,
reading the angr documentation i have seen the concept of ```state``` and the concept of ```final_state```. I cannot understand the differences between them and when it is better to use one or another. In addition, I have also seen that a node can have multiple ```final_state``` and I cannot understand why. In case there many of them what would be the difference between them? An exampl would be great if possible.

Thanks

**Comment by ltfish** [comment]
It wasn't clearly documented anywhere. In a `CFGNode`, `state` refers to the initial state of that block, and `final_states` refers to output states (which can be more than one) going out of that block.

**Comment by ltfish** [comment]
Please bear in mind that `final_states` is not part of the public API and it may subject to future change/refactor without any notice.

**Comment by rmary77** [comment]
Thanks @ltfish . So when can i have more final than one final state sorry? If i want to analyse the path and base my analysis on the vex statements i should use the final state isn't it? Im interested in the value of the temp variables.

Thanks

**Comment by ltfish** [comment]
> i should use the final state isn't it

In general, yes.

A block may have multiple final states, one for each exit. That's the only difference between them.
