### ISSUE TITLE
get_any_node returns None

### ISSUE THREAD

**Issue by rmary77** [angr/angr#443]
hello again,
I managed to obtain a path using a path_group and now I would like to get the node associated with it and after the ```finalllll_states```. I have seen that in few cases if I do something like ```cfg.get_any_node(addr)``` where ```addr``` was returned via a ```PathHistory``` I receive ```None``` as return value and I cannot understand why. If i try to get the ```block``` at the same addr all works fine. Typically the block start with something like ```add esp,0x10```. Is there any reason why a node cannot be found? I have generatd a ```CFGAccurate```.

Thanks

**Comment by ltfish** [comment]
`CFGAccurate` does not guarantee a full code coverage. Try `CFGFast` instead.

**Comment by rmary77** [comment]
thanks @ltfish that solved the problem. I have notices that in few cases the extracted node does not have anything in ```final_states```. Can I know in what case it can be possible? I'm trying to understand how to create a new analysis based on the ```vex``` instruction but I nedd ```state.scratch.temps```.

Thanks

**Comment by rmary77** [comment]
I have seen that ```CFGAccurate``` keeps the final states... is there a way for keeping all the ```final_states``` also for ```CFGFast```?

**Comment by ltfish** [comment]
`CFGFast` does not perform any simulation, thus no state is used during CFG recovery using `CFGFast`. You can calculate states on your own based on a control flow graph you obtained from `CFGFast`.

**Comment by rmary77** [comment]
thnks @ltfish by any chanche can you help me to understand how to do that? I woud like to have the name of the function that returns the ```final_states``` and if possible a really basic example code, even a skeleton is fine.

Thanks

**Comment by ltfish** [comment]
I think what you want to do is very similar to a forward data-flow analysis: for each basic block in the function, you take an input state, feed it to angr's execution engine (SimuVEX), and take the output state. The output state will become an input state of the corresponding successor of the last block. Theory-wise, you can refer to [Wikipedia](https://en.wikipedia.org/wiki/Data-flow_analysis).

[This analysis](https://github.com/angr/angr/blob/feat/variable_recovery/angr/analyses/variable_recovery/variable_recovery.py) as well as [its base analysis](https://github.com/angr/angr/blob/feat/variable_recovery/angr/analyses/forward_analysis.py) demonstrates a basic skeleton of a simple forward data-flow analysis. You can use that as a reference. Note that they are not in master branch (yet), but the basic ideas are the same.

**Comment by rmary77** [comment]
thanks again @ltfish , I'll start having a look on the links you shared and let you know. the ```CFGFast``` does not keep the ```input_state``` I think so I can only obtain the  ```final_states``` if a ```CFGAccurate``` was used, am i right?

I have seen that few weeks ago @zardus explained how to keep all the states in a path, suppose that I want the ```final_states``` only for those states, can I just consider every state in path and feed them into ```SimuVEX``` in order to obtain the ```final_states```? I would save a lot of time in that way.

Thanks again for your patience

**Comment by ltfish** [comment]
> so I can only obtain the final_states if a CFGAccurate was used, am i right?

You are correct.

> can I just consider every state in path and feed them into SimuVEX in order to obtain the final_states

Of course. That's basically what the VariableAnalysis does in its core. See [here](https://github.com/angr/angr/blob/feat/variable_recovery/angr/analyses/variable_recovery/variable_recovery.py#L571).

**Comment by rmary77** [comment]
Thanks @ltfish i'll try and let you know if i'm able to do it.

Thanks
