### ISSUE TITLE
Loading static library for analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#45]
The `cle` loader fails to load linux static libraries. This is just a feature request for adding support for loading static library. I will appreciate it.

**Comment by rhelmot** [comment]
Can you provide an example of a static library? All the libraries on my system are dynamically linked.

**Comment by riyadparvez** [comment]
Static library is basically an archive of one or more `*.o` object files, can be built by `ar` command. For example you want to use lightweight libc like musl, but do not want to force user to install musl on their system, you can just static link musl into your application. Here is a good tutorial on how to create static libraries on linux: http://www.cs.dartmouth.edu/~campbell/cs50/buildlib.html.

**Comment by rhelmot** [comment]
Alright. What mechanism would you like to have available to resolve import symbols? Static libraries provide no indication of their dependencies (though it's usually just libc), as far as I can tell.

**Comment by riyadparvez** [comment]
That is a good question. I haven't thought about that actually, is there any better way than just to leave imported symbols unresolved?

**Comment by rhelmot** [comment]
The way it's done in code concretely is that the dependencies must be resolved manually by specifying `-lname` in the compiler flags. `-lc` is implicit, of course, but everything else is manual. So in the loader options you'll have to somehow specify the libraries that need to be loaded. Pretty sure that if you just specify the libraries in `force_load_libs` their exports should get picked up automatically.

I'll do this at some point! I've got a lot of classwork to get through, but this can absolutely happen.
