### ISSUE TITLE
Error when attempting to do VRA with workers=1

### ISSUE THREAD

**Issue by Cl4sm** [angr/angr#4530]
### Description

This occurs on some binaries when workers is set to 1. It appears to work fine for values > 1.
This is the backtrace that gets output:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RuntimeError: dictionary changed size during iteration
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
RuntimeError: dictionary changed size during iteration
```

### Steps to reproduce the bug

Folder with the reproduction script, binary source, and binary - [wrapper.zip](https://github.com/angr/angr/files/14661967/wrapper.zip)
Just run the test.py script

**Comment by Cl4sm** [comment]
This now appears to be fixed on master but not the pip release.

**Comment by ltfish** [comment]
I don't think I did anything to fix this issue. I believe this issue still persists, but may not always be triggerable.

**Comment by Cl4sm** [comment]
Hmmm, looks like you're right. Though I've never failed to trigger it on the pip version, the master version is intermittent.

**Comment by Cl4sm** [comment]
I lied... I guess I'm just really lucky lol
