### ISSUE TITLE
Segfault in CFGFast for mips64 binary

### ISSUE THREAD

**Issue by d05004** [angr/angr#4533]
### Description

When analyzing an MIPS64 ELF binary, the analysis dies with a segfault
```
>>> import angr
>>> proj = angr.Project("./test.txt")
>>> proj.analyses.CFGFast()
WARNING  | 2024-03-23 18:15:16,076 | angr.analyses.cfg.cfg_base | "auto_load_libs" is enabled. With libraries loaded in project, CFG will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.
Segmentation fault (core dumped)
```
I tried debug and found that invalid address value(-1) is provided to load_value function in pyvex library.
[https://github.com/angr/pyvex/blob/eb087cc88d0660c2fdb09edbb907e0bd66bbc6da/pyvex_c/analysis.c#L442](url)

But I couldn't find where the adrress value comes from.

Here is binary for reproduce.
[test.txt](https://github.com/angr/angr/files/14730911/test.txt)

**Comment by Rroscha** [comment]
I'm also having this problem with mips64 binaries.

**Comment by ltfish** [comment]
Thanks for the report! The problem is caused by an integer overflow in pyvex. Just opened a PR (https://github.com/angr/pyvex/pull/383).
