### ISSUE TITLE
Incorrect decompilation of call

### ISSUE THREAD

**Issue by maskelihileci** [angr/angr#4546]
### Description

Opcode : 

 mov     rdx, [rax+10h]
 mov     rax, [rbp+var_28]
 mov     rcx, rax
 call    rdx

Decompile

v13(v2, *(v2)->field_10);

v13 says it calls the function with parameter v2, *(v2)->field_10 but this is not true.

The v13 reference should never exist because it is unnecessary.

![image](https://github.com/angr/angr/assets/41159853/656ddc5a-8127-4b9f-9854-9515bbafffb0)

### Steps to reproduce the bug

[p.zip](https://github.com/angr/angr/files/14785795/p.zip)

"sub_402f78"

### Environment

Date: 2024-03-28 10:52:47.750404
!!! running in global environment.  Are you sure? !!!
Platform: win-amd64
Python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
######## angr #########
Python found it in H:\Python310\lib\site-packages\angr
Pip version angr 9.2.66
######## ailment #########
Python found it in H:\Python310\lib\site-packages\ailment
Pip version ailment 9.2.66
######## cle #########
Python found it in H:\Python310\lib\site-packages\cle
Pip version cle 9.2.66
######## pyvex #########
Python found it in H:\Python310\lib\site-packages\pyvex
Pip version pyvex 9.2.66
######## claripy #########
Python found it in H:\Python310\lib\site-packages\claripy
Pip version claripy 9.2.66
######## archinfo #########
Python found it in H:\Python310\lib\site-packages\archinfo
Pip version archinfo 9.2.66
######## z3 #########
Python found it in H:\Python310\lib\site-packages\z3
Pip version z3-solver 4.10.2.0
######## unicorn #########
Python found it in H:\Python310\lib\site-packages\unicorn
Pip version unicorn 2.0.1.post1
######### Native Module Info ##########
angr: <CDLL 'H:\Python310\lib\site-packages\angr\lib\angr_native.dll', handle 7ffadc5d0000 at 0x283edc88c40>
unicorn: <CDLL 'H:\Python310\lib\site-packages\unicorn\lib\unicorn.dll', handle 7ffade010000 at 0x283ece6ec20>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x00000283ECC8D750>
z3: <CDLL 'H:\Python310\Lib\site-packages\z3\lib\libz3.dll', handle 7ffadf120000 at 0x283ebf19150>

### Additional context

Your work is really approaching paid analysis software on the market, and I congratulate you on this issue. I wish you continued success.

**Comment by ltfish** [comment]
Thanks for the report! My work-in-progress branch (https://github.com/angr/angr/pull/4543) happens to solve this issue for you. Here is my decompilation result on that branch:

```
long long sub_402f78(struct struct_3 **a0, char *a1, char *a2, unsigned long long a3)
{
    struct struct_2 **v0;  // [bp-0x90]
    unsigned long long v1;  // [bp-0x88]
    unsigned int v2;  // [bp-0x34]
    struct struct_1 **v3;  // [bp-0x30]
    char *v4;  // [bp-0x28]
    char *v5;  // [bp-0x20]
    unsigned int v6;  // [bp-0x14]
    unsigned int v7;  // [bp-0x10]
    unsigned int v8;  // [bp-0xc]
    unsigned long v9;  // [bp-0x8]
    char v10;  // [bp+0x0]
    char v12;  // [bp+0x20]

    v9 = &v10;
    v8 = 0;
    v3 = 0;
    v5 = SysAllocString(a1);
    v4 = SysAllocString(a2);
    v0 = &v3;
    v7 = *(a0)->field_a0(a0, v5, v4, 0, 0);
    if (v7 >= 0 && v3)
    {
        v2 = 0;
        v7 = 0;
        while (!v7 && !v8)
        {
            v7 = *(v3)->field_20(v3, 4294967295, 10, &v1);
            if (v7 < 0)
                continue;
            for (v6 = 0; v6 < v2 && !v8; v6 += 1)
            {
                v8 = *((long long *)&v12)((&v1)[v6], a3);
                *((long long *)(*((long long *)(&v1)[v6]) + 16))((&v1)[v6], *((long long *)(*((long long *)(&v1)[v6]) + 16)));
            }
        }
        *(v3)->field_10(v3, *(v3)->field_10);
    }
    SysFreeString(v4);
    SysFreeString(v5);
    return v8;
}
```

**Comment by ltfish** [comment]
> Your work is really approaching paid analysis software on the market, and I congratulate you on this issue. I wish you continued success.

Thank you for your kind comment!

**Comment by ltfish** [comment]
The fix has been merged to master!
