### ISSUE TITLE
How to get the process' output?

### ISSUE THREAD

**Issue by Hirrolot** [angr/angr#4570]
### Question

Suppose I'm having the following C program:

```c
#include <stdio.h>

int main(void) {
	puts("hello world");
}
```

Compiled as follows:

```
$ gcc print.c
```

Now I want to simulate the program using Angr:

```python
import angr

proj = angr.Project("a.out", auto_load_libs=False)
state = proj.factory.entry_state()
sim = proj.factory.simulation_manager(state)

# Run sim.step() until deadended...
```

How can I retrieve the resulting `stdout`? When I type `state.posix.dumps(1)`, it shows `b''`, which is not `hello world` at all. What am I doing wrong?

**Comment by Hirrolot** [comment]
Well, `sim.deadended[0].posix.dumps(1)` does what I want. Is this because states in Angr are immutable, so when I pass `state` to `simulation_manager`, it just doesn't change it?

**Comment by ltfish** [comment]
States are immutable. Simulation manager makes a copy of your input state before using.
