### ISSUE TITLE
How to find path constaint that are not using symbolic values ?

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4581]
### Question

I will go deeper in my problem. I have an executable and somewhere there is a condition that I want to recover. For different reason I am not realy interested in making the value it using in the condition symbolic but I want to recover the condition anyway. I saw from #1988 that I can recover unsat state by adding some options but I don't know how to uses these state.

Here a code exemple code snipet of the program I try to analyze:

```
switch (cmd_id) {
        case HELLO_WORLD_CMD_INC_VALUE:

                tmp_len = *(size_t*)params[0].memref.buffer;

                if (tmp_len > MAX_BUF_LEN) {
                  return ERROR_BAD_PARAMETERS;
                }

                tmp_len = *(size_t*)params[0].memref.buffer;
```

In this example the thing I want to recover is the condition on tmp_len. If you have any other suggestion I am open to it.

**Comment by ltfish** [comment]
> For different reason I am not realy interested in making the value it using in the condition symbolic

Honestly making the value symbolic and concretizing it to its original concrete value immediately after is the easiest way, if you are thinking of using dynamic symbolic execution here.

If you want to do static analysis, you can also run RDA (or your own data-flow analysis) on the entire function, figure out the dependencies out of `tmp_len`, and get all expressions and statements that depend on `tmp_len`.

**Comment by ltfish** [comment]
Oh if you are thinking of analyzing source code instead of analyzing binary code, angr is not the best choice.

**Comment by Voxanimus** [comment]
> > For different reason I am not realy interested in making the value it using in the condition symbolic
> 
> Honestly making the value symbolic and concretizing it to its original concrete value immediately after is the easiest way, if you are thinking of using dynamic symbolic execution here.
> 
> If you want to do static analysis, you can also run RDA (or your own data-flow analysis) on the entire function, figure out the dependencies out of `tmp_len`, and get all expressions and statements that depend on `tmp_len`.

It is in fact for dynamic symbolic execution. I am not supposed to have the source code. It a basis to experiment around.
So basically I have to found in which register the value is hold, transform it as symbolic, stepping, recovering the condition and then reconcretize the value ?
