### ISSUE TITLE
How to indicate from which path load a shared object?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#459]
Hi,
is there a way to specify a path where angr should look for shared objects?

Thanks

**Comment by rhelmot** [comment]
Yes. The CLE loader takes a `custom_ld_path` parameter - see http://angr.io/api-doc/cle.html

Pass this to the Project constructor and it will be passed on to CLE.

**Comment by frapik99** [comment]
Prefect

Thanks

**Comment by frapik99** [comment]
@rhelmot , I tried with the following code:
```
b = angr.Project("test", load_options={'custom_ld_path':'/tmp/ld', 'auto_load_libs': True})
```

but the shared object are not loaded because the CFG is generated to quickly. What am I doing wrong?

Thanks

**Comment by rhelmot** [comment]
"The CFG is generated too quickly is a poor metric for determining success here. You can look at the full list of loaded objects by looking at `project.loader.all_objects`.
