### ISSUE TITLE
Is they a way to explore memory fetches ?

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4592]
### Question

Let me be more clear. I have some binaries and want to be able to run my angr script without knowing apriori what is in it except that I know the address of some interesting fetches that I want to compare. The thing is that the addresses we use for fetch the memory could be in any register right ?

Is there a way to identify which register contains the thing I want ? or any other way to compare these addresses ?

**Comment by ltfish** [comment]
What does "memory fetches" mean? Memory reads?

**Comment by Voxanimus** [comment]
Yes, like a load instruction. To be more precise I want to check that 2 different memory read look at the same address or not.

**Comment by ltfish** [comment]
Are you trying to do this in a static way (which leads to higher completeness and lower precision) or during a dynamic symbolic execution run?

**Comment by Voxanimus** [comment]
> Are you trying to do this in a static way (which leads to higher completeness and lower precision) or during a dynamic symbolic execution run?

I am trying to do this during symbolic execution run.

**Comment by ltfish** [comment]
Try setting `SimInspect` inspection points? You'll want to inspect `memory_read`s.

**Comment by Voxanimus** [comment]
Woaw thank you, I think it's exactly what I needed. Thanks a lot.
