### ISSUE TITLE
Python 3.12 removed distutils, prevents running

### ISSUE THREAD

**Issue by ReversingWithMe** [angr/angr#4609]
### Description

One of the requirements from capstone pulls in a dependency of distutils, which is not installed by default. 

setuptools must be added to setup requirements.

### Steps to reproduce the bug

pyenv 3.12
pyenv local 3.12
python3 -m pip install angr
python3
>>> import angr

**Comment by twizmwazin** [comment]
Issue appears to be open already [upstream](https://github.com/capstone-engine/capstone/issues/2223), nothing more we can do here but wait. In the meantime, run `pip install setuptools` before hand. If pip isolates the build, add `--no-build-isolation` when installing capstone.
