### ISSUE TITLE
How to print the content of a SimFile?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#462]
Hi,
I was looking at the ```asisctffinals2015_license``` example. I was wondering how it would be possible to print the content of the file once the exercise is solved. I guess using ```found.state.posix.dump(fd)``` but I don't know the fd value.

Thanks

**Comment by ekilmer** [comment]
If you want to look at the contents of the file after it has been closed (which is the case here), then you will have to access it by its path and 
```python
print repr(found.state.posix.dump_file_by_path('_a\nb\tc_'))
```
The file's path was set in `license_name` in this example. 

You can see which files are left open after the analysis by looking at `found.state.posix.files` which will have a dictionary of file descriptors and their respective `SimFile`s

You can also see which files have been touched during analysis by looking at `found.state.posix.fs`.

If you have access to a SimFile `f`, you can also do `print found.state.se.any_str(f.all_bytes())`


NOTE: There is a subtlety when looking at the content of a file that is opened, modified, closed, opened, modified, etc. The respective SimFile in `posix.files` will have the most up to date content. The file's contents only get flushed back to `posix.fs` after it is closed. There are also some subtle things that can happen when opening the same file multiple times.

**Comment by frapik99** [comment]
Thanks @ekilmer , I have solved using the ```SimFile``` with ```any_str```. I would also add that in my case the ```dump_file_by_path``` was not present so maybe I need to update or the function name is not correct. I'll leave the issue open so you can comment and close it when you want.

I have another question regarding the ```SimFile```s but I'll file another issue later.

Thanks for your help

**Comment by ekilmer** [comment]
No problem! And yes, the `dump_file_by_path` function is relatively [new](https://github.com/angr/simuvex/commit/e44748ac5c4724f1ddd313a2b8cc08a1bab131ec) (merged on April 27). It'll require updating both Simuvex and angr.

Here is the related PR: https://github.com/angr/simuvex/pull/108

**Comment by frapik99** [comment]
Thanks
