### ISSUE TITLE
How to add constraints to a SImFile?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#463]
Hi all,
having a look on ```pngpixel``` I have noticed that the png file contains a crc. I was wondering if having a ```SimFile``` is it possible to express a constrain something ```byte_at_offset_x == zlib.crc32(bytes_between_x_and_y)```. So I would express a constrain that would allow me to specify how the crc should be calculated.

Thanks

**Comment by ekilmer** [comment]
I would say that generally you would want to patch out any checksums that deal with file integrity and don't affect functionality after the initial check. As far as I know, the CRC32 check for a PNG file only checks for corrupted bits during file transfer and is not really useful for fuzzing or vulnerability discovery as an attacker could just recalculate their payload's CRC32 sum and replace it. Plus, it slows down the symbolic execution. The LLVM fuzzing project also recommends to patch out the CRC check or replace it with something more friendly: http://llvm.org/docs/LibFuzzer.html#fuzzer-friendly-build-mode

If you'd like to keep it in there as an exercise, then I'm afraid I can't give you an exact answer, but here is something similar that might [help](https://yurichev.com/blog/symbolic/#Cyclic%20redundancy%20check). Here are some academic papers that might give a better idea about the efficacy of symbolic execution for hash protocols [[1]](https://pdfs.semanticscholar.org/1e06/09bd8fbf12ba1c1565a716421c77d96ceb0a.pdf) [[2]](http://lenx.100871.net/papers/TaintScope-Tissec.pdf).

Here is a nice graph from [[1]](https://pdfs.semanticscholar.org/1e06/09bd8fbf12ba1c1565a716421c77d96ceb0a.pdf) that shows time to calculate CRC32 with KLEE and STP:
<img width="469" alt="screen shot 2017-05-15 at 11 29 03 am" src="https://cloud.githubusercontent.com/assets/816362/26065405/d6ac65b6-3961-11e7-945a-6635b16dbd58.png">


[1]: https://pdfs.semanticscholar.org/1e06/09bd8fbf12ba1c1565a716421c77d96ceb0a.pdf -- Efficient Symbolic Execution for Analysing Cryptographic Protocol Implementations
[2]: http://lenx.100871.net/papers/TaintScope-Tissec.pdf -- Checksum-Aware Fuzzing Combined with Dynamic Taint Analysis and Symbolic Execution

**Comment by frapik99** [comment]
Thanks @ekilmer I think I got you point, replace it with something easy or completely remove it would be feasible.

In general, is it possible to add constraints between symbolic bytes in the same SimFile?

Thanks

**Comment by salls** [comment]
Yes it is. One way is to read the bytes from the file and add constraints then reset the current position in the file. Another way might be to hook the relevant address or use siminspect to add the constraints to the bytes as they are read. 

Here's an example of the first way:

from https://github.com/angr/angr-doc/blob/master/examples/ekopartyctf2016_rev250/solve.py
```
    for i in range(BUF_LEN):
        c = state.posix.files[0].read_from(1)
        state.se.add(char(state, c))

    state.posix.files[0].seek(0)
```

**Comment by frapik99** [comment]
Thanks I'll try this approach
