### ISSUE TITLE
Can I use two exploration_techniques at the same time?

### ISSUE THREAD

**Issue by zzloo7** [angr/angr#464]
I checked the source code of explore in pathgroup.

```
    def explore(self, stash=None, n=None, find=None, avoid=None, find_stash='found', avoid_stash='avoid', cfg=None, num_find=1, step_func=None):
        """
        Tick stash "stash" forward (up to "n" times or until "num_find" paths are found), looking for condition "find",
        avoiding condition "avoid". Stores found paths into "find_stash' and avoided paths into "avoid_stash".

        The "find" and "avoid" parameters may be any of:

        - An address to find
        - A set or list of addresses to find
        - A function that takes a path and returns whether or not it matches.

        If an angr CFG is passed in as the "cfg" parameter and "find" is either a number or a list or a set, then
        any paths which cannot possibly reach a success state without going through a failure state will be
        preemptively avoided.
        """
        num_find += len(self.stashes[find_stash]) if find_stash in self.stashes else 0
        tech = exploration_techniques.Explorer(find=find,
                                   avoid=avoid,
                                   find_stash=find_stash,
                                   avoid_stash=avoid_stash,
                                   cfg=cfg,
                                   num_find=num_find)
        self.use_technique(tech)
        out = self.run(stash=stash,
                       step_func=step_func,
                       n=n)
        out.remove_tech(tech)
        self.remove_tech(tech)
        return out
```

I find it uses _angr.exploration_techniques.explorer.Explorer_,but I want to use _angr.exploration_techniques.looplimiter.LoopLimiter_ at the same time. How can I make it?

**Comment by ltfish** [comment]
- Create a path group `pg`.
- `pg.use_technique(loop_limiter_technique)`
- `pg.explore()`

**Comment by zzloo7** [comment]
But that seems effectless. I can use pathgroup.step() with loop_limiter_technique to get into a specific address, which can't happen when I use explore().

**Comment by ltfish** [comment]
> But that seems effectless.

I'm not sure why that is the case. From what I understand, `LoopLimiter` is not conflicting with `Explorer` (they implement totally different hooks). I'll have to debug it to give you a definite answer, but since we are all busy right now, we won't have any cycles to debug it prior to this weekend.

I'll get back to you once I get some free time (this Saturday, I hope) to reproduce the issue and figure out what is going on. Before that, you can try applying the `Explorer` technique before `LoopLimiter`, then call `pg.run()` instead of `pg.explore()` and see if that works.

**Comment by zzloo7** [comment]
Ok. Thanks very much for your reply, I'll try later.

**Comment by axt** [comment]
Don't take this as an "official" answer, I may be wrong.

Based on my experience you can use several exploration techniques at the same time, but only one of them can override the `step_path` function. 

LoopLimiter didn't worked for me, here is a basic implementation, you can try with this, till the official get fixed. It's more resource consuming, needs a CFGAccurate, and currently drops the paths after the first loop, but that can be modified easily.

```python
import angr 
class LoopLim(angr.exploration_techniques.ExplorationTechnique):
    def __init__(self, cfg):
        super(LoopLim, self).__init__()
        self.cfg = cfg

    def setup(self, pg):
        if 'loop' not in pg.stashes:
            pg.stashes['loop'] = []

    def step(self, pg, stash, **kwargs):
        looping = set()
        for path in pg.active:
            call_stack_suffix = path.callstack.stack_suffix(self.cfg.context_sensitivity_level)
            block_id = self.cfg._generate_block_id(call_stack_suffix, path.addr, False, continue_at=None)
            if 'xx' not in path.info:
                path.info['xx'] = set()
            if block_id in path.info['xx']:
                looping.add(path)
            path.info['xx'].add(block_id)

        pg.move(from_stash='active', to_stash='_DROP', filter_func=lambda p: p in looping)
        pg = pg.step(stash=stash, **kwargs)
        return pg
```

**Comment by ltfish** [comment]
> LoopLimiter didn't worked for me

It is very possible that `LoopLimiter` is broken!
