### ISSUE TITLE
Is there a way to check if a function call is a call to an internal function or a library call ?

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4642]
### Question

Everything is in the title. I looked at some loader function but I don't find something that's look like what I am searching.

**Comment by rhelmot** [comment]
project.loader.find_object_containing(addr) is project.loader.main_object

If you want to catch plt stubs too you can look at project.loader.main_object.plt and project.loader.main_object.reverse_plt

**Comment by Voxanimus** [comment]
Woaw such a fast answer. Thank you ^^
