### ISSUE TITLE
How to breakpoint on a bl instruction ?

### ISSUE THREAD

**Issue by Voxanimus** [angr/angr#4646]
### Question

To make it simple. I implement a feature in a project that make me able to breakpoint at a function call and install a generic hook that does nothing for external function. The thing is some of the binary I study does not use `call` sometimes but `bl` instead to jump to external function. Example:
![image](https://github.com/angr/angr/assets/44275510/a8e16b79-01f4-4356-9f0d-cd9c892c0264)

Looking at the documentation I guess I should use the `instruction` event but I don't know how can I recover the complete instruction from the adress to check if it's a bl or not.

**Comment by ltfish** [comment]
> but I don't know how can I recover the complete instruction from the adress to check if it's a bl or not.

`if project.factory.block(address_of_the_instruction).capstone.insns[0].mnemonic == "bl": ...`

**Comment by Voxanimus** [comment]
Okay and we agree that if I did something like `state.inspect.b("instruction", when=BP_BEFORE, action=self._install_generic_call_hook)` is supposed to install a breakpoint on every instruciton right ?

**Comment by Voxanimus** [comment]
Okay so I realized that `bl` are taken into account by the "call" keyword, which is making sense since arm does not have `call` instruction. The problem is for some weird reason in this specific case it does noe go through the `_install_generic_call_hook` function.

**Comment by Voxanimus** [comment]
New realization. I notice the the `get_mem_usage` is not considered as a function, I supposed then that's it is not considered as a "call" and that's why the breakpoint is skipped. Neverthless I tried to manually hook the symbol and get this message:

`WARNING | 2024-05-24 17:53:47,120 | angr.project | Address is already hooked, during hook(0x100088, <SimProcedure memusage_hook>). Re-hooking.`

So the symbol is supposed to be hooked anyway and still the `SimProcedure` is not executed.
