### ISSUE TITLE
Why I have always only one active path?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#467]
Hi all,
I'm trying to analyze this simple project:

```
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
int main(int argc, char *argv[]) {

	int x = 10;
	char *b = NULL;
	if ( argc > 2 ) {
		malloc(10);
	}

	malloc(2);
}
```

My python script is more or less:

```
import angr
import simuvex

b = angr.Project("malloc", load_options={'auto_load_libs': False})
cfg = b.analyses.CFGFast(show_progressbar=True)
initial_state = b.factory.entry_state(remove_options={simuvex.o.LAZY_SOLVES})
path_group = b.factory.path_group(initial_state)

while len(path_group.active) > 0:
     path_group.step(1)
     print path_group.active
     raw_input("...............")
```
The problem is that when I encounter the ```if``` I don't have 2 active paths but just one. Any idea why? What am I doing wrong? How can I have 2 paths?

Thanks

**Comment by frapik99** [comment]
Of course I had to use ```blank_state```

Thanks

**Comment by zardus** [comment]
The issue is actually that angr's default entry state has no args in argv. If you want to explore that, you can specify some symbolic data in the `argv` argument when creating the entry state.
