### ISSUE TITLE
Does angr using backward symbolic execution to find targeted input?

### ISSUE THREAD

**Issue by 9iang22** [angr/angr#4676]
### Question

Hi, I found that there are backward slicing functions in Angr, that's cool. 
I wonder if there are backward symbolic executions (analysis from the target instead of exploration from the entry) used in generating input that we expect can lead to a certain address. 
Also if possible, where are the related code placed, thanks.

**Comment by ltfish** [comment]
angr does not support backward symbolic execution, and I am also not sure how to implement backward symbolic execution on binaries.

**Comment by 9iang22** [comment]
Thanks for your quick response!
