### ISSUE TITLE
Create a path from a list of addresses

### ISSUE THREAD

**Issue by rmary77** [angr/angr#468]
Morning,
Please consider that i have a list containing all the addresses of a path but i dont have the actual path. How can i create it? I was thinking to retrieve the node from the cfg, symbolically execute it and continue using the proper final_state. What do you suggest?

Thanks

**Comment by ltfish** [comment]
There is a class called `Director` in angr, which is an exploration technique. It should help.

**Comment by zardus** [comment]
I also have a `Follower` exploration technique laying around somewhere that
should do this exact thing -- I'll try to find it.
