### ISSUE TITLE
CFGEmulated() gets multiple nodes with the same address

### ISSUE THREAD

**Issue by Brubzick** [angr/angr#4713]
### Question

To practise using angr, I use CFGEmulated() to get the CFG of a binary file from a source code of deep first search algorithm. I find that the CFG contains multiple nodes that have the same name and address. One of the nodes has a predecessor, and others has no predecessors, and they all have different successors. When I start at the entry of the CFG to explore a path, I only get a path with a dead loop but no exit nodes (I mean node with no successors). What is happening? Why would this situation happen?

**Comment by ltfish** [comment]
`CFGEmulated` generates a context-sensitive CFG by default. You probably want to use `CFGFast` instead (which only generates context-insensitive CFGs). CFGFast is also the default CFG algorithm in angr.
