### ISSUE TITLE
Can angr handle disassembly directly?

### ISSUE THREAD

**Issue by Brubzick** [angr/angr#4771]
### Question

I used angr to handle binary and analyze similarity, and it worked really well. But now I am working on a project to analyze similarity between disassemblys, or between binary and disassembly.
Can angr handle disassembly directly without providing a binary? For example, can I use angr to lift disassembly to VEX IR?

**Comment by rhelmot** [comment]
No, all of our stuff only handles binaries.

**Comment by Brubzick** [comment]
I see. Thank you.
