### ISSUE TITLE
Pickle a Path?

### ISSUE THREAD

**Issue by ejm9** [angr/angr#480]
[solve.py.txt](https://github.com/angr/angr/files/1056377/solve.py.txt)

Guys,

I posted to the angr mailing list a few weeks back about not being able to pickle (to file) a path object in angr.  I was able to find a test case where it can be reproduced (the file I submitted named solve.py.txt).  This file should be placed in the angr-doc-master/examples/fauxware directory and run against the fauxware example file.  It is a slight mod on the original solve.py file that came in the fauxware directory.  This will demonstrate the problem.

So the problem is not that pickling the path object fails, but rather it succeeds, and then when pickle loads the object back in, it is a drastically larger size, and the path.history object is not the same as the path.history object that was originally pickled.  

This could just be an issue with how you have the angr/path_history.py PathHistory object setup (e.g. path_history._parent)...or there's a slight chance it's a bug in python's pickle.py.   I ran my tests using python 2.7.13

Thanks so much for your help.
Ejm

**Comment by zardus** [comment]
Hello,

From a brief glance, it looks like an issue with the path history, yeah.

We're currently in the middle of a big refactor of this code (background
info here: https://github.com/angr/angr/issues/349). Hopefully that'll
eliminate this problem, but I'll make sure to check on that branch.

- Yan

**Comment by ejm9** [comment]
Yan,

Thanks!  I'll watch the check ins.

Thanks so much,
Ejm
