### ISSUE TITLE
Fortran port of "helloworld" symbolic execution example generating incorrect results

### ISSUE THREAD

**Issue by jacksonvanover** [angr/angr#4809]
### Description

using angr (v9.2.117), I have no issues running the basic helloworld symbolic execution example described in the docs (https://docs.angr.io/en/latest/core-concepts/symbolic.html), but I cannot reproduce those results when analyzing the same program written in Fortran.

Instead of seeing the expected stdout:
```
Value of input_arg that reaches HelloWorld: 55
Function arg: min = 51, max = 99
```
I see:
```
Value of input_arg that reaches HelloWorld: {n}
Function arg: min = {n}, max = {n}
```
where `{n}` is often `0`, but also takes on other values like `4026531840`, `4294963200`, `4294836224`, `3758096384`...

- I have accounted for compiler-specific name-mangling by inspecting symbol tables via `nm`
- I have observed this issue both with gfortran (11.4.0) and ifort (2021.13.0)
- I have compiled with `-g`.
- I have tried providing additional flags to explicitly set the default integer size as either 32 or 64 bits; this did not change the printed results.
- I have verified that the values from the generated stdin do not go down the path to call helloWorld(); I tried both hardcoding and reading from stdin.
- I have tried with both auto_load_libs=False and auto_load_libs=True with no obvious change observed.

### Steps to reproduce the bug

In a new directory, create the four files below and run:

```
gcc -g -o a.c.out main.c
python3 find_helloworld_c.py
gfortran -g -o a.f90.out main.f90
python3 find_helloworld_fortran.py
```

### main.c
```
#include <stdio.h>
#include <stdint.h>

void HelloWorld() {
    printf("Hello, World!\n");
}

void firstCall(uint32_t num) {
    if (num > 50 && num < 100)
        HelloWorld();
}

int main() {
    firstCall(30);
    firstCall(60);

    return 0;
}
```

### find_hello_world_c.py
```
import angr, claripy
# Load the binary
project = angr.Project('./a.c.out', auto_load_libs=False)

# Define the address of the firstCall function
firstCall_addr = project.loader.main_object.get_symbol("firstCall")

# Define the address of the helloWorld function
helloWorld_addr = project.loader.main_object.get_symbol("HelloWorld")
# Create a symbolic variable for the firstCall arg
input_arg = claripy.BVS('input_arg', 32)

# Create a blank state at the address of the firstCall function
init_state = project.factory.blank_state(addr=firstCall_addr.rebased_addr)

# Assuming the calling convention passes the argument in a register
# (e.g., x86 uses edi for the argument)
init_state.regs.edi = input_arg

# Create a simulation manager
simgr = project.factory.simulation_manager(init_state)

# Explore the binary, looking for the address of helloWorld
simgr.explore(find=helloWorld_addr.rebased_addr)

# Check if we found a state that reached the target
if simgr.found:
    input_value = simgr.found[0].solver.eval(input_arg)
    print(f"Value of input_arg that reaches HelloWorld: {input_value}")
    # Get the constraints for reaching the helloWorld function
    constraints = simgr.found[0].solver.constraints
    # Create a solver with the constraints
    solver = claripy.Solver()
    solver.add(constraints)
    min_val = solver.min(input_arg)
    max_val = solver.max(input_arg)
    print(f"Function arg: min = {min_val}, max = {max_val}")
else:
    print("Did not find a state that reaches HelloWorld.")
```

### main.f90
```
program HelloWorldProgram
    implicit none

    call firstCall(30)
    call firstCall(60)

contains

    subroutine helloWorld()
        print *, 'Hello, World!'
    end subroutine helloWorld

    subroutine firstCall(num)
        integer, intent(in) :: num
        if (num > 50 .and. num < 100) then
            call helloWorld()
        end if
    end subroutine firstCall

end program HelloWorldProgram
```

### find_helloworld_fortran.py
```
import angr, claripy
# Load the binary
project = angr.Project('./a.f90.out', auto_load_libs=False)

# Define the address of the firstCall function
firstCall_addr = project.loader.main_object.get_symbol("firstcall.0")

# Define the address of the helloWorld function
helloWorld_addr = project.loader.main_object.get_symbol("helloworld.1")
# Create a symbolic variable for the firstCall arg
input_arg = claripy.BVS('input_arg', 32)

# Create a blank state at the address of the firstCall function
init_state = project.factory.blank_state(addr=firstCall_addr.rebased_addr)

# Assuming the calling convention passes the argument in a register
# (e.g., x86 uses edi for the argument)
init_state.regs.edi = input_arg

# Create a simulation manager
simgr = project.factory.simulation_manager(init_state)

# Explore the binary, looking for the address of helloWorld
simgr.explore(find=helloWorld_addr.rebased_addr)

# Check if we found a state that reached the target
if simgr.found:
    input_value = simgr.found[0].solver.eval(input_arg)
    print(f"Value of input_arg that reaches HelloWorld: {input_value}")
    # Get the constraints for reaching the helloWorld function
    constraints = simgr.found[0].solver.constraints
    # Create a solver with the constraints
    solver = claripy.Solver()
    solver.add(constraints)
    min_val = solver.min(input_arg)
    max_val = solver.max(input_arg)
    print(f"Function arg: min = {min_val}, max = {max_val}")
else:
    print("Did not find a state that reaches HelloWorld.")
```

### Environment

angr environment report
=============================
Date: 2024-09-03 20:01:16.061828
Running in virtual environment at /home/SVPT/.venv
Platform: linux-x86_64
Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
######## angr #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/angr/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## ailment #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/ailment/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## cle #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/cle/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## pyvex #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/pyvex/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## claripy #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/claripy/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## archinfo #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/archinfo/__init__.py
Pip version 9.2.117
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## z3 #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/z3/__init__.py
Pip version 4.13.0.0
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######## unicorn #########
Python found it in /home/SVPT/.venv/lib/python3.10/site-packages/unicorn/__init__.py
Pip version 2.0.1.post1
Git info:
        Current commit fe662916f7d374bf565f3a6c05c8e2b9d859a987 from branch angr
        Checked out from remote origin: git@github.com:ucd-plse/SVPT
######### Native Module Info ##########
angr: <CDLL '/home/SVPT/.venv/lib/python3.10/site-packages/angr/lib/angr_native.so', handle 55b5bd02d1e0 at 0x7fef7e076950>
unicorn: <CDLL '/home/SVPT/.venv/lib/python3.10/site-packages/unicorn/lib/libunicorn.so.2', handle 55b5bca1c360 at 0x7fef80f62f50>
pyvex: <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fef81bdf6a0>
z3: <CDLL '/home/SVPT/.venv/lib/python3.10/site-packages/z3/lib/libz3.so', handle 55b5bc626420 at 0x7fef83b51750>

### Additional context

[original post on Discord](https://discord.com/channels/1152679282955534336/1152696631339258018/1280604199813648470); in response, @rhelmot requested that I file an issue.

**Comment by jacksonvanover** [comment]
[A relevant reply from the Discord thread](https://discord.com/channels/1152679282955534336/1152696631339258018/1280987383453716572):
> doesn't fortran take arguments by reference by default? godbolt seems to show `firstCall` dereferencing its argument before comparing it: https://godbolt.org/z/1Pzx51YTz so then angr is concretizing the address which will do weird things

Fortran does adopt a pass-by-reference convention by default. I had not considered how this might change the angr analysis compared to that for an identical C program; admittedly, I am also new to angr so even with this info, I am unclear on how best to modify the code in the example to account for this convention.

I have tried modifying `find_helloworld_fortran.py` inspired by [this StackOverflow post](https://stackoverflow.com/questions/59142699/how-to-allocate-malloc-memory-in-an-angr-simulation-state). Using a plugin to allocate space on the heap for the symbolic variable, storing it, and then passing a pointer via the `call_state` function. The relevant portion of the code is pasted below. This resulted in printing `Did not find a state that reaches HelloWorld`.
```
...
# # Create a blank state at the address of the firstCall function
# init_state = project.factory.blank_state(addr=firstCall_addr.rebased_addr)

# # Assuming the calling convention passes the argument in a register
# # (e.g., x86 uses edi for the argument)
# init_state.regs.edi = input_arg

# below 4 lines taken from https://stackoverflow.com/questions/59142699/how-to-allocate-malloc-memory-in-an-angr-simulation-state
blank_state = project.factory.blank_state()
blank_state.register_plugin("heap", angr.state_plugins.heap.heap_ptmalloc.SimHeapPTMalloc())
ptr = blank_state.heap.malloc(4)
blank_state.memory.store(ptr, input_arg)

init_state = project.factory.call_state(firstCall_addr.rebased_addr, angr.PointerWrapper(ptr), base_state=blank_state)
...
```

**Comment by jacksonvanover** [comment]
I believe I have found two sources for the discrepancy:

#### 1) Fortran's pass-by-reference convention
As reported above, Fortran's pass-by-reference convention differs from C's pass-by-value convention. Accordingly, the means of passing the symbolic argument to the `firstCall` function must change. This can be done via one of the following:

Option 1:
```
init_state = project.factory.call_state(firstCall_addr.rebased_addr, angr.PointerWrapper(input_arg, buffer=True))
```

Option 2:
```
blank_state = project.factory.blank_state()
blank_state.register_plugin("heap", angr.state_plugins.heap.heap_ptmalloc.SimHeapPTMalloc())
ptr = blank_state.heap.malloc(4)
blank_state.memory.store(ptr, input_arg)

init_state = project.factory.call_state(firstCall_addr.rebased_addr, ptr, base_state=blank_state)
```

#### 2) Reversed Endianness of the BitVector when stored to memory
The difference between the constraints of the solver objects of "found" states for the C and Fortran programs provided the key insight.

C:
```
[<Bool input_arg_0_32 > 0x32>, <Bool input_arg_0_32 <= 0x63>]
```

Fortran:
```
[<Bool (input_arg_0_32[7:0] .. input_arg_0_32[15:8] .. input_arg_0_32[23:16] .. input_arg_0_32[31:24]) >s 0x32>, <Bool (input_arg_0_32[7:0] .. input_arg_0_32[15:8] .. input_arg_0_32[23:16] .. input_arg_0_32[31:24]) <s 0x64>]
```

So, by taking the results of the `eval`, `max`, and `min` functions, recreating a temporary BVV and calling `reverse` and then re-evaluating, I get correct results. Note that the C version of the program would require this as well if it were implemented with pass-by-reference via pointers.

### A working angr code for a Fortran-port of the "helloworld" symbolic execution example:
```
import angr, claripy

def endian_reverse_bvv(val, bv, solver):
    return solver.eval(claripy.BVV(val, bv.size()).reversed)

# Load the binary
project = angr.Project('./a.f90.out', auto_load_libs=False)

# Define the address of the firstCall function
firstCall_addr = project.loader.main_object.get_symbol("helloworldprogram_IP_firstcall_")

# Define the address of the helloWorld function
helloWorld_addr = project.loader.main_object.get_symbol("helloworldprogram_IP_helloworld_")
# Create a symbolic variable for the firstCall arg
input_arg = claripy.BVS('input_arg', 32)

# # option 1:
# ==========================================
init_state = project.factory.call_state(firstCall_addr.rebased_addr, angr.PointerWrapper(input_arg, buffer=True))
# ==========================================

# # option 2:
# # ==========================================
# # below 4 lines taken from https://stackoverflow.com/questions/59142699/how-to-allocate-malloc-memory-in-an-angr-simulation-state
# blank_state = project.factory.blank_state()
# blank_state.register_plugin("heap", angr.state_plugins.heap.heap_ptmalloc.SimHeapPTMalloc())
# ptr = blank_state.heap.malloc(4)
# blank_state.memory.store(ptr, input_arg)

# init_state = project.factory.call_state(firstCall_addr.rebased_addr, ptr, base_state=blank_state)
# # ==========================================

# Create a simulation manager
simgr = project.factory.simulation_manager(init_state)

# Explore the binary, looking for the address of helloWorld
simgr.explore(find=helloWorld_addr.rebased_addr)

# Check if we found a state that reached the target
if simgr.found:
    input_value = simgr.found[0].solver.eval(input_arg)
    input_value = endian_reverse_bvv(input_value, input_arg, simgr.found[0].solver)
    print(f"Value of input_arg that reaches HelloWorld: {input_value}")
    # Get the constraints for reaching the helloWorld function
    constraints = simgr.found[0].solver.constraints
    # Create a solver with the constraints
    solver = claripy.Solver()
    solver.add(constraints)
    min_val = solver.min(input_arg)
    min_val = endian_reverse_bvv(min_val, input_arg, simgr.found[0].solver)
    max_val = solver.max(input_arg)
    max_val = endian_reverse_bvv(max_val, input_arg, simgr.found[0].solver)
    print(f"Function arg: min = {min_val}, max = {max_val}")
else:
    print("Did not find a state that reaches HelloWorld.")
```

Output:
```
WARNING  | 2024-09-24 22:37:31,248 | cle.backends.tls.tls_object | The provided object has an invalid tls_data_size. Skip TLS loading.
WARNING  | 2024-09-24 22:37:31,249 | angr.calling_conventions | Guessing call prototype. Please specify prototype.
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing register with an unspecified value. This could indicate unwanted behavior.
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING  | 2024-09-24 22:37:31,261 | angr.storage.memory_mixins.default_filler_mixin | Filling register rbp with 8 unconstrained bytes referenced from 0x404211 (helloworldprogram_IP_firstcall_+0x0 in a.f90.out (0x404211))
Value of input_arg that reaches HelloWorld: 51
Function arg: min = 51, max = 99
```

The `endian_reverse_bvv` function feels hacky. Perhaps there is a built in way to do this that I am unaware of.

**Comment by rhelmot** [comment]
PointerWrapper(buffer=True) has the endian-reverse effect that you're observing. set it to False and see what happens.

For the state.memory.store option, the "buffer" behavior is default. Do `store(..., endness=project.arch.memory_endness)` to store a word, or use `state.mem` instead of `state.memory`.

**Comment by jacksonvanover** [comment]
Setting `buffer=True` came from the error I received without it (which also comes up when I set `buffer=False`):
```
TypeError: Failed to store pointer-wrapped data (Type mismatch: expected char, got 32 bits). Do you want a PointerWrapper(buffer=True)?
```

Which I interpret to mean that we can only store a byte at a time?

**Comment by rhelmot** [comment]
I'm guessing angr is giving you a warning about "guessing a prototype"? This is what that's about. When you use a call_state you need to specify `prototype="int foo(int *foo)"` or some other type that expresses the data layout you want in the C abi.

**Comment by jacksonvanover** [comment]
Works like a charm. When I provide the prototype argument and remove `buffer=True`, I no longer need the hacky `endian_reverse_bvv` function. Thank you.
