### ISSUE TITLE
TestJumpTableResolverCallTables should use precompiled binaries instead of runtime compilation

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr#4829]
### Description

Currently, in test_jumptables.py we compile test binaries from C source as part of each test, skipping the test in the case that a working compiler can't be run. See here: https://github.com/angr/angr/blob/master/tests/analyses/cfg/test_jumptables.py#L29

This approach is not portable, and prohibits testing on systems other than x86_64 linux, even when it would be possible if the binary was precompiled.

**Comment by ltfish** [comment]
Can you convert them into using binaries?
