### ISSUE TITLE
parsing an axf file to generate call graphs with angr

### ISSUE THREAD

**Issue by HemanthKrishna1** [angr/angr#4845]
### Question

Hi team,
Is it possible to parse an axf file and generate call graphs using angr?

I have an exf file and do some validations.
I need to parse an axf file to generate a call graphs with entry_function as root node.

**Comment by rhelmot** [comment]
I told you to please upload the file you are trying to analyze.

AXF files are ELF files, so they should work, but I don't know what kind of sections or segments are present in them.

**Comment by HemanthKrishna1** [comment]
Hi, thank you for your comment. 

Due to security reasons per university rules, they are not allowed to share their file. However, axf file is not corrupt and getting an error on the below code:
import angr
import networkx as nx
import matplotlib.pyplot as plt

axf_path = "gave the path here"

project = angr.Project(axf_path, auto_load_libs=False)


cfg = project.analyses.CFGFast(resolve_indirect_jumps=True)


call_graph = cfg.functions.callgraph


pos = nx.spring_layout(call_graph)
plt.figure(figsize=(12, 12))

nx.draw(call_graph, pos, with_labels=True, node_color='lightblue', font_size=10, node_size=500)

plt.title("Call Graph")
plt.show()

Now getting errors:

    cfg = project.analyses.CFGFast(resolve_indirect_jumps=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    raise KeyError(addr)
KeyError: 2148667392

**Comment by rhelmot** [comment]
Can you please provide instructions for generating a sample axf file? We cannot debug this without a sample.

**Comment by ltfish** [comment]
A stacktrace will immensely help in this case if you have trouble sharing the file.

**Comment by HemanthKrishna1** [comment]
@rhelmot @ltfish will be closing for now.
Will create a new issue once with the needed files.
