### ISSUE TITLE
angr + soot

### ISSUE THREAD

**Issue by fabiox77** [angr/angr#486]
Hi all,
I'm new to angr and I'd thank you for the great project. I'm particularly interested in analysing java and I was wondering when we can have a version of angr that supports soot.

Thanks

**Comment by ltfish** [comment]
Given the amount of work on our plates, I would not give a concrete deadline for a public angr release that supports Soot. Sorry.

It will definitely be released before the end of this year. We are in the process of making some big refactor in angr to make Soot-integration easier and less painful.

**Comment by fabiox77** [comment]
@ltfish I understand that, so I'll wait. Can we have an idea of would be available in the first release? How can you the soot representation? Are you creating plugin that converts it into VEX IR?

Thanks

**Comment by ltfish** [comment]
> Can we have an idea of would be available in the first release?

Yes. Shimple is extracted from Soot, converted into Python objects, and used directly in angr.

> How can you the soot representation?

Everything are converted into their equivalent Python objects.

> Are you creating plugin that converts it into VEX IR?

No. I believe that is a bad idea.

**Comment by fabiox77** [comment]
Thanks, I'm particularly curious. How do you convert the Shimple in python object? How can be this object be executed and have the same kind of result that you would have executing VEX? I don't think you are changing the execution environment only because of soot so I cannot really understand.

Thanks

**Comment by ltfish** [comment]
> How do you convert the Shimple in python object?

In the same way whereby we convert VEX IR into a Python based one: We create Python classes for each statement and expression class in Soot, and fill in the data we get from a Shimple representation of a program.

> How can be this object be executed and have the same kind of result that you would have executing VEX?

There will be a lot of changes, and I don't think I can detail any of them, as most of the effort in terms of symbolically executing Soot code is nowhere close to done. In brief, we are creating a new environment model for executing Soot code. This environment model will be quite different from the one you currently use in angr when symbolically executing binary code. Eventually, this Java environment should be able to co-exist with the legacy binary code environment, which will allow some interesting analyses.

However, I'm not sure how much effort we are going to spend on it, and when it will be ready. In my previous posts, I was merely saying we will have Java support. But I did not promise anything for symbolic execution on Java code.
