### ISSUE TITLE
Backwardslice example?

### ISSUE THREAD

**Issue by aflexa** [angr/angr#49]
Could you please provide a backward slicing example that would explain how to use the object after the slicing is finished? Which attributes does this object have?

**Comment by zardus** [comment]
@ltfish, do we have a simple example anywhere?

**Comment by ltfish** [comment]
Not yet. I'll make one.

**Comment by aflexa** [comment]
Thanks for the prompt response. Could you please provide the location of the example when created?

**Comment by gitttt** [comment]
I am also interested in an example. Thanks in advance!

**Comment by aflexa** [comment]
Any update on the example?

**Comment by ltfish** [comment]
- I just returned to work on angr. Examples will be available this week.
- Right now `BackwardSlice` cannot be directly applied to a `Path` or a `PathGroup`. Backward slicing on `Path` is in our TODO list though, since it's very useful. I'm not sure how to do it on a `PathGroup` other than perform a backward slice on every single path in that `PathGroup`.

**Comment by ltfish** [comment]
Sorry for taking so long to compose some notes about `BackwardSlice`. Here is a preliminary version that still has many TODOs: https://github.com/angr/angr-doc/blob/master/analyses/backward_slice.md

**Comment by aflexa** [comment]
Thank you

**Comment by aflexa** [comment]
Is there any way to limit the path group to explore just the paths in the backwardslice?

**Comment by zardus** [comment]
If you're using the `path_group.explore` method, you can pass in a function for the `avoid` kwarg. That function will be run on each path, with the path as the argument, to filter paths at every step. Currently, you'll have to craft a function to check the backward slice and decide whether to filter the path.

@ltfish, in the future, it'd be cool to add a BackwardSlice.filter_path function that could just be directly passed in as the `avoid` parameter to `path_group.explore`!

**Comment by aflexa** [comment]
I already tried that just instead of a crafting a function for the avoid kwarg, I passed a list of nodes from the cfg that should be avoided. However, it didn't work as expected! Anyway, thanks for the advice and in case you implement the BackwardSlice.filter_path function please let me know.

**Comment by ltfish** [comment]
The basic idea _was_ to generate an `AnnotatedCFG` from a `BackwardSlice`. An `AnnotatedCFG` contains information about which edges to take and which instructions to execute, and if you pass that to `Explorer`, only instructions on your slice will be executed.

It's working now, but unfortunately it lacks documentation (as always :-( ). Now that I'm done with my recent submission, I'll put as much time as I can to refactor and document the old code in those analyses.

**Comment by zardus** [comment]
@aflexa, could you provide a snippet that you're using with PathGroups? It should really work...

**Comment by aflexa** [comment]
p = angr.Project(args.binary)
state = p.factory.blank_state(addr=p.entry)

cfg = p.analyses.CFG(context_sensitivity_level=2, keep_state=True)

target_node = cfg.get_any_node(0x400d60) 
bs = p.analyses.BackwardSlice(cfg, -1, -1, targets=[ (target_node, -1) ], control_flow_slice=True)
acfg = bs.annotated_cfg(target_node)

pg = p.factory.path_group(state)
pg.explore(find=0x400d60, avoid=??)

if len(pg.found) > 0:
    fnd = pg.found[0].state
	
This is the code which I would like to limit the execution just to the paths in the backward slice.

**Comment by aflexa** [comment]
any suggestions?
