### ISSUE TITLE
Edge missing in CFGAccurate without normalization for ARM

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#493]
Hi,

As the title says, here is some examples of it:

![issue1](https://user-images.githubusercontent.com/23738463/27052837-67c9c524-4fbb-11e7-9800-f01fd28f7a9a.png)

The CFG block at 0x107e1 ends with an `bne` instruction, so it should have 2 exits: one at the address of the jump (0x10847) and one at the address of the next instruction of `bne` (0x1085b). However, the latter is missing.

![issue2](https://user-images.githubusercontent.com/23738463/27052968-e73a572e-4fbb-11e7-8a3c-3ef98eff2913.png)

Here again, the block at 0x10843 should have one edge to the block at 0x10847 and another to the block at 0x1085b. The latter is missing.

I've printed out all edges of the CFG and these edges are not there either, so I don't think this is a display problem. I got this with `angr.analyses.CFGAccurate(normalize=False)`

As @ltfish's quick investigation, this may be due to VEX optimization, since passing `opt_level=0` solves the issue. Should we disable the cross-instruction optimization by default? But when a user wants the optimization level of 1, the issue may be raised again.

Thanks,

**Comment by ltfish** [comment]
> Should we disable the cross-instruction optimization by default?

The solution is to disable the cross-instruction optimization for `opt_level=1`. This requires some vex-fu.

**Comment by rhelmot** [comment]
I don't believe this is a bug. That code looks like the start of a loop, where r2 is the loop counter. Therefore, when you enter the basic block at 0x10865, you really only do have exactly one control flow option: go to 0x1086be. When the loop comes back around, you will have multiple options. There will be another basic block block somewhere in the graph that overlaps with 0x10865, and this block will end with two branches. This is what it means to use an un-normalized CFG!

**Comment by tyb0807** [comment]
I see what you mean @rhelmot. What you say implies that the first iteration of the loop will always branch to the target of `bne`, so that we don't need the edge to the next block (if I understand you correctly). Tbh I don't know what should be the correct behaviour here. However, if this is not a bug, then I think `opt_level=0` should produce the same results (not having those edges).

**Comment by ltfish** [comment]
@rhelmot I (respectfully) disagree. In general, a user should reasonably expect the out edges of that block are the same no matter IR optimization is enabled or not.
