### ISSUE TITLE
Access to Test Case Sources

### ISSUE THREAD

**Issue by lion10** [angr/angr#4962]
### Question

How can I access the sources of the test cases that are used? Are you also using random code generators, such as CSmith, or hand-crafting them?
TIA

**Comment by mahaloz** [comment]
Hi @lion10, you're best bet is the subdir in the binaries repo:
https://github.com/angr/binaries/tree/master/tests_src

Over the years, many people have added binaries to the repo. Many of them come from open-source software that was simply compiled with a normal compiler, then found to look terrible in angr. One example of this is:
https://github.com/angr/binaries/blob/master/tests/x86_64/decompiler/cat.o

This is the `cat` binary from the `coreutils` package on Linux, likely compiled with `O2` in GCC. For each binary, I would first search the name (or ask GPT) and see if it's a widely known binary. After that, if you are still in search of the source, try pinging the author of the commit on the angr discord. 

As far as I am aware, the majority of these binaries are _not_ automatically generated. Hope this helps.

**Comment by lion10** [comment]
Thank you!
