### ISSUE TITLE
Obtain paths from CFGFast

### ISSUE THREAD

**Issue by fabiox77** [angr/angr#497]
Hi,
I know that this question might have been asked before but I didn't understand. Having a ```CFGFast``` can we have a graph that represents all the possible paths? Maybe retrieving all the successors for every node? I would avoid to use ```context_sensitivity_level```

Thanks

**Comment by ltfish** [comment]
`cfg.graph` is a networkx DiGraph. You can use `networkx.all_simple_paths()` on `cfg.graph` to retrieve all possible paths from one node to another.

**Comment by fabiox77** [comment]
Thanks @ltfish, unfortunately that method is not ok because it does not consider cycles. Also, CFGFast does not seem to reflect the reality because I've created the graph with angr-utils and different nodes return to the same node representing a function if they both call that function. Obviously it is not correct and I think it is related on how the graph was created. A solution would be to use CFGAccurate but I don't know context sensitivity level in advance and it would take too much.

Ideas?

**Comment by ltfish** [comment]
> because it does not consider cycles

Your can write your own graph traversal code to take loops into consideration. It's up to you how many iterations you want to unroll a loop when building the path.

> ... and different nodes return to the same node representing a function if they both call that function

This is why the context sensitivity is necessary. Without context sensitivity (which is the case in CFGFast), you'll have to manually maintain a call stack when you are doing your own graph traversal.

> A solution would be to use CFGAccurate but I don't know context sensitivity level in advance and it would take too much.

What do you mean by "it would take too much"?

**Comment by fabiox77** [comment]
Hi,
For me it would be enough to have the complete cfg on an image but as you said it requires context sensitivity level and if I use for example 10 it would take forever with a big file.

Do you reckon that creating my own graph exploration technique I could avoid that? If so, where should I start?

Thanks

**Comment by ltfish** [comment]
> ... but as you said it requires context sensitivity level and if I use for example 10 it would take forever with a big file

Why don't you start from the default value (1) and see whether the graph is what you want or not?

> Do you reckon that creating my own graph exploration technique I could avoid that? If so, where should I start?

You'll have the same issue: You need to decide on a value of the context sensitivity, which is roughly the maximum depth of the call stack you are maintaining (I'm too tired to precisely explain the concept here).

**Comment by fabiox77** [comment]
I have tried with 1 and it is not enough.. I need at least 3 and I think it would take a lot of time.

I think I can understand the concept, so in the end I have to decide a value, no way to have what I want without it.

Thanks

**Comment by ltfish** [comment]
> I think it would take a lot of time.

Try it first. Also try PyPy instead of CPython, which will at least give you some significant performance improvements.

If you really care about speed, maybe you want to a) use some other tools, or b) limit the amount of code that you are analyzing at the same time.

**Comment by fabiox77** [comment]
Thanks I'll try with PyPy first and see the difference.

Thanks

**Comment by fabiox77** [comment]
Hi @ltfish, I tried with context sensitivity level set to 4 but it was not enough, I need more functions, with 7 it has eaten 14gb of ram. What other tool do you think would be able to generate the cfg? I'm not really interested in that, I was thinking to have the cfg maybe just using the cfg fast. Maybe it is possible.

Thanks
