### ISSUE TITLE
ImportError: cannot import name operations

### ISSUE THREAD

**Issue by hahwul** [angr/angr#498]
Hi angr team.
I install angr using pip, but when i try to run the following commands

    Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 5.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: import angr
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-bcea9b74a356> in <module>()
    [..........]
    /usr/local/lib/python2.7/dist-packages/claripy/__init__.py in <module>()
         10 
         11 from .errors import *
    ---> 12 from . import operations
         13 from . import ops as _all_operations

ImportError: cannot import name operations

I think problem point is operations in claripy library.
but it is the same though it is reinstalled.
What should I do?

**Comment by fabiox77** [comment]
Hi,
I think I had this problem in the past. Could you try ```pip install angr upgrade``` or ```pip uninstall angr``` and after ```pip install angr```

Thanks

**Comment by ltfish** [comment]
Try to install angr in a virtualenv.

**Comment by hahwul** [comment]
I solving the problem with virtualenv.
Thank you.
