### ISSUE TITLE
is uc-angr open-sourced?

### ISSUE THREAD

**Issue by humeafo** [angr/angr#500]
I just read the angr paper and noticed UC-angr, is that project open-sourced like driller?

**Comment by ltfish** [comment]
It is open-sourced. Actually, it is part of SimuVEX, working as a state option. Please take a look at [this line](https://github.com/angr/simuvex/blob/master/simuvex/s_options.py#L186).

**Comment by humeafo** [comment]
thank you for the info, please close this.

**Comment by ltfish** [comment]
You are welcome.
