### ISSUE TITLE
How to pickle and reload intermediate cfg?

### ISSUE THREAD

**Issue by fabiox77** [angr/angr#505]
Hi all
In case I would need to generate a CFGAccurate with a context_sensitivity_level really high can I pickle an intermediate result, close the project in order to free the RAM, reload the saved object and restart from where I left?

Can I see a demo code?

Thanks

**Comment by fabiox77** [comment]
Hi,
I read the CFGAccurate documentation and I think via ```max_steps``` and ```resume``` I could achieve what I need. However I'm able to generate a partial CFGAccurate using those option but after I ```cfg.resume()``` the execution stops instantly and I have the same number on nodes. Any help?

Thanks

**Comment by fabiox77** [comment]
Hi,
I'm sorry to chase but I do really need to know how to proceed. Can anyone show me how to use resume on an example?

Thanks

**Comment by zardus** [comment]
@ltfish is your only hope...

A quick grep of the code shows that resume is used in some capacity in `angr/exploration_techniques/director.py`. That might help shed some light on how it works?

**Comment by fabiox77** [comment]
Thanks @zardus, I'll wait his comment and in the mean time have a look on that file.

Thanks

**Comment by fabiox77** [comment]
Hi
Just to clarify, if I create the cfg with max_steps I have only one node that is _start as expected. If I try resume with any max_steps I have only one node, instead if I create a state at the _start address and I pass it as an entry point I have few more nodes. My goal is just be able to pause the CFGAccurate and restart it from where I left. What would be the best way?

Thanks

**Comment by ltfish** [comment]
I thought I replied in this thread before. Apparently I didn't...

Pickling intermediate CFGAccurate results are not supported as of now. However, I believe it is not too hard to add such a support.

**Comment by fabiox77** [comment]
No problem @ltfish. So far I have implemented a way to pause a CFGAccurate after N nodes. Unfortunately if the graph has a huge number of nodes it would take forever. (eg 50k+ nodes). I'd there a way to improve it?

My way to implement a pause is just to return from _analysis_core_baremetal()

Thanks

**Comment by ltfish** [comment]
Are you pickling all of the states, too? Pickling that many states will take forever...

**Comment by fabiox77** [comment]
Hi, I suppose so because I just use pickle.dumps. how can exclude them? I think I need to change getstate in CFGAccurate but I'm not sure how.

Thanks

**Comment by fabiox77** [comment]
In case it could be useful to you or anyone else. I have added the following attributes in __getstate__ for the CFGAccurate:

```
#new
            '_job_info_queue': self._job_info_queue,
            '_should_abort': self._should_abort,
            '_status_callback': self._status_callback,
            '_pending_jobs': self._pending_jobs,
            #'kb': self.kb,
            '_jobs_to_analyze_per_function': self._jobs_to_analyze_per_function,
            '_traced_addrs': self._traced_addrs,
            '_max_iterations': self._max_iterations,
            '_base_graph': self._base_graph,
            '_keep_state': self._keep_state,
            '_iropt_level': self._iropt_level,
            '_max_steps': self._max_steps,
            '_context_sensitivity_level': self._context_sensitivity_level,
            '_enable_function_hints': self._enable_function_hints,
            '_pending_edges': self._pending_edges,
            '_block_artifacts': self._block_artifacts,
            '_job_map': self._job_map,
            '_avoid_runs': self._avoid_runs,
            '_additional_edges': self._additional_edges,
            '_address_whitelist': self._address_whitelist,
            '_non_returning_functions': self._non_returning_functions,
            '_allow_merging': self._allow_merging,
            '_order_jobs': self._order_jobs,
            '_pending_function_hints': self._pending_function_hints,
            '_function_input_states': self._function_input_states,
            '_call_depth': self._call_depth,
            '_advanced_backward_slicing': self._advanced_backward_slicing,
            '_completed_functions': self._completed_functions,
            '_changed_functions': self._changed_functions,
            '_normalized': self._normalized,
            '_normalize': self._normalize,
            '_times': self._times,
```

**Comment by ltfish** [comment]
> Hi, I suppose so because I just use pickle.dumps. how can exclude them?

Before pickling, you can traverse all CFGNodes in `cfg.nodes()` and empty the `initial_state` and `final_states`. You may do it in `__getstate__()`.

**Comment by fabiox77** [comment]
Thanks, I'll do as you said assigning None to them.. appreciated

**Comment by fabiox77** [comment]
Sorry, is it input_state or initial_state?

**Comment by ltfish** [comment]
`input_state`.

**Comment by fabiox77** [comment]
Thanks, i did

```for node in self.nodes():
        node.input_state = None
        node.final_states = []
```

In the ```__getstate__``` of the CFGAccurate but it takes over an hour for 50k nodes, I had to stop it. I think in my new elements in ```__getstate__``` is causing the issue.

Thanks

**Comment by ltfish** [comment]
You might want to run it with `-m cProfile` to see what's taking up that much time.

**Comment by fabiox77** [comment]
Unfortunately pickle and dill seem to be the bottle neck:

```
380   19.118    0.050   37.984    0.100 dill.py:1115(_locate_object)
      380    0.010    0.000   42.284    0.111 dill.py:1143(save_weakproxy)
      161    0.001    0.000    0.002    0.000 dill.py:1206(save_type)
        5    0.000    0.000    0.000    0.000 dill.py:1283(save_function)
   492486    0.098    0.000    0.098    0.000 dill.py:1369(is_dill)
        5    0.000    0.000    0.000    0.000 dill.py:759(_import_module)
        5    0.000    0.000    0.000    0.000 dill.py:773(_locate_function)
 164162/1    0.704    0.000   65.795   65.795 dill.py:811(save_module_dict)
        5    0.000    0.000    0.000    0.000 elf.py:226(__getstate__)
        1    0.000    0.000    0.000    0.000 engine.py:569(__getstate__)
        5    0.000    0.000    0.000    0.000 engine.py:85(__getstate__)
        1    0.000    0.000    0.000    0.000 engines.py:183(__getstate__)
        1    0.000    0.000    0.000    0.000 engines.py:57(__getstate__)
        1    0.000    0.000    0.000    0.000 engines.py:98(__getstate__)
      577    0.000    0.000    0.000    0.000 frontend.py:36(_ana_getstate)
      197    0.000    0.000    0.001    0.000 full_frontend.py:40(_ana_getstate)
        1    0.000    0.000    0.000    0.000 graph.py:610(nodes_iter)
        1    0.000    0.000    0.000    0.000 graph.py:645(nodes)
        8    0.000    0.000    0.000    0.000 memory.py:102(__getstate__)
      197    0.001    0.000    0.023    0.000 model_cache_mixin.py:86(_ana_getstate)
     2660    0.009    0.000    0.009    0.000 paged_memory.py:351(__getstate__)
    35233    0.122    0.000    0.171    0.000 pickle.py:1274(encode_long)
        1    0.000    0.000   65.797   65.797 pickle.py:1375(dump)
        1    0.000    0.000    0.000    0.000 pickle.py:173(__init__)
        1    0.000    0.000   65.797   65.797 pickle.py:220(dump)
   563919    0.724    0.000    1.337    0.000 pickle.py:227(memoize)
   563919    0.239    0.000    0.341    0.000 pickle.py:250(put)
  1507492    0.677    0.000    0.923    0.000 pickle.py:260(get)
4574734/1    5.827    0.000   65.797   65.797 pickle.py:269(save)
  4574734    0.388    0.000    0.388    0.000 pickle.py:333(persistent_id)
 175543/1    0.805    0.000   65.795   65.795 pickle.py:345(save_reduce)
  1919188    0.425    0.000    0.878    0.000 pickle.py:432(save_none)
    36099    0.016    0.000    0.026    0.000 pickle.py:436(save_bool)
   394669    0.315    0.000    0.742    0.000 pickle.py:443(save_int)
    35233    0.053    0.000    0.242    0.000 pickle.py:467(save_long)
       67    0.000    0.000    0.000    0.000 pickle.py:479(save_float)
     2947    0.004    0.000    0.013    0.000 pickle.py:486(save_string)
     2252    0.003    0.000    0.012    0.000 pickle.py:498(save_unicode)
280661/21350    1.184    0.000   64.194    0.003 pickle.py:538(save_tuple)
56633/12419    0.111    0.000   35.272    0.003 pickle.py:597(save_list)
56633/12419    2.114    0.000   35.169    0.003 pickle.py:614(_batch_appends)
 164162/1    0.308    0.000   65.795   65.795 pickle.py:646(save_dict)
 164256/1    4.276    0.000   65.795   65.795 pickle.py:661(_batch_setitems)
```

This was for 1000 nodes.

**Comment by ltfish** [comment]
A suggestion:

- Run your script with `python -m cProfile -o output.profile xxx.py`
- Install _Run Snake Run_
- View the `output.profile` with _Run Snake Run_: `runsnake output.profile`

With a visualization of the profiling result, it's easier to figure out what the culprit is.

It is natural that you see `pickle` taking up the most of the time. The point is that you might be unnecessarily pickling some objects.

**Comment by ltfish** [comment]
Before I go to bed: If you are not using PyPy, give it a try.

**Comment by fabiox77** [comment]
Thanks @ltfish,
I'm pretty sure I'm pickling something I don't need but at the moment it is
hard to understand what :) I'll follow your suggestions anyway.

Thanks

**Comment by fabiox77** [comment]
Hi,
I have investigated a bit and the culprit seems to be ```_job_info_queue``` because with it I can save 50k nodes quickly. Any idea what I can avoid to pickle for it?

Thanks

**Comment by fabiox77** [comment]
@ltfish, sorry to ask again, can you tell me how and when remove a CFGJob from the queue please? That object is too big when I try to pickle the cfg.

Thanks

**Comment by ltfish** [comment]
Are you talking about `CFGFast`? I wonder why a `CFGJob` can be too big...

**Comment by fabiox77** [comment]
Hi, no CFGAccurate... If you have time can you pickle a cfg with 50k+ nodes? But an intermediate with all the CFGJobs .

Thanks

**Comment by ltfish** [comment]
Personally I don't have time recently, but I can see that this will be a useful feature. It's possible that someone else or myself will implement it in the near future.

**Comment by fabiox77** [comment]
I'm working on it and happy to share anything. Just one question, do I need all CFGJobs or I can remove them at some point? If you have any suggestion I'll try to do it...

Thanks

**Comment by ltfish** [comment]
You do need all `CFGJob`s. But I really don't understand why they'll take that long to pickle. Maybe you can try to implement `__getstate__` and `__setstate__` for `CFGJob`?

You may push your work somewhere on GitHub, and someone else or me can start working on top of that.

**Comment by fabiox77** [comment]
Thanks, I'll starting creating getstate and setstate for the CFGJobs and see if I can narrow down the problem.

Thanks

**Comment by fabiox77** [comment]
@ltfish, so I've been working on it but not with great results. I've created the ```__getstate__``` for ```CFGJob``` but after I save the partial CFGAccurate and I try to continue I have a problem with ```cfg._call_stack```. I have an error like ```tuple has no attribute stack_suffix```. I saved the ```_call_stack``` using the same approach you use in angr. Should I do something different?

Thanks

**Comment by fabiox77** [comment]
Hi, I have update angr and now I have problems with FuncDict.__missing__ because the key is empty when I load a pickled CFGAccurate. I didn't implement any getstate. Any idea?

**Comment by fabiox77** [comment]
@ltfish, so I started easy and I'm now able to save a partial CFGAccurate made of 10k nodes. The fact is that if I include .state for all the CFGJobs it takes forever.. do I need the state for all the CFGJobs or I can avoid it in some case?

Thanks
