### ISSUE TITLE
Use angr first time, but reported that Unicorn is not installed and failed loading "angr_native.dll"

### ISSUE THREAD

**Issue by 79t1ckz** [angr/angr#5070]
### Question

I just installed by `pip install angr`, and then I tried to run a hello world with angr, but here are the warnings:
```
WARNING  | 2024-12-10 20:17:44,889 | angr.state_plugins.unicorn_engine | Unicorn is not installed. Support disabled.
WARNING  | 2024-12-10 20:17:44,942 | angr.state_plugins.unicorn_engine | failed loading "angr_native.dll", unicorn support disabled ('NoneType' object has no attribute 'unicorn')
```
the python version is 3.12. I'm looking forward to you reply :)

**Comment by ltfish** [comment]
You can try to manually install unicorn engine in your virtualenv using the following command: `pip install unicorn==2.0.1.post1`.

**Comment by 79t1ckz** [comment]
Solved. Thanks !
