### ISSUE TITLE
howto get fork points during pg se

### ISSUE THREAD

**Issue by humeafo** [angr/angr#510]
is there a good way to get symbolic fork points info and maintain them in every path？

**Comment by zardus** [comment]
Take a look at `path.branch_causes`. It'll give you the address of every branch and the name of the variable responsible. For tracking other info in every path, check out `path.info`: it's a dict that's shallow-copied along as paths branch.

**Comment by humeafo** [comment]
I noticed that h.addr == h._jump_source == block start address, should h._jump_source be the exact branch instruction address?

**Comment by rhelmot** [comment]
No. Addresses in angr generally refer to basic block addresses, since angr processes code in chunks of basic blocks. If you need the address for something you can lift the block starting at that address and get the address of its last instruction.

**Comment by humeafo** [comment]
thanks for your infos. 
another related question is how to get the opportunity to run my code just before executing a path_step and after a new path is created, I tried using state.inspect.b('path_step',...) but in the callback the state.inspect.path attrib is None because it is called by:
self.state._inspect('path_step', simuvex.BP_BEFORE)
, I think another option is to use exploration technique, but I 'm not sure whether the .step_path/.filter is the right place because there maybe complex chainings etc of ExplorationTechnique instances. or is there any reliable way of doing this in angr?

**Comment by zardus** [comment]
Currently, the most uninvasive method would be to hook `step` with an ExplorationTechnique. When this runs, you can visit each path in the stash being stepped, do your recordkeeping, then step the path group. This will work nicely with other exploration techniques.

As we speak, though, we're working on merging `simuvex` and `angr`. This will result in a convergence of many concepts, including making SimInspect considerably more powerful. After the merge is done (hopefully Somewhat Soon Now), you'll be able to do what you're trying to do with SimInspect.

**Comment by humeafo** [comment]
thanks ExplorationTechnique method works fine, you can close this now.
