### ISSUE TITLE
about path test case generation

### ISSUE THREAD

**Issue by humeafo** [angr/angr#519]
there already was a  question https://github.com/angr/angr/issues/501, but mine is that given a path, how to generate the testcase for the path, there maybe many symbolic variables introduced in simproc etc not convenient for the testcase gen code to know in advance, besides using a custom sym-var passing method, is there any better methods to accomplish this? what I can think out is to parse the state's constraints to do this, any suggestions?

**Comment by zardus** [comment]
If you're interested in getting a testcase to feed into the program, I think `state.posix.dumps(0)` (to dump out standard input) is probably what you want, regardless of the symbolic variables.

**Comment by humeafo** [comment]
@zardus in most cases state.posix.dumps(0) is enough, but for my analysis it's not because some input is not from stdin or file, instead they are marked by my analysis code, so there should be a general method to generate the testcase.

**Comment by zardus** [comment]
Where in the testcase would you want these extra variables to be inserted?

**Comment by humeafo** [comment]
My case is that I should insert some symbolic variable when calling some interface function such as fA(sym1), fB(sym2) fC(sym3) etc, it's not directly from file input, and maybe fA, fB, fC etc are the static analysis results, i don't want to manually specify the symvar in python code... the test case is just the symvar value.
may be this case is like selective SE, but not totally UC-SE.

**Comment by zardus** [comment]
So you're looking for a way to automatically specify return values from these functions into future instances of symbolic execution?

**Comment by humeafo** [comment]
I can automatically specify eg return values of these functions as symbolic variables(possibly with some constraints) into future instances of symbolic execution using angr's inspect, hook etc, but after a path reach a certain state, I need to generate test case for these symbolic variables, because they are specified by analysis code automaticlly, I need to know their name/expr to do accomplish this.
Now I can accomplish this by parsing path's constraints in hacky way to traverse the claripy ast, but it seems claripy not implemented a formal visit method, I have to use the implementation details such as "op" "args" etc to do this.

**Comment by zardus** [comment]
Ok, I see.

The "correct" way to do this is to log this into a state plugin. You can
(ab)use the existing `state.procedure_data.global_variables` for it (soon,
this will be renamed to `state.globals`, but you're ok for now). Store the
variable during your hook, and extract it when you want to generate your
testcases.

Let me know if I'm still misunderstanding :-)

**Comment by humeafo** [comment]
I think we both get the point, your solution is ok for me, this question can be closed.
