### ISSUE TITLE
Create CFGAccurate with threads

### ISSUE THREAD

**Issue by fabiox77** [angr/angr#521]
Hi,
Is it possible to generate a CFGAccurate using multiple threads at the same time? How would you approach it?

Thanks

**Comment by ltfish** [comment]
It is not possible as of now.

**Comment by fabiox77** [comment]
Thanks, as a curiosity, it is not possible because a cfgjob must execute in order one after the other or for any other reason?

Thanks

**Comment by ltfish** [comment]
The only reason is that multi-threading support is totally not implemented, on top of the fact that Python has GIL, multi-threading (not multi-processing) will not give you any benefit. But if you want, you can implement the multi-threading support.

**Comment by fabiox77** [comment]
Thanks, I was thinking that the benefit would have been to have a cfg create in a much faster way but I think it is not possible as you said.
