### ISSUE TITLE
Can we jsonpickle a CFG?

### ISSUE THREAD

**Issue by frapik99** [angr/angr#523]
Hi,
is it possible to use ```jsonpickle``` with an ```CFGAccurate```? I tried using ```dill``` but if the graph is too big it takes forever. I have seen that for example ```SimState``` cannot be serialized because not iterable.  Do you think that it is possible to solve the problem or should I do something different?

EDIT:
If I import ```SImState``` from ```SimuVEX``` and I try to encode it using jsonpickle all works. I think I'm missing something.

Thanks

**Comment by ltfish** [comment]
`pickle` works (make sure you use `pickle.dumps(cfg, -1)`). I don't know how well `jsonpickle` works.

**Comment by frapik99** [comment]
Thanks @ltfish , with pickle works. I have amended the ```CFGAccurate``` class and now I have the following error:

```PicklingError: Can't pickle <function <lambda> at 0x7f8638d1aed8>: it's not found as angr.analyses.cfg.cfg_accurate.<lambda>```. I think because ```__getstate__``` used a lambda fuction. Is it possible to do something in order to have that function pickled correctly?

As a side note, I think ```jsonpickle``` would be faster then ```pickle``` so you could consider to add support for it.

Thanks

**Comment by ltfish** [comment]
Take a look at `CFGAccurate.__getstate__()`, make sure there is no lambda function exists in that dict.

> As a side note, I think jsonpickle would be faster then pickle so you could consider to add support for it.

It's not in our plan. Feel free to add support for it and give us a PR!

**Comment by frapik99** [comment]
@ltfish , I need a lambda function honestly...

Do you have a suggestion on how to fix the problem with SimState? I would work on a PR than...

**Comment by ltfish** [comment]
I would assume you don't want to pickle that lambda function with CFGAccurate. Can you remove that lambda function in `__getstate__` and then set that lambda function again in `__setstate__`?

**Comment by frapik99** [comment]
oh, I see what you mean.  I'll try later because I need to understand which function is it and how reassign it to it.

Thanks

**Comment by ltfish** [comment]
No problem!

**Comment by frapik99** [comment]
Sorry, but how can I assign a lambda function in __setstate__? I think it is _pending_function_hints the problem...

Thanks

**Comment by ltfish** [comment]
`_pending_function_hints` are not pickled by default. Did you change the code?

**Comment by fabiox77** [comment]
Yes, I'm doing some experiments.. i need to save a partial CFGAccurate if
too big.. I have seen a similar question recently.. any suggestion?

Thanks

**Comment by ltfish** [comment]
`_pending_function_hints` is just a set. If you didn't change how it is implemented, it shouldn't be a problem. For other classes (that are the real culprit of the issue), you can implement `__setstate__` and `__getstate__` for them individually.
