### ISSUE TITLE
Deadended states lost when executing part of a binary

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#525]
Hello,

In case we skip part of a binary and start our simulation manager at a specific function (usually `main`), when we reach the end of this function, the return site is symbolic, thus the warning `Exit state has over 257 possible solutions. Likely unconstrained; skipping.`. This puts the new state into `unconstrained_successors`, however, imho, because of these lines in `manager.py`, we lost the state (it is no more in the `simgr.stashes`):
```
    if not active and not unconstrained and orig:
      always_present['deadended'].append(orig)
```
Is this behaviour intended?

**Comment by rhelmot** [comment]
simgr/path group have a constructor option called `save_unconstrained` - try toggling it on and seeing if you get an `unconstrained` stash! I wrote the code to do this, but I haven't tested it...

**Comment by tyb0807** [comment]
Yes we get the `unconstrained` stash with that option enabled

**Comment by rhelmot** [comment]
Yeah, unless yan or fish have something to say on the matter, I'm going to call having put unconstrained states in deadended previously a bug.

**Comment by ltfish** [comment]
@rhelmot Do we want to enable `save_unconstrained` by default? Otherwise the default behavior that paths go missing after stepping is really confusing to me.

**Comment by tyb0807** [comment]
:+1: for @ltfish. Missing paths are confusing!
