### ISSUE TITLE
error importing angr

### ISSUE THREAD

**Issue by benquike** [angr/angr#528]
No such file or directory: site-packages/angr/analyses/identifier/../example_flag_page'

**Comment by zardus** [comment]
Interesting... Looks like we don't install the example flag page properly when angr is pip installed. I'd recommend doing an editable install (`pip install -e`, which is also done through setup.sh). We'll fix up the pip setup process in the upcoming release.

**Comment by rhelmot** [comment]
This has been fixed in a recent release.
