### ISSUE TITLE
feature request: on symbolic forking callback or deep-copied per-state/path info

### ISSUE THREAD

**Issue by humeafo** [angr/angr#529]
path.info is shallow copied each new path is created(even there is no symbolic forking), so on symbolic forking, if there is a callback for me to deep-copy or maintain some data would be great, or if there's a similar field like info but if it is not None, then deep-copied by angr only on symbolic forking would satisfy my needs.
now I maintain data in path.info and do deep-copy using exploration techniques, but I felt not so elegant...
I haven't looked into end_time branch yet, so if this already existed in the next release, forgive me.

**Comment by zardus** [comment]
It's amazing how widely news of The End Times has spread :-)

This might, indeed, be easier in after The End Times is upon us. Basically, with Path gone, the successor to `path.info` will be a state plugin (named, in the current TET design, `state.globals`) that you'll be able to specialize as you wish.

That being said, checking whether a state is a result of a symbolic branch or not will still be tricky. I'm not against providing a SimInspect callback for that (maybe something with a BP_BEFORE right before and a BP_AFTER right after https://github.com/angr/angr/blob/wip/the_end_times/angr/engines/engine.py#L42), but the way you're doing it right now, with the exploration technique, might still be the nicest way.

**Comment by humeafo** [comment]
I think if there is a inspect callback, many things would be much easier for angr users, using exploration technique involving more codes and more detailed error-prone processing, making codes hard to understand in many cases too.

**Comment by rhelmot** [comment]
I've been thinking about this, and here are my two cents:

1. We generally try to stray as far away from deepcopying objects anywhere in angr, since angr objects are highly interconnected and if we accidentally deepcopy an object holding a reference to the state or the project, we'll make a copy of the entire project, which is not good.
2. There are applications in angr currently that have the same technical requirements as your request, and they solve it by using path.info/state.globals and treating the object they want to change as immutable, whenever they need to update them, they construct a new copy instead. This is the most efficient way of doing this.
3. We do definitely need a callback for "new fork being created".
4. I am very sad at your appraisal of exploration techniques as hard to use and error-prone :(

**Comment by zardus** [comment]
For `#4`, I think it's the name, @rhelmot ;-)

**Comment by humeafo** [comment]
to @rhelmot 
#2 treat data in path.info or state.globals as immutable can achieve the same result, but maybe not so efficient if there are many updates or copied data are big in a long running path with little symbolic forking, by do copy on forking only can save more memory and CPU(though we're using python). 
 
#4, exploration techniques was good for real exploration strategies, but compared to a "new fork being created" callback, using exploration technique to implement the same functionality is a bit tricky and tedious, I'm new to angr, so I have to study the interactions between exploration strategies and  how they affect my tasks, considering things such as: 
a. do work before or after pg.step() in technique step callback
b. when my exploration technique will be called, before or after other techniques callback?
c. when use the specified technique, should user-code care about the tech register order?

of course, after examining the path-group codes, we can solve all these questions, this is why I said the above words, it's not because exploration techniques was not good, but maybe it's not the best for a angr beginners to solve similar problems...

**Comment by zardus** [comment]
I just had a chat with @tyb0807, who was looking for similar functionality, and he's going to take a stab at implementing the `engine_process` SimInspect event in TET. Per discussion on slack, we're thinking:

- In `SimEngine.process`, before calling `SimEngine._process`, the `engine_process` `BP_BEFORE` action will be triggered and the engine, SimSuccessor object, and relevant args will be passed in.
- After `SimEngine._process` returns, the `BP_AFTER` breakpoint will be called.

The logic we're discussing here can be implemented in that `BP_AFTER` breakpoint.
