### ISSUE TITLE
Always copying SimState.arch when SimState is copied

### ISSUE THREAD

**Issue by ltfish** [angr/angr#542]
This is about my recent commit on TET: 0199a41a40300e3502b13ac680659e5b0445f8dd

The context is that if `arch` is not copied-on-write, any instruction changing `state.arch` (e.g., `state.arch.vex_archinfo`) will change it globally. As VEX relies on `arch.vex_archinfo`, a simple `mov cr0, xxx` can break *all* future lifting.

However, I'm not sure how much performance overhead this commit will yield. I don't like this fix. Maybe the correct solution is to move `cr0` out of `arch`.

@zardus @rhelmot @salls Comments?

**Comment by zardus** [comment]
I guess we resolved this (https://github.com/angr/angr/commit/5d1dc6620ba0f08ef0475156b1b1f2b8b00ffeae). Let's reopen if it's still an issue.
