### ISSUE TITLE
Make global variables symbolic

### ISSUE THREAD

**Issue by zhaogang92** [angr/angr#543]
Hi,
I am learning angr recently. I have a simple pthread program.

```C
#include <stdio.h>
#include <pthread.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>

int x=0;
int y=0;
void *func(void *);
int main(){
	pthread_t t1;
	pthread_create(&t1, NULL, func, NULL);
	if(y==0){
	    usleep(1);
            x=1;
        }
	pthread_join(t1, NULL);
	printf("x= %d, y= %d\n",x,y);
	return 0;
}
void *func(void *ptr){
	if(x==0){
        y=1;
    }
}
```

When I use angr to symbolically run this program, I expect that when angr reach branch condition `y==0`, there should be two paths. But actually only one. It seems angr initializes both x & y to their concrete initial values 0. I found another issue #209 also mentions this problem. I know how to manually get the addresses of x and y and make them symbolic, but is there anyway to automatically make all the global variables symbolic? Any answer is appreciated. Thanks!

**Comment by rhelmot** [comment]
The notion of a "global variable" is very sketchy on the binary level, and there's no easy way to just make _all_ of them symbolic without seriously messing up the rest of the program, e.g. making the pointer to stdout symbolic.

If you want to find the address of x manually to make it symbolic, you will need to use a disassembler like objdump or ida pro. If you've compiled your binary with debug symbols, you may be able to find it in the output of `readelf` as well!

**Comment by zhaogang92** [comment]
Hi rhelmot, thanks for your reply. Yeah I know how to manually make x and y symbolic and it does work in my previous experiments. But it is kind of clumsy because I have to do this for each binary that I want to analyze. Debug symbols is a good solution, but in my application very likely there is no debug symbols available.

Your concern is right, messing up the rest of the program is really a problem. Seems I have to do this manually. Anyway, Thanks for your help!
