### ISSUE TITLE
Confused about Caller detail

### ISSUE THREAD

**Issue by TN-root** [angr/angr#548]
@ltfish
When I call the caller() function to implement symbolic exploration. I set a start_address and other parameter.then I print the result of run() couldn't find found[] path.
Script:
![number](https://user-images.githubusercontent.com/30521851/28709386-b2431a0e-73b2-11e7-888e-e2186a418a22.png)
![number2](https://user-images.githubusercontent.com/30521851/28709474-0459d9a4-73b3-11e7-998e-94f3b25acc0f.png)
then I check every path, according to the result I realize that every path is end at the same block, so I search  
binary file ,this block is a library function which name is __longjmp_chk(), and the simuvex file couldn't find any conduct about this library function.
I want to know whether or not  angr dealing with this library function? Thank you!

**Comment by rhelmot** [comment]
`longjmp` is a library function which jumps to a corresponding `setjmp`. In angr there is no good way to emulate this, so it is just emulated as an exit, which is reasonable since no path can continue beyond there.
