### ISSUE TITLE
AttributeError in Path _manage_callstack due to state with symbolic IP

### ISSUE THREAD

**Issue by RayFoulk** [angr/angr#557]
Note: This effects the old angr architecture, and may be obsoleted by the newly refactored codebase.

The problem code that causes this error has  data structure located in symbolic memory, a pointer to which is on the stack.  Backtrace is attached.

[backtrace.txt](https://github.com/angr/angr/files/1197455/backtrace.txt)

Setting project.factory.path_group(state, resilience=True) does not workaround the problem as AttributeError is not ignored by PathGroup _one_path_step at line 236.

**Comment by RayFoulk** [comment]
Patching line 236 of path_group.py from:
    except (AngrError, simuvex.SimError, claripy.ClaripyError)
to:
    except (AngrError, simuvex.SimError, claripy.ClaripyError, AttributeError):
in conjunction with setting path_group resilience=True, although hacky & not ideal, at least allows execution to continue and in my case allows angr to solve the problem normally.

**Comment by RayFoulk** [comment]
Here is perhaps a better workaround:

--- /home/rfoulk/VEs/Angr/lib/python2.7/site-packages/angr/path.py.backup
+++ /home/rfoulk/VEs/Angr/lib/python2.7/site-packages/angr/path.py
@@ -561,6 +561,9 @@
                 sp = state.se.max(state.regs.sp)
             else:
                 sp = state.regs.sp._model_concrete.value
+
+            if state.regs.ip.symbolic:
+                raise AngrError("IP cannot be symbolic")
 
             # ip cannot be symbolic
             ip = state.regs.ip._model_concrete.value

**Comment by RayFoulk** [comment]
This is probably a better patch:

[patch.txt](https://github.com/angr/angr/files/1197605/patch.txt)

**Comment by rhelmot** [comment]
I believe this is fixed in the latest master - we've removed Path entirely and the callstack tracking was rewritten as a state plugin, and given a bit more care this time.

Sorry for letting this issue slip through the cracks, it's very easy to lose track of them :/
