### ISSUE TITLE
File testcase fail to generated after upgrading angr

### ISSUE THREAD

**Issue by wubingwang** [angr/angr#560]
I write a simple binary which take the argument '-l' and a file as input and want use symbolic execution to generated different test files to cover all possibilities. The shrunk pseudo-code of the binary is:
``` C++
char *arg1 = argv[1];
if (strcmp(arg1, "-l") != 0)  exit(0);
fp = fopen(argv[2], "r");
fgets(v, 255, fp);
j = atoi(v);
if (j<=5){ Something }
else{ Something }
```

The script used to get test files are:
``` Java
b = angr.Project('./test', load_options={'auto_load_libs':True})
state = b.factory.entry_state(remove_options={'simuvex.o.LAZY_SOLVES'}, args=['./test', '-l', './input'])
pg = b.factory.path_group(state)
pg.explore()
```
In older version of angr, the generated test files can be found with `path.state.posix.dumps(3)`. However, after upgrade to the latest version of angr, the file id 3 do not created. 

[test.tar.gz](https://github.com/angr/angr/files/1200243/test.tar.gz) is my test binary and source code. @rhelmot 

Thanks.

**Comment by rhelmot** [comment]
I see. This is the result of https://github.com/angr/simuvex/pull/108, which made it so that when you close a file, its descriptor actually disappears, like in a real OS. The recommended solution now is to use `state.posix.dump_file_by_path('./input')`.
