### ISSUE TITLE
No module named procedures.stubs.UserHook

### ISSUE THREAD

**Issue by jluysf** [angr/angr#565]
After pip install angr:

```
(venv)$:~/work/angr/angr-doc/examples/whitehat_crypto400$ python solve.py 
WARNING | 2017-08-07 04:16:46,082 | claripy | Claripy is setting the recursion limit to 15000. If Python segfaults, I am sorry.
Traceback (most recent call last):
  File "solve.py", line 18, in <module>
    from angr.procedures.stubs.UserHook import UserHook
**ImportError: No module named procedures.stubs.UserHook**
```

**Comment by rhelmot** [comment]
This is a byproduct of a refactor that angr is going through currently. The version available on github is a pre-release for a major version bump, and is incompatible with the old APIs, i.e. the ones available on pip.

If you want to make this script work you will need to either check out an old version of angr-docs, from before we started the refactor, or install angr from github (use the angr-dev repository to get a script to do this for you)

**Comment by jluysf** [comment]
it's very helpful to me. thank you.

**Comment by zardus** [comment]
Let's keep this open until we remember to fix this example :-)

**Comment by rhelmot** [comment]
No, we've already fixed this example, this guy was just trying to use it against the pip version.
