### ISSUE TITLE
factory.call_state API is hard to use

### ISSUE THREAD

**Issue by bennofs** [angr/angr#570]
I tried to use `factory.call_state`, but I hit several problems:

* it is not possible to specify stack alignment requirements
* the current API is very "ad hoc", and does surprising things. For example:
    * anything that has length 4 is endian-adjusted. so if I use a bitvector for a string of length 4 it will reverse the string
    * strings get automatically converted to pointers, but `BVS` / `BVV` longer than 4 isn't
    * strings are auomatically null terminated

In general, I find it very hard to understand how `factory.call_state` (and `SimCC.setup_callsite`) will convert my values. Can this API be redesigned? I would volunteer to attempt this, what is the policy on backwards compatibility?

**Comment by zardus** [comment]
Backwards compatibility is definitely "best effort", but definitely on the optional side. Correctness, of course, is important. As long as the testcases run, and the result is correct, we're absolutely open for redesigns.

@rhelmot (and probably @ltfish as well) are the experts with this stuff, and I'm sure they'd have input on any PR you want to undertake. I'd recommend making a WIP PR and pushing frequently!

**Comment by rhelmot** [comment]
One important thing you can do to make the API more predictable is wrap anything you want wrapped in a pointer with a `PointerWrapper`, a reference to which can be found in `project.factory.callable.PointerWrapper`, if I recall correctly.

Other than that, yes, the API is intensely ad-hoc and needs a principled redesign. I don't believe there is much in the way of dependencies on the existing behavior, and whatever you break probably won't have a hard time being rewritten if your redesign is as principled as promised.

**Comment by rhelmot** [comment]
Oh, and now is probably the best time to break APIs anyway, since we're gearing up for a major version bump :)
