### ISSUE TITLE
VFG unit test fails

### ISSUE THREAD

**Issue by eroncevich** [angr/angr#573]
Running test_vfg.py fails and ends with:

`SimValueError("concretized %d values (%d required) in exactly_int", len(r), 1). `

It seems to crash whenever the command project.analyses.VFG(...) is run. This is also a problem with the acsac-course repo for the exercise for slide_86-89.

**Comment by rhelmot** [comment]
This is the fault of @Lukas-Dresel, who changed the behavior of `exactly_int` and didn't really check to make sure everything still worked. As you can see, [lots of things don't work](https://travis-ci.org/angr/angr/jobs/262401963).

He is currently working on a [branch](https://github.com/angr/angr/commits/fix/new_eval_api) (also still broken) to fix this as well as rewriting the state solver interface to be more intuitive.

If you want a quick fix for this, run `git revert c891a2dc4c30317912ed09890981adf632b5e64a`, though you'll want to discard this change before the next time you pull.

**Comment by rhelmot** [comment]
I believe we've resolved the issues resulting from this particular shitshow-merge.
