### ISSUE TITLE
Find more entries for one loop.

### ISSUE THREAD

**Issue by Vectorlee** [angr/angr#579]
I have load the binary for tar program, and run CFGAccurate on it, below is the link for the package. 

[http://security.ubuntu.com/ubuntu/pool/main/t/tar/tar_1.27.1-1ubuntu0.1_amd64.deb](url)

In the loop finder stage, I got the following error:
`Bad loop: more than one entry point (<BlockNode at 0x404c28 (size 12)>, <BlockNode at 0x404c55 (size 18)>)`

I used IDA to check the binary, the loop is a very normal loop, with only one entry point. This problem occurs several times in this tar program. There might be a bug in the loopfinder.py

**Comment by ltfish** [comment]
Try passing in `normalize=True` to LoopFinder.

**Comment by Vectorlee** [comment]
setting `normalize=True` do solve some cases, but still there are many cases where the loop clearly only has one entry point, but the code still complains.

Besides, if I run `CFGFast()` and then run `LoopFinder()`, almost all the bad loops (except one) reported by `CFGAccurate()` are disappeared. I guess it might be that `CFGAccurate()` over estimate the control flow transfer edges, bring extra edges that cause multiple entries for one loop.

**Comment by Vectorlee** [comment]
The angr version I am running is 6.7.7.31.
There are some other bugs when running `CFGAccurate` on this tar program (like `angr.call_stack | Returning to an unexpected address 0x2`), you guys might be interested.

**Comment by ltfish** [comment]
>  I guess it might be that CFGAccurate() over estimate the control flow transfer edges, bring extra edges that cause multiple entries for one loop.

This is possible.

**Comment by ltfish** [comment]
Thanks for reporting. I will take a look later.
