### ISSUE TITLE
SimProcedures do not return correctly if invoked with a jump instruction

### ISSUE THREAD

**Issue by jakespringer** [angr/angr#581]
If a SimProcedure is invoked with a jump instruction (for example, as a result of a tail call optimization), for example:
```asm
jmpq   489820 <__libc_realloc>
```
the branch immediately deadends after running the SimProcedure instead of correctly continuing the program at the return address on the stack frame when the jump was invoked.

For reference (messages from @fish on the slack group):
> fish [1:38 PM] 
> @jake: it's very likely to be a bug. Can you please open an issue on GitHub?
>
> [1:39] 
> @jake: the solution is to fix the code in `SimProcedure.ret()` to manually load the return address from stack/the lr register instead of pre-calculating them at the call site (in this case, the jump site)
>
> [1:39] 
> I'm not aware of any easy workaround though, sorry :disappointed:

**Comment by rhelmot** [comment]
Can you upload a binary that triggers this issue?

**Comment by schieb** [comment]
I am also interested in an example binary. I was not able to reproduce this using a simple tail call example. If you cannot provide a binary, please give the compiler version and flags used.
