### ISSUE TITLE
ImportError: No module named procedures.stubs.UserHook

### ISSUE THREAD

**Issue by ench4nt3r** [angr/angr#582]
Hi, when I use the command **from angr.procedures.stubs.UserHook import UserHook** to import UserHook, an ImportError exception is thrown.

angr is installed by pip, its version is 6.7.7.31.

How should i fix it? thank.

**Comment by rhelmot** [comment]
The code you're trying to run targets angr 7, which is only available on github. To fix it, you can either install angr from github or adapt your script to work with the old version. If that line is from our docs, you can check out an old revision of the docs from before the refactor began, probably from early June would be a safe bet.

**Comment by ench4nt3r** [comment]
thank you for your replay.
