### ISSUE TITLE
bug found in CFGFast

### ISSUE THREAD

**Issue by benquike** [angr/angr#587]
Summary:

`get_all_predecessors` returns the wrong set of `CFGNode`s.

Running the following code
```
import angr

def main():
    p = angr.Project("TEST_00004")
    cfg = p.analyses.CFG(fail_fast=True)
    nodes = cfg.get_all_nodes(0x8048262)
    n = nodes[0]

    print cfg.get_all_predecessors(n)

if __name__ == "__main__":
    main()
```

We get the folllowing output:
```
[<CFGNode main+0x206 0x80482a6[16]>, <CFGNode main+0x1d1 0x8048271[5]>, <CFGNode main+0x21d 0x80482bd[19]>, <CFGNode _terminate 0xa000008[0]>, <CFGNode main+0x211 0x80482b1[5]>, <CFGNode main+0x1d6 0x8048276[16]>, <CFGNode _terminate 0x80482e0[12]>, <CFGNode _start+0xa 0x80482da[6]>]
```

The program and CFG are attached as follows
[TEST_00004.zip](https://github.com/angr/angr/files/1237127/TEST_00004.zip)

The CFG of the program is as follows:
The **expected** predecessors are marked as purple, but the **returned** ones are marked as yellow
![test_00004_1](https://user-images.githubusercontent.com/797426/29499488-dba8be7c-85e0-11e7-89ce-5a858ebbe702.png)

**Comment by rhelmot** [comment]
I can't reproduce this using the version on github:

```
In [2]: p = angr.Project('TEST_00004')

In [3]: cfg = p.analyses.CFGFast()

In [4]: cfg.nodes()
Out[4]: 
[<CFGNode _crcx+0x11 0x80483ea[31]>,
 <CFGNode allocate+0x16 0x804836a[4]>,
 <CFGNode fdwait 0xa000004[0]>,
 <CFGNode setjmp 0x804839c[27]>,
 <CFGNode main+0x1d1 0x8048271[5]>,
 <CFGNode main+0x52 0x80480f2[17]>,
 <CFGNode main+0xd6 0x8048176[16]>,
 <CFGNode main+0x135 0x80481d5[5]>,
 <CFGNode main+0x17e 0x804821e[16]>,
 <CFGNode main+0x63 0x8048103[5]>,
 <CFGNode _terminate 0xa000001[0]>,
 <CFGNode main+0x206 0x80482a6[16]>,
 <CFGNode _crcx_docrc 0x8048409[18]>,
 <CFGNode random 0x8048382[22]>,
 <CFGNode allocate 0xa000005[0]>,
 <CFGNode _start 0x80482d0[5]>,
 <CFGNode main+0xc6 0x8048166[16]>,
 <CFGNode main+0x21d 0x80482bd[19]>,
 <CFGNode _start+0xa 0x80482da[6]>,
 <CFGNode deallocate 0xa000006[0]>,
 <CFGNode deallocate 0x804836e[17]>,
 <CFGNode _crcx_docrc+0x12 0x804841b[8]>,
 <CFGNode main+0x79 0x8048119[5]>,
 <CFGNode _terminate 0x80482e0[12]>,
...
```

**Comment by benquike** [comment]
The issue is that the predecessors of `0x8048262` are wrong

**Comment by rhelmot** [comment]
Agh. I'm sorry.

So there's definitely some miscommunication, and possibly some misdocumentation that I'm going to have to defer to @ltfish about, but here are my observations:

- Your sample output is a list, but `get_all_predecessors` returns a dict, and [has not been modified for the last year](https://github.com/angr/angr/blame/master/angr/analyses/cfg/cfg_base.py#L270)
- `get_all_predecessors` is actually a very thin wrapper over [networkx.dfs_predecessors](https://github.com/networkx/networkx/blob/9f227e4e111c648c77efcd4de18fef662184adc4/networkx/algorithms/traversal/depth_first_search.py#L133), which performs a depth first search _forward_ from the given node, and returns a dictionary mapping each node found in the search to its predecessor
- If you want to just find the normal, immediate predecessors for the given node, you should use `cfg.get_predecessors(node)`, or just `node.predecessors`. If you want to find all the nodes that precede the given node, it does appear that there's no current method to do that on cfg.
- The reason we have `get_all_nodes` vs `get_any_node` in a CFG is to handle context sensitivity, a concept that only makes sense in the context of a cfgaccurate.

I highly suspect that get_all_predecessors is a misnamed/misdocumented function. @ltfish? I highly doubt that anyone is using these functions considering how strange they appear to be, and I would support changing them to actually return full lists of successors/predecessors.

**Comment by benquike** [comment]
OK, thanks for the clarification.

**Comment by benquike** [comment]
@rhelmot @ltfish  

Just one more question.

In the program I uploaded above, there is a function call in the first block.
I want to follow the `predecessor` and `successor` chain of a node to collect
all the predecessors and successors of a node in the CFG. 
 
But the issue I run into is that, in case there is a function call, all the nodes after
the function call are not included in the `successors` field of a node, and similarly
the nodes before the function call are included in `predecessors` field.

Is there a way to overcome this issue?

**Comment by rhelmot** [comment]
The CFG that angr produces is an _interprocedural_ CFG, which tracks control flow across an entire program, not just in a single function. As a result, the successor of a basic block ending in a call is the target of the call.

However! angr also generates what are called "fake return" successors, which go from a call to its return target. These are hidden from you by default, but you can see them with `cfg.get_successors(node, excluding_fakeret=False)`. Alternately, the individual function objects in `cfg.functions` have a `.graph` property that should be a networkx graph describing the intraprocedural (the opposite of interprocedural) CFG.

**Comment by rhelmot** [comment]
Forgot to mention - you can distinguish between the fakeret and the normal successors with `cfg.get_successors_and_jumpkind`.

**Comment by benquike** [comment]
`CFG.graph.cfg.graph.predecessors` returns both.
Thanks

**Comment by benquike** [comment]
The following code can be used to calculate the predecessors and successors

```
def get_all_predecessors(cfg, node):
	ret = set()

	def __predecessors(res, cfg, node):
		ps = cfg.graph.predecessors(node)

		for p in ps:
			if p in ret:
				continue

			res.add(p)
			__predecessors(res, cfg, p)

	__predecessors(ret, cfg, node)

	return ret

def get_all_successors(cfg, node):
	ret = set()

	def __successors(res, cfg, node):
		ss = cfg.graph.successors(node)
		for s in ss:
			if s in res:
				continue

			res.add(s)
			__successors(res, cfg, s)

	__successors(ret, cfg, node)

	return ret
```
