### ISSUE TITLE
A question on class CallStack

### ISSUE THREAD

**Issue by madshy** [angr/angr#60]
Hi, I'm a newcomer of angr.
Just now, I tried to look into path.callstack and printed it.
However, the result of it(type pathgroup.active[0].callstack directly) looked like the following.
**_CallStack (depth 3) [ 0x400580 (0x4005d0), 0x40079b (0x1000070), 0x4006c6 (0x40082d) ]_**
And the function '__repr__' in CallStack is 
**_return "\<CallStack (depth %d)\>" % len(self._callstack)_**
On the other hand,the result of 'print (pathgroup.active[0[.callstack' is same with 'pathgroup.active[0].callstack'.
And the function '__str__' in CallStack is 
**_return "Backtrace:\n%s" % "\n".join(str(f) for f in self)_**
Hoping and Thanks for solving.

**Comment by madshy** [comment]
I'm sorry for not 'str' but '\_\_str\_\_'.
The same to 'repr'.

**Comment by rhelmot** [comment]
You have an older version of angr installed than the current `master` branch. The printing behavior of `CallStack` was changed very recently from what you see printed to what you see in the code.

**Comment by rhelmot** [comment]
Oh, jeez, I forgot we haven't done a release in a while. The version on pip is a little out of date, and what you're seeing is correct. We've been going through a lot of rapid development on angr lately, and it's not clear where we should do releases. @zardus can tell you when pip will catch up to master :+)

**Comment by ltfish** [comment]
I'm expecting to merge the `wip/model` branch to master this Friday, so a release after that should make sense?

**Comment by madshy** [comment]
So sorry for close
