### ISSUE TITLE
references to non-existent "setup.sh" in README

### ISSUE THREAD

**Issue by jpendlet** [angr/angr#61]
Its not clear if there is actually a script or this should be:

    -./setup.sh
    +python setup.py install
     ```

     This clones all of the repositories and installs them in editable mode.
    -`setup.sh` can even create a PyPy virtualenv for you, resulting in significantly faster performance and lower memory usage.
    +`setup.py` can even create a PyPy virtualenv for you, resulting in significantly faster performance and lower memory usage.

**Comment by zardus** [comment]
That section is talking about `setup.sh` in the `angr-dev` repo (https://github.com/angr/angr-dev), hence the `git clone https://github.com/angr/angr-dev` in the lines above that :-)
