### ISSUE TITLE
fgets not setting file.pos correctly

### ISSUE THREAD

**Issue by themaks** [angr/angr#615]
Hi,
It seems that the `fgets` simprocedure do not generates correct constraints concerning the `pos` field of `stdin` `SimFile`.

This is my test C file : 
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char** argv){
  char buff[16];
  memset(buff, 0, sizeof(buff));
  printf("Test fgets\n");
  fgets(buff, 16, stdin);
  for (int i=0; i<16; i++)
    printf("%02X ", buff[i]);
  printf("\n");
  return 0;
}
```

And this is my angr python code : 
```
import angr
b=angr.Project("./a.out", auto_load_libs=False)
sm=b.factory.simgr()
sm.step(until=lambda s: len(s.one_active.solver.constraints)!=0) # run until fgets simprocedure is executed and generate constraints
stdin=sm.one_active.posix.files[0]

min_pos=sm.one_active.solver.min_int(stdin.pos)
max_pos=sm.one_active.solver.max_int(stdin.pos)
print "stdin.pos is constrained to be between %d and %d"%(min_pos, max_pos)

newline_only_at_the_end=[stdin.all_bytes().get_byte(i)!='\n' for i in range(14)]+[stdin.all_bytes().get_byte(14)=='\n']
print sm.one_active.satisfiable(extra_constraints=newline_only_at_the_end)

newline_in_the_middle_not_at_the_end=[stdin.all_bytes().get_byte(i)!='\n' for i in range(0,7)+range(8,15)]+[stdin.all_bytes().get_byte(7)=='\n']
print sm.one_active.satisfiable(extra_constraints=newline_in_the_middle_not_at_the_end)

no_newline_at_all=[stdin.all_bytes().get_byte(i)!='\n' for i in range(0,15)]
print sm.one_active.satisfiable(extra_constraints=no_newline_at_all)
```
and the associated output : 
```
stdin.pos is constrained to be between 15 and 15
True
False
True
```
All three tests should give `True`as a result.

The symbolic `stdin.pos` should be able to take any of the following values : 
- 0, if `fgets` received EOF before any content
- between 1 and 14, if user entered between 0 and 13 characters + a newline
- 15, if the user entered 14 characters + a newline, or more than 15 characters

(for a reminder, this is the manpage for `fgets` : `fgets()  reads  in at most one less than size characters from stream and stores them into the buffer pointed to by s.  Reading stops after an EOF or a newline.  If a newline is read, it is stored into the buffer.  A terminating null byte ('\0') is stored after the last character in the buffer.`)

Is it normal ?
Thanks in advance

**Comment by rhelmot** [comment]
So I've spent the last half hour or so looking into this, and the result is that I have no idea what about the fgets procedure would cause this behavior. our fgets is kind of [a gigantic mess](https://github.com/angr/angr/blob/master/angr/procedures/libc/fgets.py). If you can figure out what's going on in here or rewrite it from scratch to be cleaner and work correctly in all the cases we need it to, that would be great, otherwise we're kind of stuck here.
