### ISSUE TITLE
remove angrop dependency ?

### ISSUE THREAD

**Issue by themaks** [angr/angr#621]
Hi,

I saw that [angrop](https://github.com/salls/angrop) is an implicit dependency for angr, as it is used by the Identifier analysis (cf [this](https://github.com/angr/angr/search?q=angrop&type=Code&utf8=%E2%9C%93)).
It seems that only the `angrop.rop_utils.make_symbolic_state` helper function is used (cf [this](https://github.com/salls/angrop/blob/master/angrop/rop_utils.py)) which only calls `angrop.rop_utils.make_initial_state` (another helper function).

Are you planning to add explicitly angrop to angr's dependencies, or to integrate these 2 short functions to angr/angr codebase ?

Thanks

**Comment by rhelmot** [comment]
I think these functions should be relatively easy to integrate into project.factory.blank_state as keyword options...
