### ISSUE TITLE
Issue may cause headache, networkx.DiGraph() and add_edge

### ISSUE THREAD

**Issue by AndyXan** [angr/angr#627]
Hello Guys, 

I am reporting something I stumbled upon today and before starting with the Issue: This may not concern you at all, but from my experience with angr's  CFGFast / .. from over a year ago it seemed it may be an issue. 

The problem lies within how networkx.DiGraph() handles the add_edge(node_1, node_2) method and I am trying to describe the problem as simple as possible. I first encountered the problem when loading a serialized networkx.DiGraph() from a database, the core problem is the following code:

```
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(CFGNode(fromaddr, fromsize, sit_cfg_abstraction),
                                                            CFGNode(toaddr, tosize, sit_cfg_abstraction))
```

The problem already occurs with a linear chain of blocks, lets say 3 blocks with the relationship (succ, pred) leading to a code like this:
```
n1 <--> n2 <--> n3
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(CFGNode(0x00, 4, sit_cfg_abstraction),
                                                            CFGNode(0x4, 4, sit_cfg_abstraction))

sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(CFGNode(0x04, 4, sit_cfg_abstraction),
                                                            CFGNode(0x8, 4, sit_cfg_abstraction))

```

Despite creating the CFGNode for addr 0x4 two times, leading to different id(..)'s, the creating networkx.DiGraph holds only 3 nodes, because existing nodes (by __hash__) won't be added to DiGraph.nodes. So far, this is what it's supposed to be. 

However, for further simplification, above code can be written as:

```
n1 <--> n2 <--> n3
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(n1, n2)
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(x2, n3)

with __hash__(n2) == __hash__(x2)
```

with x2 never ending in the graph.nodes dict. However, x2 makes its way to the predecessor relationships of the graph, without being in the nodes dictionary. Let's take a look into the networkx code:

```
add_edge(self, u, v, ..):
       ...
        if u not in self.succ:
            self.succ[u]= self.adjlist_dict_factory()
            self.pred[u]= self.adjlist_dict_factory()
            self.node[u] = {}
        if v not in self.succ:
            self.succ[v]= self.adjlist_dict_factory()
            self.pred[v]= self.adjlist_dict_factory()
            self.node[v] = {}
        # add the edge
        datadict=self.adj[u].get(v,self.edge_attr_dict_factory())
        datadict.update(attr_dict)
        self.succ[u][v]=datadict
        self.pred[v][u]=datadict
```

The first iteration leads to:

```
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(n1, n2)
leading to:
node = {n1, n2}
succ = {n1 -> n2, n2 -> {} }
pred = {n1 -> {}, n2 -> n1}
```

But the problem comes with the second iteration
```
sit_cfg_abstraction.function_cfg_dict[graphstartnodeaddr].add_edge(x2, n3)
leading to:
node = {n1, n2, n3}  #(if x2 not in self.succ: is false, since hash(x2) = hash(n2) and n2 is in the list) 
succ = {n1 -> n2, n2 -> n3, n3 -> {}} #self.succ[x2][n3] = .. works, since hash(x2) == hash(n2) 
pred = {n1 -> {}, n2 -> n1, n3 -> x2} #self.pred[n3][x2] = .. problem
```

And here we finally arrived at the problem. Whenever I want to get graph.predecessors(n3), i will receive x2 which is not in the graph in the first place. More problematic, altering the nodes in the graph has no effect for predecessor nodes. And by all means, there are duplicate nodes which consume memory. 

So, I can fix this on application side - and maybe you guys did it in some way, didn't check it thoroughly - but maybe this is also an unnoticed Issue for you. In my opinion, this is a general networkx problem and should be addressed there with something like:

```
if u not in self.succ:
            self.succ[u]= self.adjlist_dict_factory()
            self.pred[u]= self.adjlist_dict_factory()
            self.node[u] = {}
else:
            u = self.node[u]
```

Tell me when you stopped reading ;)

**Comment by axt** [comment]
Actually I reported this behavior once (if I understand the problem correctly):
https://github.com/networkx/networkx/issues/2282

They agreed it's not an issue.

**Comment by AndyXan** [comment]
You're right about this - the problem is absolutely related to that and hagberg brought it to the point:

NetworkX assumes that objects compare equal are the same object.

So as I said before, I can fix this simply in my applications - the question is, if angr-core cfgfast, cfgbase, cfgaccurate, ... have assurance that they never create the same cfgnode (equal by hash, but different by id) multiple times and throwing them into add_edge. As far as I remember, in my early days with angr during masters degree, I stopped using predecessors because of problems i didn't understand back then.

**Comment by ltfish** [comment]
> the question is, if angr-core cfgfast, cfgbase, cfgaccurate, ... have assurance that they never create the same cfgnode (equal by hash, but different by id) multiple times and throwing them into add_edge.

I'm trying my best to reuse existing CFGNode instances if one has been created, so yes, we only create a node once for each unique program location.

I also noticed this behavior before, and I chose to live with it.

**Comment by AndyXan** [comment]
Same here. Just something to keep in mind, during all kinds of operations with CFGNodes(..).

Thanks for reply /close

**Comment by axt** [comment]
Just a note: In the DDG analysis (which is btw deprecated) this constraint doesn't hold.

**Comment by ltfish** [comment]
@axt It will be addressed.
