### ISSUE TITLE
Extract non-posix data storage from posix plugin

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#634]
This supersedes https://github.com/angr/simuvex/issues/71.

- Add a `files` plugin to handle files and other I/O streams
- Add a `heap` plugin to handle heap layout and allocation (bonus: we can have multiple implementations of the plugin that implement multiple heap allocation/freeing strategies instead of just our one that never frees anything)
- Make posix contain the actual file descriptors as SimFileDescriptors, which point to the appropriate SimFiles
- Add a `win32` or whatever plugin that handles the windows equivalents of all this nonsense 
- Add another implementation of the `libc` plugin for the msvcrt

An important question to answer is whether we want to have posix and win32 be plugins that are named as such or if they should both be found as `state.os_env` or something like that. I'm in favor of having them named separately in order to encourage the "visible name" of a plugin to be a contract about its interface.

**Comment by zardus** [comment]
If we're pulling files and heap and such out, I agree about having them named separately. I don't see them sharing an enormous amount of functionality at that point.
