### ISSUE TITLE
printf issue

### ISSUE THREAD

**Issue by bannsec** [angr/angr#636]
There's an issue where the interpretation of scanf seems to be right, and wrong, both at the same time.

Here's the C code:
```c
#include <stdio.h>
#include <stdlib.h>

int main() {
    int i;

    scanf("%d",&i);
    printf("Your input: %d\n", i);
    if (i == 1337)
        printf("Win\n");
}
```

Here's a test run:
```python
In [1]: import angr
WARNING | 2017-09-08 04:30:55,180 | angr.state_plugins.unicorn_engine | failed loading "angr_native.so", unicorn support disabled (/home/angr/angr-dev/angr/angr/lib/angr_native.so: undefined symbol: simunicorn_executed_pages: /home/angr/angr-dev/angr/angr/lib/angr_native.so: undefined symbol: simunicorn_executed_pages)

In [2]: proj = angr.Project("./a.out")

In [3]: sim = proj.factory.simgr()

In [4]: sim.explore()
WARNING | 2017-09-08 04:31:21,377 | angr.state_plugins.symbolic_memory | Concretizing symbolic length. Much sad; think about implementing.
Out[4]: <SimulationManager with 2 deadended>

In [5]: sim.deadended[1].posix.dumps(1)
Out[5]: 'Your input: -147275146\nWin\n'

In [6]: sim.deadended[1].posix.dumps(0)
Out[6]: '+0000001337\n'
```

This issue, angr correctly identifies that a valid input could be "+0000001337", but when attempting to re-create the stdout, it gives a negative number.

**Comment by rhelmot** [comment]
So this is actually a printf issue, not a scanf one. our printf currently concertizes literally everything that goes through it, except it doesn't actually add a constraint that the containerization must be valid.

So two issues:

- printf doesn't constraint its concretizations
- printf concretizes everything

2 is a lot harder than 1 to deal with.
