### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by zardus** [angr/angr#638]
Eventually, we'd like to have Python 3 compatibility. For this to happen, we need the following modules to be compatible:

- [x] angr
- [x] CLE
- [x] pyvex
- [x] archinfo
- [x] claripy
- [x] ana
- [x] mulpyplexer
- [x] monkeyhex

**Comment by ltfish** [comment]
Does this mean we need to add Python 3 compatibility to all of our dependency packages, too?

**Comment by zardus** [comment]
Yeah, stuff like ana, mulpyplexer, monkeyhex, and so on.

**Comment by rhelmot** [comment]
As far as I can tell, the only dependency we have (besides our in-house deps) that isn't already py3k-ready is capstone...

**Comment by ltfish** [comment]
PySide (not PySide 2) is also not Python3-ready, and [it is a wontfix](https://github.com/pyside/PySide/issues/132)... angr-management will have to switch to PySide2 + Qt5.

**Comment by zardus** [comment]
This also doesn't have to be all-or-nothing. I think we should maintain python2 compatibility, of course, so for now, we can probably just ignore that problem for angr-management.

**Comment by rhelmot** [comment]
Today, I did archinfo, pyvex, and claripy. The claripy tests pass now. FYI, claripy was MILES and miles away from working, that PR did not actually make things work in python 3.

**Comment by ltfish** [comment]
You are a hero!

**Comment by emc2314** [comment]
dpkt-fix cannot be installed on python3, but dpkt could. Installing angr is stuck at the dpkt-fix...

**Comment by rhelmot** [comment]
as it turns out, dpkt-fix is deprecated in favor of the normal dpkt package, last I checked!

**Comment by agroce** [comment]
Any thoughts on an ETA for angr for Python 3?  It'd be great for simplifying DeepState, since Manticore moved to Python 3 (and doesn't work on 2.7 anymore, unless you use an old build)

**Comment by rhelmot** [comment]
Whenever we can. When we decide it's time we're going to pause all other development until it's migrated. This means we need to find a time where the entire team is available for this push so it can get done quickly. I agree it needs to happen soon.

**Comment by agroce** [comment]
You're looking to be 3 and 2.7 compatible, or move to 3?

**Comment by rhelmot** [comment]
Just 3. There's too much stuff in angr to try to keep it straddling the boundary. It would be way too much for our (effectively) 2 person team.

**Comment by Mic92** [comment]
In our angr-based project we use type annotation + mypy to make the python3 transition in future when angr is ready. You might want to do the same (I find it easier this way).

**Comment by ltfish** [comment]
Another big reason for migrating to Python 3 is that PySide2 does not support Python 2.7 + Windows. We will make this migration happen soon.

**Comment by ltfish** [comment]
See #1209. I'm closing this issue.

**Comment by Mic92** [comment]
Cool to have this!

**Comment by Mic92** [comment]
Does this mean that master is now python3 ready mostly?
