### ISSUE TITLE
angr does not decode or disassemble ARM Cortex instructions

### ISSUE THREAD

**Issue by ltfish** [angr/angr#649]
This is ARM Cortex: https://en.wikipedia.org/wiki/ARM_Cortex-M

The instruction that is not supported by angr: https://github.com/aquynh/capstone/issues/596

For disassembly, it looks like we need to initialize a Capstone instance with a special flag for ARM Cortex instructions. I'm not sure whether VEX handles Cortex instructions or not.

Thanks @tyb0807 for reporting this issue. Personally I have no idea what Cortex is...

**Comment by tyb0807** [comment]
Well, I digged deeper into this and found out that VEX can handle the instruction `mrs`, but not the register used in that specific instruction `primask`. In summary, `mrs` as well as `msr` only supports `APSR` register (flag register), while in reality, these instructions might have other operands as `primask`, `control` or `basepri` (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489e/Cihibbbh.html).

The same goes for `svc` instruction (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489e/Cihibbbh.html): only the service number 0 (syscall) is handled by VEX.

I have sent a message in the VEX mailing list to ask about this, but haven't got the answer yet. Anw, I think it would be nice to have these instructions supported in angr.

**Comment by subwire** [comment]
This is solved in #1234
