### ISSUE TITLE
Oppologist and Director technique continues indefinitely

### ISSUE THREAD

**Issue by pragyansmita** [angr/angr#651]
We provide the target address and a series of addresses "the slice" that determines the path to the target address. We find that the ongoing search does not meet the exact slice, it continues indefinitely. We are using the oppologist and director technique. 

- Is there a configuration or some other option such as timeout that will allow this to conclude in a reasonable amount of time?

- Shouldn't it exhaust all possible paths through the program and make a conclusion that it is impossible?

**Comment by zardus** [comment]
I don't have much time to respond, but I'll make a start of it:

The director doesn't guarantee any sort of path following -- it just tries to push execution toward a given goal. Likewise, the Oppologist *really* doesn't reason about where it should go -- it simply catches errors from our VEX SimEngine and runs our unicorn SimEngine instead. Neither of these techniques will stick to a slice...

Regarding your second point, exhausting all possible paths through the program is not something that current techniques can do. As an example, consider the following program: `while (getchar()) { }`. This program has infinitely many paths, unless you do some constraining to limit them.

We don't have built-in timeout support, but you can probably use something like https://pypi.python.org/pypi/timeout-decorator wrap your exploration in a timeout.

**Comment by ltfish** [comment]
If you have a slice, you should consider building an `AnnotatedCFG` and then use `Slicecutor` to follow the slice during symbolic execution.

**Comment by ltfish** [comment]
A side note to myself: `AnnotatedCFG` and `Slicecutor` should all be refactored and documented.

**Comment by zardus** [comment]
As an exploration technique! Then we can finally deprecate surveyors.

On Sep 14, 2017 10:17 PM, "Fish" <notifications@github.com> wrote:

A side note to myself: AnnotatedCFG and Slicecutor should all be refactored
and documented.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/angr/angr/issues/651#issuecomment-329683888>, or mute
the thread
