### ISSUE TITLE
ARM jump sites missing

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#655]
Hello,

![js_missing](https://user-images.githubusercontent.com/23738463/30420477-f4230df6-9939-11e7-91a8-da6a0e8dc752.png)

As you can see, a `ble` with **only one** out edge.... It is not a bug in angr-utils, since I've printed out all CFG edges and it's indeed missing...

**Comment by ltfish** [comment]
Usually I blame VEX...

Joking aside, can you please try turning off the optimization?

**Comment by tyb0807** [comment]
Oh, I tried both with and without the optimization...

**Comment by ltfish** [comment]
Can you please post the bytes of those two blocks here? Or put the binary here so we can debug it later. Thanks.

**Comment by tyb0807** [comment]
Wait, I found the bug. I submitted a PR for this but before the refactor and you didn't merge in...

**Comment by ltfish** [comment]
OH

Well, time to rebase...

**Comment by tyb0807** [comment]
Should I send you a PR?

**Comment by ltfish** [comment]
Of course.
