### ISSUE TITLE
Detecting loop when the loop has a function call embedded in it fails

### ISSUE THREAD

**Issue by sjcomeau43543** [angr/angr#658]
I am trying to analyze a single function at a time while ignoring any function calls.  In an attempt to no-op the function calls I just hooked all the callout sites of the current functions I am analyzing.

`proj.hook(callout_function.addr, length=callout_function.length)`

However, whenever I come across a loop I'm trying to detect that I'm in a loop using the path 'detect_loop' method.  This method doesn't work when the loop calls a function, something similar is below.

`	for(in = 0; in < 5; in++){
		i = i + in;
		seperate_check(i);
	}
`

I can't detect this loop because angr is still calling seperate check even though I just want to skip seperate check altogether. Please let me know how I can effectively no-op this function call.

**Comment by ltfish** [comment]
`detect_loop()` is removed in the new version of angr (even `Path` does not exist anymore). You can use the old implementation as a reference and implement your own loop detector on a path. It should be an easy job.

**Comment by sjcomeau43543** [comment]
is there a better way to effectively no-op the function call?

**Comment by ltfish** [comment]
I would just hook the call instructions instead. Is it what you are doing, too?

**Comment by schieb** [comment]
I would nop out the individual bytes of the call instructions. You can use a hook of size 5 (length of call instruction on x86).

Keep in mind that if the calling convention is callee-cleanup you will need to adjust the stack appropriately in your hook.

**Comment by sjcomeau43543** [comment]
I am trying to write a script that can work for any architecture so I can't do any architecture specific modifications.  

If i made my cfg have context sensitivity level of 0 ('callee-only') would that do what I am looking for?

**Comment by ltfish** [comment]
> I am trying to write a script that can work for any architecture so I can't do any architecture specific modifications.

That is not as easy as you might think. What is your end goal? Detecting loops in a static CFG, or detecting loops in a dynamic path?

**Comment by rhelmot** [comment]
The actual answer to your original question is the `CALLLESS` state option. See https://docs.angr.io/docs/appendices/options.html

**Comment by sjcomeau43543** [comment]
thank you @rhelmot that is the solution I was looking for.  This link led me to find AST_DEPS which interests me as well, is there anywhere I can find more documentation on this?

**Comment by ltfish** [comment]
I think your best bet is reading the source code. You can grep for AST_DEPS in the angr repo.

**Comment by rhelmot** [comment]
...for a real answer, `AST_DEPS` will cause reads from memory/registers/files to return not a bitvector, but a SimActionObject, which is a proxy object for a claripy AST that will additionally do things like dependency tracking. It should be used in conjunction with the `AUTO_REFS` state option (not sure what this one does from a cursory grep but they're always used together).

I don't know the specifics for how SimActionObjects actually work or what information they give you :( they were an interface designed by yan and fish and I have been blissfully ignorant of their specifics.
