### ISSUE TITLE
CALLLESS simuvex state option making up successors

### ISSUE THREAD

**Issue by sjcomeau43543** [angr/angr#663]
The CALLLESS state option is set for the call_state at the first address of a function.  During execution I am looking at the path successors in order to determine if the path is in a loop or not (checking if it was already in the address trace).  Since the CALLLESS option overwrites all function calls, the path successors does not include the function addr.  However, this is an issue when it comes to a tail call at the end of a function.  Looking at the path successors it states that the next possible address (immediately following the function call) is a successor even though it isn't.  The CFG however does the analysis correctly and lists the function call as the only successor.

An example is for coreutils/true.c version 8.26 function: usage
In the CFG you can see in the bottom right corner the end of usage at address 0x4016fa.  There is no successor other than the function call (overwritten using CALLLESS during execution).  However, during analysis angr thinks that 0x401701 is a successor of 0x4016fa.

![cfg](https://user-images.githubusercontent.com/25495067/30704807-d5179296-9ec1-11e7-8029-36be03d21986.png)

**Comment by rhelmot** [comment]
When you're using CALLLESS, you're making a fundamental change to how angr interprets the program bytecode. The only thing it does is to trigger a tiny bit of logic to pop the return address and unconstrain the return value every time it sees a call instruction. This _very_ heavily relies on the linkage between the call instruction and an actual function call. Examples of where this linkage breaks, and this option will not actually just skip function calls, include using `call $+5` as `push eip` and tail calls.

The CFG uses its own approach to deal with these. I'm not the CFG expert, but my understanding is that it does the following:

- does NOT use `CALLLESS`, but instead uses `DO_RET_EMULATION`, which adds the fake return in addition to each call
- requires that an analysis of the called function complete and determine that it is possible to return from the called function
- detect the `push eip` idiom manually

**Comment by ltfish** [comment]
Which CFG are you talking about? `CFGFast` or `CFGAccurate`?

`CFGAccurate` may actually (and unexpectedly) respect the `CALLLESS` option. On the contrary, `CFGFast` does not take any state option.

**Comment by sjcomeau43543** [comment]
Its a CFGAccurate.  I was submitting this as an error as the CFG knows the address is not a successor however the path does think it is a successor.  The CFG is right, the path stepping is wrong

**Comment by ltfish** [comment]
> the path stepping is wrong

This is expected, since there is no way for a path to know whether a call is a tail call or not. As @rhelmot said, If you specify `CALLLESS`, it will jump all `call` instructions, regardless of the real intent of that call instruction. CFGAccurate knows it slightly better because it has global information through CFG recovery and some graph analysis.

A workaround is to detect such cases and disable `CALLLESS` option before reaching the basic block where that instruction 0x4016fa belongs.
