### ISSUE TITLE
Transition to networkx 2.0

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#665]
Main difference: some functions return iterators instead of lists, presumably to help ease the impending python 3 deadline.

**Comment by ltfish** [comment]
Here is the link to the migration document: https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

It seems that I'll own a lot of lines after migrating to networkx 2...

**Comment by ltfish** [comment]
Update: @tyb0807 will work on this issue.
