### ISSUE TITLE
maybe something wrong with libc/fgetc.py, libc/getchar.py and glibc/_IO_getc.py

### ISSUE THREAD

**Issue by joyceqi** [angr/angr#684]
In libc/fgetc.py and libc/getchar.py:
![fgetc](https://user-images.githubusercontent.com/6076137/30999641-f7ebf11a-a49b-11e7-9120-484aaaef810f.png)
![getchar](https://user-images.githubusercontent.com/6076137/30999645-fb36dad8-a49b-11e7-8b77-6f5034209893.png)
Both the argument to _IO_getc() is `file descriptor` (a small int).

But in glibc/_IO_getc.py:
![_io_getc](https://user-images.githubusercontent.com/6076137/30999757-921dc2fe-a49c-11e7-9471-efc09f795338.png)
The argument `f_p` (which is already `fd`) will be recognized as FILE struct, and call fileno(f_p) to get the corresponding `fd` again.

**Comment by rhelmot** [comment]
Thanks for the heads up! This has been fixed.
