### ISSUE TITLE
BlockNode can be missing in Function block list

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#685]
Hello,

Apparently, in some code (code that has exceptions, or code that initializes hardware for example), we can encounter this kind of function call:
```
00008008 <ResetISR>:
    8008:	4b08      	ldr	r3, [pc, #32]	; (802c <ResetISR+0x24>)
    800a:	4809      	ldr	r0, [pc, #36]	; (8030 <ResetISR+0x28>)
    800c:	4283      	cmp	r3, r0
    800e:	d20a      	bcs.n	8026 <ResetISR+0x1e>
    8010:	43da      	mvns	r2, r3
    8012:	2100      	movs	r1, #0
    8014:	4402      	add	r2, r0
    8016:	f022 0203 	bic.w	r2, r2, #3
    801a:	3204      	adds	r2, #4
    801c:	441a      	add	r2, r3
    801e:	f843 1b04 	str.w	r1, [r3], #4
    8022:	4293      	cmp	r3, r2
    8024:	d1fb      	bne.n	801e <ResetISR+0x16>
    8026:	f000 b83b 	b.w	80a0 <Main>
```
Function `Main` is called in `ResetISR` using a `b` instruction instead of `bl`. Of course, VEX does not detect the call and `CFGAccurate` does not either.

 The problem might be just that there will not be any `Function` object for `Main`, and all basic blocks of `Main` will be in `Function` of `ResetISR`. But it can also be that a `Function` object does not contain any blocks. Here's an example:
```
0000a220 <I2CMasterControl>:
    a220:	6041      	str	r1, [r0, #4]
    a222:	4770      	bx	lr
```
This function only has one single block. It is called from different places:
- Here with a `b`, the function call is not detected
```
0000969c <OSRAMWriteFirst>:
    969c:	b538      	push	{r3, r4, r5, lr}
    969e:	4605      	mov	r5, r0
    96a0:	4c07      	ldr	r4, [pc, #28]	; (96c0 <OSRAMWriteFirst+0x24>)
    96a2:	2200      	movs	r2, #0
    96a4:	4620      	mov	r0, r4
    96a6:	213d      	movs	r1, #61	; 0x3d
    96a8:	f000 fdae 	bl	a208 <I2CMasterSlaveAddrSet>
    96ac:	4629      	mov	r1, r5
    96ae:	4620      	mov	r0, r4
    96b0:	f000 fdc4 	bl	a23c <I2CMasterDataPut>
    96b4:	4620      	mov	r0, r4
    96b6:	e8bd 4038 	ldmia.w	sp!, {r3, r4, r5, lr}
    96ba:	2103      	movs	r1, #3
    96bc:	f000 bdb0 	b.w	a220 <I2CMasterControl>
```
- Or here with a `bl`, but since the `BlockNode` is already in the `OSRAMWriteFirst` `Function` object, the `Function` `I2CMasterControl` is created but has no block.
```
    96ec:	2101      	movs	r1, #1
    96ee:	4620      	mov	r0, r4
    96f0:	f000 fd96 	bl	a220 <I2CMasterControl>
```

So, I don't know what would be the best way to fix this. Adding more logic to reason about jumpkind? Or we can just add more test in `Function` class, like <a href="https://github.com/angr/angr/blob/b46e270c74a7f510dc04b1fae90dd8f85956a321/angr/knowledge_plugins/functions/function.py#L601 ">here</a>. 

I guess this is a @ltfish issue. Please let me know what you think

**Comment by ltfish** [comment]
Waking up during a road trip with this kind of issues is no fun... The way to handle it is to prioritize `bl` to `b`: Whenever we bl to a previously b'ed block, we will make sure that block and all of its successors are removed first before resuming the CFG recovery.

I was aware of this issue, and I was thinking that it is usually fine to miss a function or two...

I will fix this one.

**Comment by tyb0807** [comment]
But that will not fix the first example: `Main` is called __only__ in `ResetISR`

**Comment by tyb0807** [comment]
Here is the binary so that you can reproduce this.
[break.zip](https://github.com/angr/angr/files/1366341/break.zip)

**Comment by ltfish** [comment]
PR #706 fixes this issue when the binary has symbols. It is a lot harder when the binary is stripped.

Also CFGFast shits the bed on this binary, too. I will fix them later.

**Comment by tyb0807** [comment]
What do you mean by `CFGFast shits the bed on this binary`? It doesn't recognize all functions? I know that it's impossible for `CFGAccurate` to recover the complete CFG because of exception handlers not being detected by symbolic execution though

**Comment by ltfish** [comment]
CFGFast fails to correctly recognize all blocks of the Main function, too.

Additionally, CFGFast is definitely not fast on this binary.

**Comment by tyb0807** [comment]
So are you gonna fix CfgFast? Or I open a new issue for it?

**Comment by ltfish** [comment]
Please open a new issue, and I'll explain exactly what the problem is with CFGFast in that issue.
