### ISSUE TITLE
about veritesting exploration tech

### ISSUE THREAD

**Issue by humeafo** [angr/angr#687]
I read the original veritesting paper and angr implementation and found some (maybe bugs) ?:

1.the veritesting tech ignored some stashes, only the following stashes merged into main simgr:
https://github.com/angr/angr/blob/master/angr/exploration_techniques/veritesting.py#L28
obviously the errored stash is discarded, this may cause some error state not detected by those checkers relying on error stash, maybe deadended and some others should be kept too and let higher level code to drop it or generate testcase?

2.the original paper do veritesting only at symbolic branch starting point, but from the exploration technique code, it seems that veritesting analysis is on at every state-step this may slow the SE noticeabley, maybe it's better to do at sym forking point by hooking 'engine_process'?

3. it seems https://github.com/angr/angr/blob/master/angr/analyses/veritesting.py#L196 is not necessary because https://github.com/angr/angr/blob/master/angr/analyses/veritesting.py#L229 has already done this?

**Comment by ltfish** [comment]
> 1. ... this may cause some error state not detected by those checkers relying on error stash ...

You are right. I think all errored states should be returned, instead of being silently dropped.

> 2. ... the original paper do veritesting only at symbolic branch starting point, but from the exploration technique code, it seems that veritesting analysis is on at every state-step this may slow the SE noticeabley ...

It was a choice I had to make when implementing Veritesting, and for some unknown reason I believed that I need to perform Veritesting at every single step (otherwise it was losing some easy cases for merging). I'm not sure this was the right choice, but I'm definitely open to better ideas/design choices.

> 3. ... because line 229 has already done this?

Line 229 is redundant. It should be removed.

A bigger problem is that the Veritesting implementation generates a CFGAccurate instance way more often than what is absolutely necessary. I have to admit that as for now, our Veritesting implementation hasn't been profiled or fine-tuned for performance. It might help significantly if someone can profile and fix some underlying issues that (negatively) impacts the speed.

**Comment by zardus** [comment]
I would also add that, on a design level, we should try to integrate veritesting better into the whole exploration technique paradigm. For example, there is absolutely no reason to use two different SimulationMangers -- Veritesting should just work on the primary one and step the states in there directly. That way, we can easily chain it with the Explorer (making state checking during execution much easier) and so on.

**Comment by ltfish** [comment]
> That way, we can easily chain it with the Explorer ...

No one really knows what will happen if the Explorer hooks are called during static symbolic execution. Are you sure that's a good idea?

**Comment by zardus** [comment]
As I see it, veritesting consists of:

1. Do the CFG analysis to find the merge boundary.
2. Step all existing steps up to the boundary.
3. Merge the states that can be merged.

I agree that hooking that first step will end in tears, but the states in step 2 are completely normal states, and we can hook those however we want.

**Comment by ltfish** [comment]
>  but the states in step 2 are completely normal states

`Explorer` might cause us to step existing states beyond the desired boundary.

**Comment by zardus** [comment]
We'd just have to pass the correct stop points when the veritesting technique's `step()` calls `simgr.step()`. But we already do this in the analysis (for the same reason), so I think it'll be basically the same thing.

**Comment by humeafo** [comment]
'A bigger problem is that the Veritesting implementation generates a CFGAccurate instance way more often than what is absolutely necessary. '
I think this is caused by the decision to perform Veritesting at every single step, if do veritesting only at fork point, then this may not be a problem anymore.
I'm not aware of the reason(maybe there is some angr specifics here) to perform Veritesting at every single state-step, in theory from the paper, indeed we only need to do veritesting when symbolic fork happens.

**Comment by humeafo** [comment]
I just did a tiny experiment on my hackish veritesting version( mergepoint) and angr's implementation:
Target is CGC CROMU_00065, my naive version just do veritesting at forking point and used the same veritesting analysis module. all the experiments is under pypy using dfs exploration tech, I only run it several times so the conclusion may not be right, but just got a feeling of it, my hackish version seems faster...

mergepoint 10000 blocks run:
real	1m1.360s
user	1m0.836s
sys	0m0.520s

veritesting 10000 blocks run:
real	1m49.272s
user	1m48.332s
sys	0m0.936s

mergepoint 20000 blocks run:
real	1m51.730s
user	1m50.680s
sys	0m1.048s

veritesting 20000 blocks run:
real	4m2.336s
user	4m0.368s
sys	0m1.952s

**Comment by ltfish** [comment]
@humeafo I'm happy to take a PR that changes the strategy!

**Comment by humeafo** [comment]
@ltfish following is the code, it's hackish, I think maybe it's too hackish to be included in the angr codebase, the ideal place to do this is in step_state, but step_state doesn't support nesting, so I used step(), the question is 
`ss.flat_successors = []`
make it sneaky...
I only tested it on several examples, so I am not sure it's 100% correct.

mergepoint.py
`import angr
from angr import ExplorationTechnique
from angr.sim_options import EFFICIENT_STATE_MERGING

import logging
l = logging.getLogger('angr.mergepoint')

class MergePoint(ExplorationTechnique):
    """
    Enable veritesting. This technique, described in a paper[1] from CMU, attempts to address the problem of state
    explosions in loops by performing smart merging.

    [1] https://users.ece.cmu.edu/~aavgerin/papers/veritesting-icse-2014.pdf
    """
    def __init__(self, **options):
        super(MergePoint, self).__init__()
        self.options = options
        self._vt_candidates = {}
        self._vt_in_progress = False

    def setup(self, simgr):
        for state in simgr.active:
            if EFFICIENT_STATE_MERGING not in state.options:
                state.options.add(EFFICIENT_STATE_MERGING)
            state.inspect.b('engine_process', when=angr.BP_AFTER, action=self._on_engine_process)

    def step(self, simgr, stash, **kwargs):
        simgr = simgr.step(stash=stash, **kwargs)

        if len(self._vt_candidates) > 0:
            simgr.drop(filter_func=lambda x: x in self._vt_candidates, stash='deadended')

            for s, ldrop in self._vt_candidates.iteritems():
                l.debug('candidate veritesting block detected: %X, with successors: %d %s', s.addr, len(ldrop), ldrop)
                
                self._vt_in_progress = True
                vt = self.project.analyses.Veritesting(s, **self.options)
                self._vt_in_progress = False

                if vt.result and vt.final_manager:
                    vt_simgr = vt.final_manager
                    vt_simgr.stash(from_stash='deviated', to_stash='active')
                    vt_simgr.stash(from_stash='successful', to_stash='active')

                    simgr.stashes.setdefault(stash, []).extend(vt_simgr.active)
                    simgr.errored.extend(simgr.errored)

                    for _sname in ['deadended', 'unsat', 'unconstrained']:
                        simgr.stashes.setdefault(_sname, []).extend(vt_simgr.stashes.get(_sname, []))
                    l.debug('veritesting successful, vt-active: %d vt-errored: %d vt-dead: %d active: %d errored: %d dead: %d', len(vt_simgr.active), len(vt_simgr.errored), len(vt_simgr.deadended), len(simgr.active), len(simgr.errored), len(simgr.deadended))
                else:
                    # if veritesting failed, then we must re-add the succs
                    simgr.active.extend(ldrop)

            self._vt_candidates.clear()
        return simgr

    def _on_engine_process(self, state):
        if self._vt_in_progress: return
        ss = state.inspect.sim_successors
        if len(ss.flat_successors) >= 2:
            self._vt_candidates.setdefault(ss.initial_state, []).extend(ss.flat_successors)
            # a big hack to prevent other technique to cache these states, thus may incorrectly cause infinite state loops
            ss.flat_successors = []
`

**Comment by humeafo** [comment]
and using step() also means, this tech must be registered last, or else seems this may not properly interact with other later registered tech...so if use this method to replace veritesting module, there maybe problems, becuase veritesting often would be the first registered...

**Comment by ltfish** [comment]
I'm reopening it to keep track of the issues you brought up.

**Comment by Lukas-Dresel** [comment]
@humeafo: Why doesn't step_state support nesting? I think I changed it to do so now a while ago. If not let me know what I missed. That was what the idea behind it also now returning a stashes dict was about.

**Comment by rhelmot** [comment]
Step state doesn't support nesting... how can step state support nesting? It's the operation of taking a state and producing a successor. There's no good way to get multiple techniques to cooperate on that job.

**Comment by Lukas-Dresel** [comment]
@rhelmot: It's not about each one doing the stepping, it's about being able to deprioritize things nestedly. The same way only one technique can actually do the stash stepping, but the others can pass it through and deprioritize things or step things again as they see fit

**Comment by Lukas-Dresel** [comment]
If one technique doesn't pass through the stepping then it wins, sure.

**Comment by Lukas-Dresel** [comment]
Or for example I can have it step normally and then remove or add successors at will.

**Comment by humeafo** [comment]
@Lukas-Dresel yes, what you said is just what I means. but this maybe ok, because there are other means to accomplish the same work(eg, using siminspect).

There's another boring thing on exploration technique, the priority of the techniques can not be specified, currently calling order is based on the register order, this may cause some difficulties at some tasks, and the users must fully understand the tech order(if there are some interactions) and register them with correct order to use them.

**Comment by humeafo** [comment]
About the previous veritesting code, I'm not sure in engine_process, whether assign ss.flat_successors = [] is side effect free and acceptable, I feel it hackish personally.
