### ISSUE TITLE
cfgaccurate get_all_nodes anyaddr error

### ISSUE THREAD

**Issue by humeafo** [angr/angr#691]
the following snippet run on CROMU_00065 got fault  with get_all_nodes function, obviously, the anyaddr is broken for not considering the addr or size when it's None:

python t1.py ../tmp/CROMU_00065
building cfg accurate:
total cfg nodes: 1078 total cfg edges: 1625
Traceback (most recent call last):
  File "t1.py", line 14, in <module>
    cfg.get_all_nodes(0xcccccccc, anyaddr=True)
  File "/home/hume/mdev/symexec/angr/angr-dev/angr/angr/analyses/cfg/cfg_base.py", line 381, in get_all_nodes
    if cfg_node.addr == addr or (anyaddr and cfg_node.addr <= addr < (cfg_node.addr + cfg_node.size)):
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
fn = sys.argv[1]

code is:
`
from __future__ import print_function
import angr
fn = sys.argv[1]

print('building cfg accurate:')
b = angr.Project(fn, load_options={'auto_load_libs': False})
cfg = b.analyses.CFGAccurate(normalize=False, keep_state=True, context_sensitivity_level=3)
print('total cfg nodes: {} total cfg edges: {}'.format(len(cfg.graph.nodes()), len(cfg.graph.edges())))

cfg.get_all_nodes(0xcccccccc, anyaddr=True)
`

**Comment by humeafo** [comment]
just an additional detail:

node 804D3C4 size is None
node 804D401 size is None
node 804D3E1 size is None

the None size node is like the following code, all seems related to processing of syscall node...

.text:0804D3E6
.text:0804D3E6                 mov     eax, 3
.text:0804D3EB                 push    ebx
.text:0804D3EC                 push    ecx
.text:0804D3ED                 push    edx
.text:0804D3EE                 push    esi
.text:0804D3EF                 mov     ebx, [esp+10h+fd] ; fd
.text:0804D3F3                 mov     ecx, [esp+10h+addr] ; addr
.text:0804D3F7                 mov     edx, [esp+10h+len] ; len
.text:0804D3FB                 mov     esi, [esp+10h+arg_C]
.text:0804D3FF                 int     80h             ; LINUX -
.text:0804D401                 pop     esi . --> this
.text:0804D402                 pop     edx
.text:0804D403                 pop     ecx
.text:0804D404                 pop     ebx
.text:0804D405                 retn


.text:0804D3B8 status          = dword ptr  4
.text:0804D3B8
.text:0804D3B8                 mov     eax, 1
.text:0804D3BD                 push    ebx
.text:0804D3BE                 mov     ebx, [esp+4+status] ; status
.text:0804D3C2                 int     80h             ; LINUX - sys_exit
.text:0804D3C2 sub_804D3B8     endp
.text:0804D3C2
.text:0804D3C4 ; ---------------------------------------------------------------------------
.text:0804D3C4                 pop     ebx --> this
.text:0804D3C5                 retn

.text:0804D3C6                 mov     eax, 2
.text:0804D3CB                 push    ebx
.text:0804D3CC                 push    ecx
.text:0804D3CD                 push    edx
.text:0804D3CE                 push    esi
.text:0804D3CF                 mov     ebx, [esp+10h+arg_0]
.text:0804D3D3                 mov     ecx, [esp+10h+arg_4]
.text:0804D3D7                 mov     edx, [esp+10h+arg_8]
.text:0804D3DB                 mov     esi, [esp+10h+arg_C]
.text:0804D3DF                 int     80h             ; LINUX - sys_fork
.text:0804D3E1                 pop     esi  --> this
.text:0804D3E2                 pop     edx
.text:0804D3E3                 pop     ecx
.text:0804D3E4                 pop     ebx
.text:0804D3E5                 retn

**Comment by humeafo** [comment]
besides this, I compared the cfg of idapro, cfg_fast and accurate, following is the statistics:

total idacfg nodes: 1078 total idacfg edges: 1625
total nodes found in accurate 254 nodes found in fast 1217

there are only 254 nodes(cfg accurate) of 1217 nodes(cfg fast) left, I studied manually and found that indeed some reachable node missed in accurate, does this mean cfg accurate have some fatal bugs?
the binary is CROMU_00065 at this link: https://github.com/zardus/cgc-bins/raw/master/all_unpatched/CROMU_00065

**Comment by ltfish** [comment]
`CFGAccurate` does not guarantee full binary coverage. It generates a CFG from the specific start points (provided by `starts`) by forced execution, until it exhausts all reachable nodes.

**Comment by humeafo** [comment]
> CFGAccurate does not guarantee a full binary coverage. It generates a CFG from the specific start points (provided by starts) by forced execution, until it exhausts all reachable nodes.
It seems I misunderstood what 'accurate' means.  In fact after some time(several hours), the real covered blocks by sym-exec  is about 390 blocks, so it seems cfg-accurate analysis have done reasonable work.

**Comment by ltfish** [comment]
The word "accurate" here is indeed misleading and confusing... that name was a historical debt that I kept forgetting to pay.
