### ISSUE TITLE
Memory values manipulated

### ISSUE THREAD

**Issue by otelo29200** [angr/angr#694]
Hey,

For example, if I have the following (simplified) VEX statements :
`t24 = GET:I64(offset=56)`
`t38 = Add64(t24,0xffffffffffffff80)`
`t40 = LDle:I64(t38)`
`t10 = Sub64(t40,0x0000000000000008)`
`t41 = LDle:I64(t10)`

Is it possible to get the value of t41 directly (or something like offset + computed_address) ?

Also, is there a (simple?) way to know which memory addresses had been read/write between two sm.step() ?

**Comment by danse-macabre** [comment]
Hello,

> Is it possible to get the value of t41 directly (or something like offset + computed_address) ?

You can get the value of a temporary register from the `temps` attribute of `SimStateScratch` plugin. This could be done _after_ stepping a state forward by inspecting the `state.scratch.temps` of the desired successor.

> Also, is there a (simple?) way to know which memory addresses had been read/write between two sm.step()?

This could be done by setting a breakpoints on `'mem_read'` and `'mem_write'` events using the `state.inspect.make_breakpoint` or `state.inspect.add_breakpoint` methods, whichever you prefer. When the breakpoint is triggered, the values you're looking for could be obtained from the `state.inspect.mem_read_address` and `state.inspect.mem_write_address` respectively.

**Comment by ltfish** [comment]
> Also, is there a (simple?) way to know which memory addresses had been read/write between two sm.step()?

@danse-macabre gives one simple way. Alternatively, you can specify a set of state options called `refs` (`sim_options.refs`) to the initial state, and then take a look at `state.history.actions` after stepping.

**Comment by otelo29200** [comment]
Thanks, it seems to work perfectly :)
