### ISSUE TITLE
Hook an address (or entire memory range) with a custom SimEngine

### ISSUE THREAD

**Issue by danse-macabre** [angr/angr#695]
Following @zardus comment on #527 

> Also, an idea for a future improvement that just popped up: it might be cool to be able to hook an address (or entire memory range) with a custom SimEngine, so that it gets called for any address there. That could provide a nice interface that's more general than hooking an address with a SimProcedure, while being less deeply invasive than a SimInspect hook. We can also use this functionality to get rid of the looping-through-each-engine logic here.

I think it's a great idea, as this will make the overall angr architecture less _tight-coupled_ (or more _modular_) and flexible. The first _pros_ that comes to my mind are:

- `SimProcedure` handling will be a less-special case than it is now (no more stop_points at `SimEngineVEX`, no more checking of whether the address is hooked in `SimEngineHook`, etc.)
- The hook/unhook logic will be separated from the `Project`, and moved to somewhere it truly belongs, for example, a `SimMetaEngine` class, which will provide a generic hook/unhook/process methods.

The proposed implementation here is to introduce a new class called `SimMetaEngine` (name suggestions are welcome!). The `SimMetaEngine` would behave just like the `SimEngine` base class, expect that the process method won't take any actions on the provided state, but, instead, it will select an appropriate set of engines, which are hooked (or marked for execution) to the current address range, and iteratively try to make them process the state. For this to be done, the internal _hook map_ should be maintained in some form of a ranged dictionary. The keys for the _hook map_ are the address ranges, and the values are the ordered sets of the engines, which should be iteratively tried in order to process the state. In this case, an address range could be hooked with one or several engines, thus providing a fallback solution, if the first engine didn't work.

That's it. Sorry for bad English, I hope you understood my idea correctly. Looking forward to hear what you think about it.

**Comment by zardus** [comment]
A more configurable `EngineSelector` (suggested name) functionality might be good, but I'm not sure if it needs to mirror the SimEngine interface. Exporting hooking from the project is a really interesting concept... In the past, we've brainstormed _per-state_ hooks, which would be awkward in the current design, but we could have this selector be overridable on a per-state basis. Interesting stuff.

I'm for it in principle, and we could use something like `bintrees` to keep it fast and support ranges. However, we'll still need to pass custom stop points around, as VEX needs to know when to stop lifting, Unicorn needs to know when to stop executing, and so on.
