### ISSUE TITLE
how to distribute angr SE instance

### ISSUE THREAD

**Issue by humeafo** [angr/angr#696]
I digged the angr codes for a while, it seems the right method to distribute angr SE instance is to ana_store the states to disk or mongodb and fetch states from the central storage to do real SE distribution, am I right? Is there any existing implementations for reference or not? 
Thank you.

**Comment by ltfish** [comment]
@zardus is the best person to answer, but he is asleep.

**Comment by zardus** [comment]
If you set up the right ANA backend (see https://github.com/angr/angr/blob/master/tests/test_serialization.py), you should be able to just pickle stuff, and ANA will serialize stuff in and out to the backend as needed. This means that you _should_ be able to use celery or whatever other dispatch solution you want.

**Comment by zardus** [comment]
I'll add that the way _we_ tend to do (for example, in the Mechanical Phish) is to use kubernetes and schedule a different pod for each symbolic trace, distributing the work that way with no need to serialize state. But that's symbolic tracing, not symbolic exploration.

**Comment by humeafo** [comment]
thanks a lot for your help.
