### ISSUE TITLE
confuse about slove argv value

### ISSUE THREAD

**Issue by TN-root** [angr/angr#698]
the source code is :
![image](https://user-images.githubusercontent.com/30521851/31367690-9851f768-adab-11e7-88b8-17fb7d71c2e7.png)
I want to structure a symbol as a parameter,and after explore purpose block and on the basis of constraint I want to solve the symbol value.but it failed.
![image](https://user-images.githubusercontent.com/30521851/31367898-e453d202-adac-11e7-8cb6-9fa91d400510.png)
![image](https://user-images.githubusercontent.com/30521851/31367987-6864b476-adad-11e7-991e-2e3ecccd2147.png)
![image](https://user-images.githubusercontent.com/30521851/31368030-b6e1f03c-adad-11e7-8943-0f00f99319a1.png)
I want to know how can I solve symbol value correct?

**Comment by rhelmot** [comment]
You can't provide an address to data in the `entry_state` constructor - it expects to be given the actual string data to be used in your arguments.

The correct usage is `entry_state(args=["argv1", argv], ...)`
