### ISSUE TITLE
Docker install; missing packages?

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#70]
Hi!
I've been trying to use the Dockerfile from the https://github.com/angr/angr-doc/blob/master/INSTALL.md on a NUC running CentOS 7, and am running into some package issues. I am new to docker so I'm not sure it matters, but I have installed dependencies on the CentOS 7 (including for capstone using "pip install -I --no-use-wheel capstone" like in the documentation) that are shown as needed when the Dockerfile 'returned a non-zero code: 1':
![screenshot from 2016-03-22 12-32-45](https://cloud.githubusercontent.com/assets/10760263/13959362/34f8a2c4-f02a-11e5-845a-9b4a41d538ba.png)

Any insight as to where this may be going wrong?
Thanks!

**Comment by ltfish** [comment]
Please manually remove `libcapstone3` in `setup.sh` for now. The package is gone and we haven't updated the script yet.

**Comment by zardus** [comment]
Sorry, I did update the `setup.sh` script, but we don't have `angr-dev` auto-synchronizing between our internal repos and github, so it had never been pushed. I just pushed it, so the dockerfile should work.

As a side-note, you shouldn't need anything but docker in the host machine. All the dependencies will be installed *inside* the docker container.

Please reopen the issue if it still doesn't work!

**Comment by Dinatrix** [comment]
That's what I thought but figured I would try installing them outside of the file too before bugging you guys :) 
Works now, Thanks!
