### ISSUE TITLE
Bug in paged_memory.py when deep-copying pages for write

### ISSUE THREAD

**Issue by dorottyapapp** [angr/angr#701]
Hi! While analyzing a binary, I ran into an issue of uninitialized memory access (which resulted in a new symbolic variable, which lead to a state explosion). I tracked down the issue to the management of page copies within the machine state. Even though new objects are created for the machine state and the memory, `SimPagedMemory.branch()` uses `new_pages = dict(self._pages)`, which creates shallow copies of the memory pages. This is fine for reads, but the pages need to be deep-copied for writes to avoid overlaps in machine states. As far as I understood, in `SimPagedMemory._get_page()`, if a write is requested, the class checks whether the page in question has been already deep-copied (the page number is listed in `SimPagedMemory._cowed`). If no, than a deep copy is created of the page, and the page number is added to `SimPagedMemory._cowed` to avoid further deep copies.

The VEX IR for the block which triggers the bug: [vex_ir.txt](https://github.com/angr/angr/files/1371297/vex_ir.txt). This IR has 6 successors (of which only 1 will be followed, the jump to `0x24dc0`), and the relevant instructions for the bug are the following:

```
   11 | if (t42) { PUT(ip) = 0x24db0; Ijk_Boring }
   <...>
   30 | if (t59) { PUT(ip) = 0x24db4; Ijk_Boring }
   <...>
   41 | STle(t68) = t51
   <...>
   58 | if (t90) { PUT(ip) = 0x24dc0; Ijk_Boring }
   <...>
   73 | if (t105) { PUT(ip) = 0x24dc4; Ijk_Boring }
   <...>
   77 | STle(t108) = t93
   <...>
   79 | STle(t110) = t95
   <...>
   81 | STle(t112) = t97
   <...>
   107 | if (t139) { PUT(ip) = 0x24dec; Ijk_Boring }
   NEXT: PUT(pc) = 0x00024dd4; Ijk_Boring
}
```

At lines 11 and 30, two successor states are generated from the original, their memory pages are shallow copies of the original's. At line 41, the first write in the block happens, so the original state makes a deep copy of the page in question and adds the page number to `SimPagedMemory._cowed`. At lines 58 and 73, two additional successor states are generated, with shallow copies to the original's memory pages. The bug is triggered at line 77: this write request references the same memory page that has already been deep copied at line 41. Because the page number has already been added to `SimPagedMemory._cowed`, no deep copy is created, the memory page is written to. Even though two successor states (lines 58 and 73) hold shallow copies of the that same memory page.

The issue should be solved by emptying `SimPagedMemory._cowed` whenever a copy is made of the `SimPagedMemory` instance. That should be in `SimPagedMemory.branch()`, but the current version of the code doesn't have this instruction.

**Comment by zardus** [comment]
@m1ghtym0, would you mind terribly looking into this, since you're a memory expert? I haven't had a chance to, yet.

**Comment by m1ghtym0** [comment]
@zardus Sure I'm gonna take a look

**Comment by m1ghtym0** [comment]
From my understanding @dorottyapapp is right.
The scenario is like this:
```
state0->(page0)
  |
  |
(writes)->cp(page0->page1)
  |
  (branch)
  |        \
  |          \
  |            \
  |             |
  |            state1->(page1)
  |                 |
writes->(no cp)     |
  |
...

```
After the second write state1 has a modified page1, because state0 did not copy the page again before writing

**Comment by m1ghtym0** [comment]
@dorottyapapp Please check if your problem is solved now:-)

**Comment by dorottyapapp** [comment]
Yes, it is solved now. Thank You! :)
