### ISSUE TITLE
CFG Coverage of Angr

### ISSUE THREAD

**Issue by ikhwan12** [angr/angr#714]
Hi, I want to test angr performance and I want to know angr cfg coverage every time. By example, I want to test in 10 mins then I want to know how many percents of cfg coverage. Is it possible to do it? I need help how to do that?
Thank you.

**Comment by danse-macabre** [comment]
Hello,

Don't know if the question is still actual, but I'll try to answer it anyway.

If I understand correctly, you're interested in how much of the code in binary could be covered with the CFG analysis in a specified amount of time. If so, the one possible way to know it is to use the `progress_callback` and `show_progress` keyword arguments of *CFGFast* or *CFGAccurate*, as specified in the docstring:

```
class CFGFast(ForwardAnalysis, CFGBase): 
    ....
    def __init__(self, ...):
        """
        ...
        :param progress_callback:       Specify a callback function to get the progress during CFG recovery.
        :param bool show_progressbar:   Should CFGFast show a progressbar during CFG recovery or not.
        :return: None
        """

The `progress_callback` should be a function, that accepts a single positional argument called `percentage`, which indicates the percentage of analysis completion. The `percentage` value could be used as a metric of CFG coverage.

Please, note, that the *CFG coverage* estimation is rather inaccurate and greatly depends on the exact binary you're working on.
