### ISSUE TITLE
windows pe binary CFGAccurate issue

### ISSUE THREAD

**Issue by xwlin222** [angr/angr#728]
@ltfish 
script:
```
proj = angr.Project('hex.exe', load_options={'auto_load_libs': False})
cfg_acc = proj.analyses.CFGAccurate(keep_state=true)
```
`angr` reported `self.state.posix.argc.length is None` error, the whole error report is below:
[error_report.txt](https://github.com/angr/angr/files/1417222/error_report.txt)
The binary is in google drive:
[https://drive.google.com/open?id=0Bzz4AEqLq0iOM3EzQzdrZ2dkaW8](url)

**Comment by ltfish** [comment]
Here is what Google tells me:

```
We're sorry. You can't access this item because it is in violation of our Terms of Service.
```

Feel free to post the binary here, or send the binary to me on Slack. Thanks.

**Comment by XingweiLin** [comment]
Sorry for that.
This is the binary.
[hex.zip](https://github.com/angr/angr/files/1463319/hex.zip)
