### ISSUE TITLE
Can't define args in entry_state()

### ISSUE THREAD

**Issue by Tanjmaxalb** [angr/angr#737]
I have problem for call entry_state with defined args, when I work with PE32
```
user_id = claripy.BVS('user_id', 8 * 8)
password = claripy.BVS('password', 32 * 8)
argv = ['pe_file.exe', user_id, password]
project = angr.Project(argv[0])
state = project.factory.entry_state(args = argv)
```
```
Traceback (most recent call last):
  File "./pe_file.py", line 23, in <module>
    main()
  File "./pe_file.py", line 12, in main
    state = project.factory.entry_state(args = argv)
  File "/usr/lib/python2.7/site-packages/angr/factory.py", line 132, in entry_state
    return self._project._simos.state_entry(**kwargs)
  File "/usr/lib/python2.7/site-packages/angr/simos.py", line 796, in state_entry
    elif isinstance(arg, claripy.BV):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and type
```

**Comment by ltfish** [comment]
I'm 80% confident that we currently do not support setting `argc`s for Windows binaries. @rhelmot is this correct?

**Comment by Tanjmaxalb** [comment]
Can you suggest an alternative to emulating input values?

**Comment by ltfish** [comment]
Figure out where `argv`s are used, and manually inject symbolic variables to the correct memory location.

**Comment by ltfish** [comment]
But in any case, that line is buggy: It should be `claripy.bv.BV` instead of `claripy.BV`. Thanks for reporting.

**Comment by Tanjmaxalb** [comment]
The problem is that I need to generate for crackme challenge.

**Comment by Tanjmaxalb** [comment]
The problem is that I need to generate argv for crackme challenge.

**Comment by rhelmot** [comment]
Setting argv for windows binaries is supported! It will only work well with symbolic values if the program uses `__getmainargs` instead of `GetCommandLine` because of how disgusting the windows convention for passing command line arguments is, but it is supported, and fish's commit should fix your issue.
