### ISSUE TITLE
bug in  arm64g_calculate_condition

### ISSUE THREAD

**Issue by ejm9** [angr/angr#740]
-seems to be a bug in angr/engines/vex/ccall.py relating to handling B.LT ARM64 assembly instruction

def arm64g_calculate_condition(state, cond_n_op, cc_dep1, cc_dep2, cc_dep3):
    .....
    elif concrete_cond in (ARM64CondGE, ARM64CondLT):
        nf, c1 = arm64g_calculate_flag_n(state, cc_op, cc_dep1, cc_dep2, cc_dep3)
        vf, c2 = arm64g_calculate_flag_v(state, cc_op, cc_dep1, cc_dep2, cc_dep3)
        flag = inv ^ (1 & ~(nf ^ vf))   
    ------>  # bug happens here because nf is BV64 and vf is a BV96, and claripy operation for "^" complains that lengths are not equal

The attached file:
     
![bug](https://user-images.githubusercontent.com/29239083/32283448-91bbe5e8-bee1-11e7-85d6-f9477e6d1670.png)

... is binary (named bug.png, IT IS NOT a png, but is named that so it passes the filetype filter...) with these ARM64 instructions to show the bug:
000000000000000                 CMP             W3, #0x20
0000000000000004               B.EQ            0x10
0000000000000008               B.LT            0x14

Below is a sample program demonstrating the bug.

```python
import angr

def run_it():

    #l = logging.getLogger('angr')
    #l.setLevel(logging.INFO)

    p = angr.Project("bug.png", load_options={
        'main_opts': {
        'backend': 'blob',
            'custom_base_addr': 0x0,
            'custom_entry_point': 0x0,
            'custom_arch': 'AARCH64',
    },
    })
                
    state = p.factory.entry_state(addr=0x0)  # note: NO brackets around an option SET!!!

    state.regs.x3 = 0x0   # so the B.EQ  0x10 is not taken and get to bad instruction of B.LT  0x14

    sim = p.factory.simgr(state)

    while sim.active and not sim.unconstrained and not sim.errored: 
        if sim.active[0].addr >= 0xc:
            print("End of code reached, all done, exiting\n")
            break
        sim.step()

    print("\n\n Ended processing\n\n")
    print("sim: %s\n" % sim)

    for s in sim.errored:
        print("errored state: %s\n" % s)

if __name__ == '__main__':
    run_it()
```

**Comment by rhelmot** [comment]
Just got a chance to look at this - the bug is in arm64g_calculate_flag_v. All the lines that say `zero_extend(32)` are wrong, since v will always be a 64 bit value already. Unsure if just removing those is correct or if we actually need to get rid of the upper 32 bits of the expression.

**Comment by rhelmot** [comment]
I think I've fixed it. At least, your example runs now. Let me know if you run into any inaccuracies in emulation.
