### ISSUE TITLE
angr hangs without any warning

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#746]
When I was testing a 32bit PE binary, strange things happened.
I started running the program normally, and it started "running". First I thought it was running(it sometimes takes long time to finish). but after several minutes, it is still "running", then I broke it and examined the simgr. Surprisingly, all states stop at a simple "cdq" instruction.
Even if I modified the executable and changed the "cdq" to be "nop", it still stops at the same position.
No warning, and pretending to be running.

Here is the output
~~~~
>>> simgr
<SimulationManager with 3 deadended, 3 active>
>>> simgr.active
[<SimState @ 0x401171>, <SimState @ 0x401171>, <SimState @ 0x401171>]
>>> 
~~~~
And there is the code
~~~~
  1 import angr
  2 
  3 proj = angr.Project('./Binary_8cfe86c1f4f57d49f4fee3b297b3f9b8.exe')
  4 
  5 state = proj.factory.entry_state()
  6 simgr = proj.factory.simgr(state)
  7 
  8 simgr.explore(find=0x004014A5, avoid=0x00482ED2)                      
~~~~

**Comment by Kyle-Kyle** [comment]
Everytime, they will stop at the same address even if I set a hook at the address or several instruction before that address

**Comment by ltfish** [comment]
Can you turn on the debug logging of `angr.manager` and see what is being executed?

```
import logging
logging.getLogger('angr.manager').setLevel(logging.DEBUG)
```

**Comment by rhelmot** [comment]
If you see an address, angr may not necessarily be executing that
instruction specifically; it may be any instruction in the following basic
block.

This sounds like something has added a lot of complexity to the constraint
solver, and we are stuck in z3 for some reason. A common culprit for this
is when there are memory reads or writes to symbolic pointers. Can you
check if this is happening?

**Comment by Kyle-Kyle** [comment]
I examined it again. There is some kind of loop there, and then it is trapped there. Sorry for the trouble.
