### ISSUE TITLE
2 bugs in CFGAccurate

### ISSUE THREAD

**Issue by tyb0807** [angr/angr#747]
Hi,

Please take a look at this binary
[aes.zip](https://github.com/angr/angr/files/1450265/aes.zip)

1, We are having blocks not in their correct function. Examples are blocks from `0x93c9` to `0x946d`: they are supposed to be in `_vfprintf_r` function, but ended up being in `__aeabi_dcmpeq`. Interestingly, `__aeabi_dcmpeq` is called in block right before `0x93c9`. I guess this is a bug in https://github.com/angr/angr/pull/706?

2, Some blocks are simply missing. `__vfprintf_r` should contain block at `0xa057` which is not there. `cfg.get_any_node(0xa057)` also gives None. I guess the block is completely missing from the whole CFG?

@ltfish hope that I've explained clearly the issue.

Thanks

**Comment by ltfish** [comment]
The binary you attached is an object file `aes.obj`. Can you please give me the linked binary instead?

**Comment by tyb0807** [comment]
[aes.zip](https://github.com/angr/angr/files/1463054/aes.zip)
Here you are
