### ISSUE TITLE
Is there a method to find the CFGNode for a specific instruction address?

### ISSUE THREAD

**Issue by pragyansmita** [angr/angr#749]
Once we create the CFG, we can call get_any_node(address) to find it's corresponding CFG Node if it is the starting address of a block. 

However, for an address (that is not starting address of a block), how may we find the node that it is a part of? 

Thank you for your time and assistance.

**Comment by schieb** [comment]
`get_any_node` takes an optional kwarg `anyaddr`. Here is the documentation for that parameter:

:param bool anyaddr:    If anyaddr is True, then addr doesn't have to be the beginning address of a basic
                        block. By default the entire graph.nodes() will be iterated, and the first node
                        containing the specific address is returned, which is slow. If you need to do many such
                        queries, you may first call `generate_index()` to create some indices that may speed up the
                        query.

**Comment by pragyansmita** [comment]
Thank you, @schieb 
Trying it now. Appreciate the super quick response.

**Comment by pragyansmita** [comment]
It works. Closing the issue now.
