### ISSUE TITLE
CFGFast can not recognize some nodes

### ISSUE THREAD

**Issue by xwlin222** [angr/angr#750]
@ltfish 
```
robot_proj = angr.Project('Cube Robot.bin',
    load_options={
        'main_opts': {
            'backend': 'blob',
            'custom_base_addr': 0x8000000,
            'custom_entry_point': 0x8003791,
            'custom_arch': 'ARM'
        }
    }
)
cfg_fast = robot_proj.analyses.CFGFast()
```
But it can not recognize some nodes, such as `0x80001fe`
```
seg000:080001FE loc_80001FE                             ; CODE XREF: seg000:loc_8000244↓j
seg000:080001FE                 LDR     R0, =0x2000004B
seg000:08000200                 LDRB    R0, [R0]
seg000:08000202                 CMP     R0, #1
seg000:08000204                 BNE     loc_8000232
seg000:08000206                 LDR     R0, =0x2000004C
seg000:08000208                 LDRB    R0, [R0]
seg000:0800020A                 CMP     R0, #0x23
seg000:0800020C                 BNE     loc_8000220
seg000:0800020E                 MOVS    R1, #0
seg000:08000210                 LDR     R0, =0x40000400
seg000:08000212                 BL      sub_8004928
seg000:08000216                 MOVS    R0, #0xFA
seg000:08000218                 LDR     R1, =0x20000020
seg000:0800021A                 STRH    R0, [R1]
seg000:0800021C                 BL      sub_800263A
```
This is the binary:
https://drive.google.com/open?id=12XGHdkA6Kw_EwEnuCEwQZojPC0Zs30rh

**Comment by ltfish** [comment]
The binary is re-uploaded here.
[Cube Robot.zip](https://github.com/angr/angr/files/1463023/Cube.Robot.zip)

**Comment by ltfish** [comment]
This binary contains both ARM and THUMB code, and most of it is not reachable from the entry point you provided (`0x8003791`). It is very difficult for angr to decide whether a block should be decoded in ARM mode or in THUMB mode. We have some heuristics, including an architecture-specific option called `switch_mode_on_nodecode` that allows CFG recovery to switch between ARM and THUMB modes if VEX fails to decode an instruction. By default it is turned off. Turning it on for this binary, and changing the entry point to a better one (so `0x80001ff` is reachable from there) solves your issue.

Here is what you want to do:

```
robot_proj = angr.Project('Cube Robot.bin',
    load_options={
        'main_opts': {
            'backend': 'blob',
            'custom_base_addr': 0x8000000,
            'custom_entry_point': 0x80001ff,
            'custom_arch': 'ARM'
        }
    }
)

cfg_fast = robot_proj.analyses.CFGFast(show_progressbar=True, switch_mode_on_nodecode=True)
print cfg_fast.get_any_node(0x80001ff)
```

Output:

```
100% |####################################| Elapsed Time: 0:00:09 Time: 0:00:09
<CFGNode 0x80001ff[8]>
```

**Comment by XingweiLin** [comment]
`switch_mode_on_nodecode` can resolve this problem.
And the `collect_data_references` options will not take effect, when there is a firmware without segment information.
@ltfish
