### ISSUE TITLE
how to use angr to solve ctf problem while the target elf has PIE?

### ISSUE THREAD

**Issue by 3xp10it** [angr/angr#757]
I try to solve this ctf [challenage][1] with angr,but find it has PIE with [checksec][2],I try to solve it with below code,but it does not give me the answer,can you help me?

```
import angr

main = 0xe04
find = (0x10c8,)
avoid = (0x10bc,)

p = angr.Project('./my_secret')
#state = p.factory.entry_state()
state= p.factory.blank_state(addr=main)
state.posix.files[0].read_from(30)
pg = p.factory.simgr(state, threads=8)
ex = pg.explore(find=find, avoid=avoid)
#ex=pg.explore(find=lambda s:"it is my secret" in s.posix.dumps(1))

output = ex.found[0].posix.dumps(1)
print(output)
inp = ex.found[0].posix.files[0].all_bytes()  
print ex.found[0].solver.eval(inp,cast_to = str)

```

[1]: http://pinganctf.pwnhub.cn/#/question/59fd30123a1bf872376b1550
[2]:https://raw.githubusercontent.com/slimm609/checksec.sh/master/checksec

**Comment by ltfish** [comment]
From a quick glance at this binary, it seems to be using DES. angr (or symbolic execution) will not help you decrypt DES.

**Comment by rhelmot** [comment]
I think the more pressing issue after "angr cannot just solve this binary outright" is that you're using addresses copied from IDA - in the case of PIEs, IDA will load the binary at a base address of 0 while angr will load it at a base address of 0x400000. You see a warning about this when loading a PIE in angr.

**Comment by ltfish** [comment]
> but it does not give me the answer

For future references, "it does not give me the answer" is not useful for anyone to help you. You should clearly describe what you see (exceptions, errors, pre-mature termination of execution, etc.) when running your script.

**Comment by 3xp10it** [comment]
below is the output:

```
WARNING | 2017-11-16 08:04:44,927 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
Traceback (most recent call last):
  File "my_secret.py", line 15, in <module>
    output = ex.found[0].posix.dumps(1)
IndexError: list index out of range
```

**Comment by 3xp10it** [comment]
What if the elf doesn't use DES and just use a easy encrypt method? Will angr be able to solve it while the elf has PIE? Should I add 0x400000 to the address I found in IDA like:

```
import angr

**main = 0xe04+0x400000
find = (0x10c8+0x400000,)
avoid = (0x10bc+0x400000,)**

p = angr.Project('./my_secret')
#state = p.factory.entry_state()
state= p.factory.blank_state(addr=main)
state.posix.files[0].read_from(30)
pg = p.factory.simgr(state, threads=8)
ex = pg.explore(find=find, avoid=avoid)
#ex=pg.explore(find=lambda s:"it is my secret" in s.posix.dumps(1))

output = ex.found[0].posix.dumps(1)
print(output)
inp = ex.found[0].posix.files[0].all_bytes()  
print ex.found[0].solver.eval(inp,cast_to = str)
```

**Comment by rhelmot** [comment]
There's no difference between PIE and position-dependent binaries for angr. You can either do what you described or add `main_opts={'custom_base_addr': 0}` to the project constructor to deal with the address discrepancy between angr and ida by default.

**Comment by ltfish** [comment]
angr automatically loads PIE binaries at 0x400000. angr has no trouble dealing with PIE binaries.

**Comment by sharpicx** [comment]
> I think the more pressing issue after "angr cannot just solve this binary outright" is that you're using addresses copied from IDA - in the case of PIEs, IDA will load the binary at a base address of 0 while angr will load it at a base address of 0x400000. You see a warning about this when loading a PIE in angr.

love this answer!
