### ISSUE TITLE
Wipe Surveyors from the face of the earth.

### ISSUE THREAD

**Issue by zardus** [angr/angr#758]
Surveyors are long out of date. ~~PathGroups~~ SimulationManagers are the future. With the great power of SimulationManagers comes the great ~~responsibility~~ flexibility of ExplorationTechniques.

The last bastion of Surveyor power is the Slicecutor, which executes a provided slice. There is nothing (but lack of humanpower) stopping this from becoming an ExplorationTechnique, and we should a) do that and b) remove Surveyors for good.

**Comment by ltfish** [comment]
@peperunas is brave enough to use his super power to beat Slicecutor with his weapon called PR!

**Comment by zardus** [comment]
I'll believe it when I see it :-)

@peperunas, I'm rooting for you!

**Comment by peperunas** [comment]
The fight is on :sunglasses:

**Comment by rhelmot** [comment]
so that didn't work.

however, with the recent refactor of ExplorationTechnique it should now be much easier to implement this in a nice, way, since step_state can now be nested!

**Comment by rhelmot** [comment]
_weeps in joy_
