### ISSUE TITLE
Heap plugin

### ISSUE THREAD

**Issue by schieb** [angr/angr#762]
Heaps and memory allocations are much more than just pointers. Applications can have multiple heaps, heap allocations have sizes, permissions, etc, and different implementations depend on different metadata that needs to be kept track of somehow. In practice, the metadata is usually stored adjacent to the heap object. The typical way to keep track of such information in angr is through a state plugin.

I propose the following:
1. Move `heap_location` from the libc plugin to a new heap plugin
2. Add functions that let the user/simprocedure allocate chunks of memory, instead of forcing them to modify `heap_location` directly. Also promotes a consistent way to allocate memory. It is probably too common for people to choose an address and hope that nothing else is present there.
3. Allow for the addition of arbitrary metadata and make it easily accessible to simprocedures. The metadata could also be stored in the actual heap object giving a more accurate model with which to detect certain heap bugs.
4. As @rhelmot pointed out on slack: Ideally there would be multiple heap plugins for multiple allocators, the simplest of which is the current one where free does nothing.
5. In anticipation of 4, the simos should specify a default implementation which should be user-overridable.

Please use this issue to gather implementation and design ideas.

**Comment by rhelmot** [comment]
An important thing I'd like to have this handle is the distinction between `mmap` and `malloc`. One way to do this would be to have the heap plugin serve both `.malloc()` and `.mmap()`, with the former, handling the latter. Another way would be to add a mechanism to the memory plugin to make its allocator work the same way as linux/windows, where requesting the null address will cause it to pick an address for you.

Honestly I'd kind of like _both_ of these things to happen, with the memory implementing a generic interface and the heap plugin implementing the environment-specific interface, so e.g. the linux heap plugin would also implement `.brk()`.

**Comment by rhelmot** [comment]
cc @m1ghtym0 since he's done a lot of heap stuff in angr on what he thinks would be useful

**Comment by zardus** [comment]
If the goal is to be able to symbolically capture effects of specific allocators, then we wouldn't necessarily have a `LinuxHeap`, but a `DLMallocHeap`, `MUSLHeap`, and so forth. In that case, I think the memory map behavior wouldn't necessarily belong there. I think it'd make more sense to have the memory map stuff live, for example, fully inside SimOS (since it's really the OS that handles this), and the heap implementations use it as clients.

**Comment by rhelmot** [comment]
In that case I would like the memory plugin to have a mechanism to allocate memory by expanding the "break", regardless of if that makes sense in the current environment.

**Comment by m1ghtym0** [comment]
Just to make sure I don't get it wrong here is how I understand the initial idea:

*  We want  a heap state-plugin that provides an interface for allocator actions as `malloc`, `free`, etc.
* The plugin keeps track of all the heap metadata and states
* The plugin should behave according to some real world implementation, therefore:
     * Have a generic plugin that that provides access to `brk` and `mmap`
     * Have a specific plugin for e.g. `DLMallocHeap`, `PTMallocHeap` that mimics the particular implementation 
     * Each plugin provides an api for `.malloc()`, `.free()`, which can be used by the particular simprocedure

In that case, I agree with @zardus, it makes sense to have a plugin for each allocator's implementation.
I don't understand why we have to handle mmap and brk specifically for the heap plugin and can't use the current simprocedures? But I'm probably missing smth here.

**Comment by rhelmot** [comment]
No no no I wanted those handled by the _memory_ plugin, that is `state.memory`. The idea is that the heap plugin (or just users!) will need to perform these allocations, and shouldn’t have to call a SimProcedure to do so

**Comment by schieb** [comment]
This was implemented in #1432
