### ISSUE TITLE
LibVEXLifter seems to be ignoring the `max_bytes` value while lifting to IR

### ISSUE THREAD

**Issue by danse-macabre** [angr/angr#765]
This issue feels to do more with `pyvex`, than with `angr`, but since it does have a particulary interesting impact on the `Block` object behvaiour, I've decided to put it here.

Consider the following disassembly snippet from *tests/i386/fauxware*:

```asm
.init:08048394 53                             push    ebx             ; _init
.init:08048395 83 EC 08                       sub     esp, 8
.init:08048398 E8 00 00 00 00                 call    $+5
.init:0804839D 5B                             pop     ebx
```

Let's lift these instructions using the LibVEXLifter, while limiting the number of max lifted bytes to 9,
that is, trimming the last `pop` instruction:

```python
In [34]: p = Project('fauxware', auto_load_libs=False, translation_cache=False)

In [35]: b = Block(0x8048394, p, size=9)

In [36]: b.vex.jumpkind, b.bytes
Out[36]: ('Ijk_Boring', 'S\x83\xec\x08\xe8\x00\x00\x00\x00')
```

Note, that even that we have a `call` as the last instruction at `0x8048398`, the resulting jumpkind is still 'Ijk_Boring'. The reason behind this, to my understanding, is that the actual lifter does silently look ahead of the specified `max_bytes` to find out that the next instruction is `pop`, thus successfully indicating that the `call` instruction is not a call to a function.

Hovewer, if we lift those instructions using the exact instruction bytes, the results are different:

```python
In [34]: p = Project('fauxware', auto_load_libs=False, translation_cache=False)

In [37]: b = Block(0x8048394, p, byte_string=b'S\x83\xec\x08\xe8\x00\x00\x00\x00')

In [38]: b.vex.jumpkind, b.bytes
Out[38]: ('Ijk_Call', 'S\x83\xec\x08\xe8\x00\x00\x00\x00')
```

Here we can see that the resulting jumpkind is `Ijk_Call`, which is undoubtedly correct, as the last instruction is a `call` instruction and the lifter doesn't know what instruction does immediately follow this `call` instruction.

The fun part comes here:

```python
In [39]: p = Project('fauxware', auto_load_libs=False, translation_cache=False)

In [42]: b1 = Block(0x8048394, p, size=9)

In [43]: b1.vex.jumpkind
Out[43]: 'Ijk_Boring'

In [44]: b2 = Block(0x8048394, p, size=9)

In [45]: b2.bytes
Out[45]: 'S\x83\xec\x08\xe8\x00\x00\x00\x00'

In [46]: b2.vex.jumpkind
Out[46]: 'Ijk_Call'
```

That is, when the `bytes` property of a `Block` object is accessed before the `vex` property,
the results are different. The ambiguity comes from here:

```python
    @property
    def vex(self):
        if not self._vex:
            self._vex = self._vex_engine.lift(
                    clemory=self._project.loader.memory if self._project is not None else None,
                    insn_bytes=self._bytes,   # self._bytes is None unless the `bytes` property was accessed
                    ...
            )
            self._parse_vex_info()

        return self._vex
```

This implicit behavior could result in a bug, which is hard to detect, and which I was unlucky enough to encounter. I haven't come up with a suitable solution yet, so it'll be great to hear what you think about it.

**Comment by rhelmot** [comment]
wow

Probably the best solution to this is to disallow the lookahead behavior when it would cross the max_bytes boundary, but iirc the code structure of libVEX makes it hard to get at that information while you’re doing individual instruction translations? I’ll check when I’m not on my phone.

**Comment by danse-macabre** [comment]
I wonder if you might have time to look at this issue soon?
Or maybe you could give some advice for me on where should I start looking?

**Comment by rhelmot** [comment]
Yo, I'm fairly sure we fixed this recently - you can now pass `opt_level=-1` to disable as many optimizations as possible, including optimizations where data outside the block bytes are consulted. You can use this if you're in a situation where you need this to not be a problem.
