### ISSUE TITLE
Error when lift binary to vexir

### ISSUE THREAD

**Issue by ww9210** [angr/angr#768]
When lifting the following function to vex IR, the resulting vex IR is not correct:

0xffffffff81048a20:    push    rbp
0xffffffff81048a21:    mov    rbp, rsp
0xffffffff81048a24:    cli
0xffffffff81048a25:    pop    rbp
0xffffffff81048a26:    ret

IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64 t5:Ity_I64 t6:Ity_I64 t7:Ity_I64 t8:Ity_I64 t9:Ity_I64

   00 | ------ IMark(0xffffffff81048a20, 1, 0) ------
   01 | t0 = GET:I64(rbp)
   02 | t6 = GET:I64(rsp)
   03 | t5 = Sub64(t6,0x0000000000000008)
   04 | PUT(rsp) = t5
   05 | STle(t5) = t0
   06 | ------ IMark(0xffffffff81048a21, 3, 0) ------
   07 | PUT(rbp) = t5
   **08 | ------ IMark(0xffffffff81048a24, 2, 0) ------
   09 | PUT(pc) = 0xffffffff81048a26**
   10 | ------ IMark(0xffffffff81048a26, 1, 0) ------
   11 | t3 = LDle:I64(t5)
   12 | t4 = Add64(t5,0x0000000000000008)
   13 | PUT(rsp) = t4
   14 | t8 = Sub64(t4,0x0000000000000080)
   15 | ====== AbiHint(0xt8, 128, t3) ======
   NEXT: PUT(rip) = t3; Ijk_Ret
}

**Comment by rhelmot** [comment]
How would you like cli/sti to be emulated by a symbolic execution framework? :P

**Comment by ww9210** [comment]
I do not expect it to be simulated anyway, but hey, it is a one byte
instruction, and the vex IR thought it is a two bytes instruction, resulted
in following VEX IR incorrect.

2017-11-22 15:53 GMT-05:00 Audrey Dutcher <notifications@github.com>:

**Comment by rhelmot** [comment]
Oops, I'm sorry! Fix pushed.
