### ISSUE TITLE
No Distributions at all found for pefile (from cle->angr)

### ISSUE THREAD

**Issue by abbapatris** [angr/angr#77]
I am trying to install angr on my ubuntu 15.10 64 bit virtual machine. When I try to install it I am following the installation instructions : http://docs.angr.io/INSTALL.html

I did the: sudo apt-get install python-dev libffi-dev build-essential virtualenvwrapper
Then: mkvirtualenv angr && pip install angr
That is when it errors with "No Distributions at all found for pefile (from cle->angr)".   I have tried to install it manually and I get the same error.

**Comment by rhelmot** [comment]
I mean.... Here it is: https://pypi.python.org/pypi/pefile

Are you accessing the Internet through a proxy? That's the only thing I can think of that could allow the initial install steps to work but that one to fail...

**Comment by abbapatris** [comment]
yes I am accessing it through a proxy...but everything else I have tried to
install has worked

On Mon, Mar 28, 2016 at 11:55 AM, Andrew Dutcher <notifications@github.com>
wrote:

> I mean.... Here it is: https://pypi.python.org/pypi/pefile
>
> Are you accessing the Internet through a proxy? That's the only thing I
> can think of that could allow the initial install steps to work but that
> one to fail...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/angr/angr/issues/77#issuecomment-202454919>
>



-- 
Chad Stevens
40 Villa Roma Dr.
Tewksbury, MA 01876
Cell:    (857)939-0732

**Comment by rhelmot** [comment]
Okay, I can reproduce this. I'll let you know what I can find.

**Comment by rhelmot** [comment]
https://github.com/erocarrera/pefile/issues/92

So it looks like this issue has nothing to do with using a proxy, that was just a weirdly astute guess on my part. The pefile distribution itself seems to be broken right now, possibly due to some bugs in the package index.

I'll modify CLE to only require pefile as an optional dependency for now.

**Comment by rhelmot** [comment]
workaround until we get the new version uploaded: `pip install git+https://github.com/erocarrera/pefile.git#egg=pefile`

**Comment by rhelmot** [comment]
New release is out, no dependency on pefile. This should resolve this issue. If you run into more problems feel free to re-open or open a new issue if it's sufficiently different!
