### ISSUE TITLE
Reduce warnings in angr

### ISSUE THREAD

**Issue by ltfish** [angr/angr#776]
Currently there are too many warnings across angr. Some of them should be `INFO` instead of `WARNING`s, so we do not scare users unnecessarily.

Here is an example:

```
WARNING | 2017-11-28 23:11:53,418 | cle.loader | The main binary is a position-independent executable. It is being loaded with a base address of 0x400000.
```

The following steps can be taken to address this issue:

- Change `WARNING`s to `INFO` when necessary.
- Go over the code base of angr and its sub-modules, and change any unnecessary `INFO` output to `DEBUG`.
- Modify the logging script in angr-dev (or angr?) to print out messages with level >= `INFO` by default.

Thoughts?

**Comment by zardus** [comment]
I like it. The other thing we can do is set up multiple levels of DEBUG
logging, because that's basically how we are using INFO right now in some
places, and rename INFO to DEBUG2 or something.

But yeah, reducing the number of times that people see WARNING will help
with the support requests.

**Comment by rhelmot** [comment]
We should also have INFO1 and INFO2, with INFO1 being shown by default. Stuff like the 0x400000 default base does need to be flagged to the user.

**Comment by ltfish** [comment]
> Stuff like the 0x400000 default base does need to be flagged to the user.

I'm not sure. I'm afraid that people will get confused more easily if they expect the binary be loaded at the same location as IDA does.

**Comment by rhelmot** [comment]
no that's what I said! It _does_ need to be flagged to the user, but it's not a warning, nor is it debug. However, not all info needs to be flagged to the user, so this should be info1, which is shown by default.

**Comment by ltfish** [comment]
Oops I read it wrong.
