### ISSUE TITLE
Symbolic accesses and endianness

### ISSUE THREAD

**Issue by ercoppa** [angr/angr#777]
When using angr with this script:

```
import angr
import claripy

endness_values = [None, 'Iend_LE', 'Iend_BE']

for endness in endness_values:

    print "Testing symbolic load/write with endness=" + str(endness)

    binary = '/bin/ls' # we don't care for the binary
    project = angr.Project(binary, load_options={'auto_load_libs' : False})

    state = project.factory.entry_state(remove_options={angr.options.LAZY_SOLVES}, 
    	add_options={angr.options.SYMBOLIC_WRITE_ADDRESSES}) # store range => 128, load range => 1024 

    # addr in [0, 1]
    addr = claripy.BVS('addr', 64)
    state.se.add(addr >= 0)
    state.se.add(addr < 2)

    val = 0x01020304

    state.memory.store(addr, val, 4, endness=endness)   # we write 0x01020304 at addr
    res = state.se.any_n_int(state.memory.load(addr, 4, endness=endness), 10) # we should read 0x01020304 at addr

    print "Expected: " + hex(val)
    for r in res:
        print "Result: " + hex(r)
    print
```

Output (angr master branch):
```
Testing symbolic load/write with endness=None
Expected: 0x1020304
Result: 0x4010203L
Result: 0x2030401L

Testing symbolic load/write with endness=Iend_LE
Expected: 0x1020304
Result:  0x1020304

Testing symbolic load/write with endness=Iend_BE
Expected: 0x1020304
Result: 0x4010203L
Result: 0x2030401L
```
If endness is not `Iend_LE`, the result is wrong: `res` should be `[0x01020304]`

If we use the latest release of angr available with pip, the result is completely wrong:
```
Testing symbolic load/write with endness=None
Expected: 0x1020304
Result: 0x101a000L
Result: 0x1010000L
Result: 0x101a001L
Result: 0x1000001L
Result: 0x10da001L
Result: 0x1020304
Result: 0x1000000L
Result: 0x10fa001L
Result: 0x1012000L
Result: 0x105a001L

Testing symbolic load/write with endness=Iend_LE
Expected: 0x1020304
Result: 0x80018004L
Result: 0x8001a404L
Result: 0x1020304
Result: 0x8001a004L
Result: 0x4L
Result: 0x2018004L
Result: 0x8001e404L
Result: 0x82018004L
Result: 0x8001e004L
Result: 0x8011e004L

Testing symbolic load/write with endness=Iend_BE
Expected: 0x1020304
Result: 0x1810000L
Result: 0x1010000L
Result: 0x1000001L
Result: 0x1c10002L
Result: 0x1d10402L
Result: 0x1020304
Result: 0x1000000L
Result: 0x1c10402L
Result: 0x1c10000L
Result: 0x1d10c02L
```
We get this since the commit 3d033e0f1739008dbd86910a27becc28d52225d8 is not yet included and it is needed to get some (almost) correct results.

**Comment by ercoppa** [comment]
I have fixed few cut&paste errors in my previous comment.

**Comment by zardus** [comment]
Man, it's amazing to see how messed up the memory model can be...

@m1ghtym0, could you take a quick look? This might be impacting your results as well...

**Comment by m1ghtym0** [comment]
I have to disagree here, the result is correct IMO.
Let me explain what's going on:
- You store a concrete value to a symbolic address
- That means as long as you don't concretize the address, the value can be written to any valid solution of the BVS
- If you load from the BVS, the loading procedure will concretize the symbolic address to a certain threshold and you'll solutions for a subset of the valid addresses.
- Those addresses CAN be the destination of your write
- So the corresponding values CAN be your concret value, however that's just the case if the address of the write would be concretized to that address

=> That means the loaded value can also be the value you would receive if the write does not happen to that address. Which in this case is unconstrained memory and you receive all those other solutions. However you also see you concret value as ONE POSSIBLE solution.

**Comment by ercoppa** [comment]
@m1ghtym0 I don't follow your reasoning, sorry. There is no real concrete execution where the returned value should be different from `0x1020304`.  

Please, check my PR, it should fix the issue. The only problem was that angr was assuming little endianness when splitting a data object.

**Comment by ercoppa** [comment]
My fix is wrong. Ignore it.

**Comment by ercoppa** [comment]
I have done another PR (#789), similar to the previous one (it was failing due to lint errors). Even if no tests in Travis CI is failing, I am not confident that this is actually the right fix.

@m1ghtym0 

> If you load from the BVS, the loading procedure will concretize the symbolic address to a certain threshold and you'll receive solutions for a subset of the valid addresses.
> Those addresses CAN be the destination of your write

My point is that the symbolic engine must be consistent: if at any time, `addr` is assumed to be equal to one specific value, then any expression returned by the memory should take into account this assumption. If `SYMBOLIC_WRITE_ADDRESSES` is passed as option, then angr will:
- store several ITE expressions when doing the store (one for each address value)
- build an ITE expression when doing the load (composing the data read when reading from different valid addresses)
The returned ITE expression could have different cases, but all valid cases should evaluate to `0x1020304`, otherwise the execution is inconsistent. 

Another way of seeing this is that there is no concrete execution where the returned value (when doing a load) is different from `0x1020304`. In my example, `addr` can be only `0` or `1`.

When looking at my PR, what do you think?

**Comment by ercoppa** [comment]
Hi, i don't know you have time to look into it. Anyway, I have created a test case that shows the issue in a real binary, you can find all the stuff [here](https://gist.github.com/ercoppa/fa83bf082b5cc28e6e5a1b161ae35a53).

The C code:
```
#include <stdio.h>
#include <stdlib.h>

void avoid() { printf("Avoid\n"); exit(1); }
void found() { printf("Found\n"); exit(0); }
void failure() { printf("Failure\n"); exit(1); }

int main(int argc, char * argv[]) {

    if (argc != 2) avoid();
    char n = argv[1][0] - 97;
    if (n < 0 || n > 1) avoid();

    int m[2] = {0x0, 0x0};
    *((int *)(((char *) m) + n)) = 0x01020304;

    //printf("%d\n", *((int *)(m + n)));

    if (*((int *)(((char *) m) + n)) == 0x01020304) found();
    else failure();

    return 0;
}
```
where `avoid` and `failure` are marked as avoid targets, while `found` is the find target. There only two solutions: `a` (`97`) and `b` (`98`). 

Output (`make run`, using `qemu-mips` with the MIPS binary) with `angr==7.7.12.16`:
```
Running i386
./main-i386 a
Found
./main-i386 b
Found

Running mips
./main-mips a
Found
./main-mips b
Found

angr i386
python run.py i386
binary: main-i386
avoid: 134513803
found: 134513835
<SimulationManager with 1 found, 2 avoid>
Correct: argv[1]=[98L, 97]

angr mips
python run.py mips
binary: main-mips
avoid: [4196448, 4196600]
found: 4196524
Error: <SimulationManager with 3 avoid>
```
On i386 (little-endian) it works, while on MIPS (big-endian) it does not work.

Output after applying my patch:
```
Running i386
./main-i386 a
Found
./main-i386 b
Found

Running mips
./main-mips a
Found
./main-mips b
Found

angr i386
python run.py i386
binary: main-i386
avoid: 134513803
found: 134513835
<SimulationManager with 1 found, 2 avoid>
Correct: argv[1]=[98L, 97]

angr mips
python run.py mips
binary: main-mips
avoid: [4196448, 4196600]
found: 4196524
<SimulationManager with 1 found, 2 avoid>
Correct: argv[1]=[98L, 97]
```
Now, we get the expected result also on MIPS.

**Comment by m1ghtym0** [comment]
Hey,
Sorry for the silence and thanks for all the effort!
Will take a look this week!

**Comment by m1ghtym0** [comment]
I finally took another look!
I thought you meant the multiple results were the problem and didn't realize that you were talking about the endianness, which was indeed broken! Thank you for the clarification!
I just merged your patch! Thank you for the effort!
