### ISSUE TITLE
AttributeError: 'ArchX86' object has no attribute 'byte_width'

### ISSUE THREAD

**Issue by AnonymousXF** [angr/angr#781]
when I want to create a CFG:
import angr
p = angr.Project('binaries/tests/cgc/CROMU_00070')
cfg = p.analyses.CFGAccurate(keep_state=True)

then:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-a87ae6ca3196> in <module>()
----> 1 cfg = p.analyses.CFGAccurate(keep_state=True)

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/analysis.pyc in make_analysis(*args, **kwargs)
     94             oself._show_progressbar = show_progressbar
     95 
---> 96             oself.__init__(*args, **kwargs)
     97             return oself
     98 

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_accurate.pyc in __init__(self, context_sensitivity_level, start, avoid_runs, enable_function_hints, call_depth, call_tracing_filter, initial_state, starts, keep_state, enable_advanced_backward_slicing, enable_symbolic_back_traversal, additional_edges, no_construct, normalize, max_iterations, address_whitelist, base_graph, iropt_level, max_steps, state_add_options, state_remove_options)
    273         if not no_construct:
    274             self._initialize_cfg()
--> 275             self._analyze()
    276 
    277     #

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/forward_analysis.pyc in _analyze(self)
    499         """
    500 
--> 501         self._pre_analysis()
    502 
    503         if self._graph_visitor is None:

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_accurate.pyc in _pre_analysis(self)
    854                 # (addr, jumpkind)
    855                 ip = item[0]
--> 856                 state = self._create_initial_state(item[0], item[1])
    857 
    858             elif isinstance(item, SimState):

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/analyses/cfg/cfg_accurate.pyc in _create_initial_state(self, ip, jumpkind)
    922             state = self.project.factory.blank_state(addr=ip, mode="fastpath",
    923                                                      add_options=self._state_add_options,
--> 924                                                      remove_options=self._state_remove_options,
    925                                                      )
    926         else:

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/factory.pyc in blank_state(self, **kwargs)
    107         :rtype:                 SimState
    108         """
--> 109         return self._project.simos.state_blank(**kwargs)
    110 
    111     def entry_state(self, **kwargs):

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/simos/cgc.pyc in state_blank(self, fs, **kwargs)
     24     # pylint: disable=arguments-differ
     25     def state_blank(self, fs=None, **kwargs):
---> 26         s = super(SimCGC, self).state_blank(**kwargs)  # pylint:disable=invalid-name
     27 
     28         # Special stack base for CGC binaries to work with Shellphish CRS

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/simos/simos.pyc in state_blank(self, addr, initial_prefix, stack_size, **kwargs)
    122                 state.registers.store(i, state.se.BVV(0, state.arch.bits))
    123         if state.arch.sp_offset is not None:
--> 124             state.regs.sp = stack_end
    125 
    126         if initial_prefix is not None:

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/state_plugins/view.pyc in __setattr__(self, k, v)
     57 
     58         try:
---> 59             return self.state.registers.store(k, v, inspect=inspect, disable_actions=disable_actions)
     60         except KeyError:
     61             raise AttributeError(k)

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/storage/memory.pyc in store(self, addr, data, size, condition, add_constraints, endness, action, inspect, priv, disable_actions)
    485 
    486         # store everything as a BV
--> 487         data_e = self._convert_to_ast(data_e, size_e if isinstance(size_e, (int, long)) else None)
    488 
    489         # zero extend if size is greater than len(data_e)

/home/dell/xf/virtualenv/rex/local/lib/python2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/storage/memory.pyc in _convert_to_ast(self, data_e, size_e)
    393             data_e = self.state.se.BVV(data_e, bits)
    394         elif type(data_e) in (int, long):
--> 395             data_e = self.state.se.BVV(data_e, size_e*self.state.arch.byte_width if size_e is not None
    396                                        else self.state.arch.bits)
    397         else:

AttributeError: 'ArchX86' object has no attribute 'byte_width'

I can only find the attribute 'bytes' in state.arch.

**Comment by schieb** [comment]
Looks like the repos that angr depends on are out of sync. This often happens when users install different parts of the angr ecosystem from different sources.

For example, some from pip and others from git.

Are you using angr-dev? Please verify the output of `pip list` is what you expect.

**Comment by schieb** [comment]
The angr components are indeed out of sync - particularly archinfo and pyvex.

angr (7.7.9.21) <-- up-to-date
archinfo (7.7.9.14) <-- old
pyvex (7.7.9.14) <-- old


If you are not using an official release from pip then the recommended way of installing angr is from the [angr-dev](https://github.com/angr/angr-dev#install) repo.

If you do not want to use angr-dev then the solution is to either downgrade angr to version 7.7.9.14, or to upgrade the other dependencies manually.

**Comment by AnonymousXF** [comment]
Thanks! I have solved it
