### ISSUE TITLE
STT_GNU_IFUNC is relocated twice

### ISSUE THREAD

**Issue by m1ghtym0** [angr/angr#782]
When I try to load a binary with `STT_GNU_IFUNC` relocations, they are
resolved when creating the project with all other relocations during
`self.initial_load_objects = self._internal_load(main_binary, *force_load_libs)`

At the end of the project creation, `simos.configure_project` is called.
Which triggers the ifunc resolution in

https://github.com/angr/angr/blob/fcf7d376505e53eaa878325fbf70d4c191416a98/angr/simos/linux.py#L81-L108

Since, the relocations are resolved already, `funcaddr` is the resolved address and not the a ptr to the resolve stub.

This leads to an exception during runtime when the `IFuncResolver` `SimProcedure` is called.

**Comment by rhelmot** [comment]
Can you post a test case please? ifuncs are pretty common and I think we have test cases that depend on them

**Comment by m1ghtym0** [comment]
Will try to strip my stuff to a basic test case, asap.

**Comment by m1ghtym0** [comment]
I tried to create a basic example and that's what I got: [ifuncs_example.tar.gz](mightym0.de/ifuncs_example.tar.gz)
Hope that helps:-)

**Comment by rhelmot** [comment]
Can you explain what the problem actually is here? You said there was an exception during the ifuncresolver, but I'm not seeing any when I run the test.py

**Comment by m1ghtym0** [comment]
Oh I forgot to add the exploring in there. Still doesn't throw though.
I'm not sure why it doesn't throw the `AngrCallableError` exception in `sim_loader.py:34`. If you break there you'll see that `funcname` is `time` and `funcaddr` is `0x20bb7d0`, which is `time` in the provided libc.
This should fail as it tries to resolve `time` with the actual `time` address. However it returns `0x20bb7c0`, which is right above `time` and makes no sense to me. In my non-strip case the same situation throws the exception.

**Comment by rhelmot** [comment]
Okay so you seem to be misled about how ifuncs work - the thing that is marked by the symbol named "time" is actually the resolver stub - it tries to look into a bunch of things like the vdso to decide what the best version of time(2) it should call is, and because of the way we've jerry-rigged the environment in angr, it decides to return 0xBB7C0:

```
.text:00000000000BB7C0                 mov     eax, 0C9h
.text:00000000000BB7C5                 syscall                 ; LINUX - sys_time
.text:00000000000BB7C7                 retn
```

Which is just the simplest possible implementation.

You really need to show me something that actually throws an exception :P

**Comment by m1ghtym0** [comment]
Damn ok, the exception in my case is happening because `resolve` is not the resolver stub, but instead is the actual `time` function.
I'll try figure out where the difference is coming from
