### ISSUE TITLE
angr not finding a path

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#79]
Hi!

I'm trying to find a (known) backdoor using angr. In disassembly I have located exactly where the entered number is tested against the backdoor number (circled), as well as the normal authentication routine (has_access T/F) which leads to the overall 'open' and 'deny' outputs. My thought was to use angr to find the 'open' output but avoid the normal authentication routine and if that path exists, print out the what input allowed this path. (Presumably the backdoor)

![image](https://cloud.githubusercontent.com/assets/10760263/14210067/5d428ab0-f7f5-11e5-8aa9-1851c59a68a6.png)

However, when I try to use angr to print out possible strings that could lead us to this path, I see this error:

![image](https://cloud.githubusercontent.com/assets/10760263/14210125/9e3246dc-f7f5-11e5-8794-dd3f74650619.png)

relevant angr code:
![image](https://cloud.githubusercontent.com/assets/10760263/14210214/01b0a2f8-f7f6-11e5-9b19-2ca7fd9c0a7f.png)

Do you know what may be causing this error?
I wasn't sure how much detail to go into here, but could provide via email the binary or angr scripts I was testing.

Thanks!

**Comment by ltfish** [comment]
Can you please print out `pg`? I suppose all paths went deadended before reaching the target.

Also, are you sure that `0x406a34` is the beginning of a basic block? Right now `find` and `avoid` of `PathGroup.explore` only takes beginnings of basic blocks. This issue does not exist in `surveyors.Explorer`. I'll make sure to fix it in the next release!

**Comment by Dinatrix** [comment]
When I added 'print pg': 
![image](https://cloud.githubusercontent.com/assets/10760263/14210679/1331a1f6-f7f8-11e5-92fe-ed34976d326a.png)

![image](https://cloud.githubusercontent.com/assets/10760263/14210663/040e89a0-f7f8-11e5-9883-bdc03c2ff5e6.png)

The beginning of this whole function, used in b.factory.path:
![image](https://cloud.githubusercontent.com/assets/10760263/14210576/9d33d186-f7f7-11e5-86cd-2391d188a683.png)
I have attempted to move where this starts closer to the authentication check in case there were too many paths to explore but that did not help.

I have tried 0x406a34 as well as 0x406a24 (beginning of the 'open' block) with the same result.
The 'open' output block:
![image](https://cloud.githubusercontent.com/assets/10760263/14210522/520ad4c0-f7f7-11e5-8e77-bc1356bcdbe8.png)

The backdoor beq:
![image](https://cloud.githubusercontent.com/assets/10760263/14210541/729406da-f7f7-11e5-9837-53088dfc5061.png)

Hmm would you recommend I try a similar strategy using surveyors.Explorer if this does not work?

**Comment by ltfish** [comment]
Apparently an error occurred: `<PathGroup with 120 errored>` . It's probably a bug in either angr or your code. You can retry the path and see what the error was: `pg.errored[0].retry()`. It should print out the exception. Post the exception here and we'll see where to go from there.

**Comment by Dinatrix** [comment]
![image](https://cloud.githubusercontent.com/assets/10760263/14217069/130e8762-f81a-11e5-9bc0-d3681ee7dd26.png)

**Comment by ltfish** [comment]
Oh somehow it jumps to 0x0 and wants to execute from there. Maybe you already reached the end of the function? Can you please take a look at `list(pg.errored[0].trace)` and see if the control flow complies with what you expect?

**Comment by Dinatrix** [comment]
Hmm I have tried 'print list(pg.errored[0].trace' as well as just 'list(pg.errored[0].trace' with no change in output. Are either of these what you meant by 'take a look at list(pg.errored[0].trace)'?

**Comment by ltfish** [comment]
`print list(pg.errored[0].trace)` should give you a list of all basic blocks (which are 120 basic blocks) it traversed on the way.

**Comment by Dinatrix** [comment]
Ah this attribute seems to not be available?
![image](https://cloud.githubusercontent.com/assets/10760263/14217684/883b75ba-f81d-11e5-9e6d-92f2e16a3fb2.png)

**Comment by ltfish** [comment]
Weird... is there a `pg.errored[0].backtrace`? That attribute has been renamed to `trace` some time ago.

**Comment by Dinatrix** [comment]
Ah I ran this script against the binary in a more updated version of angr. The script definitely goes from the very beginning of the function to the end, it just happens to miss the addresses I'm looking for. I will look closer at the disassembly to follow these paths and see where it may be going.
![image](https://cloud.githubusercontent.com/assets/10760263/14218554/df2ffbac-f822-11e5-8979-355585313c0b.png)

Thanks!

**Comment by ltfish** [comment]
No problem. I see there are some C++ functions in the trace that are not executed at all (they are replaced with `ReturnUnconstrained`, which is a dummy SimProcedure). They might be the problem. You can try to load `libstdc++` along with the binary you are analyzing by specifying `load_options={'auto_load_libs': True}` when creating the project.

**Comment by ltfish** [comment]
I'm closing this issue. Feel free to reopen it or create a new one if you have more problems!

**Comment by Dinatrix** [comment]
Working my way through the addresses of the program it looks like the verification point I'm looking for is never reached due to a previous input check always failing. I also tried to avoid this other input check to force angr down the path that does have the authentication point using surveyors.Explorer rather than the pathgroup explorer, but am running into this result: 
![image](https://cloud.githubusercontent.com/assets/10760263/14254671/cc55bb82-fa5e-11e5-913b-0a798bf9d7b6.png)

Alternatively, would there be a way to test various badge IDs or lengths from within this angr program? I think part of my problem is trying to develop a backdoor finding angr script without relying on too much knowledge of the source code, but it is hard to avoid!

Thanks :)

**Comment by Dinatrix** [comment]
(As a side note, I don't believe I have permissions to re-open an issue on this repo?)
