### ISSUE TITLE
the angr doesn't work well in mechaphish

### ISSUE THREAD

**Issue by fushouhai** [angr/angr#796]
I am very interest in CGC,and I have tried many times but it doesn't work well, so  I would appreciate it if you could tell me the branch of angr used in CGC last year.

**Comment by rhelmot** [comment]
There is a script in the repository `angr-dev` called `checkout_at.py` if I recall correctly that will check out all the repositories from a specific date. You want the date of the CGC last year, August 4 2016.

We can't devote time to making sure that the full mechaphish system integration still works, but most of the components (with the exception of rex, which has been picked recently up by a third party with the intent of upgrading it to the newest angr release) should still work.
