### ISSUE TITLE
Slow CFG analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#8]
I was just trying out the sample code in angr site on `/bin/ls` binary. The analysis kept running for almost one day without any output. I've also tried with `call_depth = 3`, but in that configuration, ti can only extract CFG for some of the functions. Is this expected? Is there any way to speed up analysis?

```
>>> import angr
>>> proj = angr.Project('/bin/ls')
>>> cfg = proj.analyses.CFG(); cfg.function_manager.functions
```

**Comment by rhelmot** [comment]
https://github.com/angr/angr-doc/blob/master/faq.md

see the bottom entry :)

**Comment by riyadparvez** [comment]
Great, thanks! This should be in the CFG analysis doc.

**Comment by rhelmot** [comment]
Just added a note about this in the analysis documentation. Thanks!

**Comment by riyadparvez** [comment]
Cool!

I'm seeing multiple edges between same node i.e., the CFG is multi-graph. Is there any reason why the CFG is multi-graph?

**Comment by rhelmot** [comment]
Technically, the CFG is not a multigraph, simply a directed graph with confusingly similarly named nodes :stuck_out_tongue: 

This has to do with how the analysis works with contexts. A new node in the graph is created for every context a block is run in (this can be controlled with the context_sensitivity_level parameter). There's some discussion of what a context is in the analysis docs. In general you'll want to just use the `get_any_node` method.

**Comment by riyadparvez** [comment]
I understand.

A basic block can be represented by more than one node in CFG which are dependent on the context. 
I want the usual CFG where each block is represented by only one node in the CFG. Do you have any suggestions, how should this be done?

**Comment by ltfish** [comment]
You may want to try to generate a CFG with context sensitivity level of 1.

**Comment by riyadparvez** [comment]
The default is already context sensitivity level of 1.

**Comment by ltfish** [comment]
Then it should not happen... can you please give me an example? Thanks!

Just in case I can't reply in time: 1) Edges in CFG have a `type` field associate with them. Maybe those edges have different types. 2) Take a look at the function transition graph in `CFG.function_manager.function(name=...).transition_graph`. Do you still see more than one edge between same pair of nodes?

**Comment by riyadparvez** [comment]
Thanks for your reply.

1. I don't see any `type` field in edge, they are just tuples consists of source and destination CFG nodes. 
2. What's a transition graph of a function? Is the CFG of that function?

**Comment by ltfish** [comment]
Sorry, I meant `jumpkind` (not `type`).

`jumpkind` comes from VEX directly. VEX does not encode if a jump is conditional or not, and it's unlikely for us to encode that information in `jumpkind`. However, I believe it's a good idea to add another property for each edge (like a bool variable named `conditional`) to store the information. Does that satisfy your needs?

A transition graph is a function-level control flow graph, like what you normally see in IDA's graph view. There is also a `local_transition_graph` with only nodes in current function. Take a look at it.

Getting Internet access on a trip is difficult. My apologies for not replying in time :P

**Comment by riyadparvez** [comment]
A boolean variable `conditional` sounds good in edge data field.

Does this method `CFG.get_loop_back_edges()` return the natural loop (from `for`, `while` constructs) back edges or all the loop (any loop in the CFG including loops due to cycles in the call graph) back edges?

**Comment by ltfish** [comment]
`CFG.get_loop_back_edges()` returns all the loop back edges in the graph.

BTW: How can I tell if a loop is a natural loop or not?

**Comment by riyadparvez** [comment]
You can detect natural loops using dominator analysis on intra-procedural CFG [1].
 
[1] http://www.cs.utexas.edu/~pingali/CS375/2010Sp/lectures/LoopOptimizations.pdf

**Comment by ltfish** [comment]
Thanks! I'll read it later.

**Comment by riyadparvez** [comment]
The enumerated paths from 'usual CFG' (each Basic Block is represented by
only one node) may not be 'valid' control flow paths [1], since function
calls and returns may not be well-matched in a path of CFG.

Is it fair to say the enumerated paths from 'angr CFG' (a BB can be
represented by more than one node depending on the calling context) are
'valid' control flow paths as function calls and returns are well-matched?

[1] http://www.cs.berkeley.edu/~dawnsong/papers/2011%20issta11sandwich.pdf
- Fig. 4

**Comment by ltfish** [comment]
@riyadparvez: I believe so. It is _well-matched_ up to the level of context-sensitivity that you specify when you are building the CFG. Building a CFG with context-sensitivity of 0 yields a non-well-matched CFG.

**Comment by riyadparvez** [comment]
On Thu, Aug 20, 2015 at 4:27 PM, ltfish <notifications@github.com> wrote:

> Sorry, I meant jumpkind (not type).
>
> jumpkind comes from VEX directly. VEX does not encode if a jump is
> conditional or not, and it's unlikely for us to encode that information in
> jumpkind. However, I believe it's a good idea to add another property for
> each edge (like a bool variable named conditional) to store the
> information. Does that satisfy your needs?
>
> A transition graph is a function-level control flow graph, like what you
> normally see in IDA's graph view. There is also a local_transition_graph
> with only nodes in current function. Take a look at it.
>

@ltfish I've never used IDA. Regarding transition_graph, can you elaborate
on 'function-level control flow graph'? I don't suppose you're talking
about call graph.

local_transition_graph is the intra-procedural CFG of that function, is it
correct?

Getting Internet access on a trip is difficult. My apologies for not

**Comment by riyadparvez** [comment]
On Fri, Aug 21, 2015 at 11:13 AM, ltfish <notifications@github.com> wrote:

> @riyadparvez <https://github.com/riyadparvez>: I believe so. It is
> *well-matched* up to the level of context-sensitivity that you specify
> when you are building the CFG. Building a CFG with context-sensitivity of 0
> yields a non-well-matched CFG.
>

Cool! You guys solved one of things in my TODO list :-)

**Comment by ltfish** [comment]
> @ltfish I've never used IDA. Regarding transition_graph, can you elaborate
> on 'function-level control flow graph'? I don't suppose you're talking
> about call graph.

`transition_graph` gives you a control flow graph of basic blocks _inside_ a single function, as well as nodes that representing where the current function calls/jumps. It's not a call graph.

> local_transition_graph is the intra-procedural CFG of that function, is it
> correct?

Correct. `local_transition_graph` is a control flow graph containing just basic blocks _inside_ the current function, i.e. the intra-procedural CFG.

The reason that two different graphs are provided is simply that they are both used in our research. Pick whichever fits your needs.

I will detail them in documentation later as well.

**Comment by ltfish** [comment]
> Cool! You guys solved one of things in my TODO list :-)

I'd like to thank you for testing `angr` as well :-) I know how hard it is to work with.
