### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by liumengdeqq** [angr/angr#807]
while p.successors[0].addr not in relevants:
  File "/Library/Python/2.7/site-packages/angr-7.7.9.21-py2.7.egg/angr/sim_state.py", line 200, in __getattr__
    raise AttributeError(v)
AttributeError: successors

**Comment by liumengdeqq** [comment]
Why do you see this problem? 
  thinks

**Comment by ltfish** [comment]
Try updating your angr install first. The latest version on PyPI is 7.7.12.6.

**Comment by liumengdeqq** [comment]
while p.successors[0].addr not in relevants:
  File "/Library/Python/2.7/site-packages/angr-7.7.12.16-py2.7.egg/angr/sim_state.py", line 201, in __getattr__
    raise AttributeError(v)
AttributeError: successors

7.7.12.16 is the latest ?  but it is error.

**Comment by liumengdeqq** [comment]
I used docker， it maked error too

**Comment by rhelmot** [comment]
state.successors doesn't exist anymore. If you're using a tutorial that was written earlier than September, it is no longer valid.

**Comment by liumengdeqq** [comment]
who change it ?

**Comment by ltfish** [comment]
It was part of our major refactor during July this year.
