### ISSUE TITLE
UnsupportedIROpError: floating point support disabled

### ISSUE THREAD

**Issue by 92wyunchao** [angr/angr#809]
When I run driller to test one of cgc binary named NRFIN_00017 with the command "shellphuzz -c 2 -d 2 -C NRFIN_00017 ", I get the following error, could you tell me what is wrong here? Thank you.
Traceback (most recent call last):
  File "/home/administrator/clark/driller/angr-dev/angr/angr/engines/vex/irop.py", line 926, in translate_inner
    raise UnsupportedIROpError("floating point support disabled")
UnsupportedIROpError: floating point support disabled

**Comment by rhelmot** [comment]
(was answered in https://github.com/shellphish/driller/issues/55)
