### ISSUE TITLE
Fail to build angr_native.dylib on macOS

### ISSUE THREAD

**Issue by liumengdeqq** [angr/angr#810]
angr.state_plugins.unicorn_engine | failed loading "angr_native.dylib", unicorn support disabled (dlopen(/Library/Python/2.7/site-packages/angr-7.7.12.16-py2.7.egg/angr/lib/angr_native.dylib, 6): image not found: dlopen(/Library/Python/2.7/site-packages/angr-7.7.12.16-py2.7.egg/angr/lib/angr_native.dylib, 6): image not found 

In the Mac , if it used "import angr" , it should make error

**Comment by ltfish** [comment]
FYI: https://github.com/angr/angr/issues/234
