### ISSUE TITLE
IR decoding error on bswap reg16

### ISSUE THREAD

**Issue by newgre** [angr/angr#815]
An IR decoding error is thrown when trying to lift below bswap instruction in AMD64 mode.

`66 0F CE    bswap   si`

original error:

> angr.errors.SimIRSBNoDecodeError: IR decoding error at 0x140069aa9. You can hook this instruction with a python replacement using project.hook(0x140069aa9, your_function, length=length_of_instruction).

**Comment by rhelmot** [comment]
So this instruction is "undefined" - the docs say you shouldn't be allowed to do this, which is why vex complains. However we should be able to still do something, so I've pushed [this](https://github.com/angr/vex/commit/7394e917fc86c8f042d8ce51a609810a97c20fd7), which should resolve the issue.
