### ISSUE TITLE
size argument of get_pseudo_addr in angr 7 disappeared

### ISSUE THREAD

**Issue by XingweiLin** [angr/angr#817]
Hi, @rhelmot 
In `angr 6`, `get_pseudo_addr` has an `size` argument that I can determine the memory size of my external object.
```
    def get_pseudo_addr(self, ident, size=16):
        if ident not in self._lookup_table:
            self._lookup_table[ident] = self._next_addr
            self._next_addr += size + ((self._granularity - size) % self._granularity)
        return self._lookup_table[ident] + self.rebase_addr
```
`angr 7` discards the `size` argument and replaces it with `alignment` argument.
So I cannot allocate custom memory size for my external object.

**Comment by rhelmot** [comment]
Use .allocate() instead, which takes a size instead of a name.
Pseudo-addresses are meant for functions, hence the caching of the names.
For other sized objects, it makes more sense to use an anonymous allocation
model.

**Comment by XingweiLin** [comment]
fixed, thx @rhelmot
