### ISSUE TITLE
MIPS, How to create a SimFile and use Symbolic Execution?

### ISSUE THREAD

**Issue by zaipingy** [angr/angr#822]
I want to use angr to analysis a program as below,
`
void do_system(int code,char *cmd)`
`{`
	`char buf[255];`
	`system(cmd);`
`}`

`void main()`
`{`
`	char buf[256]={0};`
`	char ch;`
`	int count = 0;`
`	unsigned int fileLen = 0;`
`	struct stat fileData;`
`	FILE *fp;`
`	if(0 == stat("passwd",&fileData))`
`		fileLen = fileData.st_size;`
`	else`
`		return 1;`
`	if((fp = fopen("passwd","rb")) == NULL)`
`	{`
`		printf("Cannot open file passwd!\n");`
`		exit(1);`
`	}`
`	ch=fgetc(fp);`
`	while(count <= fileLen)`
`	{`
`		buf[count++] = ch;`
`		ch = fgetc(fp);`
`	}`
`	buf[--count] = '\x00';`
`	if(!strcmp(buf,"adminpwd"))`
`	{`
`		do_system(count,"ls -l");`
`	}`
`	else`
`	{`
`		printf("you have an invalid password!\n");`
`	}`
`	fclose(fp);`
`}`

By read example of asisctffinals2015_license, i write the code as below
`
import angr`
`p = angr.Project('vuln_system',load_options={'auto_load_libs':False})`
`state_main = p.factory.entry_state()`
`bytes = state_main.solver.BVS('passwd',8*8)`
`file_name = 'passwd'`
`content = angr.state_plugins.SimSymbolicMemory(memory_id='file_passwd')`
`content.set_state(state_main)`
`content.store(0, bytes)`
`passwd_file = angr.storage.SimFile(file_name, 'rb' , content=content,size=len(bytes)/8)`
`fs = {file_name:passwd_file}`
`ex = p.surveyors.Explorer(start=state_main,find=(0x400554,))`
`ex.run()
`
the find is the location of CMD, but the result of this code is 
`
WARNING | 2018-01-11 04:10:25,681 | angr.procedures.definitions | unsupported syscall: sys_4283
WARNING | 2018-01-11 04:10:25,856 | angr.procedures.definitions | unsupported syscall: sys_4054
WARNING | 2018-01-11 04:10:26,168 | angr.procedures.definitions | unsupported syscall: sys_4054
WARNING | 2018-01-11 04:10:27,165 | angr.procedures.definitions | unsupported syscall: sys_4054
WARNING | 2018-01-11 04:10:34,108 | angr.procedures.definitions | unsupported syscall: sys_4246
WARNING | 2018-01-11 04:10:36,719 | angr.procedures.definitions | unsupported syscall: sys_4246
WARNING | 2018-01-11 04:10:39,024 | angr.procedures.definitions | unsupported syscall: sys_4246
Out[16]: <Explorer with paths: 0 active, 0 spilled, 3 deadended, 0 errored, 0 unconstrained, 0 found, 0 avoided, 0 deviating, 0 looping, 0 lost>
`
Can anyone give me a hint ? Very Thanks!!!

**Comment by rhelmot** [comment]
I'm very confused as to why you're getting errors about syscalls with `auto_load_libs=False`. Can you please upload the binary?

**Comment by rhelmot** [comment]
Oh god you're probably using a statically linked binary aren't you

angr has very limiited support for emulating syscalls. as a result, the line `auto_load_libs=False` is meant to disable the loading of shared libraries to improve tractability - what angr will do is replace all functions imported from a shared library with either a python implementation of the function (a SimProcedure) or a stub that does nothing but return when no appropriate SimProcedure is available. By static-linking, you remove angr's ability to do this automatically. You can still add simprocedures to the appropriate addresses through a process called hooking; read through our docs.

**Comment by zaipingy** [comment]
@rhelmot  i have pushed the binary to [link](https://github.com/zaipingy/angr_firmware)

**Comment by zaipingy** [comment]
[binayr.zip](https://github.com/angr/angr/files/1621302/binayr.zip)

**Comment by zaipingy** [comment]
i read the docs about SimProcedures, it seems that the binary i upload lost the libs by static-linking, so it cannot analysis, and i must found these libs address, and hook it by appropriate function, does it? 
And i want to ask another question, Does angr can get the post parameters or environment variables? and how?

**Comment by zaipingy** [comment]
@rhelmot very thanks for your answer!!!
the 'post parameters' is mean the MIPS binary i analysis will accept a http request and the method is POST, so i want to structure this parameter to attact this binary.

**Comment by rhelmot** [comment]
That information is too high-level for angr to deal with automatically. You'll need to construct a partially-symbolic and partially-concrete input from several variables, then store it into the state's stdin stream, then add constraints on subcomponents of the input that various parts may not contain newlines, equals signs, etc
