### ISSUE TITLE
cloning from angr-dev, but permission denied

### ISSUE THREAD

**Issue by sebastianwalla** [angr/angr#825]
When I try cloning the angr-dev version I get the following permission denied error from git:

```
git clone git@github.com:angr/angr-dev.git
Cloning into 'angr-dev'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by sraboy** [comment]
Looks like you haven't added your public key to your Github account. If you're using bash on Windows, don't forget that it's a separate key from what you might have generated for Windows Git. Otherwise, just clone HTTPS.

**Comment by sebastianwalla** [comment]
You were right, cloning via HTTPS worked. Probably the https link should be provided rather than the ssh link in the [install instructions](https://docs.angr.io/INSTALL.html) for angr.
