### ISSUE TITLE
CFGFast(): p.entry not part of CFG

### ISSUE THREAD

**Issue by ghost** [angr/angr#828]
I have malware sample here where CFGFast() does not include the code at the entry point, even when I feed it the addresses of all functions or all BBs.

https://www.dropbox.com/s/44cx3hplxhylagv/47_c610f0a41d57dad75fab2d405f59ec25?dl=0

(Malware sample, don't execute!)

**Comment by ltfish** [comment]
The file is not there... can you please share it again?

**Comment by manduc4** [comment]
Sorry,
https://www.dropbox.com/s/44cx3hplxhylagv/47_c610f0a41d57dad75fab2d405f59ec25?dl=0
