### ISSUE TITLE
Driller?

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#84]
Hi!
After reading your paper on Driller ( https://www.internetsociety.org/sites/default/files/blogs-media/driller-augmenting-fuzzing-through-selective-symbolic-execution.pdf ) I was curious to see if there were plans to release the tool as you have angr? I am very interested in seeing the results of a tool like this firsthand, especially in combination with angr.

**Comment by giovannivigna** [comment]
We might release after the CGC event in August.
We have not decided yet…

G

**Comment by ltfish** [comment]
Like Giovanni said, Driller will not be released before this August for CGC. However, most functionalities that Driller uses are already in angr anyways, and it should be straightforward to implement a "Driller for Linux binaries" or "Driller for Windows binaries" by yourself. Keep an eye on us after August!

**Comment by Manouchehri** [comment]
@Dinatrix Should be released any day.
