### ISSUE TITLE
angr Starter Code

### ISSUE THREAD

**Issue by Bennoli13** [angr/angr#846]
Hi guys, 

Sorry I'm new in here. Does anyone know what @project.hook(0x400844) and state.posix.dump_fd(0) do in angr example code? 
Is project.hook a pointer to the correct password and state.posix.dump_fd(0) to get the content of that memory address?

Here the full code :

```
import angr

project = angr.Project("angr-doc/examples/defcamp_r100/r100", auto_load_libs=False)

@project.hook(0x400844)
def print_flag(state):
    print "FLAG SHOULD BE:", state.posix.dump_fd(0)
    project.terminate_execution()

project.execute()
```

Thanks guys...

**Comment by ltfish** [comment]
`@project.hook`: http://angr.io/api-doc/angr.html#angr.project.Project.hook

`state.posix.dump_fd(0)` dumps the content of file related to file descriptor `0` (stdin).
