### ISSUE TITLE
Simulating a variable for a run of angr?

### ISSUE THREAD

**Issue by Dinatrix** [angr/angr#85]
Hi!
I realized in the rfid_reader binary I was having problems with, since angr keeps getting going down the badge length is too small path, is it possible to simulate the badge variable (with a correct length) when the angr script runs? If this simulated variable was the correct badge length angr may finally reach the authentication point I was previously trying to find.

I saw "self.state.memory.store" and "self.state.add_constraints" but I'm not entirely sure how to use them correctly in this context.

**Comment by ltfish** [comment]
The idea is simple: find the address of the variable of which you want to simulate in a state, and use `state.memory.store` to write the initial values there.

You can take a look at some examples, for example:

- https://github.com/angr/angr-doc/blob/master/examples/whitehatvn2015_re400/solve.py, line 50 - 58
- https://github.com/angr/angr-doc/blob/master/examples/ekopartyctf2015_rev100/solve.py, line 11 - 27
- https://github.com/angr/angr-doc/blob/master/examples/mma_simplehash/solve.py, line 91

**Comment by rhelmot** [comment]
Fish's answer is pretty comprehensive, but here's my ten-second version - angr has several types of values, and one of them is a "Symbolic Bitvector", or BVS. You can just plop one into memory or registers wherever you like and the symbolic execution engine will treat it like any value.

If this value is a null-terminated string and you'd like it to be a specific length, you can add constraints that the body bytes should be nonzero and the last byte should be zero.
