### ISSUE TITLE
CFGFast distance calculation problem for ARM

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/angr#857]
Hi Guys!

I have spotted that there is some problem with "distance" calculation in CFGFast._generate_cfgnode() method for ARM binaries. In the code here:

https://github.com/angr/angr/blob/4238162b6ebc76598275e0b4bd7347838af3cd79/angr/analyses/cfg/cfg_fast.py#L3306-L3333

Consider following disassembly:

```
.text:00016EE4             loc_16EE4                               ; CODE XREF: __udivmoddi4:loc_16E7Cj
.text:00016EE4 2E 46                       MOV             R6, R5
.text:00016EE6 A8 E6                       B               loc_16C3A
.text:00016EE6             ; End of function __udivmoddi4
.text:00016EE6
.text:00016EE6             ; .text         ends
.text:00016EE6
.fini:00016EE8             ; ===========================================================================
.fini:00016EE8
.fini:00016EE8             ; Segment type: Pure code
.fini:00016EE8                             AREA .fini, CODE
```

Distance for the block 0x16ee5 will be caluclated as 3, as it is in thumb mode and thus is addr+1. So this block will miss 1 instruction. And the successor block, with addr 0x16EE7, won't be processed at all, cause its size will be 1.

May be it will be right to substitute "addr" with "addr&(~1)" for ARM arch in the distance calculation snippet?

**Comment by ltfish** [comment]
You are absolutely right. PR welcome!

**Comment by ArtemShypotilov** [comment]
Fish,

Can you please advise what tests should be run for CFGFast? 

I would also like make some minor refactoring of CFGFast._generate_cfgnode().

**Comment by ltfish** [comment]
`test_cfgfast.py` and all test cases in `Patcherex`.

I'm not sure if we have a ARM CFG test case though.

**Comment by subwire** [comment]
Issue cleanup! This is solved
