### ISSUE TITLE
Recognize symbolic memory

### ISSUE THREAD

**Issue by andreafioraldi** [angr/angr#866]
Hi guys,
is `state.memory.load(addr, size).op != "BVV"` enough to know if the loaded memory is symbolic?
Thanks.

**Comment by zardus** [comment]
Not quite. The expression might be a non-leaf node, with a symbolic
variable further in the tree. You can just .symbolic to check all cases of
symbolicity.

**Comment by andreafioraldi** [comment]
Thanks for the quick reply 👍
