### ISSUE TITLE
Missing functions in project.kb.functions

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/angr#867]
Hi Guys!

I have been doing some analysis with angr recently, and spotted that there are some functions missing in project.kb.functions despite they had legit symbols.

I found out that this happens due to the sanity check missing for some special situation in CFGBase._process_irrational_functions().

The problem is as following.

Please consider code below from the shared library:

```
.text:0000BF3C ft_mem_free                            
.text:0000BF3C                                         
.text:0000BF3C                 CBZ             R1, locret_BF42
.text:0000BF3E                 LDR             R3, [R0,#8]
.text:0000BF40                 BX              R3
.text:0000BF42 ; ---------------------------------------------------------------------------
.text:0000BF42
.text:0000BF42 locret_BF42                            
.text:0000BF42                 BX              LR

...
.text:000108BC                 EXPORT FT_TrueTypeGX_Free
.text:000108BC FT_TrueTypeGX_Free
.text:000108BC                 CBZ             R0, locret_108C4
.text:000108BE                 LDR             R0, [R0,#0x64]
.text:000108C0                 B.W             ft_mem_free
.text:000108C4 ; ---------------------------------------------------------------------------
.text:000108C4
.text:000108C4 locret_108C4                            
.text:000108C4                 BX              LR
```

When function FT_TrueTypeGX_Free is processed in

https://github.com/angr/angr/blob/cace1c6d22362f329cd79ad940190e362dca7630/angr/analyses/cfg/cfg_base.py#L1507

main variables used will be set like:

```
startpoint_addr = 0x4108BD
max_unresolved_jump_addr = 0x40BF3D
endpoint_addr = 0x4108C9
```

As you can see **max_unresolved_jump_addr** is not between **startpoint_addr** and **endpoint_addr**. And the check here:

https://github.com/angr/angr/blob/cace1c6d22362f329cd79ad940190e362dca7630/angr/analyses/cfg/cfg_base.py#L1540-L1545

misses that fact.

So when we come to 

https://github.com/angr/angr/blob/cace1c6d22362f329cd79ad940190e362dca7630/angr/analyses/cfg/cfg_base.py#L1587-L1604

All functions between 0x40BF3D and 0x4108C9 that does not have call to them (shared library can have a lot of such functions) will be merged to FT_TrueTypeGX_Free.   

So can we please extend sanity check in CFGBase._process_irrational_functions() from:

```
if  max_unresolved_jump_addr >= endpoint_addr:
    continue
```
to

```
if  max_unresolved_jump_addr <= startpoint_addr or max_unresolved_jump_addr >= endpoint_addr:
    continue
```

?

Or maybe some modification can be made to the tail jump heuristics here:

https://github.com/angr/angr/blob/cace1c6d22362f329cd79ad940190e362dca7630/angr/analyses/cfg/cfg_base.py#L1546-L1583

?

**Comment by ArtemShypotilov** [comment]
Guys,

Please consider PR above. I've been using this fix for some time. It works fine for me.

**Comment by ltfish** [comment]
I'm aware of this PR, and I will look into it tonight. As of now, I don't see any problem off the top of my head. Thank you :-)
