### ISSUE TITLE
ARM registers

### ISSUE THREAD

**Issue by valour01** [angr/angr#873]
I noticed there are several other registers like `d0,d1,d2....` besides the arm core registers in the `arch_arm.py` I looked through the ARM V7 documentation. However, I failed to find what does these registers mean. 

Apart from this, I noticed that every register has an index. For example `r0` is `8` while `cc_op` is `72`. It seems all of the index could be divided by 4 and the gap is 4 or 8. I was wondering what the algorithm is and why you guys design in this way. Besides, what is the argument_registers?

The last but maybe the most important, I want to know if I want to add new registers like co-processor registers. Anything I need to pay attention? what index should I set for those registers? Many thanks.

**Comment by rhelmot** [comment]
The register file is not our design, it is copied from valgrind. [here](https://github.com/angr/vex/blob/master/pub/libvex_guest_arm.h) is the full description of the register file.

d0 etc are the VFP coprocessor registers.

argument_registers are all the registers that are used by common calling conventions for argument passing. I believe nothing uses it though.

For working with angr, you can add whatever you want to the end of the register file.

**Comment by valour01** [comment]
@rhelmot Thanks for your very quick reply. One more question, I think `cc_op,cc_dep1,cc_dep2,cc_ndep` are used to calculate 'N Z C V' these four flags. Could you please tell me how to calculate these four flags? Or 'cc_op' is 'N', 'cc_dep1' is `Z`, `cc_dep2` is `C` and `cc_ndep` is `V`

**Comment by ltfish** [comment]
You can take a look at [angr/engines/vex/ccall.py](https://github.com/angr/angr/blob/master/angr/engines/vex/ccall.py).

**Comment by rhelmot** [comment]
Actually, the explanation you are looking for is probably at the bottom of here: https://docs.angr.io/docs/ir.html
