### ISSUE TITLE
Add a better mechanism to store numerical state options

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#877]
Storing configuration values just related to normal emulation in the `libc` plugin is a huge hack. We should add someplace to store these values associated with the state directly, either by converting `state.options` to a dict instead of a set, or adding a `state.parameters`.

**Comment by ltfish** [comment]
I like `state.parameters`. We should make it configurable using YAML files or alike.

**Comment by zardus** [comment]
I agree. We should also think about some explicit namespacing support.

I guess the question is, which one of the following is better?

```
state.parameters.libc_heap_position = X
state.parameters.libc.heap_position = X
state.parameters.heap_position = X
```

**Comment by m1ghtym0** [comment]
That has similarities to the implementation of my project, which is a `StatePlugin` right now (configured via YAML files)

I guess for `heap_position` a flat namespace is fine, but I would support a deeper namespace, that IMO at least adds some explicit context and allows for duplicate names.
Therefore, I would prefer
`state.parameters.libc.heap_position = X` over `state.parameters.heap_position = X`

**Comment by rhelmot** [comment]
I think the thing you're describing is out of the scope of this proposal. This is supposed to be parameters that operate with the same scope as state options, controlling stuff that's built into angr. If stuff needs to be namespaced, then there can be a state plugin, or you can store in state.globals using a tuple as a key.

**Comment by zardus** [comment]
Ahhh, I see what you're saying. You're talking about stuff like the default maximum length for string-simprocedures, maybe the default maximum width of a symbolic read, etc?

**Comment by rhelmot** [comment]
Yes, this is targeted at stuff which is on the same scope as state options.
