### ISSUE TITLE
angr looks for Self modifying code even if not asked to.

### ISSUE THREAD

**Issue by canpadawan** [angr/angr#878]
When loading code through [_load_bytes](https://github.com/angr/angr/blob/master/angr/engines/vex/engine.py#L495) there is a test for self modyfing code. I think the intention was that if asked to consider self modifying code, there were additional sanity checks to be made before really looking for (are memory permissions ok?, ...).

But in the current implementation, the code ignores the value of `self._support_selfmodifying_code` and considers self modifying code whenever possible

```python
        smc = self._support_selfmodifying_code
        if state:
            try:
                p = state.memory.permissions(addr)
                if p.symbolic:
                    smc = True
                else:
                    smc = claripy.is_true(p & 2 != 0)
            except: # pylint: disable=bare-except
                smc = True # I don't know why this would ever happen, we checked this right?
```

I would be rather expecting a test like 
```python
        smc = self._support_selfmodifying_code
        if smc and state:
            try:
                p = state.memory.permissions(addr)
                if p.symbolic:
                    smc = True
                else:
                    smc = claripy.is_true(p & 2 != 0)
            except: # pylint: disable=bare-except
                smc = True # I don't know why this would ever happen, we checked this right?
```

**Comment by rhelmot** [comment]
because I'm psychic and your next question is probably going to be "well why is it named like that" the answer is that it used to be different and act more like you were describing but we added the extra behavior described above to make simple kinds of self modifying code work without extra analyst input.
