### ISSUE TITLE
AttributeError: 'ExternObject' object has no attribute 'tls_block_offset'

### ISSUE THREAD

**Issue by abarbaro** [angr/angr#886]
Hi all,
I'm running the latest version of angr:
```
✗ pip show angr                                                 
Name: angr
Version: 7.8.2.21
Summary: A multi-architecture binary analysis toolkit, with the ability to perform dynamic symbolic execution and various static analyses on binaries
```

The problem is that with ```project = angr.Project(filename, load_options={'skip_libs': ['libc.so.6'], 'auto_load_libs': True})``` I have the following error: ```AttributeError: 'ExternObject' object has no attribute 'tls_block_offset'``` I think something similar was fixed in the past. 

Should I use the most recent version cloning the repo?

UPDATE: Also with the latest version from the repo I have the same error. :(

Thanks

**Comment by rhelmot** [comment]
You already reported this issue! https://github.com/angr/angr/issues/693

I still have no idea what to do about it...
