### ISSUE TITLE
Exception running data dependency analysis

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr#9]
I'm trying to run the data dependency analysis. I've tried following code:

```
>>> import angr
>>> proj = angr.Project('/bin/ls')
>>> cfg = proj.analyses.CFG(keep_input_state=True)
>>> ddg = proj.analyses.DDG(cfg)
```

I get the following exception: `SimProcedureError: Tried to run simproc continuation with empty stack`

**Comment by rhelmot** [comment]
This is a duplicate of #7
