### ISSUE TITLE
readdir support

### ISSUE THREAD

**Issue by h1994st** [angr/angr#905]
Hi all,

Why does `readdir` only support `AMD64`?

> readdir SimProcedure is only implemented for AMD64

I'm just new to angr. May I know how to extend the support to other architecture support?

Thanks!

**Comment by ltfish** [comment]
Because we only cared enough to implement it for AMD64 :)

To port it to other architectures, you want to take a look at how the `dir` struct is defined on other arches, and then implement `_build_xxx()` and `_store_xxx()` in the same class.

**Comment by ltfish** [comment]
You probably want to use `SimType` and `SimStruct` to achieve that, instead of doing it in the hackish way as we were doing in `_build_amd64()`.

**Comment by h1994st** [comment]
@ltfish I see. Thanks for your help!
