### ISSUE TITLE
Rethink/rework caching

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#921]
idk if anyone has noticed but when Tracer was refactored, its caching system was reimplemented as an exploration technique, and this does not actually work (has never worked?) for whatever reason.

Here are some questions to consider in approaching the goal of "at-receive caching", i.e. keeping around a serialized copy of the last state before it hits a syscall introducing tainted data from the environment:

- states are no longer project agnostic, which means that a state must be stored in conjunction with a project (this can't be hacked around because the state can actually mutate the project in an append-only fashion, e.g. simprocedure continuation address allocation or dynamic library loading). a good idea that tyb and I came up with together is to establish an arbitrary key/value store on the project (currently `project.storage`, which is... a defaultdict(list)? idk what's up here) and then pickle/unpickle the entire project, sort of as a first step in setting up the workflows for an angr project file format. Unfortunately, these workflows were NOT established, and currently the implementation (which doesn't actually uncache anything, remember) attempts to load the entire project from within an exploration technique from ANOTHER project, then reattaches the state from the old project to the new project. It's a mess. We really do need to refactor for a project-file based workflow.
- The cacher as an exploration technique doesn't really make sense, especially considering the design direction being established by the wip/new_files refactor. The design change is that instead of hacking on files however you like, there are now lots of well defined interfaces for initializing your state with the files you want to use for your analysis! This _totally_ does not fly with any sort of system for caching which tries to transparently intercept analysis and replace the entry state with the state from the last time you were running an analysis. My proposed solution to this is to replace the cacher with a `AtReceiveCacheAnalysis`, so you can explicitly opt into using the cache and specify the kinds of data taints you want to consider as input, to know what cache to load from and how to compute the cached state.

**Comment by rhelmot** [comment]
oh, context: I have to rip out the broken cacher in order to get wip/new_files to land. The point of the last bit is that e.g. the preconstrainer should run _after_ the cache load. This was accomplished by hardcoding the preconstrainer to rerun after cache loading, but this makes the entire design of the preconstrainer so tightly interwound with our stuff that it becomes useless for anything else.

**Comment by zwimer** [comment]
@rhelmot Please add some update to this.

**Comment by rhelmot** [comment]
The notion of at-receive caching has not been needed in the past four years, and I see nothing in the future which will necessitate its return.
