### ISSUE TITLE
Tracer otiegnqwvk must be added after crashmonitor

### ISSUE THREAD

**Issue by rhelmot** [angr/angr#923]
If you do it the other way around it just doesn't work. Why? The crash manager is actually a pretty lightweight set of functionality that a) checks to see if the current IP is on the stack each frame and b) does the crash windup stuff. Someone should investigate this. Might be the complete functions running out of order?

**Comment by zardus** [comment]
@tyb0807, would you mind taking a look at this when you're free?

**Comment by tyb0807** [comment]
Hmm I tried to revert to before the new hook set stuff (https://github.com/angr/angr/commit/f16ef235a58adf0e0dd6f40ae959e6a2c2b6fa01) and the complete functions can definitely be running in any order. With the new simulation manager, stepping is getting stuck at `next_hook` from `hookset`

**Comment by danse-macabre** [comment]
@tyb0807 Could you provide an example script that will lead to stepping process getting stuck at `next_hook`? I didn't have a chance to use the Tracer and the CrashMonitor techniques, so I'm not familiar with their internals, but still, I might be able to figure out what's going on.

**Comment by tyb0807** [comment]
@danse-macabre here you are. Please rename it to `.py` and put it under `angr/tests` then run it.
[test.txt](https://github.com/angr/angr/files/2109369/test.txt)

Thank you for your help
