### ISSUE TITLE
CFGAccurate.remove_cycles() function never removes any cycles

### ISSUE THREAD

**Issue by Wajihulhassan** [angr/angr#940]
Function CFGAccurate.remove_cycles() does not remove any cycles from CFG because of type mismatch. 
`cfg._loop_back_edges` returns edges with `Blocknode` types while the `cfg._graph` has `CFGnode` type. 

The `if self._graph.has_edge(b1, b2):` condition inside the function never becomes true even if the edge is present in the graph. So the loop back edge never gets removed from the graph

**Comment by ltfish** [comment]
Thanks for reporting. Apparently that method has been bitrotten for quite a while.

If anyone wants to fix it before I find some time for this bug, please go ahead!

**Comment by ltfish** [comment]
`cfg.get_any_node(addr)` should give you the `CFGNode` w.r.t. the given address. This is without considering context-sensitivity.

**Comment by SujayYadalam94** [comment]
I was facing the same issue. I wrote a wrapper around the remove_cycles() function which used get_any_node() to convert the BlockNode to CFGNode:

```
def graph_remove_cycles(cfg):
    cfg.remove_cycles() # Can also use _detect_loops()
    for b1, b2 in cfg._loop_back_edges:
        b1 = cfg.get_any_node(addr=b1.addr)
        b2 = cfg.get_any_node(addr=b2.addr)
        if cfg.graph.has_edge(b1, b2):
            cfg.graph.remove_edge(b1, b2)
```
