### ISSUE TITLE
pygit is unmaintained and should be replaced

### ISSUE THREAD

**Issue by afaerber** [angr/angr#948]
angr has a dependency on [pygit](https://pypi.python.org/pypi/pygit/0.1) in requirements.txt and setup.py. Version 0.1 is the latest version, from 2008, raising concerns about Python 3.x compatibility and Git evolution.

Pull #946 thus attempted to replace pygit with the actively maintained [pygit2](https://pypi.python.org/pypi/pygit2/0.27.0), which has a 2018 version. This causes failures in your CI due to involving a C library libgit2. @rhelmot would like to avoid that.

**Comment by rhelmot** [comment]
If you’re really really set on pygit2 specifically as the replacement for
pygit, submit a PR to the angr-dev repo adding the native dep to setup.sh
in the list of all the OS packages for each of the supported package
managers. iirc this is just apt and pacman.
