### ISSUE TITLE
Symbolic rounding mode

### ISSUE THREAD

**Issue by valour01** [angr/angr#956]
Hi, I noticed that when I use the angr to analysis some coreutils tool, some debugging information will print indicating the symbolic rounding mode

`WARNING | 2018-04-19 16:00:19,081 | angr.engines.vex.irop | symbolic rounding mode found, using default`

May I know what `symbolic rounding mode` is and what is the default strategy

**Comment by ltfish** [comment]
This might be a good starting point for you to read: https://github.com/angr/angr/issues/785.

**Comment by valour01** [comment]
Thanks @ltfish . I will read it immediately.

BTW: I just wondering... whether you can give me some comments on these two issues [#920](https://github.com/angr/angr/issues/920) and [#915] (https://github.com/angr/angr/issues/915). Thank angr team so much!

**Comment by rhelmot** [comment]
Short answer: floating point operations require an input that is a rounding mode, as described in the issue that fish linked. When this value is symbolic, we absolutely cannot compute with it. The logic for doing that soundly would be astronomically complex. Instead, we just fall back to the default, which is I believe configurable but the default default is RTN (round-to-nearest).
