### ISSUE TITLE
How can I get the end address of the specified function through angr?

### ISSUE THREAD

**Issue by buptsseGJ** [angr/angr#957]
For example, for a function with the following instructions:
```
.text:080483D0 __do_global_dtors_aux proc near
.text:080483D0                 cmp     ds:__bss_start, 0
.text:080483D7                 jnz     short locret_80483EC
.text:080483D9                 push    ebp
.text:080483DA                 mov     ebp, esp
.text:080483DC                 sub     esp, 8
.text:080483DF                 call    deregister_tm_clones
.text:080483E4                 mov     ds:__bss_start, 1
.text:080483EB                 leave
.text:080483EC
.text:080483EC locret_80483EC:                         ; CODE XREF: __do_global_dtors_aux+7j
.text:080483EC                 rep retn
```
The start address of function `__do_global_dtors_aux` is 0x80483D0, and the end address of it 0x80483EC.
I can get the start address through `for addr, func in cfg.kb.functions.iteritems()`, 
but **how can I get the end address of the specified function?**
Thanks!

**Comment by ltfish** [comment]
Iterate through all blocks in that function and get the maximum end address of all blocks.

**Comment by buptsseGJ** [comment]
ok，I solve that through `"block.instruction_addrs"`.
Thank you very much!

**Comment by ltfish** [comment]
How did you get the size of the last instruction of a block?

The end address (not the address of the last instruction) of a block should be the address of that block plus the size of the block.

**Comment by buptsseGJ** [comment]
I see what you mean. 
I get the control flow graph of a function using CFGFast.  But the CFG may contain the start address of a called function. So I want to ignore such an address and only preserve the edges within the current analyzed function. As a result, I don't need to know the accurate end address.  The address of the last instruction works well. I don't know how to get the size of the last instruction of a block.

**Comment by ltfish** [comment]
> So I want to ignore such an address and only preserve the edges within the current analyzed function.

You can also use `cfg.functions[func_addr].graph`, which should only contain nodes of the function that you are interested in.
