### ISSUE TITLE
How to Hook correctly?

### ISSUE THREAD

**Issue by phros** [angr/angr#96]
Hi, I'm trying trying to execute a single block and hook one address inside this block with the following code. Nothing happens and I guess that I have a conceptual misunderstanding here. Can anybody help me?

```
b = angr.Project( "mylib.so")

def hook(state):
	print "Hooked!!! Yes!"

myBlockAddr = 0x400EAE

state = b.factory.blank_state( addr=myBlockAddr )
b.hook(myBlockAddr+4, hook, length=5)

p = b.factory.path(state)
p.step()
```

**Comment by rhelmot** [comment]
Almost there!! when you say p.step(), it steps one basic block forward, but that basic block has been truncated, since you hooked in the middle of it.

If you get the step result and step it again, then _that_ will run the hook.

**Comment by phros** [comment]
Oh man, Thanks!
