### ISSUE TITLE
Conflict between successors and predecessors

### ISSUE THREAD

**Issue by valour01** [angr/angr#960]
I use this [test.zip](https://github.com/angr/angr/files/1935817/test.zip) and apply the CFGAccurate algorithm on it.

However, I noticed the following result
```
In [10]: cfg.get_predecessors(cfg.get_any_node(0x8454))
Out[10]: [<CFGNode test 0x840c[36]>]

In [11]: cfg.get_predecessors(cfg.get_any_node(0x8468))
Out[11]: [<CFGNode test 0x840c[36]>]

In [12]: cfg.get_predecessors(cfg.get_any_node(0x8440))
Out[12]: [<CFGNode test 0x840c[36]>]

In [14]: cfg.get_successors(cfg.get_any_node(0x840c))
Out[14]: [<CFGNode case2+0x10 0x8454[4]>]

```

Angr told me that `node(0x840c)` has only one successor and it is `node(0x8454)`. However, `node(0x8454)`, `node(0x8468)` and `node(0x8440)`'s predecessors are all `node(0x840c)`.

Is this a bug, or I misunderstood the definition on the `successors` and `predecessors`

**Comment by ltfish** [comment]
There might be more than one nodes at 0x840c.

**Comment by valour01** [comment]
@ltfish Thanks for your suggestions. However, angr just return back one node to me
```
In [7]: cfg.get_any_node(0x840c)
Out[7]: <CFGNode test 0x840c[36]>

```

Besides, It seems that it is because of multiple states that we have more than one node at 0x840c. If so, any options to disable this?

**Comment by ltfish** [comment]
Try `cfg.get_all_nodes(0x840c)`.

You can disable it by setting the context sensitivity level of CFGAccurate to `0`.
