### ISSUE TITLE
Issues with importing angr in PyCharm on MacOS

### ISSUE THREAD

**Issue by awskkzl** [angr/angr#965]
When I use python in Terminal, it told me  #234 

```
>  failed loading "angr_native.dylib", unicorn support disabled (dlopen(/Users/mark/Envs/angr/lib/python2.7/site-packages/angr/lib/angr_native.dylib, 6): Library not loaded: Envs/angr/lib/python2.7/site-packages/unicorn/lib/libunicorn.dylib
>   Referenced from: /Users/mark/Envs/angr/lib/python2.7/site-packages/angr/lib/angr_native.dylib
>   Reason: image not found: dlopen(/Users/mark/Envs/angr/lib/python2.7/site-packages/angr/lib/angr_native.dylib, 6): Library not loaded: Envs/angr/lib/python2.7/site-packages/unicorn/lib/libunicorn.dylib
>   Referenced from: /Users/mark/Envs/angr/lib/python2.7/site-packages/angr/lib/angr_native.dylib
>   Reason: image not found)
```

I solved this problem by relink the dylib:

```
> install_name_tool -change libunicorn.1.dylib "$BASEDIR"/unicorn/lib/libunicorn.dylib "$BASEDIR"/angr/lib/angr_native.dylib
```

Then everything goes fine in Terminal. But when I import angr in a PyCharm project, I meet the same situation... It seems to be that the relink didn't work in PyCharm. I'm new to binary analyses, can anyone help me to solve this problem? My OS is High Sierra with python 2.7.10 in virtual environment.

**Comment by ltfish** [comment]
Did you set up the Python interpreter correctly in PyCharm? You should use the interpreter inside your virtualenv.

**Comment by awskkzl** [comment]
Thanks, Itfish! I think so... 

> file:///Users/mark/Envs/angr/lib/python2.7
> file:///Users/mark/Envs/angr/lib/python2.7/lib-dynload
> file:///System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
> file:///System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
> file:///System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
> file:///System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
> file:///System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
> file:///Users/mark/Envs/angr/lib/python2.7/site-packages
> jar:///Users/mark/Envs/angr/lib/python2.7/site-packages/unicorn-1.0.1-py2.7.egg!/
> jar:///Users/mark/Envs/angr/lib/python2.7/site-packages/simuvex-7.7.9.8-py2.7.egg!/
> jar:///Users/mark/Envs/angr/lib/python2.7/site-packages/capstone-3.0.5rc3-py2.7.egg!/

/Users/mark/Envs is the folder of virtual environment.

**Comment by awskkzl** [comment]
Haha, yea you are right. Actually I don't know what unicorn-engine do... I don't know whether it will be an important part of my following work. Maybe I should read more about your documents. 
Thanks man!

**Comment by ltfish** [comment]
You are welcome. I still don't understand why unicorn-engine fails to load in PyCharm's terminal. You may deal with that problem later when it becomes a real problem...

angr is totally functioning without the unicorn-engine.
