### ISSUE TITLE
hang with simple elf

### ISSUE THREAD

**Issue by Kyle-Kyle** [angr/angr#966]
Here is the decompiled code of my ELF.
~~~~~
v4 = argv[1][3]
     + argv[1][1]
     + argv[1][3]
     + (argv[1][4]
      + argv[1][7]
      + argv[1][6]
      + argv[1][3]
      + argv[1][1]
      + *argv[1]
      - argv[1][2]
      - argv[1][4]
      - argv[1][5]
      - argv[1][1])
     * argv[1][4]
     - *argv[1]
     - argv[1][5];
  printf("%d\n", v4, argv);
  if ( v4 == 25910 )
  {
    puts("You pass this one, the secret is {The flag is masked in hint binary}");
    result = 0;
  }
  else
  {
    puts("fails");
~~~~~
It is super simple and I expected it to be solved within 10 seconds. However, with the newest angr(master branch), it simply hangs and after a long~~~~ time like 10 minutes, it says no found.
I felt strange and then ran `git reset --hard HEAD~100`.  All problems solved.
If you want, I can provide the ELF.

**Comment by Kyle-Kyle** [comment]
I enabled logging. And the log indicates `angr` did hang.

**Comment by Kyle-Kyle** [comment]
Sorry about that. It seems the problem has been solved yesterday.

**Comment by ltfish** [comment]
Can you please post the log and the binary file?

**Comment by Kyle-Kyle** [comment]
https://gist.github.com/Kyle-Kyle/bced4a044b9a40717fa1bfe0ca5a5bdb
I have no luck so far to reproduce the successful case. So I suspect I was confused by two different ELFs. I was doing an simple automated reversing problem. Maybe the one takes too long to fail really has no solution.

**Comment by Kyle-Kyle** [comment]
BTW, could you please tell me why the new code cannot generate correct logging information?
Is it because the name has been changed? Or I write anything wrong?

**Comment by ltfish** [comment]
> could you please tell me why the new code cannot generate correct logging information?

`SimulationManger` is refactored and the logging code was removed (or moved elsewhere, which I lost track of).

**Comment by rhelmot** [comment]
I added the logging back just now. Idk why it was removed.

**Comment by Kyle-Kyle** [comment]
@ltfish Hi Fish, I have reproduced the problem I mentioned. All the updates are in the gist. The correct code I expect `angr` to produce is `fx5vHlCg`. But it just tells me no found.

**Comment by Kyle-Kyle** [comment]
@rhelmot Hi Audrey, could you please double check with the logging module? I have no luck to produce correct logging information. The output I received is in the gist https://gist.github.com/Kyle-Kyle/bced4a044b9a40717fa1bfe0ca5a5bdb. And the result of `git log` is as follow:
~~~~
dumbass@parallels-vm:~/Desktop/src/angr-dev/angr git log
commit 538caf7840bae7fde315f437ddb866762e452601
Author: Audrey Dutcher <audrey@rhelmot.io>
Date:   Tue Apr 24 16:01:05 2018 -0700

    ...oops

commit 69cbc54d8c775237239dfe50355fb3634a8d2825
Author: Audrey Dutcher <audrey@rhelmot.io>
Date:   Tue Apr 24 15:03:42 2018 -0700

    Polish simulation manger, fix docstrings

commit f0404584a94d004e463639acc1a2185b1d38a139
Author: Audrey Dutcher <audrey@rhelmot.io>
Date:   Tue Apr 24 14:17:52 2018 -0700

    Added the most important simgr logging back... idk why danse removed all of them

commit 94f07a482564be0d96b14524f56b5a5b0343852e
~~~~

**Comment by Kyle-Kyle** [comment]
@rhelmot the Problem is introduced in https://github.com/angr/angr/commit/ffa109dd53ad2285a95109cf249396c5b32714a1 after my binary search...

**Comment by rhelmot** [comment]
Yes, that's the commit I'd expect...

I somehow got the impression from this thread that it was strictly a logging issue. I'll investigate the behavioral changes.

**Comment by rhelmot** [comment]
Actually, yes, can you provide the ELF and a minimal script to reproduce the bug?

**Comment by rhelmot** [comment]
Oh they're all in the gist! Never mind

**Comment by Kyle-Kyle** [comment]
@rhelmot do you mean you can get 1 found with the newest version? I always get 1 avoided with no matter what version.

**Comment by rhelmot** [comment]
I always get 1 avoided regardless of version. That's what I was trying to communicate. The only difference is the name of the logger.

Are there any real bugs you'd like me to look into?

**Comment by Kyle-Kyle** [comment]
@rhelmot I guess some overflow constraints are not well recorded. That's why no answer can be correctly generated for this ELF. But the script does generate answers for other ELFs.

**Comment by Kyle-Kyle** [comment]
@rhelmot 
Sorry for being stupid. There is something wrong with my script.
