### ISSUE TITLE
srand and rand simprocs always return BVS

### ISSUE THREAD

**Issue by toshipiazza** [angr/angr#972]
[Here](https://github.com/angr/angr/blob/master/angr/procedures/libc/rand.py#L5) it looks like `rand` is returning a symbolic variable, regardless of whether `srand` got a concrete or a symbolic seed (`srand` is just a nop). Seems like a hassle to emulate `rand` behaviour precisely between Linux and Windows and all varieties of arches but it would be helpful :)

**Comment by rhelmot** [comment]
Yeah I looked into how to emulate the glibc rand for concrete seeds at some
point but even that was way too much :(

**Comment by zwimer** [comment]
If you want your rand to return a concrete value, just reimplement the simproc.
