### ISSUE TITLE
Dockerfile Image ID

### ISSUE THREAD

**Issue by prashast** [angr/angr#974]
I pulled the docker file and the Image ID is `mystifying_banach` instead of the expected
`angr`. Would save a couple of minutes if the Image ID is renamed as `angr` again. :)

**Comment by rhelmot** [comment]
I'm not sure what you're talking about. we provide a dockerfile, you can build it as whatever you like. We also distribute a built version for you through docker.io/angr/angr, which you get when you say `docker pull angr/angr`. This will be available as angr/angr, and when you run it you will get a container instance with a name like that, or you can specify your own. This has always been the case.

**Comment by prashast** [comment]
I'd run the commands given in the docs as is without any modifications on my end:
```
sudo docker pull angr/angr
sudo docker run -it angr/angr
```
However, the ID name for the container showed it to be `mystifying_banach` instead of `angr`
```
number_three@number-three:~/$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
ebe2690b476e        angr/angr           "/bin/sh -c 'su - ..."   25 minutes ago      Up 25 minutes                           mystifying_banach
```
Anyway, it is a minor thing. I'll close it on my end.

**Comment by rhelmot** [comment]
Yeah, I don't think that's ever had any different behavior...

**Comment by zardus** [comment]
Docker generates random names (unless one is specified with the --name
option) for each container. The *image* is, and has always been, named
angr/angr, but if you want the container to be named something specific,
you need to use --name. That's just how docker works.

To see it generate a new name, just try to make a new container. It'll be
something else randomly-generated.

**Comment by prashast** [comment]
Aah my bad. I derped. Thanks for clarifying.
