### ISSUE TITLE
AttributeError: 'ELF/PE' object has no attribute 'engine_preset'

### ISSUE THREAD

**Issue by MostafaSoliman** [angr/angr#977]
Hello, I have just installed angr to start using it, i installed it on both Linux and Windows 7. When i try to test it in both i always get the attached errors. what i am missing.
![linux](https://user-images.githubusercontent.com/13528184/39675583-623ec95c-515d-11e8-80cd-861807cae3ce.JPG)
![windows](https://user-images.githubusercontent.com/13528184/39675584-626adbdc-515d-11e8-8c11-ea89ac987114.JPG)

**Comment by rhelmot** [comment]
Your version of CLE is older than your version of angr. I’m guessing you
cloned angr directly and just ran python setup.py install? Don’t do that,
you either want to just use pip install angr directly or download and
install each of archinfo pyvex claripy cle angr. The angr/angr-dev repo
helps with that.

**Comment by MostafaSoliman** [comment]
Thank you for your fast replay, the issue is solved by 
`pip uninstall angr`
`pip install angr`
