### ISSUE TITLE
Simple SimFile for program to read and print

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#978]
Hello,

I am trying to use angr to provide a file for a very simple program to read its input and print it to the stdout.

My program:
```
#include <stdio.h>
#include <stdlib.h> // For exit()

const char * filename = "test";

int main()
{

	FILE *fptr;

	char c;

	// Open file
	fptr = fopen(filename, "r");
	if (fptr == NULL)
	{
		printf("Cannot open file \n");
		exit(0);
	}

	// Read contents from file
	c = fgetc(fptr);
	while (c != EOF)
	{
		printf("%c", c);
		c = fgetc(fptr);
	}

	fclose(fptr);
	return 0;
}
```

I am trying to set the test file for the program in this way:
```
p = angr.Project(r"C:\Users\Mor\Desktop\readfile.elf", load_options={'auto_load_libs': False})
simfile = angr.storage.file.SimFile('test', "rw")
state = p.factory.entry_state()
state.posix.fs['test'] = simfile

simfile.set_state(state)
simfile.write("\x41\x42\x43\x44", 4)

sm = p.factory.simgr(state)

def correct(state):
	try:
		print state.posix.dumps(1)
	except:
		return False

sm.explore(find=correct)
```

It looks for test file and print its content.

it should run through the program and print every stdout it can (print empty if nothing outputs at the current state)

It should print ABCD (for the file content), or at least "Cannot open file" if it didn't found the file but it doesn't print anything.
I tried to go state by state and it always go the file printing (never to the can't find file part) but even though I go over the printf functions it doesn't output to the stdout stream.

I compile this program as x86 ELF file (on linux), I also tried simple program that only prints some text and it does output the file print to the stdout stream.

* I know there are changes to the file system happening right now but the master currently does not work and I am working on the pip version on windows (seems to be version 7.8.2.21)

**Comment by rhelmot** [comment]
fwiw "master does not work" is totally a lie. this script works on master:

```python
import angr                       
import logging                    
#logging.getLogger('angr.manager').setLevel('DEBUG')                

p = angr.Project('test')          
simfile = angr.storage.file.SimFile('test', "ABCD")                 
state = p.factory.entry_state(fs={'test': simfile})                 

sm = p.factory.simgr(state)       

def correct(state):               
        try:                      
                print state.posix.dumps(1)                          
        except:                   
                return False      

sm.explore(find=correct)
```

(there was an issue that you had to specify `/home/user/test` instead of just `test` but that was supposed to be a feature not a bug; I just decided now that it was a terrible feature and changed it)

**Comment by mor619dx** [comment]
I haven't tried to run the script in the master version, I just had errors when I was starting new project with:
```
angr.Project('test')  
```

I will try again later, thank you for your help!
