### ISSUE TITLE
Question: Tainting / Tracking variables or memory

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#979]
Hello,

I've search for the feature of tracking variables or memory, I saw the backward slice analyses which allow me to see the flow from a certain point but I it doesn't seems to be able to track down some memory or variables.

For example if I want to track down some argv variable or track buffer return from the recv function.
Is this kind of feature exist? If not what does it take to implement it?

**Comment by ltfish** [comment]
Do you want to do so during symbolic execution or static analysis?

**Comment by mor619dx** [comment]
I am looking more for static analysis but I would be happy to hear both options.

**Comment by ltfish** [comment]
Take a look at the [`ReachingDefinitionAnalysis`](https://github.com/angr/angr/blob/wip/nightmaRE/angr/analyses/reaching_definitions/reaching_definitions.py).

**Comment by ltfish** [comment]
Also, DDG on the master branch should also be useful for you in many cases.

**Comment by mor619dx** [comment]
Can you write what is the difference between ReachingDefinitionAnalysis and DDG?

I haven't seen a lot of documentation on ReachingDefinitionAnalysis, can you explain what it does / how to use it?

**Comment by mor619dx** [comment]
Alright it seems to work pretty good with DDG.

Is it possible to taint not only register but also memory address? for example if I set argv parameters and got their addresses (in the stack) I haven't able to taint that memory address. (ddg_obj.view) doesn't contain that address.

Is there a workaround to track argv parameters / some memory address?

**Comment by ltfish** [comment]
> Is there a workaround to track argv parameters / some memory address?

It should track memory accesses. If not, it must be a bug.
