### ISSUE TITLE
angr seems to be stucked in a library function

### ISSUE THREAD

**Issue by brokendragon** [angr/angr#98]
I run angr to test the following code
# include <stdio.h>
# include <string.h>

void test(char *buff)
{
  char buff1[4]={0};
  strcpy(buff1, buff);
  if(buff[0] == buff[1]) printf("first two bytes are equal!\n");
  else printf("first two bytes are not equal!\n");
}

void main()
{
  char buff[4] = {0};
  test(buff);
}
with the following commands

> > > import angr
> > > b = angr.Project('/home/ct/angr-dev/ct-test/external', load_options={'auto_load_libs': False})
> > > cfg = b.analyses.CFG(keep_state=True)
> > > target_func = cfg.kb.functions.function(name="test")
> > > print target_func
> > > Function test [0x4005f6]
> > >   Syscall: False
> > >   SP difference: 0
> > >   Has return: True
> > >   Returning: True
> > >   Arguments: reg: [72], stack: [9799832789158264984L, 8L, 9L, 0L]
> > >   Blocks: [0x400641, 0x40064b, 0x400667, 0x40062b, 0x40066c, 0x40064d, 0x4005f6, 0x400657]
> > >   Calling convention: System V AMD64 - AMD64 [<rdi>, [8800000000010098h], [8h], [9h]]
> > > p = b.factory.path()
> > > c = b.surveyors.Caller(0x4005f6, start=p)
> > > print tuple(c.iter_returns())

The results is
WARNING | 2016-04-28 11:22:54,653 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse((if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 24)) then 0 else mem_0_18_1024[199:192]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 25)) then 5 else mem_0_18_1024[207:200]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 26)) then 64 else mem_0_18_1024[215:208]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 27)) then 0 else mem_0_18_1024[223:216]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 28)) then 0 else mem_0_18_1024[231:224]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 29)) then 0 else mem_0_18_1024[239:232]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 30)) then 0 else mem_0_18_1024[247:240]) .. (if (((0x1 + (if <...> then <...> else <...>)) + (0xffffffffffffffff \* reg_48_16_64))[63:5] == 0x0) then 0 else mem_0_18_1024[255:248]))>
WARNING | 2016-04-28 11:23:01,513 | simuvex.s_run | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV64 Reverse((if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 24)) then 0 else mem_0_18_1024[199:192]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 25)) then 5 else mem_0_18_1024[207:200]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 26)) then 64 else mem_0_18_1024[215:208]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 27)) then 0 else mem_0_18_1024[223:216]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 28)) then 0 else mem_0_18_1024[231:224]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 29)) then 0 else mem_0_18_1024[239:232]) .. (if ((((<...> + <...>) + (<...> \* <...>))[63:5] == 0x0) && (((1 + (if <...> then <...> else <...>)) + (31 \* <...>[4:0])) <= 30)) then 0 else mem_0_18_1024[247:240]) .. (if (((0x1 + (if <...> then <...> else <...>)) + (0xffffffffffffffff \* reg_48_16_64))[63:5] == 0x0) then 0 else mem_0_18_1024[255:248]))>
()

> > > print c
> > > <Explorer with paths: 0 active, 0 spilled, 2 deadended, 0 errored, 2 unconstrained, 0 found, 0 avoided, 0 deviating, 0 looping, 0 lost>

It seems that angr gets stuck into memcpy and just find 2 unsatisfied paths and 2 unconstrained path. But it failed to find the two feasible paths in test.

How to direct angr to circumvent library code or any code I am not interested in? Or do I type wrong commands?

Thanks

**Comment by brokendragon** [comment]
The results after using the command print c is
<Explorer with paths: 0 active, 0 spilled, 2 deadended, 0 errored, 2 unconstrained, 0 found, 0 avoided, 0 deviating, 0 looping, 0 lost>

**Comment by rhelmot** [comment]
I forget exactly how to do this with a surveyor, but if you can pull the path out of the Caller object, you can look at its `trace` property (`print list(path.trace)`) to see what blocks its run through. That'll let you know if it's actually stuck in libc.

It shouldn't, though, since we have SimProcedures for strcpy and printf. I'd imagine that the problem is really that you haven't set up the arguments to that function, so you get a dereference on an unconstrained symbolic variable and things go to shit.

Can I ask where you were told to use Caller? Honestly that interface is ancient and I can't remember how it works. You might want to use Callable instead, which you can get through the `project.factory` object. That should allow you to provide args more easily. I really should write up better docs for using it, though.

**Comment by brokendragon** [comment]
@rhelmot 
I want to explore all feasible paths in test, while avoiding the paths in strcpy. So I choose caller. How can the callable object helps me to fulfill the goal?

**Comment by rhelmot** [comment]
Actually now that I look more carefully, you've already specified `auto_load_libs=False`, so it's impossible that you've got excess paths in strcpy.

I'll need to look more closely at the interfaces available to figure out what the best way to do this is. I might add some new interfaces for you.

In the meantime, the bottom line is that **it's not working because the argument to test is uninitialized, so it's a symbolic variable. It needs to be a concrete pointer to a buffer full of symbolic data.** Callable can do that for you, but it doesn't have a good interface for getting all the paths out in the end. I can't remember if Caller has any interface for setting up function arguments, but if not you just need to set the argument yourself, in the initial state.

**Comment by brokendragon** [comment]
@rhelmot 
I think you are right that I did not supply proper parameters. Then I just circumvent setting parameters by testing the modified source
`int test(char a, char b)
{
  char buff1[3]={0};
  char buff[3] = {0};
  buff[0] = a;
  buff[1] = b;
  strcpy(buff1, buff);
  printf("buff[0] = %c, buff[1] = %c\n", buff[0], buff[1]);
  printf("buff1[0] = %c, buff1[1] = %c\n", buff1[0], buff1[1]);
  if(buff1[0] == buff1[1]) {printf("first two bytes are equal!\n"); return 0;}
  else {printf("first two bytes are not equal!\n"); return 1;}
}

void main()
{
  char buff[4] = {0};
  char a = 60, b = 62;
  test(a, b);
}`

The commands and testing result is
`>>> b = angr.Project('/home/ct/angr-dev/ct-test/external', load_options={'auto_load_libs': False})
>>> cfg = b.analyses.CFG(keep_state=True)
>>> target_func = cfg.kb.functions.function(name="test")
>>> print target_func
Function test [0x40063d]
  Syscall: False
  SP difference: 0
  Has return: True
  Returning: True
  Arguments: reg: [72, 64], stack: [9799832789158265000L, 0L]
  Blocks: [0x4006fd, 0x4006e7, 0x40070c, 0x4006ee, 0x4006dd, 0x4006d1, 0x4006b2, 0x400693, 0x4006f8, 0x400711, 0x40063d]
  Calling convention: System V AMD64 - AMD64 [<rdi>, <rsi>, [88000000000100a8h]]
>>> p = b.factory.path()
>>> c = b.surveyors.Caller(0x40063d, start=p)
>>> print tuple(c.iter_returns())((<BV64 0x1>, <Path with 15 runs (at 0x400540)>), (<BV64 0x0>, <Path with 16 runs (at 0x400540)>))
>>> print c
<Explorer with paths: 0 active, 0 spilled, 0 deadended, 0 errored, 0 unconstrained, 2 found, 0 avoided, 0 deviating, 0 looping, 0 lost>`

So it seems that everything goes successfully.

I believe the caller object is very useful because it tries to explore all paths of a function. And it shows the result to me explicitly. However, setting proper parameters of the analyzed function seems to be tricky. Until now, I have not grasped how to specify parameters (symbolic or concrete) of any kinds (char, int, float, array, pointer etc) for a given function. Are there any documents about how to set parameters for the caller object or are there good examples?

**Comment by brokendragon** [comment]
The last post has problems in showing results
```
>>> print tuple(c.iter_returns())((<BV64 0x1>, <Path with 15 runs (at 0x400540)>), (<BV64 0x0>, <Path with 16 runs (at 0x400540)>))
>>> print c
<Explorer with paths: 0 active, 0 spilled, 0 deadended, 0 errored, 0 unconstrained, 2 found, 0 avoided, 0 deviating, 0 looping, 0 lost>

```

**Comment by rhelmot** [comment]
There is not, currently. The only way to do it easily right now is to use callable, which you're right about being insufficient for your job. There's been a weird amount of discussion about how to set function parameters today, so I think I'm going to pull the parameter-setting functionality out of callable and put it in a `call_state` that would go alongside `blank_state` and `entry_state`.

**Comment by kevinkoo001** [comment]
Hi, I am trying to set parameters with a ```call_state ``` with the latest ```angr``` (4.6.6.29), but it seems the arguments are not accepted in ```state_blank``` in a ```SimState``` class. I might be doing something wrong. If you have any example about how to use ```call_state``` with parameter setting, could you pinpoint it? Thanks!

```
  ...
  state = self.b.factory.call_state(addr=0x4005bd, args=['something'])
  File "/usr/local/lib/python2.7.11/lib/python2.7/site-packages/angr/factory.py", line 245, in call_state
    return self._project._simos.state_call(addr, *args, **kwargs)
  File "/usr/local/lib/python2.7.11/lib/python2.7/site-packages/angr/simos.py", line 272, in state_call
    state = self.state_blank(addr=addr, **kwargs)
  File "/usr/local/lib/python2.7.11/lib/python2.7/site-packages/angr/simos.py", line 459, in state_blank
    state = super(SimLinux, self).state_blank(**kwargs) #pylint:disable=invalid-name
  File "/usr/local/lib/python2.7.11/lib/python2.7/site-packages/angr/simos.py", line 210, in state_blank
    state = SimState(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'args'
```

**Comment by zardus** [comment]
I think `call_state` takes `*args` (as in, unpacked arguments, see: `http://www.saltycrane.com/blog/2008/01/how-to-use-args-and-kwargs-in-python/`). For example, try:

`state = self.b.factory.call_state(0x4005bd, 'something')`

**Comment by zardus** [comment]
Also, please open new issues for new questions rather than necroing an unrelated thread :-)
