### ISSUE TITLE
Exception: Not a valid binary file

### ISSUE THREAD

**Issue by EMC2SLN** [angr/angr#982]
I test Angr with my own test program, it's a simple program to print "Hello World" on the screen. And I use gcc to compile, but it doesn't work, and shows the error "Exception: Not a valid binary file"

**Comment by cq674350529** [comment]
Maybe you should attach your own program and angr analysis scripts.

**Comment by EMC2SLN** [comment]
project = angr.Project("~/test")
I haven't written my own script yet，but it should not make a mistake here at least. I test this with /usr/bin/ls, it works well. Why?

**Comment by cq674350529** [comment]
I just did a test, maybe `~` in binary path is not well handled by `angr`.  You can try relative path or absolute path instead of using `~` directly.  Here is why the error throwed：https://github.com/angr/angr/blob/master/angr/project.py#L122 。

**Comment by ltfish** [comment]
`~` (tilde) is a GNU-bash-specific syntax. This is not angr's fault. See [here](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html).

**Comment by cq674350529** [comment]
Year, the problem is related to `python`, not `angr`.

**Comment by EMC2SLN** [comment]
It's really due to the path. It's solved. Thank you.：)
