### ISSUE TITLE
Possibly argument of wrong type is used to initialize SimStruct

### ISSUE THREAD

**Issue by danse-macabre** [angr/angr#988]
According to the implementation of `SimStruct`, it seems that the `fields` attribute is expected to be an instance of `dict`. However, in at least the `glibc.py` module, there are lots of `SimStruct`s that are initialized with fields argument of type `list`, for example:

```python
# struct group * getgrnam (const char *NAME);
"getgrnam": SimTypeFunction([SimTypePointer(SimTypeChar(label=None), label=None, offset=0)], SimTypePointer(SimStruct([], name="group", pack=True), label=None, offset=0), label=None),
```

This could lead to a confusing "Can't fit value into a return value" error:

```python
Traceback (most recent call last):
  ...
  File "/home/user/angr/angr/sim_procedure.py", line 310, in ret
    arg_types=[False]*self.num_args if self.cc.args is None else None)
  File "/home/user/angr/angr/calling_conventions.py", line 556, in teardown_callsite
    self.set_return_val(state, return_val)
  File "/home/user/angr/angr/calling_conventions.py", line 608, in set_return_val
    raise ValueError("Can't fit value %s into a return value" % repr(val))
ValueError: Can't fit value <BV32 unconstrained_ret_getgrnam_387_32{UNINITIALIZED}> into a return value
```

The real cause of that problem is that the `SimType.fields` was initialized with a `list` instead of `dict`, hence the following code threw an AttributeError:

```python
class SimStruct(SimType):
    # ...
    def _with_arch(self, arch):
        if arch.name in self._arch_memo:
            return self._arch_memo[arch.name]

        out = SimStruct(None, name=self.name, pack=self._pack, align=self._align)
        out._arch = arch
        self._arch_memo[arch.name] = out
        # Next line will raise AttributeError("'list' object has no attribute 'iteritems'") in case
        # the self.fields were initialized with 'list' instead of 'dict'
        out.fields = OrderedDict((k, v.with_arch(arch)) for k, v in self.fields.iteritems())
        return out
```

Which will be later caught by:

```python
class ArgSession(object):
    # ...
        try:
            dbg.settrace('unconstrained_ret_getgrnam_387_32' in val.variables)
            betterval = self._standardize_value(val, ty, state, None)
        except AttributeError:
            raise ValueError("Can't fit value %s into a return value" % repr(val))
```

To this time, I was unable to fix it by myself, 'cause I'm not familiar with SimType at all. Or am I missing something?

**Comment by rhelmot** [comment]
Cosigned, this is definitely a bug. It's supposed to take an OrderedDict actually, though the overhead in using that is bad enough we should probably let it take a list of tuples as well. We should also probably use a less... blunt error checking mechanism there.

**Comment by danse-macabre** [comment]
@rhelmot 

> It looks like that's the error that'll show up when you're trying to return a floating point value but the CC can't.

This is the exact problem. I made the following quickfix:

```python
class SimCCARM(SimCC):
    ARG_REGS = [ 'r0', 'r1', 'r2', 'r3' ]
    # FIXME: Assume -mfloat-abi={soft|softfp}
    FP_ARG_REGS = [ 'r0', 'r1', 'r2', 'r3' ]
    FP_RETURN_VAL = SimRegArg('r0', 4)
    RETURN_ADDR = SimRegArg('lr', 4)
    RETURN_VAL = SimRegArg('r0', 4)
    ARCH = archinfo.ArchARM
```

**Comment by rhelmot** [comment]
yep... realistically each of the different possible setups should be different SimCC subclasses.

I pushed the s/[]/{}/ yesterday so I'm gonna close this issue.
