### ISSUE TITLE
SimProcedures for Android bionic libc (arm/arm64)

### ISSUE THREAD

**Issue by kevinis** [angr/angr#99]
I attempted to analyze a fauxware binary cross-compiled for Android. 
I copied simuvex/procedures/\__libc_start_main.py to \__libc__init.py, hoping the SimProcedures for glibc would work for Bionic libc.

`b = angr.Project('fauxware.arm.elf', load_options = {'auto_load_libs': False})`
`logging.getLogger('angr.analyses.cfg').setLevel(logging.DEBUG)`
` cfg = b.analyses.CFG(keep_state=True)`

Angr picked up the right SimProcedure for \__libc_init(), but the target address is not resolved correctly. Could anyone help me come up with the SimProcedures for Bionic Libc?

Here's part of the output:

DEBUG   | 2016-05-02 18:13:51,858 | angr.analyses.cfg | Basic block <SimIRSB 0x40038c> 0x40038c
DEBUG   | 2016-05-02 18:13:51,858 | angr.analyses.cfg | (Function _start of binary None)
DEBUG   | 2016-05-02 18:13:51,858 | angr.analyses.cfg | |    Call jump: True
DEBUG   | 2016-05-02 18:13:51,859 | angr.analyses.cfg | |    target: 0x400318 Appended [-] Ijk_Call
DEBUG   | 2016-05-02 18:13:51,859 | angr.analyses.cfg | |    target: 0x4003e8 Pended [Simulated Ret] Ijk_FakeRet
DEBUG   | 2016-05-02 18:13:51,859 | angr.analyses.cfg | 1 exits remaining, 1 exits pending.
DEBUG   | 2016-05-02 18:13:51,860 | angr.analyses.cfg | 1 unique basic blocks are analyzed so far.
DEBUG   | 2016-05-02 18:13:51,865 | angr.analyses.cfg | IRSB 0x400318 has an indirect jump as its default exit
DEBUG   | 2016-05-02 18:13:51,868 | angr.analyses.cfg | Basic block <SimIRSB 0x400318> 0x40038c->0x400318
DEBUG   | 2016-05-02 18:13:51,868 | angr.analyses.cfg | (Function None of binary None)
DEBUG   | 2016-05-02 18:13:51,868 | angr.analyses.cfg | |    Call jump: False
DEBUG   | 2016-05-02 18:13:51,869 | angr.analyses.cfg | |    target: 0x1000000 Appended [-] Ijk_Boring
DEBUG   | 2016-05-02 18:13:51,869 | angr.analyses.cfg | 1 exits remaining, 1 exits pending.
DEBUG   | 2016-05-02 18:13:51,869 | angr.analyses.cfg | 2 unique basic blocks are analyzed so far.
DEBUG   | 2016-05-02 18:13:52,103 | angr.analyses.cfg | Basic block <SimProcedure __libc_init> 0x40038c->0x400318
**DEBUG   | 2016-05-02 18:13:52,103 | angr.analyses.cfg | (Function None of binary None)
DEBUG   | 2016-05-02 18:13:52,104 | angr.analyses.cfg | |    Call jump: True
DEBUG   | 2016-05-02 18:13:52,104 | angr.analyses.cfg | |    target: 0x7ffeffd4 Appended [-] Ijk_Call
DEBUG   | 2016-05-02 18:13:52,104 | angr.analyses.cfg | |    target: 0x1000080 Pended [Simulated Ret] Ijk_FakeRet
DEBUG   | 2016-05-02 18:13:52,104 | angr.analyses.cfg | 1 exits remaining, 2 exits pending.
DEBUG   | 2016-05-02 18:13:52,105 | angr.analyses.cfg | 3 unique basic blocks are analyzed so far.
ERROR   | 2016-05-02 18:13:52,105 | angr.analyses.cfg | Caught an AngrError during CFG recovery at 0x7ffeffd4 (No section)**
Traceback (most recent call last):
  File "/home/yiming.j/Workspace/angr-dev/angr/angr/analyses/cfg_accurate.py", line 2268, in _get_simrun
    sim_run = self.project.factory.sim_run(current_entry.state, jumpkind=jumpkind)
  File "/home/yiming.j/Workspace/angr-dev/angr/angr/factory.py", line 131, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/home/yiming.j/Workspace/angr-dev/angr/angr/factory.py", line 71, in sim_block
    **block_opts)
  File "/home/yiming.j/Workspace/angr-dev/angr/angr/lifter.py", line 83, in lift
    raise AngrMemoryError("No bytes in memory for block starting at 0x%x." % addr)
AngrMemoryError: No bytes in memory for block starting at 0x7ffeffd4.

**Comment by rhelmot** [comment]
Looks like the bionic __libc_init uses a different prototype than glibc's __libc_start_main. https://github.com/android/platform_bionic/blob/bca25411b882abc6ab0bf07d25266ba9f8e4d398/libc/bionic/libc_init_dynamic.cpp#L92

You'll want to make a copy of __libc_start_main that uses those arguments instead. Look at the existing code for how to do things like load pointers from memory. If you need additional guidance on how to parse the "kernel argument block" you can look at how angr dumps those values into memory in the SimOS module (angr/angr/simos.py).

**Comment by kevinis** [comment]
I refactored __libc_start_main.py as __libc_init.py and updated the run() function according to Bionic's libc_init.dynamic.cpp.
    

    def run(self, raw_args, unused, slingshot, structors):
        self.main = slingshot;
        self.argc = self.state.memory.load(raw_args, self.state.arch.bits, endness=self.state.arch.memory_endness)
        # self.argv = ?
        # self.envp = ?
        self.call(self.main, (self.argc, self.argv, self.envp), 'after_slingshot')
    def after_slingshot(self, raw_args, unused, slingshot, structors, exit_addr=0):
        self.inline_call(simuvex.SimProcedures['libc.so']['exit'], 0)

After this SimProcedure is called, the parameters are as follows:  
raw_args is \<SAO \<BV64 0x7fffffffffeffd8\>\>
unused is \<SAO \<BV64 0x0\>\>
slingshot is \<SAO \<BV64 0x400894\>\>  (fauxware is PIC)
structors is \<SAO \<BV64 0x7fffffffffeffc0\>\>
self.argc is \<BV512 Reverse(0x0#448 .. Reverse(mem_7fffffffffeffd8_2_512)[63:0])\>

@rhelmot: could you please give me more hints about unpacking argc/argv/envp from raw_args?
Do the values of the parameters look correct? Thanks!

**Comment by kevinis** [comment]
This is the __libc_init.py that seems to work:

    import simuvex
    class __libc_init(simuvex.SimProcedure):
        ADDS_EXITS = True
        NO_RET = True
        local_vars = ('main', 'argc', 'argv', 'envp')

        def run(self, raw_args, unused, slingshot, structors):
            offset = self.state.arch.bits / 8 
            readlen = self.state.arch.bits / 8 
            endness = self.state.arch.memory_endness
            self.main = slingshot;
            self.argc = self.state.memory.load(raw_args + 0 * offset, readlen, endness=endness)
            argc_val = self.state.se.any_int(self.argc)
            self.argv = self.state.memory.load(raw_args + 1 * offset, readlen, endness=endness)
           self.envp= self.state.memory.load(raw_args + (1 + argc_val + 1) * offset, readlen, endness=endness)
            self.call(self.main, (self.argc, self.argv, self.envp), 'after_slingshot')

        def after_slingshot(self, raw_args, unused, slingshot, structors, exit_addr=0):
            self.inline_call(simuvex.SimProcedures['libc.so.6']['exit'], 0)
`

**Comment by rhelmot** [comment]
Awesome!! Do you want to submit a pull request adding this to simuvex?

**Comment by kevinis** [comment]
Absolutely. I'll submit the pull request until the fauxware example runs without problem.

I got another error. Any suggestions are welcome! 
/home/kevinis/angr-dev/claripy/claripy/ast/bv.pyc in BVV(value, size, **kwargs)
    152         if size is None:
    153             size = 8*len(value)
--> 154             value = int(value.encode('hex'), 16)
    155         elif size == len(value)*8:
    156             value = int(value.encode('hex'), 16)

ValueError: invalid literal for int() with base 16: ''
