### ISSUE TITLE
Question: Simulation manager only exploring active states

### ISSUE THREAD

**Issue by mor619dx** [angr/angr#991]
Hey,

So I'm trying to use the simulation manager to get to some specific branch using:
`simgr.explore(find=0x142B8)`

however it seems I am not able to reach that branch, after some testing using the step function I saw the branch is not showing on the successors stash but on the unsat stash (using state.unsat_successors)

I do however want to allow the simulation manager to reach to all the branches.

Is it possible to tell the simulation manager to go through all the branches, even unsat ones?

**Comment by mor619dx** [comment]
hmm I have added the LAZY_SOLVE flag like so:
`state = proj.factory.entry_state(addr=0x188C4, add_options={angr.options.LAZY_SOLVES})`
It doesn't make any changes, I still get 1 sat and 1 unsat.

this is the location it fails:
![ida1](https://user-images.githubusercontent.com/7024240/40054343-2cbe9aae-584d-11e8-9177-f8419469864e.PNG)
![ida2](https://user-images.githubusercontent.com/7024240/40054348-2eb9973c-584d-11e8-9394-fa7928e70c50.PNG)

It checks if vflag is 1, and vflag define in another c file (in the same binary - it is global variable)
and define as:
`extern volatile int vflag;`
in the function I run on.

Anything I can do to force it to run through those branches? because if I do it manually I can take the unsat branch and run on it but simulation manager only take the active ones

**Comment by rhelmot** [comment]
LAZY_SOLVES is supposed to do the trick. If you upload the binary and a test script I can take a look at it.

On the other hand, if there's some sort of specific thing that can't be worked around, this is exactly the sort of use case that Exploration Techniques are supposed to help with - you can write one to put all states in the active stash at all times :)
