### ISSUE TITLE
Question: Does CFGAccurate use parameter initial_state to resolve jump targets

### ISSUE THREAD

**Issue by jgaltidor** [angr/angr#993]
Does function `CFGAccurate` use parameter `initial_state` to resolve jump targets?  I get an incorrect CFG with respect to the initial program state that I pass in as a parameter.  I analyzed an x86-64 bit binary compiled to run on Ubuntu 16.04 LTS.  I am using version `7.8.2.21` of ANGR.

I used CFGAccurate to generate the CFG for an x86-64 bit binary version of a small assembly program `main.s`.  The entire `main.s` is listed below:

 ```
 BITS 64
        section .text
        global _start
_start: mov r9, _start          ; store the address _start
        sub r9, nxt2            ; compute the difference between _start and nxt2
        mov r10, nxt2           ; store the address nxt2
        cmp r11, 0x11           ; compare an unknown input to 0x11
        je nxt2                 ; if they are equal, jump to nxt2
        add r10, r9             ; otherwise, add R9 to the address in R10
        jmp nxt2                ; and jump to nxt3

nxt2:   jmp r10                 ; jump to the address in R10
```

If register r11 is equal to 0x11, then when the program reaches block nxt2, r10 is equal to the memory address of block nxt2.  If register r11 is *not* equal to 0x11, then when the program reaches block nxt2, r10 is equal to the memory address of block _start.  Therefore, if r11 is equal to 0x12, a value different than 0x11, then the last instruction in the program `jmp r10` should cause a jump to block _start.

In the ANGR script, I created a blank state, set register r11 to 0x12 in that state, and then used this state as the initial_state parameter in the call to CFGAccurate.  CFGAccurate computes a CFG where block nxt2 only has one edge coming out of it that loops back to itself.  I have attached a PNG image file of the generated CFG.
![main_cfg](https://user-images.githubusercontent.com/10366424/40132849-e21964d8-590b-11e8-8d9e-487acc1e0f36.png)

In the generated CFG, I expected an edge from block nxt2 to block _start because r11=0x12 in the initial state.  The ANGR script is short and listed below:

```python
import angr
import claripy
import angrutils

prj = angr.Project('main')

_start = prj.loader.main_object.get_symbol("_start")
nxt2 = prj.loader.main_object.get_symbol("nxt2")

print 'Address of symbol _start:', hex(_start.linked_addr)
print 'Address of symbol nxt2:', hex(nxt2.linked_addr)

start_state = prj.factory.blank_state()
start_state.regs.r11 = claripy.BVV(0x12, 64)

cfg = prj.analyses.CFGAccurate(starts=[_start.linked_addr], initial_state=start_state, keep_state=True, normalize=True)

# Writing CFG plot of binary main to file main_cfg.png
angrutils.plot_cfg(cfg, "main_cfg", asminst=True, remove_imports=True, remove_path_terminator=True)

# Symbolically executing main
sm = prj.factory.simgr(start_state)
sm.explore(find=nxt2.linked_addr)
s = sm.found[0]

print 'Possibles values of R10 when execution reaches nxt2:'
print '  R10:', map(hex, s.se.eval_upto(s.regs.r10, 3))
# Last statement will print "R10: ['0x4000e0L']"
# 0x4000e0 is the address of block _start in the resolved assembly
```

I compiled `main.s` to x86-64 binary file `main` using the following commands:

    nasm -f elf64 -o main.o main.s
    gcc -nostdlib -o main main.o

**Comment by ltfish** [comment]
> Does function CFGAccurate use parameter initial_state to resolve jump targets?

It does! But in this specific case, I suspect that the reason that it fails to calculate the indirect jump is because `CFGAccurate` is *not* path sensitive, which means it will only try to resolve the target of `jmp r10` at `nxt2` **once**, only following one of all possible execution paths leading there in the current function.

**Comment by jgaltidor** [comment]
Thanks for the response and informing me that CFGAccurate is *not* path sensitive.  After first, I thought that not being path sensitive would still allow the analysis to infer the correct jump.  I was assuming that because (1) R11 is never modified and (2) the initial state sets R11 to 0x12, then the CFG analysis would infer that only one branch from the conditional jump (right after `cmp R11, 0x11`) is possible.  This would require that the analysis knows `R11 is never modified`, which is probably out of scope for a CFG analysis.

**Comment by ltfish** [comment]
You are right. I just want to mention that in `CFGAccurate`, at every conditional branch point, all branches will be taken in an _non-derministic_ order, regardless of the satisfiability of each branch. Therefore, regardless of whether `r11` equals to `0x11` or `0x12` in the initial state, you will see one of the following possibility: a) `nxt2` branching to itself, or b) `nxt2` branching to `_start`.

`CFGAccurate` will definitely use values in the initial state to resolve indirect jumps. For example, if you have `jmp r11` somewhere, you will see a branch from that instruction to a new block whose address is the value of `r11` in your initial state.
